### ISSUE TITLE
uuid dependency needs bumping to ^3.0.1

### ISSUE THREAD

**Issue by sparkiegeek** [airbnb/enzyme#1000]
In d34630e9c3e07ca7983d37695d5668377f94a793 the dependency on `uuid` was bumped to `^3.0.0` but unfortunately `uuid` 3.0.0 does not support the API used (it was only in 3.0.1 that `uuid/v4` came into existence - see [node-uuid/HISTORY.md](https://github.com/kelektiv/node-uuid/blob/master/HISTORY.md#301-2016-11-28) and https://github.com/kelektiv/node-uuid/issues/154). 

If an application has `uuid` 3.0.0 pinned via `npm shrinkwrap` or similar, then enzyme will happily install, but then break.

**Comment by ljharb** [comment]
Fixed in #1001.
