### ISSUE TITLE
Configuration: using Enzyme with Jest/TypeScript

### ISSUE THREAD

**Issue by canhtrinh** [airbnb/enzyme#1003]
What are the configuration settings needed to get Enzyme to work properly with test written in .ts files? I'm using Jest as my runner, and ts-jest as its transform tool (vs. babel-jest). I installed @types/enzyme, but not sure if there's additional configuration required. 

Encountering the following issue, possibly because Enzyme isn't configured properly within my .ts files: 

Unexpected token (10:58)
10 |               wrapper = enzyme_1.shallow(__assign({}, props) />);
                                                                                                   ^

**Comment by ljharb** [comment]
This isn't an issue with enzyme itself; it looks like something with jest and ts-jest. Please file an issue there.
