### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rashsinha22** [airbnb/enzyme#1005]
.

**Comment by ljharb** [comment]
Is material-ui react? enzyme only works with React.

**Comment by rashsinha22** [comment]
Its material design using react.

**Comment by ljharb** [comment]
So, if I understand correctly, you're trying to test the browser itself by simulating events; instead, I'd assert on the props passed to things, and then *call those props directly*, and make assertions based on that behavior.

In other words, I'd suggest avoiding `simulate` entirely.

**Comment by ljharb** [comment]
Not sure why everything was zeroed out; closing.
