### ISSUE TITLE
Mounting Produces different Component Prop State than Shallowing

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1006]
So I know that shallow allows you to isolate testing behavior of the component (and not its children).  And that mounting renders the entire tree (parent and children, and its children,  lifecycle methods on each, and so on).

But I don't understand what is exactly going on here:

```jsx
it('stores the session and token on login', async () => {
        store = initStore()
        const loginContainer = shallow(<LoginContainer store={store} />)
        await loginContainer.find('LoginContainer').props().authenticate(fakeEmail, fakePassword)

        const { isAuthenticated, isAuthenticating, token, session } = loginContainer.find('LoginContainer').props()

        expect(isAuthenticating).to.be.false
        expect(isAuthenticated).to.be.true
        expect(session).to.equal(fakeSession)
        expect(token).to.equal(fakeToken)
})
```
If I `mount` it, then both **isAuthenticating** and **isAuthenticated** result in **_false_**
If I `shallow` it, then **isAuthenticating** is set to **_false_** and **isAuthenticated** is set to **_true_**

Notice I'm calling authenticate() by getting at it via the props of the mounted or shallowed container. 

**LoginContainer**

```jsx
export const mapDispatchToProps = {
  authenticate: AsyncActions.authenticate
}
```

so by calling `authenticate()` via my container's props(), it's simply calling my thunk action here:

```jsx
export function authenticate(email, password) {
  return async (dispatch) => {
    dispatch(AuthActions.requestAuthentication())
    try {
      const response = await AuthApi.Authenticate(email, password),
        session = response.body.data[0].session,
        token = response.body.data[0].token
      if(token){
        dispatch(AuthActions.authenticated(session, token))
      }
    } catch (err) {
      console.log(`failed request: $(err.status) /n $(err) `)
    }
  }
}
```

And the reducer:

```jsx
export const initialState = {
  isAuthenticating: false,
  isAuthenticated: false,
  token: null
}

export default function authReducer(state = initialState, action) {
  switch (action.type) {
    case ActionTypes.REQUEST_AUTHENTICATION: {
      return {...state,
        isAuthenticating: true,
        isAuthenticated: false }
      }
    case ActionTypes.AUTHENTICATED: {
      console.log('ActionTypes.AUTHENTICATED hit')
        return {...state,
          isAuthenticating: false,
          isAuthenticated: true,
          session: action.session,
          token: action.token
        }
    }
    case ActionTypes.UNAUTHENTICATED: {
      return {...state,
        isAuthenticating: false,
        isAuthenticated: false,
        token: null }
      }
    default:
      return state
  }
}
```

Can someone explain what's going on here?

**Comment by ljharb** [comment]
I believe this is an intentional part of enzyme's API design.

`shallow(<Foo />)` is not a Foo, it's "what Foo renders" - `.props()`, `.is()`, and `.children()` can verify this.
`mount(<Foo />)` is a Foo - `.props()`, `.is()`, and `.children()` should also verify this.

**Comment by dschinkel** [comment]
ok thanks. Hmm ok weird.  I've been having trouble with shallow vs mount because for some reason this test:

```
it('dispatches unauthenticate action', async () => {
          console.log('dispatches unauthenticate action')
          const unauthenticate = await AsyncActions.unauthenticate()
          await unauthenticate(dispatch)
          console.log(store.getState().auth.isAuthenticating)
          console.log(store.getState().auth.isAuthenticated)
          expect(dispatch.calledWith(Actions.unauthenticated())).to.be.true
 })
```

is somehow oddly preventing this test below which doesn't even live in the spec file of the the test that's failing (below)  from passing because for some reason if I run the test above my authenticated() dispatch isn't firing after my test below runs:

```
export function authenticate(email, password) {
  return async (dispatch) => {
    dispatch(AuthActions.requestAuthentication())
    try {
      const response = await AuthApi.Authenticate(email, password),
        session = response.body.data[0].session,
        token = response.body.data[0].token
      if(token){
        dispatch(AuthActions.authenticated(session, token))
      }
    } catch (err) {
      console.log(`failed request: $(err.status) /n $(err) `)
    }
  }
}

export function unauthenticate(){
  return async (dispatch) => {
    dispatch(AuthActions.unauthenticated())
  }
}
```

**Comment by dschinkel** [comment]
it's so bizarre....

**Comment by ljharb** [comment]
(btw, if you add `jsx` after the triple backticks, you'll get nicer syntax highlighting)

**Comment by ljharb** [comment]
Since you're using a flux store, it's highly likely that you're not emptying it out after every test. Alternatively, since your tests are synchronous but your mocked ajax thing is probably returning async, it's probably happening *after* the first test is finished.

In other words, you may need to save the mocked promise, and return a chain off of it in your test, so that your test is async.

**Comment by dschinkel** [comment]
I'm actually using react-redux connected containers...

**Comment by dschinkel** [comment]
>since your tests are synchronous

but both tests have async on the function...

**Comment by ljharb** [comment]
yes, both tests are `async function`s, which means they return a promise, but nothing inside that function is dependent on any other promise, so it's still not really async :-)

Yes, I'm saying that `nock` might be resolving after your test is completed.

**Comment by dschinkel** [comment]
ah yea nock may resolve in between the first test completing (reducer is hit test is happy) and the second test running

First test => reducer hit = > expect passes = > nocked request may still be long running
Second test runs while first nock still long running  =>  `dispatch(AuthActions.requestAuthentication())` called, expects() run and fail => nock returns so this is never run:

```jsx
if(token){
        dispatch(AuthActions.authenticated(session, token))
      }
```

**Comment by dschinkel** [comment]
ok I did a couple things, it's working now:

1) took nock out of the beforeEach so that my first test would not run nock. It doesn't need nock anyway, my thunk action for that one is not asnc anyway

looks like having nock in beforeEach isn't such a good idea

**Comment by dschinkel** [comment]
thanks for the help, appreciate it.
