### ISSUE TITLE
React router context type: "child context type is invalid; it must be a function"

### ISSUE THREAD

**Issue by andersonjb** [airbnb/enzyme#1010]
Working on a JEST test for a component that uses react-router. I'm using enzyme to mount() the component for testing. The component only calls router's push function (this.context.router.push).

Passing router context with context and childContextTypes as mount options. When I run my test I get:

`"child context type 'router' is invalid: it must be a function, usually from React.PropTypes"`

Per console logs, I confirmed contextType of router is object (not function). The component itself works fine in the browser, and does not throw any console warnings or errors. I should be able to pass a simple object, like here

`https://stackoverflow.com/questions/36143925/react-js-how-to-mock-context-when-testing-component`

Why am I getting the warning that it must be a function?

**Comment by ljharb** [comment]
`contextTypes` values, and `propTypes` values, must be validator functions. It's possible that React ignores non-function propTypes/contextTypes, but that doesn't mean it's correct, or actually checking anything.
