### ISSUE TITLE
Redux Provider and set context

### ISSUE THREAD

**Issue by heinhoang** [airbnb/enzyme#1013]
I have a component with context, I test like this:
```js
const context = {a: "b"};
mount(<Login />, context);
```
it works.
but I wrap by Provider. It not work:
```js
import configureStore from 'redux-mock-store';
const context = {a: "b"};
const store = mockStore();
mount(<Provider store={store}><Login /></Provider>, context);
```
How to fix

**Comment by ljharb** [comment]
Generally Providers provide context; so they'd ignore the context you set in mount.

**Comment by ljharb** [comment]
#664 should address this, along with #1960.
