### ISSUE TITLE
shallow.md line 46 'componentWillMount' should be 'componentDidMount'

### ISSUE THREAD

**Issue by niurui397** [airbnb/enzyme#1015]
In ShallowWrapper-spec.jsx line 2766, when disableLifecycleMethods is set to true, componentWillMount is expected to be called, componentDidMount was the one not getting called. This contradict what's in shallow.md. I found this issue when I was using disableLifecycleMethods option and componentWillMount() always fires.

**Comment by ljharb** [comment]
Indeed, `componentWillMount` should always fire, and `componentDidMount` is the one controlled by the option: https://github.com/airbnb/enzyme/blob/91bf86183b08337a45c2415e89868ea46fae81c3/src/ShallowWrapper.js#L128-L132

A PR to fix the docs would be great.

**Comment by niurui397** [comment]
Pull request is created. Simple text change in shallow.md is all that's needed I think. 
https://github.com/airbnb/enzyme/pull/1016

**Comment by ljharb** [comment]
Fixed in #1016.
