### ISSUE TITLE
ERROR in ./~/enzyme/build/Utils.js Error: Can't resolve 'uuid/v4'

### ISSUE THREAD

**Issue by brendonco** [airbnb/enzyme#1017]
Anyone know about this error thrown in windows Jenkins. I tried on MAC machine but have no problem running the unit test. I'm using karma + enzyme + jasmine.

my webpack config called from karma config.

```
externals: {
    "react/addons": true,
    jsdom: "window",
    cheerio: "window",
    "react/lib/ExecutionEnvironment": true,
    "react/lib/ReactContext": "window",
  },
```

**Comment by brendonco** [comment]
Looks like need to clean up node_modules and did npm install again. Can close this one.

**Comment by ljharb** [comment]
Does `npm ls` exit successfully? `npm install` may help.

**Comment by maor-snunit** [comment]
having the same problem here.. 
updated now to enzyme 2.8.4 and still not working.

**Comment by ljharb** [comment]
@maor-snunit same [question](https://github.com/airbnb/enzyme/issues/1017#issuecomment-312311777) to you?

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.
