### ISSUE TITLE
prop always null even though reducer is hit

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1024]
this one is really stumping me.  When I debug it, the correct case statement in my reducer that I expect to be hit by the allUsers thunk action call is definitely being hit, thus updates state but for some reason, this.props.users is always null after my connected component is done calling that thunk action:

```
it('passes a list of users as props to users child', async () => {
        const fakeToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
          userList = [{firstName: 'Dave', lastName: 'Schinkel' }],
          responseBody = { data: userList }

        await mockGet('/users', responseBody)

        const usersContainer = shallow(<UsersContainer store={store} />),
          containerProps = usersContainer.find('UsersContainer').props(),
          userProps = usersContainer.dive().find('.ft-users').props.users

        await usersContainer.find('UsersContainer').props().allUsers(fakeToken)

        expect(userProps).to.deep.equal(userList[0])
 })

```
I don't see a problem with my enzyme do you???

**UsersContainer**

```
import { connect } from 'react-redux'
import React, { Component } from 'react'
import * as UserAsyncActions from '../actions/Users/UserAsyncActions'
import Users from '../components/Users'

class UsersContainer extends Component {

  render(){
    console.log(`this.props.users: ${this.props.users}`)
    return (<Users className='ft-users' users={this.props.users} />)
  }
}
export const mapStateToProps = state => ({
  isRequestingAllUsers: state.user.isRequestingAllUsers,
  users: state.user.users
})

export const mapDispatchToProps = {
  allUsers: UserAsyncActions.allUsers
}

export { Users }
export default connect(mapStateToProps, mapDispatchToProps)(UsersContainer)
```

**Comment by ljharb** [comment]
You should be using `.dive()` instead of `.find('UsersContainer')` in all cases. If you make that change and update the code above, what happens?

**Comment by dschinkel** [comment]
I tried ` containerProps = usersContainer.dive().props().users`

and get `usersContainer.dive(...).props(...).allUsers is not a function`

**Comment by ljharb** [comment]
Where does `mockGet` provide the data to the store?

**Comment by dschinkel** [comment]
indirectly.  So here's the flow:

container.allUsers () => allUsers() thunk action makes an api call (which mockGet which is just nock) intercepts.  Once the API call returns, I dispatch another action with the data => reducer gets that data and updates users in state

That all works fine, I can actually confirm that the nock call is working.  

So after the reducer updates state, I'd expect that my container component would be re-rendered or something like that, to where mapDispatchToProps would be ru-run and state is updated therefore this.props.users should have a value in the container

**Comment by ljharb** [comment]
Ah - enzyme won't automatically rerender after state is updated. You'll need to explicitly call `wrapper.forceUpdate()`, iirc.

**Comment by dschinkel** [comment]
I tried this

```
await usersContainer.find('UsersContainer').props().allUsers(fakeToken)
usersContainer.forceUpdate()
```

and got `usersContainer.forceUpdate is not a function`

**Comment by ljharb** [comment]
sorry, forgot the API - it's just [`.update()`](http://airbnb.io/enzyme/docs/api/ShallowWrapper/update.html)

**Comment by dschinkel** [comment]
so tried this, but users is still null so assert still fails

```
await usersContainer.find('UsersContainer').props().allUsers(fakeToken)
usersContainer.update()
```

**Comment by dschinkel** [comment]
Just some more context here, not that it's necessarily going to matter..I know that the console.logs are being hit below for sure:

**UserReducer**
```
import ActionTypes from '../../../src/client/actions/ActionTypes'

export const initialState = {
  isRequestingAllUsers: false,
  usersReceived: false,
  users: null
}
export default function userReducer(state = initialState, action){
  switch (action.type) {
    case ActionTypes.users.REQUEST_ALL_USERS:
      console.log('REDUCER HIT for ActionTypes.users.REQUEST_ALL_USERS ')
      return {...state,
        isRequestingAllUsers: true
      }
    case ActionTypes.users.USERS_RECEIVED:
      console.log('REDUCER HIT for ActionTypes.users.USERS_RECEIVED: ')
      console.log(`action.users: ${action.users}`)
      return {...state,
        isRequestingAllUsers: false,
        usersReceived: true,
        users: action.users
      }
      default:
        return state
  }
}
```

**Reducers**
```
import { combineReducers } from 'redux'

import authReducer from './AuthReducer'
import userReducer from './UserReducer'

export default combineReducers({
  auth: authReducer,
  user: userReducer
})
```

**Comment by jwbay** [comment]
I see what looks like a couple off things here, commented inline

```js
userProps = usersContainer.dive().find('.ft-users').props.users // 1. this should be props().users

await usersContainer.find('UsersContainer').props().allUsers(fakeToken)

expect(userProps).to.deep.equal(userList[0]) // 2. userProps is probably stale at this point -- should be accessed from usersContainer *after* the call has completed
```

**Comment by dschinkel** [comment]
update never worked for me :(
