### ISSUE TITLE
mount() correctly renders when component under test uses React.createClass but does shallow render when only createClass

### ISSUE THREAD

**Issue by CervantesVive** [airbnb/enzyme#1029]
Migrated my code base from soon to be deprecated `React.createClass` to package `create-react-class` and a series of tests started failing.

Seems that `mount` is doing a shallow render when I switched to package `create-react-class`.

I see the same behavior if instead of

```
const MyComponent = React.createClass({});
```

I do:

```
import React, { createClass } from 'react';

const MyComponent = createClass({});
```

Seems it might be context related?
Is there some additional work to be done to use `create-react-class` or do I need to truly migrate to classes?

**Comment by ljharb** [comment]
1) You should be importing with `import createClass from 'create-react-class'`, *not* from `React`
2) yes, you should truly migrate to classes, as of React 0.14.

**Comment by CervantesVive** [comment]
> You should be importing with import createClass from 'create-react-class', not from React

Sorry, I must not have explained myself correctly.

I was illustrating that the exact problem occurs whether I use `createReactClass` from package `create-react-class`, or whether I use `createClass` from object `React`.

If I use `React.createClass` (calling from context) then `mount` works as expected.

This is only a problem during tests though, the production app works as expected.

> yes, you should truly migrate to classes, as of React 0.14.

We have hundreds (thousand?) units at work. My intents was that a staged approach using `create-react-class` would be suitable. Sounds like to continue using enzyme we might be forced to though. If so then something to note in the docs/FAQ/common-issues

**Comment by ljharb** [comment]
Hmm, this is strange - specifically that `React.createClass` would work but `{ createClass } = React` would not? What babel settings are you using? What version of React are you using with enzyme?

(fwiw, you can use codemods to migrate createClass instances to class-based instances pretty trivially; i think it covers everything except complex mixins - at airbnb we converted thousands of components very quickly this way)

**Comment by CervantesVive** [comment]
Thank you for your reply @ljharb . It is a strange problem that is puzzling me.

I uploaded a reduced example of the issue to https://github.com/CervantesVive/test-example

If you checkout the project then do `yarn && yarn run test` the test passes.

If you edit the file `test-example/src/components/Overlay/OverlayAnchor.jsx` so that the definition uses `{ createClass } = React` or `createReactClass`  then rerun `yarn run test` then it will fail.

I reduced the code though not the deps so a lot of unused deps will get pulled down.

**Comment by ljharb** [comment]
(note that "0.1" isn't a valid semver version; i had to edit it to 0.1.0)

I can definitely reproduce this with your repo.

However, when I fully uninstall `create-react-class`, and switch it so *both* components in that repo use the same method, the `createClass` version starts working.

Similarly, when I make all of them use `create-react-class`, it works too.

So, it seems the issue is that you have to migrate *every single React.createClass component* over to `create-react-class` at once, and it works fine.

**Comment by ljharb** [comment]
@CervantesVive I'm saying that if `create-react-class` *even exists on disk*, then everything in your codebase must be using it. You need to fully uninstall it if you want to test out another method.

**Comment by CervantesVive** [comment]
@ljharb Either I am misunderstanding something or we are talking past each other.

My use case is that I only use`create-react-class` . Per my previous comment, if [OverlayAnchor.jsx](https://github.com/CervantesVive/test-example/blob/master/src/components/Overlay/OverlayAnchor.jsx#L7) is edited to use `create-react-class` then no other method will be in use in the example and the test will fail.

If the example is edited to use `React.createClass` _everywhere_ (3 locations) the test will pass.

Used code-mod on the actual code base like you suggested earlier and surprise, it falls back to `react-create-class` under various cases so the test failures persist.

**Comment by ljharb** [comment]
When I used your test repo, and changed everything to use `create-react-class`, everything passed - so it seems like the issue is now that I can't reproduce your failure.
