### ISSUE TITLE
How to check if my nth node of a span tag has class="cusboard-circle-amt"

### ISSUE THREAD

**Issue by PavanRaj999** [airbnb/enzyme#1032]
I need some code like the below to identify if my tab component is rendered with cusboard-circle-amt class in it. ( Some Nth node in the element has particular class)

My test case looks like below , which is not working. i need some equivalent code.
```jsx
it('If the currency value is zero, circular component should not display any text', () => {
    const wrapper = mount(<Tab {...props} />)
    expect(wrapper.find('#tab-data-pane-0').at(2).hasClass('cusboard-circle-amt')).toBe(true)
  })
```
i am getting error saying -------> Method “hasClass” is only meant to be run on a single node. 0 found instead.

And My HTML is as below
```html
<div id="tab-data-pane-0" aria-labelledby="tab-data-tab-0" role="tabpanel" aria-hidden="false" class="tab-pane active">
<button class="dashboard-circle"><span class="dashboard-circle-number" data-test="dashboard-circleNumber">51</span><span class="cusboard-circle-amt" data-test="cusboard-circle-amt"><span>$16</span></span><span class="dashboard-circle-name" data-test="dashboard-circleTitle"></span></button>
</div>
```

Any help would be very much appreciated :)

**Comment by ljharb** [comment]
`wrapper.find('#tab-data-pane-0')` gives you a wrapper around the only element with that ID, your div. `.at(2)` selects the 3rd item from a collection of 1 - which means that `.hasClass` is called on an empty collection.

I would expect that removing the `.at(2)` fixes your problem.

**Comment by PavanRaj999** [comment]
As you said , wrapper.find('#tab-data-pane-0') as gives wrapper around the only element with that ID. I need to go down to two to three levels down from that ID to check if I have my expected class in it. not able to travers down after having wrapper.find('#tab-data-pane-0').

**Comment by ljharb** [comment]
How about `expect(wrapper.find('#tab-data-pane-0').find('.cusboard-circle-amt')).to.have.lengthOf(1)`?

**Comment by PavanRaj999** [comment]
It worked. Thanks a lot Jordan Harband. You saved me 👍
