### ISSUE TITLE
Testing functional components

### ISSUE THREAD

**Issue by rizvified** [airbnb/enzyme#1034]
_Apologies if this is a duplicate_

I am having trouble figuring out how to test function expressions (equivalent of component methods in a react class) in functional components?
```
const someFunc = ({someValue}) => {
 const someCalc = () => {
   ...
   return result
   }
 return <div>{someCalc}</div>
}
```
How would we test the someCalc() here?

**Comment by ljharb** [comment]
You can't. Closure privacy is the only true privacy JS has, and private things shouldn't be tested.

You certainly can and should make assertions on the children of the element your component renders - but that's all you can do.

(Separately, component names need to start with a capital letter - ie. SomeFunc, not someFunc)
