### ISSUE TITLE
.exists() returns true when using the component that returns null

### ISSUE THREAD

**Issue by blackpost38** [airbnb/enzyme#1037]
`.exists()` returns `true` when using the component that returns `null`

I think if the component returns `null`, `.exists()` has to be `false` because It's empty.

```js
const enzymeWrapper = mount(<NullComponent />)
expect(enzymeWrapper.exists()).toBe(false)  // fail!
```

**Comment by ljharb** [comment]
This is a tricky one; the contract for "exists" is "has nodes". `null` is technically a node.

**Comment by blackpost38** [comment]
Oh, It's clear! I got it.
