### ISSUE TITLE
Mounting with jsdom on tape-based testing frameworks

### ISSUE THREAD

**Issue by pheuter** [airbnb/enzyme#104]
I'm currently using [ava](https://github.com/sindresorhus/ava) to execute unit tests, and it's based on the tape system. From what I gathered, enzyme requires `describe` to exist in order to do full jdsom mounting, and that's not a construct available in ava.

Just wondering if there's currently a workaround or perhaps plans to support this in the future.

Thanks!

**Comment by ljharb** [comment]
We're planning on removing the mocha-specific parts from enzyme for v2.0. Related: #73 #60

**Comment by jackfranklin** [comment]
@pheuter I was able to use Enzyme with Tape - demonstrated in this article: http://12devsofxmas.co.uk/2015/12/day-2-testing-react-applications/, along with the sample repo: https://github.com/jackfranklin/todo-react-testing

**Comment by fraserxu** [comment]
I also made this recipes using tape with enzyme https://github.com/fraserxu/react-testing-recipes
