### ISSUE TITLE
Simulate('change') on select does not increase func coverage

### ISSUE THREAD

**Issue by nikini** [airbnb/enzyme#1040]
I've got a component with a select inside it 

    <select onChange={this.handleChange}>
		{this.props.options.map(this.renderOption)}
	</select>

and the following function

    handleChange(e) {
		const element = e.target;
		this.props.onChange.call(null, e, {
			value: element.value,
			label: element.options[element.selectedIndex].textContent,
		});
	}

I'm wrote a test in **Jest** and **Enzyme**, like this: 

    const onChange = jest.fn();
    // ....
    component.find('select').simulate('change');
	expect(onChange).toHaveBeenCalled();

The problem is that my **% Funcs** coverage is at **83.33%** for this test because it thinks that the `handleChange` function is not being called. All the other coverages (% Stmts, % Branch, % Lines) are at 100%, except for this one. Seems like it is an **Enzyme bug**.

I tried writing a dummy test where I would call `handleChange` manually and the coverage goes to 100%. So, it's definitely something to do with the simulate.

**So, to clarify:** The `handleChange` function is being called, the test works. The problem is that the coverage doesn't count that the function is being called.

**Comment by ljharb** [comment]
Coverage issues can't ever be a bug with real code, they're always a coverage lib bug. `.simulate` goes through React internals, so the coverage lib probably isn't instrumenting that.

Regardless, I wouldn't recommend using `simulate` - it's better to invoke the prop directly.

**Comment by nikini** [comment]
Seems to me like an enzyme bug because I have another test for another component and there I do `simulate('click')` and it works.
Anyway, but calling the function manually would imply that I have to create an event object with the properties that I know I used. But, maybe in browser environment the event object doesn't have all those properties, and that's why `simulate` would be better, or so I think. Am I wrong?

**Comment by ljharb** [comment]
`simulate` doesn't create a fake event object - http://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html

**Comment by nikini** [comment]
But still, calling simulate does create an event object. I mean, the test works and within the callback I do use some properties from the event object.

**Comment by nikini** [comment]
Never mind. I checked the facebook react utils code and there is an object being passed, but it only has the target and the type. Inspecting on why it's working for me.
Anyway, you suggest I call the function manually and not use simulate? But then, what's the point of simulate?

**Comment by nikini** [comment]
I found out why.

```
SelectComponent.defaultProps = {
	options: [],
	onChange: () => {},
};
```
It was because of the default property function.
