### ISSUE TITLE
add support to specify max level to shallow/mount

### ISSUE THREAD

**Issue by dalimian** [airbnb/enzyme#1042]
shallow is one level deep vs mount is unlimited level deep, I wanted something in between - to be able to specify max level
can we add support to pass options.level to shallow/mount - e.g.
`shallow(<MyCompoent />, {level: 2})`

**Comment by ljharb** [comment]
That's not something that's possible with `shallow` or `mount`.

It will be possible after #1007; but it wouldn't be with a number level (which is brittle), it'd be by defining certain nodes as additional "leaves" that should not be dived into.

**Comment by dalimian** [comment]
thanks, take your word, though curious as to why it wouldn't be possible now with shallow.

Agree taking a black list of nodes is more robust than taking a number.

**Comment by dalimian** [comment]
and is there a plan to do it, or would u guys take a PL

**Comment by ljharb** [comment]
`shallow` calls into react-test-renderer's shallow method, which doesn't allow for changing leaf nodes.

**Comment by dalimian** [comment]
thanks. is there an open issue?

**Comment by ljharb** [comment]
#250

**Comment by lfelipequiros** [comment]
I know is useless for components inside the wrapper component, but for cases like this one may be useful for someone to shallow inside a shallow.

`shallow(
      <WrapperComponent /'>
        { shallow(<Component {...props}/>) }
      </WrapperComponent >);
  }); `

**Comment by ljharb** [comment]
@lfelipequiros i'm relatively sure that wouldn't work; but you might want:
```jsx
shallow(
      <WrapperComponent >
        <Component {...props} />
      </WrapperComponent>;
);
```
?

**Comment by lfelipequiros** [comment]
@ljharb  Why are you relatively sure ? maybe im missing something, but im seeing it working fine . . . 
Checking the coverage it is actually doing what i expect, and doesn´t even throw a warning or something like that. 

Now that im giving it a closer look maybe is just parsing that shallow object to a unused param inside the wrapper component. 

I'll run a couple of test, if i can provide more context on this, i'll come back : )

**Comment by ljharb** [comment]
An enzyme wrapper isn’t a node; React is probably converting it to a string implicitly.

**Comment by HamidTanhaei** [comment]
@lfelipequiros @ljharb 
using shallow() inside a component totally works fine.
```
it('should render Redirect on userToken doe`s not exists', () => {
    const wrapper = shallow(<Router>{shallow(<PrivateRoute />)}</Router>);
    expect(shallow(wrapper.find(Route).props().render())).toMatchSnapshot();
  });
```

**Comment by ljharb** [comment]
@HamidTanhaei that would fail if the children propType was defined as PropTypes.node.

**Comment by udayrajMT** [comment]
Just putting a link to docs for dive()  https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/dive.html
