### ISSUE TITLE
Cannot resolve 'react-addons-test-utils' in '...\enzyme\build'

### ISSUE THREAD

**Issue by artin-phares** [airbnb/enzyme#1047]
Similar to  #891

```
ERROR in ./node_modules/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react-addons-test-utils'
```
---------------
<details>  
  <summary>full error (click to expand)</summary>  

ERROR in ./node_modules/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/addons' in 'D:\Projects\pvc\node_modules\enzyme\build'
 @ ./node_modules/enzyme/build/react-compat.js 40:14-37 41:44-67
 @ ./node_modules/enzyme/build/ReactWrapper.js
 @ ./node_modules/enzyme/build/index.js
 @ ./test/unit/tests/client/components/App.test.js
 @ ./test/unit/tests/client/components/index.js
 @ ./test/unit/tests/client/index.js
 @ ./test/unit/tests/index.js
 @ ./test/unit/entry.js

ERROR in ./node_modules/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react-addons-test-utils' in 'D:\Projects\pvc\node_modules\enzyme\build'
 @ ./node_modules/enzyme/build/react-compat.js 137:18-52
 @ ./node_modules/enzyme/build/ReactWrapper.js
 @ ./node_modules/enzyme/build/index.js
 @ ./test/unit/tests/client/components/App.test.js
 @ ./test/unit/tests/client/components/index.js
 @ ./test/unit/tests/client/index.js
 @ ./test/unit/tests/index.js
 @ ./test/unit/entry.js

ERROR in ./node_modules/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/lib/ReactContext' in 'D:\Projects\pvc\node_modules\enzyme\build'
 @ ./node_modules/enzyme/build/react-compat.js 42:21-54
 @ ./node_modules/enzyme/build/ReactWrapper.js
 @ ./node_modules/enzyme/build/index.js
 @ ./test/unit/tests/client/components/App.test.js
 @ ./test/unit/tests/client/components/index.js
 @ ./test/unit/tests/client/index.js
 @ ./test/unit/tests/index.js
 @ ./test/unit/entry.js

ERROR in ./node_modules/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/lib/ExecutionEnvironment' in 'D:\Projects\pvc\node_modules\enzyme\build'
 @ ./node_modules/enzyme/build/react-compat.js 72:2-43
 @ ./node_modules/enzyme/build/ReactWrapper.js
 @ ./node_modules/enzyme/build/index.js
 @ ./test/unit/tests/client/components/App.test.js
 @ ./test/unit/tests/client/components/index.js
 @ ./test/unit/tests/client/index.js
 @ ./test/unit/tests/index.js
 @ ./test/unit/entry.js
webpack: Failed to compile.  

</details>

---------------  

package.json
```
"enzyme": "^2.9.1",
"react": "^15.6.1",
"react-dom": "^15.6.1",
"react-test-renderer": "^15.6.1"
```

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.
