### ISSUE TITLE
alpha problems with enzyme testing setState functionality.

### ISSUE THREAD

**Issue by awitherow** [airbnb/enzyme#1049]
Hello! First, thank you for the effective shallow functionality, we use it everywhere in our tests and it really allows us to do what we want with our TDD approach.

We are attempting a react-native upgrade to 0.46 and have adopted the enzyme alpha branch as our enzyme package.

An example of what does not work.

```javascript
// Component.test.js
it('should react to presses', () => {
    toggle = jest.fn()
    rendered = shallow(<Component onPress={toggle} />
    rendered.simulate('press')
    expect(toggle).toHaveBeenCalled() // does not work
}

// Component.js
onPress = () => this.setState({ pressed: !this.state.pressed })
```

It simply throws an exception saying that expect(toggle).toHaveBeenCalled did not pass.

Any ideas on howe we can help?

**Comment by lelandrichardson** [comment]
@awitherow I'm not sure I understand your example, but I verified that a similar example works.

```
  class Component extends React.Component {
    render() {
      return (
        <div onPress={this.props.onPress} />
      );
    }
  }

  // Component.test.js
  it('should react to presses', () => {
    const toggle = jest.fn();
    const rendered = shallow(<Component onPress={toggle} />);
    rendered.simulate('press');
    expect(toggle).toHaveBeenCalled();
  });
```
If that does not answer your question, let me know. I'm not going to close this issue.
