### ISSUE TITLE
Object property selector

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#105]
From @hartzis:

I'm really excited to see support for attribute/prop selectors, but it feels like this is coding to the wrong abstraction. Under the hood JSX is javascript and this solution seems right if this was html.

Instead of a CSS selector why not supply an object of props to search for?
`<Foo foo="bar" />` => `expect(wrapper.find({foo:"bar"}))` => match
`<Foo foo="bar" blah="sheep" />` => `expect(wrapper.find({foo:"bar"}))` => match?

**Comment by lelandrichardson** [comment]
Added in 1.4
