### ISSUE TITLE
setState() functionality on a shallowed component seems not working 

### ISSUE THREAD

**Issue by linesh-simplicity** [airbnb/enzyme#1051]
## Issue 

While I'm trying to change the `state` of a shallowed component through the [`setState()`][setState documentation] provided by the [ShallowWrapper API], this piece of code is running into error: 

```js
it('should render children component when an authentication token is present', () => {
  const component = shallow(
    <LoginRequired>
      <Text>should render this</Text>
    </LoginRequired>
  ).setState({ token: 'something-not-empty' })

 expect(component.find(Login)).toHaveLength(0)
 expect(component.find(Text)).toHaveLength(1)
})
```

and the `LoginRequired` class: 

```js
export default class LoginRequired extends Component {
  constructor() {
    super()
    this.state = {
      token: ''
    }
  }

  onLogin() {
    // ...
  }

  isLoggedIn() {
    return !_.isEmpty(this.state.token)
  }

  render() {
    return (
      this.isLoggedIn() ? this.props.children : <Login onLogin={this.onLogin} />
    )
  }
}

```

The error message is:

```
TypeError: Cannot read property 'setState' of undefined
      
      at node_modules/enzyme/build/ShallowWrapper.js:377:30
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:284:3)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:376:42)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1518:25)
      at ShallowWrapper.setState (node_modules/enzyme/build/ShallowWrapper.js:375:14)
      at Object.<anonymous> (src/pages/Login/LoginRequired.spec.js:23:1)
```

I clicked into the `node_modules/enzyme/build/ShallowWrapper.js:377:30` and can see that it's actually this line, where `|` is the cursor(hope you can find it) :) 

```js
374        ...
375        this.single('setState', function () {
376          (0, _Utils.withSetStateAllowed)(function () {
377            _this4.instance()|.setState(state, callback);
378            _this4.update();
379          });
380        });
381        ...
```

According to the [`setState` documentation][setState documentation], it seems valid to use `setState()` right after a `shallow(<Component />)` call, and it seems also valid to use `const component = shallow(<Component />).setState({ token: 'something' })` since the `setState()` returns the [ShallowWrapper][ShallowWrapper API] itself according to the [ShallowWrapper API]. So I'm a bit confused if there's anything that I'm missing or getting wrong with. 

Another thing to notice is that the React Native version we use requires the alpha version of React 16, which I'm aware(If I'm right) [is not currently supported by Enzyme](https://github.com/airbnb/enzyme/issues/928). Maybe it could be the problem but I'm not sure of it. Anyone can shed some light on this issue? 

Possible related issue: https://github.com/airbnb/enzyme/issues/1049

## Debugging information 

* Enzyme version: 2.9.1
* React Native version: 0.45.1
* React version: 16.0.0-alpha.12

`package.json` attached below: 

```js
{
  "name": "retail_app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "lint": "eslint src --ext .js,.jsx",
    "test": "node node_modules/jest/bin/jest.js",
    "devtools": "react-devtools"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "devDependencies": {
    "enzyme": "^2.9.1",
    "eslint": "^4.3.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-config-airbnb-base": "^11.3.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "jest-expo": "~18.0.0",
    "npm": "4.6.1",
    "react-addons-test-utils": "^15.6.0",
    "react-devtools": "^2.4.0",
    "react-dom": "16.0.0-alpha.12",
    "react-native-scripts": "0.0.40",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^18.0.3",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-elements": "^0.13.0",
    "react-native-qrcode": "^0.2.3"
  }
}
```

[setState documentation]: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setState.md
[ShallowWrapper API]: https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md

**Comment by ljharb** [comment]
enzyme definitely does not currently support React 16 alpha or beta, which means you'd need to downgrade react-native to a version that works with React 15 to get enzyme to work.

**Comment by linesh-simplicity** [comment]
Yeah that makes sense. Looks like either we downgrade react-native to a lower version that works with React 15, or we wait until a RC/release version of React 16 is coming up.

Happy for me to close this ticket now. Thanks for the quick responding.

**Comment by erhathaway** [comment]
@linesh-simplicity I had a similar issue. I had enzyme working with React 16 alpha and some minor version upgrades caused the same `setState()` and `state` errors you are seeing. 

Pegging to absolute versions in my package.json fixed the issue:

```
    "enzyme": "2.8.2",
    "jest-expo": "0.4.0",
    "jest-serializer-enzyme": "1.0.0",
    "react-addons-test-utils": "15.5.1",
    "react-dom": "15.6.0",
    "react-test-renderer": "16.0.0-alpha.6",
    "react": "16.0.0-alpha.6",
    "expo": "^16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
```

**Comment by linesh-simplicity** [comment]
That should work as well. We find it temporarily not required now for us to use the `setState()` Enzyme API which is incompatible with React 16 alpha in our project, and now the rest of the Enzyme features works fine with React 16 alpha ... And it becomes acceptable for us to wait until React 16 RC is released. Thanks for your proposed solution still.

**Comment by linesh-simplicity** [comment]
Updates: https://github.com/airbnb/enzyme/issues/928 have an unofficial solution of using adapter for supporting React 16 alpha.

**Comment by linesh-simplicity** [comment]
Yes. We upgraded our project to RN 0.52.3 with React pinned to 16.2.0, and the `setState()` API works as expected now.

**Comment by kenware** [comment]
It does not work yet in my component

**Comment by kenware** [comment]
here is my code
this.state = {
  role: ''
}

it('should render properly with user info in the nav bar', () => {
    const tree = mount(<indexNav />).setState({ role: 'bar' });
    expect(tree).toMatchSnapshot();
  });

**Comment by ljharb** [comment]
@kenware would you mind filing a new issue?
