### ISSUE TITLE
[Query] Enzyme support for chutzpah and typescript qunit tests

### ISSUE THREAD

**Issue by nikhilexe** [airbnb/enzyme#1057]
I am trying to write react app test using Enzyme and chutzpah. Tests would be in typescript and using chutzpah to run them. I am consuming npm package [@types/enzyme](https://www.npmjs.com/package/@types/enzyme) and [enzyme](https://www.npmjs.com/package/enzyme) to write tests. This is how i am writing in my tests

```
import * as enzyme from "Package/Scripts/3rdParty/index";
...
const ddd = enzyme.shallow(component);
```

however when I ran test it fails with this error **"Error: ReferenceError: Can't find variable: exports"**

In index.js file which comes with enzyme has following code and failure happen in the first line.

```
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ReactWrapper = exports.ShallowWrapper = exports.mount = exports.shallow = exports.render = undefined;
var _ReactWrapper = require('./ReactWrapper');
...
```

If I put index.js code inside this then it doesn't complain the same issue, however enzyme has many js module and i don't want to do everywhere same thing. Any idea how I can fix this without modifying anything on the enzyme js files. Appreciate any help on this.

```
define(["require", "exports"], function (require, exports) {
});
```

**Comment by ljharb** [comment]
No idea what chutzpah is, but your last example looks like AMD, and enzyme pretty definitely won't work in an AMD environment - you need CJS (or transpired ESM, which is CJS).

**Comment by nikhilexe** [comment]
@ljharb thanks, I am closing it now and will follow up with chutzpah forum what is the best way to load CJS module.
