### ISSUE TITLE
`find(StatelessComponent)` breaks when running Uglified JS tests

### ISSUE THREAD

**Issue by lxynox** [airbnb/enzyme#1060]
I'm not sure whether it's a bug or sth can be labeled as improved, so i leave it here.

Currently we run our unit tests in dev/production mode, the only difference is that `UglifyJS` plugin is enabled when in production. (this indicates most function name gets shortened in prod)

While tracing down the `ReactWrapper.find(selector)`, there is something hard coded as: 

>  functionName(inst.constructor) === 'StatelessComponent'

in [isFunctionalComponent](https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L31), simply

a) remove ~~functionName(inst.constructor) === 'StatelessComponent'~~ 
b) replace it with `typeof inst.render === 'function'`

resolves this issue.

Steps to reproduce:

https://github.com/lxynox/find-component-breaks-on-minified-tests

**Comment by ljharb** [comment]
That wouldn't actually solve it, because `typeof class extends React.Component {}` is `function` also - that would just cause different bugs.

I would recommend not mangling function names in production mode regardless; but in general enzyme is simply incompatible with function name mangling, because React doesn't provide any other way to distinguish SFCs.

**Comment by lxynox** [comment]
Thanks for help, just noticed it was a duplicate issue. Can we do sth similar to [isCompositeComponent](https://github.com/facebook/react/blob/357925a84e34d17b96568e67d30baeb2a399da11/src/renderers/dom/test/ReactTestUtilsEntry.js#L175) to SFCs, like:

```javascript
  isFunctionalComponent: function(inst) {
    if (ReactTestUtils.isDOMComponent(inst)) {
      // Accessing inst.setState warns; just return false as that'll be what
      // this returns when we have DOM nodes as refs directly
      return false;
    }
    return (
      inst != null &&
      typeof inst.render === 'function' &&
      inst.setState === 'undefined'
    );
  },

```

**Comment by ljharb** [comment]
That would give false positives in case anyone had a static property on their SFCs, or modified HTMLElement.prototype.

**Comment by ljharb** [comment]
Really the only true solutions here are 1) React provides an unambiguous way to distinguish SFCs, and 2) don't mangle function names, since that's willfully breaking your own code to eke out a few negligible bytes.

**Comment by lxynox** [comment]
Alright, understand. I agree it's a acceptable solution to turn off the flag of function mangling by now, solution 1) would be more solid in long term. Anyway, appreciate your suggestion!
