### ISSUE TITLE
TypeError: (0 , _reactCompat.createShallowRenderer) is not a function

### ISSUE THREAD

**Issue by ashutosh1211** [airbnb/enzyme#1070]
Using react 16 beta.

**Stacktrace:**
 TypeError: (0 , _reactCompat.createShallowRenderer) is not a function
      at new ShallowWrapper (node_modules\enzyme\build\ShallowWrapper.js:125:62)
      at shallow (node_modules\enzyme\build\shallow.js:19:10)
      at Context.<anonymous>

**Comment by ljharb** [comment]
enzyme does not yet support React 16. #1007 was just merged, and v3 will be released soon, at which point you'll be able to use it with React 16.
