### ISSUE TITLE
enzyme mount() fails for even a <div>

### ISSUE THREAD

**Issue by atillaordog** [airbnb/enzyme#1071]
Hi,

I have the following versions:
`"react": "16.0.0-alpha.12",`
`"react-dom": "16.0.0-alpha.12"`
`"enzyme": "^2.9.1"`,
`"jest": "20.0.4"`,
`"jsdom": "^11.1.0"`

I have initialized jsdom as mentioned in the enzyme docs.

And I get this error:
TypeError: Cannot read property 'getPublicInstance' of undefined

at any attempt to call mount:
`mountedMulti = mount(
                <div ></div>
            );`

I tried everything, searched all over the internet, but could not get around this.

**Comment by ljharb** [comment]
enzyme 2 does not support react alphas or betas; you'll have to wait for v3 before you can use React 16 with enzyme.
