### ISSUE TITLE
Find() Does Not Find Parent, It's Finding Child in render()

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1077]
this is a bit weird.  When I debug, tab ends up being a shallow wrapper which is fine and expected.  But.. when I look at the nodes array in WebStorm of the shallow wrapper, it's always returning the <Search /> component, not <HeaderSearch />.  Why??  I'm shallow rendering HeaderSearch, not Search!

video: https://youtu.be/yyhxWI6oLPA

```
import { expect, shallow, React } from 'test/test.helpers';
import { fakeStore } from 'test/test.doubles';
import HeaderSearch from 'app/components/Header/HeaderSearch/index';

describe('Header Search Category Tab', () => {

  describe('Successful', () => {

    describe('displayed as fourth category', () => {

      it('contains search', () => {
        const search = shallow(<HeaderSearch store={fakeStore()} />).dive().find('.ft-search');
        expect(search).to.exist;
      })
    })
  })
})
```

**Container**

I'm giving the bare minimal, the **...** means "there is code here":
```
export class HeaderSearch extends Component {
  constructor() {
    ...
  }

  render() {
    ...
    return (
       <Search />
    );
  }
}

function mapStateToProps(state) {
  return {
    ...
  };
}

const TimeoutHeaderSearch = ReactTimeout(connect(mapStateToProps, {
  ...
})(HeaderSearch));

TimeoutHeaderSearch.fetchData = ({ store }) => store.dispatch(fetchSearch());
```

Here's the debug showing what was returned

![screen shot 2017-08-18 at 2 56 09 am](https://user-images.githubusercontent.com/338798/29449610-030c8cea-83c1-11e7-8498-687140e888a6.png)

**Comment by ljharb** [comment]
For one, .exist won't ever be false, because .find always returns a wrapper.

Instead, assert on the length of the wrapper, and what it contains.

**Comment by dschinkel** [comment]
yea I can't believe I did that, thanks for the catch.  I noticed the same and changed it actually yesterday.

**Comment by ljharb** [comment]
Closing since this seems answered; happy to reopen if that's not the case :-)
