### ISSUE TITLE
Find() on Shallowly Rendered Component Not Returning Found Child

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1080]
I'm not sure why the find wouldn't just give me the image.  It's give me a shallow wrapper back instead of the found image using the marker. (first assert passes fine btw)

```
it('returns a tab item for an image', () => {
      const tabImage = <img src="" alt="" className="tab-item-image" />,
        image = shallow(<TabItem store={fakeStore()} content={tabImage} />).find('.tab-item-image');

      expect(image).to.have.length(1);
      expect(image).to.deep.equal(tabImage);
    });
```
When I inspect `image` in webstorm the deep equal fails because image is a shallow wrapper.  I thought if I did a find by the marker I'd be getting the <img /> not the shallow rapper:

![screen shot 2017-08-20 at 1 57 58 am](https://user-images.githubusercontent.com/338798/29492759-56d7d786-854b-11e7-9a43-89a040223f20.png)

![screen shot 2017-08-20 at 2 08 16 am](https://user-images.githubusercontent.com/338798/29492786-83214524-854c-11e7-8911-e04d9e77bcea.png)

**TabItem**
```
export const TabItem = ({ classname, content, onclick, key }) => (
  return (
    <li
      key={key}
      className={`${classname} search-tab`}
      onClick={onclick}
    >
      {content}
    </li>
  );
);
```

**Comment by dschinkel** [comment]
hmm got it working, don't know if there's a better way than I did it though.  I had to do nodes[0] to et to the actual img even though I did a find on 

```
it('returns a tab item as an image', () => {
      const tabImage = <img src="" alt="" className="tab-item-image" />,
        tabItem = shallow(<TabItem store={fakeStore()} content={tabImage} />)
          .find('.tab-item').find('.tab-item-image');

      expect(tabItem).to.have.length(1);
      expect(tabItem.nodes[0]).to.deep.equal(tabImage);
    });
```

**Comment by ljharb** [comment]
Try `console.log(shallow(<TabItem store={fakeStore()} content={tabImage} />))` - that may tell you what the wrapper *is*, and then you can do your finding from there.

**Comment by dschinkel** [comment]
well I use webstorm's debug so able to see that nicer but yea I've totally walked that tree many times.

**Comment by ljharb** [comment]
That's not the same output as enzyme's `debug` method.

**Comment by dschinkel** [comment]
ok I'll give it a try, thanks!

**Comment by dschinkel** [comment]
looks like enzyme's debug is basically the same info I see when I drill down into the WebStorm debug, just in a slightly or maybe majorly flattened form whereas I usually drill down the tree to see what's there in WebStorm's debug pane.
