### ISSUE TITLE
.simulate('click') only working when done twice on the same component, through ID and Class

### ISSUE THREAD

**Issue by nxmohamad** [airbnb/enzyme#1081]
I have gone through existing issues and could not find one similar to this.

I have a button element like so, that sits within a `<Contact/>` component that I am testing:
```
<div>
...
<button id="Contact-button-submit" className="btn btn-primary btn-lg" onClick={this.handleSubmit}>Submit</button>
...
</div>
```
and here is my test:
```
it('calls handleSubmit when Submit button is clicked', () => {
	let wrapper = shallow(<Contact {...mockProps} />);
	wrapper.instance().handleSubmit = jest.fn();
	let { handleSubmit } = wrapper.instance();
	expect(handleSubmit).toHaveBeenCalledTimes(0);
	wrapper.find('#Contact-button-submit').simulate('click'); // the only simulate click I want
	wrapper.find('.btn-primary').simulate('click'); // the simulate click I also had to add
	expect(handleSubmit).toHaveBeenCalledTimes(1);
});
```

The funny thing is that, when I only include the first simulate click (the ID one), the test fails at the last expect. The onClick function (handleSubmit) is never called.
But when I add the second one that uses className, it passes. 

It seems like they BOTH need to be present. It will fail if one is removed.

Are there any known causes for this? I'm scratching my head over this.

**Comment by ljharb** [comment]
(btw buttons have a default `type` of `submit`, so if you're not using it as a javascriptless submit button, you want `type="button"`)

In general, I don't recommend using `simulate` at all - I'd recommend `.prop('onClick')` and invoking it directly, and asserting that your mock is called - you don't need to test React's event wiring nor the browser's.

**Comment by nxmohamad** [comment]
by `type="button"` do you mean using that as the selector?

.prop('onClick') only returns it right? to call it I assumed it would be something like `wrapper.find(SELECTOR).props().onClick()`;

**Comment by ljharb** [comment]
no, I mean using that in the jsx.

Correct, you'd do `wrapper.find(SELECTOR).prop('onClick')()`.

**Comment by nxmohamad** [comment]
ok so would there be any known reasons that it wouldn't call the function in onClick?

Before your comment I did it like what you commented above but without the last `()`. I thought that by adding that it would call the function, but it seems like it doesn't.

**Comment by nxmohamad** [comment]
would there be any known issues whereby the onClick function wouldn't be called? 

I tried to invoke with the example syntax you gave but it seems like it doesn't invoke the function I've assigned in onClick.

**Comment by nxmohamad** [comment]
regarding using type="button" as the selector, is that considered best-practice? 
what if I have multiple buttons in the same wrapper component, is it not better to use ID?

**Comment by nxmohamad** [comment]
ok so similar issue again, the test passes when I do `wrapper.find(SELECTOR).prop('onClick')()` twice.

**Comment by ljharb** [comment]
My guess is some combination of using class properties, and storing a reference to the function prior to stubbing it out. Can you share 100% of the related code?

**Comment by nxmohamad** [comment]
*Contact.js*
```
export class Contact extends Component {
	constructor() {
		super();
		this.state = {
			message: '',
			email: '',
			empty: false,
			invalidEmail: false,
			error: false
		}

		this.handleMessageChange = this.handleMessageChange.bind(this);
		this.handleEmailChange = this.handleEmailChange.bind(this);
		this.handleSubmit = this.handleSubmit.bind(this);
	}
  	handleSubmit() {
  	 ...
  	}
```

*Contact.test.js*

```
import React from 'react';
import { shallow } from 'enzyme';
import { Contact } from './index';

const mockProps = {
	browser: {
		lessThan: {
			medium: false,
			small: false
		}
	},
	contact: {},
	submitMessageHandler: jest.fn(),
	resetHandler: jest.fn()
};

afterEach(() => {
	mockProps.submitMessageHandler.mockReset();
	mockProps.resetHandler.mockReset();
});

it('calls handleSubmit when Submit button is clicked', () => {
	let wrapper = shallow(<Contact {...mockProps} />);
	wrapper.instance().handleSubmit = jest.fn();
	let { handleSubmit } = wrapper.instance();
	expect(handleSubmit).toHaveBeenCalledTimes(0);
	// below 2 lines are the original code and as I've mentioned calling onClick still needs to be done twice
	wrapper.find('#Contact-button-submit').simulate('click'); // first one through ID
	wrapper.find('.btn-primary').simulate('click'); // second one through classname
	expect(handleSubmit).toHaveBeenCalledTimes(1);
});
```

**Comment by ljharb** [comment]
OK, so that's exactly the problem. You have to stub `Contact.prototype.handleSubmit` *before* shallow-rendering the component.

**Comment by nxmohamad** [comment]
is this correct?
```
it('calls handleSubmit when Submit button is clicked', () => {
	Contact.prototype.handleSubmit = jest.fn();
	let wrapper = shallow(<Contact {...mockProps} />);
	let { handleSubmit } = wrapper.instance();
	expect(handleSubmit).toHaveBeenCalledTimes(0);
	wrapper.find('#Contact-button-submit').prop('onClick')();
	expect(handleSubmit).toHaveBeenCalledTimes(1);
	Contact.prototype.handleSubmit.mockRestore();
});
```

**Comment by nxmohamad** [comment]
@ljharb the above didn't work for me, but after your suggestion I came across a StackOverflow question that led me to something that did work, which is using `spyOn`.

https://stackoverflow.com/a/43284406/6440036

I would still like to know what is wrong with my attempt above. Thank you.

**Comment by ljharb** [comment]
your approach above should work just fine; except that `mockRestore` can't work because it can't possibly know what the original value of the function was. You definitely want to use `spyOn`, or else you have to manually preserve the original value and restore it with `=` at the end.

**Comment by nxmohamad** [comment]
somehow stubbing the prototype like in the above snippet didn't work, but I'll close this issue since I found a way to carry out what I needed. 

thank you @ljharb  for the help

**Comment by drFabio** [comment]
> OK, so that's exactly the problem. You have to stub Contact.prototype.handleSubmit before shallow-rendering the component.
--
@ljharb  what if I want to test a bound method of some class for example:
```javascript
      const stub = sandbox.stub(targetComponent.instance(), 'createAccount')
      renderedComponent.find(CreateAccountButton).at(0).prop('onClick')()
      renderedComponent.update()
      renderedComponent.find(CreateAccountButton).at(0).prop('onClick')()
      renderedComponent.update()
      expect(stub.called).toEqual(true)
```
On this case I'm needing to invoke it twice as well for it to work.

**Comment by ljharb** [comment]
You have to stub it on the component prototype *before* creating the wrapper. In other words, you need to make sure that the thing that's "bound" is the stub.

**Comment by maxnathaniel** [comment]
I finally found the solution to my `simulate('click')` problem here.  Thanks! 

I'm sure we are not the only ones who experience this issue. Can we add this `.prop('onClick')` for buttons recommendation in the official docs? Spent a long time trying to figure out what the problem was and only managed to find it by chance here.

**Comment by LouisRitchie** [comment]
> Can we add this .prop('onClick') for buttons recommendation in the official docs? 

But of course this does not work if you are testing components that are wrapped in a HOC, or are nested one or more levels deep, because you can't access `state` or `setState` or `props` or `setProps` on anything but the uppermost root function, and any hack methods like `mount(shallow(MyNestedComponent).get(0))` don't work either
