### ISSUE TITLE
Cannot test BodyMovin library with enzyme/jest. 

### ISSUE THREAD

**Issue by javaherian** [airbnb/enzyme#1090]
Hi all,

I'm trying to test a simple component which uses lottie/bodymovin animations, but they just don't work with enzyme or jest. (I'm new to testing in general so forgive me if I'm using the wrong terminology).

This is the code I'm trying to test:

```javascript
import React from 'react';
import PropTypes from 'prop-types';
// ***
// IF I COMMENT THE NEXT LINE AND THE REFERENCES TO IT, THE TEST RUNS FINE...
// ***
import ReactBodymovin from 'react-bodymovin';
import styles from './styles.css';

class Animation extends React.Component { 
  constructor(props) {
    super(props);

    const bodymovinOptions = {
      loop: false,
      autoplay: true,
      prerender: true,
      animationData: this.props.animation,
    };
  }

  // ... 

  render() {
    return (
      <div className={`${styles.animationContainer} ${this.state.showAnimation ? '' : styles.mobileSize}`}>
        <div className={styles.animationContent}>
          {this.state.playAnimation &&
            <ReactBodymovin options={this.state.bodymovinOptions} />
          }
        </div>
      </div>
    );
  }
}

Animation.propTypes = {
  animation: PropTypes.object,
  delay: PropTypes.number,
  duration: PropTypes.number,
};

export default Animation;
```

And this is the test:
```javascript
import React from 'react';
import { shallow, mount } from 'enzyme';

// XXX: Importing this line (which calls Animation, which calls ReactBodymovin) completely breaks the tests.
// TODO: Fix this.
import ReactBodymovin from 'react-bodymovin';

import Animation from '../index';
import costAnimation from './animations/cost.json';

describe('<Animation />', () => {
  it('Should run a basic test', () => {
    expect(true).toEqual(true);
  });
});
```

I get the following cryptic message in the output:

```
 FAIL  app/components/Animation/tests/index.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'src' of undefined
      
      at node_modules/bodymovin/build/player/bodymovin_light.js:8557:3244
      at Object.<anonymous>.svgNS (node_modules/bodymovin/build/player/bodymovin_light.js:1:260)
      at Object.<anonymous> (node_modules/bodymovin/build/player/bodymovin_light.js:1:311)
      at Object.<anonymous> (node_modules/react-bodymovin/lib/ReactBodymovin.js:10:17)
      at Object.<anonymous> (app/components/Animation/tests/index.test.js:6:49)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

I've looked through both the code of https://github.com/QubitProducts/react-bodymovin (Thin wrapper for bodymovin) and https://github.com/bodymovin/bodymovin and I just could not figure out the problem. So if anyone has some pointers, it would be greatly appreciated! Thanks!

**Comment by shaneowens** [comment]
👍

**Comment by ljharb** [comment]
And your code works fine in the browser?

**Comment by javaherian** [comment]
Yep, it does.

**Comment by ljharb** [comment]
What version of bodymovin is installed?

**Comment by javaherian** [comment]
I saw one piece of code in the `node_modules/bodymovin/build/player/bodymovin_light.js` file mentioned in the error message which is like this: 

```
    function loadImage(path){
        var img = document.createElement('img');
        img.addEventListener('load', imageLoaded.bind(this), false);
        img.addEventListener('error', imageLoaded.bind(this), false);
        img.src = path;
    }
```
Which I think might be the problem (possibly!). Maybe test suites don't have a `document` object?

**Comment by javaherian** [comment]
I have 

`"react-bodymovin": "^1.0.4",`

**Comment by ljharb** [comment]
Oh. Well there you go. That means to be able to require it, you have to be in a browser.

Either bodymovin needs to always assume it might not be in a browser, and/or react-bodymovin needs to only require bodymovin inside `componentDidMount`, or you need to use jsdom prior to requiring anything that requires bodymovin.

**Comment by ljharb** [comment]
I'd recommend pursuing both the first and second options there by filing issues/PRs; there's nothing related to enzyme here though, so I'm going to close this out.

**Comment by javaherian** [comment]
Thanks.

**Comment by javaherian** [comment]
In the slim chance that anyone else has the same problem, updating react-bodymovin to the 1.0.6 solved this for me!
