### ISSUE TITLE
ReactWrapperComponent assumes that node.type.contextTypes isExtensible

### ISSUE THREAD

**Issue by johnjesse** [airbnb/enzyme#1091]
Problem: When creating a wrapper using a component that uses Mobx-react inject and providing options.childContextTypes I get an error:

`Cannot add property ..., Object is not extensible`

I think this is because:

In reactWrapperComponent.jsx there is this line
`Object.assign(childContextTypes, options.childContextTypes);`

which assumes childContextTypes is extensible, i.e. ` Object.isExtensible(childContextTypes) === true` -> see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isExtensible

and as I'm using mobx-react `inject` which is calling Object.seal on the injected context Type Object this blows up with the error mentioned above.

I'd suggest the simple fix of changing line 73 in ReactWrappeComponent.jsx from:
```Object.assign(childContextTypes, options.childContextTypes);```
to:
``` const allChildContextTypes = Object.assign({}, childContextTypes, options.childContextTypes)```

and line 78 to: 
```WrapperComponent.childContextTypes = allChildContextTypes```

Currently it mutates the childContextTypes, and as long as nothing else is dependent on it doing that then it should be fine,

thoughts?

**Comment by ljharb** [comment]
Prior to enzyme 3, there's no official support for mobx nor path to it.

With v3, you'll be able to make a mobx adapter for enzyme.

That said, I agree it shouldn't be mutating and that this is a bug (it should use object spread instead).

**Comment by lemonmade** [comment]
I ran into this line from a different problem: react-redux uses the same object for `propTypes` and `childContextTypes` when connecting to the Redux store. When enzyme copied the `childContextTypes` from my options into the component's, it therefore also copied them into the `propTypes`, causing a bunch of proptype checks to fail only in dev.

**Comment by ljharb** [comment]
(this bug originated in #171)
