### ISSUE TITLE
Component shallow rendering when nested within 2 HOCs

### ISSUE THREAD

**Issue by johnyousif** [airbnb/enzyme#1092]
I have:

```
export default withRouter(connect(mapStateToProps,mapDispatchToProps)(SomeComponent))
```
I can't access the component using shallow? I have used dive() which only goes 1 level deep.

dive().dive() doesn't seem to be allowed.

Is there a simple way around this?

Thanks

**Comment by ljharb** [comment]
`.dive().dive()` should work - both on withRouter and on connect.

What happens when you try it?

**Comment by johnyousif** [comment]
Get an error saying dive can only be used on a component. It implied dive is not a valid method on a ShallowWrapper ie. What the first dive returns.

**Comment by ljharb** [comment]
Does `withRouter` wrap its contents in an HTML element?

**Comment by johnyousif** [comment]
Doesnt look like it no.

**Comment by ljharb** [comment]
On the wrapper that makes `.dive` throw, what's `.debug()` print out?

**Comment by ljharb** [comment]
Did you figure it out?

**Comment by johnyousif** [comment]
Hi Jordan, unfortunately not and I was unable to spend any more time on it. I ended up simply doing a named export on the component itself to isolate it from the connect and withRouter HOCs, which worked fine, although it's not ideal to have to change code simply to adapt to a unit testing framework, but as far as solutions go this wasn't too bad.

Would have been nice to have solved it properly. 

If you have any examples of where dive().dive() is working in similar instances please let me know.

Thanks
John

**Comment by ljharb** [comment]
We use it in airbnb in exactly this way, with many HOCs and connect - which leads me to believe it's something about withRouter specifically. Could you share the code for that?

**Comment by johnyousif** [comment]
Unfortunately I'm not allowed to share the code. However with using dive() on withRouter, I did notice some (quite infuriating!) errors occurring such as Cannot read property 'history' of undefined, Cannot read property 'router' of undefined, Cannot read property 'location' of undefined. 

So I effectively had to try and stub out all these properties that essentially make up the objects you get as a result of wrapping a component with a routing mechanism, building it up as I saw the errors but the errors seemed inconsistent depending on how I created the stub object so in the end it just became too frustrating, so I agree that it is likely something specific to the withRouter HOC (this is from react-router-dom v4 fyi).

**Comment by ljharb** [comment]
It sounds like that HOC isn't built to run outside a browser.

**Comment by johnyousif** [comment]
Yeah that's a possibility. Perhaps I'll raise it with those guys.

Thanks for your help :-)

**Comment by nikglavin** [comment]
I am also having a similar issue and it looks as though mount isn't executing the render prop in the withRouter HOC (it was working prior to the update to RR4)

`<withRouter(SplitTestHoc(ComponentA)) location={{...}}>
  <Route render={[Function]} />
</withRouter(SplitTestHoc(ComponentA))>`

is the output of debug
