### ISSUE TITLE
Website styling issue on mobile devices

### ISSUE THREAD

**Issue by sanjsanj** [airbnb/enzyme#1094]
On http://airbnb.io/enzyme the overflowing anchor links on ".book-header" are causing the sections in ".page-wrapper" to constrict in width, making for a terrible UI on mobile devices below iPhone 6 plus width.
![webpack enzyme](https://user-images.githubusercontent.com/4478671/29762575-010d5808-8bc7-11e7-8c27-7b48638ae014.png)

**Comment by harman052** [comment]
Except for hamburger, 'Edit this page' and GitHub icon, no other icons are visible for me. How you got other icons?

**Comment by sanjsanj** [comment]
The web front has been changed since I raised this issue, so it's no longer needed.
