### ISSUE TITLE
Clicking an Encapsulated Handler ...somehow indirectly?

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1098]
So in my test I need to open the dropdown in order for the items I want to assert to be rendered.  Unfortunately, but for good reason those handlers are encapsulated inside the component.  I don't want to start making those public just for testing directly, that would be bad practice.  So is there a way I can somehow get that called?

```
 it.only('contains filters', () => {
      headerSearch.props('onOpenDropdown')() // I need to do this!
      expect(headerSearch.find('.ft-search-filter').text()).to.contain('Most Recent');
      expect(headerSearch.find('.ft-search-filter').text()).to.contain('Full Episode');
 });
```

```
export class HeaderSearch extends Component {
...
  openDropdown() {
    this.setState({ isDropdownOpen: true });
  }
...
}
```
My only bet is probably simulate click to indirectly test it but just thought I'd throw this out there in case there was another option.  I'm not passing the handler via props down from the parent, so I can't just invoke it via props in this case.

**Comment by ljharb** [comment]
`headerSearch.instance().openDropdown()`?

**Comment by dschinkel** [comment]
eh I just used simulate click and added a css marker deeper down on one of the components.  Good to go.  That's probably the only way in this case since I'm rendering multiple levels, then trying to test indirectly the handler.  Nevermind...

**Comment by dschinkel** [comment]
oh crap just saw your reply. Let me try!

**Comment by dschinkel** [comment]
I'll keep that idea handy, thanks.  Good with the simulate for now.

**Comment by ljharb** [comment]
(In general I'd recommend avoiding simulate, and invoking props directly)
