### ISSUE TITLE
contains.text() fails when text is there

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1100]
So I usually use **text()** to see if a string exists in output.

This time, it doesn't work:

```
it.only('contains filters', () => {
    headerSearch.find('.sh-filter').simulate('click');
    expect(headerSearch.find('.ft-search-filter').text()).to.contain('Most Recent');
    expect(headerSearch.find('.ft-search-filter').text()).to.contain('Full Episode');
});
```

When I debug in WebStorm I see that `headerSearch.find('.ft-search-filter').text()` outputs `Most RecentMost RecentFull EpisodeAll (A-Z)Action`.  But not sure why this would fail as `Full Episode` is clearly there.

Then I read about _text()_ more and it says:

> Returns a string of the rendered text of the current render tree. This function should be looked at with skepticism if being used to test what the actual HTML output of the component will be. If that is what you would like to test, use enzyme's render function instead.

Hmm so should I use render here?  I don't think so because I get the output I expect in the find, but it's all one string.  This is finding all the text of each item in a dropdown basically and somehow concats each list item's value into one string above...

**Comment by aweary** [comment]
Hey, @dschinkel! If `.text()` is outputting the expected result then the issue isn't likely with Enzyme. What exactly is the error you're getting? What assertion library are you using?

**Comment by dschinkel** [comment]
Damn it.  It works.  rubber ducking again.  I swear when I ran my test last it failed.  Sorry.
