### ISSUE TITLE
Improve lerna workflow and packages organization

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#1101]
- [x] version numbers should not be synchronized across packages; even if they all start out as v3.0.0, they should absolutely not increment in sync (i'd prefer them to all start as v1.0.0 except for enzyme itself)
 - [x] ~~As many tests as possible should live inside individual package dirs - cd-ing into each dir and running `npm install && npm test` should provide as close to 100% coverage of that dir as possible. It's obviously still fine if there are some tests that span multiple package dirs; these should be in a top-level tests dir (and not inside any package).~~ (moved to #1132)
 - [x] Document the release process for each package

**Comment by lelandrichardson** [comment]
@ljharb i published some betas today. The plan is for all of the packages except for enzyme to start off at `1.0.0` except for enzyme which will be `3.0.0`. The repo now uses lerna in "independent" mode. Whenever you publish with lerna it will ask you which package version you want for each one. I plan on tagging those commits generally as the version number of enzyme at the time.

For instance, today I ran:
```
lerna publish --npm-tag=next -m "v3.0.0-beta.2"
```
where `--npm-tag=next` wont be needed normally.

Regarding your 2nd point, I don't see any problem with this, however I don't think it should be a "v3 blocker". We can iterate on project structure as time goes on.

**Comment by ljharb** [comment]
Looking at 394da8821f3008baad50b22f531e4317f2303b53, everything looks great *except* that the peer dep bumps are breaking changes.

Peer deps shouldn't ever be updated automatically; can this be avoided, since it's semver-major?

**Comment by ljharb** [comment]
(note to self: use something like `--skip-npm --skip-git` to test out publishing safely)

**Comment by skovhus** [comment]
Awesome work with enzyme@3! : )

> The plan is for all of the packages except for enzyme to start off at 1.0.0 except for enzyme which will be 3.0.0

@lelandrichardson Any reason for this? Seems more intuitive that related packages have the same major version number (example: Jest, Babel, React).

**Comment by ljharb** [comment]
It's definitely not intuitive; what it would cause is that adapters would have to have a breaking change even when none existed.

Babel is also moving to independent versioning for the same reason; React and Jest would be well advised to do the same.
