### ISSUE TITLE
v3 Timeline

### ISSUE THREAD

**Issue by jimmy-devine** [airbnb/enzyme#1109]
Hi Enzyme team,

I've been keeping a close eye on the changes for v3 and React 16 support. For my team, this update to Enzyme is required for us to upgrade from RN 0.42.0 to 0.49.0 once it is released.

I know at the end of [this PR](https://github.com/airbnb/enzyme/pull/1007), it is mentioned that there isn't an ETA for the v3 release. 

I've been looking at issues and PRs labeled `v3 blocker`. Is there a better way to gauge what still needs to be done other than that? Or can I assume (barring any more problems that pop up) that once those issues and PRs have been closed that v3 will be ready?

I understand that giving a timeline isn't ideal so in lieu of that, I'd love to know what's left to do. Any insight in to what it will take to get to v3 would be helpful. Thank you!

**Comment by ashtonsix** [comment]
Likewise, the lack of visibility on Enzyme v3 is very frustrating, it's damaging to React's ecosystem & every company that uses React - it'd be irresponsible for me to recommend adopting any new open source library created by AirBnB after the abysmal communication regarding this issue.

**Comment by ljharb** [comment]
@ashtonsix the damage is done by RN requiring a prerelease version of React.

v3 is being actively worked on; the v3 blockers label is a good indicator, and I'm trying to keep that list accurate; enzyme users can help by being patient.
