### ISSUE TITLE
global.window is undefined in describeWithDOM tests

### ISSUE THREAD

**Issue by chriscartlidge** [airbnb/enzyme#111]
I'm attempting to write a unit test to check if ```window.location``` has been set up-on a click event happening (I'm using describeWithDOM).

However, ```window``` is considered undefined whenever I access it within a test, even when I access it via ```global.window```.

I can get around this by instantiating https://github.com/airbnb/enzyme/blob/master/src/index.js#L25 with:

```javascript
jsdom({ skipWindowCheck: true });
```

Then within my tests creating the object e.g.
```javascipt
global.window = {};
```

Would you be willing to accept a PR for this or is there a better way to do this?

**Comment by ljharb** [comment]
(this was recently attempted in #106)

**Comment by lelandrichardson** [comment]
Closing this as this API has been removed.  Instantiating jsdom is left up to the user now.
