### ISSUE TITLE
'simulate' cannot be chained off of 'get'

### ISSUE THREAD

**Issue by zachbosteel** [airbnb/enzyme#1110]
Firstly, thanks for the great testing framework! As someone who has used React for a while outside the workplace and just recently adopted it within the workplace, you've made my life so much easier.

I have a quick issue or maybe suggestion I'd like to raise, and I didn't see it duplicated elsewhere (sorry if I missed it!). Here's a quick scenario. Say I have a collection of interactive elements, such as checkboxes in the first column of a table. I want to write a test asserting that only selected items are passed to a function when someone clicks button. I can do:

```
const wrapper = mount(<MyComponent {...props />);
wrapper.find(`input.multiselect-checkbox`).first().simulate('change');
```

... and that works great. I can also do:

```
const wrapper = mount(<MyComponent {...props />);
wrapper.find(`input.multiselect-checkbox`).map((checkbox) => {
  checkbox.simulate('change');
});
```

... and that also works great. It works great because both the `first` and `map` methods return a wrapper, as per the documentation. What I can't do is this:

```
const wrapper = mount(<MyComponent {...props />);
wrapper.find(`input.multiselect-checkbox`).get(1).simulate('change');
```
I'm guessing this is because, per the docs, `get` returns a node, and not a wrapper. It was a little surprising to me that `get` would work differently than `first`, for instance. So, I was wondering about the viability of making `get` return a wrapper, or perhaps adding some other method to get wrappers instead of nodes, in the event that node selection in particular was necessary for some form of testing. 

Thanks!

**Comment by ljharb** [comment]
This is how jQuery works as well, which we've emulated - basically, any operation that can, returns a wrapper and is chainable, but the sole purpose of the `get` method is to unwrap the wrapper, so that wouldn't make sense.

Perhaps you want `.at(0)`?

**Comment by zachbosteel** [comment]
Perfect. Thanks!
