### ISSUE TITLE
mapStateToProps Not Called

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1116]
I'm still stumped a bit on this one and it's pretty darn frustrating TBH.  A test that shallow mounts a component, hits an action creator successfully, hits a reducer successfully, yet the container that's shallow rendered's mapStateToProps is not updated reflecting the reducer that was hit.  I can't figure it out.

**Here's a screencast of the issue also: https://www.youtube.com/watch?v=u3Hr8GUX2no**

```
  beforeEach(() => {
    featuredCompaniesContainer = shallow(<FeaturedCompaniesContainer store={store} />)
  })

   it.only('gets a list of all featured companies', async () => {
        const companies = [
          { id: 1, active: true, name: 'Pivotal'},
          { id: 2, active: true, name: 'Pivotal'}
        ]
        mockGet('/companies/featured', companies)

        await featuredCompaniesContainer.props().fetchFeaturedCompanies()
        expect(featuredCompaniesContainer.props().companies).to.equal(companies)
      })
```

**container**
```
export class FeaturedCompaniesContainer extends Component {
    render(){
        return (<FeaturedCompanies className='ft-featured-companies'/>)
    }
}

const mapDispatchToProps = {
  fetchFeaturedCompanies: fetchFeaturedCompanies
}

const mapStateToProps = state => ({
  companies: state.company.companies
})

export default connect(mapStateToProps, mapDispatchToProps)(FeaturedCompaniesContainer)
```

**thunk action**
```
export function fetchFeaturedCompanies() {
  return async (dispatch, getState) => {

    const response = await CompanyApi.findFeaturedCompanies()

    if(response && response.body) {
      const featuredCompanies = response.body;
      dispatch(featuredCompaniesReceived(featuredCompanies))
    }
  }
}
```

**reducer**
```
const initialState = {
  companiesReceived: false,
  companies: null
}

export function company(state = initialState, action){
    switch (action.type) {
      case ActionTypes.FEATURED_COMPANIES_RECEIVED:
        return {...state,
        companiesReceived: true,
        companies: action.companies
      }
      default:
        return state
    };
}
```

So this works fine, hits the reducer, I see the state as it should be when the reducer creates new state, yet the companies prop on the container is still null and I can't figure out why.

**store**
```
import { applyMiddleware, createStore } from 'redux'
import thunk from 'redux-thunk'

import reducers from './reducers/Reducers'

export default (initialState = {}) => {
  let middleware = applyMiddleware(thunk)
  const store = createStore(reducers, initialState, middleware)

  return store
}
```

**root reducer**
```
import { combineReducers } from 'redux'
import { company } from './company'

const rootReducer = combineReducers({
  app,
  company
});

export default rootReducer;
```

**Problem**: in my test, `props().companies` ends up being **null**, even though I now the reducer created new state...because for some reason mapStateToProps is not invoked via the shallow render.

I've tried this, but doesn't do a thing (maybe I'm using it wrong??  or maybe it just doesn't work):

        await featuredCompaniesContainer.props().fetchFeaturedCompanies()
        featuredCompanies.update()
        expect(featuredCompaniesContainer.props().companies).to.equal(companies)

So I'm stumped, any help would be greatly appreciated.  I do not want to mount...as this is an isolated unit test.

related (however I'm not doing a find() in mine): https://github.com/airbnb/enzyme/issues/396

**Comment by dschinkel** [comment]
Until I hear back from someone, for now, this will have to suffice my satisfaction that my outside-in TDD is "done" for this feature:

```
   it.only('gets a list of all featured companies', async () => {
        const companies = [
          { id: 1, active: true, name: 'Pivotal'},
          { id: 2, active: true, name: 'Pivotal'}
        ]
        mockGet('/companies/featured', companies)

        await featuredCompaniesContainer.props().fetchFeaturedCompanies()
        const newState = store.getState()
        expect(newState.company.companies).to.deep.equal(companies)
        expect(newState.company.companiesReceived).to.deep.equal(true)
      })
```

but I'd definitely prefer to test that my props were updated per re-render or whatever after my reducer was hit which would be a much better, more accurate test of my container's behavior.

**Comment by ljharb** [comment]
I'm not sure what the issue is here, specifically.
