### ISSUE TITLE
parens in component displayName make it impossible to use as a selector

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/enzyme#1124]
@aweary I was testing out the enzyme v3 beta on Airbnb's test suite, and there were a lot of new failures around the CSS parser. The main culprit I found was from people trying to use component display names that had parens in them due to the typical convention of HOCs wrapping a component with parens.

A simple repro should be as follows:
```
const Foo = () => <div />
Foo.displayName = 'something(Foo)';
const Bar = () => <Foo />
expect(shallow(<Bar />).find('something(Foo)')).to.have.length(1);
```

This used to work, but doesn't anymore.
Any chance we could fix this?

**Comment by aweary** [comment]
This will be resolved by https://github.com/aweary/rst-selector-parser/pull/5
