### ISSUE TITLE
getting document.activeElement

### ISSUE THREAD

**Issue by wjelen26** [airbnb/enzyme#1128]
I have a component which is checking if element is focused (via `document.activeElement`).
I have mounted it to the div with `mount` and `attach`:

`const div = global.document.createElement('div');`
 `global.document.body.appendChild(div);`

`mount(<ActionListDropdown {...propsTo} actions={actions} />, {
    attachTo: div
  });`

I have tried to simulate and fire onFocus directly on my `input` but the element which is focused is still `document.body` anyway. I have added `tabIndex` attribute to the element that I want to focus but doesn't help.
Where am I making a mistake that JSDOM doesn't want to set `activEelement`?

**Comment by ljharb** [comment]
I would discourage using simulate at all; try `component.find(element).prop('onFocus')()` instead. If you want `document.activeElement` set, I'd suggest manually doing so.
