### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/enzyme#1129]
Looks like the latest beta has a memory leak. need to look into it, but this might be a blocker

**Comment by jvilk** [comment]
@lelandrichardson Do you have code that reproduces the memory leak or appears to have memory leak symptoms? As a part of my PhD research, I have developed an experimental JavaScript memory leak detector that automatically locates, ranks, and diagnoses memory leaks (publication -- and open sourcing! -- pending :) ). I'd be happy to throw enzyme at it to see what happens! All I need is a full example demonstrating the leak that I can run in a web browser.

On a side topic -- do you know who I could contact with memory leaks (and fixes!) that I've found on the main pages of airbnb.com? Some of them involve third-party services, but others appear to be in your own code. It's leaking about a megabyte each time users switch between certain pages, and continually adds global event listeners, documents, and more. You (or whoever) can drop me a line at jvilk@cs.umass.edu, and I can provide plenty of details on the problems, how to observe them, how to fix them, and the measured impact of the fixes.

**Comment by lelandrichardson** [comment]
@jvilk investigating this further, this doesn't appear to be a regression. It's very possible that enzyme has a memory leak, but it doesn't appear to be new to v3. I'll try to get a minimal repro but i'm not prioritizing this fix anymore.

**Comment by jvilk** [comment]
It doesn't need to be a minimal repro; the tool will see through whatever complexity there is. :) *Any* repro is totally fine.

(Also, I've sent the other memory leaks along to airbnb already, so no need to help me with a contact on that!)

**Comment by ljharb** [comment]
Nobody's reported this further; going to close.
