### ISSUE TITLE
explicit Prop value set being set during shallow() is being overridden by mapStateToProps during initialization

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1137]
https://youtu.be/Keg1L9mpWY4 - screencast of the issue

I'm not able to explicitely set props for those props which are being wired up through **mapStateToProps**.  **mapStateToProps** ends up overriding or taking precedence over everything and sets my **errors** prop to **null**.  

So for example when I put a debug point at the line `if (errors) return getErrorComponent(errors);` **errors** is still **null**:

**test**
```
 it.only('renders a 500 error', () => {
      const screen = shallow(<Live errors={500} store={store} />);
      const test = screen.dive().dive();
      ... rest of the code
      expect(screen).to.have.length(1);
    });
```
**container**

```
render() {
    const {
      panels,
      seo,
      errors,
    } = this.props;
      if (errors) return getErrorComponent(errors);
    return (
      <div className={style.screen}>
       .... rest of the code
      </div>
    );

... rest of the code and then at the end:
const TimeoutLive = ReactTimeout(connect(mapStateToProps, {
  fetchLive,
})(Live));

export default TimeoutLive;
```
So is there a way to maybe cause mapStateToProps to be hit again without having to say call a reducer?  I want to just re-render my container and have it invoke mapStateToProps again, and somehow persist my value of 500

**Comment by dschinkel** [comment]
came up with a solution:

 it.only('renders a 500 error', () => {
    const store = createStore(reducers, { live: { errors: 500 } });
    const screen = shallow(<Live setOverlay={() => {}} store={store} />);
    const error = screen.dive().dive().find('.ft-error');

    expect(error).to.have.type(Error500);
});

**Comment by ljharb** [comment]
Indeed, one `.dive()` per HOC is the proper solution :-)

**Comment by dschinkel** [comment]
@ljharb yep and I can still call this an isolated unit test as long as I don't go past rendering the container's render() method IMO.
