### ISSUE TITLE
to.equal does not work

### ISSUE THREAD

**Issue by SerhiiBilyk** [airbnb/enzyme#1141]
expect(wrapper.containsAllMatchingElements([<Left/>,<Right/>])).to.equal(true);
TypeError: Cannot read property 'equal' of undefined

But, toEqual works, 
Same situation with toBe and to.be...

**Comment by ljharb** [comment]
You're using jests matchers; we use chai's expect.

**Comment by ljharb** [comment]
Duplicate of #986, #1575.
