### ISSUE TITLE
upgrading to v3 adapter

### ISSUE THREAD

**Issue by ndao** [airbnb/enzyme#1148]
Hi, i'm trying to upgrade to v3 with Jest in Create React App & React 16. i see that's there's a new adapter pattern. following the documentation, it doesn't provide details on how to include the new `setup file`.  [link here](http://airbnb.io/enzyme/docs/installation/)

```
// setup file
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```
how should i be including the setup file so that i don't have to include it in every test file?

thanks.

**Comment by ljharb** [comment]
That depends on your test framework; typically they all have a way to include files as setup. Mocha has `--require`, jest has something similar.

**Comment by holman** [comment]
I'm in the same boat looking to upgrade. The appropriate spot for create-react-app is `src/setupTests.js`, but that doesn't seem to get everything set up, unfortunately.

**Comment by lelandrichardson** [comment]
hmm. this is a good point - we should add this to the docs for each testing framework guide, and include one for CRA as well.

> that doesn't seem to get everything set up, unfortunately.

@holman can you clarify what you're seeing when you do this in `src/setupTests.js`?

**Comment by holman** [comment]
@lelandrichardson I literally just blew my dev environment away for other distressing unrelated reasons — 😄 — but the error I was getting was the `react-dom is an implicit dependency in order to support` [react 13 and 14 I think it was].

**Comment by lelandrichardson** [comment]
@holman that's a strange error. It sounds like an error from enzyme 2.x are you sure you upgraded? Perhaps some dependency was still pulling in 2.x despite being 3.x at the top level?

**Comment by ndao** [comment]
@holman , i was able to do the `rc/setupTests.js` and i'm no longer getting any errors

**Comment by lelandrichardson** [comment]
@holman that error message isn't in the codebase anymore though and was only in enzyme 2.x... it must be coming from somewhere :/

**Comment by holman** [comment]
innnnnnnteresting. I just cleared out my dev environment too, so it could be getting pulled from all fresh stuff. I'll take a closer look and see what I can come up with.

**Comment by holman** [comment]
Thanks for asking the stupid questions- made me realize I was somehow symlinking `node_modules` from an older install (don't even ask, ughhhh). Everything's all good now with the `src/setupTests.js` approach for CRA; thanks again!

**Comment by osk** [comment]
For others wondering how to get Jest to run a setup file before _all_ tests:

`jest --setupTestFrameworkScriptFile ./src/setupTests.js`

where ` ./src/setupTests.js` contains

```js
// setup file
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

**Comment by IgorGee** [comment]
You can also put that option in `package.json`

```
  "jest": {
    "setupTestFrameworkScriptFile": "./src/setupTests.js",
  }
```

**Comment by KennethMa** [comment]
Or just put it in `jest.config.js`

``` javascript
module.exports = {
  // ...other options
  setupTestFrameworkScriptFile: '<rootDir>/setupTests.js',
}
```

**Comment by Tripflare** [comment]
If you are using the create-react-app (and using react 16) and have ejected your app, then the setupTests.js file can be placed in the config directory and edit the following section of the package.json file.

    "setupFiles": [
      "<rootDir>/config/polyfills.js",
      "<rootDir>/config/setupTests.js"
    ],

The above section is under the jest setup section in the package.json file. As you can see, just add the setupTests.js line and then add the file to config with:

```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```
