### ISSUE TITLE
Getting parent from arbitrary array of elements no longer possible?

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#1152]
Given an array of elements:

```jsx
const Fixture = () => <div><span /><span /></div>;
const elements = shallow(<Fixture />).find('span');
```

I used to be able to get the parent of the of elements by doing

```jsx
elements.root
```

In Enzyme 3, `root` is a function, but it always returns `undefined` in this case. Is this a bug? intentional? work arounds? I used this in [enzyme-matchers](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/utils/name.js#L68) to print a useful message like `"<Fixture, 2 spans found>"`

**Comment by ljharb** [comment]
`Fixture` isn't a component; it's an array - `shallow` takes a component.

What if you change Fixture to add `() =>`?

**Comment by blainekasten** [comment]
Sorry. That was a typo on my part. That was supposed to be `Fixture = () => ...` I'll update above

**Comment by ljharb** [comment]
Also what version of React?

What's `shallow(<Fixture />).debug()` look like?

**Comment by blainekasten** [comment]
React 16

```
    <span />
    
    
    <span />
```

**Comment by ljharb** [comment]
Is that the result of your find, or the whole wrapper? (I'll assume it's your find)

If you do `const wrapper = shallow(<Fixture />)`, is `wrapper.root()` what you expect?

**Comment by blainekasten** [comment]
It's not quite what I expected. And shallow/mount act differently here. This is what I'm getting:

```jsx
const wrapper = shallow(<Fixture />);
console.log(wrapper.root().name()); // "div"

const wrapper = mount(<Fixture />);
console.log(wrapper.root().name()); // "Fixture"
```

I would expect the root to be the same for both? And I'm pretty sure in v2 that's how it worked.

**Comment by ljharb** [comment]
I'm not sure about the root property specifically, but in v2 and v3 both, there's the same disconnect where a shallow wrapper "is" what the component *renders*, but a mount wrapper is the *component*.

**Comment by blainekasten** [comment]
This diff is hard to read. So I apologize, but I was able to get access to the component's name in v2 regardless of mount/shallow. Ultimately just need to find a way to make that happen here.

https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/__tests__/__snapshots__/toHaveClassName--tests.js.snap#L13-L45

**Comment by blainekasten** [comment]
Ah, so I found out how I used to do it. Any suggested ways to take care of it in v3? 

https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/utils/name.js#L17

used to reach into `wrapper.unrendered?.type?.name`

**Comment by ljharb** [comment]
I'd expect `wrapper.root().name()` would work in enzyme 3; it very well might be a bug if `.root()` returns `undefined` with react 16. @lelandrichardson ?

**Comment by ljharb** [comment]
Turns out we had no tests for `.root()`; I've added some, and added this issue to the project tracking the differences between shallow and mount.
