### ISSUE TITLE
Working with React 16 docs don't match the Readme

### ISSUE THREAD

**Issue by alanbsmith** [airbnb/enzyme#1159]
Heyo! First, thanks for all you do. I ❤️ Enzyme, and I appreciate you maintaining it. 😄 

## Overview
The docs [here](http://airbnb.io/enzyme/docs/installation/index.html#) on AirBnB do not seem to match the docs in the README [here](https://github.com/airbnb/enzyme/blob/master/docs/installation/react-16.md#working-with-react-16). I assume they just need to be pushed up.

Instead of `enzyme-adapter-react-16` it says `enzyme-react-adapter-16`.

Your error message:
```
          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
```
pointed me to this doc, which is how I found it.

### README
<img width="1058" alt="screen shot 2017-09-26 at 4 38 38 pm" src="https://user-images.githubusercontent.com/4818182/30887665-9a204248-a2d9-11e7-8f96-78648d6403fe.png">

### AirBnB Site Docs
<img width="871" alt="screen shot 2017-09-26 at 4 38 45 pm" src="https://user-images.githubusercontent.com/4818182/30887696-c7316c8a-a2d9-11e7-946a-adfebbcb6846.png">

It's a pretty small thing and should be a quick fix. 😄 Thanks again for all you do!

**Comment by Rob-Leggett** [comment]
+1

**Comment by ljharb** [comment]
The docs are fixed in #1142.

@Rob-Leggett no, `import * as` is both incorrect here, and never necessary. The adapters have a single default export; `import * as` provides a ModuleRecord object with a ".default" property.

**Comment by alanbsmith** [comment]
Correct, the docs are fixed in the README. But the site docs are not (as of now).
http://airbnb.io/enzyme/docs/installation/index.html#

This is still there:
```
npm i --save-dev enzyme enzyme-react-adapter-16
```

Thanks again for working on this.

**Comment by ljharb** [comment]
That won't be fixed until the next release.

**Comment by alanbsmith** [comment]
Sounds good. 👍 Appreciate your time!

**Comment by papaponmx** [comment]
There is a typo on the docs, this is the correct name for the package https://www.npmjs.com/package/enzyme-adapter-react-16
