### ISSUE TITLE
/node_modules/@types/enzyme/index"' has no exported member 'configure'.

### ISSUE THREAD

**Issue by mchaov** [airbnb/enzyme#1166]
import React from "react";
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

"configure" => /node_modules/@types/enzyme/index"' has no exported member 'configure'.

I've browsed the node module that downloads as the latest Enzyme@3.0.0 and I can't find anything related to exported method named "configure"

**Comment by ljharb** [comment]
DefinitelyTypeds a different module, that we do not maintain, so you'd need to file it there. They probably haven't updated the types for v3 yet.

**Comment by mchaov** [comment]
The problem is I can't find the exported "configure" inside the code in the node_modules, if I find it I will fill in and send PR to the team

**Comment by ljharb** [comment]
Your error message does have a weird path' the / shows the package name is missing. Maybe it's a webpack config issue or similar?

**Comment by ljharb** [comment]
You can see configure specified here: https://unpkg.com/enzyme@3.0.0/build/index.js

**Comment by mchaov** [comment]
Thanks, I will see what I can do about the types :)

**Comment by mchaov** [comment]
awaiting review: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20073
