### ISSUE TITLE
npm install --save-dev enzyme-react-adapter-16 fails with 404

### ISSUE THREAD

**Issue by mchaov** [airbnb/enzyme#1167]
npm ERR! code E404
npm ERR! 404 Not Found: enzyme-react-adapter-16@latest

Excerpt from the error log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'enzyme-react-adapter-16' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose npm-session 20bb433be2c86055
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/enzyme-react-adapter-16 1767ms
8 silly fetchPackageMetaData error for enzyme-react-adapter-16@latest 404 Not Found: enzyme-react-adapter-16@latest
9 verbose stack Error: 404 Not Found: enzyme-react-adapter-16@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "enzyme-react-adapter-16"
13 verbose node v8.4.0
14 verbose npm  v5.3.0
15 error code E404
16 error 404 Not Found: enzyme-react-adapter-16@latest
17 verbose exit [ 1, true ]

**Comment by tricoder42** [comment]
Use `enzyme-adapter-react-16`, there's a typo in docs. In repository it's already fixed (https://github.com/airbnb/enzyme/blob/master/docs/installation/react-16.md), just online version isn't updated (http://airbnb.io/enzyme/docs/installation/react-16.html)

**Comment by mchaov** [comment]
thanks!
