### ISSUE TITLE
enzyme v3 cannot work with chai-enzyme 0.8.0

### ISSUE THREAD

**Issue by linchen2chris** [airbnb/enzyme#1168]
it give errors **can not find module enzyme/build/react-compat.js**

**Comment by ljharb** [comment]
You'll need to file that on chai-enzyme (altho I believe they're working on it)

**Comment by cameronroe** [comment]
Getting the same issue.

**Comment by palaniichukdmytro** [comment]
@cameronroe try to use 1.0.0-beta.0 for chai-enzyme
