### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by pascalduez** [airbnb/enzyme#1182]
Hi,

there's no mention in the docs nor migration guide that `enzyme >= 3` dropped support for Node 4.
However, since `rst-selector-parser` [has such restriction](https://github.com/aweary/rst-selector-parser/blob/master/package.json#L33), installs fails on Node 4.

**Comment by ljharb** [comment]
In that case, that's an issue in rst-selector-parser; but `engines` is merely advisory. Why would that make installation fail?

**Comment by pascalduez** [comment]
> Why would that make installation fail?

It seems to be failing on the CI, with Yarn.
https://travis-ci.org/pascalduez/react-module-boilerplate/jobs/280622034

**Comment by ljharb** [comment]
That's due to a poor decision yarn made; npm proper doesn't fail when "engines" isn't met. I'd suggest using npm instead.

Either way, I've filed https://github.com/aweary/rst-selector-parser/issues/8
