### ISSUE TITLE
Component not re-rendering after Hot update

### ISSUE THREAD

**Issue by tomitrescak** [airbnb/enzyme#1184]
Hi, I am Tomas, creator of Luis (OSS React component development and testing environment). Screenshot below. 

In Luis, I use Enzyme to render and test components. I am also using MobX for state management.

GOOD NEWS is that Enzyme re-renders correctly when change in MobX state is detected on first try.
BAD NEWS is that this mechanism fails when page is hot reloaded. Calling wrapper.update() does not help. BUT simulating state change event DOES help :/

Here is the component and test code:

```js
class State {
  @observable number = 1;
}

@observer
class Component extends React.Component {
  constructor() {
    super();
    this.state = { number: 1 };
  }
  render() {
    console.log('Rendering ...: ' + this.props.state.number);
    return (
      <div>
        <div>Current mobx number: {this.props.state.number}</div>
        <div>Current state number: {this.state.number}</div>
        <button onClick={() => this.setState({ number: this.state.number + 1 })}>Increase</button>
      </div>
    );
  }
}

// test code
const state = new State();
const wrapper = mount(<Component state={state} />);
state.number = 6; // does not trigger re-render after HMR (only on initial page load)
wrapper.find('button').simulate('click'); // DOES trigger re-render at any time
wrapper.update(); // this simply does not do anything
```
 
<img width="1199" alt="screen shot 2017-09-20 at 9 56 27 pm" src="https://user-images.githubusercontent.com/2682705/30942891-ce5399cc-a430-11e7-96b3-f6a2f061ba31.png">

**Comment by dsumer** [comment]
I can confirm this issue. I've updated to react 16 and and enzyme 3 and  no changes for mobx observables are detected anymore. wrapper.update does not help.

If I call wrapper.setState with any state change, everything gets rerendered as it should.

**Comment by johnsoft** [comment]
I can confirm this as well. @dsumer Thanks for the workaround!

**Comment by dgcoffman** [comment]
In the past I have used `wrapper.instance().forceUpdate();` but it no longer works in v3.

**Comment by ljharb** [comment]
This is an inherent bug in hot reloading: the only way around it is for the hot reloader to replace *every* export with a Proxy before anything imports it, which is painful to write, and slow to run.

If there's still an issue *without* hot reloading, please file a new issue.
