### ISSUE TITLE
setProps dropping existing props

### ISSUE THREAD

**Issue by doque** [airbnb/enzyme#1191]
Since using React 16.0.0 and enzyme 3.0.0, we've found that some tests no longer work. The cause for this seems to be missing props in `componentWillReceiveProps` methods, such as:

```
class MyComponent extends Component {
  componentWillReceiveProps(nextProps) {
    if (nextProps.something) {
    	this.props.doSomething();
    }
  }
}
```

The corresponding test:
```

const doSomething = jest.fn();
const wrapper = shallow(<MyComponent doSomething={ doSomething } something={ false });

expect(doSomething).not.toHaveBeenCalled();
// passes

wrapper.setProps({
    something: true
});

expect(doSomething).toHaveBeenCalled();
// TypeError: this.props.doSomething is not a function
```

Logging `this.props` shows that after calling `setProps`, only `{ something: true }` remains. The `doSomething` is dropped. Shouldn't the props be merged?

Is this desired behavior for enzyme 3?

**Comment by ljharb** [comment]
Does this happen on mount also?

**Comment by doque** [comment]
I'm unable to reproduce this with a new component, the issue seems to be somewhere else: https://github.com/doque/enzyme-3-test.

Closing this for now.
