### ISSUE TITLE
`describeWithDOM` doesn't support `.skip` or `.only`

### ISSUE THREAD

**Issue by majapw** [airbnb/enzyme#120]
To maintain consistency with common mocha patterns, we should support `.skip` and `.only` on `describeWithDOM` as well.

**Comment by nfpiche** [comment]
Had a couple questions about the implementation for this, I have something ready but wasn't sure if I should open the PR first, or talk about it here.

With the addition of .only and .skip I thought it might make sense to move describeWithDOM into its own file.  

I'm also not sure how to test .only, as it skips every other test.

**Comment by ljharb** [comment]
You could have a separate test skeleton with two tests, `describeWithDOM.only` and a test that explicitly fails, and then run that as a separate `npm run-script`?

**Comment by lelandrichardson** [comment]
Fixed in 1.4
