### ISSUE TITLE
TypeError: val.forEach is not a function

### ISSUE THREAD

**Issue by FezVrasta** [airbnb/enzyme#1200]
So, I'm upgrading my project from an older version of Enzyme 2.x to Enzyme 3.x, keeping React 15.

I'm using `enzyme-to-json` to create snapshots tests in Jest, I upgraded it to 3.x as well to work with Enzyme 3.x

The problem I'm noticing is that some snapshot tests fail because of this error:

```
TypeError: val.forEach is not a function
```

I tracked this down to `pretty-format`, inside the `printImmutable.js` file.

Basically, here it expects `val` to be an array, but an empty object is provided:

```
val.forEach((item, key) => // line 84 of the compiled lib
```

The output from `enzyme-to-json` looks like this:

```
    {
      "type": "div",
      "props": {
        "className": "ButtonGroup"
      },
      "children": [
        {
          "type": "Button",
          "props": {
            "styles": {},
            "importance": "primary",
            "size": "regular",
            "className": "Button--active Button--first Button--last",
            "key": ".$0/.0"
          },
          "children": null
        }
      ]
    }
```

And it looks good to me, but I think I'm missing something...

Now, why does it happen?

p.s. actually I'm not sure if this is an Enzyme bug or a Jest one...

ps. 2:

This is my component (simplified):

```jsx
import React, { cloneElement } from 'react';
import CSSModules from 'react-css-modules';

function ButtonGroup({ children, ...props }) {
  return (
    <div styleName="ButtonGroup" {...props}>
      {Children.map(children, (child, key) => {
        return cloneElement(child, { key });
      })}
    </div>
  );
}

export default CSSModules(ButtonGroup, styles);
```

**Comment by ljharb** [comment]
This seems like an issue in enzyme-to-json, or css modules, but not in enzyme.
