### ISSUE TITLE
How to wrap nodes in a ReactWrapper in 3.0?

### ISSUE THREAD

**Issue by davidworkman9** [airbnb/enzyme#1202]
Previous to React 16 I had a function that took a bootstrap modal component, found it's portal location and then returned a new `ReactWrapper` which I could use to make assertions on the content of the modal. Since upgrading to enzyme 3.0 I can make the `ReactWrapper` but any `finds` on it don't find anything, but running those same selectors on `.querySelector` on the modal work.

This is what i use to have:

```
import { ReactWrapper } from 'enzyme';
import findReactComponent from '../utils/findReactComponent';

export default (modalComponent) => {    
    return new ReactWrapper(
        findReactComponent(
            modalComponent.props().manager.modals[0].getDialogElement(),
        ),
        modalComponent.root(),
    );
};

```

Any hints on how I can get this to work again? I've been trying to get it working all day.

**Comment by oliviertassinari** [comment]
I have been asking this question myself to in order to migrate Material-UI test suite. I have noticed that the v3 behavior is different from the v2.

**Comment by danactive** [comment]
My workaround is to convert to HTML first, then find the selector

```
wrapper.html().includes('ClassName');
```

**Comment by davidworkman9** [comment]
@danactive I tried that and unfortunately it's not even an option for me, `wrapper.html()` returns `null`, even though `getDialogElement().innerHTML` has HTML in it.

**Comment by ferdaber** [comment]
I was able to get this working by using the children API, it seems that creating a wrapper instance around a ref (which is a pure HTML node) no longer works.

My code is something like:
```jsx
const FooModal = () => <Dialog><DialogContent/></Dialog> //Dialog is a portal component so DialogContent is in body root

const contentWrapper = new ReactWrapper(mount(<FooModal/>).children().prop('children'))
```

**Comment by oliviertassinari** [comment]
Best solution so far for me is to remove the usage of `ReactWrapper` and to rely on native DOM operations.

**Comment by the-spyke** [comment]
Same issue. I have tests for a popup component and this little helper method:

```javascript
function mountPopup(popupElement) {
    const wrapper = mount(popupElement);

    return new ReactWrapper(wrapper.find(Portal).instance().$portal, true);
}
```

What is the new way to do this?

**Comment by the-spyke** [comment]
Super temporary solution:

```javascript
function mountPopup(popupElement) {
    const wrapper = mount(popupElement);
    const portalInstance = wrapper.find(Portal).instance();

    return new ReactWrapper(
        portalInstance.props.children,
        undefined,
        { attachTo: portalInstance.$portal }
    );
}
```

It works, but not always, because you can't `wrapper.update()`, etc.

**Comment by ljharb** [comment]
Does the `.wrap` method in a ReactWrapper/ShallowWrapper help?

**Comment by the-spyke** [comment]
No so much:

```javascript
const wrapper = mount(<Popup><span className="target">Test</span></Popup>);
const portalInstance = wrapper.find(Portal).instance();

wrapper.wrap(portalInstance).debug();
/*
"<undefined onClose={[Function]} />"
*/
wrapper.wrap(portalInstance.$portal).debug();
/*
"<undefined />"
*/
wrapper.wrap(portalInstance.props.children).debug();
/*
"<PopupContent posX={0} posY={0} />"
*/
new ReactWrapper(portalInstance.props.children).debug();
/*
"<PopupPosition posX={0} posY={0}>
    <span className="target">
      Test
    </span>
</PopupContent>"
*/
```

Not sure if I'm doing it right.

**Comment by ljharb** [comment]
Related to Portals specifically, I don't think enzyme has proper react 16 portal support yet.

**Comment by the-spyke** [comment]
It's React 15. I have no issues with React 16 so far (as it should be, because it has all nodes in single tree).

**Comment by ljharb** [comment]
Prior to React 16's Portal API, React has no facility for managing elements outside the render tree, and thus neither does enzyme.

If there's a specific bug with test cases, I'm happy to reopen this and address it.
