### ISSUE TITLE
TypeError: formElement.checkValidity is not a function

### ISSUE THREAD

**Issue by wojtekmaj** [airbnb/enzyme#1206]
I have a simple test case for my form validation.

Each input element in a form has checkValidity method that checks whether the element has any constraints and whether it satisfies them.

I use it to go through some form elements and I check their validity. A simplified example could be:

```js
    [
      form.querySelector('input[name="day"]'),
      form.querySelector('input[name="month"]'),
      form.querySelector('input[name="year"]'),
    ].every(formElement => formElement.checkValidity())
```

The code above would run perfectly in all modern browsers. That is sadly not true for Enzyme - when I run tests on a component containing the code above, I get TypeError.

`TypeError: formElement.checkValidity is not a function`

**Comment by ljharb** [comment]
Can you provide a bit more of your code? Which version of enzyme? Which version of React? Mount, shallow, or render?

**Comment by wojtekmaj** [comment]
Enzyme version: 3.0
React: 16
Method used: mount

**Comment by ljharb** [comment]
And your Component code?

**Comment by wojtekmaj** [comment]
The code I was trying to test is here:
https://github.com/wojtekmaj/react-date-picker/blob/master/src/DateInput.jsx#L271-L273
I have changed the way I'm getting inputs, but the test remained unchanged.

And the smallest test case that is resulting in an error:

```js
  it('calls onChange on inputs\' change', () => {
    const onChange = jest.fn();

    const component = mount(
      <DateInput
        onChange={onChange}
      />
    );

    const customInputs = component.find('input[type="number"]');

    customInputs.at(0).simulate('change');

    expect(onChange).toBeCalled();
  });
```

I was trying to run it with shallow(), but it seems in that case I get another error (`TypeError: Cannot read property 'target' of undefined at DateInput._this.onChange (src/DateInput.jsx:297:47)`), but in this case my onChange function is not getting `event` argument, so I guess it's not a good choice for this test.

**Comment by ljharb** [comment]
In general, I'd discourage use of `simulate` - if you want to invoke the onChange prop, try `.prop('onChange')()`

**Comment by ljharb** [comment]
This seems answered; happy to reopen if not.

**Comment by wojtekmaj** [comment]
Hello @ljharb,
The problem remains - form elements have checkValidity method undefined. But now with a little more knowledge I think it might be an issue with JSDom and not Enzyme.

**Comment by wojtekmaj** [comment]
For the future wanderers: workaround in #374

**Comment by Lezlee85** [comment]
The Jest docs suggests [mocking methods which are not implemented in JSDOM](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom). I think this is a cleaner solution than polluting your environment because of tests.

In my specific case, I needed to validate a form and then inspect the `classList` of the form for the presence of a certain class, the presence of which would inform me about the form's validity.

My solution was to mock the form's properties e.g mock the native implementation of `DOMTokenList` for `classList` property inside 

```
beforeAll(() => {
    window.DOMTokenList = jest.fn().mockImplementation(() => {
        return {
            list: [],
            remove: jest.fn().mockImplementation(function (item) {
                const idx = this.list.indexOf(item);

                if (idx > -1) {
                    this.list.splice(idx, 1)
                }
            }),
            add: jest.fn().mockImplementation(function (item) {
                this.list.push(item);
            }),
            contains: jest.fn().mockImplementation(function (item) {
                return this.list.indexOf(item) > -1;
            })
        };
    });
})
```
Then I used that to pass properties to the event handler. I'm able to access the form in my react component from the submit button with `event.currentTarget.form`

```
let mockClassList = new DOMTokenList();

submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => false,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    })
```

This allows me to set the validity of the form to false and true, and inspect the `mockClassList` for the presence of the `was-validated` class each time

```
    submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => false,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    });

    expect(mockClassList.contains('was-validated')).toBeTruthy();

    submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => true,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    });

    expect(mockClassList.contains('was-validated')).toBeFalsy();
```


FYI: I'm using Enzyme's `shallow` rendering for this, `mount` doesn't seem to work with this solution
