### ISSUE TITLE
 enzyme-react-adapter-16 is not in the npm registry.

### ISSUE THREAD

**Issue by suprsidr** [airbnb/enzyme#1208]
$ npm install --save-dev enzyme-react-adapter-16
npm ERR! code E404
npm ERR! 404 Not Found: enzyme-react-adapter-16@latest

**Comment by deepsweet** [comment]
it's called `enzyme-adapter-react-16`

**Comment by suprsidr** [comment]
maybe we should update http://airbnb.io/enzyme/docs/installation/index.html

Next, to get started with enzyme, you can simply install it with npm:

npm i --save-dev enzyme enzyme-react-adapter-16

**Comment by ljharb** [comment]
Fixed in #1142
