### ISSUE TITLE
enzyme-react-adapter-16 typo in docs

### ISSUE THREAD

**Issue by joshmorel** [airbnb/enzyme#1209]
http://airbnb.io/enzyme/docs/installation/index.html#working-with-react-16

`npm i --save-dev enzyme enzyme-react-adapter-16`

Should be:

`npm i --save-dev enzyme enzyme-adapter-react-16`

It seems this is fixed in master, just not in the production docs site linked above. See: https://github.com/airbnb/enzyme/blob/master/docs/installation/react-16.md

**Comment by ljharb** [comment]
Fixed in #1142.

**Comment by ljharb** [comment]
The docs site only gets updated upon release, so it will be fixed the next time we publish.
