### ISSUE TITLE
Incorrect GitBook documentation

### ISSUE THREAD

**Issue by IamJoseph** [airbnb/enzyme#1211]
Under "Working with React 16"
`npm i --save-dev enzyme enzyme-react-adapter-16`
should be:
`npm i --save-dev enzyme enzyme-adapter-react-16`

**Comment by boyney123** [comment]
@IamJoseph can you link where the problem is?

I just tried to find the issue but cant see anything?

**Comment by boyney123** [comment]
Fixed in #1142

**Comment by IamJoseph** [comment]
@boyney123 http://airbnb.io/enzyme/docs/installation/react-16.html
Is it the same typo? It's still present even after clearing my cache.

**Comment by ljharb** [comment]
The published docs will not be updated until a release is published.

#1142 fixed it in master.
