### ISSUE TITLE
component.prop("id") returned with component.find("#foo")

### ISSUE THREAD

**Issue by nikglavin** [airbnb/enzyme#1214]
### Is this a bug report?

Yes

### Environment

enzyme@3.0.0

### Steps to Reproduce

When a component is mounted with JSDOM the selector library does not differentiate props.id and element.id

using react router as an example

```
const test = mount(<Link id="foo" />)
const fooLink = test.find("#foo) <-- returns 2 nodes (<Link /> + <a>)
```

### Expected Behavior

I would not expect a custom component with the prop id to be returned when querying with a CSS selector.

- `test.findWhere(n => n.prop("id") === foo)` <-- expect to return 2 nodes
- `test.find("#foo")` <-- expect to return a single node

**Comment by ljharb** [comment]
The selector API intentionally hits all nodes, host and composite - it's not a DOM, so the rule about "IDs are unique" doesn't really apply.

What you probably want is #1179 - ie, `test.hostNodes().find('#foo')`?

**Comment by nikglavin** [comment]
That will do the trick, thanks for your quick response

**Comment by ljharb** [comment]
hostNodes is now released in v3.1

**Comment by conartist6** [comment]
This just wasted several hours of my time.

**Comment by conartist6** [comment]
What's more, `hostNodes().find("#id")` doesn't even work for me. 0 results.
`enzyme@3.7.0`
`enzyme-adapter-react-14@1.2.0`
`react@0.14.9`
`react-dom@0.14.9`

**Comment by ljharb** [comment]
enzyme is independent of react and of html. What would the selector api do with, say, react native?

**Comment by ljharb** [comment]
As far as the specific thing that doesn’t work for you, please file an issue and we’ll see if we can straighten it out.

**Comment by conartist6** [comment]
I have opened #1907 for the problems which occur regardless of this issue.

**Comment by conartist6** [comment]
Perhaps all that needs to be done is for there to be a convenience API, something like `findHost` which was a shortcut for `hostNodes().find()` At least having such a thing be present in documentation would give it more visibility and allow the find documentation to call out the circumstance in which using it would be appropriate.
