### ISSUE TITLE
`.find` has inconsistent behaviour between `mount` and `shallow` for non-host nodes

### ISSUE THREAD

**Issue by pfhayes** [airbnb/enzyme#1216]
See original discussion on https://github.com/airbnb/enzyme/issues/1174 and https://github.com/airbnb/enzyme/issues/1185

```
it('enzyme', () => {
  const F = (props) => <div/>; 
  const test = mount(<F className="x"/>);
  expect(test.find('.x').length).toBe(1);
});
```

In Enzyme 3, this passes because `.find` finds the non-host node `<F/>`. However, this test fails

```
it('enzyme', () => {
  const F = (props) => <div/>; 
  const test = shallow(<F className="x"/>);
  expect(test.find('.x').length).toBe(1);
});
```

It fails because for `shallow`, `.find` only examines host nodes and thus skips over the `className` on the `<F/>` node

The behaviour of `.find` should agree between the two implementations

@ljharb @aweary

**Comment by aweary** [comment]
I'm not sure this inconsistency is related to `find` matching host nodes. @pfhayes can you test with a component that renders a composite component that isn't the root?

```jsx
const Foo = ({ className }) => <div className={className} />;
const Bar = () = <Foo className="foo" />;
const wrapper = shallow(<Bar />);
```

IIRC shallow does not match against the root component being rendered, unlink `mount`. I know we had some discussions about changing those semantics but I don't think we ended up doing so? @ljharb

**Comment by ljharb** [comment]
We definitely haven't changed that semantic yet; we're still discussing paths forward there.

**Comment by pfhayes** [comment]
I see - yes, the test that @aweary provided passes. So the conclusion is that `mount` matches the root node and `shallow` does not, and that is expected behaviour?

**Comment by ljharb** [comment]
At the moment, yes.

The issue should remain open, however.

**Comment by kamthamc** [comment]
Had same issue 
 find is returning two nodes(the one matched & undefined for some reason).
https://github.com/kamthamc/recharts/blob/9db43163bb62f6b77115f31a3cc4b21bcf4d15db/test/specs/chart/LineChartSpec.js#L290
https://travis-ci.org/recharts/recharts/builds/284945979#L523
https://github.com/recharts/recharts/pull/916

**Comment by ljharb** [comment]
Closing; please track this issue here: https://github.com/airbnb/enzyme/projects/3
