### ISSUE TITLE
Add an .equals() method which accepts JSX

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/enzyme#122]
based on the conversation in https://github.com/airbnb/enzyme/issues/116 I think adding a `.equals(<Foo />);` method would be a reasonable addition to the API.

```jsx

const MyComponent = ({ type }) => (
<Page type={type}>
  <Header>
    My Page Title
  </Header>
  <Body>
    My Page Content
  </Body>
</Page>
);

describe('test JSX output', () => {
  it('should be done', () => {
    const component = shallow(<MyComponent type="custom" />);
    expect(component.equals(
<Page type="custom">
  <Header>
    My Page Title
  </Header>
  <Body>
    My Page Content
  </Body>
</Page>)).to.equal(true);
  });
});
```

NOTE: looking at `.contains()` should make this pretty straight-forward to implement...

**Comment by ljharb** [comment]
Should this be called `.is` to closer match jQuery?

**Comment by lelandrichardson** [comment]
There already is an `.is(selector)` method. We could just augment that method though to allow JSX to be passed in as an alternative use.
