### ISSUE TITLE
react is not defined

### ISSUE THREAD

**Issue by realseanp** [airbnb/enzyme#1222]
Updated to React 16 and Enzyme 3 - using mocha with webpack

```js
import React from 'react';
import Enzyme, { render } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

describe('...', () => {
  // ...
});
```

Webpack externals:

```
  externals: {
    jsdom: 'window',
    'react/addons': true,
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': 'window',
    'react-dom/test-utils': true,
    'react-test-renderer/shallow': true,
  },
```

I get the error `ReferenceError: react is not defined`

**Comment by ljharb** [comment]
hm, I'm not sure why any of those need to be externals in enzyme 3?

**Comment by realseanp** [comment]
@ljharb without it I get:
`Module not found: 'react-test-renderer/shallow' in '/node_modules/enzyme-adapter-react-16/build'

**Comment by ljharb** [comment]
Do you have `react-test-renderer` in your dev deps? Try `npm ls` - if it returns nonzero then nothing can be expected to work.

**Comment by realseanp** [comment]
Yeah I didn't have it in dev deps - i assumed enzyme would have it listed in its dependencies

**Comment by ljharb** [comment]
It's a peer dep; all singleton things are, and in the react ecosystem, that's basically anything "react-"-prefixed.

**Comment by realseanp** [comment]
Gotcha - shouldn't react-test-renderer be listed as a peer dep in enzyme ? Like how would I know I would need to install this before getting the error `module not found` ?

**Comment by ljharb** [comment]
It's already a peer dep in `enzyme-adapter-react-16`: https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/package.json#L44

**Comment by realseanp** [comment]
Ahh i see - but why wasn't it installed when I installed `enzyme-adapter-react-16`

**Comment by ljharb** [comment]
Because peer deps are never automatically installed in npm 3+; you always have to manually install them and add them to your `package.json`.

**Comment by deenjohn** [comment]
do this :

import React from 'react';

**Comment by aqteifan** [comment]
try importing react in your test just like you do it in you component.
`Import React from 'react'; `
:)

**Comment by trigunam** [comment]
How do we resolve this in React 17, which has new JSX Transform?
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by ljharb** [comment]
You'd simply not need to import React explicitly, whether it's in your tests or in your production code - in other words, it will have no effect on this issue.

You'll still always need the same packages installed.

**Comment by trigunam** [comment]
Thank you for the quick response. I am using next 9.5.3 and getting this exact error in tests. 

ReferenceError: React is not defined

      102 |   };
      103 | 
    > 104 |   return (
          |   ^
      105 |     <>

I have tried using the below in setupJest.js with no luck
import Adapter from "@wojtekmaj/enzyme-adapter-react-17";

Removed all imports also using react-codemod but still, the above errors pops up. 

Is there any other configuration to change?

**Comment by ljharb** [comment]
@trigunam this has nothing to do with enzyme. React's latest blog post says you need both React 17 and also custom babel configuration to be able to avoid importing React.
