### ISSUE TITLE
require makes mocha crash when used in `describeWithDOM`

### ISSUE THREAD

**Issue by hourliert** [airbnb/enzyme#123]
Hi,

I have a very weird issue happening when requiring a module in a `describeWithDOM` block.

When I am mocking a dependency with `mockery` I need to require my module (which using the mock) after the mock registration.
If I do this in a `describeWithDOM` block mocha exits without saying anything.

Here a sample that makes mocha crash:

```javascript
  describeWithDOM('With DOM', () => {
    beforeEach(() => {
      mockery.enable({
        warnOnReplace: false,
        warnOnUnregistered: false,
        useCleanCache: true,
      });
    });

    afterEach(() => {
      mockery.disable();
    });

    it('should call the signout method', () => {
      const spy = sinon.spy();
      mockery.registerMock('../../actions/session', {
        signout: spy,
      });

      const LogoutPage = require('../LogoutPage');
      
      expect(spy).to.have.not.been.called();
      mount((
        <LogoutPage />
      ));
      expect(spy).to.have.been.called();

      mockery.deregisterMock('../../actions/session');
    });
  });
```

Even if my file `../LogoutPage.js` is extremely simple:
```javascript
export default {
  here: true,
};
```
`require` makes mocha crash. 

I am using:
```
$ node --version
v5.4.1
$ npm --version
3.3.12
```

A workaround is to reinstall jsdom with `npm install jsdom`.

I am not sure if this issue is more related to enzyme, mocha or jsdom.

Thanks in advance.

**Comment by ljharb** [comment]
Can you provide a stack trace of the crash?

**Comment by hourliert** [comment]
That's the problem. Mocha crashes without saying anything. No exception, no stack trace.
I tried to debug it with node-inspector (with `node-debug /node_modules/mocha/bin/_mocha --compilers js:babel-core/register --require babel-polyfill ./src/containers/LogoutPage/__tests__/LogoutPage-test.js`) but it doesn't show anything.

Here is a typical output of a crash:
```
$ ./node_modules/mocha/bin/_mocha --compilers js:babel-core/register --require babel-polyfill ./src/containers/LogoutPage/__tests__/LogoutPage-test.js


  LogoutPage
    (uses jsdom)
      With DOM
```

**Comment by hourliert** [comment]
I made a sample repository that demos the crash: https://github.com/hourliert/jsdom-mocha-crash

**Comment by hourliert** [comment]
Hi, 

My issue is gone. I have updated my packages to latest version especially `jsdom` to version 8.

I will update this repo https://github.com/hourliert/jsdom-mocha-crash to confirm the issue is gone.

**Comment by lelandrichardson** [comment]
:+1:
