### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by SerhiiBilyk** [airbnb/enzyme#1231]
Since react 16, jest && enzyme don't work correctly
{import react from 'react'}
  ^^^
SyntaxError: Unexpected token import
****************************
My package.json
{
  "name": "skew",
  "version": "1.0.0",
  "description": "just simple RWD page",
  "main": "./src/index.js",
  "scripts": {
    "test": " jest",
    "build": "webpack --env production",
    "start": "nodemon --watch webpack.config.js --exec \"webpack-dev-server --content-base dist/ --env development\"  "
  },
  "jest": {
    "transform": {
      "\\.js$": "babel-jest"
    },
    "collectCoverageFrom": [
      "./src/components/**/test/*.jsx",
      "./src/components/*.test.jsx",
      "!./src/components/**/*.scss",
      "!./src/components/**/*.png",
      "!./src/components/**/*.jpg"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SerhiiBilyk/skew.git"
  },
  "author": "SerhiiBilyk",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/SerhiiBilyk/skew/issues"
  },
  "homepage": "https://github.com/SerhiiBilyk/skew#readme",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-styled-components": "^1.2.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-jest": "^21.2.0",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "css-loader": "^0.28.7",
    "enzyme": "^3.1.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^21.2.1",
    "node-sass": "^4.5.3",
    "nodemon": "^1.12.1",
    "postcss-load-config": "^1.2.0",
    "postcss-loader": "^2.0.6",
    "postcss-plugin": "^1.0.0",
    "react-test-renderer": "^16.0.0",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^1.3.1",
    "style-loader": "^0.18.2",
    "styled-components": "^2.2.0",
    "url-loader": "^0.5.9",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-hot-middleware": "^2.19.1"
  }
}
***********************
my .babelrc

{
  "presets": ["react","env"]
}

**Comment by mykhailo-riabokon** [comment]
Hi @SerhiiBilyk. `{import react from 'react'}` - why import statement is in brackets?

**Comment by ljharb** [comment]
Indeed, that's a syntax error. `import` statements can only appear at the top level of a Module.

**Comment by SerhiiBilyk** [comment]
@mykhailo-riabokon there are no brackets in my code, only here, I don't know why I wrote this brackets :)

**Comment by SerhiiBilyk** [comment]
@ljharb 'import react' is the first line of my code

**Comment by ljharb** [comment]
I'm not sure why updating to enzyme 3 would impact your build process :-/

**Comment by SerhiiBilyk** [comment]
@ljharb  I tried enzyme 2.x.x, react 15.x.x and others .... still don't work :(

**Comment by mykhailo-riabokon** [comment]
@SerhiiBilyk so that means it's not connected to enzyme or react.

**Comment by pvanny1124** [comment]
i am also having this issue. seems like a babel issue perhaps?

**Comment by SerhiiBilyk** [comment]
@pvanny1124 try to experiment with babel plugins
