### ISSUE TITLE
ShallowWrapper instance of Stateless React component returns null

### ISSUE THREAD

**Issue by mykhailo-riabokon** [airbnb/enzyme#1232]
Hello,

After update to enzyme 3 and React 16, ShallowWrapper `instance()` works a bit different. For Stateless React component it returns `null`. Please check test example bellow:
```javascript
import { shallow } from 'enzyme';
import React from 'react';

function Stateless({ name }) {
	return <div>{name}</div>;
}

class Statefull extends React.Component {
	render() {
		return <div>{this.props.name}</div>;
	}
}

describe('enzyme 3 with React 16', () => {
	const props = {
		name: 'Test',
	};

	describe('Stateless component', () => {
		test('shallow wrapper instance should not be null', () => {
			const wrapper = shallow(<Stateless {...props} />);
			const instance = wrapper.instance();

		    expect(instance).not.toBe(null);
		});
	});

	describe('Statefull component', () => {
		test('shallow wrapper instance should not be null', () => {
			const wrapper = shallow(<Statefull {...props} />);
			const instance = wrapper.instance();

		    expect(instance).not.toBe(null);
		});
	});
});
```
As a result I have an error in next test `enzyme with React 16 › Stateless component › shallow wrapper instance should not be null`. Also, these tests are passed with enzyme 3 + enzyme-adapter-react-15 + React 15.

setup
```javascript
const Enzyme = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');

Enzyme.configure({ adapter: new Adapter() });
```

package.json
```javascript
{
    ...
    "dependencies": {
      ...
      "react": "^16.0.0",
      "react-dom": "^16.0.0",
      ...
    },
    "devDependencies": {
      ...
      "enzyme": "^3.1.0",
      "enzyme-adapter-react-16": "^1.0.1",
      "jest": "^20.0.4",
      "react-test-renderer": "^16.0.0",
      ...
    },
    ...
}
```

So, is it configuration issue, or something else? 

Thanks for any help.

**Comment by ljharb** [comment]
This is an intentional change made by the React team in v16 - SFCs no longer have an instance.

What's your use case for needing the instance for an SFC?

**Comment by mykhailo-riabokon** [comment]
@ljharb I often use `instance` to check was method from `instance.props` called or not. For example 
```javascript
import React from 'react';
import { shallow } from 'enzyme';

function Button(props) {
  const onClick = () => {
    // do something
    props.onClick();
  };

  return <button onClick={onClick}>{props.children}</button>;
}

describe('Button component', () => {
  const props = {
    onClick: jest.fn(),
  };

  test('should call onClick method from props if onClick was fired', () => {
    const wrapper = shallow(<Button {...props}>Click on me</Button>);
    const instance = wrapper.instance(); // null

    // triger click

    expect(instance.props.onClick).toHaveBeenCalled() // error, because null has not props property
  });
});
```

**Comment by ljharb** [comment]
Why would you need to extract props from a wrapper where you literally just provided the props a line or two above? But also, wrapper.props()?

**Comment by mykhailo-riabokon** [comment]
@ljharb  In this examples it's just a few lines above, but I have cases where test preconditions are a bit higher. And it's easy to read `expects` if everything is in place. But thank you for `wrapper.props()`. 

And probably *NOTE* section in this [doc](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/props.md) is valid only for Statefull React Component in case of React 16. Because, as I showed in example above, `wrapper.instance().props` might work a bit unexpected (`wrapper.instance() // null`) with Stateless React Component (React 16). What do you think?

In case if you need some help, I can create PR with updated doc if needed.

**Comment by ljharb** [comment]
Thanks, definitely that doc should be updated to note the difference in React 16.

**Comment by mykhailo-riabokon** [comment]
@ljharb Hi. I've created [PR](https://github.com/airbnb/enzyme/pull/1243) related to discussion above. And as I am not a native English speaker I do apologize for mistakes if any. So, please let me know if something can be improved from my side.

Also, I thought about a warning message in case if `.instance()` returns `null`. It would nice to see warning in console, or documentation would be enough. What do you think?

**Comment by ljharb** [comment]
Warning/error messages fail tests, when test suites are set up properly - I don't think that'd be a good idea.

**Comment by ConAntonakos** [comment]
I ran into this as well. Unfortunately, I'm not passing my props to my functional, stateless component to the root node, but would still like to check the props that get passed in to see if they get rendered properly.

What would be the best approach now that `wrapper.instance()` returns `null` for functional components?

**Comment by ljharb** [comment]
I'm pretty sure `wrapper.props()` has always worked and continues to work for SFCs

**Comment by ConAntonakos** [comment]
Thanks for your response, @ljharb. I don't think that works unless you pass your props to the root node? I believe that is correct.

**Comment by ljharb** [comment]
`wrapper.find(Something).props()` works too. `.instance().props()` - which was always redundant - is the one that doesn't work on SFCs in React 16.

**Comment by kgregory** [comment]
I was using `instance.props` to test the default values of props.  

```
let wrapper;
let instance;

before(() => {
   wrapper = shallow(<SomeComponent />);
   instance = wrapper.instance();
});

describe('default props', () => {
   it('should default isVisible to true', () => {
      assert.isTrue(instance.props.isVisible);
   });

   it('should default className to null', () => {
      assert.isNull(instance.props.className);
   });
});
```

Checking `wrapper.props()` works except for the case where the incoming prop is used to modify a prop on the rendered component of the same name.  For example, I've used `className` as a prop that can be used to apply an additional class to the className of the root element:

```
const SomeComponent = ({ children = null, className = null}) => (
   <div
      className={classNames(classes.root, className)}
   >
      {children}
   </div>
);
```

If I'm expecting the `className` prop to be null by default, asserting that `wrapper.props().className` is null will fail because its value will include the classes applied within the component itself.

I suppose I can check the number of classes applied to the root element, but it was nice to be able to test the values received by the functional component.

**Comment by adc17** [comment]
For people coming to this from a search engine, if the `wrapper.props()` solution above doesn't work for you, try `wrapper.getElement().props`—it worked for me.

**Comment by mrchief** [comment]
`wrapper.props()` or `wrapper.getElement().props` (which points to same object as wrapper.props) has some funkiness going on though.

E.g., with the following SFC, 

```jsx
export const DatePickerField = ({ input, meta: { dirty, error } }: DatePickerProps) => {
  const format = 'MM/DD/YYYY hh:mm A'

  const handleChange = date => {
    input.onChange(date ? date.toISOString() : null)
  }

  return (
    <div className={cx('form-group')}>
      <label>Schedule for processing at a future date <br />
        All times are in Eastern Standard/Daylight Time (USA-New York).
      </label>
      <div>
        <DatePicker
          isClearable
          minDate={moment()}
          onChange={handleChange}
          placeholderText="Click to select a date"
          selected={input.value ? moment(input.value) : null}
          todayButton="Today"
          showTimeSelect
          timeFormat="HH:mm"
          timeIntervals={15}
          dateFormat={format}
        />
        {dirty && error && <span>{error}</span>}
      </div>
    </div>
  )
}

// test.js
const wrapper = shallow(<DatePickerField {...props} />)
wrapper.props().handleChange()
```

I get `wrapper.props(...).handleChange is not a function` error. 

However, with the following SFC:

```jsx
export const JobList = (props: Props) => {
  const { data: { pages, jobs, page, pageSize }, onPagination, onSort, onJobClick, onEditClick, onDeleteClick } = props
  const onPageChange = index => onPagination({ page: index })

  const onPageSizeChange = size => {
    // let's pretend there is good reason for doing this
    onPagination({ page: 0, pageSize: size })
  }

  const onSortedChange = ([{ id, desc }]) => onSort(id, desc)

  return (
    <ReactTable
      manual
      multiSort={false}
      showPaginationTop
      showPageJump={false}
      minRows={0}
      data={jobs}
      columns={getColumns(onJobClick, onEditClick, onDeleteClick)}
      pageSize={pageSize}
      page={page}
      pages={pages}
      onPageChange={onPageChange}
      onPageSizeChange={onPageSizeChange}
      onSortedChange={onSortedChange}
      defaultSorted={[{ id: 'id', desc: false }]}
      className="table striped-even"
    />
  )
}

// test.js
const wrapper = shallow(<JobList {...props} />)
wrapper.props().onPageChange(2)
```
 seems to work fine without any issues.

**Comment by ljharb** [comment]
@mrchief that all seems correct to me. Your second SFC renders an element with a `onPageChange` prop. Your first SFC, however, renders a `div` with no props. Note that a shallow wrapper is what the component *renders*, not the component itself - separately, it makes no sense to assert on props you literally just passed in.

**Comment by mrchief** [comment]
> Note that a shallow wrapper is what the component renders, not the component itself

Now I understand why its behaving the way its behaving.

But I'm still not clear on how to test the `handleChange` function inside the first SFC. Or if there's a better pattern to cases like that? Or maybe do a `mount` and then `children[1].props()`?

**Comment by ljharb** [comment]
Pass in a spy for `onPagination`, do `.prop('handleChange')()` and assert that your spy was called?

**Comment by mrchief** [comment]
`onPagination` is not the issue here, the first SFC (which is what has `handleChange`) is the problem. 

Repeating it here for reference:

```jsx
export const DatePickerField = ({ input, meta: { dirty, error } }: DatePickerProps) => {
  const format = 'MM/DD/YYYY hh:mm A'

  const handleChange = date => {
    input.onChange(date ? date.toISOString() : null)
  }

  return (
    <div className={cx('form-group')}>
      <label>Schedule for processing at a future date <br />
        All times are in Eastern Standard/Daylight Time (USA-New York).
      </label>
      <div>
        <DatePicker
          isClearable
          minDate={moment()}
          onChange={handleChange}
          placeholderText="Click to select a date"
          selected={input.value ? moment(input.value) : null}
          todayButton="Today"
          showTimeSelect
          timeFormat="HH:mm"
          timeIntervals={15}
          dateFormat={format}
        />
        {dirty && error && <span>{error}</span>}
      </div>
    </div>
  )
}

// test.js
const wrapper = shallow(<DatePickerField {...props} />)
wrapper.props().handleChange()
```

**Comment by ljharb** [comment]
If you're trying to test what `handleChange` does, you'll need to stub out `props.input.onChange` in your test, and then after you invoke `wrapper.props().handleChange()`, you can write assertions on your spy.

**Comment by mrchief** [comment]
That's exactly what I'm doing. And that's when I get `wrapper.props(...).handleChange is not a function` error.

**Comment by kgregory** [comment]
@mrchief maybe something is up with your props

**Comment by AugustoAleGon** [comment]
@adc17 solution works for me.

**Comment by jigishchawda** [comment]
@mrchief : I have been in the similar scenario except that it was for react-native.
`wrapper.props()` in the DatePicker example is going to show props of the top level component (in your case `<div>`)

> Note that a shallow wrapper is what the component renders, not the component itself

If you follow this, the shallowWrapper is nothing but the top level component (atleast for SFC, thats what I have deduced so far)

I would suggest doing something like this:
```
let mockHandleChange = jest.fn()
const wrapper = shallow(<DatePickerField {...props} handleChange={mockHandleChange} />)

wrapper.find('DatePicker').getElemet().props.onChange()

expect(mockHandleChange).toBeCalled()
```
__Why would someone want to write such a test?__
I write to test the __wiring of callbacks/handlers__

Hope this helps

**Comment by ljharb** [comment]
This seems answered.
