### ISSUE TITLE
Mount find() Does Not Find Rendered Marker

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1233]
This one is pretty frustrating.  I mount this container.  It does hit the code I expect that contains my css feature marker (**`ft-playback-error`**).  But in the end I end up with not found.

screencast of this issue: https://youtu.be/kh-UJTig3Qg

```
   it.only('renders a coordinates message in the player when no coordinates exist', () => {
      const store = createStore(reducers, {}),

        liveScreen = mount(
          <Provider store={createStore(reducers, {})}>
            <Live
              breakpoint="site-web"
              coordinates={null}
              renderInfoInDetail={() => {}}
              setOverlay={() => {}}
              store={store}
              AccessEnablerUrl=""
              getUseUtagGlobal={() => {}}
              pageViewEvent={() => {}}
            />
          </Provider>),
        message = liveScreen.find('.ft-playback-error');

      expect(message).to.have.length(1);
    });
```

**message.nodes** ends up being **0** (or aka not found).  Why?
<img width="642" alt="screen shot 2017-10-05 at 10 54 05 am" src="https://user-images.githubusercontent.com/338798/31237103-8e71eba2-a9bb-11e7-8c0a-633f0bd49c46.png">

I assumed when you mounted, it runs every child's render() (every child that's being hit down the codepath of container..obviously depending on whatever logic is in its render will determine _which_ children are being rendered) method of this container.

**Comment by ljharb** [comment]
Can you share the code that contains the class name?

**Comment by dschinkel** [comment]
yes I can share temporarily https://gist.github.com/dschinkel/e1e58c1cbdc60962078e1afe21cffe4b

**Comment by 3axap4eHko** [comment]
the same for me:
```
console.log(element.html());
expect(element.find('.feature__media').length).toEqual(1);
```
I'm getting
```
expect(received).toEqual(expected)

    Expected value to equal:
      1
    Received:
      0

<div class="feature"><div class="feature__cover"><div class="feature__media">Episode</div></div><div class="feature__details"><h3 class="feature__type">episode</h3><div class="feature__title"></div></div></div>
```
but `.feature__cover` found well

**Comment by dschinkel** [comment]
yea exactly... I feel like mount() isn't able to dig down the entire app tree..?  Iike the behavior I feel I've noticed is that it sorta stops 2-3 children down..

**Comment by ljharb** [comment]
@dschinkel how is `getPlaybackErrorProps()` used? Specifically, can I see the code that invokes `playbackErrorChildren`?

**Comment by ljharb** [comment]
@aweary any chance this is an issue with the RST selector parser?

**Comment by aweary** [comment]
@ljharb `.feature__cover` is parsed correctly, so I don't think so, but it could be related to the traversal logic. @dschinkel @3axap4eHko if you use `findWhere` does it work?

```js
element.findWhere(node => node.hasClass('.feature__cover'))
```

If it doesn't, can you verify if `findWhere` traverses the node you're targeting? A reduced example that we could reproduce the issue with would be useful, it's hard to say whats going on with a 800+ line example that imports from other unknown files.

**Comment by dschinkel** [comment]
@ljharb hehe yea let me show you that one...from this other 1000 line fing container (going from  from 1 100 line container to another 1000 container :)). 

https://gist.github.com/dschinkel/8d176d9abc19f9cbe39d5a4d6edc2c43

**Comment by dschinkel** [comment]
interesting @aweary I get:

`It looks like you're calling `ReactWrapper::hasClass()` with a CSS selector. hasClass() expects a class name, not a CSS selector.` when I tried your example

**Comment by aweary** [comment]
@dschinkel sorry my mistake, remove the leading `.` (just was the class name)

**Comment by dschinkel** [comment]
nope, got to the same result, not found :( but thanks.

**Comment by aweary** [comment]
@dschinkel can you verify if it's traversing the node you're looking for? You can try just logging out `node.props` inside the `findWhere` callback to see if its calling it with the node(s) you'd expect it to.

**Comment by dschinkel** [comment]
@aweary 

```
message = liveScreen.findWhere(node => {
          console.log(node.props)
          return node.hasClass('ft-playback-error')
        })
```

output:

```
[Function: props]
[Function: props]
[Function: props]
[Function: props]
```

**Comment by dschinkel** [comment]
this is crazy.

Here is a test  for another part in the same project but on a different container (different from the code I posted) but shows the weirdness I've been having as well in this example:

https://youtu.be/GJV9VduT0DY

**Comment by dschinkel** [comment]
sorry I missed this @aweary:
>If it doesn't, can you verify if findWhere traverses the node you're targeting? A reduced example that we could reproduce the issue with would be useful, it's hard to say whats going on with a 800+ line example that imports from other unknown files.

let me check..

**Comment by dschinkel** [comment]
Ok this shows it's traversing that node
https://youtu.be/6dgx-7WVdqE

**Comment by 3axap4eHko** [comment]
@aweary it does not work also. I use `"react": "^16.0.0",` and `"enzyme-adapter-react-16": "^1.0.1",`

**Comment by aweary** [comment]
@dschinkel sorry I assumed you were using Enzyme 3. The adapters are part of the rewrite, check out [the migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md). We fixed a number of selector parsing issues in the rewrite, and this could be related to one of them.

> In our case we're running React 15.1, do I need enzyme-adapter-react-15.4

You would use `enzyme-adapter-react-15` if you're not on version 15.4

At this point, it's going to be difficult for me to help further without a small, succinct example reproducing the issue that I can run locally and investigate.

**Comment by dschinkel** [comment]
ah ok I thought I was on the up and up...apparently my head is to buried in enzyme code.  I didn't realize there was a rewrite recently.

Thanks I'll try it out and report back!!  Thanks for you help so far @aweary @ljharb

**Comment by dschinkel** [comment]
hmm we're using React 15.1, not sure if the team wants to be upgrading react right now.  Here's how I added the adapter in one of my test helpers:

import chai, { expect } from 'chai';
import chaiEnzyme from 'chai-enzyme';
import { shallow, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-15.4';

Enzyme.configure({ adapter: new Adapter() });

Then tried to run tests and got:
`Error('react-dom@15.5+ and react-test-renderer are implicit dependencies when using ' + 'react@15.5+ with enzyme`

**Comment by 3axap4eHko** [comment]
@aweary I'm using `"enzyme": "^3.1.0"` and adapter is `"enzyme-adapter-react-16": "^1.0.1"` and I have the same problem

**Comment by 3axap4eHko** [comment]
This is what I found `console.log(element.html());` returns
``` html
<div class="feature">
  <div class="feature__cover">
    <div class="feature__media">Episode</div>
  </div>
  <div class="feature__details"><h3 class="feature__type">episode</h3>
    <div class="feature__title"></div>
  </div>
</div>
```
but `console.log(JSON.stringify(element.getNodesInternal(), null, '  '));` returns
``` json
[
      {
        "nodeType": "host",
        "type": "div",
        "props": {
          "className": "feature",
          "children": [
            {
              "type": "div",
              "key": null,
              "ref": null,
              "props": {
                "className": "feature__cover",
                "children": {
                  "key": null,
                  "ref": null,
                  "props": {
                    "feature": {
                      "id": "169934",
                      "series_id": "SH015468900000",
                      "style": "S",
                      "call_to_action": "WATCH THE TRAILER",
                      "call_to_action_override_long": "",
                      "image_url": true,
                      "subheading": "",
                      "suppress_season_number_episode_number": false
                    }
                  },
                  "_owner": null,
                  "_store": {}
                }
              },
              "_owner": null,
              "_store": {}
            },
            {
              "type": "div",
              "key": null,
              "ref": null,
              "props": {
                "className": "feature__details",
                "children": [
                  {
                    "type": "h3",
                    "key": null,
                    "ref": null,
                    "props": {
                      "className": "feature__type",
                      "children": "episode"
                    },
                    "_owner": null,
                    "_store": {}
                  },
                  {
                    "type": "div",
                    "key": null,
                    "ref": null,
                    "props": {
                      "className": "feature__title"
                    },
                    "_owner": null,
                    "_store": {}
                  }
                ]
              },
              "_owner": null,
              "_store": {}
            }
          ]
        },
        "key": null,
        "ref": null,
        "instance": null,
        "rendered": [
          {
            "nodeType": "host",
            "type": "div",
            "props": {
              "className": "feature__cover",
              "children": {
                "key": null,
                "ref": null,
                "props": {
                  "feature": {
                    "id": "169934",
                    "series_id": "SH015468900000",
                    "style": "S",
                    "call_to_action": "WATCH THE TRAILER",
                    "call_to_action_override_long": "",
                    "image_url": true,
                    "subheading": "",
                    "suppress_season_number_episode_number": false
                  }
                },
                "_owner": null,
                "_store": {}
              }
            },
            "key": null,
            "ref": null,
            "instance": null,
            "rendered": {
              "nodeType": "function",
              "props": {
                "feature": {
                  "id": "169934",
                  "series_id": "SH015468900000",
                  "style": "S",
                  "call_to_action": "WATCH THE TRAILER",
                  "call_to_action_override_long": "",
                  "image_url": true,
                  "subheading": "",
                  "suppress_season_number_episode_number": false
                }
              },
              "key": null,
              "ref": null,
              "instance": null,
              "rendered": null
            }
          },
          {
            "nodeType": "host",
            "type": "div",
            "props": {
              "className": "feature__details",
              "children": [
                {
                  "type": "h3",
                  "key": null,
                  "ref": null,
                  "props": {
                    "className": "feature__type",
                    "children": "episode"
                  },
                  "_owner": null,
                  "_store": {}
                },
                {
                  "type": "div",
                  "key": null,
                  "ref": null,
                  "props": {
                    "className": "feature__title"
                  },
                  "_owner": null,
                  "_store": {}
                }
              ]
            },
            "key": null,
            "ref": null,
            "instance": null,
            "rendered": [
              {
                "nodeType": "host",
                "type": "h3",
                "props": {
                  "className": "feature__type",
                  "children": "episode"
                },
                "key": null,
                "ref": null,
                "instance": null,
                "rendered": "episode"
              },
              {
                "nodeType": "host",
                "type": "div",
                "props": {
                  "className": "feature__title"
                },
                "key": null,
                "ref": null,
                "instance": null,
                "rendered": null
              }
            ]
          }
        ]
      }
    ]
```

**Comment by ljharb** [comment]
I wouldn't rely on the JSON version of `getNodesInternal()` - that's an internal method anyways, so you definitely shouldn't rely on it.

What about `element.debug()`?

**Comment by dschinkel** [comment]
@ljharb @aweary I'm hesitant to upgrade to 3.x..as I'm seeing quite a few issues out there for find() with 3.x.  Should I wait?

**Comment by ljharb** [comment]
It's hard to know if there are actually issues with v3, or if they're solely with the React 16 adapter, because people for some reason are upgrading to enzyme 3 and react 16 at the same time.

If you stick with React 15, and upgrade to v3, and follow the migration guide, you should be fine.

**Comment by 3axap4eHko** [comment]
It looks like it does not traverse over subcomponents imported from other files

**Comment by ljharb** [comment]
@3axap4eHko which, `shallow`? The entire point of shallow rendering is to never traverse subcomponents.

**Comment by kaiyoma** [comment]
> If you stick with React 15, and upgrade to v3, and follow the migration guide, you should be fine.

I did this today and I'm also running into the issues mentioned in this thread. Tests that were previously passing are now failing. The tests in question fail because they either:

- search for an element by classname a couple layers deep in the DOM
- search for a classname that is not listed first in the classname list for an element

**Comment by ljharb** [comment]
@kaiyoma `find` finding more than it used to is an expected change; use `.hostNodes()` if you want to filter it down to DOM elements.

**Comment by dcolthorp** [comment]
I've just tried upgrading a small project to Enzyme 3 and think I'm running into the same (or similar-looking) issue – using React 15.6.1 with enzyme-adapter-react-15 1.0.2 and enzyme 3.1.0.

It appears that Enzyme isn't updating it's internal understanding of the state of the vdom, even though the actual host nodes are updated as expected.

In this test, I'm using `react-apollo` and a mocked API  render a component which goes from a loading state to a loaded state after a 0ms sleep. In enzyme 2, everything works. In enzyme 3, I get inconsistent results between `page.html()` and `page.debug()`. (And my test fails in the same way that `debug` is wrong.)

Enzyme thinks the page is still in a loading state, even though the `html()` call returns the loaded state. (I also instrumented the test and see render being called with the 'loaded' props).

```typescript
  it("Shows the snacks in a list", async () => {
    const Provider = mockProvider({
      mocks: {
        Query: () => ({
          allSnacks: () => {
            console.log("In allSnacks");
            return [
              { id: 1, name: "Foo", voteCount: 1 },
              { id: 2, name: "Bar", voteCount: 2 }
            ];
          }
        })
      }
    });

    const page = mount(
      <Provider>
        <HomePage />
      </Provider>
    );

    await sleep(0);

    console.log(page.html());
    console.log(page.debug());
```


## Output

Expecting to see"Foo" and "Bar" listed in both the `html` and `debug` output, but only seeing them in the `html`. `debug` still returns the loading state.

### `html` output
```
 console.log modules/client/pages/home/__tests__/home-page.test.tsx:101
    <div class="home-page"><h2>Snacks</h2><ul><li><!-- react-text: 18 -->Foo<!-- /react-text --><!-- react-text: 19 -->&nbsp; (popularity: <!-- /react-text --><!-- react-text: 20 -->50%<!-- /react-text --><!-- react-text: 21 -->)&nbsp;<!-- /react-text --><a>Vote</a></li><li><!-- react-text: 24 -->Bar<!-- /react-text --><!-- react-text: 25 -->&nbsp; (popularity: <!-- /react-text --><!-- react-text: 26 -->100%<!-- /react-text --><!-- react-text: 27 -->)&nbsp;<!-- /react-text --><a>Vote</a></li></ul><div class="home-page-pop-mode-toggle"><h4>Show popularity as:</h4><div><label for="home-page-percentage"><input type="radio" id="home-page-percentage"><!-- react-text: 10 --> <!-- /react-text --><!-- react-text: 11 -->Percentage<!-- /react-text --></label></div><div><label for="home-page-vote-count"><input type="radio" id="home-page-vote-count"><!-- react-text: 15 --> <!-- /react-text --><!-- react-text: 16 -->Vote Count<!-- /react-text --></label></div></div></div>
```

### `debug` output:

```
  console.log modules/client/pages/home/__tests__/home-page.test.tsx:102
    <MockProvider>
      <MemoryRouter>
        <Router history={{...}}>
          <ApolloProvider client={{...}} store={{...}}>
            <QueryRecyclerProvider>
              <withApollo(Connect(Apollo(Component)))>
                <Connect(Apollo(Component)) client={{...}}>
                  <Apollo(Component) client={{...}} popularityMode="PERCENTAGE" onVote={[Function]} onPopularityModeChange={[Function]}>
                    <Component client={{...}} popularityMode="PERCENTAGE" onVote={[Function]} onPopularityModeChange={[Function]} snacks={{...}}>
                      <div className="home-page">
                        <h2>
                          Snacks
                        </h2>
                        <Component snacks={{...}} onVote={[Function]} popularityMode="PERCENTAGE">
                          <ul>
                            <li>
                              Loading
                            </li>
                          </ul>
                        </Component>
                        <Component selected="PERCENTAGE" onChange={[Function]}>
                          <div className="home-page-pop-mode-toggle">
                            <h4>
                              Show popularity as:
                            </h4>
                            <div>
                              <label htmlFor="home-page-percentage">
                                <input id="home-page-percentage" type="radio" checked={true} onChange={[Function]} />

                                Percentage
                              </label>
                            </div>
                            <div>
                              <label htmlFor="home-page-vote-count">
                                <input id="home-page-vote-count" type="radio" checked={false} onChange={[Function]} />

                                Vote Count
                              </label>
                            </div>
                          </div>
                        </Component>
                      </div>
                    </Component>
                  </Apollo(Component)>
                </Connect(Apollo(Component))>
              </withApollo(Connect(Apollo(Component)))>
            </QueryRecyclerProvider>
          </ApolloProvider>
        </Router>
      </MemoryRouter>
    </MockProvider>
```

**Comment by dmccown1500** [comment]
Seeing the same issue as @dcolthorp. Its odd the the element.getDOMNodes() shows the correct post loading view but the element.debug() shows the DOM from the loading screen...

**Comment by dmccown1500** [comment]
WORK AROUND FOUND: So at least for us this was an issue where Redux (or maybe Redux-Saga/Thunk?) and Enzyme are not playing well together. Enzyme does not auto-update the wrapper when some of the external updates are happening. They talk about in the [migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#for-mount-updates-are-sometimes-required-when-they-werent-before) but I guess I just missed it? In any case you can call `.update()` on the root component.

**Comment by dschinkel** [comment]
after upgrading to enzyme 3 this problem went way.  It's either that or my component wasn't rendering what I thought it was and the marker wasn't there.  Closing this.

**Comment by sadu** [comment]
@dmccown1500 I also had a similar issue, seems like redux and enzyme not working properly.
`.html()` was giving proper markup but `.find('selector')` wasn't working (`enzyme v3.1.0`)

`wrapper.update()` after modifying the redux state fixed `wrapper.find('.deep-nested-component')` returning an `empty set` 👍

**Comment by deathmood** [comment]
@sadu thanks for the tip. Had similar issue - `wrapper.html()` returned correct tree but when I was doing `wrapper.find(...)` it seemed like it was searching in the tree of the previous state. `wrapper.update()` helped

**Comment by msafi** [comment]
This needs to be reopened. This is still a problem.

**Comment by ljharb** [comment]
@msafi this specific issue was in v2; could you file a new issue if you're seeing problems in v3?

**Comment by msafi** [comment]
Just tried with Enzyme 3. This is no longer an issue. Thank you!

**Comment by SeanRoberts** [comment]
I just encountered this issue with redux and enzyme 3.3.0, the `.update()` workaround does work.

**Comment by github-account-because-they-want-it** [comment]
I'm having this issue. Enzyme 3.3.0 with MobX. HTML is correct but find doesn't work. The `update()` trick didn't help

**Comment by JaSpr** [comment]
Can confirm with versions:
```
+-- enzyme@3.3.0
+-- enzyme-adapter-react-16@1.1.1
```

when the component being tested must be wrapped by a redux Provider:
```
wrapper = mount(
      React.createElement(Provider, {store},
        React.createElement(MyComponent, props)
      )
    );
```
then  
`wrapper.html()` always shows the child nodes, but `wrapper.find(...)` will not find them UNLESS `wrapper.update()` is called first

**Comment by ljharb** [comment]
@github-account-because-they-want-it MobX isn't compatible with enzyme with a react adapter; you'd need a mobx adapter. Are you using one?

**Comment by joemcelroy** [comment]
if noone if seeing the same results from `wrapper.debug()` and `wrapper.html()` after calling update, use `wrapper = wrapper.update()`. In enzyme 3, the wrapper is immutable.

**Comment by d-scott** [comment]
Confirmed again:
```
"enzyme": "^3.3.0",
"enzyme-adapter-react-16": "^1.1.1",
```

I'm not using Redux. `wrapper.html()` was correct but `wrapper.find()` couldn't find anything. Added a `wrapper.update()` before the `find` and it worked.

**Comment by willetvary** [comment]
@dmccown1500 The update works great!

**Comment by Und3Rdo9** [comment]
still an issue but calling update() before using stuff like find() works

**Comment by StefanoSega** [comment]
still an issue and in my situation even `wrapper.update();` or `wrapper = wrapper.update();` don't help.

I'm testing a method that does DOM manipulation like creating and appending DOMs to an element that I pass as argument:
```
export const applyRippleEffectElab = (event, element, options) => {
  const ripplerContainer = element.querySelector('.ripple-container');
  const offsetInfo = element.getBoundingClientRect();
  if (ripplerContainer) {
    ripplerContainer.remove();
  }
  const rippleContainer = document.createElement('div');
  rippleContainer.style.position = 'absolute';
  rippleContainer.style.zIndex = 99;
  rippleContainer.style.width = '100%';
  rippleContainer.style.left = '0';
  rippleContainer.style.top = '0';
  rippleContainer.style.right = '0';
  rippleContainer.style.bottom = '0';
  rippleContainer.className = 'ripple-container';
  rippleContainer.style.overflow = 'hidden';
  if (options && options.roundShape) {
    rippleContainer.style.borderRadius = '50%';
  }
  element.appendChild(rippleContainer);

  const maxLength = offsetInfo.width > offsetInfo.height ? offsetInfo.width : offsetInfo.height;
  const sizeMultiplier = (options && options.sizeMultiplier) || 2;
  const circleD = maxLength * sizeMultiplier;

  const ripple = document.createElement('div');
  ripple.style.position = 'absolute';
  ripple.style.width = `${circleD}px`;
  ripple.style.height = `${circleD}px`;
  ripple.style.borderRadius = '500px';
  ripple.style.left = `${(event.pageX - offsetInfo.left) - (circleD / 2)}px`;
  ripple.style.top = `${(event.pageY - offsetInfo.top) - (circleD / 2)}px`;
  ripple.className = 'ripple';
  if (options && options.color) {
    ripple.style.backgroundColor = options.color;
  }
  if (options && options.opacity) {
    ripple.style.opacity = options.opacity.toString();
  }
  rippleContainer.appendChild(ripple);

  ripple.addEventListener('animationend', () => {
    rippleContainer.remove();
  }, false);
};
```

the test looks like:
```
import React from 'react';
import { mount } from 'enzyme';

const materialDesign = require('../../../react/utils/materialDesign');

let wrapper;

describe('applyRippleEffect', () => {
  describe('when clicking with no options', () => {
    beforeAll(() => {
      wrapper = mount(<div id="test" />);

      const event = {
        pageX: 0,
        pageY: 0,
      };
      const element = wrapper.instance();

      materialDesign.applyRippleEffectElab(event, element);
    });

    test('it should create a ripple-container element and inside a ripple element', () => {
      wrapper = wrapper.update();
      console.log(wrapper.html());
      expect(wrapper.find('.ripple-container').length).toBe(1);
      expect(wrapper.find('.ripple-container .ripple').length).toBe(1);
    });
  });
});
```

`console.log(wrapper.html());` returns this:
```
<div id="test"><div style="position: absolute; z-index: 99; width: 100%; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden;" cl
ass="ripple-container"><div style="position: absolute; width: 0px; height: 0px; border-radius: 500px; left: 0px; top: 0px;" class="ripple"></div><
/div></div>
```

**Comment by ljharb** [comment]
Manually manipulating the DOM isn't really something that's idiomatic in React, and it wouldn't surprise me if you ran into issues doing that with jsdom. Please file a new issue if you think there's an issue with enzyme.

**Comment by EvgenyW3** [comment]
For me the problem with .find() was because of wrapping a component with <React.Fragment>. Changed it back to <div> and that did the trick. Seems like Enzyme 3.3.0 doesn't like React.Fragment

**Comment by d-e-p** [comment]
@StefanoSega I had similar problem. I have component written in pure JS that inserts html inside React component. After component mount, I'm using render method before find and it works as expected. Example: 
`
const wrapper = mount(<Provider store={store}><Units /></Provider>);
const nodes = wrapper.render().find('.unit').length);
`

**Comment by wwwennn** [comment]
meet with the same problem. html() is right but find couldn't find the dom. update() doesn't help.

**Comment by paddotk** [comment]
Using `.render().find()` did the trick for me, as in @d-e-p's example. Thanks @d-e-p

**Comment by testacode** [comment]
Using `.render().find()` doesn't allow me to simulate a click for a button. This is still happening.

**Comment by ljharb** [comment]
I wouldn't recommend using `.render()`, nor using `.simulate` at all. If you want to invoke an `onClick` prop, do it explicitly.

**Comment by IamTheHttp** [comment]
still happened for me(I was also updating to React 16 and Enzyme all at once).

If you guys still wonder why people do that, it's because I updated to React 16, and then realized Enzyme has to be updated as well.. I guess for most people there's no reason to update enzyme alone if all is working :)

In any case, wrapper.update() solved it for me, wrapper.html() was showing the right DOM, but wrapper.find(...) was failing

**Comment by ljharb** [comment]
@IamTheHttp you should absolutely downgrade back to react 15, upgrade to enzyme 3 and get everything passing, and *then* update to react 16.

**Comment by ErikParso** [comment]
> @StefanoSega I had a similar problem. I have a component written in pure JS that inserts html inside React component. After component mount, I'm using render method before find and it works as expected. Example:
> 
> ```
> const wrapper = mount(<Provider store={store}><Units /></Provider>);
> const nodes = wrapper.render().find('.unit'));
> ```

This wont allow me to simulate click.
