### ISSUE TITLE
find() with class selector is returning composite components with className prop

### ISSUE THREAD

**Issue by ferdaber** [airbnb/enzyme#1237]
Our codebase has instances of common components that you can assign `className` to that is passed to their root components, like:

```jsx
const Foo = ({ className }) => <div className={className}>Hello</div>
const wrapper = mount(<div><Foo/></div>)

expect(wrapper.find('.foo').length).toBe(1) //actually returns 2
```

Is this expected behavior? Since real CSS selectors are being used I figured that `className` should really only apply to native DOM elements.

**Comment by aweary** [comment]
This is expected with Enzyme 3, you can use `hostNodes` to filter out composite components or use a more specific query like `div.foo`. See https://github.com/airbnb/enzyme/pull/1179

**Comment by ferdaber** [comment]
great, thanks!
