### ISSUE TITLE
Full Dom Rendering .is() doesn't work if dom children has parsing error

### ISSUE THREAD

**Issue by abbr** [airbnb/enzyme#1239]
See screenshot below, notice the 2 watch expressions are conflicting to each other. The dom has a parsing error. If I mount a simple div such as
```
    const wrapper = mount(<div className='sp-main-container' />)
```
It works.

I am using React@16, enzyme@3.

![image](https://user-images.githubusercontent.com/6158277/31312808-ea29ea8a-ab82-11e7-9e88-dcea1954a492.png)

**Comment by ljharb** [comment]
Try `wrapper.children().is('div')`?

**Comment by abbr** [comment]
Works!
