### ISSUE TITLE
Components with refs getting "null" (string) key even if no key is set

### ISSUE THREAD

**Issue by bdwain** [airbnb/enzyme#1240]
I have a component that returns something like
```js
return <Dropdown ref={this.setRef}>...</Dropdown>;
```

I am trying to shallow render it, but when i try to verify the element returned from .get(0), it has a key of "null", the string not the value null, even though there should be no key in the return value.

I've been trying to dig through the code and I think the problem is [here](https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-utils/src/Utils.js#L121). The function `propsWithKeysAndRef` is adding BOTH key and ref to props, even if only one of them has a value. React [stringifies all valid keys in createElement](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L196), and a key is valid if it is not undefined. [This seems like it was an intentional decision](https://github.com/facebook/react/issues/5519). 

The problem seems to be that in enzyme 3, it reruns the node through react.createElement, which now thinks you explicitly set the key to null, and so it sets it to "null". I guess an element with no key gets a "key" property of null, not undefined.

Unfortunately, I don't think the answer is to just not return key as one of the props from `propsWithKeysAndRef` if it is null, because if you explicitly set it to null, then that would be the correct thing to do. 

Is there a way to store the original key value on the node somehow, so that you can look for undefined explicitly?

**Comment by bdwain** [comment]
any update on this? I'd be happy to make a PR i just want to make sure I'm going in the right direction first.

**Comment by ljharb** [comment]
I'm not sure what the solution is; but I think you've correctly identified the bug.

**Comment by ljharb** [comment]
@bdwain what version of react are you using, and which adapter?

**Comment by bdwain** [comment]
version 16.0.0, adapter 16@1.0.1

**Comment by bdwain** [comment]
i can try to look at this later tonight.

**Comment by bdwain** [comment]
added #1254 to fix this.
