### ISSUE TITLE
Lifecycle methods aren't called as expected when state changes

### ISSUE THREAD

**Issue by sawyerh** [airbnb/enzyme#1247]
I've upgraded from Enzyme 2.x to 3.x and noticed that tests that were previously passing now fail. I've limited these down to tests that depend on lifecycle methods like `componentDidUpdate` to be called. 

In https://github.com/airbnb/enzyme/pull/1140 `lifecycleExperimental` was enabled by default, which to my understanding means lifecycle methods like `componentDidUpdate` should be called when `setState` is called on a shallow-rendered component. However, I am not seeing this behavior. 

Even more weird: the [migration guide makes it sound](http://airbnb.io/enzyme/docs/guides/migration-from-2-to-3.html#lifecycle-methods) as if 2.x wouldn't have been calling these lifecycle methods, but I assume they were since my tests were passing before upgrading 🤔 

**I've created a simplified example of what I'm trying to describe here: https://github.com/sawyerh/enzyme-bug**

The lifecycle method `componentDidUpdate` doesn't appear to be called when the component is rendered like this:

```jsx
const wrapper = shallow(<Foo />);
...
wrapper.setState({...})
```

However `componentDidUpdate` does appear to be called when the component is rendered either of these ways:

1. `const wrapper = shallow(<Foo />, { lifecycleExperimental: true });`
2. `const wrapper = mount(<Foo />);`

----

Maybe related: #1201

**Comment by koba04** [comment]
@sawyerh Thanks! I've created a PR to fix this. #1261

**Comment by sawyerh** [comment]
Thanks @koba04! 🙏

**Comment by QuantumInformation** [comment]
{ lifecycleExperimental: true } didn't help me
