### ISSUE TITLE
Lodash and underscore modules are being included in enzyme 3

### ISSUE THREAD

**Issue by ConAntonakos** [airbnb/enzyme#1249]
I noticed in the latest release of enzyme (as of this writing 3.1.0), lodash is included as a top-level module, but eventually, underscore gets pulled in. 

The hierarchy is: 
rst-selector-parser@2.2.2 > nearley@2.7.10 > nomnom@~1.6.2 > underscore@~1.4.4

That seems redundant, no? What do you think?

Thanks for taking the time to inspect this issue!

**Comment by ljharb** [comment]
That seems like an issue you'd need to file on `nomnom`, since that's the module making the decision to depend on underscore, but also, it doesn't matter - a) enzyme is a dev de anyways, and b) more deps is better.

**Comment by kalairaj1403** [comment]
https://github.com/enzymejs/enzyme/issues/1532

rst-selector-parser "^2.2.3" 
	- lodash.flattendeep "^4.4.0"
	- nearley "^2.7.10"

is possible to update sub dependencies nearley from 2.7.10 to 2.20.1 in rst-selector-parser "^2.2.3" in package.json or yarn lock file

nearley@^2.20.1 does not have nomnom package

nearley@^2.7.10:
     "nomnom": "~1.6.2",
     "railroad-diagrams": "^1.0.0",
     "randexp": "^0.4.2"

nearley@^2.20.1:
	commander "^2.19.0"
    	moo "^0.5.0"
    	railroad-diagrams "^1.0.0"
    	randexp "0.4.6"

**Comment by ljharb** [comment]
@kalairaj1403 its using a semver range, so nothing needs to be done - just update your lockfile.
