### ISSUE TITLE
wrapper.instance() returns null under React 16

### ISSUE THREAD

**Issue by jwalton** [airbnb/enzyme#1250]
To reproduce:

    npm install enzyme@3.1.0 react@16.0.0 react-dom@16.0.0 react-test-renderer@16.0.0 enzyme-adapter-react-16@1.0.1

Then create test.js:

```js
const React = require('react');
const {shallow, configure} = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');

configure({adapter: new Adapter()});

const wrapper = shallow(React.createElement('div', null, 'Hello World'));
console.log(wrapper.instance());
```

And finally:

    node test.js

We expect this to print something exciting, instead it just prints 'null'.

**Comment by ljharb** [comment]
SFCs and host nodes don't have instances in React 16.

This isn't in the migration guide (because it's React 16-related, not enzyme 3 related) - #1243 will address this by documenting the difference.

**Comment by jwalton** [comment]
So, my old tests looked like this:

```js
    it('should render', function() {
        let wrapper = shallow(<GenericError>Hi</GenericError>);
        expect(wrapper.getNode()).to.eql(
            <div className='generic-error-message-container'>
                <div className='message'>Hi</div>
            </div>
        );
    });
```

When I try to run this in enzyme 3.1.0, it says getNode() is deprecated and I need to use instance() instead, but now instance() doesn't work for stateless components.  So how do I write this test?

**Comment by jwalton** [comment]
Ah.  I see where I went wrong.  One of my `mount()` tests was complaining that I should use `instance()` instead of `getNode()`, but this is only true for `mount()` and not for `shallow()`.

**Comment by ianlovett** [comment]
Any my mistake was calling it on a functional component :)

**Comment by blu3printchris** [comment]
How do we use enzyme to test a functional component? Is there a different way?

**Comment by ljharb** [comment]
@blu3printchris you don't need the instance to test any component, really - you wrap it, you pass it props, and you assert on what it renders.
