### ISSUE TITLE
getNodeFromInstance: Invalid argument  error on testing html element

### ISSUE THREAD

**Issue by Madhu788** [airbnb/enzyme#1251]
I'm building a demo app with react and redux.

html tag : .tsx file code ==============

    `<div className={`rotator`} id='rotator_id'>`
  
test function : .test.tsx code ==========
```
import * as React from 'react';
import { expect } from 'chai';
import { mount, render, ReactWrapper, shallow } from 'enzyme';
import * as chaiEnzyme from 'chai-enzyme';
import * as _ from 'lodash';
import * as sinon from 'sinon';
chai.use(chaiEnzyme());
```

`function setup() {           
            return shallow(<ContentRotatorSummary {...props} />, { lifecycleExperimental: true });
        }`

`        it('should render rotator html', () => {
            const wrapper = setup();
            expect(wrapper.html()).to.contain('rotator_id');
        });`

When i'm testing using enzyme, I'm getting below error. 

✖ should render rotator html
        PhantomJS 2.1.1 (Windows 7 0.0.0)
      getNodeFromInstance: Invalid argument.
      invariant@src/components/ContentRotatorSummary.test.tsx:309:16
      getNodeFromInstance@src/components/ContentRotatorSummary.test.tsx:688:86
      findDOMNode@src/components/ContentRotatorSummary.test.tsx:21791:60
      createSwiper@src/components/ContentRotatorSummary.test.tsx:12091:471
      componentDidMount@src/components/ContentRotatorSummary.test.tsx:12095:596
      invoke@src/components/ContentRotatorSummary.test.tsx:27577:52
      componentDidMount@src/components/ContentRotatorSummary.test.tsx:27473:28
      src/components/ContentRotatorSummary.test.tsx:33077:39
      perform@src/components/ContentRotatorSummary.test.tsx:27065:24
      batchedUpdates@src/components/ContentRotatorSummary.test.tsx:51379:33
      batchedUpdates@src/components/ContentRotatorSummary.test.tsx:26648:41
      unstable_batchedUpdates@src/components/ContentRotatorSummary.test.tsx:49479:39
      performBatchedUpdates@src/components/ContentRotatorSummary.test.tsx:33049:44
      src/components/ContentRotatorSummary.test.tsx:33073:30
      withSetStateAllowed@src/components/ContentRotatorSummary.test.tsx:24286:5
      ShallowWrapper@src/components/ContentRotatorSummary.test.tsx:33072:38
      shallow@src/components/ContentRotatorSummary.test.tsx:54051:41
      setup@src/components/ContentRotatorSummary.test.tsx:68114:24
      src/components/ContentRotatorSummary.test.tsx:68114:258

**Comment by ljharb** [comment]
Instead of using `.html` at all, why not `expect(wrapper.props()).to.have.property('id', 'rotator_id')`?

This is unrelated to the bug, of course, just curious :-)

@Madhu788 what version of enzyme and react are you using? Note that lifecycleExperimental doesn't exist anymore in enzyme v3.

**Comment by Madhu788** [comment]
We resolved this issue. Thanks for your comments. We used Enzyme@2.9.1. If that lifecycleExperimental doesn't exist in enzyme@3, How do we test those methods using shallow ?

**Comment by ljharb** [comment]
It's enabled by default; you don't need to specify it at all.
