### ISSUE TITLE
Enzyme 3 couldn't test component when ComponentDidCatch happend

### ISSUE THREAD

**Issue by BlackGanglion** [airbnb/enzyme#1255]
My Component:
```javascript
class Error extends React.Component {
  render() {
    throw new Error('ErrorMessage');
    return <div />;
  }
}

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      hasError: false,
      error: null,
      errorInfo: null
    }
  }
  componentDidCatch(error, info) {
    this.setState({
      hasError: true,
      error,
      errorInfo: info
    });
  }
  render() {
    const { hasError } = this.state;
    if (this.state.hasError) {
      return <div className="error-view">error view</div>
    }
    return <Error />
  }
}
```

My test: 
```javascript
const app = mount(<App />);
const errorTip = app.setState({
  hasError: true,
});
expect(app.find('.error-view').length).to.equal(1);
```

When `app` is mount，`app` throws the error and I couldn't get the `app` to test the error view. How do I solve it？

**Comment by nickytonline** [comment]
I'm having similar issues. Please see https://twitter.com/nickytonline/status/924697867750699010. Basically this is my HOC, https://gist.github.com/nickytonline/c758bcbc79e3ca435310bb847fae2c88 and here is the skipped  test that I can't get working, https://gist.github.com/nickytonline/637580f12f14595f7954ecdaf5c8cd88

**Comment by nickytonline** [comment]
I've also tried my errored component as a class instead of an SFC,

```
class ErroredComponent extends React.Component {
  render() {
    throw new Error('Oh no!');
  }
}
```

but it results in the same thing.

**Comment by richardson-trevor** [comment]
Any suggested best practice on this? Has anyone found a solution they're happy with? I'm working on a similar problem.

**Comment by realseanp** [comment]
You can test `componentDidCatch` using a spy method. I am using `expect.spyOn` there's also `sinon`. Here's is a working example of testing `componentDidCatch`:

```js
import Login from './index';
import expect from 'expect';
import React from 'react';
import { mount } from 'utils/enzyme';

function ProblemChild() {
  throw new Error('Error thrown from problem child');
  return <div>Error</div>; // eslint-disable-line
}

describe('<Login />', () => {
  it('should catch errors with componentDidCatch', () => {
    const spy = expect.spyOn(Login.prototype, 'componentDidCatch');
    mount(<Login><ProblemChild /></Login>);
    expect(spy).toHaveBeenCalled();
  });
});
```

**Comment by realseanp** [comment]
You can test `componentDidCatch` using a spy method. I am using `expect.spyOn` there's also `sinon`. Here's is a working example of testing `componentDidCatch`:

```js
import Login from './index';
import expect from 'expect';
import React from 'react';
import { mount } from 'utils/enzyme';

function ProblemChild() {
  throw new Error('Error thrown from problem child');
  return <div>Error</div>; // eslint-disable-line
}

describe('<Login />', () => {
  it('should catch errors with componentDidCatch', () => {
    const spy = expect.spyOn(Login.prototype, 'componentDidCatch');
    mount(<Login><ProblemChild /></Login>);
    expect(Login.prototype.componentDidCatch).toHaveBeenCalled();
  });
});
```

**Comment by QuentinRoy** [comment]
@realseanp Any idea how to remove the annoying console logging? I could mute react's by mocking `global.console` but couldn't mute `jsdom`'s...

**Comment by craigkovatch** [comment]
Possibly related issue on Jasmine: https://github.com/jasmine/jasmine/issues/1453

IMO Jasmine should probably be agnostic of the infrastructure to properly catch errors thrown by React components. Enzyme seems like the more natural place to solve this.

**Comment by gricard** [comment]
@realseanp Nice. I did the same with jest.spyOn() and that got my coverage up to 100%. Thank you!

**Comment by brucewpaul** [comment]
This workaround only tests to make sure that `componentDidCatch`, which is definitely better then nothing. Ideally enzyme should also be able to test that the rendered output if there is an error, and ensure that it was rendered correctly as well.

@ljharb is there a milestone/checklist anywhere of react features not yet supported?

**Comment by ljharb** [comment]
@brucewpaul filed #1553 to track everything.

**Comment by jessicarobins** [comment]
@QuentinRoy I had the same issue and was able to mute jsdom's console by doing:
`jest.spyOn(window._virtualConsole, 'emit').mockImplementation(() => false);`
in a beforeEach. That might be a terrible idea? But it doesn't *seem* to have broken anything...

**Comment by lmenus** [comment]
@jessicarobins That's a good tip! For others reading this, if you want to mute all error output, silence `console.error` as that's the function used by jsdom and doesn't rely on jsdom interface which could change.

**Comment by lesbaa** [comment]
I'd argue that muting errors isn't necessarily the best course of action, error messages are there for a reason, no?

**Comment by kohlmannj** [comment]
Following up on @pizza-r0b's technique, as mentioned here: 
https://github.com/airbnb/enzyme/issues/1255#issuecomment-352529487

`expect` v23.5.0 does not appear to have a `spyOn()` method ([it was donated to Jest](https://github.com/facebook/jest/issues/1679), so that may account for the API difference?). I would like to avoid add another devDependency to my project, so I'm going to avoid sinon for now.

Instead, I've found that the following technique appears to work with `expect().toThrowError()` in Jest 23.5.0, Enzyme 3.4.1, and React 16.4.2.

Spoiler: the technique involves calling Enzyme's [`ReactWrapper.html()`](http://airbnb.io/enzyme/docs/api/ReactWrapper/html.html) and expecting an error to be thrown. You can also do this with Enzyme's [`ShallowWrapper.html()`](http://airbnb.io/enzyme/docs/api/ShallowWrapper/html.html).

## With `mount()`
```jsx
// Login.test.jsx
import React from 'react';
import { mount } from 'enzyme';
import Login from './index';

function ProblemChild() {
  throw new Error('Error thrown from problem child');
  return <div>Error</div>; // eslint-disable-line
}

describe('<Login />', () => {
  it('renders an error', () => {
    const wrapper = mount(<Login><ProblemChild /></Login>);
    expect(() => { wrapper.html(); }).toThrowError('Error thrown from problem child');
  });
});
```

**Note:** you may still want to suppress `console.error()` output, as @jessicarobins suggested above: 
https://github.com/airbnb/enzyme/issues/1255#issuecomment-377311872

As an alternative that also avoids `console.error()` output, consider using `shallow()` and `dive()` with this technique:

## With `shallow()` and [`dive()`]()
```jsx
// Login.test.jsx
import React from 'react';
import { shallow } from 'enzyme';
import Login from './index';

function ProblemChild() {
  throw new Error('Error thrown from problem child');
  return <div>Error</div>; // eslint-disable-line
}

describe('<Login />', () => {
  it('renders an error', () => {
    const wrapper = shallow(<Login><ProblemChild /></Login>);
    expect(() => { wrapper.dive().html(); }).toThrowError('Error thrown from problem child');
  });
});
```

**Comment by geminiyellow** [comment]
@kohlmannj thanks , but when i use `extends` and throw error in constructor, 

```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
```

code is here.

```
class ProblemChild extends PureComponent {
  constructor() {
    super();
    throw new Error('Error thrown from problem child');
  }
  render() {
    return <div>Error</div>; // eslint-disable-line
  }
}
```

**Comment by ljharb** [comment]
When using `mount`, `componentDidCatch` should already work. When using `shallow` on an error boundary, nothing is being rendered that *could* throw, so there's no way to trigger the error.

#1797 will add proper support for this.

**Comment by geminiyellow** [comment]
🙇 thank you!
