### ISSUE TITLE
Example of configuring Enzyme Adapter with Karma

### ISSUE THREAD

**Issue by bostanio** [airbnb/enzyme#1257]
The install instructions detail adding the adapter configuration to your 'setup file'. I can't figure out what the right incantations are for running via Karma. Is there an up to date example of combining Enzyme + Karma with adapter configuration?

**Comment by AntiFish03** [comment]
This is basically what I am using.

```javascript
// spec/helpers/enzyme-config.helper.js

// CommonJS style
// const Enzyme = require('enzyme');
// const Adapter = require('enzyme-adapter-react-16');

// ES6 Import
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

if you are using `tests.webpack.js` style config load it like this.
``` javascript
// spec/tests.webpack.js

var testHelpers = require.context('./helpers');
testHelpers.keys().forEach(testHelpers);
```

or if using `files:[]` in the `karma.config.js`
``` javascript
files: [
  {
    pattern: 'spec/helpers/*.helpers.js',
    included: true
  },
  ...
]
```

**Comment by anthonyhastings** [comment]
I'm having issues with this myself; I'm also using Karma and Webpack together but unless I put the `Enzyme.configure` call inside of the actual spec file, nothing works. I've tried the following:

```
    // Snippet of my Karma configuration.

    files: [
      'tests/test-support/setup-enzyme.js
      'config/runners/full-suite.js'
    ],
    preprocessors: {
      '**/*.js': ['webpack', 'sourcemap']
    },
```

```
    // Contents of `setup-enzyme.js`.

    import Enzyme from 'enzyme';
    import Adapter from 'enzyme-adapter-react-15.4';

    Enzyme.configure({
      adapter: new Adapter()
    });
```

```
    // Contents of `full-suite.js`.

    require('../../tests/test-support/jasmine-util/mock-globals');
    requireAll(require.context('../../tests/test-support/jasmine-util', true, /\.js$/));
    requireAll(require.context('../../tests/test-support/matchers', true, /\.js$/));
    require('../../tests/test-support/setup-polyfills');
    requireAll(require.context('../../', true, /\.spec\.js$/));
```

**Comment by ljharb** [comment]
https://github.com/airbnb/enzyme/issues/1318#issuecomment-342590767 may be helpful.

**Comment by priyajeet** [comment]
@ljharb What if the file(s) to test is dynamic? In other words, if I am running a single test or all tests, I want my `files` section to include just one file or bunch of files. In that comment it assumes that you are running for all files.

**Comment by GreenGremlin** [comment]
The issue is that the helper and the test file are processed as separate files. This means they'll each have their own copy of enzyme.

Another solution is to configure enzyme in a single file and re-export enzymes exports.

``` javascript
/* src/test/enzyme.js */
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({adapter: new Adapter()});

export * from 'enzyme';
```

Then, in your tests import the local copy of enzyme.

``` javascript
/* src/myModule.test.js */
import {shallow} from '../test/enzyme';
```

**Comment by ljharb** [comment]
@GreenGremlin want to make a PR making the docs around karma usage better?

**Comment by GreenGremlin** [comment]
> @GreenGremlin want to make a PR making the docs around karma usage better?

I'll see what I can do.
