### ISSUE TITLE
ReactWrapper::simulate() event 'transitionend' does not exist

### ISSUE THREAD

**Issue by sprockow** [airbnb/enzyme#1258]
It doesn't seem that Enzyme supports transitionend as a valid event, even though it is supported by React components: https://reactjs.org/docs/events.html#transition-events.

Is there a reason for this, or has it not simply not been whitelisted yet? 

Is this an issue within ReactAddons? https://github.com/airbnb/enzyme/blob/92da2b3820a770eac054e6b2fbab608aaae237c9/packages/enzyme-adapter-react-13/src/ReactThirteenAdapter.js#L138

**Comment by ljharb** [comment]
Which version of React added that event?

**Comment by sprockow** [comment]
0.8 ? https://github.com/facebook/react/blob/fb0199b73c90c31d0b04fb5fc0ea6f518ae80860/CHANGELOG.md#react-with-addons-3

Though React-Dom mentions a bug fix for onTransitionEnd in 15.0: https://github.com/facebook/react/blob/fb0199b73c90c31d0b04fb5fc0ea6f518ae80860/CHANGELOG.md#react-with-addons-3

**Comment by sprockow** [comment]
Thank you so much for stepping in and fixing this issue!
