### ISSUE TITLE
Enzyme 3.1.0: Issues with .find

### ISSUE THREAD

**Issue by AntiFish03** [airbnb/enzyme#1259]
Ok first thing this test works in v2 I am working on migrating from v2 -> v3.

``` javascript
beforeEach(function () {
  this.subject = () => {
    return mount(<ModalGallery {...this.props} />);
  };
});

it('Should slide to the previous image when keyboard left arrow is pressed', function () {
  this.props.activeIndex = 3;
  let event = $.Event('keyup'),
    subject = this.subject();
  event.keyCode = 37;
  subject.update();

  expect(subject.find('.item.index-3')).toHaveClassName('active');

  subject.instance().eventHandler('keyup', event);
  subject.update();

  expect(subject.find('.item.index-2')).toHaveClassName('active');
});
```

In v3 I am getting:
On the first expect:
> Expected &lt;div&gt; to have className of ".active" but instead found "item index-3"
> expected: Found node output: &lt;div class="item index-3 active"&gt;&lt;img src="/_karma_webpack_/images/gallery.image4.jpg" style="height: auto; width: auto; margin-top: 0px;"&gt;&lt;/div&gt;

On the second expect:
> Expected &lt;div&gt; to have className of ".active" but instead found "item index-2"
> expected: Found node output: &lt;div class="item index-2 active"&gt;&lt;img src="/_karma_webpack_/images/gallery.image3.jpg" style="height: auto; width: auto; margin-top: 0px;"&gt;&lt;/div&gt;

If I do `subject.html()` before the first expect I get:
``` html
<div class="carousel-inner fade" style="height: auto;">
  <div class="item index-0"><img src="/_karma_webpack_/images/gallery.image1.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-1"><img src="/_karma_webpack_/images/gallery.image2.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-2"><img src="/_karma_webpack_/images/gallery.image3.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-3 active"><img src="/_karma_webpack_/images/gallery.image4.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-4"><img src="/_karma_webpack_/images/gallery.image5.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
</div>
```

If I do `subject.html()` before the second expect I get:
``` html
<div class="carousel-inner fade" style="height: auto;">
  <div class="item index-0"><img src="/_karma_webpack_/images/gallery.image1.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-1"><img src="/_karma_webpack_/images/gallery.image2.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-2 active"><img src="/_karma_webpack_/images/gallery.image3.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-3"><img src="/_karma_webpack_/images/gallery.image4.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
  <div class="item index-4"><img src="/_karma_webpack_/images/gallery.image5.jpg" style="height: auto; width: auto; margin-top: 0px;"></div>
</div>
```

**Comment by AntiFish03** [comment]
I have found a work-around for this right now but find seems to have an unusual behavior here. I have changed:
``` javascript
expect(subject.find('.item.index-3')).toHaveClassName('active');
```
To:
``` javascript
expect(subject.render().find('.item.item-index-3.active').length).toBe(1);
```

Bypassing the `ReactWrapper.find` and using instead `ReactWrapper.render().find()`

**Comment by wheelibin** [comment]
I'm having the same issue, simply doing `component.find(".some-class")` is not finding the element. 

The workaround mentioned above is working for me so thanks for that @AntiFish03!

**Comment by yesmeck** [comment]
I think that's why [hostNodes](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/hostNodes.md) exists?

**Comment by graingert** [comment]
@wheelibin something like this? https://runkit.com/f-ruxton/enzyme-render-find/1.0.0

**Comment by wheelibin** [comment]
@graingert essentially yes, although I am using "shallow"....

```
import React from "react";
import WaterTests from "~/modules/WaterTests";
import { shallow } from "enzyme";

describe("WaterTests.components.AddDoseForm", () => {
  const createComponent = (
    actions = {
      getAllWaterTests: jest.fn()
    },
    waterTests = [],
    formState = {}
  ) => {
    return shallow(
      <WaterTests.components.AddDoseForm
        actions={actions}
        waterTests={waterTests}
        formState={formState}
      />
    );
  };

  test("shows any form validation messages", () => {
    const formState = { validation: { errors: [{ message: "An error" }] } };
    const component = createComponent(undefined, undefined, formState);

    expect(component.find(".form-errors li").length).toBe(1);
  });
...
```

I have many tests setup like this, and .find() no longer returns the elements, changing it to `component.render().find("... ` as mentioned above does work.

**Comment by graingert** [comment]
Can you make a runkit demo

**Comment by wheelibin** [comment]
:-/ Apologies....the issue I mentioned appears to be my fault...I've deleted my comments to avoid more confusion..

**Comment by sroutledge** [comment]
I'm also seeing similar behavior. Unfortunately, the fix of using `.render().find` doesn't work in all my cases, due to some child components being connected. If I render the component to do a `.find`, I get `Could not find "store" in either the context or props of "Connect(Form(myChildComponent))"`.

I will try to create a reproducible case.

**Comment by enthudrives** [comment]
@sroutledge Seems like you are trying to mount a `connected component`. Connected components need a `store` to be passed as prop when mounting. There are a few ways of doing this. 
I find this approach simple: http://enthudrives.com/blog/unit-testing-redux-containers

**Comment by enthudrives** [comment]
`render` renders all children of your component. If one of your children are connected, you would run into this issue. I personally prefer unit testing containers & components (with `shallow`). Your tests would be truly `unit` tests and you wouldn't be affected by the children.

**Comment by jedwards1211** [comment]
@enthudrives well, sometimes you have to test what the children are doing, for example when you're making components to transition children.

**Comment by enthudrives** [comment]
@jedwards1211 You don't have to verify the transition in the child component. The transition happens through `props` which are passed from parent to child.
From the context of the parent, you can see if the props passed to the child has been changed from A -> B.
From the context of child, it is just 2 scenarios with props A and B.

**Comment by graingert** [comment]
It's not really the point whether you should or should not use this approach. The features don't match the documentation

**Comment by ljharb** [comment]
The OP implies to me that this is an issue with the matcher library you were using.

If this is not resolved, please file a new issue.
