### ISSUE TITLE
Unable to get property 'offsetHeight' of undefined or null reference in swiper.js

### ISSUE THREAD

**Issue by Madhu788** [airbnb/enzyme#1260]
We are developing SharePoint framework webparts using react and redux. In there we used swiper.js.
`SCRIPT5007: Unable to get property 'offsetHeight' of undefined or null reference
File: swiper.min.js, Line: 16, Column: 28751`

**Comment by ljharb** [comment]
That seems like an issue with swiper.js; how does this relate to enzyme?

**Comment by Madhu788** [comment]
This is not related to enzyme.We developed the view using swiper. When we are going to render our web parts this occurred.
