### ISSUE TITLE
Where do I put setupTests file

### ISSUE THREAD

**Issue by iiison** [airbnb/enzyme#1265]
Hello, I am following [this guid](http://airbnb.io/enzyme/docs/installation/#working-with-react-15) to setup tests in my project(with React-15). I was going through *ES6:(setup)* and I couldn't get where should I put this test file. and how and where to import the testSetup file. I have tried to put it at root level and in the app directory(where all containers and redux logic is written) but none worked. I am using jest with enzyme. and while running tests I am getting this error:

```bash
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })` 
before using any of Enzyme's top level APIs, where `Adapter` is the adapter 
corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';
```

Or do I need to configure adapter every time?

**Comment by kmcq** [comment]
Hey @iiison, jest will handle requiring the file for each test if you tell it where this file lives. See http://facebook.github.io/jest/docs/en/configuration.html and more specifically, http://facebook.github.io/jest/docs/en/configuration.html#setuptestframeworkscriptfile-string.

So in your package.json file, you'd have something like:
```json
{
  "jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/path/to/your/file.js",
  }
}
```

and in that file you'd require enzyme and use the adapter:
```js
const Enzyme = require('enzyme');
const EnzymeAdapter = require('enzyme-adapter-react-15');

// Setup enzyme's react adapter
Enzyme.configure({ adapter: new EnzymeAdapter() });
```

**Comment by FezVrasta** [comment]
If you use Create React App, you can create a `src/setupTests.js` and put inside it the Enzyme initialization code. CRA will tell Jest to load it before each of your tests automatically.

**Comment by QuantumInformation** [comment]
What if your using https://github.com/wmonk/create-react-app-typescript ?

I have this:

![image](https://user-images.githubusercontent.com/216566/32440994-6ff2c49e-c2ed-11e7-9ca5-9b98c5f9863b.png)


but get:

![image](https://user-images.githubusercontent.com/216566/32441141-11f90aa0-c2ee-11e7-8e56-f92e43db94fb.png)

**Comment by QuantumInformation** [comment]
I also tried this:

```js
  "jest": {
    "setupTestFrameworkScriptFile": "src/setupTests.js"
  }
```
```js
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

```

![image](https://user-images.githubusercontent.com/216566/32441556-1aec75aa-c2f0-11e7-8f24-7790385ffaf8.png)


same error

**Comment by ljharb** [comment]
I believe typescript may be broken by default when importing from CJS - you may need to try `import * as Adapter from ‘enzyme-adapter-whatever’`.

**Comment by adepatie** [comment]
@QuantumInformation Where you able to figure this one out? Having the exact same issue currently.

**Comment by likethemammal** [comment]
Made a PR to clarify Jest setup https://github.com/airbnb/enzyme/pull/1396

**Comment by priyajeet** [comment]
Where would this go for mocha/karma?
I added the adapter logic in the karma.conf.js, however doesn't seem to work

```js
{
...
    files: [
        'node_modules/babel-polyfill/dist/polyfill.js',
        'test/enzyme-adapter.js',
        ...
    ],
    preprocessors: {
        'test/enzyme-adapter.js': ['webpack'],
        ...
    }
...
}
```

**Comment by yinguangyao** [comment]
@priyajeet Hi, were you able to solve this issue?

**Comment by priyajeet** [comment]
@yinguangyao I ended up migrating my repo to use Jest instead. Ripped the bandaid off before it gets worse.

**Comment by yinguangyao** [comment]
@priyajeet hahaha, thanks.
But I have solved this issue in my repo: https://github.com/yinguangyao/msg-board

**Comment by amorfati0310** [comment]
I also have same problem using react-script-ts 
These options in your package.json Jest configuration are not currently supported by Create React App:
  • setupTestFrameworkScriptFile

**Comment by ljharb** [comment]
It’s possible that CRA doesn’t work with a jest setup file without ejecting; if so, that’s a bug you should file.

Since this is both answered here and a part of jest’s documentation that’s unrelated to enzyme, i think this can be closed.

**Comment by nileshgulia1** [comment]
Can anyone please tell me where to keep ```jest.config.js``` in my project ?I tried keeping it in a subfolder inside my root dir but it throws error same as specified by @QuantumInformation .

**Comment by bullgare** [comment]
If you use create-react-app, maybe this solution could help:
https://stackoverflow.com/a/46810504/801426
The idea is that config should be placed in path **src/setupTests.js**.

**Comment by kreedz** [comment]
I had the same issue.
My problem was that I put `"setupFiles": ["<rootDir>/src/setupTests.ts"],` into package.json, but if you have `jest.config.js` than you should place `setupFiles` in that file.

**Comment by jayarjo** [comment]
@QuantumInformation, @adepatie and everybody who uses Create React App + TypeScript - the correct path, that you can use without ejecting from default environment, is `src/setupTests.ts` (notice `.ts` extension).

**Comment by xploreraj** [comment]
For those who are not using `create-react-app`, and only `mocha + enzyme` and not `jest`, how should we configure the setup file?

**Comment by nileshgulia1** [comment]
@xploreraj  There is small a instruction here http://airbnb.io/enzyme/docs/guides/mocha.html . This is a general configuration file we use for mocha , jsdom:
``` javascript
require('babel-register')();

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

documentRef = document;
```

**Comment by mcgodan** [comment]
i can't get it to work in mocha either, I've tried --require setupTests.js in mocha which didn't work

**Comment by dosentmatter** [comment]
I've been working on setting up a starter create-react-app + typescript + mocha project for the past two weeks.
Like others have said, use
`import * as Adapter from 'enzyme-adapter-react-16';`
instead of
`import Adapter from 'enzyme-adapter-react-16';`
in your setup file

Put your setup file at src/setupTests.ts if you are using the default jest. You can see that your `tsconfig.json` already references this file to exclude from the build:
![image](https://user-images.githubusercontent.com/5732253/39387791-910c097c-4a30-11e8-9157-d7ae7ca77124.png)

@mcgodan 
To get mocha working, it requires some setup. If I get the time, I'll write up a blog or something on how to set it up. But for now, here are some pictures:

Add test script to package.json:
![image](https://user-images.githubusercontent.com/5732253/39387884-106bb334-4a31-11e8-8715-1c6c0d22994e.png)

scripts/test.sh:
![image](https://user-images.githubusercontent.com/5732253/39387903-2ab79eec-4a31-11e8-8a3a-994fdc28a5bd.png)

mocha.opts:
![image](https://user-images.githubusercontent.com/5732253/39387942-6766cb6a-4a31-11e8-82ec-83d128f95891.png)

config/enzyme.ts:
![image](https://user-images.githubusercontent.com/5732253/39387944-6fb29498-4a31-11e8-94ac-5cb584adc788.png)

Pretty much you have to set everything for mocha that jest already does in create-react-app-ts. I don't like putting the enzyme.ts file at src/setupTests.ts because it's for tests and not really app source code. I might end up symlinking it just so jest still works.

**Comment by manoharreddyporeddy** [comment]
Several hours wasted, and below config worked;

package.json has

```
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4"
  },
  "devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "^16.3.2"
  },
```

\src\setupTests.js has 

```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
```

Hope that helps.

**Comment by ShawnXiao105** [comment]
@manoharreddyporeddy Thanks, it works!!!! Remove jest > setupTestFrameworkScriptFile key in package.json is very very important.

**Comment by manoharreddyporeddy** [comment]
@ShawnXiao105 glad to hear
I worked in React.js for 2 days :-), its good
but Angular 4/5 is taking on the world, even though React.js is nice
(the problems that you are facing is an example of many changes and old documentation, here React.js needs to be improve)

**Comment by Julian-Jurai** [comment]
For those like me please pay attention to the file name `\src\setupTests.js` its plural!! setupTest**S**

**Comment by HarryDao** [comment]
I believe it should be "<rootDir>/src/setupTests.js", not just "src/setupTests.js"

**Comment by travisCarson** [comment]
Jest looks for the setupTests.js file when you start the test runner. If you have a terminal open somewhere with the test runner in watch mode, you'll get no love.

You don't need to add the following to your package.json unless you've ejected
`"jest": {
  "setupTestFrameworkScriptFile": "<rootDir>/src/setupTests.js"
 }`

**Comment by reywright** [comment]
Is there anyway to "require" the setupTests file? I'd love to just define this once.

**Comment by guilhermefelipesilva** [comment]
![image](https://user-images.githubusercontent.com/11430631/61188647-d2792b80-a658-11e9-8e98-f9c25a82c843.png)

I used `require`:

```js
import * as enzyme from 'enzyme';
const Adapter = require ('enzyme-adapter-react-16') ;

enzyme.configure({ adapter: new Adapter() });
```

It worked!

![image](https://user-images.githubusercontent.com/11430631/61188658-f2a8ea80-a658-11e9-9fef-4852467b95a3.png)

**Comment by ljharb** [comment]
That’s because it’s incorrect to use `import * as` there - that’s typescripts broken-by-default module system.

**Comment by mfaizan1** [comment]
> Just as a precaution, you should restart tests if you add `setupTest.js`.

Scrolled down to comment it , already here :P

**Comment by adrienplg** [comment]
The solution provided by @kirrosh worked for me, for the exception of the import syntax for the Adapter. I used the following with `"typescript": "^3.6.2"`
```
import Adapter from 'enzyme-adapter-react-16';
```

**Comment by kikiondo117** [comment]
If you are using ts with create-react-app . --typescript and you use **script eject** you need to add a new path as the image show you: 


<img width="953" alt="bubu" src="https://user-images.githubusercontent.com/49052662/68601480-0418cc80-046a-11ea-8d12-40fc6184bbe9.PNG">

n.n)/

**Comment by exapsy** [comment]
I've tried every solution I could. Making a `jest.config.js` file in root dir and setting up a `setupFiles` configuration. Then setting up `snapshotSerializers` with `enzyme-to-json` serializer. Then switching between `.ts` and `.js` extensions just in case. Nothing worked really in my `CRA TS` no-inject case.

**What worked** is placing the **jest configuration** inside `package.json`.

**package.json**
```json
{
  "jest": {
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
}
```

But of course you first have to install `npm install --save-dev enzyme-to-json`/`yarn add -D enzyme-to-json` which is something guides didn't inform me of but was quite easy to get that information from errors.

**Comment by iiison** [comment]
@kikiondo117 I like the font you are using. What's the name of this font(if you don't mind 🙏)?

**Comment by kikiondo117** [comment]
Sure, the name is fira code, it's free :D, you can download here ->  https://github.com/tonsky/FiraCode

**Comment by MedinaGitHub** [comment]
i have the same problem when i can use mount =(
![Captura de pantalla de 2020-10-23 11-08-01](https://user-images.githubusercontent.com/16387514/97013926-0ad80c80-1520-11eb-8c51-2361c8652052.png)

**Comment by ruslanguns** [comment]
The answer provided by @kmcq works and fix this issue how ever in favor of the deprecation of "setupTestFrameworkScriptFile" you have to use "setupFilesAfterEnv" which receives an Array of jest setup files:

```json
// package.json

{
  "jest": {
    "setupFilesAfterEnv":  "<rootDir>/path/to/your/file.js",
  }
}
```

Or if you have a jest.config.js file:

```json
// jest.config.js

module.exports = {
  "setupFilesAfterEnv": [
      "<rootDir>/path/to/your/file.js"
   ]
}
```

If your React application is generated by CRA then make sure you add `setupTest.js` file inside `src/*`. If you want to override this behavior follow the steps above.
