### ISSUE TITLE
.find('[type=text]') behaves like .find('[type]')

### ISSUE THREAD

**Issue by lencioni** [airbnb/enzyme#127]
If I have a component that renders a form that has one input with `type=text` on it and a few others that have `type` attributes with other values, `.find('[type=text'])` will give me all the nodes that have a `type` attribute. I would normally expect to get just the one that has a `type` attribute with a value of `"text"`, or see an error. To fix this in my test, I am quoting the value of the attribute: `.find('[type="text"]')`.

**Comment by ljharb** [comment]
This seems like a bug. If you want to compare to the string "text" you absolutely need the quotes - however since `text` isn't a literal in JS, that should throw an error (where as `type=3` would be fine).

**Comment by blainekasten** [comment]
Yeah. It should throw an error.
