### ISSUE TITLE
issue with render/find

### ISSUE THREAD

**Issue by graingert** [airbnb/enzyme#1272]
I can't seem to use .find for classes on a deep rendered wrapper, here's a runkit demo: https://runkit.com/graingert/enzyme-render-find/1.0.0

I thought it might be related to: https://github.com/airbnb/enzyme/issues/1259#issuecomment-336967422 but I don't think it's the same issue

**Comment by hellosmithy** [comment]
Having the same issue for anything rendered via a function. E.g. mapping over a list to a render callback or calling a class method to render anything breaks find functionality.

**Comment by AntiFish03** [comment]
@graingert That is the same problem I can't seem to do a find for anything in a child component but my work around in #1259 was to use the cheerio wrapper and its find method which worked for what I was doing.

**Comment by ljharb** [comment]
This is by design; `render` uses cheerio, and in v1 of cheerio, there's no root element anymore. If you render `() => <div className='foo' />` then your test will work.
