### ISSUE TITLE
.debug() is not on the mount API

### ISSUE THREAD

**Issue by lencioni** [airbnb/enzyme#128]
It is useful to use `.debug()` when using the shallow API, but it is missing from the mount API. It would be nice to add this convenient method to aid in debugging.

**Comment by ljharb** [comment]
Good call! We should have symmetry between the APIs whenever possible anyways.

**Comment by zjzh** [comment]
Hello,
@ljharb ,  could you answer a question which I want to ask and which is puzzling me?
 Why the label, "Good First Task", is not showed the labels, but I can see the label, "Good First Task", in events.

**Comment by ljharb** [comment]
@zjzh posting on an ancient issue about something off topic is not appropriate; in this case, that label used to exist but was deleted many years ago.https://github.com/enzymejs/enzyme/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 may be the label you're looking for.
