### ISSUE TITLE
airbnb.io/enzyme has certificate errors for https

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [airbnb/enzyme#1281]
Expected: should default to https.

Actual: gives a certificate error.

![image](https://user-images.githubusercontent.com/3335181/31782023-aa197444-b4ae-11e7-867e-aad084b6124a.png)

**Comment by ljharb** [comment]
No github pages support https for custom domains: https://github.com/isaacs/github/issues/156

The URL must be HTTP to work properly.
