### ISSUE TITLE
Manually attach a ref to a wrapper?

### ISSUE THREAD

**Issue by ryexley** [airbnb/enzyme#1287]
I'm working on converting an older set of test fixtures from React Test Utils to enzyme, and I have a test that was taking the rendered component (rendered with React Test Utils) and manually attaching a ref to it, like this:

```javascript
const focusStub = sinon.stub();
component.refs.someRef = { focus: focusStub };
```

...and then it executes some logic and runs an assertion to ensure that the focus stub was called as expected.

I'm having some trouble figuring out how I can do this with an enzyme wrapper. Is something like this possible with enzyme? Can someone point me in the right direction?

Thanks.

**Comment by ljharb** [comment]
`wrapper.instance().refs.someRef = { focus: focusStub };`?

**Comment by ryexley** [comment]
_/me dies_

That should have been a _lot_ more obvious to me. Not sure why I didn't consider that. Thanks very much.
