### ISSUE TITLE
`mount(<Component />).is(selector)` not working, but `shallow(<Component />).is(selector)` works

### ISSUE THREAD

**Issue by maximilianschmitt** [airbnb/enzyme#1291]
Hi, I'm trying to replace our Karma tests with jest + enzyme. It appears to me that `.is(selector)` is not working correctly for us:

```javascript
const { mount } = require("enzyme");

const wrapper = mount(
  <FormHelpText>
    Some <strong>formatted</strong> help text
  </FormHelpText>
);

console.log(wrapper.html());

console.log(wrapper.is("div"));
```

outputs:

```bash
# console.log(wrapper.html());

<div class="FormHelpText "><span>Some </span><strong>formatted</strong><span> help text</span></div>

# console.log(wrapper.is("div"));

false # <-- expecting true
```

Is there anything obviously wrong with this?

`<FormHelpText />` is a simple functional component. If I make it just return `<div />` I still get `false` for `wrapper.is('div')`.

However, I can get `true` for `console.log(mount(<div />).is("div"))`.

Also, I get `true` when using `shallow` instead of `mount`.

---

Using:

- react 0.14.9
- enzyme 3.1.0
- enzyme-adapter-react-14 1.0.2
- jest 21.2.1.

**Comment by ljharb** [comment]
This is an intentional difference between shallow and mount; a shallow render "is" what the component *renders*, a mount "is" the component itself.
