### ISSUE TITLE
Grid CSS properties are ommitted

### ISSUE THREAD

**Issue by wojtekmaj** [airbnb/enzyme#1292]
Enzyme version: 3.0
React version 16.0
render method used: mount, but does not seem to matter

I have a simple component that creates a CSS grid based on some parameters. In my component, I have a getter function called gridStyle which builds an object like this:

```
{
      height: '100%',
      display: 'grid',
      gridTemplateRows: 'repeat(1, 1fr)',
      gridTemplateColumns: 'repeat(10, 1fr)' 
}
```

I'm rendering React component like so:

```<div className="Grid" style={this.gridStyle} />```

On Google Chrome, this results in:

```
<div class="Grid" style="height: 100%; display: grid; grid-template-rows: 1fr; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
</div>
```

while in Enzyme, it results in:

```
<div class="Grid" style="height: 100%; display: grid;"></div>
```

**Comment by ljharb** [comment]
When you say "in enzyme", do you mean `render`? Could you elaborate?

**Comment by wojtekmaj** [comment]
I meant doing `mount(<Component />).html()`.

**Comment by ljharb** [comment]
This seems like something React itself is doing in `findDOMNode`, which the adapter uses under the hood.

**Comment by ljharb** [comment]
`.html()` does a server-render, and returns the result.

Try `.debug()`; if that's working, but `.html()` is not, then it's an issue with React, and it needs to be filed there.
