### ISSUE TITLE
setState in componentWillReceiveProps triggers additional render

### ISSUE THREAD

**Issue by savbace** [airbnb/enzyme#1294]
Hi,
I'm using `shallow` rendering with React 16 and have problem with rendering new props.
```js
const component = shallow(<MyComponent title="hello world" />);
// component.render has been called
component.setProps({ color: 'red' });
// component.render has been called but with old props (i.e. without color: 'red')
```
I call `setState`  in `componentWillReceiveProps` which triggers `render` with **new state** but with **old props**.
As I understand calling `setState` inside `componentWillReceiveProps` should not trigger additional render (i.e. should be queued/batched). Render should be called only once along with `nextProps` applied and the new state.

Please, clarify whether this is a correct behavior of shallow rendering?
Thanks!

**Comment by savbace** [comment]
Seems that issue not directly related to Enzyme.
I've discovered a discussion on shallow renderer batched updates facebook/react#10355 recently.
It implies that shallow renderer is not going to support batched updates. See [ReactShallowRenderer.enqueueSetState](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactShallowRenderer.js), it just updates state and immediately renders.

**Comment by ljharb** [comment]
Regardless, batching is something you're not supposed to rely on, but something you're supposed to expect might happen.

I don't think this is an issue with enzyme.

**Comment by abotchen** [comment]
@savbace  I have the same situation.  If you have any solution, reply me.

**Comment by savbace** [comment]
@abotchen, the problem with my code was that in `MyComponent.render` I did not handle a situation with **new state** and **old props** because I relied on batching in `componentWillReceiveProps `. The fix was implied from @ljharb answer: do not rely on batching. So I just added a code to handle the situation above in `render`.
