### ISSUE TITLE
Update docs to remove `lifecycleExperimental` option

### ISSUE THREAD

**Issue by maurocarrero** [airbnb/enzyme#1303]
When `shallow` is used with `lifecycleExperimental` option as false, `componentDidMount` is called.

From [shallow docs](http://airbnb.io/enzyme/docs/api/shallow.html): 
`
options.lifecycleExperimental: (Boolean [optional]): If set to true, the entire lifecycle (componentDidMount and componentDidUpdate) of the React component is called. The current default value is false with enzyme v2, but the next major version will flip the default value to true.
`

You can check the issue in this [repo with example](https://github.com/maurocarrero/react16-enzyme-shallow-did-mount)

Let me know if additional details are needed.
Thanks.

**Comment by blainekasten** [comment]
What version are you using? I think we would want to remove that flag more than fix any old compatibility.

**Comment by maurocarrero** [comment]
Hi @blainekasten, is detailed in the repo's README:
`"enzyme": "^3.1.0",
"enzyme-adapter-react-16": "^1.0.2",`

I would expect that shallow's default behavior avoids running those methods that belongs to a mounted component, but per docs, that would be already changed:
`but the next major version will flip the default value to true`

**Comment by ljharb** [comment]
`lifecycleExperimental` is gone; the flag you want to set is `disableLifecycleMethods: true`.

We may need to update the docs.

**Comment by maurocarrero** [comment]
That option is the one I found to fix the unit tests after upgrading. Everything is in the repo I added at the beginning.

Agree, you may need to update the docs. Thanks.

**Comment by maurocarrero** [comment]
@ljharb I can help with this.

**Comment by maurocarrero** [comment]
https://github.com/airbnb/enzyme/pull/1319
