### ISSUE TITLE
Make `.debug` log automatically

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#1304]
The `.debug` function should probably only be used for debugging and not a trustworthy API to build tests against. The most common use-case is something like:

```
console.log(wrapper.debug())
```

It seems like having to wrap it in a console.log is a bit of friction. I've got a couple ideas on how we could simplify this. I think the main thing we have to watch out for is situations where `console.log` may not be available, or over-written.

### 1. Allow override at the Adapter level.

Add a new option to the configure API to pass in the `stdout` API and use that internally in Enzyme for any and all logging.

### 2. Allow override as an argument for `wrapper.debug`

example impl:

```js
wrapper = {
  debug(logger = console.log) {
    logger(generateDebug())
  }
}
```

This should be a safe change as it wouldn't break anyones tests, but instead potentially double log if they left calls in their code like `console.log(wrapper.debug())`

It might be worth being explicit in the naming that it will log and deprecate `wrapper.debug` in favor of `wrapper.logDebug` or something. bike-shed that one.

**Comment by ljharb** [comment]
Hmm - this would be a breaking change. It seems like the primary benefit is to attempt to prevent people from relying on `debug` output - but since in your proposal the user can pass in a custom logger function, they could always rely on the debug output *being passed into that function* - which means the API contract we'd have to maintain is identical.

**Comment by ljharb** [comment]
Although perhaps it would be better to rename `debug` to something more sensible, I don't think automatically logging really makes sense. I'm going to close this, since it's unlikely we'll add this.
