### ISSUE TITLE
Hpw to attach the ref when componentDidMount

### ISSUE THREAD

**Issue by palaniichukdmytro** [airbnb/enzyme#1307]
I tried to test ref container on mount, but when I update to enzyme 3.x and react 16,  I catch the error and can not found the ref container that expected.
Before:
```jsx
class Automatic extends Component {
.....
    state = {}

    componentDidMount = () => this.focusContainer()
    componentDidUpdate = () => this.focusContainer()

    focusContainer = () => this.refs.container.focus()
....
    render = () => {
        return (
            <div style={{outline: 'none'}}
                onBlur={this.focusContainer}
                ref='container'
            </div>)
    }
}

export default Automatic
```
```jsx
it('should focus container on mount', () => {
        automatic = mount(<Automatic />, mountContext)

        document.activeElement.should.be.equal(automatic.ref('container').node)
    })
```

Error : 
```AssertionError: expected <div style="outline: none;" tabindex="0">........</div> to equal undefined```

I tried like this but got an error 
`expect(automatic.ref('container')).toBeInstanceOf(automatic.constructor)`
`Invalid Chai property: toBeInstanceOf`

**Comment by ljharb** [comment]
What happened on enzyme 3 and React 15? (Upgrading both at the same time is a very bad idea)

**Comment by palaniichukdmytro** [comment]
We can close it, now all work as expected I removed **.node**
` document.activeElement.should.be.equal(automatic.ref('container'))`
