### ISSUE TITLE
child's componentDidMount is not called before parent's componentDidMount

### ISSUE THREAD

**Issue by psychobolt** [airbnb/enzyme#1312]
My project's use case is more complicated, but bellow should illustrate the problem.

Ref:
https://stackoverflow.com/questions/32814970/is-componentdidmount-of-parent-called-after-all-componentdidmount-of-children

In the code, console.log('parent') should be called after console.log('child mount'). However this is not the case in enzyme's mount. Instead, console.log('parent') gets called first.

I am using enzyme version 3.0.0 and React 16.0.0 although docs doesn't state it, the behavior is still the same.

**Comment by ljharb** [comment]
Why did you close this, did you figure it out?

**Comment by psychobolt** [comment]
Yes, I closed it because it is not an issue. It seems that in React 16.0.0, child's componentDidMount gets called after the parent's, which is same with enzyme tests. In my project, I had another subtree that gets mounted earlier with the same components and that just misled me while I was debugging the console.logs.
