### ISSUE TITLE
Missing documentation for getElement()

### ISSUE THREAD

**Issue by darekkay** [airbnb/enzyme#1315]
In the [migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md), it is mentioned to replace `getNode()` with `getElement()` when using `shallow()`. However, the [API](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md) is missing any `getElement()` documentation.

**Comment by pyp** [comment]
Hey @ljharb, I would love to take it. But before I start a couple of questions:
- Should I also add `getElements` that exist but not mentioned in docs? 
- Should I remove `getNode` and `getNodes` from shallow docs?

**Comment by artiebits** [comment]
Hey @ljharb, I would love to take it. But before I start a couple of questions:
- Should I also add getElements that exist but not mentioned in docs?
- Should I remove getNode and getNodes from shallow docs?

**Comment by ljharb** [comment]
Anything you see that needs correcting, please do send a PR for :-)

**Comment by ljharb** [comment]
Closed in #1425
