### ISSUE TITLE
Is it possible to run Enzyme tests in a browser?

### ISSUE THREAD

**Issue by vladimir-rovensky** [airbnb/enzyme#132]
I like the library a lot, but I was wondering if it's possible to run tests written with enzyme in a browser? Say I use the full DOM rendering mode which uses jsdom, then run the test in Chrome. Will it use Chrome's DOM API instead of jsdom? 
I think it would be beneficial to still be able to run tests in a real browser, surely there can be subtle differences between jsdom and the real thing.

Thanks

**Comment by marr** [comment]
I got tests running in the browser with my boilerplate here using browserify and browser-run: https://github.com/marr/my-boilerplate/commit/18d92738fe784c1ae876a3777307fef745bbfbbb

I don't think jsdom is required, even though its pulled into the package.json. I was thinking about using `chai-enzyme` with tape, but that may not possible.

**Comment by milesj** [comment]
I run all my tests through Karma, which launch instances of Chrome and FF. Here's an example of my config: https://github.com/titon/toolkit/blob/3.0/.karma.js
