### ISSUE TITLE
Connecting wrapper component to redux store with shallow

### ISSUE THREAD

**Issue by EugeneDraitsev** [airbnb/enzyme#1324]
Hi! I trying to use enzyme with redux and react-apollo 2. So I have one pretty simple problem, but have no idea how to fix it. I have 1 connected to redux store component and all works fine with this code:

```
import React from 'react'
import { shallow } from 'enzyme'
import configureStore from 'redux-mock-store'
import { MainRoute } from './..'

describe('MainRoute renders without crashing', () => {
  const initialState = { questions: [] }
  const mockStore = configureStore()
  let store
  let container

  beforeEach(() => {
    store = mockStore(initialState)
    container = shallow(<MainRoute store={store} />)
  })

  it('render the connected(MainRoute) component', () => {
    expect(container.length).toEqual(1)
  })

  it('check Prop matches with initialState', () => {
    expect(container.prop('questions')).toEqual(initialState.questions)
  })
})
```

I can pass store to this component and verify passed state. But when I use Apollo 2 (they removed redux integration in 2.x) I need wrap my component like this : 

```
  beforeEach(() => {
    store = mockStore(initialState)
    container = shallow(
      <ApolloProvider client={client}>
        <MainRoute  store={store} />
      </ApolloProvider>,
    )
  })
``` 

And aftert this changes store is not connected to my component. How I can connect wrapped componet with `shallow` ?

**Comment by ljharb** [comment]
You may want to look into `.dive()`.

**Comment by EugeneDraitsev** [comment]
@ljharb, thanks for very fast response! I tried to use `dive()` like `container.find(MainRoute).dive().prop('questions')`  but got error (with wrapped to ApolloProvider component) : 
```
    Invariant Violation: Could not find "client" in the context of "Apollo(Conn
ect(WithFeatureFlags))". Wrap the root component in an <ApolloProvider>
```
Probably I still missed something?

**Comment by ljharb** [comment]
Instead of `.find`, I mean `container.dive().dive()` - one .dive per HOC/provider.

**Comment by EugeneDraitsev** [comment]
If I use `container.dive(MainRoute).prop('questions')` - props is undefinied 
If I use `container.dive(MainRoute).dive().prop('questions')` and all other variations like `container.dive().dive(MainRoute).prop('questions')` - I get error as on example above 
```
Invariant Violation: Could not find "client" in the context of "Apollo(Connect(WithFeatureFlags))". Wrap the root component in an <ApolloProvider>
```

It seems that I am completely confused

**Comment by ljharb** [comment]
`.dive` takes no arguments.

OK, so let's step through this one by one. What is `container`? What is `container.debug()`?

**Comment by EugeneDraitsev** [comment]
`container.debug()` is 
```
    <QueryRecyclerProvider>
      <Apollo(Connect(WithFeatureFlags)) store={{...}} />
    </QueryRecyclerProvider>
```

container.dive().debug(): 
```
  <Apollo(Connect(WithFeatureFlags)) store={{...}} />
```

After 1 more dive I see error as in previous examples

**Comment by ljharb** [comment]
So, since one dive is "Apollo wrapping Connect wrapping WithFeatureFlags", `container.dive().dive().debug()` should be just "Connect wrapping WithFeatureFlags", and `container.dive().dive().dive().debug()` should be just `WithFeatureFlags`?

**Comment by edraitsev** [comment]
@ljharb, Yep you're right, but `container.dive().dive().debug()` throw exception about `<ApolloProvider>` from above. I think I need to try use `mount` for my case, but still hope that I can use `shallow` here

**Comment by ljharb** [comment]
I'm not familiar with Apollo or ApolloProvider; however at this point I'd say it depends on how ApolloProvider is implemented.

I'm assuming here that you're using ApolloProvider in all these dive tests - it's definitely required. Can you confirm that?

**Comment by edraitsev** [comment]
Yep, my component is not working without `ApolloProvide`, so I going to ask Apollo team how to properly mock their components. Thanks for help in investigation, I think you can close this ticket
