### ISSUE TITLE
Support multiple React versions

### ISSUE THREAD

**Issue by simeg** [airbnb/enzyme#1325]
**With the new addition of adapters, is it possible to support multiple versions of React?** Trying to figure out if I should spend time on making my component using enzyme work for multiple versions or if I should just migrate to React 16. Thanks.

**Comment by ljharb** [comment]
Yes! #1321 is imminent which will address this problem.

**Comment by ljharb** [comment]
See https://github.com/airbnb/react-dates/pull/846 for an example of how to use it.
