### ISSUE TITLE
Warn if `context` supplied without corresponding `childContextTypes`

### ISSUE THREAD

**Issue by WickyNilliams** [airbnb/enzyme#1327]
I think it would be useful to warn/error if `context` option is supplied without corresponding `childContextTypes` option (and possibly vice versa, though i imagine that's far less likely to occur). 

In the last few days, a teammate of mine and someone on reactiflux have both made the mistake of omitting `childContextTypes`. So it seems like an obvious place to guide developers in the right direction.

**Comment by ljharb** [comment]
Related to #664.

**Comment by ljharb** [comment]
Now that #664 is merged, if you fail to provide childContextTypes, then children simply won't get your context - so this should no longer require a warning.
