### ISSUE TITLE
Updating root context should trigger a re-render

### ISSUE THREAD

**Issue by tzvipm** [airbnb/enzyme#1329]
We're using react-router in one of our apps, and we mock out the context from the router when testing individual page components. When our component calls `router.push`, we end up seeing that the context changed successfully, but the mounted component doesn't re-render, so the changes are not reflected in the output JSX.

This seems to be a breaking change from enzyme 2.x.

Note that `root.update()` does not fix the problem, because the internal react node was never updated with the changed context.

**Comment by ljharb** [comment]
How do you "mock out" the context?

If the context object doesn't change itself - only gets mutated - then `wrapper.update()` should work.

**Comment by Omniroot** [comment]
We "mock out" the context using a plain javascript object that looks like the context of our app provider's `getChildContext()` output. When our component calls router.push, we simply mutate the `router.location` key on the mocked context.

Upon further reflection on the docs, it seems that indeed `wrapper.update()` should work, as it should trigger a re-render of the root. Unfortunately, it doesn't seem to be doing this.

On looking at the source code, it seems that `root.update()` simply calls the adapter's `getNode` function. In the react 15.4 adaptor, at least, this seems to just call `instanceToTree` on the internal instance, which seemingly just updates the wrapper's references to the underlying react node.

Am I misunderstanding something here? When I manually call `root._reactInternalInstance._instance.forceUpdate()` and then `root.update()` it seems to work.

**Comment by Omniroot** [comment]
any thoughts on this @ljharb ? How can I help move this forward?

**Comment by ljharb** [comment]
I'm not sure what the issue is here yet; if you want to submit a PR with a failing test case, and even better, a fix, that'd be great :-)

**Comment by ljharb** [comment]
Mutating the context in React itself doesn't cause a rerender, so I wouldn't expect enzyme to do it.

Happy to reopen this with a failing test case using a forced rerender.
