### ISSUE TITLE
`find` does not properly traverse the subtree of JSX in custom ReactWrapper.

### ISSUE THREAD

**Issue by tzvipm** [airbnb/enzyme#1330]
As part of a custom layered rendering solution, we create a ReactWrapper with provided JSX. In enzyme 2.x, this worked fine, but in enzyme 3.1, we run in the the following issues:

1. `find(selector)` does not return any matches, whereas `findWith((node) => node.is(selector))` does. It seems that the latter version traverses the subtree whereas the former does not.

2. the predicate in `findWith((node) => node.is(selector))` sometimes gets called with nodes having length `0`, so `node.is(selector)` throws an error. Our solution is to use `node.findWhere(node) => node.length > 0 && node.is(selector))`, which is quite ugly.

**Comment by aweary** [comment]
@Omniroot can you please provide a reduced test case that reproduces the issue? It's difficult to debug this if we can't reproduce it.

**Comment by acidicX** [comment]
We have the same issue, for example here:

```js
  const MockComponent = () => <div />
  const Delay = delay(MockComponent)
  const component = mount(<Delay />)

  expect(component.find('MockComponent').length).toEqual(0)
  jest.runTimersToTime(500)
  expect(component.find('MockComponent').length).toEqual(1)
```

`delay` is just a HOC that prevents rendering the subcomponent for 500ms:

```js
import React, { Component } from 'react'

const time = 500

export default BaseComponent =>
  class Delay extends Component {
    state = {
      ready: false
    }

    componentDidMount () {
      this._timeout = setTimeout(() => this.setState({ ready: true }), time)
    }

    componentWillUnmount () {
      clearTimeout(this._timeout)
    }

    render () {
      return this.state.ready && <BaseComponent {...this.props} />
    }
  }
```

With enzyme v3, the wrapper is always empty. It worked with enzyme v2.

**Comment by Omniroot** [comment]
@acidicX your issue seems a bit different. if you run `component.update()` after the `jest.runTimersToTime(500)` does that fix your issue?

**Comment by acidicX** [comment]
> if you run component.update() after the jest.runTimersToTime(500) does that fix your issue?

It does indeed. Thank you for the hint. Do you really have to do this (it's a mounted component, so it should do it itself - and it is not modified externally)? Did I miss this in the docs somewhere? Or is it a workaround you use?

**Comment by Omniroot** [comment]
Yeah, I also missed that in the docs at first. It's deep inside the migration guide: https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved

**Comment by ljharb** [comment]
This seems answered.
