### ISSUE TITLE
`find('Button').at(0)` does not work after updating to enzyme 3

### ISSUE THREAD

**Issue by SandroMachado** [airbnb/enzyme#1331]
After updating to enzyme 3 this stoped working.

```
component.dive().find('Button').at(1).simulate('click');
```

I get `TypeError: Cannot read property 'children' of undefined`.

If I change to:

```
component.dive().find('Button').simulate('click');
```

I get `Method “simulate” is only meant to be run on a single node. 2 found instead.`

**Comment by ljharb** [comment]
Is the TypeError in the `simulate` call, or in the `at` call?

If the former, this issue should be retitled.

**Comment by ljharb** [comment]
Also, what version of react are you using? What does `component` look like?

**Comment by lazurey** [comment]
I have encountered exactly the same error when I upgraded `react` and `enzyme`

From: `react@15.6.1`, `enzyme@2.9.1`
To: `react@16.0.0`, `enzyme@3.1.1`

I'm using `mount` to test my form component (`redux-form@7.0.3`)

Other packages I have:
```
"react-dom": "16.0.0",
"react-test-renderer": "16.0.0",
"enzyme-adapter-react-16": "1.0.4"
```

I've tried `at(0)`, `first`, `getElement()`, `getElements()[0]`, none of them worked for me.
Could someone suggest anything else to try?
Thanks a lot!

**Comment by ljharb** [comment]
@lazurey please try react 15 with enzyme 3 first; if you upgrade both react and enzyme at the same time, it's not possible to figure out where the issue is.

**Comment by lazurey** [comment]
Hi @ljharb  thanks for the quick reply.
I tried `react@15.6.1` with `3.1.1` and `enzyme-adapter-react-15`, and got the same errors.

```
 Method “simulate” is only meant to be run on a single node. 6 found instead.
```

Code snip:
```javascript
  // simulate
  this.find(`[name="${selector}"]`).simulate('change', { target: { value: 'some_value' } });
  // mount
  handleSubmit = jest.fn();
  const ComponentToTest = () => {
    const store = configureStore(initialState);
    return (
      <MemoryRouter initialEntries={['/']}>
        <Provider store={store}>
          <SearchForm onSubmit={handleSubmit} />
        </Provider>
      </MemoryRouter>
    );
  };
  const component = mount(<ComponentToTest />);
```

Any ideas?

**Comment by ljharb** [comment]
try adding `.hostNodes()` after the find, before the simulate.

**Comment by lazurey** [comment]
Hi @ljharb `.hostNodes()` solved all my errors, thank you so much!

**Comment by SandroMachado** [comment]
If found that diving again in the component solves the issue. This is a different behaviour from enzyme 2. 

Thanks @ljharb for the help.

**Comment by wonderware** [comment]
@ljharb why does adding .hostNodes() fix this? I'm having this same issue with multiple tests, and that fix does solve it, but I can't figure out why...

**Comment by ljharb** [comment]
@wonderware in enzyme 3, `.find` gives both host nodes (divs and other HTML elements) and custom components. `.hostNodes()` filters the list to only include HTML elements.

**Comment by wonderware** [comment]
@ljharb Ah, got it! I had read that, but I think it finally clicked for me. Thanks for the explanation and the help.

**Comment by vikas199** [comment]
adding hostnodes() says that hostNode() is noy a function

**Comment by ljharb** [comment]
@vikas199 it's `hostNodes()`, not `hostNode`.
