### ISSUE TITLE
forEach function is undefined

### ISSUE THREAD

**Issue by zenjava** [airbnb/enzyme#1332]
```jsx
  const wrapper = render((
      <div>
        <div className="foo bax" />
        <div className="foo bar" />
        <div className="foo baz" />
      </div>
    ));

    wrapper.find('.foo').forEach((node) => {
      expect(node.hasClass('foo')).to.equal(true);
    });
```
result is TypeError: wrapper.find(...).forEach is not a function

**Comment by ljharb** [comment]
`render` provides a wrapper using `cheerio` - cheerio doesn't provide a `.forEach` method; it provides an `.each` method.

`.forEach` is only present on `shallow` and `mount` wrappers.
