### ISSUE TITLE
Where to put setup file for CRA

### ISSUE THREAD

**Issue by lindgr3n** [airbnb/enzyme#1336]
Would you accept a PR for updating the [Install documentation](https://github.com/airbnb/enzyme/tree/master/docs/installation) with a note where to create the setup file when using Create React App? Or maybe something to be added in Common Issues?

Maybe its not a big problem but i needed some searching before i found issue #1265 and @FezVrasta 
 comment that helped me in the right direction!

Create a file src/setupTests.js and put setup content inside it.

**Comment by likethemammal** [comment]
Mentioned it in this PR: https://github.com/airbnb/enzyme/pull/1396

**Comment by FezVrasta** [comment]
The thing is that with CRA this config is automatic, so people just have to create the `setupTests.js`, without any ejection or custom config.
