### ISSUE TITLE
hasClass does not work on root ReactWrapper

### ISSUE THREAD

**Issue by amccloud** [airbnb/enzyme#134]
I think this is because `MountedTraversal#instHasClassName` short circuits to false if the instance does not pass the `isDOMComponent` check. Could we relax the check?

Example test case (React 0.14):

```javascript
const shallowComponent = shallow(<Video src="example.mp4" />);
const mountComponent = mount(<Video src="example.mp4" />);

// From ShallowTraversal
// Works!
assert.equal(shallowComponent.node.props.className, 'Video');

// Works!
assert.isTrue(shallowComponent.hasClass('Video'));

// Fails :( because isDOMComponent(mountComponent.node) is false
// Would otherwise pass
assert.isTrue(mountComponent.hasClass('Video'));

// From MountedTraversal (without isDOMComponent check)
// Works!
assert.equal(findDOMNode(mountComponent.node).className, 'Video');

// Works! ... but seems unnecessary
assert.isTrue(mountComponent.find('.Video').hasClass('Video'));
```

**Comment by lelandrichardson** [comment]
hmmm. @amccloud this is an interesting side effect of how both react + enzyme is implemented. The react render tree is sort of a two-dimensional graph, where-as in shallow it is one-dimensional.  It's hard to know what the right implementations are.

I need to look at what the side effects of this are, but I suspect relaxing the isDOMComponent requirement will end up doubling the number of results getting returned for class-based selection...

```jsx
const Bar = () => (
  <div className="bar" />
);
const Foo = () => (
  <div><Bar /></div>
);

const wrapper = mount(<Foo />);
```

```jsx
// with your suggested change:
wrapper.find('.bar');
// <Bar />
// <div className="bar" />
```
```jsx
// right now it does this...
wrapper.find('.bar');
// <div className="bar" />
```

**Comment by dozoisch** [comment]
I have the exact same issue. Was working with < 1.6. I've also tested on 2.0.0, same issue.

Here is a minimal example to repro

```js
const TestComponent = ({ children, className }) => (
  <div className={className}/>
);

describe('TestComponent', () => {
  it('mount allows us to set custom props', () => {
    const wrapper = mount(<TestComponent className="test" />);
    assert(wrapper.hasClass('test')); // false
  });
  it('shallow allows us to set custom props', () => {
    const wrapper = shallow(<TestComponent className="test" />);
    assert(wrapper.hasClass('test')); // true, as expected
  });
});
```

Note: `.props()` returns an empty object.

**Comment by lelandrichardson** [comment]
Hmm. This seems like a real bug. Will try to take a look at this ASAP. It may be worthwhile to put the fix in as a patch to `1.x` branch as well.

**Comment by ryanalane** [comment]
The crux of this behavior seems to be various incompatibilities with mounting SFCs, due them not having proper react instances by design, but which enzyme relies on to render certain values. #220 contains workaround fixes for `props()` and `debug()` to return useful values for SFCs.

However, hasClass() and its cousins in MountedTraversal are all blocked behind the same `isDOMComponent` check as @amccloud mentioned. Should we consider a different checking strategy to allow SFCs to have fully-functional wrappers when mounted?

**Comment by egeste** [comment]
I'm seeing this same behavior in 2.3.0

**Comment by devrelm** [comment]
I'm still seeing this in 2.4.1 as well. I'm not sure if it's for the same reason, but it has the same behavior of `hasClass` working with `shallow`, but not `mount`.

**Comment by christian-schulze** [comment]
I just spent hours trying to figure out why tests were failing using `hasClass`. `wrapper.html()` shows me the class is there, and yet `hasClass` still returns false. This is really frustrating and unexpected behaviour, which wastes everybody's time.

May I suggest we document this in the readme, with some alternatives for checking if the wrapper has a class?

**Comment by bbnnt** [comment]
does this https://github.com/airbnb/enzyme/pull/677/files/e9ede3e2eac83bc8af7e51058616ff11acc1da3f#diff-2f849fa739461853c70ddd193891074f (#677) close the issue ?

**Comment by nibblesnbits** [comment]
Has this commit made it into an updated npm package?  I'm still seeing it in 2.7.1.

**Comment by jacek213** [comment]
Have the same problem on `3.0.0` with react `0.16`, `.html()` shows the class is in there but hasClass returns false.

**Comment by rooch84** [comment]
I'm also seeing it in 3.1.0.

**Comment by ljharb** [comment]
@jacek213 @rooch84 can you file a new issue for enzyme 3?

Note that this is likely an issue with the fact that shallow wrappers represent what the component *renders*, but mounted wrappers represent *the component* itself.

**Comment by rooch84** [comment]
I think I've finally figured out my issue - because I'm using Meteor, the react components are wrapped with a ReactMeteorDataComponent.  So I need to find my component first before I can then inspect its classes, props, etc.

**Comment by ljharb** [comment]
@rooch84 that's what `.dive()` is for.

**Comment by rooch84** [comment]
@ljharb But I thought dive only worked on shallow?

**Comment by ljharb** [comment]
@rooch84 ah, true. then yes, if you're using `mount`, you'll need to find your component first.

**Comment by josh08h** [comment]
I have the same issue whilst using React@15.5.4 and Enzyme@3.1.1.
```
> wrapper.html()
"<div class="fixedDataTableCellLayout_wrap1 public_fixedDataTableCell_wrap1 Cells__closedAccount___q0Nnb Cells__attributeCell___2-rsR"><div class="fixedDataTableCellLayout_wrap2 public_fixedDataTableCell_wrap2"><div class="fixedDataTableCellLayout_wrap3 public_fixedDataTableCell_wrap3"><div class="public_fixedDataTableCell_cellContent"><div title="CR6737" class="data_fb_panel" data-fb-panel="ref" style="width: 206px;">CR6737</div></div></div></div></div>"


>wrapper.hasClass('Cells__closedAccount___q0Nnb')
false
```

**Comment by ljharb** [comment]
yes; `wrapper.html()` returns the inner HTML, not the outer HTML. `wrapper.debug()` will show this.
