### ISSUE TITLE
Error: Cannot find module 'react-dom/lib/ReactTestUtils' After Updating react/react-dom@16.0 and enzyme 3 react-test-renderer 16

### ISSUE THREAD

**Issue by ghost** [airbnb/enzyme#1340]
I want to upgrade my react version to 16.0 after updating i faced issues then i figured out that i need to update my enzyme to version 3 react-dom - 16 

after updating im getting the below error no clue on whats going on 

`to be executed: "mocha --opts mocha.opts "src/main/javascript/**/*.test.js""
Configuring Mocha...
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
module.js:471
    throw err;
    ^

Error: Cannot find module 'react-dom/lib/ReactTestUtils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)`

Please find the below package.json for ref 

```json
 "dependencies": {
    "bootstrap": "^3.3.7",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "^0.9.0",
    "fixed-data-table": "^0.6.3",
    "flux": "^2.1.1",
    "font-awesome": "^4.7.0",
    "gel-bootstrap-3": "^0.6.23",
    "google-maps-react": "^1.0.19",
    "invariant": "^2.2.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "loader-utils": "^1.1.0",
    "lodash": "^4.16.6",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.6",
    "promise": "^7.1.1",
    "prop-types": "^15.5.8",
    "react": "^16.0.0",
    "react-bootstrap": "^0.30.6",
    "react-document-title": "^2.0.2",
    "react-dom": "^16.0.0",
    "react-esri-map": "0.1.19",
    "react-flexbox": "^3.1.1",
    "react-hotkeys": "^0.9.0",
    "react-infinite-scroller": "^1.0.4",
    "react-overlays": "^0.6.10",
    "react-router": "^2.5.2",
    "react-router-bootstrap": "^0.23.1",
    "react-router-transition": "0.0.5",
    "react-scroll": "^1.5.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "whatwg-fetch": "^0.11.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.11.0",
    "babel-register": "^6.14.0",
    "better-npm-run": "0.0.8",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.5.0",
    "copy-webpack-plugin": "^2.1.1",
    "enzyme": "^3.1.1",
    "enzyme-adapter-react-16": "^1.0.4",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^5.2.2",
    "eventsource-polyfill": "^0.9.6",
    "globule": "^1.0.0",
    "h2o2": "^5.4.0",
    "hapi": "^13.3.0",
    "hapi-webpack-plugin": "^1.3.0",
    "html-webpack-plugin": "^2.29.0",
    "inert": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "json-loader": "^0.5.4",
    "mocha": "^2.5.3",
    "mocha-junit-reporter": "^1.11.1",
    "nodemon": "^1.11.0",
    "nyc": "^7.1.0",
    "react-addons-perf": "^15.4.2",
    "react-addons-test-utils": "^15.5.1",
    "react-dom": "^16.0.0",
    "react-hot-api": "^0.4.5",
    "react-hot-loader": "^1.3.0",
    "react-test-renderer": "^16.0.0",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-hot-middleware": "^2.6.0"
  }
}
```

**Comment by ljharb** [comment]
Upgrading to react 16 prior to upgrading to enzyme 3 means it's nearly impossible to figure out the issues.

Can you roll back to React 15, successfully upgrade to enzyme 3, and *then* upgrade to React 16?

**Comment by Santhuraoi** [comment]
@ljharb 

I just tried to update my enzyme version getting the below issue.

running better-npm-run in C:\Users\C843252\Desktop\tj-view
Executing script: test:mock

to be executed: "mocha --opts mocha.opts "src/main/javascript/**/*.test.js""
Configuring Mocha...
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
module.js:471
    throw err;
    ^

Error: Cannot find module 'enzyme/build/react-compat'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)


below are my list of dependencies and devDependencies in my package.json 
`"dependencies": {
    "bootstrap": "^3.3.7",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "^0.9.0",
    "fixed-data-table": "^0.6.3",
    "flux": "^2.1.1",
    "font-awesome": "^4.7.0",
    "gel-bootstrap-3": "^0.6.23",
    "google-maps-react": "^1.0.19",
    "invariant": "^2.2.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "loader-utils": "^1.1.0",
    "lodash": "^4.16.6",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.6",
    "promise": "^7.1.1",
    "prop-types": "^15.5.8",
    "react": "^15.4.2",
    "react-bootstrap": "^0.30.6",
    "react-document-title": "^2.0.2",
    "react-dom": "^15.4.2",
    "react-esri-map": "0.1.19",
    "react-flexbox": "^3.1.1",
    "react-hotkeys": "^0.9.0",
    "react-infinite-scroller": "^1.0.4",
    "react-overlays": "^0.6.10",
    "react-router": "^2.5.2",
    "react-router-bootstrap": "^0.23.1",
    "react-router-transition": "0.0.5",
    "react-scroll": "^1.5.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "whatwg-fetch": "^0.11.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.11.0",
    "babel-register": "^6.14.0",
    "better-npm-run": "0.0.8",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.5.0",
    "copy-webpack-plugin": "^2.1.1",
    "enzyme": "^3.1.1",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^5.2.2",
    "eventsource-polyfill": "^0.9.6",
    "globule": "^1.0.0",
    "h2o2": "^5.4.0",
    "hapi": "^13.3.0",
    "hapi-webpack-plugin": "^1.3.0",
    "html-webpack-plugin": "^2.29.0",
    "inert": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "json-loader": "^0.5.4",
    "mocha": "^2.5.3",
    "mocha-junit-reporter": "^1.11.1",
    "nodemon": "^1.11.0",
    "nyc": "^7.1.0",
    "react-addons-perf": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-hot-api": "^0.4.5",
    "react-hot-loader": "^1.3.0",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-hot-middleware": "^2.6.0"
  }
}
`

**Comment by ljharb** [comment]
@Santhuraoi i'm not sure what would be looking for `enzyme/build/react-compat`, that file was removed entirely for v3.

**Comment by Santhuraoi** [comment]
@ljharb I tried to update the only enzyme from 2.2.0 to 3.1.1 but I'm unable to run the test cases.

Please tell me what all steps i need to follow when i'm updating from 2 to 3 i have gone through your enzyme 2-3 migration guide i followed all the steps.

when i'm updating enzyme to 3 what is the best chai-enzyme version i need to use .

Please give me your valuable inputs i tired all the things but nothing is working at all.

**Comment by ljharb** [comment]
Use the latest chai-enzyme version, and it should work. Can you be more specific about "unable to run the test cases"?

**Comment by Santhuraoi** [comment]
@ljharb finally most of test cases are running thanks for your help, But when i import render from enzyme those test cases are failing could you please tell me why

**Comment by ljharb** [comment]
Probably because cheerio 1.0 works differently than 0.22.

Specifically, instead of containing the rendered nodes, the render wrapper now *is* the rendered nodes.

**Comment by lyndouchehero** [comment]
Hi everyone, I have a problem, I used react JS version 0.12 and I develop by es5, I need to implement the test by Jest, can you help me , that's the dependency , `  "dependencies": {
    "async": "~1.4.2",
    "events": "^1.0.2",
    "flux": "^2.0.1",
    "html-entities": "^1.1.2",
    "jest-environment-jsdom": "^22.4.1",
    "keymirror": "^0.1.1",
    "object-assign": "^2.0.0",
    "react": "^0.12.2",
    "react-router": "^0.11.6",
    "react-test-renderer": "^1.0.0",
    "underscore": "^1.7.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "~5.2.2",
    "cordova": "5.4.0",
    "jest-cli": "^22.4.2",
    "json-loader": "~0.5.2",
    "node-libs-browser": "~0.5.2",
    "raw-loader": "~0.5.1",
    "regenerator-runtime": "^0.11.1",
    "webpack": "~1.10.0",
    "webpack-dev-server": "^1.9.0",
    "xml-loader": "~1.0.0"
  },
  "scripts": {
    "start": "set NODE_ENV=productio webpack -p && cordova run --android",
    "test": "jest --watch --verbose"
  }` please thank you in advance...

**Comment by ljharb** [comment]
Closing, because this user deleted their account.

**Comment by zhoulujun** [comment]
https://www.zhoulujun.cn/html/tools/webpack/2016_0217_6459.html
  "react": "^16.7.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.7.0",
react-dom 16 根本就没有lib/ReactTestUtils 这玩意儿。
于是修改，react-addons-test-utils index 文件,坑还是未填好
//module.exports = require('react-dom/lib/ReactTestUtils');
module.exports = require('react-dom/test-utils');
最好还是降级到15.x ，期待官方修复！
