### ISSUE TITLE
Single rendered element in array not equal to that element in Enzyme 3

### ISSUE THREAD

**Issue by hmaracic** [airbnb/enzyme#1347]
In Enzyme 3 two shallow-rendered elements are declared not equal if one of their child elements is wrapped in a single-element array, i.e.

```
<div className='parent-component-class'>
  <div key={'a'} className='asd'></div>
  <div key={'b'} className='fgh'></div>
</div>
```
is not equal to
```
<div className='parent-component-class'>
  <div key={'a'} className='asd'></div>
  {[<div key={'b'} className='fgh'></div>]}
</div>
```

On the other hand,
```
<div className='parent-component-class'>
  <div key={'b'} className='asd'></div>
</div>
```
is equal to
```
<div className='parent-component-class'>
  {[<div key={'b'} className='asd'></div>]}
</div>
```

In Enzyme 2, both of these were equal.

The above test suite is available at
[https://github.com/hmaracic/enzyme-array-test](https://github.com/hmaracic/enzyme-array-test)
with one tag being with Enzyme 2 (passing) and the other tag being with Enzyme 3 (failing).

Is this a bug, expected behavior or maybe an improper use of the framework?

**Comment by ljharb** [comment]
Thanks; the test repo was very helpful. All your tests are now passing with this fix.
