### ISSUE TITLE
Create-React-App: Jest: Enzyme Internal Error => message not shown

### ISSUE THREAD

**Issue by valorize** [airbnb/enzyme#1354]
When I use create-react-app and complement it with enzyme as written in their docu and run the following test code:

```
it('shallow Filter isSearchFocused', () => {
	...
	const wrapper = shallow(<Filter {...props} />);
	console.log(wrapper.find('.filter-prediction'));
	wrapper.find('.omf-filter-prediction').simulate('click');
});
```
Enzyme outputs the following:
```
 FAIL  src/components/__tests__/Filter.js
   Console

    console.log src/components/__tests__/Filter.js:30
      ShallowWrapper { length: 2 }

   shallow Filter isSearchFocused

    Method simulate
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1618:17)
      at ShallowWrapper.simulate (node_modules/enzyme/build/ShallowWrapper.js:929:21)
      at Object.<anonymous>.it (src/components/__tests__/Filter.js:31:41)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Expected would be a message from  `throw new Error('Method \u201C' + fnName + '\u201D is only meant to be run on a single node. ' + String(this.length) + ' found instead.');` at `node_modules/enzyme/build/ShallowWrapper.js:1618`

**Comment by ljharb** [comment]
What version of enzyme are you using?

**Comment by valorize** [comment]
It should be 20.0.4 https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/package.json

**Comment by ljharb** [comment]
@valorize that'd be a jest version; that package.json doesn't specify an enzyme version.

**Comment by valorize** [comment]
Your right. It's enzyme@3.1.0 in combination with enzyme-adapter-react-15@1.0.3.

**Comment by ljharb** [comment]
I'm not sure about that error message; if you wrap the `simulate` call in a `try`/`catch` I would expect you'd see the expected error message.

**Comment by valorize** [comment]
I tried different positions of the try/catch: Just around my `simulate`. Around all tests in `it` and around `it` with

```
try {
    wrapper.find('button').simulate('click'); // click all buttons, expect to at least call deleteItem once
}
catch(error) {
    console.log(error.message);
}
```

It always just shows 
```
FAIL  src/components/tests/BasketListItem.js
   shallow BasketListItem

    Method simulate
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1618:17)
      at ShallowWrapper.simulate (node_modules/enzyme/build/ShallowWrapper.js:929:21)
      at Object.<anonymous>.it (src/components/tests/BasketListItem.js:16:32)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

or 

```
Console

    console.error src/components/tests/BasketListItem.js:19
      Method simulate
```

**Comment by ljharb** [comment]
hmm - there's a curly quote in the message. Is there any chance you're using a non-UTF8 encoding anywhere, including in your terminal? In particular, if you're on a Mac and using iTerm, can you try in the normal Terminal?

**Comment by valorize** [comment]
Which curly quote you refer to? The `{ length: 2 }`?

**Comment by ljharb** [comment]
Closing; happy to reopen with more information.
