### ISSUE TITLE
Cannot read property 'outerHTML' of undefined with mount() on Redux connected component

### ISSUE THREAD

**Issue by apucacao** [airbnb/enzyme#1355]
Hey all,

We're migrating from Karma/mocha/chai/... to Jest; we use Enzyme everywhere.

We're running into strange problems when using `mount` with (Redux) connected components. For example, here is a simple test:

```js
test('should render', () => {
  const Content = () => <div>content</div>;
  const store = createStore();
  const Connected = connect(() => ({}))(Content);
  const result = mount(
    <Provider store={store}>
      <Connected />
    </Provider>,
  );

  expect(result.html()).toEqual('<div>content</div>');
});
```

That fails with the following error:

```
    TypeError: Cannot read property 'outerHTML' of undefined

      at ReactWrapper.<anonymous> (../../node_modules/enzyme/build/ReactWrapper.js:728:45)
      at ReactWrapper.single (../../node_modules/enzyme/build/ReactWrapper.js:1421:25)
      at ReactWrapper.html (../../node_modules/enzyme/build/ReactWrapper.js:726:21)
      at Object.<anonymous> (components/__tests__/connect-test.js:19:22)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (../../internal/process/next_tick.js:188:7)
```

`console.log(result.debug())` outputs:

```
    <Provider store={{...}}>
      <Connect(Content)>
        <Content dispatch={[Function]}>
          <div>
            content
          </div>
        </Content>
      </Connect(Content)>
    </Provider>
```

I haven't been able to find much about this on the Web. Does anyone have any clues as to what is going on?

We get other variants of that one depending on what we're testing. In other tests, `outerHTML` is `classList` for example.

We're using React 15.6.0.

Thanks!

**Comment by ljharb** [comment]
What version of enzyme and cheerio are you using?

**Comment by ljharb** [comment]
The specific code erroring is:
```js
  return node === null ? null : node.outerHTML.replace(/\sdata-(reactid|reactroot)+="([^"]*)+"/g, '');
```

This would happen if `node` is anything that lacks an `outerHTML` property - and `node` comes from `adapter.nodeToHostNode` - which is a wrapper around `React.findDOMNode`. So, I can only imagine it's a React + Karma bug, if anything.

Closing, but happy to reopen with more information.
