### ISSUE TITLE
Enzyme ERROR: 'There is no timestamp for /base/enzyme.js!' in unit testing React app

### ISSUE THREAD

**Issue by VishalGulati** [airbnb/enzyme#1358]
I tried using Enzyme for unit testing my React application with karma as test runner but facing below error:

```
    PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR: 'There is no timestamp for /base/enzyme.js!'
    
    14 11 2017 12:25:32.469:WARN [web-server]: 404: /base/enzyme.js
    PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
      Error: Script error for "enzyme", needed by: C:/.../testlib/unit/component/Shared/Butto
    n/Button-test.js
      http://requirejs.org/docs/errors.html#scripterror
      at C:/.../node_modules/requirejs/require.js:143
```

As suggested in Docs, I installed following modules:

```
    "enzyme": "^2.9.1",
    "enzyme-adapter-react-15.4": "^1.0.5",
    "react-test-renderer": "^15.6.2",
```

My React version is `15.1.0`. And my test file is as follows:

```
    import Button from 'lib/component/Shared/Button/Button';
    import { shallow } from 'enzyme';
    import { assert, expect } from 'chai';
    
    describe('component/Shared/Button', () => {
        describe('render', () => {
            const wrapper = shallow(<Button />);
            expect(wrapper.find('button').hasClass('btn-blue')).to.equal(true);
        });  
    });
```
    
I guess I am surely missing some configuration, hope someone can help! TIA.

**Comment by ljharb** [comment]
Can you try with enzyme 3? We don't really support enzyme 2 anymore.

**Comment by VishalGulati** [comment]
@ljharb Does Enzyme v3 works with React 15.1.0? I wont be able to update React as this is an existing application live.

**Comment by ljharb** [comment]
Yes, absolutely - it works with React 0.13 and greater; you just need to select the appropriate adapter.

**Comment by VishalGulati** [comment]
@ljharb I have installed v 15.4 of module enzyme-adapter-react-15.4 as stated [here](http://airbnb.io/enzyme/docs/guides/migration-from-2-to-3.html):
I also see that this configuration is to be included:

import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

Which file should this be placed in? Do i need to import this somewhere as well?

**Comment by ljharb** [comment]
@VishalGulati that file should be brought in prior to all your tests; exactly how to do it depends on your test runner.

**Comment by VishalGulati** [comment]
@ljharb : Tried with Enzyme v3, did not work. PFB the details:

modules installed:

```
"enzyme": "^3.1.1",
"enzyme-adapter-react-15.4": "^1.0.5",
```

Created a file enzyme.config.js:
```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-15.4';

Enzyme.configure({ adapter: new Adapter() });
```

Included the above file in my karma runner conf:
```
files: [
        // test setup
        ...........
        'test/unit/testutils/enzyme.config.js',
        ..........
]
```

Got following error:
```
Running "karma:dev" (karma) task
14 11 2017 15:55:12.394:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
14 11 2017 15:55:12.394:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
14 11 2017 15:55:12.415:INFO [launcher]: Starting browser PhantomJS
14 11 2017 15:55:13.986:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket _Me2FalpHyjaMBWPAAAA with id 13784764
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
  at test/unit/testutils/enzyme.config.js:1


Warning: Task "karma:dev" failed.
```

**Comment by VishalGulati** [comment]
@ljharb Could you please let me know if I am missing something. I am really helpless with this setup. The steps have all been followed but still got no clue why it does not work. There is no info over net as well. I am stuck!

**Comment by VishalGulati** [comment]
@zeke @roberto @schleyfox @indexzero anyone of you could please step up?

**Comment by ljharb** [comment]
"Use of reserved word 'import'" means you're not babel-transpiling your files before they get to phantom.

I'm going to close this, since there's nothing actionable from enzyme's side here.
