### ISSUE TITLE
`simulate` does not return the enzyme wrapper (migration 2.x to 3.x)

### ISSUE THREAD

**Issue by juanca** [airbnb/enzyme#1362]
Hello!

I was not able to find any documentation about dropping the type signature for `simulate`. Was this mentioned somewhere? (I'm trying to document all my changes with some changelog references).

If this wasn't intentional: should `simulate` return the wrapper? This facilitates complex behavior involving a chain of simulated events.

**Comment by ljharb** [comment]
Type signatures aren't supported by this library, so that's a bug you'll have to file on wherever the type signatures come from.

`simulate` has never returned the wrapper as far as I'm aware; in general, simulate should be avoided in favor of explicitly invoking props.

**Comment by juanca** [comment]
For posterity sake: Enzyme 2.x's `simulate` would return the wrapper (and I used it to chain many simulated events). However, this is not desirable given Enzyme 3.x's wrapped caches (where elements can go stale).

Are there any plans to officially deprecate `simulate`? I would like more information to encourage my team to stop using `simulate`.

**Comment by ljharb** [comment]
I would like to do so, and I’ve commented as such on many issues on this repo. There’s no timeline or official commitment to do so yet, though - just my stated intention.
