### ISSUE TITLE
`.prop(...)` is not actually using the instance props (regardless of hard-coded `.update()`)

### ISSUE THREAD

**Issue by juanca** [airbnb/enzyme#1368]
Environment:

- enzyme @ 3.1.1
- enzyme-adapter-react-15 @ 1.0.5

```
> wrapper.prop('errorMessage')
< undefined

> wrapper.instance().props.errorMessage
< ""

> wrapper.update()
< ShallowWrapper {length: 1, Symbol(enzyme.__root__): ShallowWrapper, Symbol(enzyme.__unrendered__): {…}, Symbol(enzyme.__renderer__): {…}, Symbol(enzyme.__node__): {…}, …}

> wrapper.prop('errorMessage')
< undefined

> wrapper.instance().props.errorMessage
< ""
```

Is this a known bug? Or is the intention to know when to access the instance vs the `ShallowWrapper` -- if so, can I have some a bit more information on this reasoning?

Just to provide more information:

```
> wrapper.instance().props
< {durationInSeconds: 1000, showSeconds: false, saveInProgress: false, setDuration: ƒ, resetDuration: ƒ, …}

> wrapper.props()
< {className: "duration-field_container__68uCx", data-selector: "duration-container", children: Array(5)}

```

**Comment by ljharb** [comment]
@juanca can you provide more information? What's the full component code, and how are you creating `wrapper`?

**Comment by juanca** [comment]
This is too long ago to pull out the relevant code. 

However, it should be pretty straight-forward React + Enzyme usage.

```
export default class SomeComponent extends React.Component {
  render() {
    return (
      <div>
        <ErrorFlag errorMessage={this.props.errorMessage} />
      </div>
    );
  }
}

SomeComponent.defaultProps = {
  errorMessage: '',
};
```

and


```
import { shallow } from 'enzyme';
import SomeComponent from './some-component.jsx';

it('does a thing!', () => {
  const wrapper = shallow(<SomeComponent />);
});
```

---

I think since then I have realize that the behavior was intentional:

The component returns a virtual node that does not have the `errorMessage` property. But the instance of the component. Essentially: virtual node != component instance

Hope that clears things up! Feel free to close this.

**Comment by ljharb** [comment]
Indeed, that's right - `.props()` should return the passed-in props, *not* the props the instance sees.
