### ISSUE TITLE
Testing components function for click

### ISSUE THREAD

**Issue by vanlong2712** [airbnb/enzyme#1369]
I create a jest spy to test my component function with expecting the function will be called. However, it seems not to be called.
Here is my test:
```javascript
 test('Should call mock function when clicking NavBar button', () => {
   const openNavSpy = jest.fn();
   const wrapper = shallow(<SideNavBar openNav={openNavSpy} />);
   const p = wrapper.find('i');
   console.log(p.debug());
   p.simulate('click');
   expect(openNavSpy).toHaveBeenCalledTimes(1);
  });
```
Here is my related function in SideNavBar component
```javascript
openNav = () => {
   if (this.mySidenav) {
     this.mySidenav.style.width = '360px';
   }
};
....
<i className="fa fa-bars" aria-hidden="true" onClick={this.openNav} />
```
The console log shows `<i className="fa fa-bars" aria-hidden="true" onClick={[Function]} />.`
If I check the simulate with console.log, it shows undefined.
And of course the error shows Expected mock function to have been called one time, but it was called zero times.

**Comment by ljharb** [comment]
This is because you're using an arrow function in a class property, which you should never do; also, you can't override an instance property by passing in a prop.

Instead, do:
```jsx
openNav = this.openNav.bind(this);
openNav() {
   if (this.mySidenav) {
     this.mySidenav.style.width = '360px';
   }
}
```

Then, in your test, spy on `SideNavBar.prototype.openNav` *before* you create your `wrapper`.
