### ISSUE TITLE
`find()` does not find inside custom tags by class name

### ISSUE THREAD

**Issue by kadishmal** [airbnb/enzyme#1370]
- `enzyme: 3.1.0`
- `jest: 20.0.4`
- `enzyme-adapter-react-16: 1.0.4`

The `component` is mounted as:

    const component = mount(<VolumesViewer />);

Output of `component.html()` is:

    <div><ui-button initialized="true"><button class="ui-button ui-button-variant-normal ui-hover-child-icons" type="submit" override-focus=""><span ui-button-region="text">Update Volumes</span></button></ui-button><pre>{}</pre></div>

The following test fails.

```
const button = component.find('ui-button');

expect(button).toHaveLength(1); // Succeeds

console.log(button.html());
```

Outputs:

    <ui-button initialized="true"><button class="ui-button ui-button-variant-normal ui-hover-child-icons" type="submit" override-focus=""><span ui-button-region="text">Update Volumes</span></button></ui-button>

But the following fails.

```
expect(button.find('button')).toHaveLength(1);
```

And it say there are no children:

    console.log(button.children().length); // Returns 0

The following:

    button.tap(n => console.log(n.debug()));

Returns:

    <ui-button id={[undefined]} class={[undefined]} />

Any way to match elements inside a custom tag?

The only way I could find it is:

```
const button = component
            .render()
            .find('button');
```

But this is not acceptable because after `render()` the `find()` returns a `CheerioWrapper` which does not allow to click on the button.

**Comment by ljharb** [comment]
What does `component.debug()` print out? `.html()` uses cheerio so it's not going to help you debug mount issues.

**Comment by kadishmal** [comment]
The output of:

        console.log(component.debug());

is:

```
<Component describeVolumesInit={[Function]} error={{...}}>
      <div>
        <Button onClick={[Function]}>
          <ui-button id={[undefined]} class={[undefined]} />
        </Button>
        <pre>
          {}
        </pre>
      </div>
    </Component>
```

**Comment by kadishmal** [comment]
I just talked with the developer of the component and found out that they are using `mithril.js` for VDOM internally, which might be the reason why something isn't working.

So, there is a workaround I have been told.

    const node = component.getDOMNode();

    node.querySelector("button").click();

**Comment by ljharb** [comment]
@kadishmal indeed, mithril isn't react, and you're using an enzyme react adapter. For example, the `class` prop on `ui-button` - `ui-button` isn't a valid HTML node for react, so that component just might not work at all.

If you want to use a mithril component, you need to be using mithril, which means you'd need to be using a mithril adapter for enzyme. I'm not sure there's a solution here.
