### ISSUE TITLE
create-react-app React 16.1.1

### ISSUE THREAD

**Issue by howardkitto** [airbnb/enzyme#1371]
I'm trying to install Enzyme with React 16.1.1 (via create-react-aap)

The adapter is not happy see below - is there a workaround?

`$ npm i --save-dev enzyme enzyme-adapter-react-16@next

`- react-test-renderer@16.1.1 node_modules/react-test-renderer
`template@1.0.0 
`~/Projects/template

`├── enzyme@3.2.0

`├─┬ enzyme-adapter-react-16@1.0.0-beta.7

`│ └── UNMET PEER DEPENDENCY react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0

`├── UNMET PEER DEPENDENCY jest@>=19.0.0

`├── UNMET PEER DEPENDENCY react@^15.5.0

`├── UNMET PEER DEPENDENCY react-dom@^15.5.0

`└── UNMET PEER DEPENDENCY react-test-renderer@^15.5.0

`npm WARN enzyme-adapter-react-15@1.0.5 requires a peer of react@^15.5.0 but none was `installed.
`npm WARN enzyme-adapter-react-15@1.0.5 requires a peer of react-dom@^15.5.0 but none was `installed.
`npm WARN enzyme-adapter-react-15@1.0.5 requires a peer of react-test-renderer@^15.5.0 but `none was installed.
`npm WARN enzyme-adapter-react-16@1.0.0-beta.7 requires a peer of react@^16.0.0-0 but none `was installed.
`npm WARN enzyme-adapter-react-16@1.0.0-beta.7 requires a peer of react-dom@^16.0.0-0 but `none was installed.
`npm WARN enzyme-adapter-react-16@1.0.0-beta.7 requires a peer of react-test-`renderer@^16.0.0-0 but none was installed.
`npm WARN enzyme-adapter-utils@1.1.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 || `^16.0.0-0 but none was installed.
`npm WARN jest-enzyme@4.0.1 requires a peer of jest@>=19.0.0 but none was installed.

**Comment by ljharb** [comment]
Something being a peer dependency means you need to explicitly have it as a top-level dep in package.json.

The implication is that `enzyme-adapter-react-15` is installed - either by you or by create-react-app - and that conflicts with `enzyme enzyme-adapter-react-16` (which, btw you should not install at "next"; that label isn't up to date nor will be updated; use "latest")

**Comment by howardkitto** [comment]
Fantastic - I uninstalled enzyme-adapter-react-15 and it worked. Not sure why it was installed and not listed in package.json - I expect it was due to my fat fingers. Thanks so much for such a quick response.
