### ISSUE TITLE
find result did not update after component's render change

### ISSUE THREAD

**Issue by dfroger** [airbnb/enzyme#1372]
I have a component `Content` like this:

    export class Content extends Component {
        constructor(props) {
            super(props);
            this.state = { bar: false };
            setTimeout(() => {
                this.setState({ bar: true });
            }, 300);
        }
        render() {
            if (this.state.bar) {
                console.log('===============> render Bar')
                return <Bar/>;
            } else {
                console.log('===============> render Foo')
                return <Foo/>;
            }
        };

    };

Before the timeout, `app.find(Foo).length` and `app.find(Bar).length` are `1`
and `0`, that's what I'm expecting.

After the timeout, they are still `1` and `0`, while I would expect `0` and
`1`.

What make the `find` method of a `ReactWrapper` given by a `mount` behave like
this? Is there some documentation about this behaviour somewhere?

Here is the code (based on  `create-react-app`):  https://github.com/dfroger/issue/tree/master/enzyme

(Sorry if it's commonly asked question, I'm starting to dig github issues).

**Comment by dfroger** [comment]
Seems I was looking for that:
https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#for-mount-updates-are-sometimes-required-when-they-werent-before

**Comment by ljharb** [comment]
Yes, this is intended. You’d need to call wrapper.update() to rerender.

**Comment by dfroger** [comment]
@ljharb ok thanks! I did't try for now, but I think I will not have difficulties, and this seems to be well documented in the migration guide, so I can close the issue.
