### ISSUE TITLE
can`t get state value

### ISSUE THREAD

**Issue by Leannechn** [airbnb/enzyme#1378]
I can`t get state value, witch init in constructor function.
```jsx
    constructor (props) {
        super(props);
        this.state = {
            someProp: props.someProp,
        };
    }
```
 use enzyme:
```jsx
 let wrapper = shallow(<MyComponent someProp={100} />);
 wrapper.state('someProp')  // get undefined? why~
```

**Comment by ljharb** [comment]
@Leannechn I'm not sure what the `\` are for - your wrapper line should be `const wrapper = shallow(<MyComponent someProp={100} />);` (note the proper jsx syntax, and `MyComponent` should be capitalized.

**Comment by ljharb** [comment]
Also, what version of enzyme and react are you using?

**Comment by Leannechn** [comment]
Y, wrapper is ` const wrapper = shallow(<MyComponent someProp={100} />)。`
I want test state when componentDidMount, witch set in constructor such as 
```
constructor (props) {
        super(props);
        this.state = {
            someProp: props.someProp,
        };
    }
```
react version: 16

**Comment by ljharb** [comment]
If you want to test componentDidMount, you should use `mount` instead of `shallow`.

**Comment by Leannechn** [comment]
thanks I got the solution。
```
wrapper.dive().state(). someProp === 100
```
It`s I want.
