### ISSUE TITLE
how to test customized 'react-lodable'?

### ISSUE THREAD

**Issue by raku1089** [airbnb/enzyme#1387]
#### below is the code ,for which i want to write test case.

``` js 
import Loadable from 'react-loadable'
import LoadingScreen from 'shared/components/Loading'

const CustomLoadable = loader => {
  return Loadable({ ...loader, loading: LoadingScreen })
}
export default CustomLoadable
```

I am lodaing componenet dynamically like this .
``` 
const LoginSuccessPageLoadable = CustomLoadable({
  loader: () => import('./login-success')
})  ```

**Comment by ljharb** [comment]
@raku1089 can you elaborate a bit further? What project are you trying to add tests for?

**Comment by raku1089** [comment]
i need to mock the dependency and test wether it is called with appropriate arguments or not

**Comment by raku1089** [comment]
Hey pal ,could you please suggest somthing

**Comment by ljharb** [comment]
@raku1089 If you want to mock out `Loadable`, you'd need to use rewire, or proxyquire, or `jest.mock`, or something similar - that's not an enzyme question, I'm afraid, so I'm going to close this.
