### ISSUE TITLE
spyOn: what is the difference between calling it on prototype versus on wrapper's instance

### ISSUE THREAD

**Issue by nxmohamad** [airbnb/enzyme#1388]
to spy on a component's method, we do
`spyOn(Component.prototype, 'methodName' )`

However at times I have encountered an error that says 'cannot read property methodName of undefined'

I would then resort to doing
`spyOn(wrapper.instance(), 'methodName')`
which would work.

I have no idea why so. Can anyone explain?

**Comment by ljharb** [comment]
This is a `sinon` question, not an `enzyme` one - but it sounds like you're using an arrow function class property on your component, instead of (properly) using a constructor-bound instance method.

Can you share your component code?
