### ISSUE TITLE
Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'

### ISSUE THREAD

**Issue by turnipdabeets** [airbnb/enzyme#1390]
`enzyme-adapter-react-16` has a peerDependency for `react-dom`, however React Native apps do not have react-dom installed. 

This throws an error `Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'`. A quick fix is to install react-dom explicitly as a devDependency, but this is not an ideal solution.

**Comment by ljharb** [comment]
`enzyme-adapter-react-16` is for React 16; react-dom is required. If you want to use it with react-native, someone would need to create an adapter for react-native.

**Comment by thegame8714** [comment]
hi @ljharb, do you know if by any chance someone is working about this issue?

**Comment by ljharb** [comment]
@thegame8714 this issue is in fact not an issue; #1436 tracks creating an adapter for react-native.

**Comment by nelsonchen90** [comment]
for my case, I linked the internal node-module which includes the enzyme. once I unlink it, the error goes away

**Comment by Ahmed-Imam** [comment]
this worked for me 
`npm install --save-dev react-dom enzyme`
