### ISSUE TITLE
Typo re: hasClass

### ISSUE THREAD

**Issue by SparrowSquire** [airbnb/enzyme#1392]
Ref: https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/hasClass.md

Example:    `.hasClass('disabled')).to.equal(true);`
Correction: `.hasClass('disabled')).toEqual(true);`

**Comment by ljharb** [comment]
In fact, `.to.equal` is correct - we use chai's expect, not jasmine/jest's built-in matchers.

**Comment by ljharb** [comment]
Related to #1141, #986, #1575.
