### ISSUE TITLE
[data] attributes return incorrect length amounts when using mount()

### ISSUE THREAD

**Issue by QuantumInformation** [airbnb/enzyme#1393]
For things like classes and id's the selectors work great.

If I do this in a test:
 ```js 
  console.log(renderedItem.find('[data-test-turbine-row]').length)
```
  I get the value 2, but If I run this 
```js
 expect(renderedItem.find('[data-test-turbine-row]')).toHaveLength(2)
```
I get the length 6.

Something is seriously wrong here. I will note that my tests are written in Typescript.

![image](https://user-images.githubusercontent.com/216566/33316297-63e8ff02-d42b-11e7-9f18-7b551ac4edb8.png)

**Comment by aweary** [comment]
@QuantumInformation can you verify if the test passes when you manually assert on the length?

```js
// Sub `toBe` for whatever your assertion library provides for basic equality checks
expect(renderedItem.find('[data-test-turbine-row]').length).toBe(2)
```

If the `.length` property is returning the correct value (which it looks like it is) then I would suspect that there's something wrong with `toHaveLength`

**Comment by QuantumInformation** [comment]
Changing it to `    expect(renderedItem.find('tr')).toHaveLength(3)` works fine

**Comment by QuantumInformation** [comment]
changing that to data- gives

![image](https://user-images.githubusercontent.com/216566/33363555-c1fe54fe-d4d8-11e7-8547-acf631fa675c.png)

**Comment by QuantumInformation** [comment]
Sorry, the error only occurs when using mount(), not render()

**Comment by ljharb** [comment]
@QuantumInformation enzyme 3 now returns more kinds of nodes in the list. Try `expect(renderedItem.find('tr').hostNodes()).toHaveLength(2)`

**Comment by QuantumInformation** [comment]
Thx, that is exactly the fix!

**Comment by QuantumInformation** [comment]
Another question: this should only return 1:
`    renderedItem.find('[data-test-row="code"]').simulate('click');`
but I get 

● ItemsList › renders the correct amount of rows

    Method “simulate” is only meant to be run on a single node. 3 found instead.

**Comment by QuantumInformation** [comment]
adding .hostNodes() fixed it

`renderedItem.find('[data-test-row="code"]').hostNodes().simulate('click');`
