### ISSUE TITLE
Issues with shallow and refs

### ISSUE THREAD

**Issue by Toolo** [airbnb/enzyme#1394]
Say you have a component with a `ref` callback to store the DOM element, I've experienced some issues when testing in the following two scenarios:

## Scenario 1

```
class MyComponent extends React.Component {
   componentDidMount() {
      console.log(this.element.getBoundingClientRects().height);
   }

   render() {
      return (
         <div ref={element => this.element = element}/>
      );
   }
}
```

 If you `shallow` render the component, `componentDidMount` will throw an exception because `this.element` is null.

## Scenario 2

```
class MyComponent extends React.Component {
   render() {
      return (
         <div ref={element => this.element = element}/>
      );
   }
}
```

If you `shallow` render the component and set the state, `this.element` is going to be set to null.

```
const myComponent = shallow(<MyComponent/>);
// myComponent.instance().element is defined
myComponent.setState({someChange: true});
// myComponent.instance().element is null
```

## Question
Is this the expected behavior and the only way to get it to work is using `mount`?

**Comment by ljharb** [comment]
refs only work with `mount`, yes.

**Comment by nicolasiensen** [comment]
We should close this issue, right?

**Comment by nvh95** [comment]
I work around with ref when still using `shallow` by passing `disableLifecycleMethods` to shallow then trigger `componentDidMount` and `componentDidUpdate` by myself
```
class MyComponent extends React.Component {
   componentDidMount() {
      this.input.focus();
   }
   render() {
      return (
         <input ref={element => this.input = element}/>
      );
   }
}
```


```
const myComponent = shallow(<MyComponent/>, { disableLifecycleMethods: true });
myComponent.instance().input =  {
    focus: jest.fn(),
};
myComponent.instance().componentDidMount();

```

**Comment by gogogous88** [comment]
Here is another way you can try:

`class MyComponent extends React.Component {
   componentDidMount() {
      this.input.focus();
   }
   render() {
      return (
         <input ref={element => this.input = element}/>
      );
   }
}`

`MyComponent.prototype.input = { focus: jest.fn()};
const spy = jest.onSpy(MyComponent.prototype.input, 'focus');
const wrapper = shallow(<MyComponent {...props} />);
wrapper.instance().componentDidMount();
expect(spy).toHaveBeenCalled();`
`

**Comment by markmoomoo** [comment]
Here is another way you can try:

`class MyComponent extends React.Component {`
   `componentDidMount() {`
     ` this.input.focus();`
   `}`
   `render() {`
      `return (`
         `<input ref={element => this.input = element}/>`
      `);`
   `}`
`}`

`MyComponent.prototype.input = { focus: jest.fn()};`
`const spy = jest.onSpy(MyComponent.prototype.input, 'focus');`
`const wrapper = shallow(<MyComponent {...props} />);`
`wrapper.instance().componentDidMount();`
`expect(spy).toHaveBeenCalled();`

I guess, the main reason shallow has something not setup for lifecycle run correctly.
it did not run the reference before the componentDidMount is tested.
so, we can mock a focus function in this.input as `MyComponent.prototype.input = { focus: jest.fn()};`
and really tricky here that you can spy it in this way `const spy = jest.onSpy(MyComponent.prototype.input, 'focus');`
then shallow that new MyComponent as you decorated it with mock functions been added

**Comment by ashvin777** [comment]
Use mount instead of shallow. Mount renders the refs 

```javascript
const myComponent = mount(<MyComponent/>);
```
