### ISSUE TITLE
Cannot change value of <input type="number" />

### ISSUE THREAD

**Issue by tomitrescak** [airbnb/enzyme#1412]
Hi, when I use the `simulate` to change the value of the number field, the value remains the same.

```html
<input type="number" id="num" value={reactiveValue} onChange={(e) => reactiveValue = e.target.value} />

```

```js
wrapepr.find('input#num').simulate( 'change', {target: {value: 6}} )
```

This works for type="text", but does not work for number unfortunately.

**Comment by ljharb** [comment]
This is because `simulate` here is not actually simulating anything; it's just invoking the `onChange` prop. You have to manually make any changes you want made.

I'd suggest avoiding `simulate` entirely.

**Comment by tomitrescak** [comment]
@ljharb not sure what you mean .. this approach works for type="text"

**Comment by tomitrescak** [comment]
What is the alternative to using "simulate" in these cases?

**Comment by ljharb** [comment]
@tomitrescak `simulate` doesn't change the value; it basically just does `.prop('onClick')()`. I'm suggesting that you do that directly.

**Comment by tomitrescak** [comment]
I still don’t know what you mean by “directly” :( would you give an example please?

**Comment by ljharb** [comment]
@tomitrescak sure! `wrapper.find('input#num').prop('onChange')({ target: { value: 6 } })`

**Comment by tomitrescak** [comment]
Duh, I cannot believe I did not get this one ... Thanks for your support.
