### ISSUE TITLE
Upgrading to Enzyme 3 w/React 15 test runner broke findWhere using mount.

### ISSUE THREAD

**Issue by brenthosie** [airbnb/enzyme#1413]
Here's the test:

```
test('When onChange is passed in, clicking on the label runs the callback', () => {
  const onChange = jest.fn()
  const wrapper = mount(<RFCheckbox onChange={onChange}} />)

  expect(onChange).not.toHaveBeenCalled()

  const checkboxId = wrapper.state('checkboxId')
  const labelWrapper = wrapper.findWhere(n => n.prop('htmlFor') === checkboxId)
  labelWrapper.simulate('click')

  expect(onChange).toHaveBeenCalled()
})
```

Here's the error after upgrading to Enzyme 3 with React 15 test runner:

> Method “props” is only meant to be run on a single node. 0 found instead.

If I switch this test over to shallow, the test no longer breaks

console.log(wrapper.debug()) using shallow:

```
<label className="rf-checkbox" htmlFor="rf-checkbox-9bd9fd2f-c504-4cfb-b77e-f6b22e7c0352" data-test="label-wrapper">
      <input data-test="rf-checkbox-input" id="rf-checkbox-9bd9fd2f-c504-4cfb-b77e-f6b22e7c0352" type="checkbox" onChange={[Function]} />
      <div className="checkbox-bg" />
      <RFIcon data-test="rf-checkbox-icon" type="check" title="" />
    </label>
```

console.log(wrapper.debug()) using mount:

```
<RFCheckbox onChange={[Function]}>
      <label className="rf-checkbox" htmlFor="rf-checkbox-0d353015-8b2b-43c4-a91b-5cf19ef9c665" data-test="label-wrapper">
        <input data-test="rf-checkbox-input" id="rf-checkbox-0d353015-8b2b-43c4-a91b-5cf19ef9c665" type="checkbox" onChange={[Function]} />
        <div className="checkbox-bg" />
        <RFIcon data-test="rf-checkbox-icon" type="check" title="">
          <span className="rfSI" style={[undefined]} title="" onClick={[undefined]} onMouseDown={[undefined]} onMouseUp={[undefined]}>
            <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <title />
              <path d="M0 0h24v24H0z" fill="none" />
              <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
            </svg>
          </span>
        </RFIcon>
      </label>
    </RFCheckbox>
```

**Comment by brenthosie** [comment]
A little more info for you, when my mounted Checkbox component renders the Icon component, there's a node getting spit out that's empty.

this was found using:

```
wrapper.findWhere(n => { console.log(n.debug() )})
```

<img width="1058" alt="screen shot 2017-12-05 at 10 05 44 am" src="https://user-images.githubusercontent.com/1789219/33620011-e42ae5cc-d9a3-11e7-93d4-aab6330b918b.png">

**Comment by ljharb** [comment]
@brenthosie can you share the source of `RFIcon`? I'm wondering if there's something inside the svg that we're not traversing properly. (I assume that if you shallow-render `RFIcon`, you'll be able to reproduce the same bug)

**Comment by brenthosie** [comment]
@ljharb Thanks for the response!

I had mentioned in my original comment that `shallow` seems to work fine for some reason, but I didn't bold the comment so I could see how that was easily missed.

Here's a screenshot showing that the `RFIcon` tests pass just fine, along with the source showing shallow is used:

![screen shot 2017-12-06 at 8 49 12 am](https://user-images.githubusercontent.com/1789219/33670618-c0736324-da62-11e7-8dfc-c8218054f5ec.png)

Here is the source code for `RFIcon`:

![screen shot 2017-12-06 at 8 49 36 am](https://user-images.githubusercontent.com/1789219/33670641-cda3b6a2-da62-11e7-863c-a0719f588117.png)

It uses an object called `iconList` to find which SVG to render. Heres a screenshot showing examples of some icons:

![screen shot 2017-12-06 at 8 49 59 am](https://user-images.githubusercontent.com/1789219/33670691-e015d0cc-da62-11e7-9b7b-f8ea93fce60f.png)

**Comment by brenthosie** [comment]
The typical way you'd invoke `RFIcon` would be

`<RFIcon type='add-circle' />`

or

`<RFIcon type='iconAddCircle' />` <--- we don't really use this option even though it's possible

**Comment by ljharb** [comment]
Can you share (in text, not a screenshot) the result of `mount(<RFIcon type='add-circle' />).debug()` and `shallow(<RFIcon type='add-circle' />).debug()`?

**Comment by brenthosie** [comment]
@ljharb The result for `shallow` is:

```
<span className="rfSI" style={[undefined]} title={[undefined]} onClick={[undefined]} onMouseDown={[undefined]} onMouseUp={[undefined]}>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <title />
        <path d="M0 0h24v24H0z" fill="none" />
        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z" />
      </svg>
    </span>
```

The result for `mount` is:

```
<RFIcon type="add-circle">
      <span className="rfSI" style={[undefined]} title={[undefined]} onClick={[undefined]} onMouseDown={[undefined]} onMouseUp={[undefined]}>
        <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <title />
          <path d="M0 0h24v24H0z" fill="none" />
          <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z" />
        </svg>
      </span>
    </RFIcon>
```

**Comment by ljharb** [comment]
Thanks. In your original post, which line is throwing the error?

**Comment by brenthosie** [comment]
I believe that the `findWhere` is failing during `mount` when it encounters that blank option that's being spit out during the loop.

> Method “props” is only meant to be run on a single node. 0 found instead.

So, it's when I'm trying to find the label wrapper:

`const labelWrapper = wrapper.findWhere(n => n.prop('htmlFor') === checkboxId)`

**Comment by brenthosie** [comment]
@ljharb any update on this?

**Comment by ljharb** [comment]
@brenthosie I tried to create failing test cases with your code; everything passed with both shallow and mount on React 15.

**Comment by ljharb** [comment]
This seems addressed.

Some things that might help:
 - use `.hostNodes` to filter a collection down to only DOM nodes, since mount trees contain both component instances and DOM nodes, and both might have the same props
 - avoid `simulate`: it doesn't faithfully simulate anything, it's just sugar for invoking a prop function

**Comment by ljharb** [comment]
If there's any outstanding issues, please file a new one with a test case and I'll fix it asap.

**Comment by brenthosie** [comment]
@ljharb Unfortunately this was still a problem for me when using `findWhere`, but I found a way around it using the `.find` syntax. This specific issue has been off my radar for some time.

**Comment by ljharb** [comment]
@brenthosie if you come across the problem again, getting a test case would be helpful.
