### ISSUE TITLE
Erroneous description in README.md file

### ISSUE THREAD

**Issue by hangyangws** [airbnb/enzyme#1415]
such as：  
` expect(wrapper.contains(<div className="unique" />)).to.equal(true);`

But the truth is not found "to、equal" function，
and I found that the right way is:

` expect(wrapper.contains(<div className="unique" />)).toEqual(true);`

~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ianschmitz** [comment]
This depends on which assertion library you are using. For example Chai assertions look like `.to.equal(true)`, however Jest assertions look like `.toEqual(true)`.

**Comment by ljharb** [comment]
At Airbnb, we exclusively use chai's expect; thus, it's correct as-is.
