### ISSUE TITLE
Unit testing image tag with image object

### ISSUE THREAD

**Issue by alagesann** [airbnb/enzyme#1416]
```jsx
import lionIcon from 'assets/images/lion.svg';
import dogIcon from 'assets/images/dog.svg';

            <img
                className="animal-btn-img"
                src={isLion ? lionIcon : dogIcon}
              />
```
how do i unit test that based on 'isLion' prop, appropriate animal object is set on the img tag.?
```jsx
        let img = wrapper.find('.animal-btn-img');
        console.log(img.prop('src'));
```
the above console.log returns only empty object as {}

**Comment by ljharb** [comment]
Can you share how `wrapper` is created, and `img.debug()`?

**Comment by ljharb** [comment]
Ah, also - those icons are SVGs. How have you mocked out those non-standard SVG imports in your tests?

**Comment by sactyagi** [comment]
Testing a angular component in jasmin by mocking the image url. While getting the attribute of the img its returning null.
// getting the handle of the the image
const imgSrc = fixture.debugElement.query(By.css('.thumbnailImage')).nativeElement;
// while prining imgSrc, its coming like <img _ngcontent-c0="" border="1" class="thumbnailImage"> 
not showing the src attribute.
Printing null while in below log:
console.log('Source IMAGE [src]: ', imgSrc.getAttribute('src'));
Please advise ?
