### ISSUE TITLE
Not returning the correct children for a newly defined component

### ISSUE THREAD

**Issue by nelsyeung** [airbnb/enzyme#1417]
I've tried to ask this question on stackoverflow, but no luck there. Hence, I'm submitting this as an issue.

Original question: https://stackoverflow.com/questions/47618989/enzyme-not-returning-the-correct-children-for-a-newly-defined-component

I'm expecting the following test to pass:

    const Foo = ({ children }) => (
      <div>
        {children}
      </div>
    );
    
    describe('<Foo />', function () {
      it('always renders a <div />', function () {
        const foo = mount(
          <Foo>
            <div className="foo" />
          </Foo>
        );
    
        expect(foo.children().html()).to.equal('<div class="foo"></div>');
      });
    });

However, the above would give me:

    AssertionError: expected '<div><div class="foo"></div></div>' to equal '<div class="foo"></div>'

## Temporary fix
I found that I can simply chain two `children()` calls to make this work:

    describe('<Foo />', function () {
      it('always renders a <div />', function () {
        const foo = mount(
          <Foo>
            <div className="foo" />
          </Foo>
        );
    
        expect(foo.children().children().html()).to.equal('<div class="foo"></div>');
      });
    });

## Inconsistency
If I just use a normal `div` instead of the `Foo` component to wrap the inner `div`, I'll get the right result. That is,

    describe('<Foo />', function () {
      it('always renders a <div />', function () {
        const foo = mount(
          <div>
            <div className="foo" />
          </div>
        );
    
        expect(foo.children().html()).to.equal('<div class="foo"></div>');
      });
    });

Furthermore, I found that `foo.children().html()` returns exactly the same string as `foo.html()`. Hence the following `expect` would pass:

    expect(foo.html()).to.equal(foo.children().html());

## Question
If that's the expected behaviour, why?
Is there a neater way to get the children than just to chain it twice?

**Comment by ljharb** [comment]
This is intentional. When you mount a component, you get that component - you need `.children()` to get at the thing it renders.
