### ISSUE TITLE
Enzyme 3 - Static Rendering skimming most outer tag

### ISSUE THREAD

**Issue by Andsbf** [airbnb/enzyme#1420]
package.json
```
 "enzyme": "^3.2.0"
 "enzyme-adapter-react-16": "^1.1.0"          
 "react": "16.1.1",           
```

```jsx
import React from 'react';
import { shallow, render } from 'enzyme';

import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

const Foo = () => {
  return <div className="fooClass">FooContent</div>
}

console.log(render(<Foo />).html())
console.log(shallow(<Foo />).html())

xit('let me run the test', () => {});

```

```jsx
console.log(render(<Foo />).html())
```
it will log ` FooContent`

```jsx
console.log(shallow(<Foo />).html())
```
it will log `<div class="fooClass">FooContent</div>`

when using `render` the most outer tag from the component doesn't get rendered.

Is it the expected behaviour? 

I could not find any reference to this change in this document https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md 

or the in the `Static Rendering` doc:
http://airbnb.io/enzyme/docs/api/render.html

Thanks in advance! 
Please let me know any further info you guys need!

**Comment by ljharb** [comment]
Yes, this is expected behavior, and due to the breaking change in cheerio v1.

**Comment by Andsbf** [comment]
It might be a silly question, do we get any benefit out of it? 

The only reason I ask is because, now we need wrap our components in div's on the test to be able to test it, using render.

**Comment by ljharb** [comment]
It's a change cheerio made; enzyme can't stay on 0.22 forever, so we had to upgrade eventually.

**Comment by Andsbf** [comment]
Thanks for the prompt answers @ljharb !

I would suggest the following in this case.

in: https://github.com/airbnb/enzyme/blob/27d05a0829221b3f1eca0917a0ab7393e4148804/packages/enzyme/src/render.js#L22

instead of 
```javascript
return cheerio.load('')(html);
```

it could be:
```javascript
return cheerio.load(html)('body');
```

Then the return would still the same as before(enzyme version 2). So the cheerio upgrade would not be a breaking change. Let me know If that sounds like a good idea, if so,  I can create a PR for it.

**Comment by ljharb** [comment]
At this point, making that change would be a breaking change for enzyme 3.

**Comment by Andsbf** [comment]
I see, in this case there is nothing to be done about i.

Thanks, and have a great day! :)
