### ISSUE TITLE
Add RST mapping to contains

### ISSUE THREAD

**Issue by eddyerburgh** [airbnb/enzyme#1422]
I'm making an enzyme-inferno-adapter, but I've hit some problems getting the last few tests to pass. 

Enzyme requires `className` to be inside `props`. This is fine normally, because we can convert the inferno VNode tree to an enzyme RST tree. 

But when you call `contains`, enzyme compares the RST node to the newly created VNode. The RST node has `className` inside `props`, the inferno VNode has className on the vNode.

Example:

RST Node:

```js
{
type: 'div',
  props: {
    className: 'bar'
  }
}
```

Inferno VNode
```js
type: 'div',
  props: {
  },
  className: 'bar'
}
```

That means we can't call a method like this:
```js
const a = <div className="bar" />;
expect(mount(Component).contains(a)).to.equal(true);
```

Can we convert the node that `contains` is called with to an RST node before comparing? 

I'm happy to make the PR

**Comment by ljharb** [comment]
Hmm; I'm a bit confused. A PR with test cases might make it more clear?

**Comment by eddyerburgh** [comment]
I'm not sure how to write a test case, hopefully this code makes it clear:

https://github.com/eddyerburgh/enzyme/commit/671b7aebb70380229c505c3def8eab9711327d83

In the inferno enzyme adapter, we need to [add className to props](https://github.com/bbc/enzyme-adapter-inferno/blob/master/src/InfernoEnzymeAdapter.js#L36). That means we need to convert any vNodes before we compare them, otherwise components with the same className will fail, because enzyme compares props in `internalNodeCompare`.

Currently using inferno, this:
```js
const a = <div className="bar" />;
expect(mount(Component).contains(a)).to.equal(true);
```
Will always return false because it's comparing `Component` in RST form, to `a`, which hasn't been transformed. The RST node for `Component` will have `className` inside props, `a` does not have `className` inside props, because it hasn't been transformed.

This isn't a problem for React, because you don't need to transform the `props` object.

**Comment by ljharb** [comment]
I think that makes sense.

It seems like the change you want would theoretically continue to pass on all our React tests; I'm indeed not sure how to test the need for it without making a custom adapter for that purpose.

Want to make a PR?
