### ISSUE TITLE
mount() throwing TypeError when the component contains <img />

### ISSUE THREAD

**Issue by jackyef** [airbnb/enzyme#1424]
I am using jest. Whenever I am trying to `mount` a React Component that contains `img` tag, it throws an error.

```
TypeError: symbol is not a function
console.error node_modules/react-dom/cjs/react-dom.development.js:9747
    The above error occurred in the <img> component:
        in img (created by ChatBubbleAttachment)
        in span (created by ChatBubbleAttachment)
        in div (created by ChatBubbleAttachment)
        in div (created by ChatBubbleAttachment)
        in ChatBubbleAttachment (created by WrapperComponent)
        in WrapperComponent
```

**Comment by ljharb** [comment]
What does the code of `ChatBubbleAttachment` look like?

**Comment by jackyef** [comment]
This is what `ChatBubbleAttachment` renders:

```
return (
      <div className={this.containerClass}>
        {this.renderTopMeta()}
        <div id={`rid-${replyId}`} className="u-clearfix room--bubble" onClick={this.handleThumbnailClick}>
          <img className={this.thumbnailClass} src={attachment.imageUrl} />
        </div>
        {this.renderBottomMeta()}
      </div>
    );
```

**Comment by ljharb** [comment]
What's the rest of the file?

**Comment by ljharb** [comment]
(from the code you sent me privately)

It's happening in `this.renderBottomMeta`, in `<img src={statusIcons[readStatus]} alt="Chat status" className="topchat__room--status-icon" />` - `statusIcons` has values that are imports of a png file, which isn't something you're actually able to import by default.

In other words, whatever hack (or webpack config) you're using in your production code to allow you to import PNGs, you'll have to replicate or mock out somehow for your tests. This isn't specific to enzyme; it'd be the same with any testing framework.

**Comment by jackyef** [comment]
Ah I see! Thanks.

Marking as closed.

**Comment by naser-baig-au4** [comment]
@jackyef, could you please share the solution? I am having the same issue.

Shallow works just fine but mount and render throws the exact Type Error you had.

I have images in my component as well and I am mocking them in jest config by using identity-obj-proxy dependency.

Here's my config

```
"jest": {
    "setupFilesAfterEnv": [
      "jest-enzyme"
    ],
    "testEnvironment": "enzyme",
    "moduleNameMapper": {
      ".+\\.(css|styl|less|sass|scss|png|jpg|gif|ttf|woff|woff2)$": "identity-obj-proxy"
    }
  },

**Comment by michaelbayday** [comment]
@naser-baig-au4  did you find a solution? I'm getting same issue

**Comment by naser-baig-au4** [comment]
> 
> 
> @naser-baig-au4 did you find a solution? I'm getting same issue

No Micheal. I have used shallow for my purpose. Will keep you posted if I find any solutions for this.

**Comment by Rogeriohsjr** [comment]
I solved my issue changing **jest.config.js**.

In my case I double check that I was importing a gif image in the img element.

Then I added the gif on jest.config.js

  moduleNameMapper: {
    '\\.(css|less|sass|scss)$': '<rootDir>/src/test/__mocks__/styleMock.js',
    **'\\.(gif)$': '<rootDir>/src/test/__mocks__/fileMock.js',**
    '.+\\.(png|jpg|ttf|woff|woff2)$': 'identity-obj-proxy'
  }

fileMock.js has only module.exports = {};

https://stackoverflow.com/a/54513338

Hope that helps.
