### ISSUE TITLE
Access provider childrens (state and elements) - Moving from v2 to v3

### ISSUE THREAD

**Issue by sandrina-p** [airbnb/enzyme#1428]
On React 15 this test was working. I need to access state and elements attrs inside a component that has a container (Button). After updating to React 16 and Enzyme 3, the test fails:

**wishlist.js**
_p.s. This is only part of the code_
```js
    render() {
        return (
            <div className="wl" { ...styleInline }>
                { /* Button is a container */}
                <Button theme={ theme } Icon={ IconStar }
                    isActive={ this.props.isActive }
                    onClick={ this._handleOnClick }>
                    Add to wishlist
                </Button>
            </div>
        );
    }
```

**wishlist.test.js**
```js
   test('When isMobile, setState iconPos and use it on .wl as inline style', () => {
        const mockOutput = { right: '73px' };
        const provider = setProvider(
            <WishlistButton { ...propsMock } isMobile />
        );

        const wrapper = provider.getElement('WishlistButton');

        expect(wrapper.root.find('.wl').props().style).toEqual(mockOutput);
    });
```
> TypeError: Cannot read property 'state' of undefined

I didn't change the component code, so it should still work. How do I access state and elements now?

**Comment by ljharb** [comment]
Please try on React 15 and enzyme 3 first; upgrading 2 things at once basically means we can't have any idea which one is causing the problem.

**Comment by sandrina-p** [comment]
So, let me change my question. How do I do with Jest/Enzyme to access an element `.wl` inside a component with a provider?

**Comment by ljharb** [comment]
I don't know what `setProvider` is doing in your test example; nor `getElement`. None of those are using enzyme that I can see :-/
