### ISSUE TITLE
Crazy idea I might like to try -- send results of ReactWrapper.html() to a browser

### ISSUE THREAD

**Issue by morganpackard** [airbnb/enzyme#1429]
Hi! Thanks so much for making Enzyme available!

I'm noticing that when I get in to a flow with enzyme, I'm often leaving `console.log(wrapper.html())` in my test in order to "view" my UI as I'm developing. It has occurred to me that it would be even better if I could actually see what the rendered component would look like. It seems like it wouldn't be hard to pipe the output of `wrapper.html()` to a browser, include my CSS, and have a very fast server-less development workflow which would have the benefit of encouraging developers to write more tests.

My questions are:

1) Any reason this is a dumb idea?
2) Has anyone else already done this?
3) If I make this happen, is anyone interested in hearing about it?

thanks!

**Comment by ljharb** [comment]
I'd recommend using `.debug()`, not `.html()` - the latter goes through cheerio, so the former will be much more faithful and useful.

I feel like this is what storybook is for - which already exists - and wouldn't really need to be related to enzyme.

**Comment by morganpackard** [comment]
Thanks for the quick response!
