### ISSUE TITLE
v2.0.0-rc1 as latest on npm?

### ISSUE THREAD

**Issue by billyjanitsch** [airbnb/enzyme#143]
Apologies if this is known or already explained somewhere -- I couldn't find it in the docs or issues.

The current `latest` version on npm is `2.0.0-rc`, which appears to be *behind* the current `1.4.1` release (I can't find any references to the 2.0.0 release in the commit history).

Because it's marked as `latest`, `npm i enzyme` installs `2.0.0-rc`. Was this publish a mistake? If so, could it be replaced by `1.4.1` as `latest` on npm to fix the default install?

**Comment by ljharb** [comment]
This was fixed last week - `npm show enzyme` should show `'dist-tags': { latest: '1.4.1', next: '2.0.0-rc1' },`.

**Comment by billyjanitsch** [comment]
Not the case for me. `npm show enzyme` shows `'dist-tags': { latest: '2.0.0-rc1', next: '2.0.0-rc1' },`

**Comment by billyjanitsch** [comment]
Oops, my bad, had to clear our company's [sinopia](rlidwka/sinopia) cache. Thanks!
