### ISSUE TITLE
Documentation clarification - what's a host node?

### ISSUE THREAD

**Issue by chrisprobably** [airbnb/enzyme#1430]
Hello,

Could you please clarify what a 'host node' is in the documentation here: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/hostNodes.md

The example says that one node is returned - but I'm unclear which one is returned and why it is considered a host node.

Thanks!

**Comment by ljharb** [comment]
A `div` is a host node (as are all HTML nodes); a non-host node is one created by a custom component.

**Comment by ljharb** [comment]
#1670 may help a bit with this.

**Comment by ljharb** [comment]
Fixed with #1670.
