### ISSUE TITLE
Mocking functions bound to child components

### ISSUE THREAD

**Issue by erikse** [airbnb/enzyme#1432]
I'm new to Enzyme, so probably doing something weird here - all I'm trying to do is to mock a function that is invoked when a button is pressed, e.g.:

```js
export default class App extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      count: 0
    };

    this.handlePress = this.handlePress.bind(this);
  }

  handlePress() {
    this.setState((prevState) => {
      return { count: prevState.count + 1 }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
        <Button title={`Pressed ${this.state.count} times`} onPress={this.handlePress} />
      </View>
    );
  }
}
```
With a test like:
```js
describe('interactions', () => {
  describe('a button press', () => {
    it('should invoke the handlePress callback', () => {
      let wrapper = Enzyme.shallow(<App />);
      let mockFn = jest.fn();

      wrapper.instance().handlePress = mockFn;
      wrapper.find('Button').props().onPress();

      expect(mockFn).toHaveBeenCalledTimes(1);
    });
  });
});
```
I've tried adding `wrapper.update()` but it doesn't seem to update the function bound to the button onPress property.

Any ideas?

**Comment by ljharb** [comment]
You can't mock it by overriding it after the component is already shallow-rendered. Try spying on `App.prototype.handlePress` *before* calling `shallow`.

**Comment by erikse** [comment]
Cheers @ljharb - that works:

```js
    it('should invoke the handlePress callback', () => {
      let mockFn = jest.fn();
      App.prototype.handlePress = mockFn;

      let wrapper = Enzyme.shallow(<App />);
      wrapper.find('Button').props().onPress();

      expect(mockFn).toHaveBeenCalledTimes(1);
    });
```

Thanks!

**Comment by yiochen** [comment]
@ljharb This works when the function is in the prototype, is there a way to mock arrow functions?
```
class App extends React.Component {
   pleaseMockMe = () => {};
}
```

**Comment by ljharb** [comment]
No. Never use arrow functions in class properties; *always* prefer a constructor-bound instance method (or a `foo = this.foo.bind(this)` class property).

**Comment by kbui-prosper** [comment]
If I'm not mistaken, you can mock
```
class App extends React.Component {
   pleaseMockMe = () => {};
}
```
with 
```
```

**Comment by kbui-prosper** [comment]
If I'm not mistaken, you can mock 
```
class App extends React.Component {
   pleaseMockMe = () => {};
}
```
with 
```
it('should invoke pleaseMockMe callback', () => {
    let mockFn = jest.fn();
    let wrapper = Enzyme.shallow(<App />);
    wrapper.instance(). pleaseMockMe = mockFn;
    wrapper.find('Button').props().onPress(); // assuming onClick={this.pleaseMockMe} for Button
    expect(mockFn).toHaveBeenCalledTimes(1);
});
```

**Comment by ljharb** [comment]
You are mistaken; a reference to the original pleaseMockMe has been used in the render.

**Comment by ortonomy** [comment]
@ljharb -- you can do this. it works, I've tested it, errr, in a test. 😆

**Comment by ljharb** [comment]
@ortonomy only if you force update the wrapper after the instance has been overwritten.

Either way, it’s conceptually incorrect to put arrow functions in class fields - i recommend never to do it.

**Comment by psyanite** [comment]
@kbui-prosper's solution didn't work for me :( Made my arrow function into a constructor-bound instance function instead as per @eideer's solution,

As a shot in the dark, anyone know how to mock a named import? Where `MyComponent` will call `pleaseMockMe`. I know you could possibly mock an entire module like.

```
export async function pleaseMockMe() {
  console.log('meow');
}
```


```
import { pleaseMockMe } from './Services'

let pleaseMockMe = jest.fn(); //error
let wrapper = Enzyme.shallow(<MyComponent />);
expect(pleaseMockMe).toHaveBeenCalledTimes(1);
```

**Comment by ljharb** [comment]
@psyanite "instance member not accessible" isn't an error message I'm familiar with. Where did that come from? Being a PureComponent doesn't matter. Separately, you can't mock modules that way - you'd need `jest.mock`, per above.

Either way, please file a new issue; this one is pretty old.

**Comment by anupammaurya** [comment]
> let pleaseMockMe = jest.fn(); //error let wrapper = Enzyme.shallow(<MyComponent />); expect(pleaseMockMe).toHaveBeenCalledTimes(1);


you haven't used your **wrapper** herer?

**Comment by psyanite** [comment]
@anupammaurya how should the wrapper be used?

**Comment by MrOggy85** [comment]
I think this issue is _irrelevant_ since this unit test is not optimal (no finger pointing). 
You want to test the **outcome** of your button press, which in this case is a state change (which will cause a rerender).

Therefor, you should assert on the state (the outcome), rather than mocking and asserting on `handlePress` (intermediate step). 

Your events will always have some kind of outcome (fire prop, change state, pass props to subcomponent, call DOM, etc) that you should assert on. This will make your tests:
* more robust since changes internally will not automatically break test
* you are testing a use case/intention, rather than the current technical implementation

**Comment by mockey-jockey** [comment]
@ljharb tried to like this but it did not work. can u pls help me here.
```
let wrapper, tabChange = jest.fn(),
  saveClick = jest.fn();

  beforeEach(() => {
    const historyMock = {
      replace: jest.fn(),
      length: 0,
      location: {
        pathname: '',
        search: '',
        state: '',
        hash: '',
      },
      action: 'REPLACE',
      push: jest.fn(),
      go: jest.fn(),
      goBack: jest.fn(),
      goForward: jest.fn(),
      block: jest.fn(),
      listen: jest.fn(),
      createHref: jest.fn(),
    };
    ProfilePage.prototype.onSaveClick = saveClick;
    ProfilePage.prototype.onTabChange = tabChange;
    wrapper = mount(
      <Router history={historyMock}>
        <compoent
          name={null}
        />
      </Router>,
    );
});

it('check save click', () => {
    
    wrapper.find('WithStyles(ForwardRef(Tab))').at(1).simulate('click');
   
    expect(tabChange).toHaveBeenCalledTimes(1);

    wrapper.find(CustomizedButton).at(1).simulate('click');
    expect(saveClick).toHaveBeenCalledTimes(1);
  });
```

**Comment by ljharb** [comment]
`<compoent` won't work; custom components have to start with a capital letter.

Separately, instead of wrapper.find, pass the `Router` in with `wrappingComponent`, and then do `wrapper.dive().dive()` to get at the wrapped component. Also, I'd suggest avoiding `simulate`; if you want to test invoking the `onClick` prop, use `.invoke('onClick')()`

**Comment by mockey-jockey** [comment]
@ljharb thanks 
`<compoent` typo mistake, it's starting with capital only.
can u pls help me how to do this `pass the Router in with wrappingComponent, and then do wrapper.dive().dive() to get at the wrapped component.`

ya sure will use `invoke` as u suggested instead of `simulate `

**Comment by ljharb** [comment]
Please check the docs: https://enzymejs.github.io/enzyme/docs/api/shallow.html#arguments

This is all off topic to the issue; please file a new issue if you have further questions.

**Comment by mockey-jockey** [comment]
ya sure, I think completely forgot to mention what is the real issue.

Issue here is - ` expect(tabChange).toHaveBeenCalledTimes(1);` `tabChange` is not called after clicking the tab 

But i can see after clicking tab will render some content, but don't know why am getting `toHaveBeenCalledTimes - 0`
