### ISSUE TITLE
Testing node scrollHeight and clientHeight in enzyme: is this possible?

### ISSUE THREAD

**Issue by SonofNun15** [airbnb/enzyme#1435]
We have a React component called ScrollContainer than calls a prop function when its content is scrolled to the bottom.

Basically:

```js
componentDidMount() {
  const needsToScroll = this.container.clientHeight != this.container.scrollHeight

  const { handleUserDidScroll } = this.props

  if (needsToScroll) {
    this.container.addEventListener('scroll', this.handleScroll)
  } else {
    handleUserDidScroll()
  }
}

componentWillUnmount() {
  this.container.removeEventListener('scroll', this.handleScroll)
}

handleScroll() {
  const { handleUserDidScroll } = this.props
  const node = this.container
  if (node.scrollHeight == node.clientHeight + node.scrollTop) {
    handleUserDidScroll()
  }
}
```

this.container is set as follows in the render method:

```html
<div ref={ container => this.container = container }>
  ...
</div>
```

I want to test this logic using Jest + Enzyme.

I need a way to force the clientHeight, scrollHeight and scrollTop properties to be values of my choosing for the test scenario.

With mount instead of shallow I can get these values but they are always 0. I have yet to find any way to set them to anything non zero. I can set the container on wrapper.instance().container = { scrollHeight: 0 } and etc, but this only modifies the test context not the actual component.

Any suggestions would be appreciated!

**Comment by thk2b** [comment]
Hi,

I am looking to test a similar scroll behaviour, which depends on the `scrollHeight` and `scrollTop` of the rendered component. 

I found that the `clientHeight` of the rendered element is always 0, meaning that jsdom does not even try to size it as a normal browser would. So `scrollHeight` and `scrollTop` are also 0. 

The solution would be for jsdom to calculate element sizes. But according to this [stackoverflow answer](https://stackoverflow.com/questions/19914111/get-dom-elements-actual-width-using-jsdom)(and further investigation) jsdom is not designed to perform rendering calculations.

So, sadly, behaviours dependent on rendered element sizes cannot be tested with jest/enzyme/jsdom.

**Comment by ljharb** [comment]
This seems like an issue with jsdom.
