### ISSUE TITLE
Enzyme Internal Error: configured enzyme adapter did not inherit from the EnzymeAdapter base clas

### ISSUE THREAD

**Issue by zachrickards** [airbnb/enzyme#1437]
I'm getting this error and there is no documentation on it or information I can find anywhere.

**Comment by ljharb** [comment]
This implies that you have more than one copy of enzyme in your dependency graph. What does `npm ls` say?

**Comment by smackjax** [comment]
@zachrickards 
Hi! I hope you figured something out by now, but I had the same error from `configure()`-ing  like
`{ adapter: ReactAdapter }`
instead of 
`{ adapter: new ReactAdapter() }`
in case someone else finds this helpful.

**Comment by ljharb** [comment]
That sounds like a specific case we could check for, and provide a more helpful error message. Alternatively, we could detect it and silently instantiate it for you.

**Comment by cyl19910101** [comment]
I got the same error. I use yarn workspaces to manage packages and happened to have `"enzyme": "^3.2.0",` in one package and have `"enzyme": "^3.3.0",` in another one. And the corresponding section in `yarn.lock` is

    enzyme@^3.2.0:
      version "3.2.0"
      resolved "https://registry.yarnpkg.com/enzyme/-/enzyme-3.2.0.tgz#998bdcda0fc71b8764a0017f7cc692c943f54a7a"
      dependencies:
        cheerio "^1.0.0-rc.2"
        function.prototype.name "^1.0.3"
        has "^1.0.1"
        is-subset "^0.1.1"
        lodash "^4.17.4"
        object-is "^1.0.1"
        object.assign "^4.0.4"
        object.entries "^1.0.4"
        object.values "^1.0.4"
        raf "^3.4.0"
        rst-selector-parser "^2.2.3"
    
    enzyme@^3.3.0:
      version "3.3.0"
      resolved "https://registry.yarnpkg.com/enzyme/-/enzyme-3.3.0.tgz#0971abd167f2d4bf3f5bd508229e1c4b6dc50479"
      dependencies:
        cheerio "^1.0.0-rc.2"
        function.prototype.name "^1.0.3"
        has "^1.0.1"
        is-boolean-object "^1.0.0"
        is-callable "^1.1.3"
        is-number-object "^1.0.3"
        is-string "^1.0.4"
        is-subset "^0.1.1"
        lodash "^4.17.4"
        object-inspect "^1.5.0"
        object-is "^1.0.1"
        object.assign "^4.1.0"
        object.entries "^1.0.4"
        object.values "^1.0.4"
        raf "^3.4.0"
        rst-selector-parser "^2.2.3"

After change all dependencies to `"enzyme": "^3.3.0",`, the code ran correctly again. Hope this helped.

**Comment by ljharb** [comment]
@cyl19910101 that seems like an issue with yarn workspaces; you probably want to configure it to insist that there only be one copy of `enzyme`.
