### ISSUE TITLE
Stimulate('click') is not working on a tag element

### ISSUE THREAD

**Issue by NilapuAnusha** [airbnb/enzyme#1439]
Test case is failing when I expect stimulate click event on a tag element

     const props = {
       logOut :  logOutActions.logOut,
       history: history,
    }

    it('on click logout', () => {
      const clickEvent = spy(Navbar.prototype, 'onLogOutClick')
      const wrapperX = mount(<Navbar {...props}/>)
      wrapperX.find('.dropdown-menu a').simulate('click')
      // wrapperX.find('.dropdown-menu a').html() => <a><span class="glyphicon glyphicon-log-out"></span> Logout</a>
      expect(clickEvent.calledOnce).to.be.true // returns false instead of true
    })

**Comment by ljharb** [comment]
`simulate` should be avoided. It doesn't actually faithfully simulate anything.

If you want the `onClick` invoked, do `.prop('onClick')()`.

**Comment by mir3z** [comment]
@ljharb Why don't you put that in the docs?

**Comment by matteoantoci** [comment]
Maybe this can help... https://github.com/airbnb/enzyme/issues/1426#issuecomment-353335738
