### ISSUE TITLE
ShallowWrapper::dive() can not be called on Host Components

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1447]
I don't normally create this many test helpers but allowed my collegue to while teaching him TDD while pairing.  We found though some pain that I never feel, because I usually put some of this stuff in a beforeEach rather than helpers as we have below:

```
  function expectCarouselItemsLength(items, expectedLength) {
    const carousel = createCarousel(items);
    const carouselItems = carousel.findAttribute(carousel, 'carousel-item');
    expect(carouselItems.length).to.equal(expectedLength);
  }

  // this needs to be in setup, helpers should not do setup stuff, we need to keep helpers simpler
  function createCarousel(items) {
    const carousel = shallow(<Carousel items={items} />);
    const foundCarousel = findAttribute(carousel, 'carousel');
    return foundCarousel;
  }

  function findAttribute(component, attributeName) {
    const foundComponent = component.find(`[data-test='${attributeName}']`);
    return foundComponent;
  }
```

So I found troubleshooting tests hard because we're overdoing test helpers first off.
Anyway the pain with our helpers doing to much causing use to live and debug in our helpers and having to look up and down too much from our test definition, came here when I new I needed to probably dive:

```
    it.only('returns one item', () => {
      const items = [{
        description: 'description',
        image: 'image.jpg',
        title: 'title',
      }];

      expectCarouselItemsLength(items, 1);
    });
```

so I thought ok fine, let me dive() because I know that searching for 'carousel-item' doesn't live in the immediate parent anymore, it lives in a child.

When I went to try and add dive() to this I got `ShallowWrapper::dive() can not be called on Host Components`:

```
  function expectCarouselItemsLength(items, expectedLength) {
    const carousel = createCarousel(items);
    const carouselItems = carousel.dive().findAttribute(carousel, 'carousel-item'); // error here, can't dive on Host Components
    expect(carouselItems.length).to.equal(expectedLength);
  }
```
it didn't let me dive on the carousel const.

Why?

Normally I wouldn't have this in a helper anyway and would be able to just in my test do that and it would have been fine _I think_

**Carousel.js**

```
import React, { Component } from 'react';
import Slider from 'react-slick';
import CarouselItem from './CarouselItem';

export default class Carousel extends Component {
  renderItems() {
    const { items } = this.props;

    return items && items.map((item, i) => {
      return <CarouselItem key={`${item.title}${i}`} item={item} />;
    });
  }

  render() {
    const { item } = this.props;
    return (
      <div className="container">
        <div test="carousel">
          <Slider>
            {this.renderItems()}
          </Slider>
        </div>
      </div>);
  }
}
```

**Comment by dschinkel** [comment]
yea we can't create helpers like createCarousel.  Because what we return ultimately for foundCarousel is a <div>, not the shallow Carousel and you can't dive() on a div I don't think.  So this backs up my thoughts about having too many helpers or helpers doing too much and certain redundant code, if you want to keep dry needs to be in beforeEach so you can act on enzyme appropriately and with flexibility.  If you bury setup in a helper and you don't return the native enzyme shallow wrapper for your tests to work with, you have just put a wall between enzyme and your tests essentially.  Some stuff belongs in setup, not encapsulated in helpers.  If you put the shallow in setup and have constants, those can be reused in your tests and now you're actually working with the raw shallowed component like your tests need.

**Comment by ljharb** [comment]
`.dive()` re-shallow-renders, which makes no sense on a host component. In your Carousel.js example, you need to `wrapper.find(Slider).shallow()` if you want to shallow-render the Slider itself (which I'd discourage, since testing that is the responsibility of the `react-slick` package)

**Comment by dschinkel** [comment]
so...we're not testing slick, we're testing this behavior:

`{this.renderItems()}`

and I don't want to export enderItems just for testing, I want that to be encapsulated so we don't over test.

**Comment by ljharb** [comment]
@dschinkel ah, in that case, `const children = wrapper.find(Slider).prop('children');`, and then something like `children.forEach((child) => { shallow(() => child); /* make assertions on child */ }`?

It's totally possible to re-shallow a `Slider`, but you have no guarantee that `Slider` is rendering the children you give it or not - the actual thing of value is "what props did I pass to `Slider`"; it doesn't actually matter (to your tests) what `Slider` does with it.

As far as diving past HOCs; that (by design) only works when the HOC directly renders a custom component. In your case, `Slider` isn't an HOC, it's a normal component.

**Comment by dschinkel** [comment]
>It's totally possible to re-shallow a Slider, but you have no guarantee that Slider is rendering the children you give it or not 

true, I've tried to render third party HOCs before only to find they have a f'd up way of what they actually output :).

thanks

**Comment by dschinkel** [comment]
I'm going to work on a simpler path to solve this tonight but thanks for your input.  I'll report back once I solve this.

**Comment by dschinkel** [comment]
wait dive() does a shallow()..

**Comment by dschinkel** [comment]
strange so I changed things up a little:

```
import { expect, React, shallow } from '../../test.isolated.imports';
import Carousel from '../../../components/Carousel/Carousel';
import Slider from 'react-slick';
....
    it.only('returns one item', () => {
      const items = [{
        description: 'description',
        image: 'image.jpg',
        title: 'title',
      }];
      const carousel = shallow(<Carousel items={items} />);

      // const carouselItems = carousel.shallow().shallow().find('[test="carousel-item"]');
      // const carouselItems = carousel.find(Slider).props;
      const carouselItems = carousel.find(Slider).props;

      expect(carouselItems.length).to.equal(items.length);
    });
```

```
import React, { Component } from 'react';
import Slider from 'react-slick';
import CarouselItem from './CarouselItem';

export default class Carousel extends Component {
  renderItems() {
    const { items } = this.props;

    const carouselItems = items && items.map((item, i) => {
       return <CarouselItem key={`${item.title}${i}`} item={item} />;
    });

    return carouselItems;
  }

  render() {
    return (
      <Slider test="carousel">
        {this.renderItems()}
      </Slider>
    );
  }
}
```

for some reason, these aren't working:
      // const carouselItems = carousel.find(Slider).props;
      const carouselItems = carousel.find(Slider).props;

it says **Slider is not defined** even though I imported it into my test.

**Comment by dschinkel** [comment]
Ok this is weird, how come even though I did a find on Slider, it's still giving me the enzyme wrapper?  I just made things simple to see what's going on:

```
 it.only('returns one item', () => {
      const items = [{
        description: 'description',
        image: 'image.jpg',
        title: 'title',
      }];
      const carousel = shallow(<Carousel items={items} />);

      const carouselItems = carousel.find(Slider);

      expect(carouselItems.length).to.equal(items.length);
    });
```
![screen shot 2017-12-20 at 8 56 22 pm](https://user-images.githubusercontent.com/338798/34238671-864ffa92-e5c8-11e7-8153-3dce2b2a02db.png)

**Comment by ljharb** [comment]
No, of course you shouldn't. `find` returns a wrapper. The thing you want to check `.length` on is `.prop('children')`.

**Comment by dschinkel** [comment]
ugh right so I'd want to dive past the wrapper but you're saying you can't dive on a third party or you can dive but you need to work with it through its children.

**Comment by dschinkel** [comment]
yea this works. But please clarify my final thoughts in my last post

 `const carouselItems = carousel.find(Slider).prop('children').length`

**Comment by ljharb** [comment]
Strict TDD is often impractical, yes - but good testing can be achieved either with or without it. (snapshot testing is inherently brittle, and I'm not including that in "good").

Third party code is wonderful, and it's not "magic" nor a bad thing - it just means that you're delegating testing responsibility of a third-party component to that component. That's part of the beauty of shallow rendering.

Actually now that I look at it, `carousel` *is* a Slider, so you should be able to just call `.prop('children')` directly on it?

**Comment by dschinkel** [comment]
yea I want to stay away from snapshots and mount.  I want to TDD the front-end.  

> Third party code is wonderful, and it's not "magic" nor a bad thing - it just means that you're delegating testing responsibility of a third-party component to that component. That's part of the beauty of shallow rendering.

It's magic you didn't code, thus magic, thus a black box and it makes testing harder than if you were to create your own simple custom components.  I get that as you add layers it makes testing more difficult and there's the temptation to mount() or worse snapshots but those tests don't tell you where problems are, don't allow you to TDD to design, and give you the feedback loop and the feedback I desire.  Integration tests are crap, they are throwing the dice and hoping something doesn't indirectly cause them to fail while isolated tests are just that, isolated, repeatable, etc.

>Strict TDD is often impractical, yes

not for the backend.  It's just TDD'ing the front-end is hard but people need to learn how.

**Comment by dschinkel** [comment]
thanks again for your help @ljharb

**Comment by fadookie** [comment]
Was banging my head on the wall about this error message for an hour and finally figured out a solution. In my case the situation above didn't really apply although I was trying to write a test that shallow renders a HOC.

Apparently, [enzyme considers any component with a lowercase name to be a host component](https://github.com/airbnb/enzyme/issues/966#issuecomment-305614624). So if you run into this error and it doesn't seem to make sense, make sure your variables are using uppercase names, ex:
```
// Error!
const myComponent = myHoc(SomeComponent);
shallow(<myComponent/>).dive(); 

// Works!
const MyComponent = myHoc(SomeComponent);
shallow(<MyComponent/>).dive(); 
```

**Comment by ljharb** [comment]
@fadookie not just enzyme, but react and jsx itself - anything that's a custom component MUST be named with a capital letter.
