### ISSUE TITLE
`contains` does not fail on string input

### ISSUE THREAD

**Issue by IanVS** [airbnb/enzyme#145]
The API for `contains()` clearly indicates that it should be provided a node, and yet if a string is provided instead, it seems that it will return `true`, no matter the string.  I would have expected an error to be thrown, or at least that `false` would be returned.

**Comment by lelandrichardson** [comment]
hmm. I'd expect the following behavior:
```jsx
shallow(<div>foo</div>).contains('foo'); //=> true
shallow(<div>foo</div>).contains('bar'); //=> false
```

and I assume that you're saying the second statement returns true as well, right?

**Comment by IanVS** [comment]
Thanks @smacker!  Perhaps the [API docs](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/contains.md) should be updated as well?

**Comment by smacker** [comment]
I'm not sure that we need to update docs. It's expected behavior.

**Comment by IanVS** [comment]
Hm, maybe I misunderstand the docs then.  The signature is: `.contains(nodeOrNodes) => Boolean` and at the bottom is:

> `.contains()` expects a ReactElement, not a selector (like many other methods). Make sure that when you are calling it you are calling it with a ReactElement or a JSX expression.

But, `"foo"` in @lelandrichardson's example above isn't a ReactElement or a JSX expression, and yet the assertion will be true.  I admittedly don't understand all this very well, am I missing something?

**Comment by smacker** [comment]
Strings and numbesr are "nodes". Also it's valid JSX expression. But of course let maintainers decide.
