### ISSUE TITLE
setState on shallowWrapper needs explicit update

### ISSUE THREAD

**Issue by nikhilexe** [airbnb/enzyme#1451]
After upgrading to Enzyme V3, we started observing that now we need explicit update after setState. I read the migration guide and somehow i didn't get sense this is expected and hence raising issue here, please correct me if my understanding is wrong.

Here is the sample component

```
export class ComponentA { 

    public render(): JSX.Element {

        return (
            <div className={"myClass"}>
                {
                    this.state.myState ?
                        this._getComponentB() :
                        this.props.children
                }
            </div>
        );
    }

    private _getComponentB(): JSX.Element {
        return (
            <ComponentB
                text={this.props.text} />
        );
    }
}
```

In the test I am trying to do following, see in the setState callback I have to explicit update now to make test pass. Is this expected? I feel this is common scenario and enzyme should handle this.

```
let shallowWrapper = Enzyme.shallow(<ComponentA text="text" />);

shallowWrapper.setState({
                    isLoading: false
                }, () => {
			shallowWrapper.update();
			// Assertion here
		});
```

**Comment by isnifer** [comment]
Just got this too!

**Comment by koba04** [comment]
What about moving your assertion to after the setState?
The following example, you don't need to call `shallowWrapper.update()` manually.

```js
let shallowWrapper = Enzyme.shallow(<ComponentA text="text" />);

shallowWrapper.setState({isLoading: false});
// Assertion here
```

But I think it's an unexpected behavior for developers so I've created a PR to fix this. #1453

**Comment by testking123** [comment]
Thanks @koba04 for raising PR to fix this issue, moving out assertion after setState will work, but its good to have support of callback without any explicit update. For now I updated my test, hoping it get fixed in next version of enzyme

**Comment by nikhilexe** [comment]
Thanks @koba04 for raising PR to fix this issue, moving out assertion after setState will work, but its good to have support of callback without any explicit update. For now I updated my test, hoping it get fixed in next version of enzyme
