### ISSUE TITLE
How to call component instance methods when using render()?

### ISSUE THREAD

**Issue by gunters63** [airbnb/enzyme#1458]
It seems not to be possible to get access to the component root instance when using render().
In my scenario I want to do snapshot testing (currently using enzyme and enzyme-to-json) but for some test cases I have to call component methods before a render tree is generated.

Is there a way around that?

#### API

- [ ] shallow
- [ ] mount
- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  2.9.1
| React            |  15.6.1

**Comment by ljharb** [comment]
Render is just a wrapper around cheerio, which doesn’t have any knowledge of enzyme adapters or instances.

You could use mount or shallow, and use `.render()` when you’re ready, i suppose? (I don’t recommend snapshot testing at all, though, it’s quite a brittle testing approach)

**Comment by gunters63** [comment]
I already feared that, thanks for confirmation.

As for snapshot testing: Yeah they can be brittle. But I think it also depends on the project. In ours we have a already finalized UI design which does not change much but a code base which is in need of refactoring so I think snapshot testing is a good addition. Its another story when the UI is evolving a lot.
