### ISSUE TITLE
`wrapper.context()` API

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#146]
Similar to [`wrapper.props`](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/props.md), there should be an api to introspect into the context of a component. 

The vernacular is sort of weird if we want to mimic the `prop`/`props` style as it would be:

```js
wrapper.contexts() // returns entire context object
wrapper.context('foo') // returns foo from the context object
```

Part of me thinks the word `contexts` sounds weird. We could do this for an API:

```js
wrapper.context() // no argument - returns entire context object
wrapper.context('foo') // returns foo from the context object
```

though this might cause some confusion and unreliability to the API. Thoughts?

**Comment by lelandrichardson** [comment]
@blainekasten the `.state()` and `.state('foo')` API is like the latter and I think would make sense...

I'm not strictly sure we are able to do this though?  We might need to specify `childContextTypes` before-hand.... I'm really not sure though.

**Comment by blainekasten** [comment]
I've been doing it hackily by this code:

```
wrapper.node.context; // full context
wrapper.node.context[arg] // context item
```

Is it not internally safe to depend on the `node` item? If it is, this API could be really simple to implement. I'll give it a test in a bit.
