### ISSUE TITLE
Travis / Testing Strategy with multiple versions of React

### ISSUE THREAD

**Issue by sprjr** [airbnb/enzyme#1461]
### Current behavior
Prior to upgrading to latest `enzyme` + the adapters, I was able to simply `yarn add ...` different versions of React, ReactDom, and ReactAddonsTestUtils in order to run my test suite against multiple versions of react for a small library I've been (semi) maintaining & using.

Some folks at work recently wanted to update the peerDeps to React 16, to remove some console logs. The module _works_, but I haven't been able to confirm that via _tests_.

I've tried a few different things now, and it feels like I'm on the wrong path or approach. I was wondering if there was any guide or information on how to manage dependencies in order to run my test suite against:

React 16, ReactDom16, Enzyme 3.3.0 + the React 16 adapter
React ^15, ReactDom ^15, Enzyme 3.3.0 + the React 15 _or_ 15.5 adapter.

My goal is to at least update the test suite to work with "latest 15.x branch, and latest 16.x branch". I've been able to update the `.travis.yml` and dependencies to work with React 16 [here](https://github.com/sprjr/react-access/pull/19), but I am starting to get a few different errors for the 15.x run and haven't found the right knobs to twirl in order to get it working.

I also dislike that my test setup file has a conditional require for the adapters based on an env var, but maybe that's the only way to go about it?

### Some of the Errors
Depending on which modules I've loaded (and yes, just to clarify, I have been blowing away node_modules) I've received a few various errors on the 15.x attempts:

```
Error: Enzyme Internal Error: unknown composite type undefined
      at compositeTypeToNodeType (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:61:13)
      at Object.getNode (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:254:27)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:121:46)
      at shallow (node_modules/enzyme/build/shallow.js:19:10)
      at Context.<anonymous> (test/unit/react-access-context.js:40:23)
```

or

```
TypeError: Cannot read property 'ReactCurrentOwner' of undefined
    at /Users/srivas/dev/react-access/node_modules/react-reconciler/cjs/react-reconciler-reflection.development.js:54:39
    at Object.<anonymous> (/Users/srivas/dev/react-access/node_modules/react-reconciler/cjs/react-reconciler-reflection.development.js:333:5)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/srivas/dev/react-access/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

### Your environment
Github/TravisCI, React 15/16, Enzyme 3.3.0. I run tests locally with various versions on OSX as well as in TravisCI and am able to repro the same errors with `yarn run test`.

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.2.0 & ^15.0.0

#### Adapter

- [x] enzyme-adapter-react-16
- [x] enzyme-adapter-react-15
- [x] enzyme-adapter-react-15.4

Any how, if I'm missing something obvious in the docs or installation portion sorry - but just wanted to make sure I am on the recommended approach - if there is one for doing this!

Thanks.

**Comment by sprjr** [comment]
Update: I was able to tune the travis yarn installs correctly to get the suite to pass for the different versions. My only remaining question then is, is this the correct approach to testing multiple versions of React:

```
if (process.env.REACT_VERSION === '^15.4.0') {
  const Adapter = require('enzyme-adapter-react-15.4');
  configure({ adapter: new Adapter() });
} else if (process.env.REACT_VERSION === '<15.4.0 >15.0.0') {
  const Adapter = require('enzyme-adapter-react-15');
  configure({ adapter: new Adapter() });
} else {
  const Adapter = require('enzyme-adapter-react-16');
  configure({ adapter: new Adapter() });
}
```

Aka, I need to configure enzyme in the test/setup files this way and there's not another (better?) way that this is recommended to be handled?

**Comment by ljharb** [comment]
Use enzyme-adapter-react-helper to do exactly this.

Here's a guide: https://twitter.com/ljharb/status/931953598308679680

**Comment by sprjr** [comment]
Ah, thanks. I missed this in the docs but that would do the trick.

**Comment by ljharb** [comment]
It's not in the docs :-) if you'd like to write some up and make a PR, that'd be helpful!
