### ISSUE TITLE
How to spy on refs?

### ISSUE THREAD

**Issue by mikeborozdin** [airbnb/enzyme#1462]
I have a component that has a `MapView` from `react-native-maps`. I want to test that I'm calling `MapView.fitToSuppliedMarkers()` inside `componentDidUpdate` of my component.

My code under test:

```
componentDidUpdate() {
    //some other code
    this.refs.map.fitToSuppliedMarkers(/* some parameters */);
  }
```

But I struggle on how to access and spy on `this.refs` using `enzyme` and `jest`.

**Comment by ljharb** [comment]
For one, string refs are deprecated, so you should migrate those to callback refs.

Once that's done, you can spy on the constructor-bound ref callback, on the prototype, prior to creating the enzyme wrapper.

**Comment by mikeborozdin** [comment]
Hi @ljharb,

I've changed it to callback refs and spied on the prototype and it worked as a charm! Thank you!

**Comment by mxdi9i7** [comment]
@ljharb  @mikeborozdin  Hi I'm new to Enzyme and not sure how to actually test for ref callback, could you provide a sample code on how you did it?

**Comment by ljharb** [comment]
Share your component code and test code, and I’ll see what I can do

**Comment by mxdi9i7** [comment]
Found the ref callback sample code from SO just minutes ago:

```
// component code
class Carousel extends Component {

  ...

  prevSlide () {
    this.slider.slickPrev()
  }

  render () {
    const settings = {
      ...
    }

    return (
         ...
        <Slider ref={c => (this.slider = c)} {...settings}>
          {this.props.data}
        </Slider>
        ...
    )
  }
}
// testing code
test('call slick carousel's ref change slide method when change slide component method is triggered', () => {
    const wrapper = mount(<Carousel />)
    const spyPrev = jest.spyOn(wrapper.instance().slider, 'slickPrev')
    wrapper.instance().prevSlide()
    expect(spyPrev).toHaveBeenCalled()
  })
```
I could only find sample for string refs in the enzyme docs, should we have a section for ref callback sample code? since ref callback is the recommended way to do things now

**Comment by ljharb** [comment]
Sure, i guess we could - altho by using ref callbacks, enzyme’s totally uninvolved.

**Comment by mxdi9i7** [comment]
I don't follow here, why would enzyme be uninvolved if one tests with ref callback?

**Comment by ljharb** [comment]
Because while a "ref callback" is something React knows how to invoke when using `mount`, enzyme itself doesn't do anything with it, nor provides any API to work with it. Testing a ref callback is identical to how you'd test any non-lifecycle instance method - you spy on it, then create the wrapper, then assert on how and when it's called; or, you do `wrapper.instance().whatever()` and call it directly, and assert on its effects.

**Comment by mxdi9i7** [comment]
Thanks for the explanation, in that sense it doesn't make as much sense to  be in the official docs. sample code is easily found with a google search as well.

**Comment by mxdi9i7** [comment]
@xxryan1234 In my case I was not using the Slider library, I was testing ref callback in my own component that needed to listen on a scroll.
