### ISSUE TITLE
createRenderer is a required method of EnzymeAdapter, but was not implemented.

### ISSUE THREAD

**Issue by reecemillsom** [airbnb/enzyme#1463]
### Current behaviour

Current behaviour since running tests when migrating from mocha to Karma, I get an error of:
**`createRenderer is a required method of EnzymeAdapter, but was not implemented.`**

Would love help to get to the bottom of this and know what's wrong.

### Expected behaviour

When running tests I would expect them to run without any errors. Maybe some test assertion failures since migrating to karma or something similar.

### Your environment

Typescript, Karma, Enzyme

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | ^3.3.0
| React            |  15.6.2

#### Adapter

- [x] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by koba04** [comment]
@reecemillsom
Can you put your test code?
It seems you are passing an `EnzymeAdapter` instance to `configure` instead of a `ReactFifteenAdapter` instance.

**Comment by reecemillsom** [comment]
Thanks for replying:

Karma Config:
```
"use strict";

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['mocha', 'chai', 'sinon', 'sinon-chai', 'karma-typescript'],
        files: [
            'src/**/*.+(tsx|ts)'
        ],
        exclude: [],
        preprocessors: {
            'src/**/*.+(tsx|ts)': ['karma-typescript'],
        },
        reporters: ['karma-typescript', 'mocha'],
        mochaReporter: {
            showDiff: true
        },
        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json",
            coverageOptions: {
                threshold: {
                    global: {
                        statements: 95,
                        branches: 95,
                        functions: 95,
                        lines: 95,
                        excludes: ["src/**/*.spec.*"]
                    }
                }
            },
            reports: {
                "lcovonly": {
                    "directory": "coverage",
                    "filename": "coverage.html"
                },
                "text-summary": ""
            }
        },
        port: 9876,
        colors: true,
        logLevel: config.LOG_DEBUG,
        autoWatch: false,
        browsers: ['ChromeHeadless', 'FirefoxHeadless'],
        customLaunchers: {
            FirefoxHeadless: {
                base: "Firefox",
                flags: ["-headless"]
            }
        },
        singleRun: true,
        concurrency: false
    });
};

```

Enzyme Adapter:
```
import { configure } from "enzyme";
import ReactFifteenAdapter from "enzyme-adapter-react-15";

configure({ adapter: new ReactFifteenAdapter() });
```

**Comment by ljharb** [comment]
We've seen lots of issues with Karma; are you sure that `ReactFifteenAdapter` is what you expect when running in Karma?

**Comment by reecemillsom** [comment]
Yeah the setup adapter is actually running, because previous to me moving the test file into the src directory i was getting:

```
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() }) before using any of Enzyme\'s top level APIs, where `Adapter` is the adapter corresponding to the library currently being tested. For example: import Adapter from \'enzyme-adapter-react-15\'; To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html');
```

**Comment by reecemillsom** [comment]
Got to the bottom of it, for some unknown reason the error:
**`createRenderer is a required method of EnzymeAdapter, but was not implemented.`**

is being thrown when I try to import the dependencies for enzyme and the adapter. But when I do this through a require statement it works. Not entirely sure why, but thought I should make you aware of this.

**Comment by reecemillsom** [comment]
Think this is fixed, what I had to do was to require in enzyme and the adapter instead of using the import syntax. Not entirely sure why but the tests are now running with no issues

**Comment by ljharb** [comment]
Hmm, that implies a circular dependency (that I'm pretty sure doesn't exist within enzyme).

**Comment by mfsjr** [comment]
Same here:
CRA (unejected)
React 16.2
Enzyme 3.30 (shallow)
enzyme-adapter-react-16
TypeScript 2.7.1

**Comment by mfsjr** [comment]
Actually able to work around this by using ES5-style imports:
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-16');
enzyme.configure({ adapter: new Adapter() });

**Comment by ljharb** [comment]
@mfsjr Your problem seems like an issue with TypeScript.

**Comment by ljharb** [comment]
Indeed, this was/is a bug in TypeScript - you'll need to enable synthetic imports (such that `import React from 'react'` works), otherwise you won't have spec-compliant code.
