### ISSUE TITLE
Confusing (maybe incorrect) error when accessing now private `node` field on a ReactWrapper

### ISSUE THREAD

**Issue by gcarling** [airbnb/enzyme#1464]
### Current behavior

I upgraded to Enzyme 3 and tried to run my existing tests. One failed with this error: 

```
Attempted to access ReactWrapper::node, which was previously a private property on
Enzyme ReactWrapper instances, but is no longer and should not be relied upon.
Consider using the getElement() method instead.
```

I tried using `getElement()` but my test was now failing - I was doing an equality check on the result, and the results no longer matched. After a lot of time and effort I figured out that the `instance()` method returns the exact same thing that access the `node` property used to.

### Expected behavior

The error should tell me to use the `instance()` method, since this returns the exact same thing that the `node` field used to.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.1.1
| React            |  16.1.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

I am happy to submit a PR for this - it seems to me that the same thing would be true of the `getElements()` error message, along with the matching errors in the `ShallowWrapper` class. Not sure if this is on purpose or not, but caused me a lot of pain and it seems like the error just suggests a method that is not doing the exact same thing.

**Comment by ljharb** [comment]
This is in the v2 → v3 [migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md), fwiw - did you read that before upgrading? I'm not sure if it needs a specific error message here; we don't want more runtime messages in v3 that assume people were migrating from v2.
