### ISSUE TITLE
Please remove cheerio / parse5 dependency as parse5 has gone rogue

### ISSUE THREAD

**Issue by huntharo** [airbnb/enzyme#1467]
### Current behavior
Using Enzyme in React Native projects causes TypeScript builds to fail with error:

    node_modules/@types/node/index.d.ts(138,13): error TS2300: Duplicate identifier 'require'.
    node_modules/@types/react-native/index.d.ts(8598,14): error TS2300: Duplicate identifier 'require'.

Enzyme depends on Cheerio which depends on Parse5, and Parse5 lists @types/node as a runtime dependency that gets installed with the NPM package into consuming projects.  @types/node conflicts with the types provided in React Native projects and possibly other project types.

### Expected behavior

Parse5 does not even use TypeScript *AT ALL* so it shouldn't be including ANY @types packages.

Builds of React Native projects should work, not fail, when using TypeScript.

The fix is simple: either remove this @types dependency from parse5 or move it from a runtime dependency to a dev dependency as in the following pull request for parse5:

https://github.com/inikulin/parse5/pull/226

Issue first reported to parse5 in November, 2017 and the active unhelpfulness of the maintainer to remove something that provides no benefit to them but actively hurts others is documented here:

https://github.com/inikulin/parse5/issues/220

Please either remove the cheerio / parse5 dependencies, fork them with a fix, or get the maintainer of parse5 to fix this.  Thanks!

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.2.0
| React            |  16.0.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This isn’t the place to report this. Report it to Cheerio and to typescript (because typescript builds shouldn’t be so brittle as to fail in this scenario).
