### ISSUE TITLE
mount-ing components that represent entire pages

### ISSUE THREAD

**Issue by dnutels** [airbnb/enzyme#1469]
### Current behavior

When defining a trivial test:

```
function DummyPage() {
    return <html><head><title>Dummy</title></head><body></body></html>;
}

describe('DummyPage', () => {
   test('first', () => {
      const wrapper = mount(<DummyPage />);
      expect(true).toBeTruthy;
   });
});
```

this is the output (using Jest):

```
$ jest --config=jest.js
 PASS  test/unit2/pages/test-page.test.js
  DummyPage
    ✓ first (21ms)

  console.error node_modules/fbjs/lib/warning.js:33
    Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
        in html (created by DummyPage)
        in DummyPage (created by WrapperComponent)
        in WrapperComponent

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.111s
Ran all test suites.
```

### Expected behavior

**Assumption**: because of the way the `mount` wrapper works, components (intended for server-rendering of entire pages) can't be mounted, as that creates some sort of `div` wrapper before passing it on to React to create VDOM.

### Your environment

Mac High Sierra 10.13.2
Node 9.3.0

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0 
| React            | 16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by dnutels** [comment]
For the record, same thing happens in Mocha:

```
function DummyPage() {
    return <html><head><title>Dummy</title></head><body></body></html>;
}

describe('DummyPage', () => {
   it('first', () => {
      const wrapper = mount(<DummyPage />);
      expect(true).to.be.true;
   });
});
```
which gives the following output:

```
DummyPage
Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
    in html (created by DummyPage)
    in DummyPage (created by WrapperComponent)
    in WrapperComponent
    ✓ first
```

**Comment by ljharb** [comment]
I’m confused; doesn’t React need to render into a container, so it *cant* represent a whole page?

**Comment by ljharb** [comment]
To clarify: `mount` is exclusively to test in-browser use cases; you’d never use ``mount`` to test a server-rendered use case.

**Comment by dnutels** [comment]
React doesn't need to render into a container, because the same thing above using `enzyme`'s `render` works perfectly.

Either way, since it is entirely possibly to do the code above, from React standpoint, AFAIK, the warning message `enzyme` causes should **at least** be configurable.

Also, what do you mean `mount` is "exclusively in-browser"? Because of jsdom? 

Yes, that's true, but then, there is no other option to test server-rendered code... besides `render` and, with all due respect, that's just `cheerio`, which I don't need `enzyme` for.

My hope was to leverage VDOM...

**Comment by ljharb** [comment]
I'd suggest shallow-rendering all of your components; that will get you full coverage as well as more closely approximate a non-DOM environment.

There doesn't exist any API at the moment besides `render` to fully render a tree without a DOM present.

**Comment by dnutels** [comment]
Yeah... I guess you are right. Using DOM to test SSR is not ideal, but it is either that or ?

**Comment by ljharb** [comment]
or shallow-render every component individually, instead of attempting to integration-test it all at the top level.

**Comment by dnutels** [comment]
We already do that. It's the integration that we wanted to do with Enzyme, cause I am not aware of any alternative for SSR.

**Comment by ljharb** [comment]
#250 is the issue to track this.
