### ISSUE TITLE
Delay Unit Test to give time to the component to setState and render

### ISSUE THREAD

**Issue by sfratini** [airbnb/enzyme#1471]
### Current behavior

Code coverage shows that the state is being correctly updated (async) but the snapshot and the wrapper.state() call have the default values. 

### Expected behavior

The snapshot shows the correct layout and updated state. 

#### API

- [X ] shallow

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.2.0
| React            |   16.0.0

#### Adapter

- [X ] enzyme-adapter-react-16  (1.1.1)

Currently, I am setting the state in an async call. Basically, I check the network info and based on that, I update the state. The code coverage shows that the setState internally is being called and I can confirm that with some logging. 

I saw that if you call the setState async you need to call wrapper.update or wrapper.instance().forceUpdate. None of those worked for me. 

The only way the snapshot shows the correct layout, is if I call wrapper.setState manually, which is not the purpose of my tests. 

After some logging, I realized that the setState internally is actually executing AFTER my Jest tests (based on the logs) so I wanted to know if there is a way to delay the jest unit test for some ms in order to test the fully rendered shallow component. 

I tried this, but it seems to not be working:

```
jest.useFakeTimers()
        //wrapper.setState({basicLogin: true, isLoading: false});
        setTimeout(()=>{
            const spy = jest.spyOn(wrapper.instance(), "_toggle");            
            expect(wrapper).toMatchSnapshot();            
        }, 500);    
        jest.runAllTimers();
```

No matter what I do, the state is always the default one at this stage. 

Any input, appreciated. Thanks

**Comment by sfratini** [comment]
My bad, evantually I made it work like this:

```
it("should render", (done) => {
        
        const wrapper = shallow( <LoginComponent />);

        setTimeout(()=>{
            const spy = jest.spyOn(wrapper.instance(), "_toggle");            
            expect(wrapper.update()).toMatchSnapshot();   
            done();         
        }, 100);    
    
    })
```

**Comment by anilanar** [comment]
How is this your bad?
With your solution, there is no guarantee that:

1) your test won't break in a future update of React
2) your test won't break with different combinations of micro/macro tasks.

**Comment by sfratini** [comment]
@anilanar My bad because I didnt know you cuold do async in enzyme at that time. 

The right way to do this right now it is to actually inject a promise as a dependency and return the test when that promise returns so that will execute in order. 

I didnt have that knowledge when I wrote this

**Comment by GeoDoo** [comment]
@sfratini Could you please write an example of what you say here:

> The right way to do this right now it is to actually inject a promise as a dependency and return the test when that promise returns so that will execute in order.

**Comment by sfratini** [comment]
> 
> 
> @sfratini Could you please write an example of what you say here:
> 
> > The right way to do this right now it is to actually inject a promise as a dependency and return the test when that promise returns so that will execute in order.

Yeah, I didnt explained myself very well. This is an example, for a code that needs to wait for a promise to resolve:
```

it("should return the image source of the icon", () => {
    expect.assertions(3);
    return icons.getSource("Entypo", "home").then(source => {
        expect(source).toBeDefined();
        expect(source).toHaveProperty("scale");
        expect(source).toHaveProperty("uri");  
    });
});
```

Or you can create a promise and pass it to the component which is the way I usually prefer to test components, just passing the dependency:

```
    it("should catch a network info error", () => {
        const wrapper = shallow(<LoginComponent/>);
        let promise = Promise.reject(new Error("networkInfo"));
        NetInfo.getConnectionInfo = jest.fn(() => promise);
        return promise.catch(err => {
            expect(err.message).toContain("networkInfo")
        });        
    })
```

Bottom line, you return a promise, and calculate the assertions after the promise is resolved, which guarantees the code executed.
