### ISSUE TITLE
getElement does not give access to child's member variables

### ISSUE THREAD

**Issue by prijuly2000** [airbnb/enzyme#1472]
### Current behavior
Hi, 

The new version of enzyme that i am using forces me to use `getElement` API which does not give access to member variables of the child components which makes my unit tests fail.
In previous version, i was access node or nodes to set the child's member variable. How do i access it in `getElement`
### Expected behavior
getElement should return me member variables of the child component.
### Your environment
enzyme@3.3.0

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  15.6.2

#### Adapter

- [x] enzyme-adapter-react-16
- [x] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'm not sure what you mean by "member variable"; could you share component and test code?

**Comment by prijuly2000** [comment]
`
class Item extends React.Component {
    constructor(props) {
       this.firstCall = false;
   }
 onClick() {
   this.props.onClick(this.props.index);
}
  render() {
      //code 
   }
}
class List extends React.Component {
   constructor(props){
      this.state ={selectedValue: 0};
  }
  onChange(index) {
  this.setState({selectedValue: index});
 }
 render() {
    return this.props.values.map((el, i) => <Item index={i} value="i/>)
  }
}
`
Unit tests
`
it("test", () => {
  const component = mount(<List values={["a","b","c"]}>);
  const items = component.find("Item").getElements()
  items.firstCall = true; // Not accessible
})
`

**Comment by ljharb** [comment]
In that example, what is `console.log(items)`?

**Comment by prijuly2000** [comment]
<img width="643" alt="screen shot 2018-01-10 at 5 44 46 pm" src="https://user-images.githubusercontent.com/7428850/34804572-29247fac-f62e-11e7-8c81-10faca80f31a.png">

**Comment by ljharb** [comment]
and `component.find("Item").debug()`?

**Comment by prijuly2000** [comment]
Output of `component.find("Item").debug();`
```
component.find("Item").debug()
"<Item onChange={[Function: bound onChange]} index={0} value="a">
  <div onClick={[Function: bound handleClick]} />
</Item>


<Item onChange={[Function: bound onChange]} index={1} value="b">
  <div onClick={[Function: bound handleClick]} />
</Item>


<Item onChange={[Function: bound onChange]} index={2} value="c">
  <div onClick={[Function: bound handleClick]} />
</Item>"
```

**Comment by prijuly2000** [comment]
I see that 3.3.0 version removed support for private variables like node, nodes, renderer etc. We were relying on those for accessing the member variables of the component's class like firstCall in above example. How can i access the firstCall in new version?

**Comment by prijuly2000** [comment]
Ah... never mind.. found another way..

**Comment by kannanmavila** [comment]
Hi @prijuly2000, could you please explain how you managed to do it? I am facing the same problem. Thanks!

**Comment by prijuly2000** [comment]
@kannanmavila
Just use get function in place of mode like 
`component.find('Item').get(0).firstCall` in my case

**Comment by ljharb** [comment]
You may also want `component.find(Item).instance().firstCall`?
