### ISSUE TITLE
Cannot read property 'then' of undefined overriding module function

### ISSUE THREAD

**Issue by sfratini** [airbnb/enzyme#1482]
### Current behavior

Overriding module before the Unit Test makes it become undefined and fails the test. 

### Expected behavior

Module function is replaced on each Unit Test in order to mock different implementations. 

#### API

- [x] shallow

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.2.0
| React            |  16.0.0

#### Adapter

- [x ] enzyme-adapter-react-16

I am trying to test this particular Login component in RN. It has a basic login, SMS login and network login. Right now, I am having some issues with some async functions that change the state and the layout. I am solving some of these issue by adding a setTimeout on each Unit Test, which I now is not recommended. So I am trying to chain all these promises together and I am failing at doing so. I would like to understand if there is something I am missing. 

This is the code I want to test, and the actual coverage, you can see is going for the catch:

![coverage](https://user-images.githubusercontent.com/10799414/34922247-10c50896-f96c-11e7-99a7-dce9b7659bc9.png)

This is my test I wrote:

```
it("should store the confirmation result", (done) => {

        //Import y pisar la funcion
        firebase.auth.signInWithPhoneNumber = jest.fn(() => {
            console.log("Overriding signIn");
            return Promise.resolve(jest.fn());
        });

        let wrapper = shallow( <LoginComponent
            sms={{
                enabled: true,
                sms_placeholder: 'Phone Number',
                text: 'Enter your phone number',
                buttonSend: {
                    text: 'SEND'
                }
            }}
        />); 
        wrapper.setState({phone: '1234567890'});
        
        setImmediate(()=>{
            expect(wrapper.update()).toMatchSnapshot();    
            const spySendSms = jest.spyOn(wrapper.instance(), "sendSms");
            const spyError = jest.spyOn(wrapper.instance(), "error");
            wrapper.update().find("[testID='smsButtonSend']").simulate("press");
            expect(spySendSms).toHaveBeenCalledTimes(1);
            expect(spyError).toHaveBeenCalledWith({}); //Added just to see which is the failing error
            expect(spyError).toHaveBeenCalledTimes(0);                      
            done();         
        });  
        
    });
```

This is the error I am getting:  Expected mock function to have been called with:
      {} as argument 1, but it was called with [TypeError: Cannot read property 'then' of undefined].

As I want to try different errors, and scenarios, I would like to mock module functions differently on each Unit Test. I do have the module mocked completely in a global file and then I am doing the above on each test. 

Is it actually possible to do what I am trying to do? I have multiple internal async functions that check the network info, or network state, fetch, etc. Should I refactor my component so I can override the functions through props? 

I am basically trying to do something like this but failing: https://github.com/airbnb/enzyme/issues/346#issuecomment-304535773

Any input appreciated. Thanks!

**Comment by ljharb** [comment]
You’re trying to mock out `firebase.auth.whatever`, but your code is calling `firebase.auth().whatever`.

**Comment by sfratini** [comment]
@ljharb Jeez, my bad, that was part of the problem. Now I have re written the test like this however the .find is not working because my setState has not executed by the time the test executes, and it is still showing a spinner (the snapshot shows that) instead of the layout that has the button. 

Is there any way to chain that too? Otherwise I will just settle with manually executing some internal functions or the setTimeout, which I want to avoid. 

Thanks again

```
let promise = Promise.resolve(123);
        firebase.auth().signInWithPhoneNumber = jest.fn(() => promise);

        let wrapper = shallow( <LoginComponent
            sms={{
                enabled: true,
                sms_placeholder: 'Phone Number',
                text: 'Enter your phone number',
                buttonSend: {
                    text: 'SEND'
                }
            }}
        />); 

        wrapper.setState({phone: '1234567890'});
        
        expect(wrapper.update()).toMatchSnapshot();    
        const spySendSms = jest.spyOn(wrapper.instance(), "sendSms");
        const spyError = jest.spyOn(wrapper.instance(), "error");
        wrapper.update().find("[testID='smsButtonSend']").simulate("press");
        
        return promise.then(() => {
            expect(spySendSms).toHaveBeenCalledTimes(1);
            expect(spyError).toHaveBeenCalledTimes(0);   
            expect(wrapper.update().state()).toBe(123);                  
        });
```

**Comment by ljharb** [comment]
In general, I'd suggest avoiding `.simulate` entirely; it doesn't faithfully simulate anything. Try `wrapper.find(whatever).prop('onPress')()`.

If you want something to happen after `promise` resolves - like `wrapper.update()` or the snapshot checking, it *all* needs to happen after `promise.then`.

**Comment by sfratini** [comment]
Closing this one as I feel I have a better understanding of what it needs to be done. I was trying very hard to simulate everything exactly however I now feel manually triggering some functions is actually fine.

**Comment by dschinkel** [comment]
it makes me cringe when I see people use "wrapper" as the const name.  Name it the thing you're testing!  This doesn't read very business-like.
