### ISSUE TITLE
Enzyme adapter is not being configured with webpack + karma + typescript

### ISSUE THREAD

**Issue by vagonpidarasov** [airbnb/enzyme#1483]
### Current behavior
```
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
              configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
              before using any of Enzyme's top level APIs, where `Adapter` is the adapter
              corresponding to the library currently being tested. For example:
              import Adapter from 'enzyme-adapter-react-15';
              To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
```

### Expected behavior
Enzyme adapter is being properly configured.

### Your environment
https://github.com/vagonpidarasov/react-redux-pet

**Comment by ljharb** [comment]
https://github.com/vagonpidarasov/react-redux-pet/blob/336fc123495729626c9fc56f1aa4a5f2020f5a8b/src/test-setup.ts#L2 is incorrect; that imports a ModuleRecord which can never be a function.

You want `import Adapter from 'enzyme-adapter-react-16'`.

It's likely that the flawed TypeScript recommendation to use `import *` is the issue here.

**Comment by vagonpidarasov** [comment]
If I have
```
import {configure} from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-16';
configure({adapter: new Adapter()});
```
directly in the test suite (https://github.com/vagonpidarasov/react-redux-pet/blob/336fc123495729626c9fc56f1aa4a5f2020f5a8b/src/modules/scaffold/components/scaffold.component.spec.tsx) everything works.

**Comment by vagonpidarasov** [comment]
Ok, so this actually helped:

### test-setup.ts
```
import {configure} from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-16';

configure({adapter: new Adapter()});

const testContext = require.context('./', true, /\.spec\.tsx/);
testContext.keys().forEach(testContext);
```

### karma.conf.js
```
files: [
            {pattern: 'src/polyfills.ts', watched: false},
            {pattern: 'src/test-setup.ts', watched: false},
            {pattern: 'src/**/*.spec.ts', watched: false},
        ],
```

**Comment by ljharb** [comment]
I'd still suggest `import Adapter from`; `import *` there is simply not correct.

Glad it's all working!
