### ISSUE TITLE
Calling render with portal throws a heap memory exception.

### ISSUE THREAD

**Issue by JakeLaCombe** [airbnb/enzyme#1485]
I have the following code for a react component.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';

class ModalPortalExample extends React.Component {
  render() {
    let modal = 
      <div>
        <button>Open Modal</button>
      </div>;

    return ReactDOM.createPortal(
      modal,
      document.createElement('div'),
    );
  }
}

export default ModalPortalExample;

```

To test it, I have the following jest code.

```jsx
import React from 'react';
import Enzyme, { mount, render, shallow } from 'enzyme';
import ModalPortalExample from './ModalPortalExample';

it('should render an open modal', () => {
  const modal = render(<ModalPortalExample />);
  expect(modal).toMatchSnapshot();
});

```

When I execute this test, I get the following exception.

```
<--- Last few GCs --->

[12565:0x102801600]    26817 ms: Mark-sweep 1409.1 (1441.6) -> 1409.1 (1439.1) MB, 1180.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1181 ms) last resort GC in old space requested
[12565:0x102801600]    27984 ms: Mark-sweep 1409.1 (1439.1) -> 1409.1 (1439.1) MB, 1167.3 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x26d9af25ee1 <JSObject>
    1: read [/Users/jl021230/Documents/PopulationHealth/terra/terra-core/node_modules/react-dom/cjs/react-dom-server.node.development.js:~2206] [pc=0x35d2ffcdc5a5](this=0x26d6ccc2a91 <ReactDOMServerRenderer map = 0x26dfef24649>,bytes=0x26d891829a9 <Number inf>)
    3: renderToStaticMarkup [/Users/jl021230/Documents/PopulationHealth/terra/terra-core/node_modules/react-dom/cjs/react-dom-server.node...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/jl021230/.nvm/versions/node/v8.9.2/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/jl021230/.nvm/versions/node/v8.9.2/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/jl021230/.nvm/versions/node/v8.9.2/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/jl021230/.nvm/versions/node/v8.9.2/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/jl021230/.nvm/versions/node/v8.9.2/bin/node]
 6: 0x35d2ffb0463d
 7: 0x35d2ffcdc5a5
```

### Current behavior

Test executes properly with portal behavior

### Expected behavior

An error log depicting a heap memory failure.

### Your environment

Mac OS Sierra 10.12.6
Node Version 8.9.2
NPM Version 5.6.0

#### API

- [ ] shallow
- [ ] mount
- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| Jest               | 21.0.2
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
`render` just uses cheerio under the hood, after using the adapter to render to string (https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/render.js#L20-L21)

What happens if you try `ReactDOM.renderToString(<ModalPortalExample />)`?

**Comment by JakeLaCombe** [comment]
I'm still getting the same error. I run it with ReactDOMServer.renderToString, and also ReactDOM.server.

**Comment by ljharb** [comment]
Gotcha. In that case, it's not an enzyme error, it's an issue with react itself.

Are you sure that `ReactDOM.createPortal` should be passed a new div every render? Generally you'd create a portal in an *existing* div.

**Comment by ryami333** [comment]
@JakeLaCombe I'm having this issue too - did you find a workaround?

**Comment by JakeLaCombe** [comment]
I have not been able to. Since we had nightwatch and webdriver tests
testing our components, we decided just to remove the render test as we
felt we had sufficient coverage.

**Comment by ljharb** [comment]
@ryami333 it's not irrelevant; the way it's used in React determines the way it'd be supported in enzyme. `render` uses `cheerio`, which is a separate package/project, so it's not something enzyme would be involved with (beyond passing arguments into the initial `cheerio` call). That the error doesn't occur on `mount` means that enzyme itself likely has no problem; and that the error still occurs on React's own render methods means it's *definitely* a React issue.

**Comment by ljharb** [comment]
@ryami333 I think you may have been misunderstanding me. In [this comment](https://github.com/airbnb/enzyme/issues/1485#issuecomment-358098638) I had two points:
 1. if it fails with *react's own rendering methods*, then it's a problem in react, NOT IN ENZYME. Full stop.
 1. totally unrelated, i was asking about why a new div element was being created on every render.
