### ISSUE TITLE
Shallow rendering shows error, but Mount does not

### ISSUE THREAD

**Issue by Sawtaytoes** [airbnb/enzyme#1486]
I believe this issue appears only when using the latest react-hot-loader v4.

### Current behavior
When shallow mounting my component:
```js
shallow(<MyComponent />).html()
```

I see this error:
```js
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Doing the same behavior with `mount`, I see the component output instead as an HTML string:
```html
<div style="margin: 0px 0.4em;"><span style="color: dimgrey; font-size: 2em; white-space: nowrap;">0 </span>Total<span style="font-size: 2em;"> | </span><span style="color: green; font-size: 2em; white-space: nowrap;">0 </span>Passing<span style="font-size: 2em;"> | </span><span style="color: crimson; font-size: 2em; white-space: nowrap;">0 </span>Failing<span style="font-size: 2em;"> | </span><span><span style="color: dimgrey; font-size: 2em; white-space: nowrap;">0.0s </span>Duration</span></div>
```

Doing a shallow render directly with `<div />` works fine:
```js
shallow(<div />).html()
```

Although using a simple stateless functional component does not:
```js
const MyComponent = () => <div />
shallow(<MyComponent />).html()
```

### Expected behavior
Behavior should resemble the HTML output shown by `mount`.

#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.2.0
| React Hot Loader | 4.0.0-beta.14

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I believe react hot loader doesn't work with SFCs, and that this isn't an enzyme thing. Does it work if `MyComponent` is a class-based component?

**Comment by Sawtaytoes** [comment]
Haven't tried a class-based component just yet. Previous versions, including 3 and 4 of React Hot Loader do work with stateless functional components.

**Comment by ljharb** [comment]
With SFCs and with React 16? React 16 did change things with SFCs so they no longer have internal instances attached.
