### ISSUE TITLE
Testing a component with a certain property

### ISSUE THREAD

**Issue by mahomahoxd** [airbnb/enzyme#1487]
### Current behavior
It tests well, it finds shallow and it gives the shallow render wrapper back. However when trying to access certain properties like lets say the property "text" of the component I'm testing, it's not even listed in the properties. 

This is an example definition of how I have it right now : 

```
class SomeComponent extends Component { 
        const { text } = this.props;
        render() {
            return (<TouchableOpacity><Text>{text}</Text></TouchableOpacity>);
        }
}

SomeComponent.defaultProps = { 
       text:' ',
}
SomeComponent.propTypes = {
       text: PropTypes.string,
}
```

Whereas I'd define it in the test as `<SomeComponent text="test" />`
It'd render correctly but in the test, if I define the component and then try to access the .props().text property, it'd return undefined. It is a part of the component as if I run a console.log at the property it gets the correct "test" message.

### Expected behavior
If I write `expect(component.props().text).toBe('something');` it should return true, not undefined on the property as its being set before.

### Your environment
Linux mint 18.3 x64

#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| React-Native | 0.51.0
| Enzyme           | 3.3.0
| React            |  16.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

Maybe I'm doing things wrongly, but I can't really see anything being wrong.

**Comment by ljharb** [comment]
The issue is that the wrapper isn't `SomeComponent` - it's what SomeComponent *renders*.

Try `console.log(component.debug())` and you'll see that it's a `TouchableOpacity`, not a `SomeComponent`.

(Separately, it makes no sense to assert on the props you literally just passed in a few lines previously)
