### ISSUE TITLE
Shallow renderer calls React lifecycle methods

### ISSUE THREAD

**Issue by mir3z** [airbnb/enzyme#1494]
I'm not sure if this is issue or not in the latest version but I have a test that worked in the previous version and now it keeps failing because `componentWillMount` is called by shallow renderer. One thing that may be unusual is that I'm using function as a children prop.

Conside the following components:

```
class Foo extends React.Component {
    componentWillMount() {
        console.warn("***");
    }

    render() {
        return (
            <div>
                { this.props.children({ a: 20, b: 50 }) }
            </div>
        );
    }
}

const Bar = () => (
    <Foo>
        { ({ a, b }) => <div>{ a + b }</div> }
    </Foo>
);
```

and then I call: `shallow(<Bar />).dive()`

### Current behavior
The `componentWillMount` is called.

### Expected behavior
I'd expect the lifecycle methods are not called when using shallow renderer.

### Your environment
* enzyme: 3.3.0,
* enzyme-adapter-react-16: 1.1.1
* react: 16.2.0
* OSX
#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.2.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by koba04** [comment]
@mir3z
It's an expected behavior.
`componentWillMount` is called from previous versions, which is a behavior of ReactShallowRenderer.
(BTW, `componentDidMount` is called by default from v3)

**Comment by mir3z** [comment]
@koba04 Thanks for explanation and sorry for confusion. I've just found the right paragraph in the docs.
