### ISSUE TITLE
[DX] API Wish: element.click(), element.change()

### ISSUE THREAD

**Issue by tarjei** [airbnb/enzyme#1495]
I dearly miss some simple shortcuts for triggering the most common js events; `click` and `change` without going through the `simulate()` method.

### Current behavior
```js
const elm = mount(<SomeComponent />)
elm.click()
// test blows up with undefined function
```
### Expected behavior
```js
const elm = mount(<SomeComponent />)
elm.click({target: {value: 2})
```
// the click event is fired on the element

#### API

- [x] shallow
- [x] mount
- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  2.9.1
| React            |  15.6

Will upgrade soon :)

**Comment by ljharb** [comment]
`elm.prop('onClick')()`?

**Comment by karak** [comment]
Can't you add the shorthand in your own code?

Just like this:

```js
['click', 'change'].forEach(function (name) {
    ReactWrapper.prototype[name] = function (mock) {
        this.simulate(name, mock);
    };
});
```

**Comment by ljharb** [comment]
Monkeypatching objects you don't own is a terrible practice.

**Comment by tarjei** [comment]
@ljharb the point of this suggestion is to make the flow of writing tests as natural as possible - and the as readable as possible. That is why I do not want elm.props().onClick() or variants thereof.

If you find that this is a bad extension of the api surface of enzyme I can understand that.

@karak: I do not want the shorthand in my code because it is not my ocde but my teams code :P. I want my team to be able to understand what is happening.

Regards,
Tarjei

**Comment by karak** [comment]
@tarjei 
Actually, we have a safer way to enhance 'enzyme' as long as you track the public APIs, but I'm not sure you'd like to do that.

Please see demo <https://github.com/karak/enzyme-ext/blob/master/src/enzyme-ext.js>

**Comment by tarjei** [comment]
@karak interesting! I like the implementation, allthough I was hoping for something within enzyme proper :P 

Good work!

**Comment by ljharb** [comment]
Yes, I think anything that pretends or implies that it handles events (like simulate does) is harmful unless it faithfully does what events do.

Absent that, I think explicitly using the full prop name is the best approach.
