### ISSUE TITLE
refs are not triggered on root elements

### ISSUE THREAD

**Issue by pfhayes** [airbnb/enzyme#1504]
Refs on the mounted root element do not appear to be triggered. Is this expected behaviour?

```
  it('triggers refs on child elements', (done) => {
    mount(<div><span ref={(c) => done()}/></div>);
  });

  it('triggers refs on root elements', (done) => {
    mount(<span ref={(c) => done()}/>);
  });
```

### Current behavior

The child elements test passes, but the root element test fails

### Expected behavior

Both tests should pass

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Does this happen with other versions of react as well?

**Comment by pfhayes** [comment]
I was able to reproduce this in 16.0.0 and 15.0.0
