### ISSUE TITLE
Failed prop type on a decorated children component

### ISSUE THREAD

**Issue by nelsyeung** [airbnb/enzyme#1505]
### Current behavior

```
console.error node_modules/fbjs/lib/warning.js:33
    Warning: Failed prop type: The prop `classes` is marked as required in `WithStyles(Bar)`, but its value is `undefined`.
        in WithStyles(Bar)
```

The only two files to you need to reproduce this are
`package.json`
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "material-ui": "^1.0.0-beta.31",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-jest": "^22.1.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "jest": "^22.1.4"
  },
  "babel": {
    "plugins": [
      "transform-class-properties",
      "transform-decorators-legacy"
    ],
    "presets": [
      "env",
      "react"
    ]
  }
}

```
`__tests__/app.test.js`
```js
import Adapter from 'enzyme-adapter-react-16';
import Enzyme from 'enzyme';
import React from 'react';
import PropTypes from 'prop-types';
import { shallow } from 'enzyme';
import { withStyles } from 'material-ui/styles'

Enzyme.configure({ adapter: new Adapter() });

@withStyles({})
class Bar extends React.Component {
  static propTypes = {
    classes: PropTypes.object.isRequired,
  }

  render() {
    return (
      <div>test</div>
    );
  }
}

class Test extends React.Component {
  render() {
    return (
      <Bar />
    );
  }
}

it('renders without crashing', () => {
  shallow(<Test />);
  expect(true).toBe(true);
});
```

This problem does not occur when not using decorator.

### Expected behavior

No warnings.

### Your environment

OS: macOS 10.13.3

#### API

- [ ] shallow

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.2.0

#### Adapter

- [ ] enzyme-adapter-react-16

**Comment by ljharb** [comment]
So if you use `withStyles` in function form, it works, but if you use it as a decorator, it fails?

If so, are you sure material ui's withStyles is meant to be used as a decorator?

**Comment by nelsyeung** [comment]
Unless I'm testing the function form incorrectly, then yes, the test passes without any warnings.
Here's my function form of `Bar`:
```js
const Bar = withStyles({})(class extends React.Component {
  static propTypes = {
    classes: PropTypes.object.isRequired,
  }

  render() {
    return <div>test</div>;
  }
});
```
I'm fairly sure that it can be used as a decorator (provided that the developers are actually correct): https://material-ui-next.com/customization/css-in-js/#examples
> Also, you can use as decorators like so:

I've reproduced what the `withStyles` HOC kind of does, so that this can be reproduced without material-ui (maybe this is not the right way to setup the decorator in the first place?):
```js
import Adapter from 'enzyme-adapter-react-16';
import Enzyme from 'enzyme';
import PropTypes from 'prop-types';
import React from 'react';
import { shallow } from 'enzyme';

Enzyme.configure({ adapter: new Adapter() });

const withStyles = styles => Component => class extends React.Component {
  render() {
    return <Component classes={styles} />
  }
}


@withStyles({})
class Bar extends React.Component {
  static propTypes = {
    classes: PropTypes.object.isRequired,
  }

  render() {
    return <div>test</div>;
  }
}

class Test extends React.Component {
  render() {
    return <Bar />;
  }
}

it('renders without crashing', () => {
  shallow(<Test />);
  expect(true).toBe(true);
});
```

**Comment by ljharb** [comment]
I’m not 100% sure that’s how a class decorator works; but the decorator proposal has changed over time.

in either case, though, using `shallow` only renders o en level deep - you generally need one `.dive()` per HOC. Are you sure that either version is actually working? Use `.debug()` to determine what’s actually being rendered.

**Comment by nelsyeung** [comment]
I know that the decorated components are rendered on a page, if that's what you mean.
This is what I get from `.debug()`:
```js
// console.log(shallow(<Test />).debug());
<_class />

// console.log(shallow(<Test />).dive().debug());
<Bar classes={{...}} />
```
The warning is still visible in the `.dive()` case since I haven't avoided `shallow()`
I'm really just trying to get some snapshot tests in for the parent component without errors and warnings, so I guess I don't need `.dive()` in this case yet.

**Comment by ljharb** [comment]
If you're getting a propType warning, your component graph is invalid - so the first step is always to fix those warnings.

**Comment by nelsyeung** [comment]
Thank you for your _detailed_ explanation, as usual. I have now asked this on stackoverflow so that some light can actually be shed on this problem: https://stackoverflow.com/questions/51227180/why-enzyme-gives-failed-prop-type-on-a-decorated-child-component

**Comment by ljharb** [comment]
@nelsyeung i'm not sure why you needed to add "as usual". I'm triaging hundreds of issues right now, so it's pretty reasonable not to write a full paragraph every time I have a response.

enzyme is not giving this error, since propType warnings only ever come from React. Thus, if you're getting this error, it's a bug *in your element code* inside your tests. 

PropType warnings can be masked by shallow rendering - so if they only show up on a `.dive()`, that means that the outer component isn't passing valid props into the inner component.

**Comment by elowes** [comment]
@nelsyeung If you are including your plugins manually and using @babel/plugin-proposal-class-properties, make sure that @babel/plugin-proposal-decorators comes before @babel/plugin-proposal-class-properties.

**Comment by nelsyeung** [comment]
@elowes That is absolutely beautiful and it kind of makes sense as well. Thank you very much for this. I'm glad someone else found this issue.
