### ISSUE TITLE
Can't Find Internal Handler to call

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1508]
I'm using enzyme 3

I thought that you should be able to just do this rather than call simulate():

```
shallow(<Header
        store={fakeStore()}
        setOverlay={spy}
      />).prop('onSearchClick')();
```

However in our component, look at how onSearchClick is implemented, it's in turn calling a prop called onSearchClick:

```
  onSearchClick = (e) => {
    const { onSearchClick } = this.props; // this is the problem, we're passing in a prop to this component with the same name as this handler!
    if (onSearchClick) onSearchClick(e);
    this.props.setOverlay(OVERLAY_HEADER_SEARCH);
  };
```

So consequently, this fails because it's trying to call a property that doesn't exist, which is the expected passed in onSearchClick function.

Is there a way not to use simulate but in a case where we're passing down yet another function named onSearchClick to an internal handler, that we can still just somehow call the internal handler directly?  In this case we can't because it tries calling the prop not the internal handler.

**Comment by dschinkel** [comment]
I mean I am able to go this route but wondering if there's a way to get the **first** way working in that situation where you're passing in a prop with the same name as a private member, probably not...

link.prop('onClick')(); works, I just add a marker, find it, click it.  I'd much rather test that handler directly and not through the UI though.

**Comment by ljharb** [comment]
I'm kind of confused; if the `onSearchClick` method relies on calling the `onSearchClick` prop on `Header`, then you need to pass in a function there - like `<Header onSearchClick={spy} />`.

**Comment by dschinkel** [comment]
no we want to exercise the logic inside onSearchClick.  We're actually spying on `setOverlay`.  So we need to invoke the `internal` handler because I want to exercise all logic in that handler and assert on it.

**Comment by dschinkel** [comment]
I think the way we're even coding that handler is weird in the first place, passing in a handler with the same name as a handler that exists privately inside a component is just a huge smell to me.  I'm closing this.  Thanks!
