### ISSUE TITLE
New React context API adds new tag types

### ISSUE THREAD

**Issue by lourd** [airbnb/enzyme#1509]
The new API for context, publicly released just a few hours ago in the React 16.3 alpha, adds new tag types for the `Provider` and `Consumer` components that are returned from the `createContext` function.

When updating my module to use the new API, I get an unknown node error from the `ReactSixteenAdapter.js`:

```
Enzyme Internal Error: unknown node with tag 13
```

I went in and took a stab at updating the adapter, and found that the Consumer prop has another new tag type, 12.

I added the following lines:

```diff
+ var ContextProvider = 13
+ var ContextConsumer = 12
```

and tried adding cases for both of those in the module's switch statement, but none of the existing case handling options worked to get my tests passing again.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.0-alpha.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper

**Comment by lourd** [comment]
Here's the relevant [build output](https://travis-ci.org/lourd/react-google-api/jobs/336793556) from [my test](https://github.com/lourd/react-google-api/blob/react-16.3/modules/__tests__/GoogleApi.test.js) and [the source](https://github.com/lourd/react-google-api/blob/react-16.3/modules/GoogleApi.js) that its covering

**Comment by Anonyfox** [comment]
any news on this?

**Comment by ljharb** [comment]
Nobody's put up a PR yet - so no news yet.

**Comment by x3mka** [comment]
Guys, publish a new version with this fix, please. No way for npm install from git monorepo sub dir drives me crazy: https://github.com/npm/npm/issues/2974

**Comment by diegohaz** [comment]
@x3mka in the meanwhile, I've copied the `ReactSixteenAdapter` contents and put it on my setup file: https://github.com/diegohaz/constate/blob/93b7b5b469be4521784b51380f49e6589c3e56b9/test/setup.js

**Comment by x3mka** [comment]
@diegohaz Thanks!

**Comment by South-Paw** [comment]
Hi, just hit this issue with a repo we're working on, thanks to @diegohaz's solution though I've been able to solve it and continue working on things. I assume until #1553 is complete, this is the best way to solve the issue..?

Side note; thanks, for all the hard work you guys do! 👍❤️

**Comment by ryandrewjohnson** [comment]
If you're using jest I found that you can get decent results mocking out context with a utility function like so:

```javascript
// ensure you're resetting modules before each test
beforeEach(() => {
  jest.resetModules();
});

const getComponentWithContext = context => {
  // mock out the context you're using in the component
  jest.doMock('./YourContext', () => {
    return {
      YourContext: {
        Consumer: (props) => props.children(context)
      }
    }
  });
  
  // you need to re-require after calling jest.doMock.
  // return the updated Component module that now includes the mocked context
  return require('./Component');
};

// then use it like so...
it('should return stuff', () => {
    const Component = getComponentWithContext({ data: 'here is some context data for test' });
    const wrapper = mount(<Component />);
    // now do your assertions
  });
```

For a more detailed explanation I did a quick write up [Unit testing components using React’s new Context API](https://medium.com/@ryandrewjohnson/unit-testing-components-using-reacts-new-context-api-4a5219f4b3fe)

**Comment by icfantv** [comment]
@ryandrewjohnson Thanks for the example!  I'm curious as to what the the `Producer` key looks like in the mocked context.  I was unable to figure out the right syntax to make Jest happy.

**Comment by kysedate** [comment]
Following up with @ryandrewjohnson's example, this can be done with shallow as well if you add .dive() at the end of the call. (i..e const wrapper = shallow(<Component />).dive();). I ran into a scenario where I'm adding context to controls that already have extensive unit tests, and this was the only way to avoid major breakage.

**Comment by artin-phares** [comment]
So issue was fixed, but not published on npm yet (for 1.5 months)?

**Comment by shahkashani** [comment]
Please publish this, y'all.

**Comment by hrasoa** [comment]
Guys if you really want that fix right now, you can:
- fork the project
- cherry pick the PR commit(s) from the latest tag.
- publish your fork on npm.
- use that fork on your project.

**Comment by shahkashani** [comment]
While that's technically possible, in some development/deployment environments that requires an internal registry.

**Comment by MurrayJack** [comment]
Any news on this im wanting to use the new API context but cannot due to the Enzyme Internal Error: unknown node with tag 13 issue.

**Comment by swese44** [comment]
can we get a timeline on when this can be published? thanks!

**Comment by sandersky** [comment]
Any idea when this may get published, even if it as an alpha or beta? This is making it very difficult to move forward with using React contexts without throwing a bunch of testing out the window in the current state. If there are any other blockers in which I can contribute to please let me know.

cc @ljharb since it you appear to be pretty active on this project.

**Comment by mAAdhaTTah** [comment]
What I did in my project to get around this was use React 16.2 with [`react-create-context`](https://github.com/jamiebuilds/create-react-context), which Enzyme identifies as a regular component and functions appropriately. Obviously, that doesn't help if you need `forwardRef` and other features, but if you're only using context, this could be a useful stopgap for people.

**Comment by mbrowne** [comment]
The workaround in portfolio-react-boilerplate referenced above is working for me for now.

**Comment by merrywhether** [comment]
https://libraries.io/npm/enzyme

Last publish for enzyme to npm was Dec 28, 2017. Is something up with this project?

**Comment by oreqizer** [comment]
Mandatory bump so this gets released

**Comment by egdbear** [comment]
GOGOGOGO!

**Comment by fedevegili** [comment]
I depend on this as well

**Comment by Anonyfox** [comment]
really waiting for it, too

**Comment by natseg** [comment]
Just to add on @ryandrewjohnson's fix (thank you so much), if you get an invalid type error (`Warning: React.createElement: type is invalid`), you are probably using `export default` instead of `export`.
In this case, change `return require('./MyComponent');` to `return require('./MyComponent').default;`.

**Comment by damianobarbati** [comment]
When will this be published? 😱

**Comment by KevinGrandon** [comment]
Best way to fix this currently: `yarn add --dev enzyme-adapter-react-16@npm:enzyme-react-adapter-future`.

[More details here.](https://github.com/airbnb/enzyme/pull/1513#issuecomment-397128309)

**Comment by dndhm** [comment]
You can also mock a context consumer just by using `jest.fn()` and a single `jest.mock()`, fwiw:

```
const mockContext = jest.fn();
jest.mock('./YourContext', () => ({
  Consumer: ({ children }) => children(mockContext()),
}));
```
and then just `mockContext.mockReturnValue(value)` for each of your test cases.

A quick gist: https://gist.github.com/dndhm/27ce047f4688f9d7968a495c96e31958

**Comment by ice1080** [comment]
Hi @KevinGrandon, we are using forward ref and a context consumer. Does your fix work for this? We are having trouble finding a patch that will allow us to test our components.

```
class MyClass extends Component {
   ...
   render() {
      ...
      methodA();
      methodB();
      ...
   };
}

export default React.forwardRef((props, ref) => (
   <MyContext.Consumer> 
      {context => <MyClass {...props} {...context} ref={ref} />}
   </MyContext.Consumer>
));
```

In order to do our testing we need to be able to mock the methods on MyClass. I've tried to do that by using `jest.spyOn(MyClass.prototype, 'methodA')` and by `MyClass.prototype.methodA = jest.fn();` and it always says the prototype is null. Any thoughts on this? Is there another way to mock that I am missing?

We are using react 16.3.1 but I have tried this with 16.4.0 and 16.4.1. We were using enzyme-adapter-react-16-context-fixes 1.1.2, but have also tried with your fix: enzyme-adapter-react-16@npm:enzyme-react-adapter-future.

On a side note, I've also only been able to use enzyme's mount method when we have the forwardRef and consumer together. Shallow returns a wrapper whose `instance()` method returns null. Not sure if that's related or not.

**Comment by shahkashani** [comment]
The reluctance to publish is truly one of the greatest mysteries in the tech world right now.

**Comment by KevinGrandon** [comment]
> we are using forward ref and a context consumer. Does your fix work for this? We are having trouble finding a patch that will allow us to test our components.

I haven't tested this unfortunately yet, but will try to find some time. If there's a patch in enzyme master, I'd be happy to try to cut a forked release of it.

**Comment by ediblecode** [comment]
I came across this thread as I was using a HOC context wrapper, like explained in [Consuming Context with a HOC](https://reactjs.org/docs/context.html#consuming-context-with-a-hoc) and trying to test it with Jest. I was trying to two things: tests the HOC itself and test the components that used it. For testing the HOC itself, I ended up mocking React's `createContext` method in my tests. This meant that I wasn't rendering type 12 or 13 elements so Enzyme was happy, something like this:

```jsx
import React from "react";
function mockReact() {
	const originalReact = require.requireActual("react");
	return {
		...originalReact,
		createContext: jest.fn(defaultValue => {
			var value = defaultValue;
			const Provider = (props) => {
				value = props.value;
				return props.children;
			};
			const Consumer = (props) => props.children(value);
			return {
				Provider: Provider,
				Consumer: Consumer
			};
		})
	};
}
jest.mock("react", () => mockReact());
```

As for testing wrapped components, I did one of 2 things: either using a named export for the unwrapped components or using the `createContext` mock as above. I know the original post wasn't specifically about HOCs and Context API but hopefully this might help someone else in the absence of a fix!

**Comment by richardtagger** [comment]
Great news, thanks!

**Comment by ryami333** [comment]
I understand your reasoning behind not publishing ASAP (not wanting to open the flood gates) but couldn't you do a pre-release/beta/alpha/next release so that those of us who are struggling with these issue can at least opt-in (consciously aware that there may be other breakages)?

**Comment by ljharb** [comment]
It takes a lot of work to publish individual packages, and juggling the semver here isn't going to be easy. I'll try to have something published soon.

**Comment by artin-phares** [comment]
As a side note I would also add that it's not _issues_ (like bugs or no-publishing) what usually irritates, but _silence from team_.  

eg. 3 month ago...

Team: "Hey guys, we know you all waiting for this, but we have _this_ difficulties to make it quick, and you have _that_ ways to workaround, so just keep calm and wait =)."
Me: "Ok, I see that problem is in team`s focus, so probably I shouldn't cry in comments, and really just wait a while.."

**Comment by ljharb** [comment]
@artin-phares the time it takes to comment on every issue and PR is the exact time I haven't had, or else i'd have been triaging things. I did post https://github.com/airbnb/enzyme/pull/1513#issuecomment-388173895 a month ago, ftr.

**Comment by artin-phares** [comment]
@ljharb Yeah, that was useful update in https://github.com/airbnb/enzyme/pull/1513#issuecomment-388173895. Sadly - in another issue :smiley:

**Comment by BenLorantfy** [comment]
Could you not setup some continuous integration to publish release candidates on every commit?

**Comment by ljharb** [comment]
@BenLorantfy i could, sure - but even if i thought auto-publishes from "not a human" were ever a good idea, that would mean i have a much higher number of versions people would be filing bugs about, which exacerbates the very problem I'm trying to avoid by delaying publishing now.

**Comment by kush-patel-hs** [comment]
would love to hear if there is update on publishing or if can help in any way @ljharb, I ran into this issue today

**Comment by ChuckJonas** [comment]
Still no update on this one?

**Comment by ljharb** [comment]
Not yet, things are in progress. Please be patient.

**Comment by mspoerer** [comment]
Any news on this topic?

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)
