### ISSUE TITLE
Enzyme Selectors do not recognize SVG attributes

### ISSUE THREAD

**Issue by clhenrick** [airbnb/enzyme#1510]
I'm creating SVG components with React as follows:

```jsx
function IconWrapper({ fillColor, width, height }, children) {
  return (
    <svg fill={fillColor} height={height} viewBox="0 0 24 24" width={width}>
      {children}
    </svg>
  );
}

IconWrapper.propTypes = {
  fillColor: PropTypes.string,
  width: PropTypes.number.isRequired,
  height: PropTypes.number.isRequired,
};

IconWrapper.defaultProps = {
  fillColor: '#222',
};

const ArrowDown = props =>
  IconWrapper(props, [
    <path key="a" d="M7.41 7.84L12 12.42l4.59-4.58L18 9.25l-6 6-6-6z" />,
    <path key="b" d="M0-.75h24v24H0z" fill="none" />,
  ]);
```

But when I try to test that the `svg` returned by `IconWrapper` has certain attributes that are set via `props`, Enzyme seems to not find them using the [attribute selector syntax](http://airbnb.io/enzyme/docs/api/selector.html):

```js
describe('IconWrapper', () => {
  const props = {
    fillColor: '#222',
    width: 40,
    height: 40,
  };
  const children = [<path key="a" />, <path key="b" />];
  const svg = Icons.IconWrapper(props, children);
  const wrapper = mount(<svg />);
  const rendered = wrapper.render();
  
  // this test passes
  it('renders an svg element', () => {
    expect(wrapper.type()).toEqual('svg');
  });

  // this test fails
  it('assigns a viewBox attribute to the svg element', () => {
    expect(wrapper.find('svg[viewBox="0 0 24 24"]')).toHaveLength(1);
  });

  // this test also fails
  it('sets the svg element fill, width, and height attributes', () => {
    expect(wrapper.find(`svg[fill="${props.fillColor}"]`)).toHaveLength(1);
    expect(wrapper.find(`svg[width="${props.width}"]`)).toHaveLength(1);
    expect(wrapper.find(`svg[bla="${props.height}"]`)).toHaveLength(1);
  });
}
```

### Current behavior
`wrapper.find('svg[fill="${props.fillColor}"]')` or `rendered.find('svg[fill="${props.fillColor}"]')`
returns `ReactWrapper { length: 0 }`

`shallow(<svg />).find('svg[viewBox="0 0 24 24"]');`
returns `ShallowWrapper { length: 0 }`

### Expected behavior
`wrapper.find('svg[fill="${props.fillColor}"]')` or `rendered.find('svg[fill="${props.fillColor}"]')`
returns `ReactWrapper { length: 1 }`

`shallow(<svg />).find('svg[viewBox="0 0 24 24"]');`
returns `ShallowWrapper { length: 1 }`

### Your environment
MacOS 10.12.6
NodeJS 6.11.2

#### API

- [x] shallow
- [x] mount
- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.2.0
| Jest   | 22.1.4

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
If you `.find('svg')`, do they show up? If you use `.findWhere` instead of string selectors, are you able to find them?

**Comment by clhenrick** [comment]
@ljharb thanks for responding

> If you .find('svg'), do they show up? 

Not sure I follow what you mean. If I do `wrapper.find('svg')` I get `ReactWrapper { length: 1 }`. Do you mean chain another `.find()` on, like `wrapper.find('svg').find('[fill="#222"]')`? 
That returns `ReactWrapper { length: 0 }`

> If you use .findWhere instead of string selectors, are you able to find them?

If I do the following using `.filterWhere` the test passes:

```js
  it('sets the svg element fill, width, and height attributes', () => {
    expect(wrapper.findWhere(n => n.find('[fill="#222"]'))).toHaveLength(1);
    expect(wrapper.findWhere(n => n.find('[width=40]'))).toHaveLength(1);
    expect(wrapper.findWhere(n => n.find('[height=40]'))).toHaveLength(1);
  });
```

however _it still passes_ if I alter the values of the attributes to be different than what `props` set them to, e.g.

```js
  it('sets the svg element fill, width, and height attributes', () => {
    expect(wrapper.findWhere(n => n.find('[fill=999]'))).toHaveLength(1);
    expect(wrapper.findWhere(n => n.find('[width="abc"]'))).toHaveLength(1);
    expect(wrapper.findWhere(n => n.find('[height="xyz"]'))).toHaveLength(1);
  });
```

> Does this also happen with shallow?

Yes, if I do: `shallow(<svg />).find('svg[viewBox="0 0 24 24"]');` I get `ShallowWrapper { length: 0 }`

I think my problem relates to https://github.com/airbnb/enzyme/issues/634 in that I'm trying to test for the attributes on the rendered HTML?  It seems that there are varying opinions on whether or not HTML attributes should be tested for and that perhaps unit tests with React should stick to testing for props?

**Comment by clhenrick** [comment]
Okay I think I solved it. The problem I was having was that I should have mounted my component as follows:

```js
const wrapper = mount(Icons.IconWrapper(props, children));
```

instead of doing: 

```js
const svg = Icons.IconWrapper(props, children);
const wrapper = mount(<svg />);
```

Now the following tests pass:

```js
  it('assigns a viewBox attribute to the svg element', () => {
    expect(wrapper.find('[viewBox="0 0 24 24"]')).toHaveLength(1);
  });

  it('sets the svg element fill, width, and height attributes', () => {
    expect(wrapper.find('[fill="#222"]')).toHaveLength(1);
    expect(wrapper.find('[width=40]')).toHaveLength(1);
    expect(wrapper.find('[height=40]')).toHaveLength(1);
  });
```
Feel free to close as this seems to be my fault implementing `mount` with usage of a React HOC.
