### ISSUE TITLE
ReactWrapper.key returns undefined for empty string keys

### ISSUE THREAD

**Issue by tryggvigy** [airbnb/enzyme#1511]
### Current behavior
```js
  it('asd', () => {
    const foo = [{ a: '' }, { a: '2' }, { a: '3' }];
    const wrapper = mount(<div>{foo.map(i => <span key={i.a} />)}</div>);
    expect(wrapper.children().first().key()).toBe('');
  });
```
results in:
![image](https://user-images.githubusercontent.com/2373958/35782828-9f9c2778-09fe-11e8-94ac-8865e979b173.png)

### Expected behavior
I expected the test to pass.

#### API

- [x] shallow
- [x] mount
- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.1.0
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Does the same thing happen with `shallow`?

What about with other versions of React?

**Comment by tryggvigy** [comment]
@ljharb This happens with `shallow` as well yes. I'm not sure if this happens with other versions of React. This issues popped up in our repo when I did a minor version bump of our prod deps:
<details><summary>Diff</summary><p>

```diff
diff --git a/ui/package.json b/ui/package.json
index a47590a10e..9ae4e2b1e9 100644
--- a/ui/package.json
+++ b/ui/package.json
@@ -102,48 +102,48 @@
     "classnames": "^2.1.3",
     "debug": "2.6.9",
     "dom-delegate": "~2.0.3",
-    "domify": "~1.3.1",
+    "domify": "~1.4.0",
     "domready": "^1.0.8",
-    "enzyme-adapter-react-16": "^1.0.1",
+    "enzyme-adapter-react-16": "^1.1.1",
     "escape-html": "~1.0.1",
     "events": "^1.0.2",
     "extend": "^2.0.1",
-    "findandreplacedomtext": "0.4.4",
+    "findandreplacedomtext": "0.4.6",
     "glob": "^5.0.10",
-    "handlebars": "^4.0.6",
-    "hbsfy": "^2.7.0",
+    "handlebars": "^4.0.11",
+    "hbsfy": "^2.8.1",
     "highlight.js": "^9.12.0",
     "humanize": "^0.0.9",
     "immutable": "^3.8.2",
     "inherits": "^2.0.1",
     "is-jpg": "~1.0.0",
     "jsonify": "file:libs/jsonify",
-    "knockout": "3.4.2",
+    "knockout": "3.5.0-beta",
     "lodash": "^4.2.0",
     "minimist": "^1.2.0",
-    "moment": "^2.8.3",
+    "moment": "^2.20.1",
     "mout": "^0.11.0",
     "nlp_compromise": "^1.1.3",
-    "node-sass": "^4.6.0",
+    "node-sass": "^4.7.2",
     "partialify": "^3.1.5",
     "promisify-native": "^1.0.0",
     "prop-types": "15.6.0",
     "quantize": "^1.0.2",
     "quill": "0.19.10",
     "ramda": "^0.25.0",
-    "raven-js": "^3.15.0",
-    "react": "^16",
+    "raven-js": "^3.22.1",
+    "react": "^16.2.0",
     "react-css-transition-replace": "^3.0.2",
-    "react-dom": "^16",
+    "react-dom": "^16.2.0",
     "react-redux": "^5.0.5",
-    "react-test-renderer": "^16",
+    "react-test-renderer": "^16.2.0",
     "react-transition-group": "1.2.1",
-    "react-virtualized": "^9.9.0",
+    "react-virtualized": "^9.18.2",
     "redux": "^3.4.0",
     "redux-immutable": "^3.0.8",
     "redux-logger": "^2.7.0",
     "redux-thunk": "^1.0.3",
-    "request": "^2.36.0",
+    "request": "2.83.0",
     "reselect": "^2.5.4",
     "shaka-player-spotify": "2.1.4-sp.3",
     "slick": "^1.12.2",
@@ -151,10 +151,10 @@
     "spotify-cosmos-api": "^1.7.3",
     "spotify-deferred": "^0.3.0",
     "spotify-eventemitter": "^2.1.0",
-    "spotify-gaia": "^0.6.0",
+    "spotify-gaia": "0.8.0",
     "spotify-liburi": "^4.5.0",
     "spotify-modal": "^1.1.0",
-    "spotify-player": "^2.0.0",
+    "spotify-player": "2.1.2",
     "spotify-simple-navbar": "^1.0.0",
     "spotify-tree": "^1.1.2",
     "teamcity-service-messages": "^0.1.9",
```

</p></details>

As you can see, React goes from 16.0.0 -> 16.2.0
The [React changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1620-november-28-2017) doesn't seem to contain anything that looks related.

I'll try downgrading React to 16.0.0 again and see if that has any effect.

**Comment by tryggvigy** [comment]
I dug around a bit more. The behavior of empty string key prop changes between:

```diff
-    "enzyme-adapter-react-16": "^1.0.1",
+    "enzyme-adapter-react-16": "^1.1.1",
```

The test described in this issue passes on `enzyme-adapter-react-16@1.0.1` 
but fails on `enzyme-adapter-react-16@1.1.1`.

**Comment by tryggvigy** [comment]
I think I found the commit.
https://github.com/airbnb/enzyme/commit/8c21e406afb1f958bab19aa66be265eb80d5a28c#diff-359ceaf4dec809e15a7f54fb0e2c2f42
Would you be interested in a PR fixing this issue @ljharb ?

**Comment by bdwain** [comment]
I guess all of those `el.key || undefined` should be `el.key || (el.key === '' ? '' : undefined)`, though that seems kind of awkward. Should definitely be a helper rather than repeat everywhere.

**Comment by ljharb** [comment]
Seems like a good change; a PR to fix it would be great!

**Comment by tryggvigy** [comment]
Opened PR https://github.com/airbnb/enzyme/pull/1524 for this issues
