### ISSUE TITLE
Test cases for google analytics

### ISSUE THREAD

**Issue by hema1592** [airbnb/enzyme#1515]
I'm writing test cases for my react component where the google analytics have been implemented.I have searched and found there are no method to cover the Google analytics using enzyme/jest.Is there any method to do testing for GTM?

Code:
```jsx
if (msg === 'ADD') {
      this.props.mydata.addData(this.props.courseId, data, msg);
      AnalyticsManager.dispatch({
        category: 'data',
        action: 'Add data',
        label: JSON.stringify({ title: data.title, message: data.content })
  });
```

**Comment by ljharb** [comment]
In a generic JS sense, you'd mock out the `dispatch` function here, and assert on what it's called with. 

This isn't specific to enzyme.
