### ISSUE TITLE
Testing component which requires certain width

### ISSUE THREAD

**Issue by 8bitjoey** [airbnb/enzyme#1517]
### Current behavior
Trying to test a thirdparty component ([ag-grid-react](https://github.com/ag-grid/ag-grid-react)) which doesn't natively support React (like d3). (Yes, I read about common issues with 3rdparty components, but this case is a little different, imo). 

This grid component has a feature to not render columns which are not visible in a viewport. And when it is rendered in enzyme, it only renders the very first column.

### Expected behavior

It should render all columns. That could be possible if container reports non zero width to the AgGridReact when the latter is rendered.

Note: ag-grid has [domLayout="forPrint"](https://www.ag-grid.com/javascript-grid-width-and-height/#dom-layout) option which forces it to render all columns. But I can't use it because that's not the behavior I want to see in the app.

### Question

Is there a way to force container to have a certain width?

### Unit test code

```
import {AgGridReact} from 'ag-grid-react/lib/agGridReact';
...
let wrapper = mount(<MyComponentWhichUsesAgGridReact ...someprops.../>);
let agGrid = wrapper.find(AgGridReact).render();
expect(agGrid.find('.ag-body-container > .ag-row').first().find('[col-id="name"]')).to.have.length(1);
```

#### API

- [ ] shallow
- [X] mount
- [X] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | ^2.7.1
| React            | ^15.5.0 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [X] others (? not requiring any of these in my package.json)

**Comment by 8bitjoey** [comment]
It doesn't natively support React. It is an old good js library which works with DOM directly. However it has react wrapper - ag-grid-react (many libraries do so, e.g. highcharts). 
And it could work as I expect if the container's width was non 0.

**Comment by ljharb** [comment]
All your tests need to do, though, is assert that `ag-grid-react` is rendered with the right props; testing the functionality of that component itself is the job of that package's tests.

**Comment by 8bitjoey** [comment]
That's correct. Although there is one small detail which I wanted to test.
Columns in that grid accept so called value formatter. A thing which takes cell value and formats it, say formats Date object as mm/dd/yyyy string. I wanted to ensure these formatters are applied correctly.
Do you think this is not mine's responsibility, but instead ag-grid-react's responsibility?

**Comment by ljharb** [comment]
Correct; it's not your responsibility to test that.

**Comment by 8bitjoey** [comment]
Ok, we can consider this is not what _unit_ test should do. I understand and agree with a responsibility division principle, but as an app owner, I'd like to ensure it works fine after all.

What if some ag-grid-react's tests fail in a new version of that library and that results in corrupted UI? I'd like to have automated tests to catch this case. So it's kind of not my responsibility, but I still care about this.

This is called _integration_ tests, right? Do you think enzyme is the right tool do run such tests or there's a better tool for that?

**Comment by ljharb** [comment]
I think that enzyme isn't the right tool for that; that's what a browser-driven tool would be used for.

**Comment by 8bitjoey** [comment]
Right. I also thought about using selenium tests as integration tests. Thanks!
