### ISSUE TITLE
Please update the gitbook docs.

### ISSUE THREAD

**Issue by SirYummy** [airbnb/enzyme#1521]
Here is an example of outdated content:

http://airbnb.io/enzyme/docs/api/ShallowWrapper/instance.html

I assume should contain all of this:

https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/instance.md

**Comment by SirYummy** [comment]
I tried fixing it myself and opening a PR, but I'm getting an error when trying to install gitbooks.

**Comment by ljharb** [comment]
It should be updated on every released version - and it absolutely isn’t guaranteed to match master.

Does it match the latest tag?
