### ISSUE TITLE
Stricter typescript types on simulate's event.

### ISSUE THREAD

**Issue by CarloPalinckx** [airbnb/enzyme#1528]
simulate's event param is defined (in `@types/enzyme`) as `string`. Is there a reason why this couldn't be defined as a union of all possible React Synthetic events (https://reactjs.org/docs/events.html)? Do people use this param outside of the support events?

If so, should this be stricter? (as a bonus, it also helps alot with API discovery in most IDE's).

Wouldn't mind making a pull request over at https://github.com/DefinitelyTyped/DefinitelyTyped if that is favorable.

**Comment by ljharb** [comment]
We don’t use TypeScript nor maintain those types, so that’s indeed the right place to ask/PR.
