### ISSUE TITLE
Contains

### ISSUE THREAD

**Issue by SeeThruHead** [airbnb/enzyme#153]
I kinda was expecting this to not pass

```js
  const wrapper2 = shallow(<Button><span>Hello</span><div>Goodbye</div></Button>);
  const expectedChildren = [
    <span>wrong</span>,
    <div>Goodbye</div>
  ];

  t.ok(wrapper2.contains(expectedChildren), 'should render children');
```

Any thoughts?

**Comment by lelandrichardson** [comment]
whoa.  I'd call that a bug.

**Comment by SeeThruHead** [comment]
workarounds: 
```js
  const expectedChildren = [
    <span>bye</span>,
    <div>Goodbye</div>
  ];

  t.deepEqual(wrapper2.props.children, expectedChildren, 'should render children');
```
```js
  t.ok(wrapper2.contains(<span>Hello</span>), 'should render children');
  t.ok(wrapper2.contains(<div>Goodbye</div>), 'should render children');
```

Maybe it's fine that contains only accepts single nodes?

**Comment by lelandrichardson** [comment]
@SeeThruHead Yeah. I'm not sure what contains would actually do when passed an array... I don't think the case is ever handled specifically so I'm not sure what it actually does in that case.

**Comment by SeeThruHead** [comment]
Looks like it will try to compare the array to every node using nodeEqual from './Utils'

I'll take a look at it later to see if I can figure out why nodeEqual(Array, Node) is passing.

**Comment by lelandrichardson** [comment]
@SeeThruHead I believe I've fixed this ^^. Thanks for reporting the bug!

**Comment by SeeThruHead** [comment]
Awesome thanks a lot @lelandrichardson
