### ISSUE TITLE
Use Enzyme for React Native without react-native-mocks (React v16)

### ISSUE THREAD

**Issue by gabrielrotbart** [airbnb/enzyme#1530]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### Current behavior

react-native-mocks currently does not support React v16. See https://github.com/RealOrangeOne/react-native-mock/issues/139

Reading through the issues there are hints that a re-write is happening but for now it seems the solution is downgrading to React < 16.

### Expected behavior

Hoping there are ways around using react-native-mocks. If not, a downgrade will have to do until that library is updated.

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by gabrielrotbart** [comment]
Never mind. Managed to fix all the issues in https://github.com/gabrielrotbart/react-native-mock/tree/update_to_support_react_16

**Comment by gusgard** [comment]
@gabrielrotbart I fix it with `yarn upgrade enzyme enzyme-adapter-react-16` hope it helps someone 👍
