### ISSUE TITLE
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

### ISSUE THREAD

**Issue by graingert** [airbnb/enzyme#1532]
### Current behavior
installation prints a warning

### Expected behavior
Installation does not print a warning
### Your environment
N/A

also a nice excuse to excise nomnom and its underscore craziness: https://github.com/airbnb/enzyme/issues/1249

**Comment by ljharb** [comment]
Warnings like this can and should be ignored; either way, closing in favor of https://github.com/aweary/rst-selector-parser/issues/12

**Comment by Schlesiger** [comment]
@ljharb Can this be expedited? `npm install` is now throwing an error and breaking my CI.

**Comment by Schlesiger** [comment]
In case anyone else comes across this, I ran `npm_config_loglevel=silent npm install` to ignore the warnings. Now it seems subsequent `npm install`'s complete successfully.

**Comment by ljharb** [comment]
The loglevel wasn't necessary; the reason `npm install` stopped showing the errors is urelated to this issue (deprecation warnings never should break CI).

**Comment by jrgleason** [comment]
It is ignored technical debt like this that makes me opinionated against a project. This project uses the dependency in one place and the dependency project has stated it will not be updating. Can't the dependency be replaced or forked?

**Comment by graingert** [comment]
The code that's deprecated isn't actually executed

On 24 Oct 2018 15:34, "Jackie Gleason" <notifications@github.com> wrote:

It is ignored technical debt like this that makes me opinionated against a
project. This project uses the dependency in one place and the dependency
project has stated it will not be updating. Can't the dependency be
replaced or forked?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/enzyme/issues/1532#issuecomment-432682405>, or mute
the thread

**Comment by ljharb** [comment]
@jrgleason a *warning* from a downstream transitive dependency isn’t technical debt; 
https://github.com/aweary/rst-selector-parser/issues/12 is the proper place to file it, not here; if there ever is a time when a dependency is ctually causing a real problem in enzyme - which it is currently not - then of course we’d have to find a way to replace it.

These warnings don’t break installs, they don’t obstruct anything - all they do is notify about a *potential* issue. In this case, there is no issue, and thus no action that is needed.

**Comment by edmorley** [comment]
@ljharb whilst that is true, having multiple persistent warnings from various transient dependencies being shown during yarn/npm install, trains users to ignore the warnings entirely - when for things like missing peer dependency warnings they really shouldn't be ignored (as I'm sure you can appreciate, given the number of `eslint-config-airbnb(-base)` support tickets that are due to invalid peer dependencies).

**Comment by ljharb** [comment]
@edmorley yes, i realize consolé warning output can be irritating, but that’s not the same thing as “ignored technical debt”. As for peer dep warnings, those show up on `npm ls`, which is the only place you should be validating your dependency graph - this warning shows up on install.
