### ISSUE TITLE
Use the new react-is package for internal introspection

### ISSUE THREAD

**Issue by aweary** [airbnb/enzyme#1538]
There is now an official package for introspection called `react-is` as of https://github.com/facebook/react/pull/12199. We should use this in the React 16 adapter instead of manually copying over the element type constants.

**Comment by ljharb** [comment]
Is it incompatible with older reacts? it'd be great to use it in all the adapters.

**Comment by aweary** [comment]
I think it should be backwards compatible, I don't see why not!

**Comment by ljharb** [comment]
@aweary looks like it might not be compatible with react 0.13 :-/ https://travis-ci.org/airbnb/enzyme/jobs/396931952

I'll use it on the other adapters for now tho.
