### ISSUE TITLE
Remove use of react-reconciler/reflection

### ISSUE THREAD

**Issue by aweary** [airbnb/enzyme#1539]
See https://github.com/airbnb/enzyme/pull/1399#issuecomment-363029503 for details. This seemed like a good idea at the time, but it will probably cause headaches in the future. We need to either just revert #1399 or think of a better solution. Related to #1538, maybe we could have `react-is/reflection`?

Either way, we should probably undo this.

**Comment by ljharb** [comment]
I’m fine reverting, but would it be better to expose an actual synced package for this?

**Comment by ljharb** [comment]
This is done for the 16 adapter, and future adapters, in #1778 / #1790.
