### ISSUE TITLE
ReactWrapper.update() after setState() on ReactWrapper doesn't update ReactWrapper.instance().state

### ISSUE THREAD

**Issue by GarrettGeorge** [airbnb/enzyme#1542]
### Current behavior
Wrapper is from `shallow(<SuggestedTags />)` and component is `wrapper.instance()`
```
it('should not remove tag when tagIndex is invalid', () => {
  wrapper.setState({ suggestedTags: ['Mozart'] })
  wrapper.update()
  component.handleClick(-1)
  expect(component.state.suggestedTags).toEqual(['Mozart'])
})
```

`setState` is properly rerendering but for whatever reason component which is `wrapper.instance()` is not having its state change.

### Expected behavior
Component.state.suggestedTags is equal to `['Mozart']` because `-1` is an invalid array index
#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 22.4.2
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by GarrettGeorge** [comment]
It seems as if this works.
```
it('should not remove tag when tagIndex is invalid', () => {
	component.state = { suggestedTags: ['Mozart'] }
	component = wrapper.instance()
	component.handleClick(-1)
	expect(component.state.suggestedTags).toEqual(['Mozart'])
})
```

Even though this is my `beforeEach` why does the component reference not hold? 
```
beforeEach(() => {
  component = wrapper.instance()
})
```

**Comment by koba04** [comment]
@GarrettGeorge I'm not sure the `handleClick` implementation but what about calling `wrapper.update()` after `component.handleClick(-1)`?

**Comment by ljharb** [comment]
Also try ``wrapper.state()` instead of `component.state`

**Comment by ljharb** [comment]
@GarrettGeorge did you figure this out?

**Comment by GarrettGeorge** [comment]
@ljharb Closed because isn't an issue from a dead codebase from a uni project. I was just cleaning out issues I created and were no longer necessary to be open.
