### ISSUE TITLE
setState in componetDidUpdate interrupt method call (and produce bad snapshot) 

### ISSUE THREAD

**Issue by LucaLovagnini** [airbnb/enzyme#1549]
I have this component (simplified version, let me know if you need more, but the original code is not opensrc):

    export default class MyComponent extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
                isLoading: false,
                data: {}
            };
        }
    
        componentDidUpdate(prevProps, prevState) {
            if(this.props.time && this.props.time !== prevProps.time){
               this.setState({
                 isLoading: true
               })
               fetch(...).then(data => {
                 this.setState({
                   data: data
                   isLoading:false
                 }
            }
        }
        render(){
          {isLoading, data} = this.state;
          return (isLoading ? /*show spinner*/ : /* show data*/);
        }
    
    }

This component works: it shows a spinner while fetching data, then it shows the data.

I'm trying to test it using jest and enzyme:

    test('Mounted correctly', async() => {
       let myComponent = mount(<MyComponent time='01-01-18'/>);
       myComponent.setProps({time: '02-01-18'}); //necessary to call componentDidUpdate
       expect(myComponent.state()).toMatchSnapshot();
    }

From my knowledge, in order to call `componentDidUpdate` **you have to** call `setPros` ([link](https://gist.github.com/fokusferit/e4558d384e4e9cab95d04e5f35d4f913)). However, following the debugger, the call end when hitting:

           this.setState({
             isLoading: true
           })

Which is kinda of expected, the problem is that the snapshot is:

    Object {
      "isLoading": true
      "data": {}
    }

Which is, of course, something that I don't want. How can I solve this?

**Comment by koba04** [comment]
@LucaLovagnini 
It seems to be an expected behavior because `fetch` hasn't resolved yet at the snapshot. What do you expect as the result?

**Comment by ljharb** [comment]
@LucaLovagnini can you reproduce this on the latest enzyme and adapter? If so, I'm happy to reopen.
