### ISSUE TITLE
Mounting component with props passed with spread operator doesn't work right

### ISSUE THREAD

**Issue by maksimsemenov** [airbnb/enzyme#1556]
### Current behavior
I'm trying to mount a component to make a snapshot test. When I pass component props with normal syntax, i. e.: `mount(<Component randomProp={randomValue}/>)` the mount work as expected and I see the full component tree in the snapshot.

However, if I'm trying to pass props with object spread operator, i. e. `mount(<Component {...props}/>)`, instead of a full component tree in the snapshot I see only the Component with passed props: `<Component randomProp={randomValue} />`

### Expected behavior
See the full component tree while mounting component with props passed with the spread syntax

### Your environment
OS: macOS High Sierra
Node: v8.3.0

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library                                      | version
| ---------------------------- | -------
| Enzyme                                   | 3.3.0
| enzyme-adapter-react-16    | 1.1.1
| enzyme-to-json                     | 3.3.1      
| React                                      | 16.2.0 
| Jest                                         | 22.4.2 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
enzyme doesn't have snapshot support, so I'm not sure how to interpret that part.

What is the output of `mount(<Component randomProp={randomValue}/>).debug()` vs `mount(<Component {...{randomProp: randomValue }} />).debug()`?

**Comment by maksimsemenov** [comment]
I'm sorry. I figure out it was totally my fault
