### ISSUE TITLE
[3.x] New initialization makes it difficult to integrate

### ISSUE THREAD

**Issue by xixixao** [airbnb/enzyme#1567]
I'm trying to migrate Facebook to Enzyme 3, but I'm running into the following:

We use Jest, and enzyme is included as an automatic global. This essentially translate to a `require('enzyme')` call whenever `enzyme` is used. So to upgrade to Enzyme 3, I would like this require to both load up enzyme and configure it. But this is practically impossible to do at the moment, because `enzyme-adapter-react-16` itself has a `require('enzyme')` call in its source.

The ideal solution would be to pull out the shared dependency (`enzyme.EnzymeAdapter`) into a separate package, that both `enzyme` and `enzyme-adapter-react-16` require.

What do you guys think?

(cc @mjesun, @cpojer )

**Comment by ljharb** [comment]
If we had a separate package it’d have to work like enzyme-adapter-react-helper does - ie, work for all react versions.

It seems like you could alias all enzyme requires that aren’t inside node_modules (since it’s never a good idea to transform third party code) to your file that requires and configures and re-exports enzyme?

**Comment by xixixao** [comment]
@ljharb The `EnzymeAdapter` implementation already has to work for all React versions, the way it is implemented today.

Jest unfortunately doesn't know what modules are in `node_modules` and what modules are in our codebase, it works on the level of Node's module resolution, so it's applied to both. I would have to modify `enzyme-adapter-react-16` to use `require.requireActual` for it to not be affected by Jest (but it would be nice to not have to modify third-party code, as you mention).

**Comment by ljharb** [comment]
Hmm, I'm not sure what you mean. https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/EnzymeAdapter.js is tightly coupled to the enzyme version, which is why it's not in a separate codebase.

I'm still a bit confused why you can't configure enzyme in a jest setup file, and then use a babel transform to inject an explicit enzyme import/require in tests that need it (or in the jest setup file, set up enzyme as an explicit global)?

**Comment by xixixao** [comment]
Pretty sure this is a dupe of this issue:
https://github.com/airbnb/enzyme/issues/1365

What you're suggesting with transform is not possible, unless it's some super smart transform that checks whether the file uses enzyme, and only then injects the configuration, and ideally checks whether enzyme is already configured, because I guess we wouldn't want to configure it a thousand times. We don't want to put enzyme as a dependency for every Jest test in our codebase.

Module initialize on initial `require` is the perfect time to do this configuration.

**Comment by ljharb** [comment]
It would take a pretty trivial transform to track all global variables and at program exit, determine if any of them are called "enzyme" and inject enzyme at the top of the file if so; there's a number of babel transforms in the ecosystem that do precisely this for React.

**Comment by xixixao** [comment]
@ljharb FB's system is a bit more complex than the usual Babel set up. Even running a transform only for tests is something we don't have support for atm. Again, it seems like an overtly complex solution. There's already `enzyme-adapter-utils`, how about moving the `EnzymeAdapter` there?

**Comment by ljharb** [comment]
There’s no technical reason why it couldn’t; the concern is that when a major change happens, it’d be harder to juggle the dependencies.

**Comment by cpojer** [comment]
> FB's system is a bit more complex than the usual Babel set up. Even running a transform only for tests is something we don't have support for atm.

This is incorrect however I do not agree that a babel transform is the right solution in this case.

**Comment by ljharb** [comment]
@cpojer is not having explicit globals (importing enzyme in every file) an option? If not, could the custom global be set up in a jest setup file?

**Comment by ljharb** [comment]
@xixixao @cpojer is this still something that's needed? any thoughts on https://github.com/airbnb/enzyme/issues/1567#issuecomment-373923167 ? (cc @aweary @gaearon)

**Comment by ljharb** [comment]
Closing; happy to reopen if needed.
