### ISSUE TITLE
Returning Null returns length of 1 

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#1571]
Why would returning null from a react component return a length of 1?  Shouldn't it be zero?

```
it.only('blah blah blah', () => {
  const someComponent = shallow(<SomeComponent />);
  expect(someComponent).to.have.length(0); // fails I get a length of 1
});
```

```
export function SomeComponent(props) {
  ....

  if(!something) return null; // why would length on shallow be 1 in this case?

  return (
    <div>Works!</div>
  );
}
```

**Comment by dschinkel** [comment]
nevermind, I always use test markers which allows me to do a to.have.length(0).  I took the marker out and so you get the enzyme wrapper back.

**Comment by ljharb** [comment]
You shouldn’t ever need test markers. Try adding .hostNodes() ?
