### ISSUE TITLE
Peer dependency issue with `enzyme-adapter-react-15.4`

### ISSUE THREAD

**Issue by VishalGulati** [airbnb/enzyme#1573]
I am facing the peer dependency issue with `enzyme-adapter-react-15.4`. I use JEST along with ENZYME to unit test my React application. I use below config:

    "react": "^15.1.0",
    "enzyme": "^3.2.0",
    "react-addons-test-utils": "^15.3.1",
    "enzyme-adapter-react-15.4": "^1.0.5",
    "react-dom": "^15.1.0",

And I get below errors even when I have all modules in place:

```
! peer dep missing: react@15.0.0-0 - 15.4.x, required by enzyme-adapter-react-15.4@1.0.5
npm ERR! peer dep missing: react-addons-test-utils@15.0.0-0 - 15.4.x, required by enzyme-adapter-react-15.4@1.0.5
npm ERR! peer dep missing: react-dom@15.0.0-0 - 15.4.x, required by enzyme-adapter-react-15.4@1.0.5
```

I see in the node_modules/react/package.json that the version installed is 15.6.2 whereas I specifically installed 15.1 as prod dependency.

My config files:

    // enzyme-setup.js
    import { configure } from 'enzyme';
    import Adapter from 'enzyme-adapter-react-15.4';
    
    configure({ adapter: new Adapter() });

**JEST:**

    {
        "testEnvironment": "jsdom",
        "setupTestFrameworkScriptFile": "./enzyme.setup.js",
        "testResultsProcessor": "jest-teamcity-reporter",
        "coverageReporters": [
            "teamcity", "lcov"
       ],
        "rootDir": "",
        "roots": [
          "__tests__/unit/"
        ],
        "moduleNameMapper": {
            "@PathToMappers(.*)$": "<rootDir>/src/data/mappers/$1",
            "@PathToModels(.*)$": "<rootDir>/src/data/models/$1",
            "@PathToMocks(.*)$": "<rootDir>/__tests__/mocks/data/$1",
            "@PathToXHRClient(.*)$": "<rootDir>/src/service/xhr-client/$1",
            "@PathToComponents(.*)$": "<rootDir>/src/component/$1"
        }
    }

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.2.0
| React            |  15.1.0

#### Adapter

- [x] enzyme-adapter-react-15.4

This breaks the dependency report generation step at CI (Teamcity) and hence fails to deploy. Any help shall be highly appreciated.

CC @brucewpaul, @ljharb, @bdwain.

**Comment by bdwain** [comment]
^15.1.0 does not indicate version 15.1. It says pull in the latest version with a major version of 15, which is 15.6 like you see in your node modules. 

You either need to switch your react and react-dom semvers to keep them below 15.5 (~15.1.0 would keep you at 15.1.x) or change your enzyme adapter to enzyme-adapter-react-15, since that is for 15.5 up to 16.

**Comment by ljharb** [comment]
@VishalGulati additionally, react-addons-test-utils must *precisely* match your react and react-dom versions. You should use `~` for react, react-dom, and react-addons-test-utils (whether you upgrade the adapter to the 15.5+ or not).

**Comment by VishalGulati** [comment]
Thanks @ljharb @bdwain I updated to adapter v15 and had to install React-test-renderer and it worked fine. Thanks again!

**Comment by Link631** [comment]
someone got this working with react 15.4?

**Comment by ljharb** [comment]
It should be working fine, as long as `npm ls` exits successfully.

**Comment by Link631** [comment]
uff... npm ls shows this...

I think, i have another problem somewhere else.

npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.12.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.3
npm ERR! missing: inherits@2.0.3, required by glob@7.1.3
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.3.5, required by tar@4.4.8
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.8
npm ERR! missing: safe-buffer@5.1.2, required by tar@4.4.8
npm ERR! missing: yallist@3.0.3, required by tar@4.4.8
npm ERR! missing: minipass@2.3.5, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.3.5
npm ERR! missing: yallist@3.0.3, required by minipass@2.3.5
npm ERR! missing: minipass@2.3.5, required by minizlib@1.2.1

**Comment by Link631** [comment]
I now have a clean npm ls.
Whatever I try, i can not get rid of this error:
 Cannot find module 'react-dom/test-utils' from 'ReactFifteenAdapter.js'

**Comment by ljharb** [comment]
and react and react-dom are both the same minor version?

**Comment by Link631** [comment]
yes...
I am using this preset:
npm install jest@23.6.0 @voitanos/jest-preset-spfx-react15 --save-dev --save-exact

after that, the package.json looks like this:

 "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": "1.13.1",
    "libraries.ressources": "file:packages/libraries.ressources.1.0.0",
    "react": "15.4.2",
    "react-dom": "15.4.2"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@voitanos/jest-preset-spfx-react15": "1.3.2",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "jest": "23.6.0"
  }

and in package.lock.json theese are referenced:

    "@voitanos/jest-preset-spfx-react15": {
      "version": "1.3.2",
      "resolved": "https://registry.npmjs.org/@voitanos/jest-preset-spfx-react15/-/jest-preset-spfx-react15-1.3.2.tgz",
      "integrity": "sha512-RG5EiTgUe6mK263IDaPYh904VPpZ0oesUjwXBfNULhmzinDSiIQTxP/DQxOQVuOv6ki748/p3dWwfIp+ay0w4A==",
      "dev": true,
      "requires": {
        "@types/enzyme": "3.1.8",
        "@types/enzyme-adapter-react-15": "1.0.3",
        "@types/enzyme-to-json": "1.5.2",
        "@types/jest": "23.3.10",
        "@types/react-test-renderer": "15.5.7",
        "enzyme": "3.4.1",
        "enzyme-adapter-react-15": "1.0.6",
        "enzyme-to-json": "3.3.4",
        "identity-obj-proxy": "3.0.0",
        "raf": "3.4.0",
        "react-test-renderer": "15.6.2",
        "ts-jest": "23.1.4"
      },
      "dependencies": {
        "@types/enzyme": {
          "version": "3.1.8",
          "resolved": "https://registry.npmjs.org/@types/enzyme/-/enzyme-3.1.8.tgz",
          "integrity": "sha512-HNOmXnm6RvyzVJRue3Ebrb1f609BQ0Lf5eNRCENPD95r6JKTTOwfDDpPE5tVp/fhJiBtvZ3To8a8E1Hq8eExNg==",
          "dev": true,
          "requires": {
            "@types/cheerio": "0.22.14",
            "@types/react": "0.14.46"
          }
        }
      }
    },

**Comment by Link631** [comment]
well... i guess now the problem got clear... 

what i did was npm i without optional
npm dedupe
npm up
npm prune.

I am depending on react 15.4, so I reference enymeadapter 15.

npm ls now tells me:
npm ERR! peer dep missing: react@^15.5.0, required by enzyme-adapter-react-15@1.0.6
npm ERR! peer dep missing: react@^15.6.2, required by react-test-renderer@15.6.2
npm ERR! peer dep missing: react-dom@^15.5.0, required by enzyme-adapter-react-15@1.0.6

I have react 15.4 and i can not upgrade it. So what can I do now?

**Comment by ljharb** [comment]
You’re using the 15 adapter. Use the 15.4 adapter instead. (also your react types are for 0.14 but that’s an unrelated problem)

**Comment by Link631** [comment]
which version of react types should I use? ... I will try 15.4 adapter again, but i remember, i was running into the issue described in this  topic headline...

**Comment by ljharb** [comment]
The types for X should always be the same minor version of X that you have.

**Comment by Link631** [comment]
hmm....

well... now i have following:
I did not understand, which version of types-react i should take. I checked the Versions and I dont see a version react/types 15.4.2... I guess i did not understand where the x should map.

Anyway, the react-types dont do any troubles.

I now have following:
I installed:
jest, enzyme with adapter 15.4 and react-addons-test-utils.
I added types/jest to types

when i build my project, it throws serveral errors like this::
Error - typescript - node_modules\@types\jest\index.d.ts(58,25): error TS1005: ')' expected.
Error - typescript - node_modules\@types\jest\index.d.ts(58,53): error TS1005: ',' expected.....

Thats why i started looking for the preset for sharepoint 2016 on prem... but theese dependencies also do not fit.

current package.json:
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@types/es6-promise": "0.0.33",
    "@types/jest": "^24.0.23",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": "1.13.1",
    "jest": "^24.9.0",
    "libraries.ressources": "file:packages/libraries.ressources.1.0.0",
    "react": "15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "15.4.2"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-15.4": "^1.4.1",
    "gulp": "~3.9.1"
  }
}

**Comment by ljharb** [comment]
Those look right to me; does `npm ls` exit successfully there?

As for those TS errors, that looks unrelated to enzyme (and you're using jest types for 24.0, but you have jest 24.9, so you probably need to make those match too).

**Comment by Link631** [comment]
hmm....

I cant reference a version for @types/jest@24.9.

Jest types got installed automatically by npm install jest. When I explicitly give that version number to types, it says following:

npm ERR! notarget No matching version found for @types/jest@24.9.0
npm ERR! notarget In most cases you or one of your dependencies are requesting

npm ls is clean.

**Comment by Link631** [comment]
possible, that this is an issue with npm version 5.6?
Also I am using tsc --version: 3.7.2

**Comment by Link631** [comment]
OMG... I solved it.

I forgot that I have a dependency to ts 2.2.4. TypeScript 2.2.4 needs jest types in version ^21.1.2.

Now I can compile.

I just saw theese dependencies on the jest/types documentation page on git.

Thanks for the support!
