### ISSUE TITLE
Fragment / id selector with initial number doesn't work

### ISSUE THREAD

**Issue by xixixao** [airbnb/enzyme#1577]
### Current behavior

`#0` is invalid selector, it was valid in v2

### Expected behavior

`#0` should be a valid selector

### Your environment
Jest
#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3
| React            |  16

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by xixixao** [comment]
Work around:
```es6
component.findWhere(
      n => n.prop('id') === SOME_NUMERICAL_ID,
    );
```

**Comment by ljharb** [comment]
`document.querySelector('#0')` throws for me in safari; I'm relatively sure that it's invalid for IDs to start with numbers?

**Comment by xixixao** [comment]
Looks like it, same in Chrome.
