### ISSUE TITLE
.is() doesn't accept complex selectors ? ( selector with a space? ) 

### ISSUE THREAD

**Issue by smoholkar** [airbnb/enzyme#1578]
Migrating tests from v2 to v3 

****************************
```
 const component = shallow(<TestComponent {...properties} />);
    const node1 = component.find('.node1-container');
    expect(node1.is('.abc')).toBeTruthy();
    expect(node1.is('.apple fa banana')).toBeTruthy();
```
Ain;t we now allowed to pass in a space in the selector for .is() ? Is this an expected change ? Should I just be using component.find('complex selector') instead ? 

#### API

- [X] shallow
- [] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  latest
| React            |  15.5.4

#### Adapter

- [ ] enzyme-adapter-react-16
- [X ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Is "'.apple fa banana'" the actual selector you're using? What exact error are you receiving, including the stack trace?

**Comment by smoholkar** [comment]
@ljharb This is what I have & this fails with the following error : 
```
expect(node1.is('.has-error fa fa-ban')).toBeTruthy();

```
 TypeError: This method does not support complex CSS selectors

      at buildPredicate (node_modules/enzyme/build/selectors.js:278:13)
      at ShallowWrapper.is (node_modules/enzyme/build/ShallowWrapper.js:742:55)
      at Object.<anonymous> (lib/components/private/field-wrapper/__tests__/field-wrapper.test.js:46:34)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ljharb** [comment]
I would expect that selector to be valid (altho I’d never expect it to match anything since there’s no html components with the tag names “fa” or “fa-ban”).

@aweary?

**Comment by ljharb** [comment]
Since `fa fa-ban` are invalid selectors, this seems correct.

There's been some selector improvements on master since this was filed; I'm going to close this, but am happy to reopen if a valid selector isn't working.
