### ISSUE TITLE
Version in package.json doesn't match npmjs.org

### ISSUE THREAD

**Issue by jcollum** [airbnb/enzyme#1579]
https://www.npmjs.com/package/enzyme -- 3.3.0 

https://github.com/airbnb/enzyme/blob/master/package.json -- `"version": "0.0.1",` in master

This is peculiar. What's the reasoning behind it? Usually the version in package.json on master matches the version in npm. The way this repo is doing it seems counter to community standards.

**Comment by ljharb** [comment]
This repo isn’t organized the way typical repos are; it contains many packages. The root package.json has private:true, indicating it’s never published.

This is more akin to a lerna monorepo - check the packages dir to see all the published items.

**Comment by jcollum** [comment]
Thanks. 

For anyone curious: lerna: https://github.com/lerna/lerna
