### ISSUE TITLE
Add getter for instance to child components

### ISSUE THREAD

**Issue by xixixao** [airbnb/enzyme#1583]
I guess this doesn't always work, but sometimes you can get the React instance of a child component via `.instance` field on ReactWrapper.

1) When does it work/doesn't?
2) Can we add a getter that isn't restricted to root?

**Comment by ljharb** [comment]
`.instance` is a method, not a getter: https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ReactWrapper.js#L206-L211
We don't have any test cases where `.instance()` doesn't return a component instance - however in React 16+, I believe SFCs don't have an instance, so I think it returns `null` there.

I'm not sure why this is restricted to the root on `mount` - I believe for any (non-SFC in React 16+) custom components, we should have an instance available in the tree.

Perhaps @lelandrichardson can speak to why this is restricted?

**Comment by ljharb** [comment]
On `mount`, `.instance()` definitely should already work on anything that has one - namely, custom components, and in React 16+, non-SFCs.
