### ISSUE TITLE
This undefined in mounted class components

### ISSUE THREAD

**Issue by gwenf** [airbnb/enzyme#1588]
`this` is undefined for React class components when I use `shallow` or `mount` from enzyme.

### This is the error I'm getting:

`TypeError: Cannot read property 'props' of undefined`

### Here is an example test file:

```js
import React from 'react';
import Enzyme, { shallow } from 'enzyme';
import sinon from 'sinon';
import PropTypes from 'prop-types';
import Adapter from 'enzyme-adapter-react-15';
Enzyme.configure({ adapter: new Adapter() })

import Logo from '../../app/logo/Logo';

describe('Logo', () => {
    const props = {
        cState: {
            go: sinon.spy()
        }
    };
    test('test that clicking sends to dashboard', () => {
        const wrapper = shallow(
            <Logo {...props} />
        );
        wrapper.find('a').simulate('click');
        expect(props.cState.go.called).toEqual(true);
    });
});
```

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            | 15.6.1

*Note: this problem happened before AND after I upgraded from Enzyme v2 to v3*

#### Adapter

- [ ] enzyme-adapter-react-16
- [x] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by aweary** [comment]
@gwenf can you share the implementation of the component you're testing, `Logo`? Sounds like there's probably a method that isn't bound correctly.

**Comment by gwenf** [comment]
@aweary thanks.
That was dumb of me. I just jumped into this codebase to change Karma/Mocha for Jest and I (wrongly) assumed it was an Enzyme problem.
Sorry about that.
