### ISSUE TITLE
How to traverse to nth node using DOM render? I am trying to test equality of select options.

### ISSUE THREAD

**Issue by xploreraj** [airbnb/enzyme#1591]
Using `render`, how can we traverse to nth node, say, 2nd or 3rd `select option` and match this for equality? Using `shallow` or `mount`, I understand we have `at`, but for `render`?

### Your environment
node 6

#### API

- [x] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.2.0

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by ljharb** [comment]
Since `render` is just a cheerio wrapper, you can use cheerio's [API](https://www.npmjs.com/package/cheerio#api) to traverse.

**Comment by xploreraj** [comment]
Thanks @ljharb, I figured that out later but I reached nth node by calling `next()`. If you know, can you tell me to reach to  particular index directly. Like 3rd in the options or 5th select of the page for example.

**Comment by ljharb** [comment]
Cheerio has .eq as well as .slice, those may help.
