### ISSUE TITLE
Mac OS test stopped not working after installing enzyme dependency

### ISSUE THREAD

**Issue by mnemanja** [airbnb/enzyme#1593]
### Current behavior
Tests watcher starts failing after installing Enzyme.

### Expected behavior
It should not affect the tests by just being installed.

From the list of 3 (currently found) problematic dependencies removing one makes the tests watcher work properly:

* node-sass-chokidar: 1.2.2
* material-ui: 0.20.0
* enzyme: 3.3.0

### Your environment
OS: Mac OS High Siera
node: 8.10.0 or 9.9.0
npm: 5.7.1

#### Version
| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.2.0
| node-sass-chokidar            |  1.2.2
| Material-ui            |  0.20.0 or 1.0.0-beta.38

#### Steps to reproduce
https://github.com/mnemanja/failing-tests-repo
1.  Clone the repo
2. Install dependencies
3. Run test

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [x] others (`"react-test-renderer": "^16.2.0"`) 

I have also created similar reports on all involved repos:
https://github.com/michaelwayman/node-sass-chokidar/issues/50
https://github.com/facebook/create-react-app/issues/4215
https://github.com/mui-org/material-ui/issues/10801

**Comment by ljharb** [comment]
Based on the linked issue, this is not an enzyme problem, and has been resolved.
