### ISSUE TITLE
Not able to interact/see modal content (Portal compenent). [enzyme 3.2.0]

### ISSUE THREAD

**Issue by giulioambrogi** [airbnb/enzyme#1596]
I am not able to interact or see the **content** of Portal components such as a **modal** from `semantic-ui-react`. 
For instance I am not able to:
- see the `.html()` of the element
- `find` any of its children, then I cannot simulate any event on its children

Please see the code sandbox that demonstrate the issue: https://codesandbox.io/s/526ozp2zwl.

I understand there are workaround to get the html content of the modal. How about when the state changes? Does enzyme propagate the state changes to the portal components?
Am I testing it wrong? 

### Current behavior

`find(Modal).find(button)` doesn't return child button element
`find(Modal).html()` returns null

### Expected behavior
`find(Modal).find(button)` to return child button element
`find(Modal).html()` to return html representation of the modal

### DEMO
See the unit test in this code sandbox: https://codesandbox.io/s/526ozp2zwl.

#### API
- [ ] shallow (not tested)
- [x] mount
- [ ] render (not tested)

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.2.0
| React            |  16.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by jgzuke** [comment]
It looks like `semantic-ui-react` is not using react portals in the linked version, but is using their own [Portal implementation](https://github.com/Semantic-Org/Semantic-UI-React/blob/36d84690c82f978eecf13974c9d78df76feca518/src/addons/Portal/Portal.js).

Once the new `semantic-ui-react` Portal is out (which uses `createPortal`) this should work properly.

**Comment by ljharb** [comment]
In that case, see https://github.com/airbnb/enzyme/blob/d65fc69d87e985fcb51ad5cdc8fdec4933519fe6/docs/common-issues.md#testing-third-party-libraries - there's nothing we can really do until it supports proper Portals.
