### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 13

### ISSUE THREAD

**Issue by diegohaz** [airbnb/enzyme#1598]
### Current behavior

Getting `Enzyme Internal Error: unknown node with tag 13` when testing things with the new React Context API (React v16.3.0).

### Expected behavior

I was using https://github.com/jamiebuilds/create-react-context before with no errors. That's what I expected to have after upgrading React.

### Your environment

macOS
npm 5.6.0
Node v9.7.1

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |   16.3.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by diegohaz** [comment]
Closing this in favor of #1509 and #1513

**Comment by julianguyen** [comment]
Did you figure out what the issue was?

**Comment by diegohaz** [comment]
That was because enzyme didn't support React Context types by the time I created this issue. With the latest versions, it should work (I'm not using Enzyme anymore though, switched to https://github.com/kentcdodds/react-testing-library)
