### ISSUE TITLE
Documentation: in the doc for `shallow`, the link to `hostNodes` links to the .md instead of the .html

### ISSUE THREAD

**Issue by julienw** [airbnb/enzyme#1607]
In the [documentation for `shallow`](http://airbnb.io/enzyme/docs/api/shallow.html) the link for `hostNodes` links to the [markdown version](http://airbnb.io/enzyme/docs/api/ShallowWrapper/hostNodes.md) instead of the [html version](http://airbnb.io/enzyme/docs/api/ShallowWrapper/hostNodes.html) like others.

The raw documentation for `shallow` looks fine, so I don't know what brings this issue.

**Comment by ljharb** [comment]
Ah, thanks for clarifying. Mind submitting a PR?

**Comment by julienw** [comment]
I could if I'd understand the issue :-) Do you have an idea of why this happens ?

**Comment by ljharb** [comment]
Ah, the linked PR indeed solves it - but the docs won’t be updated until the next release, so you won’t see the fix until then :-)

**Comment by julienw** [comment]
Ah thanks, good to know ! I didn't know that having the links (or not!) in SUMMARY.md actually had an effect elsewhere...
