### ISSUE TITLE
Please publish package precompiled to es5

### ISSUE THREAD

**Issue by ogim** [airbnb/enzyme#1609]
hi 

I am using create-react-app and we use enzyme :-)

However when we try to build it can't be minified, probably because the enzyme package is distributed as an es6 package. ( this problem is described at the bottom of http://bit.ly/2tRViJ9 )

Can you please distribute it as es5 ?

here is the error log

/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build --scripts-prepend-node-path=auto

> FE@0.1.0 build /Users/.../Projects/fe/client
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/enzyme-to-json/createSerializer.js:18 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FE@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the FE@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-04-09T11_45_21_110Z-debug.log

Process finished with exit code 1

**Comment by ljharb** [comment]
`enzyme-to-json` is not part of this project; all of our packages are always transpiled to ES5 prepublish.

I believe the repo is here: https://github.com/adriantoine/enzyme-to-json
