### ISSUE TITLE
"ReactWrapper#debug" API does not work, when after async function called, that includes "setState".

### ISSUE THREAD

**Issue by naoki-tomita** [airbnb/enzyme#1610]
`ReactWrapper#debug` and `ReactWrapper#find` does not work, after calls setState from async function.
But, `ReactWrapper#html` is work. So, I think this behavior is bug.

#### I wrote sample code of this issue.
https://github.com/naoki-tomita/enzyme-test

### Current behavior
`ReactWrapper#debug`, `ReactWrapper#find` does not returns updated DOM, after async function called.
But, `ReactWrapper#html` is returns updated DOM.
Please check my sample code.

### Expected behavior
`ReactWrapper#debug`, `ReactWrapper#find` returns updated DOM correctly, after async function called too.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version|
| ---------------- | -------|
| Enzyme           | 3.3.0|
| React            |  16.3.1|
|`enzyme-adapter-react-16 ` | 1.1.1|
|jest|22.4.3|

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is expected; you need to call `wrapper.update()` after [this line](https://github.com/naoki-tomita/enzyme-test/blob/master/__tests__/Components.test.jsx#L19)

**Comment by naoki-tomita** [comment]
Awesome!!!!
Thank you @ljharb !!
The test has passed.
