### ISSUE TITLE
Can't find tags containing a dot

### ISSUE THREAD

**Issue by YagoGG** [airbnb/enzyme#1611]
### Current behavior

This is related to #439.

When `.find()`ing a component that contains a dot (`.`) in its name (e.g. `<Some.Name />`), enzyme is unable to get it.

Tried with:

```js
component.find('Some.Name')
component.find('Some\.Name')
component.find('Some\\.Name')
```
But all of them return a 0-length wrapper.

### Expected behavior

It should return the components that match that tag name, probably with the escaped syntax: `component.find('Some\.Name')`.

CSS selectors [apparently support](https://stackoverflow.com/questions/3447329/styling-elements-with-a-dot-in-the-class-name) the `\.` escaping.

---

#### API

- [x] shallow

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.2.0
| React            |  16.1.1

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by YagoGG** [comment]
I just found out that actually that is rendered to `SomeName`. Closing, thanks!

**Comment by brunohkbx** [comment]
I'm running into the same issue.

Thats my snapshot
```
<withTheme(Appbar.Header)>
  <withTheme(Appbar.Content)
    title="Flashcards"
  />
  <Appbar.Action
    icon="search"
    onPress={[MockFunction]}
    size={24}
  />
</withTheme(Appbar.Header)>
```

It didn't found anything when I've tried ``` wrapper.find('Appbar.Action') ``` .

@YagoGG how did you solve this problem?

**Comment by ljharb** [comment]
@brunohkbx try finding it by reference instead of with a string name.

**Comment by brunohkbx** [comment]
@ljharb sorry, can you provide me an example?
thanks.

**Comment by ljharb** [comment]
Import it, and pass the component itself onto find

**Comment by brunohkbx** [comment]
Thanks @ljharb, got it :smile:
