### ISSUE TITLE
ShallowWrapper.text() with only &nbsp; should equal to ' '

### ISSUE THREAD

**Issue by nelsonchen90** [airbnb/enzyme#1613]
### Current behavior
if the element only contains `&nbsp;`, when reading it with shallowWrapper.text(), it doesn't equal to ' ' (one space)

### Expected behavior
`&nbsp;` should equal to ' ' (one space)

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.3.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

### code snippet
```
// component
const Foo = () => (
  <div className={styles.foo}>
    &nbsp;
  </div>
);


// test
 const container = shallow(<Foo />);
  expect(container.find(`.${styles.foo}`).text()).toEqual(' ');


// test result
expect(received).toEqual(expected)

    Expected value to equal:
      " "
    Received:
      " "

```

**Comment by nelsonchen90** [comment]
related to #1349 ?

**Comment by rardoz** [comment]
For now this works



```js
expect(container.find(`.${styles.foo}`).text()).toEqual(' \u00a0');
```

**Comment by ljharb** [comment]
I think the issue is that perhaps your literal non-breaking space in your tests is getting transformed to a normal one.

I've added explicit tests for the character codes generated by non-breaking spaces, and they both are already passing.
