### ISSUE TITLE
Mono-Repo's: I did something stupid, and the error threw me....

### ISSUE THREAD

**Issue by peter-mouland** [airbnb/enzyme#1616]
### Current behavior
when running tests (using `jest`) I kept seeing this error:

```
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:
    
          import Adapter from 'enzyme-adapter-react-15';
    
          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
```

I have setup my adapters correctly (I promise!).  My jest.json had the `setupFiles` correctly set (which i knew because after whacking a `console.log` in the file, _classic_, i could see it in the terminal:

```
  "setupFiles": [
    "<rootDir>/tests/jest/enzymeSetup.js"
  ]
```

While creating a reduced-test case it suddenly started working again and I was able to track it down - it was the mono-repo's fault!  (well, my fault then if you have to know. yes, I did set up the mono-repo).  Like most mono-repos, I had the following structure:

```
./app/
 | -> packages
 |      | -> package-a
 |      |      | -> package.json (containing devDependency: enzyme 3.3.0)
 |      | -> package-b
 |      |      | -> package.json (containing devDependency: enzyme 3.3.0)
 | -> package.json (containing devDependency: enzyme 3.3.0)
```

as you can see I have my devDependency set in each package.  This caused enzyme to think it wasn't setup correctly.  Clearly this is my own fault, but it did take me a little time to track down.

I have setup a few mono-repo's and previously have never include `devDependencies` in each packages `package.json`.  This time I forgot and create a few packages, all with enzyme as a devDep.

### Expected behavior

I'm not sure : 
 * maybe a different error message to highlight duplicate enzymes (not that `npm ls enzyme` would find dupes as there were no dupes in the root project).
 * maybe enzyme, or more likely _jest_, should still pick up the correct installation of enzyme from the root, rather than the package dir?
 * or, as I suspect detecting every possible _stupid_ thing we do is difficult, a word about mono-repos in trouble shooting or readme?

### Your environment
macOS X 10.3
node 9

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.3.0
| React            |  16.3
| Jest | 22.4.3

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Whatever monorepo tool you're using needs to hoist dependencies that span multiple subprojects - lerna does this automatically.

I don't think it would make sense to have a generic note about monorepos in enzyme's docs - all it would say is "don't do it yourself, use one of the multiple monorepo management tools"

**Comment by peter-mouland** [comment]
cool, i'm using lerna - but maybe not to run for tests i.e. i think i've set up the runner to search all packages dirs.  i'll take a look at how to do it another way with lerna... i just wouldn't want to end up with 10s of separate coverage reports rather than one.

Thanks for getting back.
