### ISSUE TITLE
Testing select element value with enzyme

### ISSUE THREAD

**Issue by cgungaloo** [airbnb/enzyme#1617]
Hi Ive been struggling with this and cant seem to get it to work.

Im try to test the value of a select element after a simulate.
```jsx
it('should select transmission',() =>{

  const wrapper = mount(<Transmission/>);
  const select = wrapper.find('select').first();
  select.simulate('change',{target: {value:"manual"}});
  expect(select.props().value).toEqual('manual');
});
const Transmission=(props) =>{
return(

<select name="transmission" onChange={props.handleChange}>
  <option value="automatic">Automatic</option>
  <option value="manual">Manual</option>
</select>
);
}
export default Transmission;
```
Even if I remove the onChange method from the select, the error is the same:

Expected value to equal:
  "manual"
Received:
  undefined

Difference:

  Comparing two different types of values. Expected string but received undefined.
Appreciate some help.

**Comment by ljharb** [comment]
`simulate` does not actually simulate anything; all it does is invoke a prop for you.

I recommend avoiding it entirely, and doing `.prop('onChange')()` if that's what you want.

**Comment by rv-rhill** [comment]
Excellent solution, @ljharb. Thank you!

**Comment by vanor89** [comment]
@ljharb I've seen you suggest this in various posts but there are times when just running on change is worthless, because this doesnt actually change the value of the select, so if something depends on the value of the selected option that will not work. this is for UNCONTROLLED selects that do not have a `value` prop. I have state that is bound to the selects state, I do not change this state in the "onChange" method, this is done automagically by HTML when you select an option in an uncontrolled select, this is what will work in those cases:
```javascript
await act(async () => {
  const option = wrapper.find('.curriculum select option').at(2);
  option.simulate('click');
  wrapper.find('.curriculum select').simulate('change', {
    target: { name: 'curriculum', value: option.prop('value') },
  });
});
wrapper = await wrapper.update();
```

**Comment by ljharb** [comment]
@vanor89 i'm not sure what you mean. the `onChange` indeed does not change the value - the change is what triggers `onChange`. You, however, can set the value directly, or you can just pass a custom event object into `onChange`.

**Comment by vanor89** [comment]
You cant set a value of an undefined property. `value` does not exists in the props of the element, because it is uncontrolled, I only have a `defaultValue` on it

**Comment by ljharb** [comment]
Right, but in the enzyme tree, you can set the `value` prop directly on the resulting `select`, and then invoke `onChange`. In most cases, you won't need to actually set the value (because you won't be reading it off of the select's ref), so passing it into `onChange`'s event object param would be sufficient.

**Comment by vanor89** [comment]
You cannot set the value prop directly in the resulting select, that throws an error, "value" is undefined

**Comment by ljharb** [comment]
gotcha. `simulate` doesn't do that either, though, so either way you have to manually do it.

If you find the `select`, it's a DOM node - you can `.setAttribute('value', 'whatever')` directly. Does that not work?

**Comment by vanor89** [comment]
No, that did not work. value was still undefined when I read it in the change handler of the second select.

Simulate doesn't really do anything other than running a function that has been registered as an event handler, its not throwing any actual events, which is where all the work is happening, that is actually done in the click event of the option itself, when you click an option, HTML sets the value of its select to its value.

That's what I found works, click the option. THEN trigger the change event.

**Comment by ronaldomaiacorrea** [comment]
Hello,

I'm a beginner in Enzyme. I have the same question discussed here. I've tried all that you guys with no success.
Maybe you can help.

The test:

```
 it("Should show table when one formula is selected", () => {
    const handleChange = jest.fn();
    const formulaName = "F1";
    const wrapper = mount(<Formulas />);
    const selectFormula = wrapper.find("select").first();
    selectFormula.simulate("change", { target: { value: "F1" } });
    console.log(selectFormula.props());
    expect(selectFormula.props().value).toEqual(formulaName);
  });
```
The log:
```
