### ISSUE TITLE
cannot use component constructor to find child elements

### ISSUE THREAD

**Issue by tylerthehaas** [airbnb/enzyme#1618]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

### Current behavior
When I attempt to find a child elemnt using `wrapper.find(El)` I get the following error.
`     TypeError: Enzyme::Selector expects a string, object, or Component Constructor`.

### Expected behavior
When attempting to find a child element using `wrapper.find(El)` it should return a new shallow wrapper.

### Your environment
using the mocha test runner on a mac running sierra.

#### API

- [x ] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
What is `El` here?

**Comment by ljharb** [comment]
Happy to reopen when more info is provided.

**Comment by josezapataruiz** [comment]
Hi @tylerthehaas. Were you able to solve this problem?

I have same problem with reactstrap 9.1.5
