### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 12

### ISSUE THREAD

**Issue by kkwiatkowski** [airbnb/enzyme#1620]
### Current behavior
React in version 16.3 introduces new Context API. That API comes with two new node types (12 and 13).
These node types are not supported and therefore `enzyme-adapter-react-16` is throwing an error:
```bash
# for ContextConsumer
Enzyme Internal Error: unknown node with tag 12
```
or
```bash
# for ContextProvider
Enzyme Internal Error: unknown node with tag 13
```
when you use Context API inside your React components.

An example:
```jsx
import React from 'react';
import { mount } from 'enzyme';

const { Provider, Consumer } = React.createContext();
const Component = () => (
  <Provider value="test">
    <Consumer>{value => <span>{value}</span>}</Consumer>
  </Provider>
);

mount(<Component />); // this will thrown an error mentioned earlier

```

### Expected behavior
New node types are handled correctly.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  ^3.3.0
| React            |  ^16.3.0

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by kkwiatkowski** [comment]
@baldwmic thanks for your answer. For some reason I couldn't find anything around it.

**Comment by KaiHotz** [comment]
Did this fix get released yet ? i still have this problem on Enzyme v3.3.0 with enzyme-adapter-react-16 v 1.1.1

**Comment by ljharb** [comment]
No, not yet. Please be patient.

**Comment by dzearing** [comment]
Sorry to ping here, but any ETA on the release? This is blocking a lot of people, I'd suspect. Basically we aren't able to move to the new context without breaking existing enzyme tests.

**Comment by ljharb** [comment]
No ETA just yet. I understand the frustration and that it's blocking many people, including Airbnb, from using many of React 16's new features.

It will be released as soon as it's ready.

**Comment by nhunzaker** [comment]
@ljharb just chiming in to say thanks for taking the time to do it right. Enzyme is an amazing library!

**Comment by msluther** [comment]
@ljharb Is there an issue we can follow that isn't closed to check on the progress of a fix here getting published?

**Comment by msluther** [comment]
@ljharb Thank you! 😄

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)

**Comment by Fl4v10** [comment]
I got this problem with _"enzyme": "^3.9.0"_

**Comment by ljharb** [comment]
@Fl4v10 please file a new issue
