### ISSUE TITLE
High order component doesn't have its own methods

### ISSUE THREAD

**Issue by egor-sorokin** [airbnb/enzyme#1621]
### Current behavior
When I unwrap my high order component and call `shallow` on the unwrapped component it doesn't have its own methods. (see code below for details)

**api.test.js**
```
import React from 'react';
import withFetching from './api';
import { DEFAULT_API_URL, URL_PATH_EDUCATIONS } from '../constants/index'
import Educations from '../components/Educations/index';
import { shallow, render, mount } from 'enzyme';
import axios from "axios";

jest.mock('axios', () => ({
  get: jest.fn(() => Promise.resolve({ data: { educations: [] }}))
}));

describe('WithFetching',  () => {
  const WithFetching = withFetching(URL_PATH_EDUCATIONS, Educations);

   // succeded
  it('checks that fetchData was called only once', () => {
    const spy = jest.spyOn(WithFetching.prototype, '_fetchData');
    const wrapper = mount(<WithFetching />);

    expect(spy).toHaveBeenCalledTimes(1); 
  });

  
  // failed
  it('should fetch educations', () => {
    const wrapper = shallow(<WithFetching />);
    
    axios.get.mockImplementation(() =>
       Promise.resolve({
       data: { educations: ["cat.jpg"] }
      })
    );

    return wrapper._fetchData().then(educations => expect(educations).toEqual(["cat.jpg"]));
  });
});
```

**api.js** 
```
import React, { Component } from 'react';
import axios from 'axios';
import { DEFAULT_API_URL } from '../constants/index'

const withFetching = (url, CurrentComponent) =>
    class WithFetching extends Component {
      constructor(props) {
        ...
      }

      componentDidMount() {
        this._fetchData();
      }

      _fetchData() {
        this.setState({isFetching: true});

        axios.get(DEFAULT_API_URL + url)
          .then(response => {
            ...
          })
          .then(data => this.setState({data, isFetching: false}))
          .catch(error => this.setState({error, isFetching: false}));
      }

      render() {
        return (
          <CurrentComponent {...this.props} {...this.state} />
        )
      }
    };

export default withFetching;
```

Educations.js (dummy component)
```
import React, { Component } from 'react';
import withFetching from '../../utils/api';
import { URL_PATH_EDUCATIONS } from '../../constants/index';

const Educations = ({ data, isFetching, error }) => {
  const educations = data.educations || [];

  return (
     ...
  );
};

export default withFetching(URL_PATH_EDUCATIONS, Educations);
```

So when I call `_fetchData` I get an error:
`wrapper._fetchData is not a function`
But when I run a test to check whether this function was called or not, I get that actually it was called.

When I use `expect(wrapper.instance()).toMatchSnapshot()` or `expect(wrapper.dive().instance()).toMatchSnapshot()` there is no `_fetchData `method in the final snapshot. I am pretty new in testing and not sure whether I do something wrong or it's a bug.

### Expected behavior
**_fetchData()**  is defined and can be called

### Your environment
 System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 9.8.0
    Yarn: 1.5.1
    npm: 5.8.0

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.1
| Jest               | 22.4.3

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by egor-sorokin** [comment]
@mykhailo-riabokon 👍  thank you, I've another question, but I think it's better to ask it on StackOverflow since it's not relevant to this issue

**Comment by mykhailo-riabokon** [comment]
@egor-sorokin could you close this issue if it's resolved for you.
