### ISSUE TITLE
Snapshots failing after upgrade from Enzyme 2 to 3

### ISSUE THREAD

**Issue by alistaircolling** [airbnb/enzyme#1622]
Hi there, I'm in the process of updating a project from React 15 to 16. Part of this requires me to update Enzyme to 3.x which I have done. I've been through the [doc](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md) but couldn't find anything relevant to this issue. I guess that I need to update snapshots where the formatting has changed (e.g.  trailing commas added). I'm not sure if the fact that all handlers e.g. `onBlur` have anonymous functions  - is this expected?

### Current behavior
Many snapshot tests fail for trailing commas, line breaks & handler functions being anonymous:
```
  + expected - actual
      -    onBlur={[Function]}
      -    onChange={[Function]}
      +    onBlur={[Function bound onBlurHandler]}
      +    onChange={[Function bound onChangeHandler]}
...
             disabled={false}
             name="ticketTime"
             placeholder="Setup instructions.."
             rows={10}
          -  value="Sample text"
          ->
          +  value="Sample text">
...
      -          "label": "one",
      +          "label": "one"
               }
      -      }
      -    >
...
    + expected - actual
           <div>
          -  <h1
          -    key="0"
          -  >
          +  <h1>
```

### Expected behavior
Snapshots all pass.

### Your environment
OSX 
npm 9.3.0
yarn 1.5.1

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme          | 3.3.0
| React            |  16.3.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
@alistaircolling it's highly recommended to get everything working on enzyme 3 and react 15, prior to upgrading to react 16.

As for your issue; enzyme doesn't support snapshots in any way, so it might be an issue with whatever you're using to work with snapshots.
