### ISSUE TITLE
setState() can only be called on class components -- but my component is a class

### ISSUE THREAD

**Issue by jcollum** [airbnb/enzyme#1624]
### Current behavior

The docs: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setState.md

The docs say to do this: 

```
const wrapper = shallow(<Foo />);
...
wrapper.setState({ name: 'bar' });
```

My class:  `class PrivacyInquiry extends React.Component {`. The class renders fine on the page. 

This is the test: 

```
it('Shows additional info box if category is Complaint or Question ', (done) => {

...
    const privacyPage = shallow(<PrivacyInquiry country="us" language="en" path="/" localizations={localizations} />);
    privacyPage.setState({ selectedCategory: 'Complaint' }, ()=>{
      const textArea = privacyPage.find('textarea#additionalInfo');
      expect(textArea.length).toEqual(1);
      done();
    });

  });
```

When I run the test it fails on the `setState` line: 

```
 ShallowWrapper::setState() can only be called on class components
```

It looks like my component is a class. It looks like I'm doing exactly what the docs say to do. It seems that everything I'm doing is normal React stuff. I have another test that just tests the rendering of `PrivacyInquiry` and looks for some items on the page and that test passes. That test uses `mount` though.  

### Expected behavior

`setState` changes state 

### Your environment
```
✗ node --version
v6.9.5
```

Is the node version the problem? I can't really change it

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3
| React            |  16.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by jcollum** [comment]
Closing. Turns out my class wasn't exported. 

`class PrivacyInquiry extends React.Component {`

to 

`export class PrivacyInquiry extends React.Component {`

Confusing error still, since the page rendered fine according to Enzyme.

**Comment by hoainamcr** [comment]
The same issue.
So, in the root app, Ex: app.js
to export look like 
`class App extends React.Component {
     // todo
}`
`export default hot(module)(withHttpErrorHandler(withErrorAlert(App)));`

please help me how to run test

**Comment by DenisBubnov** [comment]
> The same issue.
> So, in the root app, Ex: app.js
> to export look like
> `class App extends React.Component { // todo }`
> `export default hot(module)(withHttpErrorHandler(withErrorAlert(App)));`
> 
> please help me how to run test

Do you have the solution of your problem?

**Comment by hoainamcr** [comment]
> > The same issue.
> > So, in the root app, Ex: app.js
> > to export look like
> > `class App extends React.Component { // todo }`
> > `export default hot(module)(withHttpErrorHandler(withErrorAlert(App)));`
> > please help me how to run test
> 
> Do you have the solution of your problem?

NO @Denis, I Still waiting for anyone can help.

So, I consolog the App component. it show like below

![image](https://user-images.githubusercontent.com/8084862/48471364-578c1680-e826-11e8-953b-791eb9c39d61.png)

**Comment by ljharb** [comment]
@hoainamcr if you notice in the last debug, you’re using ContextConsumer, which is not yet supported in enzyme. See #1553.

**Comment by hoainamcr** [comment]
> @hoainamcr if you notice in the last debug, you’re using ContextConsumer, which is not yet supported in enzyme. See #1553.

Yes @ljharb , so how to switch to a normal component to set state for it? actually I'm out of options. Many thanks for your infomation.

**Comment by ljharb** [comment]
@hoainamcr I'm not sure which of your components is using `createContext`.

**Comment by r3wt** [comment]
I am facing similar issue, in my case my component is wrapped with `withStyles` from `material-ui`. i have checked calling `instance()` on the wrapper and it returns null, is there any known workaround?

**Comment by ljharb** [comment]
@r3wt `.dive()`.

**Comment by rmakarov** [comment]
.dive() is only for shallow wrapper.
