### ISSUE TITLE
API Addition: `findByClass`

### ISSUE THREAD

**Issue by danny-andrews-snap** [airbnb/enzyme#1629]
I think it would be really nice to have a `findByClass` (or equivalent) method. 99% of the time, I select portions of the DOM by class, and when using css-modules, you end up having to do awkward things 
like

```js
const subject = wrapper.find(`.${styles.slotNumberCol}`);
```

to select them.

```js
const subject = wrapper.findByClass(styles.slotNumberCol);
```

would be **much** nicer.

Even in the normal case, it would nicer (albeit slightly) to do

```js
const subject = wrapper.findByClass('slot-number-col');
```

rather than

```js
const subject = wrapper.find('.slot-number-col');
```

**Comment by danny-andrews-snap** [comment]
Similar to #349 but different in that it matches class names exactly, not by `RegExp`. I would argue this is a much more common scenario and so warrants a special method in the API.

**Comment by ljharb** [comment]
The "special native method" you mention is a legacy one; the modern API is to *only* use querySelector/querySelectorAll.

I think that "find by class" is a pattern that *shouldn't* be common; either way, I think adding a specialized convenience method to avoid prepending a `.` is complexity we probably don't want.

**Comment by serhii-yakymuk** [comment]
@danny-andrews-snap 
Just use this, if you're using jest
https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules

**Comment by Everettss** [comment]
@danny-andrews-snap 

> > I think that "find by class" is a pattern that shouldn't be common;

> 
> What? Why? How else should you find elements?

Take a look at the `data-testid` pattern https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269

**Comment by ljharb** [comment]
I highly discourage that pattern; test IDs is something that was common 5-10 years ago, but is an antipattern because you're a) changing your production code for testability, and b) you're coupling your code to your tests, which makes your tests more brittle (they aren't testing what you think they are).

**Comment by ljharb** [comment]
@craigkovatch if you're selecting enough DOM elements that 3200x even matters, you've got something subpar with your architecture :-)

**Comment by ljharb** [comment]
I'm going to close this; the added complexity in enzyme isn't worth it for the simple sugar of avoiding a template literal with a leading dot.

**Comment by danny-andrews-snap** [comment]
FYI, I realized this is off-topic. Feel free to ignore.

> I highly discourage that pattern; test IDs is something that was common 5-10 years ago, but is an antipattern because you're a) changing your production code for testability, and b) you're coupling your code to your tests, which makes your tests more brittle (they aren't testing what you think they are).

@ljharb Just out of curiousity, how would you recommend selecting elements in your test if not by `className` or test-id?

**Comment by ljharb** [comment]
@danny-andrews-snap i don't have a silver bullet in mind; it'd depend on your specific component.
