### ISSUE TITLE
cheerio text() method for children

### ISSUE THREAD

**Issue by cliren** [airbnb/enzyme#163]
How do we solve this in enzyme? The enzyme version fails to retrieve text from a child element.

Cheerio version:

```
let $ = cheerio.load(<div><div class="comment">hello</div><div class="comment">world</div></div>);
$(".comment").length.should.eql(2);
$($(".comment")[0]).text().should.eql("hello");
$($(".comment")[1]).text().should.eql("world");
```
Enzyme version:

```
let $ =render(<div><div class="comment">hello</div><div class="comment">world</div></div>);
$.find(".comment").length.should.eql(2);

**//DOES NOT WORK as text is not a function on child elements returned**
$.find(".comment")[0].text().should.eql("hello");
$.find(".comment")[1].text().should.eql("world");
```

**Comment by lelandrichardson** [comment]
doing `$($.find(".comment")[0]).text().should.eql("hello");` should work, no?

Additionally, I believe enzyme exposes a method to get the first element wrapped:

`$.find(".comment").first().text()`

**Comment by cliren** [comment]
Complained that $ is not a function
```
$($.find(".comment")[0]).text()
```

The following works fine but can only get first and last elements, what about others?
```
$.find(".comment").first().text() and $.find(".comment").last().text()
```

Using Cheerio's .eq(index) method to rescue. A better method name would have been .get()!

```
$.find(".comment").eq(0).text()
$.find(".comment").eq(1).text()
and so on
```

**Comment by ljharb** [comment]
@cliren `eq` returns a wrapped element, `get` returns a raw one.

**Comment by cliren** [comment]
@ljharb Thanks and I noticed that later. I think .eq should be renamed to or add a new method .getWrappedElement to make it more intuitive. Even better .get returns a wrapped element and .get().element /rawElement gives the raw one.

**Comment by lelandrichardson** [comment]
@cliren i don't like the naming of `.eq()` either, which is why for shallow and mount we use `at()` and `get()` (though those could be further disambiguated as well).

We can't change the cheerio wrapper right now since this is cheerio's API and they are trying to follow jquery directly.

**Comment by Aweary** [comment]
@lelandrichardson maybe close this if it's a wontfix? 😄
