### ISSUE TITLE
Simulated click does not update component props

### ISSUE THREAD

**Issue by pivcec** [airbnb/enzyme#1632]
### Current behavior
When I simulate a click on avatarImage then pieWrapper length = 0.

```
  it('Renders PieWrapper when AvatarImage is clicked', () => {
    const updateHoveredAvatarId = jest.fn();
    const updateSelectedAvatarId = jest.fn();
    const avatar = shallow(<Avatar
      activeAvatarId={null}
      hoveredAvatarId={1}
      id={1}
      selectedAvatarId={2}
      updateHoveredAvatarId={() => updateHoveredAvatarId()}
      updateSelectedAvatarId={() => updateSelectedAvatarId()}
    />);
    const avatarImage = avatar.find(AvatarImage);
    avatarImage.simulate('click');
    // avatar.instance().forceUpdate();
    // avatar.update();
    const pieWrapper = avatar.find(PieWrapper);
    console.log(avatarImage);    
    console.log(pieWrapper);
    // const pieWrapper = avatar.find(PieWrapper);
    // expect(pieWrapper.instance()).toBeInstanceOf(PieWrapper);
  });
```

### Expected behavior
Simulating a click on avatarImage should update activeAvatarId state in parent component to 1 (via callback function) - which should cause avatar to re-render and return pieWrapper.

Clicking on the actual component in the browser does exactly that.

This is a CRA app.

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by craigkovatch** [comment]
I'm not expressing an opinion on how this *should* work, but what you've described is consistent with the documentation:

http://airbnb.io/enzyme/docs/api/ShallowWrapper/debug.html
http://airbnb.io/enzyme/docs/api/ReactWrapper/debug.html

**Comment by ljharb** [comment]
I'd avoid using `simulate`; it doesn't faithfully simulate anything. Instead, directly invoke a prop function.

**Comment by craigkovatch** [comment]
@ljharb this is a very confusing response. Why does the method exist at all then?

**Comment by ljharb** [comment]
@craigkovatch the method exists because react-test-renderer's shallow renderer had a "simulate" option, at the time enzyme was first created.

It still exists because it wasn't until v2 that it became abundantly clear that it's a terrible method, and it wasn't removed in v3 because we wanted to make the migration to v3 as easy as possible. However, whenever a v4 comes around, it will be removed for certain.
