### ISSUE TITLE
How can I test mapped <Route /> components?

### ISSUE THREAD

**Issue by sintloer** [airbnb/enzyme#1633]
**I have following code...**

Component:

```javascript
import React from "react"
import { Route as RouteComponent } from "react-router-dom"

import type { Route } from "@/types"

export type Props = {
	routes: Array<Route>
}

const Content = ({ routes }: Props) => {
	return routes.map(({ path, component, exact }, i) => {
		return (
			<RouteComponent
				key={i}
				path={path}
				component={component}
				exact={exact}
			/>
		)
	})
}

export default Content
```

Test:

```javascript
import React from "react"
import { shallow } from "enzyme"
import { Route } from "react-router-dom"

import routes from "@/routes"
import Content from "@/containers/Content"

describe("<Content />", () => {
	it("should be render with routes", () => {
		const component = shallow(<Content routes={routes} />)
                // HOW?
	})
})
```

How can I check if Content component return greater than 0 Route components?

I try like this: `expect(component.find(Route).length).toBeGreaterThan(0)`
but this generate error: `Expected value to be greater than:
      0
    Received:
      0`

Why .find(Route).length returns 0?

### Your environment
Parcel Bundler, React, Flow, ESLint, Babel, Jest + Enzyme

#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.2

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
@sintloer did you figure this out?

**Comment by sintloer** [comment]
@ljharb, when I wrote this issue I didn't know Enzyme well. This is not important anymore. Thanks.

**Comment by kevbost** [comment]
@sintloer What was your solution?  Because I'm facing the same problem, and this thread could help be a solution for a lot of people.

Relevant: https://xkcd.com/979/

**Comment by webberwang** [comment]
> @ljharb, when I wrote this issue I didn't know Enzyme well. This is not important anymore. Thanks.

Would be great if you could share you findings, thanks.

**Comment by annaloukianova** [comment]
I have a similar problem.

Component:
```
     <div data-classid="app-routes">
          <ErrorBoundary>
            <Switch>
              {
                  routes.map((child) => {
                    return (
                      <Route key={child.to} path={`${match.path}/${child.to}`} component={child.component} />
                    );
                  })
                }
            </Switch>
          </ErrorBoundary>
        </div>
```

.debug() output:
```
  <div data-classid="app-routes">
    <ErrorBoundary>
      <Switch />
    </ErrorBoundary>
  </div>
```

Any ideas on what to try or how to debug? I have verified that `routes` are not empty, test has a valid `MemoryRouter` with `initialEntries`. I know this is an old, closed issue but this is the only thing that comes up remotely close when searching.

**Comment by ljharb** [comment]
@annaloukianova that should work fine if you're sure that `routes` isn't empty in the test. Please file a new issue with full component and test code and I'll take a look.
