### ISSUE TITLE
add a parameter to prettify html output

### ISSUE THREAD

**Issue by capaj** [airbnb/enzyme#1634]
I very often use `html()` to make a string that I pass to jest snapshoting method. Problem is I always need to import `pretty` package and wrap it in that because it just dumps the html on a single line. It would be helpful if I could jsut pass a true argument which would make the output span multiple lines. Is that something you'd be willing to merge if I made a PR?

this:
![image](https://user-images.githubusercontent.com/1305378/39421606-0cac2bee-4c6a-11e8-8f33-4a6ec35e9540.png)

instead of:
![image](https://user-images.githubusercontent.com/1305378/39421622-210d17c4-4c6a-11e8-8e90-ea6a69505ee2.png)

Surely I could make my own `toMatchPrettySnapshot` test util function, but this issue will be prevalent in all testing libraries and frameworks, so if I'd have a project with ava instead of jest I'd just have to create another util.

**Comment by ljharb** [comment]
I'd recommend using `.debug()` instead of `.html()` here, for a number of reasons.

**Comment by ljharb** [comment]
I'm going to close, but am happy to reopen if there's still a feature you need.

**Comment by carloscuesta** [comment]
Debug is not meant to be used on snapshot testing @ljharb

**Comment by ljharb** [comment]
@carloscuesta that's true, but if you insist on doing (brittle, discouraged) snapshot testing, `.debug()` is the closest reliable thing enzyme provides for it.
