### ISSUE TITLE
ReactWrapper.setProps swallows render errors

### ISSUE THREAD

**Issue by psfrankie** [airbnb/enzyme#164]
`this.component.setChildProps` in the method below returns a promise.  If there is a render error due to un-renderable props being passed into `setProps()`, the promise will reject but will swallow the exception.

```
setProps(props) {
    if (this.root !== this) {
      throw new Error('ReactWrapper::setProps() can only be called on the root');
    }
    this.component.setChildProps(props);
    return this;
  }
```

Example:

Consider the following component:

```
<div>
	{ user.name.givenName }
</div>
```

`mount()` will work with these initial props:

```
{
	user: {
		name: {
			givenName: 'Meghan'
		}
	}
}
```

It will fail silently when the following props are passed to `setProps()`:

```
{
	user: {}
}
```

**Comment by ljharb** [comment]
What do you mean, "will swallow the exception" - if the promise rejects then you need a `.catch` on that promise (which should always be on every promise chain) in order to expose it.

**Comment by lelandrichardson** [comment]
@ljharb in this case, it's enzyme that is not catching the promise and exposing it

**Comment by ljharb** [comment]
aha, that sounds like a bug then :-)

**Comment by lelandrichardson** [comment]
agreed. 

Thanks, @psfrankie - we will fix this. If you feel like submitting a PR with this tweaked, we'd sure appreciate it as well! :)

**Comment by lelandrichardson** [comment]
This has been fixed. Closing.
