### ISSUE TITLE
Enzyme still trigger a render when null is returned from setState

### ISSUE THREAD

**Issue by samouss** [airbnb/enzyme#1643]
### Current behavior

Not sure if it's an issue or a non documented behaviour (or I didn't found it). With `shallow` when we return `null` from an updater function, React prevent the render. But Enzyme don't. 

There is no issue with `mount`.

### Expected behavior

Enzyme should prevent the render when we return `null` from an updater function.

### Your environment

Here is [an example](https://github.com/samouss/enzyme-setstate-null).

#### API

- [x] shallow

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  `^3.3.0`
| React            |  `^16.3.2`

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by koba04** [comment]
Fixed by facebook/react#12756

**Comment by samouss** [comment]
Thanks!
