### ISSUE TITLE
Cannot Access Children

### ISSUE THREAD

**Issue by adamk1230** [airbnb/enzyme#1645]
My goal is to test data within a table.  I am able to find the 'TdComponent' and it's children.  However when I try to access a child the code stops executing.

For Example:
```javascript

console.log(enzymeWrapper.find('TdComponent').children()) // returns ReactWrapper { length: 50 }
console.log(enzymeWrapper.find('TdComponent').childAt(0).text()) // doesn't return anything
console.log("test") // doesnt return anything

```

I've also tried the following:
```javascript

console.log(enzymeWrapper.findWhere(n => n.text() === '20')) //doesn't return anything

console.log(enzymeWrapper.find('TdComponent').findWhere(n => n.text() === '20')) //doesn't return anything

```

Running debug at TdComponent gives the following:

```javascript

console.log(enzymeWrapper.find('TdComponent').children().debug())
/*
<div className="rt-td" role="gridcell" style={{...}} onClick={[Function]}>
      20
    </div>


    <div className="rt-td" role="gridcell" style={{...}} onClick={[Function]}>
      2
    </div>
    ... rest of data omitted
*\
```

Goal is to have a test with the following functionality:
```javascript

expect(enzymeWrapper.find('TdComponent').childAt(0).toBe('20');

```
This is how my test file current looks:
```javascript

import React from "react";
import { shallow, mount } from "enzyme";
import Blocks from "./Blocks";
import ReactTable from 'react-table';

const setup = () => {
  const props = {
    //omitted for brevity
  }

  const enzymeWrapper = mount(<Blocks {...props} />);

  return {
    props,
    enzymeWrapper
  }
};

describe("Blocks", () => {
  test("Blocks and ReactTable components should render", () => {
    const { enzymeWrapper } = setup();
    expect(enzymeWrapper.exists()).toBe(true);
    expect(enzymeWrapper.find(ReactTable).exists()).toBe(true);
  });

    test("Table displays blocks", () => {
      const { enzymeWrapper } = setup();
      console.log("My Logs")
      console.log(enzymeWrapper.find('TdComponent').children())
      console.log(enzymeWrapper.find('TdComponent').childAt(0).text())
      console.log('test')
    })
});
```

I'm fairly new to Unit Testing so perhaps my approach is not the best or incorrect.  Any guidance is much appreciated. 

### Current behavior

Nothing happens and the following code doesn't execute.

### Expected behavior

To console.log what .text() returns.

### Your environment
node 8.11.1
create-react-app

#### API

- [ ] shallow
- [ x ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |   16.2.0
| React            |   3.3.0

#### Adapter

- [ x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by adamk1230** [comment]
I was able to find the data I was looking for by using the following:

```javascript
console.log(enzymeWrapper.find('TdComponent').findWhere(n => n.type() === 'div' && n.contains(/* data */)))
```
I would still like to be able to correctly select the table cells.

**Comment by ljharb** [comment]
Happy to reopen with more information.
