### ISSUE TITLE
dependencies require a json-loader (webpack)

### ISSUE THREAD

**Issue by romnempire** [airbnb/enzyme#1650]
**Describe the bug**
Including enzyme in a webpacked test environment results in the following files throwing an error `Module parse failed: /[redacted]/node_modules/entities/maps/[something].json Unexpected token (1:6)
You may need an appropriate loader to handle this file type.`

This occurs for the following files:

`ERROR in ./~/cheerio/package.json`
`ERROR in ./~/css-select/lib/procedure.json`
`ERROR in ./~/entities/maps/entities.json`

**Expected behavior**
Enzyme ... doesn't depend on the specifics of the build environment to handle its dependencies ?

enzyme 3.3.0

**Additional context**
The solution of adding the json loader is pretty trivial, most of the time.  But, this clashes with a particular of what i'm testing, and in the event this is a wontfix, i'd like to hear an opinion on how you guys would handle this, make sure i'm not missing something:

I want to override the module bundler's json handling, because another one of my tests is testing custom json handling.  I can't do that because enzyme is requiring me to configure my bundler to handle its json.

- passing it through my json handler seems wrong, because it's purpose specific
- writing multiple matching rules to support two json handlers in webpack seems like an uncommon thing to do
- the path of least resistance is to stringify in my json parsing tests and then reparse, which kinda introduces a lot of surface tested.

**Comment by ljharb** [comment]
enzyme is a test framework, so it expects to run in node. By default, node loads JSON. It's just an odd choice that webpack doesn't load JSON by default.

I'm not really sure how we'd handle it - it seems the responsibility of your webpack config to handle.

Can you elaborate on what you're trying to test with parsing JSON, in a browser, where the input content is a json file instead of a string?

**Comment by romnempire** [comment]
In use, the parser would be parsing ajax responses.  Storing the simulated response as js would sidestep the loader issue, and basically test the same stuff.  Yeah.

...It seemed like the cleanest way of representing an json response was a json file, so i didn't really think about changing that :|

Thanks!
