### ISSUE TITLE
Don't see change when setState/setProps is used after wrapper.find

### ISSUE THREAD

**Issue by croraf** [airbnb/enzyme#1662]
I've posted my question here but replies do not solve: https://stackoverflow.com/questions/50513234/enzyme-wrapper-doesnt-change-when-state-props-are-changed

Excerpt from `MyTable.js` component 
```
render () {

  // before return I manipulate this.props at this point and assign some of them to bootstrapTableProps

  return (
    <div>
        <Header />
        <BootstrapTable {bootstrapTableProps}/>
    </div>
  )
}

```
Excerpt from MyTable.spec.js test case:
```
let wrapper = shallow(
  <MyTable
    {...someProps}
  />
);

// change state
wrapper.setState({sortName: 'timestamp', sortOrder: 'asc'});

let bootstrapTableWrapper = wrapper.find('BootstrapTable');
let timestamps = bootstrapTableWrapper.prop('data').map(row => row.timestamp);
expect(timestamps).to.be.ascending; // CORRECT, sorted to be ascending

// change state second time
wrapper.setState({sortName: 'timestamp', sortOrder: 'desc'});

let timestamps = bootstrapTableWrapper.prop('data').map(row => row.timestamp);
expect(timestamps).to.be.descending; // ERROR, still ascending

// recreate the inner wrapper
bootstrapTableWrapper = wrapper.find('BootstrapTable');
let timestamps = bootstrapTableWrapper.prop('data').map(row => row.timestamp);
expect(timestamps).to.be.descending; // CORRECT, descending
```

Check the comments in the code.
So it seams like wrapper.find is creating a deep copy of the found element, and that the subsequnet changing of state or props on the outer wrapper do not affect that copy?

**Comment by ryami333** [comment]
Have you tried doing `wrapper.update()` directly after `wrapper.setState`?

**Comment by croraf** [comment]
I tried now. Does not help. I must again recreate bootstrapTableWrapper with wrapper.find('BootstrapTable') to see the changed state in effect.

**Comment by zhaolc90** [comment]
same issue with 
[getting-started-with-tdd-in-react](https://semaphoreci.com/community/tutorials/getting-started-with-tdd-in-react)
Test 7: Accepting Input
Now, let's wire up the input box to accept changes. Write the test:
```jsx
describe('InputArea', () => {
  ...

  it('should accept input', () => {
    const wrapper = shallow(<InputArea/>);
    const input = wrapper.find('input');
    input.simulate('change', {target: { value: 'Resin' }});
    expect(wrapper.state('text')).to.equal('Resin');
    // expect(input.prop('value')).to.equal('Resin'); // F
    expect(wrapper.find('input').prop('value')).to.equal('Resin');
  });
});
```

**Comment by ljharb** [comment]
@zhaolc90 I'm not clear on what the issue is here. `simulate` does not actually simulate anything, nor cause any changes - it just invokes a prop function.

@croraf can you provide the entire code for the component? it's pretty difficult to help with excerpts.

As for sub-wrappers, in v3 and later, you must *always* re-find from the root to get updates.

**Comment by ljharb** [comment]
It's already mentioned in the v3 migration guide; any time you'd like to file a PR to improve the docs, that'd be appreciated!
