### ISSUE TITLE
Shallow does not find direct child when inside React.Fragment

### ISSUE THREAD

**Issue by sepo27** [airbnb/enzyme#1664]
**Describe the bug**
Shallow should find direct child when inside React.Fragment.
(At least it does so for indirect descendants).

**To Reproduce**
```javascript
import * as React from 'react';
import {shallow} from 'enzyme';

const MyCom = () => (
  <div className="container">
    <React.Fragment>
      <span>A span</span>
    </React.Fragment>
  </div>
);

describe('enzyme shallow', () => {
  it('test#1: should find descendant span inside fragment ', () => {
    const myCom = shallow(<MyCom />);
    expect(myCom.find('.container span')).toHaveLength(1);
  });

  // TEST FAILS
  it('test#2: should find direct child span inside fragment', () => {
    const myCom = shallow(<MyCom />);
    expect(myCom.find('.container > span')).toHaveLength(1);
  });
});

```

**Expected behavior**
Expect `test#2` to pass.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS GNOME 
 - Browser: X
 - Version: X

**Additional context**
Tests are failing inside Jest.

**Comment by mykhailo-riabokon** [comment]
Hi @paska27 

There is an open [issue](https://github.com/airbnb/enzyme/issues/1553) issue for React 16 support and as far as I see `React.Fragment` support  is in progress. So, please check for updates.

**Comment by sanketkalawade** [comment]
anybody.. please help me with this issue? (I'm new to enzyme)

**Comment by ljharb** [comment]
@sanketkalawade please file a new issue if you're having trouble; this was fixed over a year ago.
