### ISSUE TITLE
Can't simulate keypress events in a full DOM render (mount)

### ISSUE THREAD

**Issue by fterh** [airbnb/enzyme#1665]
**Describe the bug**
In my render, I included this: `<input id="test" value="foo" />`.

In my test, I wrote this:
```
expect(wrapper.find('#test').props().value).toBe('foo');
wrapper.find('#test').simulate('focus');
wrapper.find('#test').simulate('keyPress', {key: 'l'});
wrapper.find('#test').simulate('keyPress', {key: 'l'});
expect(wrapper.find('#test').props().value).toBe('foo');
```

**Expected behavior**
The test should fail, because the value should have changed.

**Comment by skbolton** [comment]
This is explained in their docs. You can only simulate events with shallow https://github.com/airbnb/enzyme/blob/master/docs/future.md

**Comment by ljharb** [comment]
@fterh `simulate` does not actually faithfully simulate anything; it's just sugar for invoking a prop function.

**Comment by maufarinelli** [comment]
@ljharb if it is just sugar, we should call `.prop('onKeyPress')()` 
but than, we should mock the event and pass it like `.prop('onKeyPress')(event)`?
if so, omg, it is quite painful

**Comment by ljharb** [comment]
Yes, that is exactly what you should do.

**Comment by maufarinelli** [comment]
Alright, let's do it this way. 👍 
However, I thought it was the purpose of `simulate()`, to leverage all of it.

**Comment by ljharb** [comment]
That's what simulate *should* do, but unfortunately doesn't.
