### ISSUE TITLE
How to mock api in jest and enzyme?

### ISSUE THREAD

**Issue by jainvizz** [airbnb/enzyme#1666]
I have already added a post on stackoverflow for the same 

[https://stackoverflow.com/questions/50621873/how-to-mock-api-in-jest-and-enzym](https://stackoverflow.com/questions/50621873/how-to-mock-api-in-jest-and-enzym)

I have started writing the test cases for my application and stuck at one place where I need to mock fetch calls to api.

this is my common component (client.jsx) method which I use to make fetch calls

```
static sendJsonRequest(address, action, requestType, jsonData, queryParams, successCallback, errorCallback){

    var finalURL = Client.getServiceURL( address, action, queryParams);

    fetch(finalURL, {
      method: requestType,
      headers: {
        'content-type': 'application/json; charset=utf-8',
        'Authorization': 'Bearer ' + localStorage.getItem("access_token"),
        'pragma': 'no-cache',
        'cache-control': 'no-cache'
      },
      body: String(requestType).toLowerCase() === "get" ? undefined : JSON.stringify(jsonData)
    })
    .then(function(response) {
      if (!response.ok) {
          throw Error(response.statusText);
      }
      return response.json();
    })
    .then(function(jsonObj) {
      successCallback(jsonObj);
    })
    .catch(function(err) {
        errorCallback(err);
    });
}

```

And this is how I use this static method in my components:
 ```
        componentDidMount(){
            this.getPermissions();
        }

        getPermissions(){
            this.setState({
              Permissions_DATA: []
            });
            var permissionData = {userName: "xyz", resourceId : localStorage.getItem("target_resource_id")};
            Client.sendJsonRequest("authData", "getPermData", "POST", permissionData, "", this.handleGetPermissions, this.handleError);
          }

          handleGetPermissions(response){
            ---
          }

          handleError(e) {
             ---
          }
```

As as beginner I want to write test case for mocking this fetch call, but I don't know how to write the test cases for the same, can any one please help me out with this.

I tried googling out this as well, but not able to figured out anything.

**Comment by vikmn** [comment]
@jainvizz have a look at fetch-mock npm package documentation for mocking fetch calls http://www.wheresrhys.co.uk/fetch-mock/quickstart

**Comment by vikmn** [comment]
@jainvizz I dont think it matters if your method is static or not (not sure why you would use the staic keyword anyways in this instance). So for example in the following code if i have a function clientRequest which wraps the fetch call . The fetchMock library provides a fetch implementation which is only available in the browsers.
```
const headers = {
  Accept: "application/json",
  Authorization: token
};

export const clientRequest = (url, header = headers) => fetch(url, { headers: header })
  .then(response => {
    return response.json();
  });

export const getAllCategories = () =>
  clientRequest(`${api}/categories`)
    .then(data => data)
``
My test then looks something like this
```
let fetchMock= require('fetch-mock');
const headers = {
    Accept: "application/json",
    Authorization: "token"
};
describe('calling the api with header', () => {
  fetchMock
  .get('http://google.com', { data: '12345' }, { headers })
  .catch({});
  
  it('returns data for matching url and header', () => {
    clientRequest('http://google.com', headers)
      .then(res => {
        expect(res.data).toBe('12345');
      });
  });
```

**Comment by jainvizz** [comment]
@vikmn if you will see the above code which I have provided, I am not returning any promise object from my fetch call instead it's calling the callback functions passed as arguments, in case of success and error. 

```
.then(function(jsonObj) {
      successCallback(jsonObj);
    })
    .catch(function(err) {
        errorCallback(err);
    });
```
Because of this I am not getting how to write the test case. I can't change this function as well.

**Comment by ljharb** [comment]
@jainvizz since sendJSONRequest calls fetch, fetch-mock should work for you.

Separately, you could (and probably should) make your static method return the promise - then you can both unit-test it, and safely mock it out for the rest of your component.
