### ISSUE TITLE
describeWithDOM -- document is not defined

### ISSUE THREAD

**Issue by caalberts** [airbnb/enzyme#167]
I'm running a test with `describeWithDOM`, and the component I'm testing uses a component npm package  `react-youtube` which looks for document.head. How can I resolve this? 

```
var head = document.head || document.getElementsByTagName('head')[0]
             ^

ReferenceError: document is not defined
```

**Comment by zellwk** [comment]
+1. Having the same problem too.

**Comment by lelandrichardson** [comment]
@caalberts @zellwk You should load the jsdom document at the beginning of your test suite, before any other modules are required (including react and react-youtube).  At this point everything should work... and you should not need to use `describeWithDOM` at all.

Also FYI, `describeWithDOM` will be going away soon, and we will no longer be recommending its usage.

**Comment by caalberts** [comment]
@zellwk requiring this at the beginning of each file seems to help.

`setup.js`
```
import jsdom from 'jsdom'

const doc = jsdom.jsdom('<!doctype html><html><body></body></html>')
const win = doc.defaultView

global.document = doc
global.window = win

propagateToGlobal(win)

function propagateToGlobal (window) {
  for (let key in window) {
    if (!window.hasOwnProperty(key)) continue
    if (key in global) continue

    global[key] = window[key]
  }
}
```

**Comment by zellwk** [comment]
Awesome. Thanks @lelandrichardson, @caalberts

**Comment by lelandrichardson** [comment]
Closing. This information is now contained in our guides: http://airbnb.io/enzyme/docs/guides.html
