### ISSUE TITLE
Question: How to debug shallow matchesElement?

### ISSUE THREAD

**Issue by wKich** [airbnb/enzyme#1671]
For example. I have component
```jsx
class Foo extends React.Component {
  render() {
    return (
      <div>
        {this.props.words.map(word => <span key={word}>{word}</span>)}
        <span>{'Whatever'}</span>
      </div>
    )
  }
}
```

And I want to test it, so I write test something like this:
```jsx
const wrapper = shallow(<Foo words={['Hello']} />)

expect(
  wrapper.matchesElement(
    <div>
      <span>{'Hello'}</span>
      <span>{'Whatever'}</span>
    </div>,
  ),
).to.be.equal(true)
```

But, I got the error `AssertionError: expected false to equal true`
So I decide to add `console.log(wrapper.debug())` in my test to see what's wrong, and I got the following output:
```
<div>
  <span>
    Hello
  </span>
  <span>
    Whatever
  </span>
</div>
```
I don't understand why my test is failing. I try to read the docs, experimenting with test/component, but nothing help at all. But after several hours to figure out, I found solution, what test should be 
```jsx
const wrapper = shallow(<Foo words={['Hello']} />)

expect(
  wrapper.matchesElement(
    <div>
      {[<span key>{'Hello'}</span>]}
      <span>{'Whatever'}</span>
    </div>,
  ),
).to.be.equal(true)
```

How to ease debug such cases?

**Comment by mykhailo-riabokon** [comment]
Hi @wKich 

It's a bit tricky case as `matchesElement` matches based on the matching of the node's children as well (from [doc](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/matchesElement.md#common-gotchas)). And in you case one of the child nodes is an array of items so you have to match it in such way.

`.debug()` is a simple and common way to get a `string` output of your wrapper and usually it helps.

To debug your case you might use `wrapper.get(0)` which returns first node (`<div>`) and as you can see from `children` prop, first child as an Array which is your list.

<img width="506" alt="screen shot 2018-06-08 at 16 27 57" src="https://user-images.githubusercontent.com/10687640/41161170-89d2e204-6b3a-11e8-9339-f115a5b92f1e.png">

Overall if you want to test some HTML output it's better to use [.html()](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/html.md) instead. And, if you consider `jest` as a test runner it has [snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html#snapshot-testing-with-jest) which is much more maintainable and simple way to test such kind of things.

**Comment by wKich** [comment]
@mykhailo-riabokon thank you to explanation. Looks like snapshot testing is that I need.

**Comment by ljharb** [comment]
I definitely do not recommend snapshot testing; as that’s very brittle.

I’d recommend explicitly testing for the presence of the elements you need.
