### ISSUE TITLE
.find('.css-selector') returns empty ShallowWrapper.

### ISSUE THREAD

**Issue by arkadyt** [airbnb/enzyme#1673]
**Describe the bug**
.find() returns empty ShallowWrapper when searching by CSS selector.

**To Reproduce**
```
[*.test.js]
// ...all required imports

configure({ adapter: new Adapter() });
const wrapper = shallow((
    <div className='.klas'></div>
));

it('has a class', () => {
    // search by tag works, test succeeds
    expect(wrapper.find('div').props().className.indexOf('.klas') >= 0).toEqual(true);

    // search by css selector does not, test fails
    expect(wrapper.find('.klas')).toHaveLength(1);    
});
```

**Expected behavior**
Upon the .find() call, get ShallowWrapper containing the node which has the CSS selector passed as the argument.

**Workaround**
`wrapper.find('div[className=".klas"]')` or
`wrapper.find({ className: '.klas' })`

**Software**
```
enzyme@3.3.0
enzyme-adapter-react-16@1.1.1
enzyme-adapter-utils@1.3.0
jest@20.0.4
react-reconciler@0.7.0
react-test-renderer@16.4.0
react-is@16.4.0
react@16.4.0
react-dom@16.4.0
react-scripts@1.1.4
```
NodeJS v6.11.4
OS: Ubuntu 17.10

**Comment by arkadyt** [comment]
Also just found out:
```
// returns false
console.log(wrapper.find('div').hasClass('sample'));

// returns true with the warning to avoid using css selector
console.log(wrapper.find('div').hasClass('.sample')); 
```

**Comment by hthuong09** [comment]
`wrapper.find('.sample')` means looking for node which has `sample` class, not `.sample`.
Try `wrapper.find('.\\.sample')` (haven't tested).

**Comment by arkadyt** [comment]
Didn't work! :(

<img width="327" alt="screenshot_20180606_185949" src="https://user-images.githubusercontent.com/23281304/41074223-d3f8777a-69bb-11e8-8ebc-1c99b2379fe7.png">

**Comment by arkadyt** [comment]
> wrapper.find('.sample') means looking for node which has sample class
Yeah, right, that's what I am saying, 
Expected behaviour is to get a node containing specified css selector, but find() returns empty wrapper with the length of zero.

**Comment by arkadyt** [comment]
Found workaround:
`wrapper.find('div[className=".klas"]')` or
`wrapper.find({ className: '.klas' })`.
But still, [documentation](http://airbnb.io/enzyme/docs/api/ShallowWrapper/find.html) is then misleading.

**Comment by arkadyt** [comment]
That was the dumbest mistake.
const wrapper = shallow((
    <div className='.klas'></div> // Class name should not start with a dot.
));
I have to go back to learning basics :D.

**Comment by rrawat-dev** [comment]
Just to add, found similar issue if we accidentally/incorrectly use class instead of className in JSX:
// incorrect
const wrapper = shallow((
    <div class="klas"></div> // Class name should not start with a dot.
));

// correct
const wrapper = shallow((
    <div className="klas"></div> // Class name should not start with a dot.
));
