### ISSUE TITLE
getDerivedStateFromProps state argument is previous state on setState

### ISSUE THREAD

**Issue by adamnoakes** [airbnb/enzyme#1676]
Not sure if this is a bug with enzyme or react
**Describe the bug**
When calling `setState`, since react 16.4.0 `getDerivedStateFromProps` is called. When running our app the state argument includes the values that has just been set, however when running through enzyme the state argument includes the values before the state has been set.

**To Reproduce**
```
state = {
    someKey: 'someValue'
}

setState({ 
    someKey: 'newValue'
});

getDerivedStateFromProps(props, state) {
    console.log(state.someKey) // 'someValue'
}
```

**Expected behavior**
```
getDerivedStateFromProps(props, state) {
    console.log(state.someKey) // 'newValue'
}
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS ]
 - Browser [chrome]
 - Version [10.13.4]

**Comment by fatfisz** [comment]
It seems to be a problem with react-test-renderer, I created an issue in React's repo: https://github.com/facebook/react/issues/13027.

**Comment by adamnoakes** [comment]
Cool, I see you've got a PR merged so i'll close this issue - thanks!
