### ISSUE TITLE
Nested stateless component not found

### ISSUE THREAD

**Issue by lijunray** [airbnb/enzyme#1678]
#**Describe the bug**
Let's say I have a class component like below:
```javascript
class Parent extends React.Component {
    render() {
        return <div><Child /></div>;
    }
}

export default Parent;
```
and `Child`:
```javascript
const Child = props => <div>child!</div>;

export default Child;
```
Testing code:
```javascript
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-15.4';
Enzyme.configure({ adapter: new Adapter() });

describe('test', () => {
    it('tests', () => {
        const parent = Enzyme.mount(<Parent />);
    });
});
```
It throws an error:
```javascript
Invariant Violation: Child(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```
It can be traced to the line of `Enzyme.mount()`;
I did a lot of search online with keyword "stateless component" but only found some issue reports about testing stateless component instead of testing component with stateless component nested.
Maybe I'm doing something wrong, given my actual component is much complex and this should be a common situation. 
I tried Enzyme 2.7.1 and 3.3.0, both with react 15.3.2 and enzyme adapter 1.0.5.
Any advice is appreciated!

**Comment by ljharb** [comment]
Can you provide the *full* files for Parent and Child, including imports?
