### ISSUE TITLE
Error when passing imported package in constructor

### ISSUE THREAD

**Issue by KostyaErsak** [airbnb/enzyme#1679]
Hi, everyone
I testing container using Enzyme, Jest and Chai. 

Here is my code:
```
import axios from 'axios';

export class Ingredient extends Component {
    constructor(props) {
        super(props);
        const CancelToken = axios.CancelToken;
        const source = CancelToken.source();
        // const source = {}; //Only for Testing
        this.state = {
            CancelToken: source
        };
    }
}
```
And test code:

```
import 'jsdom-global/register';
import React from 'react';
import {configure, shallow} from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import {expect} from 'chai';

import Spinner from '../../../../components/UI/Spinner/Spinner';

configure({adapter: new Adapter()});

describe('Ingredients', ()=>{
    let wrapper;
    beforeEach(()=>{
        wrapper = shallow(<Ingredient onRefreshTimer={()=>null}/>,
           {context: {translate: ()=>null}});
    });
    it('should render Spinner if no props.ings', ()=>{
        expect(wrapper.find(Spinner)).to.have.length(1);
    });
});
```
When I  run the test i got error: 
`TypeError: Cannot read property 'source' of undefined.`
If i change _const source = {}_ it works. Why 'axios' not available in constructor?

**Comment by KostyaErsak** [comment]
Yes, error in line `CancelToken.source()`. In dev/prod its work fine.

**Comment by ljharb** [comment]
How do you run your tests?

**Comment by KostyaErsak** [comment]
`npm run test`

**Comment by ljharb** [comment]
lol yes but what command does that run. what test runner are you using? do you have a setup file? what babel/webpack/etc settings are you using?

**Comment by KostyaErsak** [comment]
`react-scripts test` this script executed when i run `test` command. Apparently Jest is used.

**Comment by KostyaErsak** [comment]
Or maybe trouble with shallow rendering. How i can define where is bug?

**Comment by ljharb** [comment]
I’d console.log axios and axios.CancelToken in your test - it seems like that’s what’s not loading correctly in jest (outside of enzyme)
