### ISSUE TITLE
Non-dev dependencies?

### ISSUE THREAD

**Issue by milesj** [airbnb/enzyme#168]
Is there a reason why `mocha-jsdom`, `sinon`, `jsdom`, etc, is a dependency and not a dev dependency? Yet `mocha` itself is a dev dependency? 

Furthermore, why are there non-dev dependencies to begin with? Enzyme is for running tests in dev. Just seems counter-intuitive to have it setup this way. I also believe this is causing unmet dependencies when running `npm install` or `npm update`.

**Comment by ljharb** [comment]
@milesj devDependencies are for developing *this module*. dependencies are things this module needs to work.

**Comment by ljharb** [comment]
For example, mocha is a dev dep because it's for running enzyme's own tests. mocha-jsdom is used as part of enzyme's actual functionality.

This is all working as intended, and `npm install` works just fine. If you have a specific unmet dependency issue I'd love to see the output so we can fix it!

**Comment by milesj** [comment]
I know full well how dependencies work. Why is `mocha-jsdom` a dependency when it definitely is not required, as I can run tests without mocha? That's the issue.

```
npm WARN mocha-jsdom@1.0.0 requires a peer of mocha@* but none was installed.
```

But after looking at the source, it was moved to optional. https://github.com/airbnb/enzyme/blob/master/package.json#L82 Yet the one I just downloaded has it under dependencies and I'm using `~1.5`. Maybe NPM is out of date? Or we need a minor bump?

**Comment by ljharb** [comment]
v2.0 will be removing all of the test-framework-specific packages, like sinon, jsdom, mocha-jsdom, etc. In its initial release, enzyme was primarily used with mocha, although it certainly works with other testing frameworks. In v2, it will be very clearly usable with other frameworks, and will not include extra dev dependencies.
