### ISSUE TITLE
`text()` incorrectly returns an empty string on text nodes mades of a single interpolated zero number

### ISSUE THREAD

**Issue by tdd** [airbnb/enzyme#1686]
When a wrapper node represents a text node whose content was obtained by `{0}`, its `text()` method incorrectly returns an empty string. This reeks of boolean-equivalence over the underlying text.

**To Reproduce**

1. Go to https://codesandbox.io/s/3vrwoojn51
2. Click on the console tab at the bottom
3. See how the first `text()` call returns an empty string, whilst the second one does not.

**Expected behavior**

Both `text()` calls should return `"0"`

**Additional context**

- React 16.4.1
- React-DOM 16.4.1
- Enzyme 3.3.0 with React 16 Adapter v1.1.1

**Comment by ljharb** [comment]
@tdd thanks for the post! I'm unable to reproduce this locally, and your sandbox doesn't work because of `util.inspect`.

**Comment by ljharb** [comment]
I've added some test cases to master that are passing; I'm going to close this, but am happy to reopen if I can repro the bug.

**Comment by tdd** [comment]
@ljharb wth with the codesandbox? It worked fine when I authored it, now it breaks. No idea why, I seem to be on the latest versions…

**Comment by ljharb** [comment]
Not sure :-/ maybe object-inspect updated, and code-sandbox isn’t using a bundler that shims util?

Can you still reproduce this issue with the zero?
