### ISSUE TITLE
How to test ConnectedComponent internal methods when using 'mount' ?

### ISSUE THREAD

**Issue by abharadiya** [airbnb/enzyme#1688]
In a use case, I have to mount connected component like this
```
const wrapper = mount(<Provider store={store}><ConnectedEditor {...props}/></Provider>);
```
This connected component has one method like
```
_renderSpinner = () => {
	console.log('rendering spinner...');
}
```
How do I test that method?

**Comment by ljharb** [comment]
Never put arrow functions in class fields - instead, use a normal instance method, and bind it in the constructor if needed.

Once that's fixed, you'll be able to unit-test it by spying on `ConnectedEditor.prototype.renderSpinner` (if ConnectedEditor isn't wrapped by `connect()`).

If it is wrapped (as the name implies), then you can only test it by either a) exporting the inner component just for tests (but you don't want to do this), or b) exercise whatever code path invokes it, and test for its behavior.
