### ISSUE TITLE
How to test debounce method

### ISSUE THREAD

**Issue by cxucheng** [airbnb/enzyme#1699]
Hey guys, I want to test a debounce method, code is similar to the following structure:

```
class SomeComponent extends React.Component {
    constructor(props) {
        super(props);
        this.fetchSth =  _.debounce(this.fetchSth, 500).bind(this);
        this.fetchSthElse = this.fetchSth.bind(this);
    }
    
    fetchSth() {
        return postJson(endpoint, { a: 2}) // the endpoint returns { total: 2 }
            .then((response) => {
                setState({ total: response.total});
            );
    }

    fetchSthElse() {
        return postJson(endpoint, { a: 2}) // the endpoint returns { total: 2 }
            .then((response) => {
                setState({ total: response.total});
            );
    }
```
In my unit test, I use fetch-mock to mock my postJson call and I was able to retrieve the promise from ```fetchSthElse()```. However, I can't get the promise from ```fetchSth()```, it is always undefined for me. The code for unit test is:
```
    const props  = { b: 2 };
    wrapper = shallow(<SomeComponent {...props} />);
    instance = wrapper.instance();
    const promiseFetchSth = instance.fetchSth();
    promiseFetchSth.then(() => {  // promiseFetchSth is always undefined
        assert.strictEqual(wrapper.state("total"), 2);
    });

    const promiseFetchSthElse = instance.fetchSthElse();
    promiseFetchSthElse.then(() => { 
        assert.strictEqual(wrapper.state("total"), 2);
    })
```
You can assume all my dependencies are the latest and I am using ubuntu 16.

I wonder how to test a debounce function that returns a promise. Any idea would be very helpful :)

I remove the elipsis in the code, which I think should be sufficient :), plz let me know if there is anything needed

**Comment by ljharb** [comment]
It's pretty difficult to help with all the elided code. Could you provide the entire component and test code?
