### ISSUE TITLE
Version number does not seem up to date.

### ISSUE THREAD

**Issue by jcandeli** [airbnb/enzyme#1702]
**Describe the bug**
Installing version 1.1.1 does not yield the same code that is shown in the current master branch for 1.1.1. More specifically it's missing the new React Context Api types. I am getting this error "Enzyme Internal Error: unknown node with tag 13" even though that bug was fixed in February. 
https://github.com/airbnb/enzyme/commit/e21b7b506ae2cc8aff8cac233564e74a605291b2#diff-359ceaf4dec809e15a7f54fb0e2c2f42R32

**To Reproduce**
1. npm install enzyme-adapter-react-16
2. go to node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js or node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js
3. search for `ContextProvider`
4. it is not found.

**Expected behavior**
Should be able to mount a component that uses React Context API in jest without getting the error 
`Enzyme Internal Error: unknown node with tag 13`
When I manually edit the file node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js and add the ContextConsumer and ContextProvider types, the error goes away.

**Screenshots**
node_modules/enzyme-adapter-react-16/package.json 
![screen shot 2018-07-03 at 11 46 09 am](https://user-images.githubusercontent.com/1228521/42238744-ba0969fe-7eb6-11e8-8950-b7cbb5e3dd27.png)

node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js 
![screen shot 2018-07-03 at 11 45 54 am](https://user-images.githubusercontent.com/1228521/42238746-bb674924-7eb6-11e8-8553-64883a8626e3.png)

**Desktop (please complete the following information):**
 - OS: OSx High Sierra
 - Browser N/A
 - Version N/A

Other useful information:
    "react": "^16.4.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "jest": "^22.4.0",

**Comment by ljharb** [comment]
This is often the case for every repo - there’s unreleased code on master. This is normal, and expected. The issue you’re reporting will be fixed in the next release.

If you want to see the code for a specific version, visit its git tag.

**Comment by parkedwards** [comment]
Looks like these commits were made after the last known pkg publish:

https://github.com/airbnb/enzyme/commit/e21b7b506ae2cc8aff8cac233564e74a605291b2#diff-359ceaf4dec809e15a7f54fb0e2c2f42
https://github.com/airbnb/enzyme/commit/81167fb4a4f5dfc6324f6154662eaa9656e6e048#diff-359ceaf4dec809e15a7f54fb0e2c2f42


npm registry:
https://www.npmjs.com/package/enzyme-adapter-react-16
![image](https://user-images.githubusercontent.com/19556538/42239031-8e64de90-7eb7-11e8-9bf0-21e625ad7a93.png)

**Comment by jcandeli** [comment]
Yes I understand that some code may not be released yet but the issue I am reporting has actually already been fixed in February as @parkedwards pointed out above. Just curious how much longer it will take to release it? It seems like something that can be done in a few minutes.

**Comment by jcandeli** [comment]
@ljharb I still think there is clearly a mistake here. I looked up version 1.1.1 by tag like you suggested and looked at the commits in it and there is clearly one for the issue I am talking about. 
https://github.com/airbnb/enzyme/compare/enzyme-adapter-react-16@1.1.1...master

Commit: https://github.com/airbnb/enzyme/commit/e21b7b506ae2cc8aff8cac233564e74a605291b2

I am still confused why I can't see that code *which is part of tag 1.1.1* in the the src when I install your package?

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)
