### ISSUE TITLE
Lack of recent NPM package updates

### ISSUE THREAD

**Issue by dupski** [airbnb/enzyme#1705]
**Describe the bug**
Enzyme has not been published to NPM for over 6 months

**To Reproduce**
https://www.npmjs.com/package/enzyme
https://www.npmjs.com/package/enzyme-adapter-react-16

**Expected behavior**
There have been some important fixes merged in, such as the fix to support React 16.3 context API:
https://github.com/airbnb/enzyme/pull/1513 , which I (and I'm sure others) need to use.

Please can a new version of Enzyme + the React 16 adapter be published?

I realise AirBnB are moving away from React Native, which I guess could be the reason for lack of updates. If that is the case, can access be given to others in the community to publish new versions?

**Comment by ljharb** [comment]
Airbnb's choices around React Native are utterly unrelated; it's simply that we aren't yet ready to publish updates.

I'm not going to publish any further updates to any part of enzyme that have partial support for React 16 features, as that will just result in a flood of new bug reports, all of which would distract from completing support for React 16's features.

It's being worked on; you'll need to be patient.

**Comment by dupski** [comment]
Ok sweet as - good news :)

**Comment by FezVrasta** [comment]
No cache to at least get a pre-release? That would be so helpful to start experimenting with it and have an initial React 16.2+ support

**Comment by ljharb** [comment]
@FezVrasta the work required to make a prerelease is basically identical to the work required to make a real one.

**Comment by dupski** [comment]
For anyone that wants to give the standard [react-test-renderer](https://reactjs.org/docs/test-renderer.html) a try, to get around this problem, I've just written up a medium article with some learnings on how to get started with it (the docs aren't that great!):

https://medium.com/@dupski/d9c65d689e88

**Comment by ljharb** [comment]
The release will be as soon as possible; hopefully this or next month. I’d discourage migrating your tests to use the same APIs that motivated the creation of enzyme in the first place.

**Comment by dupski** [comment]
I'd be interested in reading about the motivations for Enzyme (I've just always used it). Is there a write-up somewhere?

The test renderer seems to be incredibly fast, although could just be my new MacBook :)

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)
