### ISSUE TITLE
Can't find a styled component when use as constructor

### ISSUE THREAD

**Issue by jeremenichelli** [airbnb/enzyme#1713]
**Describe the bug**
When a _styled-component_ is used as base for another component, `enzyme` doesn't find the inner component when when it's rendered.

**To Reproduce**

Given this component in a reduced case:

```jsx
import innerComponent from './innerComponent'

const wrappingComponent = styled(innerComponent)``

class TestComponent extends React.Component {
  render() {
     <div>
         <WrappingComponent>
              {this.props.title}
         </WrappingComponent>
     </div>
  }
}
```

Then on the test:

```jsx
const enzymeSample = enzime.shallow(<TestComponent title={title} />)
enzymeSample.find(IconV2).length
// -> 0
```

The `length` is `0` when it should be `1`.

I'm submitting this here and not in other tooling because when using `react-test-renderer` this happens:

```jsx
const sample = TestRenderer.create(<Tag title={title} />)
sample.root.findAllByType(IconV2).length
// -> 1
```

Which is correct.

**Expected behavior**
Inner children for styled components are found and reported on shallow's length.

**Comment by jeremenichelli** [comment]
Closing it since replacing `shallow` with `mount` solves it. I think that the documentation is nice, but might need some gardening to understand better these combinations before hand.

**Comment by ljharb** [comment]
There’s no Iconv2 being rendered by TestComponent though - it renders a WrappingComponent only. Shallow rendering is shallow.
