### ISSUE TITLE
Where to configure the adpater?

### ISSUE THREAD

**Issue by joetidee** [airbnb/enzyme#1715]
In the docs you have this line:

```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

Is this done in every test file that uses enzyme, or somewhere central in my application that detects the dev environment?

**Comment by ljharb** [comment]
That really depends on your choice of test framework - most offer some kind of “setup” or “harness” file that they’ll run for you; otherwise, you’d have to do that setup in every test file (requiring/importing a common harness file).

**Comment by joetidee** [comment]
So for Jest, this would be in the `jest.config.js` file?

**Comment by ljharb** [comment]
For jest, the option is called `setupTestFrameworkScriptFile`
