### ISSUE TITLE
Can another version of enzyme-adapter-react-16 be released soon?

### ISSUE THREAD

**Issue by chris-peerman** [airbnb/enzyme#1723]
**Is your feature request related to a problem? Please describe.**
My project is using the createContext API however the current version of enzyme-adapter-react-16 (version 1.1.1) released back in December doesn't support the createContext API, so I get the error `Enzyme Internal Error: unknown node with tag 13`. The current version on master seems to work fine. Also found it a bit odd that there has been a release of adapter 13, 14, 15 and 15.4 recently but not of 16 yet.

**Describe the solution you'd like**
Make another release of enzyme-adapter-react-16 soon.

**Describe alternatives you've considered**
Temporarily checked out the master branch of enzyme, copied the enzyme-adapter-react-16 to our project and wired it up.

**Additional context**
None

**Comment by ljharb** [comment]
Can it be released soon? Yes, as soon as it's ready.

We're likely going to need to split it up into multiple adapters - like how React 15.0-15.4 has a different adapter than ^15.5 - and figuring out those details is tricky.
