### ISSUE TITLE
License file missing in npm package 

### ISSUE THREAD

**Issue by char0n** [airbnb/enzyme#1729]
Hello, is it possible to incorporate the LICENSE file inside the npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it.

Thank you

**Comment by ljharb** [comment]
Which package? This repo has 10.

Personally I think that the SPDX field in package.json is more than sufficient, but I suppose we can include the license file. Either way, nobody distributes enzyme - so the lack of a license file shouldn't actually impact anyone's ability to use it.

**Comment by char0n** [comment]
Hi,

Sorry for not being specific enough.

> Which package? This repo has 10.

enzyme-adapter-utils

> Personally I think that the SPDX field in package.json is more than sufficient, but I suppose we can include the license file. Either way, nobody distributes enzyme - so the lack of a license file shouldn't actually impact anyone's ability to use it.

The thing is that you distribute the code with npm and this code is not accompanied by the full license text. That is a real problem in legal perspective. Even though we're not distributing it, we cannot use it becase we're just missing a license.

**Comment by ljharb** [comment]
That would be an issue for *npm*, sure, but it's not a legal issue for someone who consumes the package and does not redistribute it. Certainly your lawyers might be paranoid, but there's zero legal obstacle for you if you're not redistributing the package.

At any rate, the next time any of these packages is published, they'll have the license file included.

**Comment by dcousens** [comment]
Another example is https://github.com/kach/nearley/issues/396

enzyme/package.json:51:    "rst-selector-parser": "^2.2.3"
rst-selector-parser/package.json:42:    "nearley": "^2.7.10"
nearley/package.json:41:    "nomnom": "~1.6.2",

---

IANAL, but @ljharb don't you need a LICENSE for permission to use?  Not merely distribute?
