### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by cameronjroe** [airbnb/enzyme#173]
Is there a way to import the jsdom environment before lib imports that depend on `window`? I'm getting window is undefined when running with mocha.

**Comment by gmcquistin** [comment]
yes: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by juanpasolano** [comment]
Hi, 
Is there a way to bypass this...
I'm doing `if(window)` but it still throws the undefined. And I don't want to necessarily add jsdom.

Thanks
