### ISSUE TITLE
`.find` unable to find dynamic nodes

### ISSUE THREAD

**Issue by zheshishei** [airbnb/enzyme#1736]
**Describe the bug**
`mount .find` is unable to find a dynamically created dom node within the tree.

I know this is an edge case since, in the majority of cases, react components render other reacts components all the way down. I just wanted to point this out in case this is something you wanted to support. I came across this when trying to write some tests for `react-codemirror`, which is a react wrapper around a code mirror object.

**To Reproduce**
Here's a test case that showcases the error:
```
import React from 'react';
import { mount } from 'enzyme';

const myClassName = 'my-great-class';

class ComponentWithDynamicChild extends React.Component {
  constructor() {
    super();
    this.container = React.createRef();
  }

  componentDidMount = () => {
    this.container.current.append(`<div class="${myClassName}"></div>`);
  }

  render() {
    return (<div className="container" ref={this.container} />);
  }
}

describe('enzyme dynamic class', function() {
  let mountedComponent;

  it('should find the dynamically inserted div', function() {
    mountedComponent = mount(<ComponentWithDynamicChild />);
    expect(mountedComponent.find(myClassName)).to.have.length(1);
  });
});
```

**Expected behavior**
I  expected `.find` to return a reference to a node? Maybe a stripped down wrapper that has a `text()` method.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 67

**Comment by zheshishei** [comment]
I just found the Common Issues section. Does this issue fall under https://github.com/airbnb/enzyme/blob/master/docs/common-issues.md#testing-third-party-libraries?

**Comment by zheshishei** [comment]
I think it fits, so I'm going to close this issue.

**Comment by ljharb** [comment]
Sounds right to me, unfortunately.
