### ISSUE TITLE
Give error when installing with incompatible react version

### ISSUE THREAD

**Issue by pgangwani** [airbnb/enzyme#1744]
**Describe the bug**
I am using `react@16.2.0 with enzyme-adapter-react-16`, suddenly since last few hours, 50+ passed test cases started failing due to upgrade because of `"enzyme@~3.3.0",
        "enzyme-adapter-react-16@~1.1.1"` in package.json, referred your doc didnt find warning or note but when checked releases, found you guys forked 16.1, 16.2 and so on to have dedicated support.

**To Reproduce**
1. use `enzyme-adapter-react-16` with older version of `react <=16.2`
2.  Passed test cases will suddenly started failing

**Expected behavior**
when trying to install `enzyme-adapter-react-16` with incompatible version of react, throw error in `npm i`

**Comment by ljharb** [comment]
v1 of the 16 adapter will always support all v16.x versions. I'm planning on releasing a v2 that requires v16.4 and up.

However, you should be able to use any of React v16.0, v16.1, v16.2, v16.3, or v16.4 with v1 of the v16 adapter.

Can you share some of the failing tests?

**Comment by pgangwani** [comment]
`import React from 'react';
import { shallow } from 'enzyme';
import { expect } from 'chai';
import FindStoresMapView from './FindStoresMapView';
import StoreMockData from './__stories/mock';

describe('Component:MapWrapper', () => {
    let wrapper;
    beforeEach(() => {
        wrapper = shallow(
            <FindStoresMapView
                stores={StoreMockData.stores}
                center={StoreMockData.stores[0]}
            />,
        );
    });

    it('To check if the MapWrapper component exist', () => {
        expect(wrapper).to.exist;
    });

    it('Simulate click should change stores information', () => {
        wrapper.instance().clickStore({ plot: StoreMockData.stores[1] });
    });

    it('Check if the error message hides on re-render', () => {
        wrapper.setProps({ center: 1, stores: [1, 2] }); // This will call componentWillReceiveProps
        expect(wrapper.state('center')).to.equal(1);
    });
});
`

**Comment by pgangwani** [comment]
Yes it fails with enzyme v3.4 and 16 adapter v1.1.1 , also with enzyme v3.3 and the v1.2.0 adapter.

Need to try with enzyme 3.3 or 3.4 and the 16.2 adapter, do I need to change 
`import Adapter from 'enzyme-adapter-react-16';` statement to ===>16.2 module

**Comment by ljharb** [comment]
Thanks, can you also share the component code?

**Comment by pgangwani** [comment]
Sorry for late. Here you go

`    import PropTypes from 'prop-types';
    import React from 'react';
    import isEmpty from 'lodash/isEmpty';
    import className from 'classnames/bind';
    import List from 'yoda-core-components/lib/components/List/List';
    import MessageBox from 'yoda-core-components/lib/components/MessageBox/MessageBox';
    import Button from 'yoda-core-components/lib/components/Button/Button';
    import config from 'yoda-core-components/lib/components/List/List.config';
    import StoreDetailsCard from '../StoreDetailsCard/StoreDetailsCard';
    import FilterStore from '../FilterStore/FilterStore';
    import StoreLocatorPage from '../StoreLocatorPage/StoreLocatorPage';
    import MultiSelectStore from '../MultiSelectStore/MultiSelectStore';
    import FindAStoreLoader from '../FindAStoreLoader/FindAStoreLoader';
    import * as styles from './FindStoresPageView.css';
    import { findStoreThemes } from '../../../../common/Constants';
    import messages from './errorMessage';

    const cx = className.bind(styles);

    /**
     * This component renders the stores in a list view with store details
     *
     * @param {any} { selectStoreAction, selectActionCallback, productDetails, zipCode, stores }
     */
    function FindStoresPageView(options) {
        const {
            selectStoreAction,
            selectActionCallback,
            productDetails,
            zipCode,
            stores,
            deviceType,
            theme,
            findMoreStores,
            nextPageLink,
            mapView,
            count,
            miles,
            invalidInput,
            userLatLong,
            storeSelectedServices,
            onFilterChange,
            from,
            showLoader,
            defaultStoreId,
            hideDirections,
            appointmentActions,
            selectedSkuId,
        } = options;

        const isFindAStorePage = (theme === findStoreThemes.findAStorePage);
        const isGalleryStore = (theme === findStoreThemes.gallery);
        const storeViewRenderer = (store, index) => {
            const newStore = Object.assign({}, store);
            newStore.displayName = `${index + 1}. ${newStore.name}`;
            return (<StoreDetailsCard
                storeDetails={newStore}
                productDetails={productDetails}
                selectStoreAction={selectStoreAction}
                selectActionCallback={selectActionCallback}
                deviceType={deviceType}
                hideDirections={hideDirections}
                theme={theme}
                userLatLong={userLatLong}
                isDefaultStore={defaultStoreId === store.id}
                from={from}
                appointmentActions={appointmentActions}
                selectedSkuId={selectedSkuId}
            />);
        };

        /**
         * Renders the error message when no stores are having inventory or no stores are found for a zipcode
         */
        const renderMessage = (messageDetails) => {
            const { content } = messageDetails;
            return (
                <div className={cx('messageWrapper')} data-automation-id="at-no-sdpu-stores-msg">
                    <MessageBox
                        {...messageDetails}
                    >
                        {content || ''}
                    </MessageBox>
                </div>
            );
        };

        const onShowMore = () => {
            const payload = {
                nextPageLink,
            };
            findMoreStores(payload);
        };

        const renderViewMoreButton = () => (
            // Show view more button only when there are stores left to display
            <section className={cx('loadMoreContainer', 'row')}>
                <Button
                    buttonType="Primary"
                    type="submit"
                    size="Xl"
                    className={cx('loadMoreButton')}
                    automationId="at-store-list-view-more"
                    onClick={onShowMore}>
                    View more stores
                </Button>
            </section>
        );

        const getServices = isFindAStorePage ? (<FilterStore
            onFilterChange={onFilterChange}
            deviceType={deviceType}
            stores={stores}
            selectedFilters={storeSelectedServices}/>) : null;

        const renderMap = () => {
            const mapWithFilters = cx('mapWithFilters', {
                col6: !mapView,
            });
            const zoomLevel = (stores && stores.length) ? 10 : 3;
            return (
                <div className={mapWithFilters}>
                    {getServices}
                    <div className={styles.mapsWrapper}>
                        <StoreLocatorPage
                            plotPlaces={stores || []}
                            automationId="at-store-map-view"
                            zoom={zoomLevel}
                            userLatLong={userLatLong}
                            />
                    </div>
                </div>
            );
        };

        const renderSelectStoreList = () => {
            const findAStoreLargeView = isFindAStorePage && !deviceType.isMobile;
            const displayTotalStores = (findAStoreLargeView) && miles && zipCode;
            const displayErrorMessage = !showLoader && zipCode && isEmpty(stores);
            const filtersForMobileList = deviceType.isMobile ? getServices : null;
            let errorContext = messages.invalidInput;
            if (!invalidInput) {
                errorContext = messages.noStores;
                /* istanbul ignore if */
                if (!isEmpty(productDetails)) {
                    errorContext = messages.noSDPUStore;
                }
            }
            const contentWrapper = cx('contentWrapper', {
                mobileView: deviceType.isMobile,
            }, theme);
            const listWrapper = cx('listWrapper', {
                col6: isFindAStorePage && !deviceType.isMobile,
            });
            const listBodyClass = cx({
                storeDetailsList: isFindAStorePage,
            });
            return (
                <div className={contentWrapper}>
                    { mapView ? renderMap() : filtersForMobileList }
                    <div className={listWrapper}>
                        {
                            findAStoreLargeView ?
                                <div className={cx('storeMsgWrapper')} data-automation-id="at-store-msg">
                                    <strong>{`${count} stores `}</strong>
                                    {displayTotalStores ? <span>
                                        within
                                        <strong> {`${miles > 50 ? '50+' : miles}mi`} </strong>
                                        of
                                        <strong> {zipCode}</strong>
                                    </span> : null}
                                </div> : null
                        }
                        <div className={styles.storesContent}>
                            {displayErrorMessage ? renderMessage(errorContext) : null}
                            {!displayErrorMessage && isEmpty(stores) ? renderMessage(messages.initialInfo) : null}
                            <List
                                direction={config.direction.VERTICAL}
                                spacing={config.spacing.NONE}
                                itemSpacing={config.spacing.NONE}
                                datasource={stores}
                                childRenderer={storeViewRenderer}
                                listBodyClass={listBodyClass}
                                automationId="at-change-stores-list"
                            />
                            {isEmpty(nextPageLink) ? null : renderViewMoreButton()}
                            {isGalleryStore && stores && stores.length ?
                                <MultiSelectStore selectStoreAction={selectStoreAction}/> : null}
                        </div>
                    </div>
                    { findAStoreLargeView ? renderMap() : null}
                    <FindAStoreLoader />
                </div>
            );
        };

        return renderSelectStoreList();
    }

    FindStoresPageView.propTypes = {
        stores: PropTypes.arrayOf(PropTypes.object).isRequired,
        zipCode: PropTypes.oneOf(PropTypes.string, PropTypes.number),
        selectStoreAction: PropTypes.func.isRequired,
        onFilterChange: PropTypes.func,
        selectActionCallback: PropTypes.func,
        deviceType: PropTypes.objectOf(PropTypes.object),
        hideDirections: PropTypes.bool,
        theme: PropTypes.string,
        mapView: PropTypes.bool,
        from: PropTypes.string.isRequired,
        defaultStoreId: PropTypes.string,
        appointmentActions: PropTypes.func.isRequired,
        selectedSkuId: PropTypes.string,
    };

    FindStoresPageView.defaultProps = {
        zipCode: null,
        selectActionCallback: null,
        deviceType: {},
        hideDirections: false,
        theme: '',
        mapView: false,
        defaultStoreId: null,
        selectedSkuId: '',
    };

    export default FindStoresPageView;
`

**Comment by pgangwani** [comment]
@ljharb :
I dont believe I had created this and found this when I started contributing to airbnb/enzyme.

Closing this as everything is working (though I dont know How did I resolve).

**Comment by ljharb** [comment]
So to confirm, the tests are all passing when using the latest 16 or 16.2 adapter?

**Comment by pgangwani** [comment]
latest 16 adapter

**Comment by ljharb** [comment]
Can you also check the latest 16.2 adapter, since you're on 16.2?

**Comment by pgangwani** [comment]
Now we have upgraded to react 16.8 and everything seems to be working fine
with latest 16 update. Do you still want me to try with 16.2 ?

**Comment by ljharb** [comment]
If it’s not too much trouble :-)
