### ISSUE TITLE
Mount doesn't render a child component

### ISSUE THREAD

**Issue by aslanovsergey** [airbnb/enzyme#1745]
**Describe the bug**
I have a component which I'am trying to test, I wrote some tests successfully but there is one child component in my mounted component which is not rendered completely.

The code for mounted component is quite long so just post only render method.

```
    public render() {
        let detailsList = <div>
            <CommandBar
                items={this._getCommandBarItems()}
                farItems={this._getCommandBarFarItems()}
            />
            <DetailsList
                className="fieldMappingTable"
                compact={true}
                items={this.props.dataTable}
                setKey="set"
                columns={this.state.columns}
                onRenderItemColumn={this._renderItemColumnEditMode}
                onColumnHeaderClick={this._onColumnClick}
                selection={this._selection}
            />
        </div>;

        return (
            <div>
                {this.state.fullScreenMode ?
                    <div>
                        <Panel
                            isOpen={this.state.fullScreenMode}
                            type={PanelType.smallFluid}
                            onDismiss={() => this.setState({ fullScreenMode: false })}
                        >
                            {detailsList}
                        </Panel>
                    </div>
                    :
                    <div>{detailsList}</div>
                }
            </div>
        );
    }
```
The problem is with that `<DetailsList>` component, which is from Office UI Fabric React library 

When I mount its parent component and trying to get this DetailsList I can't find it.

And here is what I see when call debug() on parent component. It's kind of how it should be rendered but there is nothing below that `<div className="ms-Viewport" style={{...}} />`
```
              <WithViewportComponent className="fieldMappingTable" compact={true} items={{...}} setKey="set" columns={{...}} onRenderItemColumn={[Function]} onColumnHeaderClick={[Function]} selection={{...}}>
                <div className="ms-Viewport" style={{...}} />
              </WithViewportComponent>
```

**Expected behavior**
When the component is rendered in browser it works as it should. Here is the screen from React Dev Tools
![image](https://user-images.githubusercontent.com/22150933/43910553-cefb513a-9c05-11e8-9ac5-28ed85cdcd74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 68.0.3440.84

**Comment by ljharb** [comment]
That looks like that component is mutating the DOM directly after mounting - see https://github.com/airbnb/enzyme/blob/d65fc69d87e985fcb51ad5cdc8fdec4933519fe6/docs/common-issues.md#testing-third-party-libraries
