### ISSUE TITLE
update .simulate() docs regarding mock event when shallow or full mounting rendering

### ISSUE THREAD

**Issue by alejo4373** [airbnb/enzyme#1748]
I spent quite a few hours trying to figure out why when shallow rendering a react form my test was failing due to `event.preventDefault` not being defined. When using `.mount()` the error didn't happen.
Can we clarify in the docs that when using `.shallow()` a mock event object must be provided if you are doing anything with the event?.
The function signature says that a mock event is optional `.simulate(event[, mock]) => Self` And nowhere else says that if you need the event for whatever reason you should provide it.

Also can we say that when using `.mount()` a `SyntheticEvent` object gets passed, and that you might need to replace it if your are doing anything with the event. Is the `SyntheticEvent` created by react? or emulated by enzyme? 

Thanks in advance,
I'll be happy to create PR to update these docs.

**Comment by ljharb** [comment]
Sure, that seems like a great improvement.

React creates the synthetic event (which I think is what it does in production react as well)
