### ISSUE TITLE
3.4.x breaks existing test involving returning an array of items

### ISSUE THREAD

**Issue by meganwalker-ibm** [airbnb/enzyme#1749]
**Describe the bug**

Previously, when using 3.3.x  the code and test outlined in the reproduction steps would pass. Now in 3.4.x it does not. It is unclear if this is a case of our code / test being wrong, or if enzyme has accidentally regressed something whilst trying to land React 16 features.

Several of our tests, are failing now, but I've isolated down one of them to the most minimal recreate possible - stripping out all props and ensuring it still acts as we've observed.

**To Reproduce**

Here's a minimal test case for the simplest of the tests that are now failing...
Create a react component like so:
```js
const Minimal = () => {
  return []
}

export default Minimal
```

Create a jest test like so:
```js
describe('Minimal', () => {

  describe('minmal tests', () => {
    it('works', () => {
      const wrapper = shallow(<Minimal />)
      expect(wrapper).toHaveLength(1)
      expect(wrapper.find('div')).toHaveLength(0)
    })
  })
})
```

Test this out against
react@16.4.2
jest@23.5.0
enzyme-adapter-react-16@1.2.0

flipping between enzyme@3.3.0 and enzyme@3.4.1

**Expected behavior**
In 3.3.x, this test case passed. Wrapper had length 1, and wrapper.find(div) had length 0.
In 3.4.x the expect statement `expect(wrapper).toHaveLength(1)` fails with length 0.

**Additional context**

enzyme@3.4.1 (previously 3.4.0)
react@16.4.2
jest@23.5.0
enzyme-adapter-react-16@1.2.0

If  you need any more information, let me know. I can't see anything obviously wrong with our code (the re-create is minimal, but we need to check the logic based on  a large combination of props -> which, for this has boiled down to the recreate above once you strip out the logic).

**Comment by ljharb** [comment]
This was a bug in < 3.4; and components rendering arrays is still not fully supported in enzyme (see #1213).

In this case, a component that returns an empty array is basically identical to one returning null - both don’t actually render anything. It was incorrect for enzyme to ever return a length of 1 there.

**Comment by meganwalker-ibm** [comment]
Ahh, I see. Thanks for clarifying! With that information I've managed to work out why our other cases were broken too. Feel free to close it out :)
