### ISSUE TITLE
how to test component that includes `RouteHandler`

### ISSUE THREAD

**Issue by amcmillan01** [airbnb/enzyme#175]
Is it possible to test a component that includes `RouteHandler`?

```
let SomeComponent = React.createClass({

  contextTypes: {
    router: React.PropTypes.func.isRequired
  },

  getInitialState() {
    return {};
  },

  render () {
    return <div>
      <h2>Some Header</h2>
      <RouteHandler />
    </div>;
  }
});
```

**Comment by ljharb** [comment]
I don't see why not - can you `shallow` render it, and simply assert that it's included?

**Comment by amcmillan01** [comment]
I'm not sure I follow. 

I want to test `SomeComponent ` and set an arbitrary  `RouteHandler` passed in. Is there an example for this?

**Comment by ryanalane** [comment]
@amcmillan01 What aspect are you attempting to test? That SomeComponent contains a RouteHandler child at all? Or that the RouteHandler has specific properties? Or perhaps that SomeComponent fails to render unless it contains a valid RouteHandler?

**Comment by amcmillan01** [comment]
I'm testing application workflow (integration testing). So I ended just using `React`, `react-router`, & `jsdom` for these kind of tests.

**Comment by Aweary** [comment]
@amcmillan01 feel free to share any of the techniques you used to test `RouteHandler`. I'm going to close this for now as it doesn't seem to be an issue with enzyme itself.
