### ISSUE TITLE
Find fails when using a proxy of React Component

### ISSUE THREAD

**Issue by MarcelloVSilva** [airbnb/enzyme#1767]
**Describe the bug**
I need to proxify some components in my app. They are rendering rightly but I'm not able to run tests because enzime method find is throwing the message `Method “simulate” is only meant to be run on a single node. 0 found instead.`

**To Reproduce**

just create and run that simple test

```typescript
import * as React from "react"
import { shallow, configure } from "enzyme"
import * as Adapter from "enzyme-adapter-react-16"

configure({ adapter: new Adapter() })

describe("Test", () => {
    it("Call directly", async () => {
        const r = shallow(<A />)
        r.find("button").simulate("click") // works well
    })
    it("Using fetcher", async () => {
        const r = shallow(<B />)
//        expect(r.html()).toEqual("?")  // HTML is  "<div><button type=\"button\">Btn</button></div>"
        r.find("button").simulate("click") // Method “simulate” is only meant to be run on a single node. 0 found instead.
    })
})

class A extends React.Component {
    public render() {
        return <div>
            <button type="button">
                Btn
            </button>
        </div>
    }
}

const B = createProxy(() => <A />)

function createProxy(Component) {
    // I need to do more things here
    return class extends React.Component {
        public render() {
            return <Component />
        }
    };
}

```

**Expected behavior**
find must return the button element

**Desktop (please complete the following information):**
 - OS: `Linux 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux`
 - node --version `v8.11.3`
- npm --version 6.1.0
-  "enzyme": "^3.4.1",
-  "enzyme-adapter-react-16": "^1.2.0",
-  "react": "^16.4.1",
-  "react-dom": "^16.4.1",
-  "realm": "^2.14.2",

**Comment by ljharb** [comment]
so fwiw, `createProxy` isn't creating a proxy, that's an HOC - ie, it's wrapping your original component in another one. That will be observable to tests - you'll need an additional `.dive()` whenever you use "createProxy". An actual `Proxy` would *replace* - not wrap - the component.

**Comment by ljharb** [comment]
You may find using `.debug()` more helpful than using `.html()` - it will give you a better idea of what's going on.

**Comment by ljharb** [comment]
@MarcelloVSilva are you able to provide more information, such as the code of `createProxy`? if so, i'll be happy to reopen this; otherwise i'll need to close it.
