### ISSUE TITLE
findOne / findOneWhere

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [airbnb/enzyme#177]
Thanks for enzyme! Would you consider adding (or accept a pull request to add) a `findOne` / `findOneWhere` feature for `ShallowWrapper` (that throws if more or less than one element is returned)?

**Comment by lelandrichardson** [comment]
I'd be open to an API addition like this. @ljharb what are your feelings?

For context, the very first iteration of enzyme had `.find()` and `.findAll()` methods, where `.find()` would throw if it found more than one. This API was removed and instead we made enzyme "wrapper"-based, where all of the methods were available whether or not you were wrapping a single element or a collection of elements, but the methods that only made sense to be run on a single element (such as `.props()` would throw if you were wrapping more than a single element.  This is closer to how jquery works and just felt a lot nicer to me.

An alternative to this API would be to have a `.single()` method or something which simply threw an exception if the wrapper was wrapping more than a single element:

```js
wrapper.find('.there-should-only-be-one').single();
```

**Comment by uhoh-itsmaciek** [comment]
Actually, perhaps `single` is a better solution here. I like the JQuery-like behavior, but I don't wan to rely on it in tests, since it's not immediately clear (at least to me--I'm getting reacquainted with JS after a very long hiatus) which methods require a single element, which hampers readability of the tests.

**Comment by ljharb** [comment]
Maybe a more general solution would work here - like `.assertCount(n)` that throws if the count doesn't match `n`, otherwise returns the wrapper?

**Comment by uhoh-itsmaciek** [comment]
For what it's worth, I think I'd end up doing `.assertCount(1)` 99.9% of the time and would prefer `.single()` but I freely admit I lack experience here.

**Comment by ljharb** [comment]
`.single` is certainly more convenient but doesn't seem like an assertion to me :-/

**Comment by uhoh-itsmaciek** [comment]
Fair enough. I'd be fine with any of the above solutions.

**Comment by lelandrichardson** [comment]
Something I feel is worth mentioning here: Nothing is stopping you from adding this as a prototype method yourself right now:

```
import { ReactWrapper } from 'enzyme';

ReactWrapper.prototype.findOne = function findOne(selector) {
  const result = this.find(selector);
  if (result.length !== 1) {
    throw new Error(...);
  }
  return result;
};
```

**Comment by uhoh-itsmaciek** [comment]
Sure, I'm doing something like that now. I just thought it'd be worthwhile to add that as a core feature if it seems useful to others.

**Comment by laggingreflex** [comment]
Came here looking for exactly this but..

>that *throws* if more or less than one element is returned

I think `findOne` should return the **first** node if more than are found, not throw an error. That's how it behaves in Mongodb, and makes most sense.

Anyways, is there a way this could be achieved currently? I.e. get the first node if more than one are found? Like `.find(…)[0]` (doesn't work). Especially I want to get the enzyme node with which I could do other enzyme stuff, like `.find(…).nodes[0].simulate(…)` (doesn't work either)?

**Comment by ljharb** [comment]
@laggingreflex what's your use case for needing only the first node found?

**Comment by laggingreflex** [comment]
Actually nevermind, I missed `.first()` and `.at()` methods. My use case was that there was a bunch of similar nodes, and I just wanted to test if at least one of them existed, and if so perform a `simlulate` on it. Instinctively I thought of `findOne` (not knowing above methods existed) and landed here.

**Comment by uhoh-itsmaciek** [comment]
Thinking about this some more, `enzyme` is probably not the right place for asserting expectations. Given there's not really consensus on what this would look like, I'm going to close the issue to reduce clutter in the repo. A helper is more verbose, but probably the best solution.
