### ISSUE TITLE
Es6 import

### ISSUE THREAD

**Issue by Jaytrindade** [airbnb/enzyme#1770]
Import ("something") does not work but import "something" works. Was wrong?

**Comment by ljharb** [comment]
`import (` is not valid syntax. If you want normal synchronous imports, use `import`; if you want asynchronous imports, use `import(` (no space)

Closing, since this is not enzyme-related.

**Comment by Jaytrindade** [comment]
Okay, I know that. was typos.
the problem remains I do not know why !!!
