### ISSUE TITLE
`props()` returns different properties after upgrading to enzyme-adapter-react-16 or enzyme-adapter-react-16.3

### ISSUE THREAD

**Issue by dagda1** [airbnb/enzyme#1782]
**Describe the bug**

I have this helper function:

```
  isFormValid() {
    // check that every form that has valid set has it set to true
    return _.every(
      this.wrapper
        .find('Form')
        .map(form => {
          console.log('--------------');
          console.dir(form.props());
          console.log('--------------');
          return form.prop('valid');
        })
        .filter(valid => valid != null)
    );
  }
```

When I use `enzyme-adapter-react-16` version 1.1.1 I get the full list of redux-form props including `valid`.

When I upgrade to 1.2.0 or use enzyme-adapter-react-16.3 then there the redux form props are no longer available via `props` or `prop`

**To Reproduce**

upgrade to 1.2.0

**Expected behavior**
I expect to have all the redux-form props available.

**Screenshots**

**Comment by ljharb** [comment]
Can you share the code for `Form`?

**Comment by ljharb** [comment]
@dagda1 ping

**Comment by ljharb** [comment]
I'm going to close this; if you can share the code for `Form`, and the code that creates `this.wrapper`, i'll be happy to reopen it.
