### ISSUE TITLE
Assert state changes in one atomic function

### ISSUE THREAD

**Issue by daggeto** [airbnb/enzyme#1787]
**Is your feature request related to a problem? Please describe.**
Hi, i want to test state changes in some atomic action. 
Will try to explain code in this snippet:
```
class MyCompnent {
...
onImageLoad(file){
  this.setState({loading: true});
  await this.uploadImage(file);
  this.setState({loading: false});
}
...
}

class myComponentTest{
   it('shows and hides loading', async () => {
      ...
      trigger(myComponent, 'onImageLoad');
      // Somehow assert that loading component was rendered and later hidden while onImageLoad was executed
   })
}
```

**Describe the solution you'd like**
I want to to listen to changes on state. Let's say listen to `setState` or `render`. So later i can assert that `loading` was `true` and later changed to `false`.
**Describe alternatives you've considered**
`expect(MyComponent.find(Loading)).toHaveLength(0)` is not actually what will help me, because it will assert only final state after `onImageLoad`. Also, test won't be valid as if i remove `Loading` completely test will still succeed.

**Comment by ljharb** [comment]
Because `onImageLoad` is an `async function`, it's not an atomic function.

Your test would have to have access to the promise returned by `this.uploadImage`, and then await it, and *then* assert on the second state change.

**Comment by daggeto** [comment]
Good point. Thanks, will try to do that.
