### ISSUE TITLE
Documentation for ShallowWrapper.setProps out of sync

### ISSUE THREAD

**Issue by wanecek** [airbnb/enzyme#1788]
**Describe the bug**
On the [overview of functions for ShallowWrapper](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md), `setProps` is denoted to accept a callback as the second argument (`.setProps(nextProps[, callback]) => ShallowWrapper`). On the [details page](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setProps.md), it only documents accepting the `nextProps` (`.setProps(nextProps) => Self`).

**To Reproduce**
_N/A_

**Expected behavior**
Since the callback does, in fact, seem to work, I would suggest documenting it (and also submitting a PR to `@types/enzyme`, which was how I noticed it). If it's intended to be deprecated, I suggest removing it from the overview and adding a note about in the details page.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Seems to originate from https://github.com/airbnb/enzyme/pull/1361

**Comment by ljharb** [comment]
This is fine - the docs reflect the last *published* version, if you change from "master" to https://github.com/airbnb/enzyme/blob/enzyme%403.4.4/docs/api/ShallowWrapper/setProps.md, which matches that tag, you'll see they're in sync.

The next time master is published, the docs will be updated. (When adding types for a specific version of anything, you'll always want to be be on the appropriate version tag, not on latest master)

**Comment by wanecek** [comment]
Thanks for taking your time to explain this, and for the advice regarding types! :) 

I may just be slow, but I still think the docs might be out of sync for 3.4.4 - compare [enzyme@3.4.4/docs/api/shallow.md](https://github.com/airbnb/enzyme/blob/enzyme%403.4.4/docs/api/shallow.md) with [enzyme@3.4.4/docs/api/ShallowWrapper/setProps.md](https://github.com/airbnb/enzyme/blob/enzyme%403.4.4/docs/api/ShallowWrapper/setProps.md).

### enzyme@3.4.4/docs/api/shallow.md
![screenshot-2018-08-25t17 20 54](https://user-images.githubusercontent.com/1533747/44619912-8d0b0e80-a88c-11e8-93c3-5981f875286a.png)

### enzyme@3.4.4/docs/api/ShallowWrapper/setProps.md
![screenshot-2018-08-25t17 20 27](https://user-images.githubusercontent.com/1533747/44619930-d196aa00-a88c-11e8-9e10-77165a8a2ec4.png)

**Comment by ljharb** [comment]
Thanks, you’re right. A PR to fix that would be appreciated.

**Comment by wanecek** [comment]
Will do! Just to confirm, the intended behaviour is to allow a callback, right?

**Comment by ljharb** [comment]
Yes

**Comment by ljharb** [comment]
Fixed by #1791.
