### ISSUE TITLE
Component is not updated after simulating error

### ISSUE THREAD

**Issue by aliaksandr-yermalayeu** [airbnb/enzyme#1809]
**Describe the bug**
Component is not rendered correctly after [error simulation](https://airbnb.io/enzyme/docs/api/ReactWrapper/simulateError.html) 

Possibly related issues: [#1757](https://github.com/airbnb/enzyme/issues/1757), [#1283](https://github.com/airbnb/enzyme/issues/1283)

**To Reproduce**
I created minimal [repo ](https://github.com/aliaksandr-yermalayeu/enzyme_mount_simulate/) with contained issue. Clone it, run _npm i_, then run tests with _npm test_ command. One snapshot will fail. 

![2018-09-07 19_33_09-dimscreen screen](https://user-images.githubusercontent.com/14282348/45231631-44644400-b2d5-11e8-8c91-66c96e227521.png)

**Expected behavior**
Error message should be rendered instead of normal content. It works fine with **shallow** and fails with **mount**

**Desktop:**
 - OS: win7
 - Version 3.6.0

**Comment by ljharb** [comment]
enzyme has no snapshot support; the closest would be `.debug()`.

Can you update your test cases to assert that either `Component` or `Error` have a length of 1, as you'd expect?

**Comment by asapach** [comment]
@ljharb, could you please explain why it works with `shallow()` and doesn't work with `mount()`?

**Comment by aliaksandr-yermalayeu** [comment]
> enzyme has no snapshot support; the closest would be .debug().

There was no difference after I replaced snapshots with .debug(), except formatting.

> Can you update your test cases to assert that either Component or Error have a length of 1, as you'd expect?

No problem. I updated repo, removed all unnecessary tests, added one similar test with pure error for comparison.

![2018-09-08 01_11_21-dimscreen screen](https://user-images.githubusercontent.com/14282348/45245234-3548ba80-b304-11e8-95a3-92f0e2963b84.png)

**Comment by ljharb** [comment]
@asapach `mount` uses react itself to render; `shallow` uses react-test-renderer. It's possible/likely that there's bugs in react-test-renderer, or in enzyme's use of it.

**Comment by aliaksandr-yermalayeu** [comment]
@jgzuke I suspected something like that. Thank you for the clarification.

**Comment by ljharb** [comment]
Reopening until #1812 lands.
