### ISSUE TITLE
displayName set on forwardRef is not honored

### ISSUE THREAD

**Issue by probablyup** [airbnb/enzyme#1810]
**Describe the bug**
In styled-components v4 beta we started decorating the forwardRef wrapper with displayName and various other statics to reduce the amount of interim component layers during rendering and preserve various library behaviors. https://github.com/styled-components/styled-components/blob/30c372cf635e0db77f74c0aaacf60deda729581c/src/models/StyledComponent.js#L249-L311

However, it doesn't seem like enzyme surfaces a `displayName` set on a forwardRef component.

**To Reproduce**
See this codesandbox: https://codesandbox.io/s/yv7l2p76q9

**Expected behavior**
The test expectations should work since name and displayName are set on the forwardRef node.

It would be really great if this could work for a few reasons:

1. Shallow rendering does not currently render the immediate child of ForwardRef, so if we modified our library so the wrapped child of ForwardRef had all the statics etc it still wouldn't work without diving

2. The components don't show up at all when using "find" off of "mount" since ForwardRef isn't honoring displayName

Sidebar: I really wish ref forwarding was implemented as a decorator or class mixin... _sigh_.

**Comment by ljharb** [comment]
Hmm, does react itself respect .displayName on a forwardRef?

**Comment by probablyup** [comment]
@ljharb It doesn't in the devtools as of right now... but it's a weird case since it's a metacomponent thingy and doesn't have a renderable

**Comment by probablyup** [comment]
cc @gaearon

**Comment by ljharb** [comment]
If it doesn't show up in the dev tools, then I wouldn't expect it to make any sense to have a displayName - typically only custom components have displayNames, and forwardRef produces a special kind of component that's not a class or an SFC.

**Comment by probablyup** [comment]
Yeah, I’m not really sure what to do about it honestly. Usage of the ref
forwarding API is incredibly awkward, but the functionality is super
compelling.

**Comment by gaearon** [comment]
If DevTools doesn't show it that sounds more like a bug with DevTools that we can fix.

**Comment by gaearon** [comment]
Do React warnings show it?

**Comment by probablyup** [comment]
I'll experiment and get back to you

**Comment by probablyup** [comment]
@gaearon I don't believe it does:

```
Users/bear/code/homepage/node_modules/react-error-overlay/lib/index.js:2172 Warning: Failed prop type: The prop `fluid.aspectRatio` is marked as required in `Image`, but its value is `null`.
    in Image (created by Context.Consumer)
    in BaseStyledComponent (created by ForwardRef)     <- that should be a named component
    in article (at PostExcerpt/index.js:24)
    in PostExcerpt (at PostList/index.js:13)
    in div (created by Context.Consumer)
    in BaseStyledComponent (created by ForwardRef)
```

**Comment by probablyup** [comment]
@gaearon this will be a problem with react-native too since they started doing the same thing we are: https://github.com/facebook/react-native/commit/e708010d18f938e2d6b6424cfc9485d8e5dd2800#diff-e250436371d8e58356be701ad28b37caR268

**Comment by probablyup** [comment]
Made a PR against React to support this: https://github.com/facebook/react/pull/13615

**Comment by jackson-sandland** [comment]
@probablyup I'm running into the issue you're describing.
I've confirmed the changes from this PR are in my local `react` src.
I've created a `Button` that uses forwardRef.
I've set a displayName as a static property in that file. 
`Button.displayName = "Button"`

When using find in an enzyme test - the static property displayName is not recognized. 
ForwardRef is recognized. 
`let component = shallow(<Form {...props} />).find("ForwardRef");` <-- component found
`let component = shallow(<Form {...props} />).find("Button");` <-- component not found

**Comment by ljharb** [comment]
@jackson-sandland what version of react and enzyme and enzyme adapter are you using?

**Comment by jackson-sandland** [comment]
@ljharb 
`react@16.5.2`
`enzyme@3.6.0`
`enzyme-adapter-react-16@1.5.0`
`enzyme-adapter-utils@1.8.0`
I figured out how to set the `displayName` but it's the `Higher Order Component` version of the `displayName` e.g. higherOrderWrapper(wrappedComponent).
Is that the best option we've got? 
Can we actually get a `find` by the name of the `wrappedComponent`?

**Comment by ljharb** [comment]
Finding by reference is preferred; so in that case, you can find by the wrapped component constructor itself.

Setting the displayName should make it show up in `.debug()`, but it may still be a bug that it's not findable.

**Comment by jackson-sandland** [comment]
It must still be a bug. 
Here's the output of `wrapper.debug()`:
'<div className="container">
  <ForwardRef(Button) className="btn" onClick={[Function: proxy]}>
    Text here
  </ForwardRef(Button)>
</div>'

**Comment by ljharb** [comment]
@jackson-sandland would you mind filing a new issue covering all this? I'll be happy to take a look at it ASAP.
