### ISSUE TITLE
enzyme-adapter-react-16 doesn't work with React v16.5.0

### ISSUE THREAD

**Issue by mocheng** [airbnb/enzyme#1813]
**Describe the bug**
After upgrading to React v16.5.0, all `mount` fails with error information: "Invariant Violation: Unable to find node on an unmounted component."

**To Reproduce**
1. With unit test code as below
```
import React from 'react';
import PropTypes from 'prop-types';
import Enzyme from 'enzyme';

const {mount, shallow} = Enzyme;
const Adapter = require('enzyme-adapter-react-16');
Enzyme.configure({adapter: new Adapter()});

describe('test name', () => {
      it('foo', () => {
        const wrapper = mount(<div>hello</div>);
        expect(wrapper.html()).toMatch(/hello/);
      });
});

```
2. Run the test case with enzyme

**Expected behavior**
It should pass, but failed.
After lock React version in `16.4.0`, the same unit test passes.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Node: v6.13.0
 - React: v16.5.0

**Comment by ljharb** [comment]
What version of react-dom are you using? The versions of react and react-dom always must be *identical*. (or at least the same minor)

**Comment by renom1101** [comment]
What `enzyme-adapter-react-16` package version do you use? Upgrading it to version `1.5.0` helped me.

**Comment by ljharb** [comment]
That is also required, as v1.5.0 contains a bugfix that prevents React v16.5 from breaking.

**Comment by jEnbuska** [comment]
I'm also experiencing the same problem. Described by @mo

**Comment by tyler-johnson** [comment]
I was also having this error, but upgrading to enzyme-adapter-react-16@1.5.0 fixed it for me so maybe that is all it takes?

**Comment by mocheng** [comment]
@tyler-johnson  After upgrading to h3o-next-example/package.json, it works.  Thank you
