### ISSUE TITLE
componentDidUpdate on setState with disableLifecycleMethods

### ISSUE THREAD

**Issue by TrevorBurnham** [airbnb/enzyme#1818]
**Describe the bug**

`componentDidUpdate` is invoked when `wrapper.setState()` is called, even when `wrapper` was created with the `{disableLifecycleMethods: true}` flag.

I've observed this bug in Enzyme 3.3.0 and 3.6.0.

**To Reproduce**

```jsx
import React from 'react';
import { shallow } from 'enzyme';

class TestComponent extends React.Component {
  componentDidUpdate() {
    throw new Error('componentDidUpdate was called');
  }

  render() {
    return null;
  }
}

describe('TestComponent', () => {
  it('does not call componentDidUpdate when disableLifecycleMethods is true', () => {
    const wrapper = shallow(<TestComponent />, {
      disableLifecycleMethods: true,
    });
    wrapper.setState({ foo: 'bar' });
    expect(true).toBe(true);
  });
});
```

**Expected behavior**

`componentDidUpdate` should never be invoked when `{disableLifecycleMethods: true}` is set.

**Comment by jgzuke** [comment]
@TrevorBurnham this seems to be intentional, see https://github.com/airbnb/enzyme/blob/master/packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx#L4702. It looks like this lifecycle method will not be called for `setState` in React 16

**Comment by TrevorBurnham** [comment]
@jgzuke Hmm, interesting. Any idea why the inconsistency between React 15 and 16 exists? Also, why is `componentDidUpdate` called by `setState` but not `setProps` under React < 16?

The [relevant line](https://github.com/airbnb/enzyme/blob/947fce04205679dc84e052eabae13d835c9c31cc/packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx#L4708) seems to have been a [very recent addition](9c5183320e4f16193d347ed7798e30e8a075b6e7) to the test suite, and I can't find any other context on it.

**Comment by ljharb** [comment]
You'd have to ask the React team - that's a change they made, and should be documented in the v16 changelog.
