### ISSUE TITLE
enzyme can not get the element that wrapper in antd form.creat()

### ISSUE THREAD

**Issue by chenglin0006** [airbnb/enzyme#1824]
**Describe the bug**
enzyme can not get the element that wrapper in antd form.creat()

**To Reproduce**
```jsx
import {shallow,mount} from 'enzyme';
import React from 'react';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import Filter from '../src/index'
import renderer from "react-test-renderer";
Enzyme.configure({ adapter: new Adapter() });

import {Form} from "antd/lib/index";
const WrappedAdvancedFilter = Form.create()(Filter);
const props = {
    // Jest 提供的mock 函数
    filterData:[{
        id: 'activityCode',
        name: '活动编码',
        inputChangeName:'titleChangeFun'
    },{
        id: 'searchParam',
        name: '查询条件',
    }],
    handleReset: jest.fn( (e) => {
        console.log('reset','=============')
    }),
    handleSearch:jest.fn( (e) => {
        console.log('search','=============')
    }),
    handleBack:jest.fn( (e) => {
        console.log('back','=============')
    }),
}

describe('filter', () => {
    it('simulates click events', () => {
        const component = renderer.create(
            <div className={'test'} onClick={()=>{console.log('test')}}>
                <WrappedAdvancedFilter {...props}/>
            </div>
        );
        let tree = component.toJSON();
        expect(tree).toMatchSnapshot();

        const wrapper = shallow(
            <div className={'test'} onClick={()=>{console.log('test')}}>
                <WrappedAdvancedFilter {...props}/>
            </div>);
        wrapper.find('div.test').simulate('click');//which outer the wrapper console log right info
        wrapper.find('button.reset').simulate('click');//which in the wrapper report wrong info
    });
});
```
**Expected behavior**
enzyme can get the element of formitem in the wrapper

**Screenshots**
![image](https://user-images.githubusercontent.com/25606887/45615003-e20dff00-ba9d-11e8-9b5c-6dc27a369669.png)
snapshots of the WrappedAdvancedFilter show the button reset exist,but jest can not find it
![image](https://user-images.githubusercontent.com/25606887/45615049-01a52780-ba9e-11e8-8a7f-7d8ec7d30c28.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
github:https://github.com/chenglin0006/bnq-common-filter

**Comment by ljharb** [comment]
I'm not familiar with `antd` or with `Form.create`. Enzyme doesn't have snapshot support - what does `wrapper.debug()` print out?

**Comment by ljharb** [comment]
Closing; happy to reopen with more info.

**Comment by afaqahmedkhan** [comment]
@ljharb I'm also facing the same issue with antd and enzymem, I'm trying to test pagination of antd with enzyme
here's my code
```

  it('should change pagination’s disabled state when clicking on pagination button', () => {
    const wrapper = shallow(
      <EditForm
        initialValues=""
        pageSize={10}
        DocumentFormData={initialValuesArr}
        handleSaveChanges={handleSaveChanges}
        handleCancel={handleCancel}
      />,
    );
    const firstPageButton = wrapper.find('.ant-pagination-item').at(0);
```


and the error I'm facing is 

![image](https://user-images.githubusercontent.com/7557141/55140590-44853d80-515a-11e9-84d6-bc032e32d125.png)

it's unable to find .ant-pagination-item class

**Comment by ljharb** [comment]
@afaqahmedkhan please file a new issue, include the implementation of `EditForm`, and the result of `wrapper.debug()`. Thanks :-)
