### ISSUE TITLE
A nested ForwardRef is not recognized as a valid component by shallow dive()

### ISSUE THREAD

**Issue by SinHouse** [airbnb/enzyme#1830]
**Describe the bug**
A nested ForwardRef is not recognized as a valid component when I do shallow dive() to it.

**To Reproduce**
1. Sample code:
```javascript
  import * as React from "react";
  import { shallow } from 'enzyme';

  const Component = () => <div/>
  const HOCOne = (WrappedComponent) => React.forwardRef(() => <WrappedComponent/>)
  const HOCTwo = (WrappedComponent) => React.forwardRef(() => <WrappedComponent/>)
  const WithNestedForwarRefComponent = HOCTwo(HOCOne(Component)))
  
  const vDomWrapper = shallow(<WithNestedForwarRefComponent/>);
  
```
2. Then debug() and dive() vDomWrapper:
```javascript
  vDomWrapper.debug()
  vDomWrapper.dive()
```
3. Debug output:
`<ForwardRef(HOCOne(Component)) />`
4. See dive() error:
`TypeError: ShallowWrapper::dive() can only be called on components`

**Expected behavior**
A ForwardRef component must be recognized as such and it must be possible to do dive () on it.

**Desktop:**
 - OS: Ubuntu 18.04
 - Node: 8.11.3
 - Enzyme: 3.6.0
 - React: 16.5.0

**Comment by SinHouse** [comment]
Fixed by this [Pull Request](https://github.com/airbnb/enzyme/pull/1832)

**Comment by ljharb** [comment]
What happens when you directly shallow-wrap `React.forwardRef(() => <WrappedComponent/>)`?

**Comment by SinHouse** [comment]
> What happens when you directly shallow-wrap React.forwardRef(() => <WrappedComponent/>)?

It works well in that case @ljharb
