### ISSUE TITLE
How to test Higher Order Component that provides Context

### ISSUE THREAD

**Issue by iiison** [airbnb/enzyme#1838]
I've created a HOC for my [form component](https://codesandbox.io/s/xr5r1n2xzo), it exposes few functions as `context` variables. Here is the code:

```js
// React 15


import React, { Component } from "react";
import PropTypes from "prop-types";

export default class FormContainer extends Component {
  constructor(props) {
    super(props);

    this.state = {
      shouldValidateForm: false
    };
  }

  getChildContext() {
    return {
      setFieldValue: (event, field) => {
        const fieldName = field.id;

        this.setState(prevState => ({
          [fieldName]: {
            ...prevState[fieldName],
            value: event.currentTarget.value
          }
        }));
      },

      addField: data => {
        this.setState({
          [data.id]: data
        });
      },
      formData: this.state
    };
  }

  /**
   * React Lifecycle Method: Renders the data
   *
   * @return {DOM} Main container DOM.
   */
  render() {
    return <form action="">{this.props.children}</form>;
  }

  static childContextTypes = {
    addField: PropTypes.func,
    setFieldValue: PropTypes.func,
    formData: PropTypes.object
  };
}
```

I want to unit test `addField`, `setFieldValue` in unit tests. I tried a few things but I couldn't figure it out. Can someone please point me in right direction about how to test it..
#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.1.0
| React            |  15.6.1

#### Adapter

- [ ] enzyme-adapter-react-16
- [X] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
If you want to test FormContainer's child context, you may need to wait on #664, or use `mount`.

(Note that there's no such property as `.childContextTypes`, unless you're exposing that as a convenience to consumers - in which case i'd named-export it instead of attaching it as a property)

**Comment by ljharb** [comment]
#664 is merged, and will be released soon; this seems answered.
