### ISSUE TITLE
Test for displaying button only when conditions are true

### ISSUE THREAD

**Issue by liricy** [airbnb/enzyme#1846]
I have a render function as shown below:
```
private render(): JSX.Element {
return (
<div>
{this.props.x && this.state.y &&
   <DefaultButton 
   onClick={this.onDeleteButtonClick}
   >		
   Delete
  </DefaultButton>
}		
</div>
);
}
```

Only when the 2 conditions this.props.x and this.state.y are true, display button. How do I write a test for the same? Please let me know. Thanks!

**Comment by ljharb** [comment]
Write one set of tests when `x` is `false`, and another when `x` is `true`.

In each case, setState so that `y` is `true`, and `false`, and then assert what renders in each of those 4 cases.
