### ISSUE TITLE
Error with test

### ISSUE THREAD

**Issue by lipalath-ms** [airbnb/enzyme#1847]

**Comment by ljharb** [comment]
I'm confused why you're doing `const userRolesErrorMessage = (instance)["userRolesErrorMessage"] = "";` - that's both conflating two assignments, and also it's extracting a momentary value off of the instance.

What is the value of `props`?

**Comment by liricy** [comment]
I apologize. Updated my question.

**Comment by ljharb** [comment]
The error message you're reporting isn't for the test code you showed. Can you either show the test code for the test that's failing, or show the error output for the code you provided?

**Comment by liricy** [comment]
Initially I was getting the above mentioned error. Please see updated:

Code:

private userRolesErrorMessage: string = "";
public test(): void {
      this.userRolesErrorMessage = "xyz";      
}

Test:

it('test', () => {
        const wrapper = mount(<TitleContainer {... props} />);
        expect(wrapper).toBeDefined();
        const instance = wrapper.instance() as TitleContainer;
        (instance)["test"];
        expect((instance)["userRolesErrorMessage"]).toEqual("xyz");
    });

Error:

![image](https://user-images.githubusercontent.com/6519992/46309827-6a96a000-c572-11e8-95ea-c9d5767ec0cd.png)

**Comment by ljharb** [comment]
`(instance)["test"]` would be a noop no matter what you did, unless `instance` had a getter on it. With `instance.test()`, are you still getting the issue? (Similarly, please do `instance.userRolesErrorMessage` instead of wrapping the object in parens, and using bracket notation for the property)

**Comment by liricy** [comment]
Figured out the issue. My code is assigning the value "xyz" as follows:

private userRolesErrorMessage: string = "";
public test(): void {
      this.userRolesErrorMessage = escape(strings.ListSubmissionsUserRolesFailMessage);      
}

escape(strings.ListSubmissionsUserRolesFailMessage) has the value "xyz". However, the test is not able to understand that expression and is returning null.

**Comment by liricy** [comment]
@ljharb Thanks for your help!
