### ISSUE TITLE
State is always initialized under `shallow`

### ISSUE THREAD

**Issue by abettadapur** [airbnb/enzyme#1849]
**Describe the bug**
I have a component that does not initialize any state.

If I shallow mount this component, when `render` is called, `this.state` has a `{}` value, even though I did not initialize it.

Repro:
```
const Enzyme = require("enzyme");
const React = require("react");
class Foo extends React.Component {
    constructor(props, context) {
        super(props, context);
    }
    render() {
        console.log(`State: ${JSON.stringify(this.state)}`); // prints State: {}
        return (React.createElement("div", null));
    }
}
it("Test render", () => {
    Enzyme.shallow(React.createElement(Foo, null));
});
```

**Expected behavior**
this.state should be `undefined`

** Versions **
Enzyme: 3.3.2
Enzyme-Adapter-React-16: 1.5.0

**Comment by ljharb** [comment]
See https://jsfiddle.net/69z2wepo/310645/ - it looks like `this.state` starts out `null` when you don't specify it.

I've added some tests that verify this, which seem to be passing locally.

Can you try updating to the latest enzyme (v3.6.0)?

**Comment by abettadapur** [comment]
I will upgrade and see.
The state may not be undefined, but it should not be {}

**Comment by ljharb** [comment]
Very true; it looks like actually in React 16.0 - 16.3 this [might be the case](https://travis-ci.org/airbnb/enzyme/builds/436310394) (please fill out the entire issue template). What React version are you using?

**Comment by ljharb** [comment]
Turns out this is a bug in the React shallow renderer, fixed in https://github.com/facebook/react/pull/11965.

I'll see if I can fix it in the 16.0, 16.1, and 16.2 adapters.

**Comment by abettadapur** [comment]
@ljharb Thanks for the quick turnaround

Just to close the loop, when will the fix appear in the adapter packages?

**Comment by ljharb** [comment]
The next release will include it; hopefully it will be in the next couple days.

**Comment by abettadapur** [comment]
@ljharb Thanks! Appreciate the quick response
