### ISSUE TITLE
wrapper.state() does not work

### ISSUE THREAD

**Issue by bonjefir** [airbnb/enzyme#1851]
This is a test in order to check value of `input` sets appropriately to state of component.
```
describe('RegistrationForm component', () => {
	const mockStore = configureStore();
	let wrapper;
	let store;

	beforeEach(() => {
		const initialState = { type: LOGIN_USER }; // LOGIN_USER is imported ...
		store = mockStore(initialState);
		const props = { store }

		wrapper = mount(<RegistrationForm {...props} />);
		console.log("beforeEach done", wrapper.state()) // ********* CONSOLE PRINT
	});

	it('should has firstName', () => {
		wrapper.find('[name="firstName"]').find('input').simulate('change',
			{
				target: { value: 'BBBBB', name: 'firstName' }
			}
		);
		//wrapper = wrapper.update();

		console.log("test->state: ", wrapper.state());  // ********* CONSOLE PRINT
		expect(wrapper.state().user.firstName).toBe('BBBBB');
	});
});
```
Here there is two calls to `state()` function of `wrapper` which both of them output `{}` as result. Also I put three `console.log(this.state)` in component, one in last line of constructor and two in first and last line of `handleChange` to ensure `simulate` runs as expected. Since I set `firstName` to `AAAAA` in constructor. It shows `constructor done -> AAAAA`, `handleChange1 -> AAAAA` and  `handleChange2 -> BBBBB`. So it seems wrapper could connect to component but `state()` could not get its state. I checked `wrapper.instance().state` as well.

```
"enzyme": "^3.6.0",
"enzyme-adapter-react-16": "^1.5.0",
"react": "^16.5.2",
"react-dom": "^16.5.2",
"jest": "^23.6.0",
```

**Comment by ljharb** [comment]
What's your component code? (Note that "simulate" doesn't actually simulate anything, it just calls a prop function)

You should also replace the commented line with `wrapper.update();`

**Comment by bonjefir** [comment]
Here is component code.
```
class RegistrationForm extends Component {
    constructor() {
        super()
        this.state = { user: {firstName: 'AAAAA'}}; // other fields of user omitted
        console.log('constructor done->', this.state);
    }
    // some other code here
    handleChange(event) {
        console.log('handleChange1 -> ', this.state); // shows handleChange1 -> AAAAA after running simulate
        let { user } = this.state;
        user[event.target.name] = event.target.value;
        this.setState(user);
        console.log('handleChange2 -> ', this.state); // shows handleChange2 -> BBBBB after running simulate
    }
    // some other code here
    render() {
        return (
            // some other code
            <ValidatorForm>
                <TextValidator
                    name='firstName'
                    onChange={this.handleChange}
                    // some other props
                >
                <TextValidator/>
            <ValidatorForm/>
        );
    }
}
```
1) Why `state()` in the test does not get expected result(it output `{}` as component state)?

2) Why getting state right after `mount` outputs `{}` instead of component state?

3) Calling `wrapper.update()` after `simulate` does special work? (I am confused, in some examples in order to simulate they do that and some other they do not and get right behaviour.)

**PS:**

@ljharb Thanks

TextValidator is [here](https://www.npmjs.com/package/react-form-validator-core)

**Comment by ljharb** [comment]
I think you have a bug in your code, btw - `this.setState(user);` should be `this.setState({ user });`

**Comment by bonjefir** [comment]
That was a typo. Currently I have not actual code at home and I rewrite it. I can double check that tomorrow but consider that `console.log('handleChange2 -> ', this.state);` output right thing(i.e `BBBBB` which sets from test).

**Comment by bonjefir** [comment]
I attached the actual code of both component and test. Also I attached the screenshot of test result. In the screenshot we have five state print. Three of them from inside component(constructor + 2*handleChange) which they have right value. But others which prints from test with `wrapper.state()` does not have value...
I Also uncomment `wrapper = wrapper.update()` and change it to `wrapper.update()` but it does not change anything...

![screenshot from 2018-10-06 12-33-25](https://user-images.githubusercontent.com/23652454/46569585-3cdf9b80-c964-11e8-9eab-890881209db5.png)
[RegistrationForm.txt](https://github.com/airbnb/enzyme/files/2452864/RegistrationForm.txt)
[RegistrationForm.test.txt](https://github.com/airbnb/enzyme/files/2452865/RegistrationForm.test.txt)

**Comment by bonjefir** [comment]
What is status of this issue? Is someone working on it?

**Comment by ljharb** [comment]
@bonjefir the one that was filed 4 days ago, that got its last update from you on a friday while it's sunday night right now? yes, someone's probably going to look into it, but you'll need to have some patience.

**Comment by ronen** [comment]
I just hit the same problem, and came across this issue.   

After some poking around I discovered the cause:  The component is wrapped with `connect` from `react-redux`, so the root node of the wrapper isn't actually the component in question, but rather a `Connect` instance -- which quietly returns empty state.

So my question is then... any good workaround to actually get at the wrapped instance's state?

**Comment by ljharb** [comment]
@ronen with `mount`, you should be able to traverse to the child and retrieve it directly; with `shallow`, you'd need to `.dive()` to it first.

**Comment by sensui7** [comment]
@ljharb what do you mean by traversing to the child? Could you elaborate?

**Comment by ljharb** [comment]
@sensui7 if you could share the results of `wrapper.debug()`, i can show you.

**Comment by sensui7** [comment]
Here is the result of wrapper.debug() for my testing component.
It's being wrapped with connect, so do I need a way to access it somehow through
`wrapper.instance()`?

`
<Connect(MyComponent) store={{...}}>
<MyComponent store={{...}}>
  <div />
</MyComponent>
</Connect(MyComponent)>
`

**Comment by reergymerej** [comment]
Here's the [`dive()` documentation](https://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html) for anyone interested.  This is so useful!  I'd been pulling out the semi-secret [`WrappedComponent`](https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L266) prior to this. 🤦‍♂️

**Comment by gogogous88** [comment]
**No one seems understand what is the problem**
even though shallow+dive() or mount gives a <Provider store={store}><Foo /></Provider>
state a expected {}, but in the Foo, this.state = {email:'', password:'',...}
<img width="445" alt="Screen Shot 2019-09-27 at 3 27 51 PM" src="https://user-images.githubusercontent.com/31117561/65805755-ad666600-e13b-11e9-88de-fc9ce2f59625.png">
<img width="667" alt="Screen Shot 2019-09-27 at 3 29 08 PM" src="https://user-images.githubusercontent.com/31117561/65805759-b48d7400-e13b-11e9-9b02-4ea33509601b.png">
<img width="596" alt="Screen Shot 2019-09-27 at 3 28 56 PM" src="https://user-images.githubusercontent.com/31117561/65805770-beaf7280-e13b-11e9-871c-65b4aa13c916.png">

**Comment by ljharb** [comment]
@gogogous88 i definitely understand the problem - in your case, however, it's that you shouldn't be accessing `instance.state`, you should be accessing `wrapper.state()` - ie, `wrapper.find(LoginPersonal).state()`.

**Comment by ljharb** [comment]
@bonjefir there's a number of issues here:
 - don't use `simulate`
 - `setState` could be async, so you can't rely on the values of `this.state` being set immediately after calling it

I apologize it took so long to respond to your original issue, especially given my comment above.

Can you update all enzyme things to the latest, and confirm if you still have the problem? If so, I'll happily reopen this.

**Comment by gogogous88** [comment]
> @gogogous88 i definitely understand the problem - in your case, however, it's that you shouldn't be accessing `instance.state`, you should be accessing `wrapper.state()` - ie, `wrapper.find(LoginPersonal).state()`.

really fast, Appreciate.

i got the problem and here is the right one to me
<img width="663" alt="Screen Shot 2019-09-27 at 4 10 52 PM" src="https://user-images.githubusercontent.com/31117561/65807038-827f1080-e141-11e9-81ff-cb156d79559d.png">

the quoted "LoginPersonal" give me the wrapper, and the unquoted I believe give me the instance

**Comment by ljharb** [comment]
@gogogous88 you're incorrect; they both only ever give you an enzyme wrapper. However, that suggests that the `LoginPersonal` you're finding for is not actually the same one being found when you find by name. Finding by reference is far more reliable than finding by name, and in either case do NOT do `.instance().state`, always only do `.state()`.

**Comment by niteshghule2** [comment]
I also facing same problem - can not read "wrapper.state" on test file.
I find following way to access the state values in test file.
I don't known this is write way or not.

  const ins = wrapper.instance()._instance;
  console.log(ins.state.error);
