### ISSUE TITLE
Snapshot testing for string literals exhibits unexpected behaviour

### ISSUE THREAD

**Issue by alanyin0322** [airbnb/enzyme#1857]
**Describe the bug**
The snapshot testing seem to render different snapshot for two different ways that would produce the same wrapper:
- `<strong>{this.props.whatever}</strong>{' for '}`
- `<strong>{this.props.whatever}</strongr> for{' '}`
In both cases, you would expect whitespace before and after `for`. However the snapshot for the above cases are different: 
- The first one produces:
```
        <strong>
          Dr Alan Yin
        </strong>
         for
         
        hospital admissions for

```
         
- The second one produces: 
```
        <strong>
          Dr Alan Yin
        </strong>
         for 
        hospital admissions for
  
```
The difference is whether the whitespace after the first `for` will start on a new line.  

**To Reproduce**
1. Set up a component that produce the above text snippet
2. Write a snapshot test for the component

**Expected behavior**
Both **should** produce the same snapshot, as writing it either way won't fail the actual test(for `wrapper.text()`). However the result shows that they produce different snapshots.

**Screenshots**
<img width="434" alt="screen shot 2018-10-08 at 3 23 56 pm" src="https://user-images.githubusercontent.com/25688258/46592409-3d1b9a80-cb0e-11e8-985b-20bf5e8358a4.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 59

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by ljharb** [comment]
Enzyme has no snapshot feature and no support for it.

If you’re talking about .debug() or traversal output, then I’d expect them to be a little different, because the former is one child of a string, and the latter is two string children.

**Comment by alanyin0322** [comment]
My apologies. I was going to create the issue in the Jest repo... @ljharb
