### ISSUE TITLE
Error: Cannot find module 'util'

### ISSUE THREAD

**Issue by schabluk** [airbnb/enzyme#186]
Hello,
I'm trying to create a simple test for my Meteor/React application. When doing import { shallow } from 'enzyme', I'm getting this error to the browser console:
> Error: Cannot find module 'util'

Source code: https://github.com/schabluk/test-meteor
Test file: https://github.com/schabluk/test-meteor/blob/master/client/__tests__/main-test.js
Meteor in version 1.3 (beta).

**Comment by lelandrichardson** [comment]
@schabluk is there a stack trace that goes along with that error?  I'm not sure where it would be coming from. We don't have any named `util` modules...

**Comment by schabluk** [comment]
This is what I get in the browser: 
> require()
 modules.js:100
require<.node_modules.htmlparser2.lib["Parser.js"]<()
 app.js:6060
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.node_modules.htmlparser2.lib["index.js"]<()
 app.js:5862
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.node_modules.cheerio.lib["parse.js"]<()
 app.js:3920
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.node_modules.cheerio.lib["cheerio.js"]<()
 app.js:3767
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.node_modules.cheerio["index.js"]<()
 app.js:3745
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.node_modules.enzyme.build["index.js"]<()
 app.js:133
fileEvaluate()
 modules.js:206
require()
 modules.js:98
require<.client.__tests__["main-test.js"]<()
 app.js:9
fileEvaluate()
 modules.js:206
require()
 modules.js:98
<anonimowa>
 app.js:57708

**Comment by schabluk** [comment]
After manually installing 'util' and 'events' packages (also was missing), I have this error: 

> TypeError: require(...).inherits is not a function

**Comment by ljharb** [comment]
Both of those packages are node core packages, which browserify should be shimming for you - neither need to be installed.

**Comment by lelandrichardson** [comment]
Yes, @schabluk this looks like you are trying to bundle enzyme in a browser-based environment but it is not bundling the dependencies correctly. What tools are you using in order to provide this?

If you haven't already, please take a look at our guides: http://airbnb.io/enzyme/docs/guides.html

**Comment by schabluk** [comment]
@lelandrichardson: yes, I followed the guide for both Jest and Mocha. Meteor is handling dependency bundling. I'm using new 1.3 beta, so it can be Meteor bug.

**Comment by lelandrichardson** [comment]
@schabluk interesting. Have you gotten this issue resolved? We may want to add a guide for meteor if there is something special that needs to be done for meteor.

Thanks!

**Comment by schabluk** [comment]
@lelandrichardson no, however the Mantra project (https://goo.gl/kHhja5) is using Meteor 1.3 and enzyme for testing, and it's working without errors, but the application architecture is bit different. I will have to make some effort to debug this issue.

**Comment by lelandrichardson** [comment]
@schabluk great. Well, let me know if there's anything we need to do to make enzyme work for that project.
