### ISSUE TITLE
isEmptyRender Not Working for Children

### ISSUE THREAD

**Issue by LandonSchropp** [airbnb/enzyme#1866]
**Describe the bug**

It seems like `isEmptyRender` fails when a component renders children, even if the children themselves are empty.

**To Reproduce**

This is a simplified test case that illustrates the problem:

```
class RenderChildren extends React.Component {
  render() {
    return this.props.children;
  }
}

class RenderNull extends React.Component {
  render() {
    return null;
  }
}

it("is an empty render", () => {
  let component = mount(
    <RenderChildren>
      <RenderNull />
    </RenderChildren>
  );

  expect(component.html()).toEqual(null);
  expect(component.isEmptyRender()).toEqual(true);
});
```

In this example, the first matcher passes but the second does not.

**Expected behavior**

If the component's HTML is `null`, then the component should be considered an empty render.

**Screenshots**

<img width="544" alt="screen shot 2018-10-12 at 11 53 54 am" src="https://user-images.githubusercontent.com/361591/46888507-92f58880-ce15-11e8-8239-fa6ea4e4b7cd.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser N/A
 - Version 3.7.0

**Comment by ljharb** [comment]
This is because `component` in this case *is* RenderChildren - which is not an empty render. You might want `component.hostNodes().isEmptyRender()`?

**Comment by LandonSchropp** [comment]
@ljharb Thanks for the quick reply. 🙂

I think I understand what you're saying, but it's not what I would expect from this function. My expectation when calling `isEmptyRender` is that it would work recursively. If the component ultimately ends up not rendering anything (by recursively evaluating to `null`, `false` or `[]`, then I would expect `isEmptyRender` to return `true`. Is it possible to change the current behavior?

**Comment by ljharb** [comment]
ah, true - in this case, `.hostNodes()` would return an empty wrapper because you don't have any.

`isEmptyRender` isn't currently designed to work recursively - although for `mount`, perhaps that makes sense.

**Comment by sstern6** [comment]
Working on this for Mount only per @ljharb suggestion.

A few things I noticed, current implementation of isEmptyRender is only checking for null.

https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored are the valid supported children.

Should we address supporting whats in the documentation in this tickets for isEmptyRender? or should we make another ticket for supporting those?  In addition, which of the following should we be supporting if not all of them.

Looks like the ones from the documentation that should make `isEmptyRender` return `true`:
- fasle
- null
- undefined?
- `<></>` (Fragments)
- `""`

`isEmptyRender` should return `false`?
- <div></div>
- <div />
- <div>{ null }</div>
- <div>{ undefined }</div>
- <div>{ false }</div>
- `"not an empty string"`

Did I miss any or did I misunderstand any of the test cases?

Thanks

**Comment by ljharb** [comment]
* note, empty fragments, but not fragments containing non-empty things.

I think your analysis makes sense.

**Comment by sstern6** [comment]
https://github.com/airbnb/enzyme/pull/1924

**Comment by LandonSchropp** [comment]
Thanks guys!
