### ISSUE TITLE
Selecting an ID equal to a number throws an error

### ISSUE THREAD

**Issue by sinisbad123** [airbnb/enzyme#1868]
**Describe the bug**
Whenever I chain the `.find()` to select a particular child element with an `id` prop and has a prop value of `1`, it throws an error.

I know 

**To Reproduce**
1. Create a `<table />` element
2. Populate the `<tbody />` with  several`<tr />` with a number value for the `id` prop
3. Run a sample test to chain the `.find()` method as follows: `wrapper.find('tbody').find('#1')`.

**Expected behavior**
To only select the specific `<tr />` with the corresponding single-digit id specified

**Screenshots**
No screenshot needed

**Desktop (please complete the following information):**
 - OS: OSX Version 10.13.4
 - Built-in Terminal of Visual Studio Code
 - Visual Studio Version: 1.28.1 (1.28.1)

**Additional context**
I only tried using the selector to select elements with single and double digits. Not sure if it has an issue with accepting numbers as the id selector

**Comment by ljharb** [comment]
That’s not a valid ID, i believe?

**Comment by sinisbad123** [comment]
Not quite sure if it's valid or not.

I know it sounds painful to actually selecting IDs with number values but there are really some people who actually assigns IDs based on the `Arrap.map()` index and loops elements with it. :/

**Comment by ljharb** [comment]
I think it is invalid; see https://github.com/airbnb/enzyme/issues/1577#issuecomment-372906961

It’s wildly incorrect to use IDs for that; they should be using data attributes.

**Comment by sinisbad123** [comment]
I see. Thanks @ljharb for this reference! I'll be sure to let other people know to actually use data attributes instead!
