### ISSUE TITLE
State of mounted wrapper (or child) not influencing logic in child's attributes.

### ISSUE THREAD

**Issue by scottiducati** [airbnb/enzyme#1870]
### Current behavior
Whether I update the state of the wrapper or a child, the child's props are not updated if their values are based on the state (or ternary logic uses state). 

### Expected behavior
A wrapper has a Button as a child, which has an attribute 'disabled'. The attribute's value is dependent on the state (example: toggle disabled state of button based on whether flag is true or false in state property). 

If state is changed, the ternary operator inside the child's 'disabled' attribute should pick up on the new state and alter the value of the attribute accordingly. 

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.7.0
| react               |  16.3.2
| react-dom           |  16.3.2
| react-test-renderer |  -
| adapter (below)     |  1.6.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by scottiducati** [comment]
````javascript

class Wrapper extends React.Component {

constructor() {
   this.state= {
       disabled: true
    }
}
return (
...
<Button disabled={this.state.disabled}/>
...
)

}
````

I've tried several different ways of inducing a state change in enzyme (works just fine) to test the appropriate change in props. However, the props of the Button don't change, even when .update() or instance().forceUpdate() are used. 

Any help is appreciated :)

**Comment by scottiducati** [comment]
Resolved this issue. Was due to Material UI's withStyles HOC, thus, when I set the state it wasn't setting the state of my component but the HOC instead. 

Solution was to export the component for testing without the HOC.

**Comment by ljharb** [comment]
@scottiducati I'd strongly suggest not doing that, and instead, use `.dive()` - one dive per HOC.

**Comment by scottiducati** [comment]
@ljharb Appreciate the quick feedback. 

Unfortunately, using `.dive()` I can't get access to the props of children of the component due to them being shallow-rendered (that's at least my understanding of the issue). So I'm running into the following scenario, where ` let component = wrapper.find('MyComponent').dive()` yields:

`expect(childOfComponent.exists()).toBeTruthy() ---> TRUE (as expected)`
BUT
`console.log(childOfComponent.instance().props) ---> FAIL (no access to props?)`

Is there a way to actually mount the component I want to test after (using `.dive()`) I've stripped off the HOC?

**Comment by scottiducati** [comment]
Resolved... I had to use `childOfComponent.props()` instead of `childOfComponent.instance().props`.

**Comment by ljharb** [comment]
Yep, in general you always want the enzyme methods; `.instance()` is an escape hatch, that comes with caveats.

Glad you figured it out!

**Comment by scottiducati** [comment]
Really appreciate all the fast help and tips Jordan!

Constructive Feedback: 
I think the Enzyme docs could benefit from a summary page (similar to the link I shared) that gives an overview of what hooks are executed for each method. Maybe it exists on the docs but I didn't see it and its super helpful to understand how to think about shallow vs. mount etc.

**Comment by ljharb** [comment]
I’d be happy to accept a PR that adds that!

**Comment by scottiducati** [comment]
Cool! 

Thanks again for the help!
