### ISSUE TITLE
Feature Request: Support space separated attribute selector

### ISSUE THREAD

**Issue by conartist6** [airbnb/enzyme#1879]
**Is your feature request related to a problem? Please describe.**
As someone writing testable components, I would like to use attributes to describe tag elements for the purposes of being selectable by tests. This is cleaner than css selectors, which could come to have styling associated with them. I would like for those attributes to be able to have multiple values. For example I may have a button component which is serving two simultaneous roles, "button", and "close-button". I would like to be able to represent this as `data-qa="button close-button"` which seems like a sensible, proactive way of making the application's UI available to test code.

**Describe the solution you'd like**
I would like for enzyme to support the space separated attribute selector defined as part of the css spec. The selector is `~=`. I would then select the close-button from the example above with `[data-qa~="close-button"]`.

**Describe alternatives you've considered**
There are obviously workarounds, but given that the solution aligns cleanly with the wording and the intent of the css selector specification, I don't readily see attractive alternatives.

I am willing to write the PR for this.

**Comment by ljharb** [comment]
A PR for this would be great! You may need to also make a change in https://github.com/aweary/rst-selector-parser, however.

**Comment by conartist6** [comment]
OK, thanks for the pointer!

**Comment by conartist6** [comment]
Actually it looks like it should be fine, which also is good because it means less potential that the change is breaking. [attributeValuesSelector](https://github.com/aweary/rst-selector-parser#attributevalueselector) has an operator field which captures the needed information.

**Comment by conartist6** [comment]
It looks like someone has already done this! https://github.com/airbnb/enzyme/commit/4c19481469b8f93cd5a4b7fb9761652a6c7d1a35

I'm going to close this ticket and open a separate one to update the documentation...
