### ISSUE TITLE
Tape instructions are incomplete

### ISSUE THREAD

**Issue by StefanoDeVuono** [airbnb/enzyme#1886]
I'm not sure if it was oversight because tape isn't the most popular library or because it was referenced on the same page as ava works with es6 out of the box, but there are no instructions for how to run tape tests. Obviously, `node [path-to-test].js` won't work.

This would be useful to document

**Comment by ljharb** [comment]
Why would that not work? As long as your test file configured enzyme before using it, I’d expect it to work fine.

**Comment by StefanoDeVuono** [comment]
Because it's ES6.

```
/Users/stefanodevuono/Documents/fudbud/client/tests/header.js:1
(function (exports, require, module, __filename, __dirname) { import tape from 'tape'
                                                                     ^^^^

SyntaxError: Unexpected identifier
```

**Comment by ljharb** [comment]
Ah - in that case you’d need something like `node --require=@babel/register file.js` since it’s invalid syntax in node otherwise. Since that remains true unrelated to enzyme, I’m not sure why extra documentation for it is called for - but if you think it would help, sure.

**Comment by TaeKimJR** [comment]
@StefanoDeVuono Lemme know if https://github.com/airbnb/enzyme/pull/1898 helps!
