### ISSUE TITLE
Best way to test event handlers

### ISSUE THREAD

**Issue by LukasZvikas** [airbnb/enzyme#1893]
Hello, I'm pretty new to this technology and having an issue finding the best way testing event handlers. As @ljharb mentioned couple of times that it's better to invoke functions directly, without simulation. So what would be the proper way to test onChange event with an event parameter for example without simulate function? Is it enough to check if it was called or there is more that has to be done? I would appreciate any advice, thanks.

**Comment by ljharb** [comment]
Answered [here](https://github.com/airbnb/enzyme/issues/1606#issuecomment-436819673), where you posted the same question:
> you don't need to test the event, you need to test the onChange handler. So, you'd do `wrapper.prop('onChange')()`. You don't need to test that it's been called - react and the browser handle that, and that's their job to test, not yours.
