### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 7

### ISSUE THREAD

**Issue by NorbertPiskorz** [airbnb/enzyme#1900]
### Current behavior

Some of my tests, that I haven't touched for over 10 weeks (also it's corresponding components) suddenly started to fail with the Error  `Enzyme Internal Error: unknown node with tag 7`

Example testcase where that happens:
```
let searchField = mount(<Autocomplete value='b' searchResults={[]} isOpen />)
const searchResultsNode = searchField.find(SearchResults)
expect(searchResultsNode).toBeTruthy()
```
`<Autocomplete />` is a regular PureComponent, so is `<SearchResults />`

### Expected behavior

`.find()` method not to throw that error, but find the matching element

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  ^3.2.0
| react               |  ^16.6.1
| react-dom           |  ^16.6.1
| react-test-renderer | ^16.3.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
If you update enzyme to the latest version, the 16 adapter should still work on React 16.3 - but certainly the 16.3 adapter will be more stable for you.

I'd like to fix this issue if it's still occurring on the latest general 16 adapter and enzyme. Can you confirm?

**Comment by NorbertPiskorz** [comment]
Updating fixed the issue
