### ISSUE TITLE
Dive shallow in a Context Consumer

### ISSUE THREAD

**Issue by flackou** [airbnb/enzyme#1908]
Hi,

### Current behavior

I'm trying to dive into a Component wrapped with a HOC that adds a Context Consumer but I get an error `TypeError: ShallowWrapper::dive() can only be called on components`. Here is my test case to reproduce :
```js
import React from 'react';
import { configure, shallow } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

const ThemeContext = React.createContext('light');

const withTheme = (Component) => {
  class ComponentWithTheme extends React.Component {
    render() {
      return (
        <ThemeContext.Consumer>
          {theme => <Component {...this.props} theme={theme} />}
        </ThemeContext.Consumer>
      );
    }
  }
  ComponentWithTheme.displayName = `withTheme(${Component.displayName || Component.name})`;
  return ComponentWithTheme;
}

class MyComponent extends React.Component {
  render() {
    const { theme } = this.props;
    return <div>{theme}</div>;
  }
}
const MyComponentWithTheme = withTheme(MyComponent);

const wrapper = shallow(<MyComponentWithTheme />, { context: 'dark' }).dive(); // TypeError
```
I'm not familiar with React Contexts, but it seems related to the "function as a child", which is however the regular way to use contexts (cf [Context.Consumer](https://reactjs.org/docs/context.html#contextconsumer) in React doc).

### Expected behavior

In my test case, the `dive` should succeed and return a wrapper around `<div>dark</div>` I guess.

### Your environment
My `package.json` :
```json
{
  "dependencies": {
    "react": "^16.5.1",
    "react-dom": "^16.6.3"
  },
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0"
  }
}
```
#### API

- [x] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.5.1
| react-dom           | 16.6.3
| react-test-renderer | 16.3.2
| adapter (below)     | 1.7.0

#### Adapter

- [x] enzyme-adapter-react-16

Am I getting something wrong ? Is there anything particular to do when "shallow diving" in a Context Consumer ? I can't see where's my error on this case so any help would be appreciated !

**Comment by ljharb** [comment]
Indeed; this is because you're shallow rendering your arrow function, which means your render prop is never invoked.

You can try: `shallow(<MyComponent />, { context: 'baz' }).shallow()` - which should give you a wrapper around the div.

**Comment by flackou** [comment]
Hi @ljharb, thanks for your answer. It's not better with `.shallow()` :
```
Invariant Violation: ReactShallowRenderer render(): Shallow rendering works only with custom components, but the provided element type was `object`.
```
But you made me realize that my use case is not accurate : in fact, I met this error while diving into a HOC that adds `Context.Consumer` wrapper. I edited my initial comment to make it clearer. And to be more precise, my "real word" use case is with React Native and the [withNavigation](https://github.com/react-navigation/react-navigation/blob/2.18.1/src/views/withNavigation.js) HOC provided by React Navigation package, but I guess it's not very important as far as I can reproduce the error with a simple test case like above.

**Comment by ljharb** [comment]
Ah - that’s the problem then. enzyme does not yet support new-style Context.

**Comment by flackou** [comment]
Oh OK ! So I guess I have to wait for the checkbox "New context APIs in 16.3" to be checked in #1553 ? If so, I'll just close my ticket and follow the latter for updates.

**Comment by WNemencha** [comment]
Hello, any workaround ?

**Comment by ljharb** [comment]
The workaround is, continue to use the regular context APIs and avoid createContext for now.

**Comment by thousight** [comment]
@ljharb do you have an example on how to do that?

**Comment by ljharb** [comment]
@thousight there's tons of examples all over the internet on how to use the only form of context that existed prior to React v16.3 :-)

**Comment by Fandekasp** [comment]
Enzyme is the final hurdle we have to complete the react-redux v6 migration (which uses the React v16.3 new context API).
Looking forward to see the PR #1966 completed!

**Comment by mkatanski** [comment]
@thousight I've done some workaround for it, below is my example. If someone knows better solution I'm eager to see it 😈 

In my example I can test whether the `changeByOffset` method that comes in context is called in `onChange` event. 

**DataListPagination.test.tsx**
```ts
const mockChangePageByOffset = jest.fn().mockReturnValue('mock changePageByOffset');
jest.mock('../../providers/DataPaginationProvider', () => ({
  DataPaginationContext: {
    // tslint:disable-next-line:no-any
    Consumer: (props: any) =>
      (
        <div id="DataPaginationContext.Consumer" {...props}>
          {props.children({
            limit: 'limit',
            offset: 'offset',
            totalCount: 'totalCount',
            changePageByOffset: mockChangePageByOffset,
          })}
        </div>
      ),
  },
}));

describe('DataListPagination', () => {

    it('should handle offsetChange event correctly', () => {
      const component = enzyme.shallow<DataListPagination, {}, DataListPagination>(
        (<DataListPagination />));

      // call shallow() method to invoke render prop function
      // and return component inside it
      const deepComponent = component.shallow();
     
     // find component and simulate onChange event
      deepComponent.find('OffsetPagination').simulate('change', 'test_value');

      expect(mockChangePageByOffset).toHaveBeenCalledTimes(1);
      expect(mockChangePageByOffset).toHaveBeenCalledWith('test_value');
    });
});
```

Tested component **DataListPagination.tsx**

```ts
export class DataListPagination extends Component<{}> {
  handleOffsetChange = (changePageByOffset: (n: number) => void) =>
    (newOffset: number) => changePageByOffset(newOffset)

  renderChildren = ({ limit, offset, totalCount, changePageByOffset }: DataPaginationContextType) => {
    return !!totalCount && (
      <OffsetPagination
        limit={limit}
        offset={offset}
        maxItems={totalCount}
        floated="right"
        onChange={this.handleOffsetChange(changePageByOffset)}
      />
    );
  }

  render() {
    return (
      <DataPaginationContext.Consumer>
        {this.renderChildren}
      </DataPaginationContext.Consumer>
    );
  }
}
```

**Comment by zhaiduo** [comment]
> Indeed; this is because you're shallow rendering your arrow function, which means your render prop is never invoked.
> 
> You can try: `shallow(<MyComponent />, { context: 'baz' }).shallow()` - which should give you a wrapper around the div.

I have the same problem, but return the following error:

> Invariant Violation: ReactShallowRenderer render(): Shallow rendering works only with custom components, but the provided element type was `object`

**Comment by jstnn** [comment]
From Enzyme `v3.9.0` you can dive in context consumers ;)

**Comment by atsikov** [comment]
Looks like this issue is not fully fixed. `.dive()` works correctly for jsx, but fails to dive into class of functional components.

This will pass
```
    const wrapper = shallow(
        <Context.Consumer>
            {({ text }) => <Component text={text} />}
        </Context.Consumer>,
    );
    expect(wrapper.dive().text()).toBe("from context");
```

However this will fail
```
const WithConsumerFC = props => (
    <Context.Consumer>
        {({ text }) => <Component text={text} />}
    </Context.Consumer>
);
const wrapper = shallow(<WithConsumerFC />);
expect(wrapper.dive().text()).toBe("from context");
```
```
Expected: "from context"
Received: "<Component />"
````

**Comment by atsikov** [comment]
Actually, I am wrong. Just need to dive deeper to get actual Component rendered.

**Comment by mjancarik** [comment]
I created module for workaround https://www.npmjs.com/package/shallow-with-context. The module works well in our projects.

**Comment by ljharb** [comment]
@mjancarik if the workaround fixes the problem, filing it as a PR would be helpful - but you may want to look into the `wrappingComponent` option.

**Comment by vishalc129** [comment]
> Actually, I am wrong. Just need to dive deeper to get actual Component rendered.

what do you mean by dive deeper, i'm facing same issue

**Comment by evo-home-task** [comment]
@vishalc129 you need to call `.dive()` once again. The first call returns what is rendered by `<Context.Consumer>`, second will return what is rendered by your wrapped component.

**Comment by atsikov** [comment]
@vishalc129 you need to call .dive() once again. The first call returns what is rendered by <Context.Consumer>, second will return what is rendered by your wrapped component.

**Comment by vishalc129** [comment]
> @vishalc129 you need to call `.dive()` once again. The first call returns what is rendered by `<Context.Consumer>`, second will return what is rendered by your wrapped component.

im wrapping my component  as 
const component = shallow(<Login {...props} />);

when i tried to debug using   console.log(component.debug());   then o/p is -- 
 <ContextConsumer>
          [function]
        </ContextConsumer>

and when i use - component.dive() it says - 
 TypeError: ShallowWrapper::dive() can not be called on Host Components

**Comment by ljharb** [comment]
@vishalc129 please file a new issue and i'll help you debug it.

**Comment by LingVuDev** [comment]
For all who came here for a solution. I just did 
```js
componentWrapper = shallow(<SomeComponent {...props} />).dive()
```

,which worked for a component wrapped by a context consumer.
