### ISSUE TITLE
documentation is too vague

### ISSUE THREAD

**Issue by allan-bonadio** [airbnb/enzyme#1919]
<details>

### Current behavior
I read the documentation, and get frustrated because it leaves out lots of information.

### Expected behavior
I read the documentation, and I understand and know what to expect.

### Your environment
two eyes, one brain, and my laptop and its react projects

#### API

- [ x ] shallow
- [ x ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |   3.7.0
| react               |  16.4.2
| react-dom           | 16.4.2
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ X ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

#### Specific Questions

</details>

The documentation is too vague about a lot of its nouns.  I would gladly edit your doc pages if I knew answers to these questions.  (by wiki or by source?)  And, hurry up, I'm unemployed this month so I have time to work on it.

First of all, there needs to be a clear distinction between types of nodes:
- DOM nodes, created from react nodes
- React nodes, embedded inside wrapper nodes
- Wrapper nodes, the main topic of enzyme.  These are 'enzyme wrappers' not 'react wrappers', right?

Wrapper nodes seem to be analogous to jQuery objects - a non-array array of ... some kind of nodes.  Maybe wrappers aren't nodes themselves, but they contain zero or more nodes as with a jQuery object?

- What's the difference between at() and childAt()?  They look the same.  

- get(i) will return the React node for the slot i in the called wrapper.  If I want the wrapper for the Wrapper node at slot i, should I use an array index [i]?

- What's a "host node" and what does hostNodes() do?

- is first() the same as at(0) or childAt(0) or get(0)?  What's the 'current node' in the description?

- if exists(no argument) returns false, does that mean that the wrapper it's called on has 0 nodes?  Again, it talks about "the current node" - except a wrapper is an array of nodes.

- hasClass() is written as though the wrapper has exactly 1 node in it - is that a requirement?  What is the 'current node' again?

- instance() returns an 'underlying instance' of a wrapper.  It says the return type is "ReactComponent | DOMComponent".  Does that only work on wrappers with one node?  Do you mean, for a ReactComponent it'll return the 'this' instance of the class?  and if it's a real dom element like &lt; div &gt; it'll return the DOM node itself?  What if it's a functional react component?

- matchesElement(node) says it "Returns whether or not a given react element matches the current render tree."  It's not clear whether the wrapper it's called on is the 'react element' or the 'current render tree'.  Do wrappers have a secret 'root node' hidden inside?

- the .name() function should make a clear distinction that it's not returning the value of the 'name' attribute.

- what's the overall difference between Shallow Rendering methods and Full DOM Rendering methods?  That is, if I say 
let s = shallow(&lt;MyComp selectedIndex='0' /&gt;);
let m = mount(&lt;MyComp selectedIndex='0' /&gt;);

what's the difference between s.at(0) and m.at(0)?  Since the shallow wrapper doesn't have any enclosed nodes, shouldn't the first return null or something?

- does find(selector) give up at a node once it's found, without traversing inside it?  Seems to be.  For instance if you find('strong') on &lt;strong&gt;&lt;strong /&gt;&lt;/strong&gt;, you will get only the outer-most strong node, right?  wasn't what I was expecting.

**Comment by ljharb** [comment]
It's markdown files in the repo, and at release time, those are converted to the gitbook format. Definitely update the `.md` files :-)

Thanks!
