### ISSUE TITLE
When using forwardRef, the wrapper instance is null

### ISSUE THREAD

**Issue by 42shadow42** [airbnb/enzyme#1928]
### Current behavior

It appears when wrapping components in forwardRef, the component instance becomes null.

### Expected behavior

The instance should be an instance of the forwardedRef

  expect(wrapper.instance()).toBeTruthy();

### Your environment

        "next": "^7.0.2",
        "react": "^16.4.2",
        "react-dom": "^16.4.2",
        "enzyme": "^3.5.0",
        "enzyme-adapter-react-16": "^1.3.0",
        "jest": "^23.5.0",

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.5.0
| react               | ^16.4.2
| react-dom           |^16.4.2 
| react-test-renderer | ???
| adapter (below)     | ^1.3.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

```
import React from "react";
import { mount } from "enzyme";
import Layout from ".";

test("has children", () => {
  const wrapper = mount(<Layout>Some children</Layout>);
  const text = wrapper.text();

  expect(text).toContain("Some children");
  expect(wrapper.instance()).toBeTruthy();
});

```

```
import React, { forwardRef } from "react";

const Layout = ({
  children
}) => (
  <div>{children}</div>
);


export default forwardRef((props, ref) => {
  return <Layout {...props}></Layout>
});

```

**Comment by ljharb** [comment]
This is correct as is - react only provides an instance on class-based components. SFCs and all the new types intentionally lack an instance.

What are you trying to use the instance for?

**Comment by 42shadow42** [comment]
I'm trying to test the Layout component, but I can't get an instance, I tried converting the functional component to the following class component, but it still returns null

export class Layout extends Component {

  render(){
    return (<div>
      {this.props.children}
    </div>)
  }
}

**Comment by 42shadow42** [comment]
From what you say the main problem is my higher order component is functional and can't return an instance, I understand now why the workaround of exporting the lower order component and finding it from the DOM works;
```
import React from "react";
import { mount } from "enzyme";
import Layout,  { Layout as RealLayout } from ".";

test("has children", () => {
  const wrapper = mount(<Layout>Some children</Layout>);

  expect(wrapper.text()).toContain("Some children");
  expect(wrapper.find(RealLayout).instance()).toBeTruthy(); //workaround
  expect(wrapper.instance()).toBeTruthy();
});


```

It doesn't resolve my issue. The higher order component is created by a mobx decorator and to my understanding there isn't a way to export the real component in this case.

```
@inject('stores'), @observer
export class Layout extends Component {

  render(){
    return (<div>
      {this.props.children}
    </div>)
  }
}

```

**Comment by 42shadow42** [comment]
Nevermind, I tried it with the decorator syntax, and it works. I can use the find method in any cases where decorators are not used. Closing the issue. Thanks for your insight.

**Comment by ljharb** [comment]
I'd suggest looking into `.dive()` (one per HOC), and `expect(wrapper.find(RealLayout).instance()).toBeTruthy();` provides zero value - if you're trying to determine if it's there, do `expect(wrapper.find(RealLayout).length).toBe(1);` or similar.
