### ISSUE TITLE
Cannot find HTMLElements by class

### ISSUE THREAD

**Issue by 42shadow42** [airbnb/enzyme#1929]
### Current behavior

It appears that find, can't find html elements by class like HTMLAnchorElement

### Expected behavior

```
test("can find anchors", ()=> {
  const wrapper = mount(<div><a href="#"></a></div>);

  expect(wrapper.find('a').length).toBe(1); // passes
  expect(wrapper.childAt(0).instance()).toBeInstanceOf(HTMLAnchorElement); //passes
  expect(wrapper.find(HTMLAnchorElement).length).toBe(1); //fails
});

test("can find spans", ()=> {
  const wrapper = mount(<div><span>Test</span></div>);

  expect(wrapper.find('span').length).toBe(1); //passes
  expect(wrapper.childAt(0).instance()).toBeInstanceOf(HTMLSpanElement); //passes
  expect(wrapper.find(HTMLSpanElement).length).toBe(1); //fails
});

```

### Your environment

        "next": "^7.0.2",
        "react": "^16.4.2",
        "react-dom": "^16.4.2",
        "enzyme": "^3.5.0",
        "enzyme-adapter-react-16": "^1.3.0",
        "jest": "^23.5.0",

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.5.0
| react               | ^16.4.2
| react-dom           |^16.4.2 
| react-test-renderer | ???
| adapter (below)     | ^1.3.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
That is very much not something we ever expected anyone would do. Can you elaborate on your use case? (Considering you can get and find by the tag name, or by the `.type()`)

**Comment by 42shadow42** [comment]
No, special use case, it was just the first way I tried, at first I thought my code was broken.

**Comment by ljharb** [comment]
On the enzyme wrapper, you can call .type() and it will give you either the component function or the html tag name, which can be passed into .find().

**Comment by ljharb** [comment]
In general I wouldn't use `.instance()` for that - instead, `expect(wrapper.childAt(0).is(Layout)).toBe(true)`.

There's nothing to fix - React itself uses a string for HTML tags - it's very rare for anything in the entire JS ecosystem to use DOM constructors directly.

**Comment by ljharb** [comment]
To clarify; nothing to fix in .type() - it definitely seems like a reasonable feature request to be able to find DOM elements by constructor.

**Comment by k3ithl1m** [comment]
I would like to help this out :)

**Comment by k3ithl1m** [comment]
@ljharb Here's my plan on approaching this feature. I'm going to write the test cases for all the HTML element constructor. and each of it will basically be something like
`it('finds area element with HTMLAreaElement', () => {
        const Component = mount(<div><area alt="#" /></div>);

        expect(Component.find(HTMLAreaElement).length).toBe(1);
      });`

After writing all the test cases. I will then implement the feature within the reduceTreesBySelector function (because find uses that with the selector) and implement some function there (havent fully thought through yet. 

However, I have one question. For the time being. How do i import the HTMLElements constructor/class

**Comment by ljharb** [comment]
That seems like a good approach.

In a browser, they’ll be globals - but in node, they’ll be nonexistent. So we’ll need to code for both cases gracefully, using typeof (and using skip in the tests as needed). We’ll want to be sure we have test cases for both mount and shallow.

**Comment by ljharb** [comment]
You can't know; all you can do is check if `typeof HTMLAnchorElement === 'undefined'` or not, etc.

It would be a good idea to test for everything that we might be able to support.

**Comment by k3ithl1m** [comment]
I might be misunderstanding this and correct me if i'm wrong. But if that's the case, then we couldnt write test cases in ReactWrapper.spec.js like this 

`   expect(Component.find(HTMLAreaElement).length).toBe(1);
  });`

because the HTMLAreaElement couldnt be defined in the first place?

And if I am wrong, how should I go about writing a test case?

**Comment by ljharb** [comment]
That test will work fine - when the tests are run in an environment that has a DOM available. In node, they’ll be skipped.

**Comment by k3ithl1m** [comment]
Ok, got it. I'm gonna write the test cases for all of them and then make a PR for you to check and provide suggestions. When those are good, I'll work on on the feature then.
