### ISSUE TITLE
state set by enzyme is not accessible inside component

### ISSUE THREAD

**Issue by jitenderchand1** [airbnb/enzyme#1936]
### Current behavior
setState not able to re-render the component.  I have two different layout depending on data which is being set using setState. I can see the state within the test case by running `wrapper.instance().state.rows` but state inside component won't display the state. 

### Expected behavior
State which are set by enzyme's `setState` method should be available inside component.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.7.0
| react               | ^16.5.2
| react-dom           | ^16.5.2
| react-test-renderer | NA
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

**table.js**

```
import React, { Component } from 'react';
import styled from 'styled-component';
import ReactDataGrid from 'react-data-grid';
import { Filters } from 'react-data-grid-addons';
import PropTypes from 'prop-types';


export class Table extends Component {
  constructor(props) {
    super(props);
    const {
      NumericFilter,
      AutoCompleteFilter,
    } = Filters;
    this.columns = [
      { key: "id", name: "ID", editable: true },
      { key: "title", name: "Title", editable: true },
      { key: "complete", name: "Complete", editable: true }
    ];
    this.state = {
      rows: [],
    };
  }

  renderRow = (i) => {
    const { rows } = this.state;
    return rows[i];
  }

  render() {
    const { className } = this.props;
    const { rows } = this.state;
    console.log('rows Length', rows.length) // always 0
    return (
      <div className={className}>
        {rows.length
          ? (
            <ReactDataGrid
              rowHeight={50}
              columns={this.columns}
              rowGetter={this.renderRow}
              rowsCount={rows.length}
            />
          )
          : <span id="no-product-message">No Items to be Shown</span>
        }
      </div>
    );
  }
}

Table.propTypes = {
  className: PropTypes.string,
};

Table.defaultProps = {
  className: '',
};


export default styled(Table)`
  .react-grid-HeaderCell{
    white-space: normal !important;
  }
  .react-grid-Cell__value{
    display: flex;
    align-items: center;
  }
`;
```

**mountWithTheme**

```
export const mountWithTheme = (children, options) => (
  mount(<ThemeProvider theme={theme}>{children}</ThemeProvider>, options)
);
```

test.js

```
it('should render table if product data is available', () => {
    const wrapper = mountWithTheme(<Table />).find(Table);
    const instance = wrapper.instance();
    jest.spyOn(instance, 'renderRow');
    instance.setState({
      rows: [{ id: 0, title: "Task 1", complete: 20 }],
    });
    console.log(instance.state.rows) // [{ id: 0, title: "Task 1", complete: 20 }]
    expect(wrapper.find('ReactDataGrid').exists()).toBe(true);
    expect(instance.renderRow).toHaveBeenCalledTimes(1);

  });
```

**wrapper.debug()'s output**

<img width="459" alt="screen shot 2018-12-11 at 4 54 29 pm" src="https://user-images.githubusercontent.com/19687185/49782730-76b98d80-fd6b-11e8-82c3-098cd71990f9.png">

**Comment by ljharb** [comment]
Don't use `instance.setState`, use `wrapper.setState`.

**Comment by jitenderchand1** [comment]
this was exactly what I did back but got following error. 

<img width="695" alt="screen shot 2018-12-12 at 9 33 16 am" src="https://user-images.githubusercontent.com/19687185/49834683-238a1e00-fdf1-11e8-9ff3-455fc222a901.png">

**Comment by jitenderchand1** [comment]
and when I do following modification in code
`const wrapper = mountWithTheme(<Table />);`
 
I got this error 

<img width="541" alt="screen shot 2018-12-12 at 9 33 56 am" src="https://user-images.githubusercontent.com/19687185/49835106-5254c400-fdf2-11e8-9ae9-0ab42ab849ff.png">

**Comment by ljharb** [comment]
ah, this is styled components - you have to use one `.dive()` per HOC, to get at your inner class.

**Comment by jitenderchand1** [comment]
I am using `mount` method, I don't think I need `.dive` here. but anyway I gave a try but none of following work.

` const wrapper = shallowWithTheme(<OrderProductTable />).find(OrderProductTable).dive();`
` const wrapper = shallowWithTheme(<OrderProductTable />).dive();`
` const wrapper = mountWithTheme(<OrderProductTable />).find(OrderProductTable).dive();`
` const wrapper = mountWithTheme(<OrderProductTable />).dive();`

Error
`.dive is not a function `


**helper.js**

```
export const shallowWithTheme = children => (
  shallow(children, { theme })
);

export const mountWithTheme = (children, options) => (
  mount(<ThemeProvider theme={theme}>{children}</ThemeProvider>, options)
);
```

**Comment by ljharb** [comment]
In that case, you'd need `.find` - the HOC wrapper might not have state, so you have to traverse down to your inner component.

**Comment by jitenderchand1** [comment]
This is what I was trying to do. I am using `.find` to traverse  `<Table>` and this is class component which does have state but even though I am getting error which I mentioned in my second [comment](https://github.com/airbnb/enzyme/issues/1936#issuecomment-446388759). 

Technically I am doing right, I am running the test against pure react component not on `styled-component. `

`import { Table } from './Table';`

**Comment by ljharb** [comment]
Gotcha, thanks. I'll take a look.

**Comment by ljharb** [comment]
OK, so, a few things:
 - `.dive()` only works on `shallow`
 -  in React 16+, SFCs don't have an instance, and they thus don't have state (other than with hooks, but that's unrelated)
 - `mountWithTheme` renders a `ThemeProvider` - what kind of component is that?
 - make sure you've got the latest version of enzyme and your react adapter, and try again?

I'm going to close for now, but will be happy to reopen it when we can reproduce it.
