### ISSUE TITLE
React - Jest - Enzyme: How to mock ref properties

### ISSUE THREAD

**Issue by X-Y** [airbnb/enzyme#1937]
I'm writing test for a component with ref. I'd like to mock the ref element and change some properties but have no idea how to. Any suggestions?

```
// MyComp.jsx
class MyComp extends React.Component {
  constructor(props) {
    super(props);
    this.getRef = this.getRef.bind(this);
  }
  componentDidMount() {
    this.setState({elmHeight: this.elm.offsetHeight});
  }
  getRef(elm) {
    this.elm = elm;
  }
  render() {
    return <div>
      <span ref={getRef}>
        Stuff inside 
      </span>
    </div>
  }
}

// MyComp.test.jsx
const comp = mount(<MyComp />);
// Since it is not in browser, offsetHeight is 0
// mock ref offsetHeight to be 100 here... How do I do it?
expect(comp.state('elmHeight')).toEqual(100);

```

**Comment by ljharb** [comment]
For one, you'd need `ref={this.getRef}`, but to mock that, do `sinon.spy(MyComp.prototype, 'getRef')` *before* creating the wrapper.

**Comment by X-Y** [comment]
Thanks @ljharb. I'm using jest, which I assume would be similar to sinon. I tried `jest.spyOn(MyComp.prototype, 'getRef').mockImplementation(()=>{this.ref={offsetHeight: 100}}`, the thing is "this" here is not refering to MyComp anymore, and I'm not sure how to get a reference to that. Do you know a way of fixing it?

**Comment by ljharb** [comment]
That's because you passed an arrow function as your mock implementation - pass a normal one instead.

**Comment by X-Y** [comment]
Great stuff, typescript is not happy, and I was not expecting it could monkey-patch inner workings like this, but this actually works. Thanks a lot!

**Comment by X-Y** [comment]
Code example in https://stackoverflow.com/questions/53721999/react-jest-enzyme-how-to-mock-ref-properties/53739669#53739669

**Comment by jacintorodrigues** [comment]
@ljharb and about mocking ref properties in function components?

Here is my example component:
```
const Example = ({onClick}) => {
  const ref = useRef(null);
  const handleClick = () => {
    onClick();
    ref.current.scrollTop = 0;
  };
  
   return (
      <button type="button" onClick={handleClick}>
        click me
      </button>
   );
```

And here is the test:
```
  it('should call provided onClick function when clicked', () => {
  const onClick = jest.fn();

    const wrapper = mount(
      <Example
        onClick={onClick}
      />,
    );

    wrapper.find('button').simulate('click');

    expect(onClick).toHaveBeenCalledTimes(1);
  });
```
I always have the following error: `TypeError: Cannot set property 'scrollTop' of null`

**Comment by ljharb** [comment]
@jacintorodrigues react, and the react shallow renderer, both provide no facility i'm aware of for hooking into hooks. Thus, there's no way to mock them out, introspect them, etc. You may want to `wrapper.update()` after mounting it, to ensure the ref is ready?

**Comment by megha-ui** [comment]
> For one, you'd need `ref={this.getRef}`, but to mock that, do `sinon.spy(MyComp.prototype, 'getRef')` _before_ creating the wrapper.

**@ljharb** 

when am trying to do this, am facing an error as " TypeError: Attempted to wrap undefined property _setRef as function" please help

my component is as follows:

/HeatmapComponent.js/

import React, { Component } from 'react';
import * as d3 from "d3";
import { connect } from 'react-redux';
import { executeSeries, updateFetchedData } from '../redux/actions/baseAction';
import GeneralUtils from '../utils/GeneralUtils';

class HeatmapComponent extends Component {
	constructor(props) {
        super(props);
        this.bodyIdentifier='';
        this.tooltipDivision='';
        this.heatmapdata = [
            {
                "group": "OP",
                "variable": "NR",
                "rating":""
            },
            {
            "group": "OP",
            "variable": "LO",
            "rating":"LO"
            }
        ]
    }

    componentDidMount(){
        this.createTable(this._rootNode.id, this.heatmapdata, "");
    }

	
    componentWillReceiveProps(nextProps) {
        const { heatmapData } = nextProps;
        d3.select("#heatmapChart").remove();
        this.createTable(this._rootNode.id, this.heatmapdata, heatmapData);
	}

	_setRef(componentNode) {
		this._rootNode = componentNode;  
	}
	
	createTable(id,hdata,apvalue){... }


            drawLegend(irlegend, "legendIR", legendColorIR);
            drawLegend(qrmlegend, "legendQRM", legendColorQRM);
            function drawLegend(ratings,id, color) { ...}


	render() {
		return (
            <div>
            <div className="heatmap" id="heatmap" ref={this._setRef.bind(this)}> </div>
            <svg id="legendIR" class="legendratings" width="500" height="30"></svg>
            <svg id="legendQRM" class="legendratings" width="500" height="30"></svg>
            </div>
		)
	}
}

export default connect(mapStateToProps, mapDispatchToProps)(HeatmapComponent); 

-----------------------------------------------------------------------------------------------

/HeatmapComponent-Test.js/


     it("should call _setRef",()=>{
          const _setRefSpy = sinon.spy(HeatmapComponent.prototype, '_setRef');
          wrapper= shallow( < HeatmapComponent store={store} 
            componentNode={true}
             _setRef={_setRefSpy}/>)
          wrapper.instance()._setRef()
          expect(_setRefSpy.calledOnce).to.equal(true)

        });

-----------------------------------------------------------------------------------------------
ERROR:

● HeatmapComponent › should render _setRef

    TypeError: Attempted to wrap undefined property _setRef as function
      
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:70:21)
      at Function.spy (node_modules/sinon/lib/sinon/spy.js:45:16)
      at Sandbox.spy (node_modules/sinon/lib/sinon/sandbox.js:275:26)
      at Object.<anonymous> (test/components/HeatmapComponent-test.js:55:42)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by ljharb** [comment]
@megha-ui because the method isn't on `HeatmapComponent` - that's a connect-HOC-wrapped component. In this case, you need to get a reference to the *unwrapped* component, and you can then spy in *its* prototype.

Either way, you wouldn't pass a `_setRef` prop anywhere.

**Comment by megha-ui** [comment]
> @megha-ui because the method isn't on `HeatmapComponent` - that's a connect-HOC-wrapped component. In this case, you need to get a reference to the _unwrapped_ component, and you can then spy in _its_ prototype.
> 
> Either way, you wouldn't pass a `_setRef` prop anywhere.

@ljharb 

the method _setRef is in HeatmapComponent only and it is calling by the render method as follows:


/HeatmapComponent .js/

 _setRef(componentNode) {
		this._rootNode = componentNode;  
	}


render() {
		return (
            <div>
            <div className="heatmap" id="heatmap" ref={this._setRef.bind(this)}> </div>
            </div>
		)
	}


can you please tell me how to write test case here for ref with this case.

**Comment by megha-ui** [comment]
> @megha-ui because the method isn't on `HeatmapComponent` - that's a connect-HOC-wrapped component. In this case, you need to get a reference to the _unwrapped_ component, and you can then spy in _its_ prototype.
> 
> Either way, you wouldn't pass a `_setRef` prop anywhere.

@ljharb

the method _setRef is in HeatmapComponent only and it is calling by the render method as follows:

/HeatmapComponent .js/

_setRef(componentNode) {
this._rootNode = componentNode;
}

render() {
return (
<div>
<div className="heatmap" id="heatmap" ref={this._setRef.bind(this)}> </div>
</div>
)
}
can you please tell me how to write test case here for ref with this case.

**Comment by ljharb** [comment]
You're not exporting HeatmapComponent though - you're exporting `connect()(HeatmapComponent)` or similar.

**Comment by mrdulin** [comment]
How about this answer: https://stackoverflow.com/a/61789113/6463558

**Comment by CristianoYL** [comment]
> How about this answer: https://stackoverflow.com/a/61789113/6463558

It works! Finally.

**Comment by gabor-ottlik-epam** [comment]
This didn't work for me when the variable of `useRef` is in `useEffect`

```
const test = useRef()

useEffect(() => {
  console.log(test.current)
})
```

This logs out the underlying dom element instead of the mock function since useEffect runs when the dom is rendered hence the dom element is attached to ref.
