### ISSUE TITLE
shallow->setProps: props not being set

### ISSUE THREAD

**Issue by MountainDrew** [airbnb/enzyme#1939]
### Current behavior
When running setProps. This results in it not being set in the most simple of scenarios:

simplified down to a basic component / test
```
import React from 'react';
import {configure, shallow} from 'enzyme';

import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });

const Component = ({prop1}) => <div>{prop1}</div>

describe.only('Component', () => {
  it('should set the props', () => {
    const component = shallow(<Component />);

    component.setProps({prop1: 'prop1'});

    expect(component.prop('prop1')).toEqual('prop1');
    expect(component.props()).toEqual({prop1: 'prop1'});
  });
});
```
result:

![image](https://user-images.githubusercontent.com/20781479/49811741-cabc7600-fd5b-11e8-9811-cc7f050038ac.png)

### Expected behavior
```
shallow -> component
-> set props
-> props -> the props that were set
```

### Your environment

Running this inside of jest (23.6.0) on Node (8.14.0).

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.3.0
| react-dom           | 16.3.0
| react-test-renderer | n/a
| adapter (below)     | 1.7.0

#### Adapter

- [ ] enzyme-adapter-react-16
- [x] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is because you're confused about what the wrapper *is* - it's not Component, it's what component *renders* - in this case, a div with no props.

**Comment by pablo-bl** [comment]
@ljharb 
From docs: 
> shallow(node[, options]) => ShallowWrapper, ShallowWrapper: The wrapper instance around the rendered output.

...'it's not Component, it's what component renders'

**Comment by ljharb** [comment]
@pablo-bl right - the rendered output. The docs agree with my comment.

**Comment by paddotk** [comment]
These answers don't help. What is `.setProps()` for if it's not expected to do anything?

**Comment by ljharb** [comment]
It certainly is expected to do something - it sets the props on the *rendered element*, not on the element whose `render` method is being evaluated. (for shallow)
