### ISSUE TITLE
Could not test onChange function of input component with enzyme

### ISSUE THREAD

**Issue by kartikjain26** [airbnb/enzyme#1941]
### Current behavior
This is my code
```jsx
it('onChange should work', function () {
    const onChange = spy(),
      wrapper = mount(CompoundInput label='Rule one' description='About us' onChange={onChange});

      // using classname of html input component
      wrapper.find('.pm-form-control').simulate('change', {target: { value : 'hello'}}); 
      expect(onChange).to.have.property('callCount', 1);
      expect(wrapper.find('.pm-form-control').props().value).to.be.equal('hello');
  });

it('onChange should work', function () {
    const onChange = spy(),
      wrapper = mount(CompoundInput label='Rule one' description='About us' disabled={true} onChange={onChange});

      // using classname of html input component
      wrapper.find('.pm-form-control').simulate('change', {target: { value : 'hello'}}); 
      expect(onChange).to.have.property('callCount', 0);
  });
```
### Expected behavior
First test
I expect onChange function to be called once which works but when I assert the changed value after onChange, my props.value is undefined.

Second Test
I expect onChange function to not be called at all as disabled=true is passed which disables the component but onChange is called once despite disabled being true.

Version- enzyme 3.3.0

**Comment by ljharb** [comment]
Please fill out the full issue template.

I'd suggest not using `simulate` at all - it doesn't faithfully simulate anything. You don't need to test that the browser, or React itself, are working properly - all you need to test is that you're providing the function you expect in the `onChange` property, and that that function does what you expect.
