### ISSUE TITLE
Expecting input text value to be equal to a label

### ISSUE THREAD

**Issue by Ibrahim-Islam** [airbnb/enzyme#1944]
I am trying to assert that anything I write in an input text is mirrored in a label.

```js
it('input text === label', () => {
  const wrapper = mount(<App />);
  const input = wrapper.find('input').first();
  input.instance().value = 'test';
  expect(wrapper.find('label').first().text()).to.equal('test');
});
```
`TypeError: Cannot read property 'equal' of undefined`

Its difficult to know what the issue is without being able to debug the tests and `console.log(wrapper.find('label').first().text())` does not print anything either.

**Comment by ljharb** [comment]
The input's value is based on props - setting it's JS instance value doesn't cause a rerender, so it's not available to the wrapper.

What do `wrapper.debug()` and `input.debug()` print out?

**Comment by Ibrahim-Islam** [comment]
That is correct. Triggering a change worked `input.simulate('change');`
