### ISSUE TITLE
why would shallow-rendering get more coverage and be easier to write.

### ISSUE THREAD

**Issue by 951565664** [airbnb/enzyme#1946]
However I'd say a series of shallow-rendering tests, for each component in your tree, would get you more coverage and be easier to write.

_Originally posted by @ljharb in https://github.com/airbnb/enzyme/issues/1289#issuecomment-338449546_

**Comment by ljharb** [comment]
Because there’s less to cover for each component at once that way - certainly yes, you’d want shallow rendering tests for every component in your tree.
