### ISSUE TITLE
TypeError: Cannot read property 'nodeType' of null when calling state()

### ISSUE THREAD

**Issue by xAlstrat** [airbnb/enzyme#1956]
I'm trying to test that a sub component is only rendered when the root component has an specific state value.

```
<div>
        <RetrieveHeaders
          ...
        />
        <RetrieveModelList
          ...
        />
        {headers && (
          <CustomTable
            ...
          />
        )}
      </div>
```

### Current behavior

TypeError: Cannot read property 'nodeType' of null when trying to access the mounted component state (Ej: mounted.state() or mounted.state("headers"))

### Expected behavior

Get the state object or it headers value.

The problem solves when I remove the `{headers && ...}` code.

#### API
- [ ] mount

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.5.2
| react-dom           | 16.5.2
| react-test-renderer | 
| adapter (below)     | enzyme-adapter-react-16

**Comment by ljharb** [comment]
Can you share the entire component and test code in question?

**Comment by xAlstrat** [comment]
I found the problem while trying to code a simpler version of my component.

My CustomTable uses the ReactTable component. I added a custom column with a button, like this: 

```
buildEditColumn = () => {
    const { classes } = this.props;
    return {
      Header: "",
      maxWidth: 40,
      Cell: cell => this.editOption(cell, classes),
      accessor: "__edit",
      sortable: false,
      filterable: false
    };
  };

editOption = (cell, classes) => (
    <Button
      variant="fab"
      mini
      color="warning"
      aria-label="Edit"
      className={classes.icon}
      onClick={() => this.handleEditOption(cell)}
    >
      {this.props.readOnly ? <Visibility /> : <Edit />}
    </Button>
  );
```

The problem is in the line `className={classes.icon}`, `classes` is not defined when I test the component, but instead of throwing an undefined/null exception when rendering, it throws the exception I mentioned above when accessing the state (but I could access the props without any problem).

Problem solved.

Thanks so much !

**Comment by ljharb** [comment]
I'm not familiar with `ReactTable`.

I'm glad you figured out the issue, but I completely agree that calling `.state()` should not throw an error. It'd be great if you could provide the code that can reproduce this, so i can fix the underlying bug.

**Comment by ljharb** [comment]
Closing for now; happy to reopen if there's a repro.
