### ISSUE TITLE
Can't get root state from a mounted component

### ISSUE THREAD

**Issue by pvanny1124** [airbnb/enzyme#1963]
### Current behavior
``` javascript
  import React from 'react';
  import { mount, shallow, render } from 'enzyme';
  import toJson from 'enzyme-to-json';
  import Signup from '../../app/src/Components/Authentication/Signup';
  import Client from '../../app/src/Client';
  import { Grid } from '@material-ui/core';

  describe("<Signup />", () => {
    it.only("checks if the password and confirmed passwords match", () => {
            const wrapper = mount(
                <Signup signupMethod={Client.Authentication().create} />
            );
            // console.log(wrapper.state()) //throws error here as well
            wrapper.find(Grid).find(".Submit").find("Button").simulate('click');
            expect(wrapper.state("uiMessage")).toBe("New password and confirmed password do not match.")
    });
```

Error upon running test with JEST:  ReactWrapper::state() can only be called on class components

### Expected behavior
according to docs, state([key]) of a full-dom rendered component returns the state of the root. finding my "button" component works fine, but the code breaks at the expect clause with this error: 

ReactWrapper::state() can only be called on class components

### Your environment
Running webpack, docker, node, mongodb on macOS.

#### API

- [ ] shallow
- [x ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.8.0
| react               | 16.4.2
| react-dom           | 16.4.2
| react-test-renderer | 16.7.0
| adapter (below)     | enzyme-adapter-react-16.3

#### Adapter

- [ ] enzyme-adapter-react-16
- [ x] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by Smolations** [comment]
FWIW, I've just run into this with a simple dropdown component. We just refactored it from a class component using `setState` to a functional component using hooks, and now `.state()` can no longer be acquired, throwing the error described in this issue. My guess is that this person's `Signup` component is doing the same thing, but just a guess.

**Comment by ljharb** [comment]
@Smolations hooks didn't exist when this issue was filed; and until the next release of enzyme, many hooks won't work with enzyme yet.

**Comment by ljharb** [comment]
[v3.10.0](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.10.0) has now been released.

Closing, pending repro info.
