### ISSUE TITLE
Missing displayName for styled-component

### ISSUE THREAD

**Issue by xunuoi** [airbnb/enzyme#1978]
For latest styled-component v4 and latest enzyme version, in test cases, the snapshots often miss the displayName. 

There is a relevant PR of styled-component v4, https://github.com/styled-components/styled-components/issues/1985

Please help check and give some proper fixing, thanks!

```js
it('render small app', () => {
        const result = shallow(
            <SmallApp
                company="Supercell"
                i18n={mockI18n}
            />
        );
        expect(result).toMatchSnapshot();
    });
```

### Current behavior

Shallow or mount styled-component Component would get `<ForwardRef >` and `<StyledComponent>` instead of its correct displayName.

```js
<SmallEntity
  company="Supercell"
  name={
    <ForwardRef
      style={
        Object {
      }
    >
      Supercell
    </ForwardRef>
  }
/>
```

### Expected behavior

Should get correct displayName in snapshots,

```js
<SmallEntity
  company="Supercell"
  name={
    <Text
      style={
        Object {
      }
    >
      Supercell
    </Text>
  }
/>
```
### Your environment
Jest+Enzyme
#### API

- [X] shallow
- [X] mount

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 16.7.0
| react-dom           | 16.7.0
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Note that enzyme has no snapshot support; `wrapper.debug()` is the closest thing.

What does that output?

**Comment by xunuoi** [comment]
@ljharb Ah, it's from jest. expect(shallow(Component)).toMatchSnapshot();

**Comment by chenesan** [comment]
@xunuoi pass shallow wrapper directly for snapshot test should not work I think. Are you wrapping the shallow wrapper with [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json)? And also it'd be easier to debug if you can share the output of `wrapper.debug` and the implementation of `SmallApp` and `SmallEntity`.
