### ISSUE TITLE
Simulate should return the event pass in

### ISSUE THREAD

**Issue by huchenme** [airbnb/enzyme#1980]
Not working (takes forever to run):

```
const changeEvent = { target: { value: 'foo' } };

component.find('input').simulate('change', changeEvent);

expect(onChange).toHaveBeenCalledWith(changeEvent);
```

Working:

```
component.find('input').simulate('change', { target: { value: 'foo' } });

expect(onChange.mock.calls[0][0].target.value).toEqual('foo');
```

Spend a lot time and figured out the event passed in have been changed to `SyntheticEvent` with lots more attributes.

Please let me know the correct way to test `input` change event

**Comment by huchenme** [comment]
Ok, I have a React component which have `value` and `onChange` prop, the React component internal have an `input`, the test scenario is: 

find `input` in the component, change the value, `onChange` should be triggered with the changed value. Here I am not testing React `input` is working as expected but my React component is working as expected.

Can you help me on how to test this using `enzyme`?

**Comment by ljharb** [comment]
You definitely don't need to test that - all you need to do is ensure that your component is putting the right function on an `onChange` on the input. Everything else you can trust to react and the browser.

I'd recommend using enzyme, but not `simulate` - `wrapper.find('input').prop('onChange')()` will invoke the prop function explicitly.

**Comment by huchenme** [comment]
Are you recommending this?

```
const onChange = jest.fn();
const wrapper = mount(<MyComponent onChange={onChange} />;
expect(wrapper.find('input').prop('onChange')).toBe(onChange);
```

**Comment by ljharb** [comment]
Yep! Or:
```jsx
const onChange = jest.fn();
const wrapper = mount(<MyComponent onChange={onChange} />;
const argument = {};
wrapper.find('input').prop('onChange')(argument);
expect(onChange).toHaveBeenCalledWith(argument); // or whatever the syntax is.
```

**Comment by huchenme** [comment]
Thanks, closing this now
