### ISSUE TITLE
Click event simulate not working

### ISSUE THREAD

**Issue by borisyordanov** [airbnb/enzyme#1982]
### Current behavior
When running this test:
```
    test('Inputs are required', () => {
        const wrapper = mount(<Payment />);
        const submitBtn = wrapper.find('#card-payment-submit-btn').at(1;
        const cardNumberError = wrapper.find('#card-number-error');

        submitBtn.simulate('click');

        const cardNumberErrorText = cardNumberError.text();
        expect(cardNumberErrorText).toEqual('Required');
    });
```
The expected value is never what it should equal. When i test manually the component functions as the test intends it to. This leads me to the belief that the click is never simulated.

### Expected behavior
I expect the `simulate` method to simulate a click

### Your environment
```
        "react": "^16.7.0",
        "@types/react": "^16.7.18",
        "jest" : "6.4.1",
        "ts-jest": "^23.10.5",
        "@types/jest": "^23.3.12",
        "enzyme": "^3.8.0",
        "enzyme-adapter-react-16": "^1.7.1",
        "@types/enzyme": "^3.1.15",
        "@types/enzyme-adapter-react-16": "^1.0.3",
```

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.8.0
| react               |  16.7.0
| react-dom           | 16.7.0
| react-test-renderer | N/A
| adapter (below)     | 

#### Adapter

- [x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Unfortunately, `simulate` doesn't really simulate anything - it's just sugar for invoking the `onClick` prop. As such, I'd suggest explicitly doing that in your test.

**Comment by borisyordanov** [comment]
@ljharb Can you tell us when simulate should/can be used for? Perhaps this information should be included in the docs (i myself can't find any relevant info), perhaps in the [Common Gotchas](https://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html#common-gotchas) section

**Comment by ljharb** [comment]
I don't think it should ever be used; explicitly invoking a prop is better. I haven't had time to write up anything in the `simulate` docs.

**Comment by borisyordanov** [comment]
@ljharb Can you share a resource about simulate? I'd be happy to prepare a PR updating the docs. I'd appreciate if you can point me in the right direction, i couldn't even find `simulate()` in the repo

**Comment by ljharb** [comment]
I don't have any resource available except a number of comments I've made in this very repo.

Simulate is documented here: https://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html / https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/simulate.md and https://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html / https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/simulate.md
