### ISSUE TITLE
ShallowWrapper renderProp docs link is broken

### ISSUE THREAD

**Issue by Bates550** [airbnb/enzyme#1983]
### Current behavior
![kapture 2019-01-18 at 16 03 47](https://user-images.githubusercontent.com/2865469/51418860-0278c380-1b3b-11e9-9b37-a35abaf41e25.gif)
On the [Shallow Rendering API](https://airbnb.io/enzyme/docs/api/shallow.html) page, `.renderProp(key)() => ShallowWrapper` doesn't navigate to the docs for `renderProp`. 

### Expected behavior
It should navigate to a page that looks like the rest of them (e.g. [render](https://airbnb.io/enzyme/docs/api/ShallowWrapper/render.html)), but with the information for [`renderProp`](https://airbnb.io/enzyme/docs/api/ShallowWrapper/renderProp.md).

**Comment by ljharb** [comment]
Indeed, thanks - that should link to https://airbnb.io/enzyme/docs/api/ShallowWrapper/renderProp.html

**Comment by doniyor2109** [comment]
Looks like it is gitbook's issue. GitbookIO/gitbook#1070

**Comment by ljharb** [comment]
Hmm, I’m not sure if that’s the issue - there’s no spaces in the filename.

**Comment by ljharb** [comment]
Are there more than just renderProp.md?

**Comment by doniyor2109** [comment]
I have built locally and these files are not converted to `.html`

- [Main Page](https://airbnb.io/enzyme/)
  - [Using Enzyme with SystemJS](https://airbnb.io/enzyme/#running-enzyme-tests)
- [Shallow Rendering API](https://airbnb.io/enzyme/docs/api/shallow.html)
  - [isEmptyRender](https://airbnb.io/enzyme/docs/api/shallow.html#isemptyrender--boolean)
  - [renderProp](https://airbnb.io/enzyme/docs/api/shallow.html#renderpropkey--shallowwrapper)
- [Full Rendering API](https://airbnb.io/enzyme/docs/api/mount.html)
  - [renderProp](https://airbnb.io/enzyme/docs/api/mount.html#renderpropkey--reactwrapper)

**Comment by doniyor2109** [comment]
It turns out those missing pages are not added to `SUMMARY.md`. That is why gitbook is not generating `.html` files for them.
