### ISSUE TITLE
TypeError: Cannot read property 'Events' of undefined

### ISSUE THREAD

**Issue by andysmith415** [airbnb/enzyme#1988]
### Current behavior
My test suite fails on Enzyme bootstrapping because it cannot find the needed react-dom dependency, despite the fact that I have it installed. 

Setup file:
```
import Enzyme from "enzyme";
import Adapter from "enzyme-adapter-react-16";

Enzyme.configure({ adapter: new Adapter() });
```

Test file: 
```
import React from 'react';
import { mount } from 'enzyme';

const Foo = () => <div />;

describe('Foo', () => {
  it('Works', () => {
    const wrapper = mount(<Foo />);
    expect(wrapper).toBeDefined();
  });
});

 FAIL  src/Test.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'Events' of undefined

      5 |

      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:838:89
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1252:5)
      at Object.<anonymous> (node_modules/react-dom/test-utils.js:6:20)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:31:18)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/index.js:4:18)
      at Object.<anonymous> (src/setupTests.js:7:50)
```
Any ideas what I'm missing here? Thanks.
### Expected behavior
The test runs to completion. 
### Your environment
```
    "@babel/cli": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-transform-destructuring": "^7.1.0",
    "@babel/plugin-transform-flow-strip-types": "^7.1.6",
    "@babel/preset-flow": "^7.0.0",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "jest": "23.6.0",
    "jest-pnp-resolver": "1.0.1",
    "jest-resolve": "23.6.0",
    "react": "^16.7.0",
    "react-app-polyfill": "^0.1.3",
    "react-dom": "^16.7.0",
    "webpack": "4.19.1",
```

Jest config:
```
 "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "resolver": "jest-pnp-resolver",
    "setupFiles": [
      "react-app-polyfill/jsdom",
      "<rootDir>/src/setupTests.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.js?(x)",
      "<rootDir>/src/**/?(*.)(spec|test).js?(x)"
    ],
    "testEnvironment": "jsdom",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      ".*@babel.*"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx"
    ]
  }
```
#### API

- [X] shallow
- [X] mount
- [X] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 16.7.0
| react-dom           | 16.7.0
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by prishedko** [comment]
@andysmith415 I had the same problem when **react-dom** was mocked. Please looked at mocks of **react-dom** in **__mock__** folder or in tests. In my case the problem was fixed by modifying mocks in **__mock__** folder like this:
```
jest.mock('react-dom', () => ({
   ...
    __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED: {
        Events: []
    }
}));
```

**Comment by ljharb** [comment]
I'm going to close this, but will be happy to reopen it if @andysmith415 can provide a repro case.

**Comment by andysmith415** [comment]
Thanks @prishedko for the tip, it turned out that I had previously mocked `react-dom` and hadn't defined some of the internals that `react-dom` uses. Removing that mock got up and running. Sorry about that!

**Comment by euclidesdry** [comment]
> @andysmith415 I had the same problem when **react-dom** was mocked. Please looked at mocks of **react-dom** in ****mock**** folder or in tests. In my case the problem was fixed by modifying mocks in ****mock**** folder like this:
> 
> ```
> jest.mock('react-dom', () => ({
>    ...
>     __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED: {
>         Events: []
>     }
> }));
> ```

It solved My Issues too!
