### ISSUE TITLE
Enzyme v3 .findWhere() returns empty wrappers.

### ISSUE THREAD

**Issue by Ranguro** [airbnb/enzyme#1993]
### Current behavior

When running `.findWhere()` it returns empty wrapper for some scenarios.

### Expected behavior

`.findWhere()` should return null instead of an empty wrapper.

### Your environment

Currently using:
 ```
 "enzyme": "^3.8.0",
 "enzyme-adapter-react-16": "^1.8.0",
 "enzyme-to-json": "^3.3.5"
```
with React 16.7.0 and Webpack 1.15.0

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  ^3.8.0
| react               | ^16.7.0
| react-dom           | ^16.7.0
| react-test-renderer | ^16.7.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

#### Scenario

https://gist.github.com/Ranguro/bf1f2e95201fcd9cff32e2de86b13705

**Comment by sstern6** [comment]
Thanks for the report!

Why do you expect it to be null instead of being an empty wrapper?  Also, do you expect the return value of wrapper.findWhere to be null or if the callback item doesnt have a length to return null?
