### ISSUE TITLE
.findWhere failing to parse all nodes in wrapper

### ISSUE THREAD

**Issue by MikaelCarpenter** [airbnb/enzyme#1994]
### Current behavior
I have a component that does conditional rendering in the form of: 
```jsx
<header>
  <h1>{title}</h1>
  {subtitle && <div>{subtitle}</div>}
</header>
```
_Note: subtitle is defaulted to an empty string, so that block is returning an empty string_

When that component is inside of a `ReactWrapper` and I use `.findWhere`, the function doesn't get past that conditional render.

### Expected behavior
I would expect `.findWhere` to be able to see that empty string and still navigate to the next node in the wrapper

Now, I'd say this could be considered user error, since we can write that condition differently and get the test to pass. However, it also seems strange to me that `findWhere` would get stuck on this. If this isn't something you consider an issue just let me know 👍 Otherwise I can take a crack at fixing it if y'all are cool with that.

### Your environment
You can see this replicated in [this codesandbox](https://codesandbox.io/s/jp4vnqy2n3?expanddevtools=1&module=%2Fsrc%2FHello.js&previewwindow=tests)

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 16.7.0
| react-dom           | 16.7.0
| adapter (below)     | 1.8.0

#### Adapter

- [x] enzyme-adapter-react-16

#### Related issues
I saw these two issues that seemed like they might be relevant, but after looking into it I don't think they are quite related:
#1825 
#1993

**Comment by sstern6** [comment]
@MikaelCarpenter thanks for the report and the PR.  I think youre right, it shouldnt fail at `subtitle`.  Given that React is supporting larger and larger "empty" values i think adding  the ever growing list would be ideal.  Ill leave more relevant comments on PR.
