### ISSUE TITLE
containsMatchingElement not returning true when element exists

### ISSUE THREAD

**Issue by luskin** [airbnb/enzyme#1998]
When using `mount` it seems that `containsMatchingElement` is not performing correctly:

*NavigationBarContainer*
```
export class NavigationBarContainer extends React.Component {

  handleEvent = (event: NavigationBarEvent) => {
    console.log('Event')
  }

  render() {
    return (
      <ErrorBoundary>
        <Wrapper>
          <Routes handleEvent={this.handleEvent} />
        </Wrapper>
      </ErrorBoundary>
    )
  }
}
```

*Test*
```
describe.only('<NavigationBarContainer />', () => {
  it('should render a company logo, routes and user menu', () => {
    const renderedComponent = mount(
      <ThemeProvider theme={theme}>
        <NavigationBarContainer />
      </ThemeProvider>,
    )

    console.log(renderedComponent.debug())
    const eventHandlerSpy = jest.fn()
    expect(
      renderedComponent.containsMatchingElement(
        <Routes handleEvent={eventHandlerSpy} />,
      ),
    ).toEqual(true)
  })
})
```

*Debug Output*
```
      <ThemeProvider theme={{...}}>
        <NavigationBarContainer>
          <ErrorBoundary>
            <styled.header>
              <StyledComponent forwardedComponent={{...}} forwardedRef={{...}}>
                <header className="sc-bdVaJa gLXwrC">
                  <Routes handleEvent={[Function: handleEvent]}>
... etc
```

You can see that in the debug Routes with a handleEvent prop is clearly in the dom tree, however it always returns false

```
    expect(received).toEqual(expected)

    Expected value to equal:
      true
    Received:
      false

      38 |         <Routes handleEvent={eventHandlerSpy} />,
      39 |       ),
    > 40 |     ).toEqual(true)
         |       ^
      41 |   })
      42 | })
      43 |
```

We have tried all of the different contains methods as well as using shallow for this test, everything returns false. 

### Current behavior

containsMatchingElement is returning false for a matching elemnt

### Expected behavior

containsMatchingElement should return true for a matching element

### Your environment
Mac OS 10.14

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

enzyme: 3.8.0
react: 16.6.0
#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
In this case, it's because `containsMatchingElement` is determining that `jest.fn() !== theActualPropValue`. If you're trying to find out if there's a `Routes` with a `handleClick` that's a function, you'll have to `.filter(Routes).findWhere(x => typeof x.prop('handleClick') === 'function')`.
