### ISSUE TITLE
html() breaks on a mounted Fragment

### ISSUE THREAD

**Issue by matt-gresham** [airbnb/enzyme#2002]
### Current behavior

Calling the html() method (and other methods) on a mounted component which is a multi-element Fragment causes a TypeError. This appears to be an issue that has been introduced with enzyme-adapter-react-16 v1.9.0, as downgrading to v1.8.0 produces the expected behaviour.

### Expected behavior

The component ought to have mounted correctly and it should be possible to call methods on it without producing TypeErrors.

### Your environment

See this [example on codesandbox](https://codesandbox.io/s/6v80l2wn5n).

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 16.7.0
| react-dom           | 16.7.0
| react-test-renderer | N/A
| adapter (below)     | 1.9.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'm a bit confused; we have [passing tests](https://github.com/airbnb/enzyme/blob/master/packages/enzyme-test-suite/test/ReactWrapper-spec.jsx#L5171-L5199) for this exact case.

**Comment by ljharb** [comment]
Ah, I think I see the issue; these methods are returning `undefined` in this case when paired with v1.9.0 of the adapter.
