### ISSUE TITLE
Enzyme 2 to 3 upgrade: shallow() with numeric child literal gives unexpected results

### ISSUE THREAD

**Issue by cnatale** [airbnb/enzyme#2019]
### Current behavior
After upgrading my project's environment from Enzyme 2 to 3, running the following code:
```
      it.only('does a sanity check', function() {
        const component = shallow(<div>{2}</div>);
        console.log(component.debug());
      });
```

produces this output:
```
LOG LOG: '<div>
  0
  0
</div>'
```

Increasing the numeric literal value to 10 results in hundreds of 0's. If I set the numeric literal to be above 50 or so, the test server actually times out. To be clear, the timeout occurs whether console.log() is included in the code or not. The shallow render is what causes it.

Also, running the test with mount() instead of shallow() produces expected results.

### Expected behavior

I should get the following output from the aforementioned console.log():
```
LOG LOG: '<div>
  2
</div>'
```

Additionally, using larger literal values that roughly 50 should not cause a timeout of the test runner.

### Your environment
OSX v10.11.6
Node v8.12.0
NPM v6.4.1

Test runner: Karma with Mocha, v1.3.0 (using PhantomJS)

#### API

- [X ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               | 15.6.2
| react-dom           | 15.6.2
| react-test-renderer | 15.6.1
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [X] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
So, the div shouldn't be logged, because in shallow, the wrapper is what the component *renders* - in other words, it should be a wrapper around `2`. However, the repeated zeroes are an issue - looking into it.

**Comment by ljharb** [comment]
hmm, oddly enough i'm getting the div, and the child, in my test. I'll keep looking.

**Comment by ljharb** [comment]
My similar test is passing; is there any mocha setup you're doing, or any packages that might be modifying enzyme?

**Comment by cnatale** [comment]
I'm using React 15 Adapter v1.3.0. I'm not doing anything with Mocha other than pointing to it in my Karma config.

Main karma.config looks like this:
```
/* eslint-disable import/no-commonjs */
const webpackTestConfig = require('./webpack.config.test.babel.js');
const wrapWebpackWithEnzymeConfig = require('./karma.webpack.enyzme.js');
module.exports = function(config) {
  config.set({
    basePath: '',

    frameworks: ['mocha'],

    browsers: ['PhantomJS'],

    reporters: ['spec'],

    autoWatch: true,

    singleRun: false,

    port: 3002,

    files: [
      // Polyfill PhantomJS
      'node_modules/sinon/pkg/sinon.js',
      'node_modules/phantomjs-polyfill/bind-polyfill.js',
      'node_modules/phantomjs-polyfill/bind-polyfill.js',
      'node_modules/core-js/client/core.min.js',
      // Test bootstrap (e.g. chai.use(sinon-chai))
      'tests/index.js',
      'tests/tests.context.js',
      'tests/enzyme.js'
    ],

    preprocessors: {
      'tests/index.js': ['webpack'],
      'tests/enzyme.js': ['webpack'],
      'tests/tests.context.js': ['webpack']
    },

    client: {
      captureConsole: true,
      mocha: {
        ui: 'bdd',
        reporter: 'html'
      }
    },
    // karma watches the test entry points
    // (you don't need to specify the entry option)
    // webpack watches dependencies
    webpack: wrapWebpackWithEnzymeConfig(webpackTestConfig),
    webpackMiddleware: {
      noInfo: true
    }
  });
};
```

tests.index.js content:
```
const root = window;
import chai from 'chai';
chai.config.includeStack = true;
chai.config.truncateThreshold = 1000; // Lenient truncation
import sinonChai from 'sinon-chai';

// Exports
root.expect = chai.expect;

// Plugins
chai.use(sinonChai);

// Flag to work around dependency issues in tests.
root.isTestSuite = true;

before(() => {
  sinon.stub(console, 'error', warning => {
    throw new Error(warning);
  });
});
```

tests/enzyme.js looks like this:
```
/* eslint-disable */
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-15';

// Configure Enzyme for the appropriate React adapter
// Enzyme.configure({ adapter: new Adapter() });
Enzyme.configure({ adapter: new Adapter() });

// Re-export all enzyme exports
export * from 'enzyme';
```
...and then I'm importing this module into individual modules.

tests.context.js just sets the files to test against:
```
import moment from 'moment-timezone';
moment.tz.setDefault('UTC');

// Pointers to spec files, used by Karma
const context = require.context('.', true, /.+\.spec\.jsx?$/);
const keys = context.keys();
keys.forEach(key => {
  context(key);
});
```

**Comment by ljharb** [comment]
hmm - it's possible there's issues with karma, specifically. Have you read through https://github.com/airbnb/enzyme/blob/master/docs/guides/karma.md ?

**Comment by cnatale** [comment]
Yeah. I think I've set it up properly, but could have messed something up. I'll post any updates.

**Comment by cnatale** [comment]
The problem turned out to be caused by having this file in my files karma.conf.js files array: `'node_modules/core-js/client/core.min.js'`. The version in question is ^2.5.5. It wasn't being used in the current incarnation of the app, so I got rid of it and the problem went away. Closing this issue. Thanks for the quick help!

**Comment by ljharb** [comment]
That's very troubling, since that's used in babel-polyfill :-/ but at least you figured it out!
