### ISSUE TITLE
How do I resolve css that is required in with webpack

### ISSUE THREAD

**Issue by mjhamm75** [airbnb/enzyme#202]
I am trying to test a component that `require`'s in some `css`.  Here is what the component looks like:

```
import '!style!css!sass!./DropdownContainer.scss';

export default class DropdownContainer extends Component {
	render() {
		return (
				<h1>DropdownContainer</h1>
		)
	}
}
```

Here is my test:

```
const wrapper = shallow(<DropdownContainer />);
tape('render test', t => {
	t.equal(wrapper.type(), 'h1');
	t.end();
});

```
But `enzyme` does not run the `component` through `webpack` and everything blows up on the `css` import.  Here is my error:

`Error: Cannot find module '!style!css!sass!./DropdownContainer.scss'`

How do I resolve this?

**Comment by ljharb** [comment]
Could you run your tests on the build output (since that's what gets shipped to production anyways)?

**Comment by mjhamm75** [comment]
I could, but what I send to production is a bundle of lots of stuff.  I want to be able to test this one component.  Is there any other way?

**Comment by ljharb** [comment]
I'm not sure how - if you're using syntax that only webpack understands, webpack has to process the code before anything else can work with it.

**Comment by blainekasten** [comment]
You generally can hook a pre processor into whatever testing framework you
use. Jest has one, I assume mocha and other frameworks have one.

**Comment by lelandrichardson** [comment]
This question doesn't really have anything to do with enzyme... Enzyme isn't determining what environment you're running your tests with. You will need to use webpack to run the tests, just like you are using it to bundle your source code.

You may want to look at this project as an example: https://github.com/lelandrichardson/enzyme-example-karma-webpack

**Comment by CodyReichert** [comment]
I know this closed, but in case anyone else coming across this - you just need to make sure you're using `extract-text-webpack-plugin`<sup>[1]</sup>  in your test suite's webpack configuration. Eg,

    ....
    plugins: [
        new ExtractTextPlugin('./test-bundle.css')
    ],
    ....

[1] - https://github.com/webpack/extract-text-webpack-plugin

**Comment by vs-zhang** [comment]
I found out this nice blog http://pebblecode.com/blog/react-redux-unit-testing/ about how to setup karma with webpack to preprocess the file first before testing.
