### ISSUE TITLE
Regression on 'componentDidUpdate' not being called when calling 'setProps' on shallow wrapped component

### ISSUE THREAD

**Issue by BertrandFritsch** [airbnb/enzyme#2020]
Calling `setProps` on a shallow wrapper may result in not calling `componentDidUpdate` of the wrapped component. It's the case when the state depends on a prop and when that specific `setProps` call does change the state. If that call doesn't change the state, `componentDidUpdate` is called. I suspect this is a regression of #2007. It worked fine in version 3.8.0

### To reproduce

```javascript
import { shallow } from 'enzyme';
import * as React from 'react';

class DummyComp extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = { stateCounter: 0 };
  }

  static getDerivedStateFromProps(nextProps) {
    // set stateCounter if asked for
    if (nextProps.propCounter > -1) {
      return {
        stateCounter: nextProps.propCounter
      };
    }

    return null;
  }

  componentDidUpdate() {
    console.log('Counter:', this.state.stateCounter);
  }

  render() {
    return <p>Counter: { this.state.stateCounter }</p>;
  }
}

describe('Counter', () => {
  it('should call cDU on setProps', () => {

    const wrapper = shallow(<DummyComp propCounter={ 0 } />);

    const cDUSpy = jest.spyOn(wrapper.instance(), 'componentDidUpdate');

    // does not change the state, so cDU will be called
    wrapper.setProps({ propCounter: -1 });

    expect(cDUSpy).toBeCalledTimes(1);

    // does change the state, cDU should be called anyway
    wrapper.setProps({ propCounter: 1 });

    expect(cDUSpy).toBeCalledTimes(2); // this test will fail
  });
});
```

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.2
| react-dom           | 16.8.2
| react-test-renderer | 16.8.2
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
cc @peanutenthusiast; see also https://github.com/airbnb/enzyme/pull/2007#issuecomment-464745567

**Comment by peanutenthusiast** [comment]
@ljharb thanks for the cc will look into this.

**Comment by ljharb** [comment]
@peanutenthusiast i'm honestly not sure; the first thing ideally would be a PR that contains the failing test case, and we can iterate from there?
