### ISSUE TITLE
`memo` does not work with class components

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#2025]
Followup from #1914 and #1875.

See https://github.com/airbnb/enzyme/pull/1914#issuecomment-467244909 and 
https://github.com/airbnb/enzyme/pull/1914/commits/6b3274b72dbed367acf1fc985dd0a9b873a35b0b; once https://github.com/facebook/react/issues/14807#issuecomment-462147431 is resolved, we'll need to revisit these tests.

**Comment by kachkaev** [comment]
https://github.com/facebook/react/issues/14807 seems to be closed now

**Comment by ljharb** [comment]
hmnm, this already seems revisited here: https://github.com/airbnb/enzyme/blob/master/packages/enzyme-test-suite/test/shared/methods/find.jsx#L918 - but I suspect that's the cause of #2113. Closing in favor of that.
