### ISSUE TITLE
.find for full DOM rendering

### ISSUE THREAD

**Issue by clouddra** [airbnb/enzyme#203]
In the documentation for [`.find`](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/find.md) for full rendering, it says that we are able to find for sub components.

e.g.
```jsx
const wrapper = mount(<MyComponent />);
expect(wrapper.find('Foo')).to.have.length(1);
```
From my testing, it doesn't seem like this is possible since the components are recursively rendered down to leaves. 

Anyone observing this as well?  I suspect that the documentation might be wrong...

**Comment by lelandrichardson** [comment]
@clouddra the documentation is not wrong. The render tree is composed of virtual nodes as well as non-virtual nodes that render to actual DOM.

You can actually have a very full and large render tree that renders nothing but a single `<div>`.

For instance, let's say we have:

```jsx
const Foo = () => <div />;
const Bar = () => <Foo />;
```
rendering `<Bar />` ends up as a single DOM node on the page, but the actual render tree is a linear graph composed of: `Bar -> Foo -> 'div'`

**Comment by clouddra** [comment]
@lelandrichardson Yup that would be how the render tree works. Suppose we have 
```jsx
const Foo = () => <div/>;
const Bar = () => <div> <Foo/> </div>;
```
The documentation says that we can do 
```jsx
expect(mount(<Bar/>).find('Foo')).to.have.length(1);
```
for full rendering.

`.find('Foo')` wouldn't have made sense for **full rendering** since `<Bar/>` ends up as a single DOM node on the page.

**Comment by lelandrichardson** [comment]
@clouddra well actually, your example ends up as a single div inside of another div.  But in any case, the example you are showing *should* work and in fact *does*.

If you are finding that this does not work this is probably because of the string-based selector you are using `'Foo'`, which requires that the component you are looking for has a `.displayName` or `.name` property of `'Foo'`. If your components are arrow functions this will not work. Named function expressions and ES6 classes will work though.  Either way, I would recommending finding composite components by references to their constructor instead: `wrapper.find(Foo)` rather than `wrapper.find('Foo')`.

**Comment by clouddra** [comment]
@lelandrichardson I did try a simple example using ES6 classes
```jsx
export default class Test extends React.Component {
  render() {
    return (
      <div>
        <div>Test 1</div>
        <Test2/>
      </div>
    );
  }
}
```

```jsx
export default class Test2 extends React.Component {
  render() {
    return <div>Test 2</div>;
  }
}
```

```jsx
describe.only('FeedbackPage', () => {
    it('renders Test2', () => {
      const render = mount(<Test />);
      expect(render.find('Test2')).to.have.length(1); //got 0
    });
});
```
I may be doing something wrong here?

**Comment by ljharb** [comment]
@clouddra what happens if you import Test2 into your test, and `.find(Test2)`? Passing a component name into "find" is discouraged.

**Comment by lelandrichardson** [comment]
@clouddra can you try manually adding `Test2.displayName = 'Test2';`. Your build tool (or browser you're testing this in) may not be automatically creating the `.displayName` or `.name` property to the component.

Using the function reference is really the preferred way to do this though. The stringified displayName is much more brittle.

**Comment by clouddra** [comment]
@lelandrichardson cool. It works if i pass in a reference. Setting the `displayName` however does not seem to work for me. Thanks for the help. I will close the issue.
