### ISSUE TITLE
ForwardRef displayName is ignored when JSX is used in prop

### ISSUE THREAD

**Issue by tvooo** [airbnb/enzyme#2032]
### Current behavior

When using a forwardRef-generated component in an enzyme wrapper, the generated snapshot calls it "ForwardRef" instead of the displayName we've set. This only happens, however, for JSX passed in a prop.

#### Here's an example

Component in question:

```js
const Icon = React.forwardRef(props => <span {...props} />);

Icon.displayName = 'Icon';
```

Test:

```js
const wrapper = mount(
  <div someProp={<Icon id="this-does-not-work" />}>
    <Icon id="this-works-fine" />
  </div>
);

expect(wrapper).toMatchSnapshot();
```

Snapshot:

```
exports[`renders`] = `
<div
  someProp={
    <ForwardRef
      id="this-does-not-work"
    />
  }
>
  <Icon
    id="this-works-fine"
  >
    <span
      id="this-works-fine"
    />
  </Icon>
</div>
`;
```

### Expected behavior

I expect the displayName to be honored even when the component is passed in a prop. Like so:

```
exports[`renders`] = `
<div
  someProp={
    <Icon
      id="this-does-not-work"
    />
  }
>
  <Icon
    id="this-works-fine"
  >
    <span
      id="this-works-fine"
    />
  </Icon>
</div>
`;
```

#### API

- [x] shallow
- [x] mount
- [?] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.6.0
| react               | 16.7.0
| react-dom           | 16.7.0
| react-test-renderer | 16.5.0
| adapter (below)     | (16) 1.7.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
enzyme has no snapshot support, and I don't recommend them - what does `.debug()` print out?

Also, note that `react-test-renderer`, `react`, and `react-dom` all must have the *precise same* minor version for things to work properly.

**Comment by tvooo** [comment]
Thanks for the quick response. `.debug()` prints out the following:

```
<div someProp={{...}}>
  <Icon id="this-works-fine">
    <span id="this-works-fine" />
  </Icon>
</div>
```

That `...` is not inserted by me; this is literally what `.debug()` prints.

I followed your suggestion and fixed the versions of `react-test-renderer`, `react-dom`, and `react` to `16.7.0`; the result was still the same.

I also used `enzyme-to-json` as a serializer, with the following result:

```
<div
  someProp={
    <ForwardRef
      id="this-does-not-work"
    />
  }
>
  <span
    id="this-works-fine"
  />
</div>
```

I've got no clue how enzyme works internally; but it seems that it does not walk into branches (or treats such branches differently) where a React element is passed as prop.

I hope that helped a bit. Don't you recommend snapshots in general, or just trying to use them with enzyme wrappers? What do you recommend instead?

**Comment by ljharb** [comment]
There's a verbose option that will print the someProp details - try `wrapper.debug({ verbose: true })`?

I don't recommend snapshots in general - snapshot testing is inherently brittle, and its only value is when you're trying to do a refactor that changes nothing about the snapshot (eg, nothing about the component hierarchy or the html) - and otherwise, people just rubber stamp changes rather than properly reviewing them.

**Comment by tvooo** [comment]
Thanks for the hint, that indeed helped to get better insight:

```
<div someProp={{ $$typeof: Symbol(react.element), type: { $$typeof: Symbol(react.forward_ref), render: [Function], displayName: 'Icon' }, key: null, ref: null, props: { id: 'this-does-not-work' }, _owner: null, _store: {} }}>
  <Icon id="this-works-fine">
    <span id="this-works-fine" />
  </Icon>
</div>
```

The `displayName` is clearly there, so I'd seek the issue with the serializers (both jest's builtin `pretty-format` and the 3rd party `enzyme-to-json` seem to ignore it). Thanks for your input, really appreciated. I will close this issue.

Regarding snapshot testing: we are maintaining a component library as part of our design system, and snapshot testing has been incredibly valuable for our SFCs. I can imagine that people just rubber stamping changes becomes an issue when the changes are too big; we had that happen too. Doing more atomic changes helped us in this regard. In the end, just use what works best for your team :-)
