### ISSUE TITLE
React suspense Error: Method “props” is meant to be run on 1 node. 0 found instead.

### ISSUE THREAD

**Issue by DonikaV** [airbnb/enzyme#2033]
#### API

- [ ] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9
| react               |  16.8.3
| react-dom           | 16.8.3
| react-test-renderer | 
| enzyme-adapter-react-16      |  1.10.0

I updated react and test libraries today . App works fine, lazy loading etc.. but my tests are failing..
```

 it("Should render", async () => {
        const wrapper = shallow(<MyParentComponent {...props} />);
        expect(wrapper.find("MyChildrenComponent").props()).toEqual({HERE PROPS})
```

/// MyParent component render

```
render() {
        return (
            <div>
                <React.Suspense fallback={<Spinner/>}>
                    <MyChildrenComponent/>
```

But i have error 

> Error: Method “props” is meant to be run on 1 node. 0 found instead.

**Comment by ljharb** [comment]
enzyme does not currently support `Suspense`; closing in favor of #1917.

**Comment by DonikaV** [comment]
There are any workaround to fix this? Thanks in advance :)

**Comment by ljharb** [comment]
No, the workaround is to not use Suspense yet.
