### ISSUE TITLE
Check if Component is called with expected props

### ISSUE THREAD

**Issue by milap1296** [airbnb/enzyme#2037]
**Is your feature request related to a problem? Please describe.**
Consider my component goes something like this -> 
```javascript
class Parent extends React.Component {
  ...
  render() {
    return (
        <React.Fragment>
                 <Child
                        childProp1= {valueGetter()}
                        childProp2= {valueGetter()}
                        childProp3= {valueGetter()}
                 />
        </React.Fragment>
   )
  }
}
```

Now, I need to test that whenever I render the Component `A`, I am able to call the component `B` with some expected props.

For now my test will go something like this -> 
```javascript
const wrapper = shallow(
      <Parent
        {...props}
      />
    ).find(Child);
const childProps = wrapper.props();
expect(childProp1).toBe(expectedChildprop1);
expect(childProp2).toBe(expectedChildprop2);
expect(childProp3).toBe(expectedChildprop3);
```

**Describe the solution you'd like**
It becomes very boring and lengthy to test each components props in such a way, instead we can have something like and let enzyme internally tell me the diff. 

```javascript
wrapper.hasProps({
   childProp1: expectedChildprop1,
   childProp2: expectedChildprop2,
   childProp3: expectedChildprop3,
})
```

**Describe alternatives you've considered**
For now I have made a generic function for all my tests which takes wrapper props and propsToCheck as it's arguments and tells me whether they are present or not.

**Thanks**

**Comment by ljharb** [comment]
You can already do this:
```js
expect(wrapper.props()).to.deepEqual({
   childProp1: expectedChildprop1,
   childProp2: expectedChildprop2,
   childProp3: expectedChildprop3,
});
```
(mocha, jest, and most test runners support some form of "deep equal" already). Does that meet your needs?

**Comment by milap1296** [comment]
No I dont need to check all the `props` for the component, `deepEqual` won't suffice my requirements since I need to check if `subset of props` is passed to a component!

Let's say I have
```javascript
<Child
       childProp1= {valueGetter()}
       childProp2= {valueGetter()}
       childProp3= {valueGetter()}
       {...extraProps}
/>
```
But I need to check just a subset of the props the component is rendered with!

**Comment by ljharb** [comment]
@milap1296 sure! that's also something all test frameworks tend to have a solution for. In mocha/chai, it'd be something like:
```js
expect(wrapper.props()).to.have.properties({
   childProp1: expectedChildprop1,
   childProp2: expectedChildprop2,
   childProp3: expectedChildprop3,
});
```

**Comment by milap1296** [comment]
Sure thanks, as I can see the plugin `chai-subset` is capable of doing so, since they don't support `to.have.properties` in chai.

Closing for now, thanks @ljharb :)

**Comment by ljharb** [comment]
`.to.have.keys`, maybe? It's definitely supported in chai.
