### ISSUE TITLE
setState with function component wrapper 

### ISSUE THREAD

**Issue by eps1lon** [airbnb/enzyme#2043]
### Current behavior
`wrapper.find('DisplayNameOfClassComponent').state()` triggers ` Error: ReactWrapper::state() can only be called on class components` when `wrapper` is a function component even though `DisplayNameOfClassComponent` is a class component and has state. 

### Expected behavior
Same behavior if `wrapper` is a class component or `DisplayNameOfClassComponent` itself i.e. all 3 test in the codesandbox pass.

### Your environment
- codesandbox PROD-1551955038-1564be28 https://codesandbox.io/s/6l5ym51rzr

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.3
| react-dom           | 16.8.3
| react-test-renderer | unknown
| adapter (below)     | 1.10.0

#### Adapter

- [ ] enzyme-adapter-react-16
- [x] enzyme-adapter-react-16.3@1.10.0
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
What version of the 16.3 adapter are you using?

**Comment by eps1lon** [comment]
> What version of the 16.3 adapter are you using?

1.10.0. Updated the initial post. Dependency version can be verified in the codesandbox.
