### ISSUE TITLE
Tests fails since Jest version 24.5.0 shallow: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kaligrafy** [airbnb/enzyme#2049]
I get an ReferenceError: document is not defined
at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1158:7)
when testing a component with shallow since I updated Jest.

Also, I get this warning:
Warning: It looks like you called TestUtils.act(...) in a non-browser environment. If you're using TestRenderer for your tests, you should call TestRenderer.act(...) instead of TestUtils.act(...).

### Current behavior
Test fails

### Expected behavior
Test should not fail

#### API

- [x] shallow

#### Version
| enzyme  |  3.9.0

#### Adapter

- [x] enzyme-adapter-react-16

**Comment by albertstill** [comment]
Seeing the same error, it was caused when going from `enzyme-adapter-react-16@1.10.0` to `enzyme-adapter-react-16@1.11.0`. Fix was to lock the version down, until they patch release 1.11.

**Comment by ljharb** [comment]
Fixed in e5e2a1fb3926d43c6fde207f4598759eb7ab5cd7; will be released in v1.11.2 of he react 16 adapter.
