### ISSUE TITLE
Fragments in ReactWrapper are not rendered with html() if children are functions

### ISSUE THREAD

**Issue by atsikov** [airbnb/enzyme#2052]
I believe this issue is related to https://github.com/airbnb/enzyme/issues/2006 not being fully fixed.

This issue only affects `ReactWrapper`, `ShallowWrapper` seems to work fine.

### Current behavior
`.html()` doesn't show children created from functions when component is wrapped with fragment.

### Expected behavior
`.html()` returns exact markup if rendered children are either classes or functions.

### Your environment
https://codesandbox.io/s/032mpxq6rv

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.7.0
| react-dom           |  16.7.0
| react-test-renderer |  
| adapter (below)     | 1.11.2

#### Adapter

- [x] enzyme-adapter-react-16
- [x] enzyme-adapter-react-16.3
- [x] enzyme-adapter-react-16.2
- [x] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by atsikov** [comment]
Tried a few `enzyme-adapter-react-16` versions, looks like this issue is a regression `1.8.0` -> `1.9.0`

**Comment by ljharb** [comment]
Thanks, this was a very helpful repro.

**Comment by atsikov** [comment]
@ljharb, as I can see, fix was released, but this test case still fails with `enzyme-adapter-react-16@1.12.1`

**Comment by atsikov** [comment]
Repro fork with updated adapter version
https://codesandbox.io/s/n9v3j8p164

**Comment by ljharb** [comment]
@atsikov it has not yet been released in enzyme proper; it will be included in the next one.

**Comment by ljharb** [comment]
[v3.10.0](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.10.0) has now been released.
