### ISSUE TITLE
Code coverage badge problem

### ISSUE THREAD

**Issue by allevo** [airbnb/enzyme#2053]
For the time being the code coverage is 10. Why?

### Current behavior

The coverage is 10%

### Expected behavior

The coverage reported could not be right.

### Your environment

master of Github

**Comment by ljharb** [comment]
Thanks, our coveralls setup has been having some issues.

**Comment by ljharb** [comment]
Fixed in 12f324abbfcf362156e3909b99a095ed876a6841.
