### ISSUE TITLE
support unstable_Profiler

### ISSUE THREAD

**Issue by eps1lon** [airbnb/enzyme#2054]
### Current behavior
mounting a tree using `React.unstable_Profiler` throws
`Enzyme Internal Error: unknown node with tag 12`

https://codesandbox.io/s/jxjoj2p0v

### Expected behavior
`mount(<React.unstable_Profiler id="test" onRender={id => console.log(id)} />);` does not throw

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.4
| react-dom           | 16.8.4
| react-test-renderer | 16.8.4
| adapter (below)     | 1.11.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

As far as I can tell enzyme is simply not supporting this (yet). Happy to start working on a PR that adds this to the mount API. 

I'm personally not that interested in shallow rendering. I guess we would need to establish first how the Profiler should work with shallow rendering.

This should also be included in #1553.

**Comment by ljharb** [comment]
You’re correct, it doesn’t yet. A PR would be great!

**Comment by ljharb** [comment]
(and yes, to be added to mount we’d need to decide what the behavior is for shallow, and ideally it’d be identical)

**Comment by ljharb** [comment]
I'd say this is closed by #2055.
