### ISSUE TITLE
Call to this.props... in mounted components updated immediately after update to props, not in browser

### ISSUE THREAD

**Issue by rajjeet** [airbnb/enzyme#2062]
### Summary of Issue
Within a click handler, I invoke a Redux action which resulting in props changing for the component where the action was invoked. Right after the Redux action call, I update the component state with a prop that should have been updated (still within the same method). When testing using enzyme's mount, the prop updates right after the call, while in the browser the prop doesn't update. I'm seeing two different outcomes (browser vs. jsdom/enzyme). 

Here's my codebase that reproduces this scenario: [enzyme-prop-update-repoduce](https://github.com/rajjeet/enzyme-prop-update-repoduce)

### Current behavior
When the component's props update after a method call, the component sees the new props in the jsdom via enzyme's mount test right away. In the browser, the component sees the old stale prop. 

### Expected behavior
Expect the way props update to be identical in browser vs jsdom

### Your environment
Node environment: v8.11.3
[Javascript Libraries:](https://github.com/rajjeet/enzyme-prop-update-repoduce/blob/enyzme-prop-update/package.json)

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version
[See codebase package.json] (https://github.com/rajjeet/enzyme-prop-update-repoduce/blob/enyzme-prop-update/package.json)
#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by rajjeet** [comment]
Fixed my own issue. I wrapped the redux action call with a promise. 
I replaced:
```
addToGlobalCounter = () => {
   this.props.addToGlobalCounter();
   this.setState({globalCounterCopy: this.props.globalCounter})
};
```
with the following...
```
addToGlobalCounter = () => {
        this.addToGlobalCounterAsync().then(() => {
            this.setState({globalCounterCopy: this.props.globalCounter})
        });
  };

addToGlobalCounterAsync = () => {
   return new Promise((resolve) => resolve(this.props.addToGlobalCounter()));
};
```

This ticket probably was irrelevant to Enzyme, I will close this now.

**Comment by ljharb** [comment]
Either way I’d suggest avoiding functions in class fields; prefer constructor-bound or field-bound instance methods. Glad you figured it out!
