### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by kevgathuku** [airbnb/enzyme#207]
Hello,
I am getting this error when trying to use enzyme with webpack and jest
I have noticed that this happens when I make the changes to my `package.json` file as recommended in https://github.com/airbnb/enzyme/blob/master/docs/guides/jest.md
The full error is:
```
● Runtime Error
TypeError: Super expression must either be null or a function, not undefined
```

`package.json` contents:
```
"jest": {
    "scriptPreprocessor": "<rootDir>/utils/preprocessor.js",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/react-dom",
      "<rootDir>/node_modules/react-addons-test-utils",
      "<rootDir>/node_modules/fbjs",
      "enzyme",
      "cheerio",
      "htmlparser2",
      "lodash",
      "domhandler",
      "object.assign",
      "define-properties",
      "function-bind",
      "object-keys",
      "object.values",
      "es-abstract"
    ],
```

`webpack.config.js` contents:
```
externals: {
      'cheerio': 'window',
      'react/lib/ExecutionEnvironment': true,
      'react/lib/ReactContext': true
    }
```

**Comment by lelandrichardson** [comment]
@kevgathuku strange. are you able to get a stack trace for that error?  It would be helpful if we could tell which library the error was coming from (enzyme, or a dependency).

**Comment by kevgathuku** [comment]
Hello @lelandrichardson, thanks for your reply.
I'm not sure how to get the stack trace for the error, but I've noticed it occurs when I add any of the additional packages to the `unmockedModulePathPatterns` jest configuration section.

**Comment by kevgathuku** [comment]
I'm not sure I can provide additional info on this. `jest` verbose mode does not even display the error message shown above.
