### ISSUE TITLE
I am seeing missing PropTypes warning during tests when using the `containsMatchingElement` API.

### ISSUE THREAD

**Issue by josh08h** [airbnb/enzyme#2075]
### Current behavior
I am seeing missing PropTypes warning during tests when using the `containsMatchingElement` API.

Here is a minimal code example to get the warnings:

```
const AnotherComponent = ({ requiredProp }) => (
  <div>{requiredProp}</div>
);

AnotherComponent.propTypes = {
  exampleProp: PropTypes.string.isRequired
};

const MyComponent = () => {
  const someComputedValue = 'foo';
  return (
    <React.Fragment>
      <AnotherComponent someValue={ someComputedValue } />
    </React.Fragment>
  );
};

const wrapper = shallow(<MyComponent />);
expect(wrapper.containsMatchingElement(<AnotherComponent />)).toBe(true);
```
I can use `expect(wrapper.find(AnotherComponent).length).toBe(1)` but I'd really like to use the `containsMatchingElement` API in order to check other props are correct.

Any thoughts?

### Expected behavior
I would like to not see these warnings.

#### API

- [x] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.8.0
| react               |  16.8.1
| react-dom           | 16.8.1
| react-test-renderer | 16.8.1
| adapter (below)     | 16

#### Adapter

- [ ] enzyme-adapter-react-16

**Comment by ljharb** [comment]
If it's a required prop, then an element of it shouldn't be created without that prop - i'm not sure how to handle it, and i think using `find` is the proper way.

**Comment by josh08h** [comment]
Yes true and it won't be created without that prop. It's the contains matching element API call without that prop that causes the warnings.

I don't care what the prop is because I am checking that the component does *not* exist in the render tree.

**Comment by josh08h** [comment]
Ah I see my example is slightly wrong.

The assertion should be `expect(wrapper.containsMatchingElement(<AnotherComponent).to.not.be(true)`

**Comment by ljharb** [comment]
I'd definitely use `find` then; "matching" is about the props, not the component type.

**Comment by ljharb** [comment]
Actually specifically I'd probably use `expect(wrapper.exists(AnotherComponent)).toBe(false)`

**Comment by josh08h** [comment]
Ok perfect. This can probably be closed then. Thanks
