### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by Mohan-hari** [airbnb/enzyme#2077]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Please fill out the issue template; your title is nowhere near enough for us to be able to help.

Closing now; happy to reopen when the template is filled out.

**Comment by Mohan-hari** [comment]
TypeError: React.createContext is not a function

**Comment by ljharb** [comment]
That implies that you're not using a version of React that supports createContext.

Can you please fill out the issue template and describe the problem you're having?

**Comment by Mohan-hari** [comment]
there is  a form  component  i say ( Loginform.js) it it has a common style component called 
import { FormContentContainer } from '../../styles';
i  have created a new test component for test it says ( loginform.test.js) while running  test 
it showing error  is  console that test failed and says TypeError: React.createContext is not a function
why this errror

**Comment by ljharb** [comment]
Presumably because you're not using React v16.3+, which is what added support for createContext? I'm not sure how that's related to enzyme.

**Comment by tibic** [comment]
react 16.8 ,enzyme-adapter-react-16, i have same issue

**Comment by ljharb** [comment]
@tibic can you file a new issue for that, and fill out the template?

**Comment by tibic** [comment]
@ljharb Maybe it's not you. I need more validation. Thank you
