### ISSUE TITLE
wrapper.simulate() should be wrapped in ReactTestUtils.act()

### ISSUE THREAD

**Issue by mikesteele** [airbnb/enzyme#2084]
**Is your feature request related to a problem? Please describe.**
React 16.8 introduced <a href="https://reactjs.org/docs/test-utils.html#act">act()</a> to allow component interactions to be tested in a synchronous way.

**Describe the solution you'd like**
`wrapper.simulate()` should be wrapped in `act()` to ensure any state changes are resolved before proceeding.

**Describe alternatives you've considered**
```
act(() => {
  wrapper.simulate();
});
```

Though it's easy to forget `act`.

**Additional context**
I have a feeling this is already on your roadmap, but I couldn't find an issue about it.

**Comment by ljharb** [comment]
This is already addressed by #2034.

**Comment by mikesteele** [comment]
Out of curiosity, does that PR mean that any time a mounted component is rendered, it's wrapped in `act()`? Or only on `mount()`?

**Comment by ljharb** [comment]
Only mount mounts components, so yes to both?

Shallow rendering does not yet have an “act”, so that’s still unaddressed.

**Comment by jquense** [comment]
@ljharb sorry how does #2034 address this? It seems like that only wraps `mount()` calls in `act()`? `simulate()` should _also_ wrap calls, which is not what's happening on the latest published enzyme

**Comment by ljharb** [comment]
@jquense there's a bunch of unpublished stuff in enzyme, for one, but you're right that simulate probably isn't covered. A PR to fix that would be great.

`act` requires a DOM, and there's no `act` that works in a non-browser environment, so it's simply not an option for `shallow` at this time.

**Comment by mikesteele** [comment]
Could you re-open this issue then?

**Comment by ljharb** [comment]
It’s not fixable by enzyme until the shallow renderer provides an act, but sure.

**Comment by mikesteele** [comment]
But it's not fixable for `simulate` in full DOM rendering?

**Comment by ljharb** [comment]
Ah, true, that is fixable. PRs welcome :-) even if they only have test cases.

**Comment by mikesteele** [comment]
Thanks! I'll try to find time to contribute. I think this will be a huge improvement for users who need to force wrappers to update after simulating events to ensure that state updates are complete.

**Comment by jquense** [comment]
@mikesteele let me know if you don't have any time . i'd be happy to put something together as well

**Comment by ljharb** [comment]
Feel free to race each other to get something up :-p thanks in advance! <3

**Comment by mikesteele** [comment]
@jquense I probably won't have time for a few weeks, feel free to take this
