### ISSUE TITLE
After updating enzyme and adapter, all mount throw errors

### ISSUE THREAD

**Issue by kylemh** [airbnb/enzyme#2085]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### Current behavior
Run all my tests, with every test leveraging `mount()` failing with the following error:
```TypeError: (0 , _enzymeAdapterUtils.getNodeFromRootFinder) is not a function``` 

### Expected behavior
Run all my tests without error.

### Your environment
https://github.com/OperationCode/front-end
MacOS latest

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16 **Version 1.12.0**
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by maracuja-juice** [comment]
Just wanted to report the same error.

Here would be an example:

```
import * as React from 'react';

interface TestComponentProps {
}

export class TestComponent extends React.Component<TestComponentProps> {

    render() {
        return (
            <div className='TestComponent'>
                Test
            </div>
        );
    }
}
```

And two tests:
```
import * as React from 'react';
import { configure, mount, shallow } from 'enzyme';
import * as ReactSixteenAdapter from 'enzyme-adapter-react-16';
import {TestComponent} from './TestComponent';

configure({ adapter: new ReactSixteenAdapter() });

describe('TestComponent', () => {
   it('should contain a div with the correct class (shallow)', () => {
       const testComponent = shallow(<TestComponent />);

       expect(testComponent.find('.TestComponent')).toHaveLength(1);
      }
   );

   it('should contain a div with the correct class (mount)', () => {
       const testComponent = mount(<TestComponent />);

       expect(testComponent.find('.TestComponent')).toHaveLength(1);
   });
});
```

On 1.11.2 of the package "enzyme-adapter-react-16" both work. But on 1.12.0 the test with mount fails.

**Comment by ljharb** [comment]
Thanks, looks like I need to publish a patch that bumps the minimum version of adapter-utils. Coming shortly.

**Comment by ljharb** [comment]
Specifically, you can fix this by ensuring `enzyme-adapter-utils` is fully updated - if you have a lockfile, that might be causing the problem - but by publishing a patch, it'll force it to be updated.

**Comment by ljharb** [comment]
v1.12.1 of the adapter is published. Happy to reopen if that doesn't solve it.

**Comment by maracuja-juice** [comment]
Thanks for the fix. Works for me! 👍

**Comment by kylemh** [comment]
Absurdly fast. Thanks @ljharb
