### ISSUE TITLE
TypeError: Moment is not a function

### ISSUE THREAD

**Issue by GeorgeWL** [airbnb/enzyme#2088]
### When `import * as moment from 'moment';` with locale set, test returns TypeError
```js
import * as moment from 'moment';
require('moment/locale/de');
```
```js
TypeError: moment is not a function

      16 |         </div>
      17 |         <div className="changetime">
    > 18 |           <p>
      19 |             {moment(auditLogEntry.changeTime.toISOString()).format(
      20 |               'dddd, MMMM Do YYYY, HH:mm'
      21 |             )}

      at AuditLogLine.render (src/modules/auditLog/auditLogLine.tsx:18:11)
      at ReactShallowRenderer._mountClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:809:37)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:738:14)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:547:35
      at fn (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:546:68)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:265:22)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Object.<anonymous> (src/modules/__tests__/auditLogLine.test.tsx:30:7)
```
if change to `import moment from 'moment'; tests pass, but the component no longer renders when run in the actual browser, with a plethora of errors.
### Expected behavior
Should be agnostic to the import behavior used, and read the component shallow render without any issue.
Should be able to compare the value to see if it is the expected string from the supplied date prop
### Your environment
Windows 10
Node 10.15.3

#### API

- [ x ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.4.1
| react-dom           |  16.4.1
| react-test-renderer |  16.8.6
| adapter (below)     |  1.11.2
| jest | 22.4.2

#### Adapter

- [ x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This isn’t an enzyme problem, for one.

Second, `import * as moment` is *not* correct; note that if you’re using typescript, in order not to violate the js spec, you have to enable the synthetic imports and es module interop options, at which point you’d use `import moment`

As to why it’s different in node and the browser, are you using Babel to transpile for both? If not, do.

**Comment by hitunes** [comment]
did you try this ```import moment from 'moment-timezone';```

**Comment by GeorgeWL** [comment]
> did you try this `import moment from 'moment-timezone';`

we're not using moment-timezone, so no.

The solution in the end was to not require the language at all. but to instead do 
```js
import moment from 'moment'
moment.setLocale('de')
```

We were using moment purely for formatting of the Date to text, and using dates passed through from an api call (and faked with native `new Date()`.

**Comment by Ritin** [comment]
import * as temp from 'moment';
const moment = temp["default"];

**Comment by GeorgeWL** [comment]
which is bad practice and should be avoided at all costs.
