### ISSUE TITLE
Missing documentation for getWrappingComponent/invoke

### ISSUE THREAD

**Issue by ErnestoR** [airbnb/enzyme#2092]
### Current behavior

Docs are outdated and don't have latest API documentation and the following are missing: 

/docs/api/ShallowWrapper/invoke.md
/docs/api/ShallowWrapper/getWrappingComponent.md

/docs/api/ReactWrapper/invoke.md
/docs/api/ReactWrapper/getWrappingComponent.md

### Expected behavior

The following docs should be available:

https://airbnb.io/enzyme/docs/api/ShallowWrapper/invoke.html
https://airbnb.io/enzyme/docs/api/ShallowWrapper/getWrappingComponent.html
https://airbnb.io/enzyme/docs/api/ReactWrapper/invoke.html
https://airbnb.io/enzyme/docs/api/ReactWrapper/getWrappingComponent.html

#### API

- [X] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Nope, they shouldn't, because those features are not yet released. The published docs only match the last released version.

In other words, when the next version of enzyme is released, the docs will be updated, and until then, they won't be.

**Comment by ljharb** [comment]
[v3.10.0](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.10.0) has now been released.
