### ISSUE TITLE
wrapper.find(Component).instance().setState(STATE) sets state, doesn't update render

### ISSUE THREAD

**Issue by GeorgeWL** [airbnb/enzyme#2093]
### Current behavior
Setting a wrapped components instance state does show that it has updated the state when observed, but doesn't update the render when observed
```tsx
wrapper = mount(
          <Router>
            <IntlProvider locale="en">
              <ComponentExample
                userStore={userStore}
                lenderStore={lenderStore}
                history={history}
                location={history.location}
                match={match}
              />
            </IntlProvider>
          </Router>
        );
```
Test 
```tsx
wrapper
      .find(ComponentExample)
      .instance()
      .setState(TEST_STATE);
    expect(
      wrapper
        .find(ComponentExample)
        .instance()
        .state
    ).toEqual(TEST_STATE);
```
Result
```log
PASS
```
component snippet
```tsx
public state = {
     loaded:false
}
//other stuff like async componentDidMount, clickHandlers, etc.

public render(){
  const {
    loaded,
    //other state not mentioned here
  } = state;
  return (
    <div className='container'>
      {loaded &&
        (
          <div className='pageHeader'>
            {/* other children */}
          </div>
        )}
      <span>Loading</span>
    </div>
  )
}
```
TEST 2:
```tsx
 wrapper
      .find(ComponentExample)
      .instance()
      .setState(TEST_STATE);
    expect(
      wrapper
        .find(ComponentExample)
        .instance()
        .state
    ).toEqual(TEST_STATE);
    wrapper.update();
    expect(
      wrapper
        .find('.pageHeader')
        .isEmptyRender()
    ).toEqual(false)
    expect(
      wrapper
        .find('.pageHeader')
    ).toHaveLength(1)
```
RESULT
```log
FAIL: ReactWrapper::getNode() can only be called when wrapping one node
FAIL: Expected Length 1, Received Length 0
```
### Expected behavior
TEST 2:
```tsx
 wrapper
      .find(ComponentExample)
      .instance()
      .setState(TEST_STATE);
    expect(
      wrapper
        .find(ComponentExample)
        .instance()
        .state
    ).toEqual(TEST_STATE);
    wrapper.update();
    expect(
      wrapper
        .find('.pageHeader')
        .isEmptyRender()
    ).toEqual(false)
```
RESULT
```log
PASS
```
### Your environment
Windows 10
#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               | 16.4.1
| react-dom           | 16.4.1
| react-test-renderer | 16.8.6
| adapter (below)     |  1.11.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by tonyhallett** [comment]
What is TEST_STATE

**Comment by GeorgeWL** [comment]
Sorry, it's simply a `const` with some example state in it, the key part of which is that it contains `loaded: true`

**Comment by GeorgeWL** [comment]
Sorry, it's simply a `const` with some example state in it, the key part of which is that it contains `loaded: true`

**Comment by GeorgeWL** [comment]
Sorry, it's simply a `const` with some example state in it, the key part of which is that it contains `loaded: true`

**Comment by tonyhallett** [comment]
Have you debugged to see if render is being called ?

**Comment by tonyhallett** [comment]
And exactly which method throws the exception

**Comment by GeorgeWL** [comment]
@tonyhallet, how would I test that? 
And the last method of the stack, 
```js
expect(
             wrapper
                 .find('.pageHeader')
                 .isEmptyRender()
           ).toEqual(false)
```

**Comment by tonyhallett** [comment]
isEmptyRender ?

**Comment by GeorgeWL** [comment]
Yes.
Specifically cause it's unable to find the div, as when I run
```
console.log(wrapper.debug())
```
It does not appear in the render

**Comment by GeorgeWL** [comment]
The loaded state would normally rely on a API call.

**Comment by tonyhallett** [comment]
you will need to show your full component

**Comment by ljharb** [comment]
Indeed; we'd need to see the full component.

What's likely happening here is that your "loaded" state is getting set asynchronously, and your test isn't properly waiting on that asynchronous action.

**Comment by GeorgeWL** [comment]
I think you're correct.

I'll upload that to a private gist now.

https://gist.github.com/GeorgeWL/2b4c051c2eb234bddc03dd800aca40bb

**Comment by tonyhallett** [comment]
@GeorgeWL  Have you debugged it yet ?

**Comment by tonyhallett** [comment]
@GeorgeWL The problem is the call to isEmptyRender.  It will throw even if your div with class pageHeader is rendered.  isEmptyRender does not throw for wrapped component but does for a wrapped div so the method must only apply to react components.  Also, given that it always has inner html I wonder why you used it in the first place.

**Comment by GeorgeWL** [comment]
yet if instead I use 
```js
expect(
    wrapper
        .find('.pageHeader')
).toHaveLength(1)
```
it also states that there are 0 children. So I don't believe it's the method I've used for testing.
And the observation of the instance state does show that the state has changed, but the render doesn't update.

**Comment by tonyhallett** [comment]
@GeorgeWL  the isEmptyRender method is definitely incorrect.  

As for why it has not rendered - again - have you debugged ?

**Comment by ljharb** [comment]
@GeorgeWL specifically, your `componentDidMount` is an async function, which returns a promise. You'd have to get access to this promise, and await it in your test, and `wrapper.update()` after that, to be able to assert on the updated state.

One alternative is to explicitly `wrapper.setState({ loaded: true })` rather than relying on cDM to set it.

Either way, this is due to the nature of your component, and not something enzyme-related, so I'm going to close.

**Comment by GeorgeWL** [comment]
Thank you. I wasn't certain of the cause you see.
