### ISSUE TITLE
mount with react native doesn't work

### ISSUE THREAD

**Issue by yaizudamashii** [airbnb/enzyme#2094]
Using jest with enzyme and react native

I've followed the instructions in (did not add jsdom stuff in setup-tests.js as I'm using jest)
https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md
And mount should work, according to the documentation.  Please advise.

The stripped down test file as below.

```
/**
 * @jest-environment jsdom
 */
import React from 'react';
import { ScrollView } from 'react-native';
import { mount } from 'enzyme';

describe('Card', () => {
    let wrapper;
    describe('copy', () => {
        it('should render text', () => {
            const tree = mount(
                <ScrollView>
                </ScrollView>
            );
            expect(tree).toMatchSnapshot();
        });
    )};
)};
```
### Current behavior
```
 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.

    > 52 |             const tree = mount(
         |                                    ^
      53 |                 <ScrollView>
      54 |                 </ScrollView>
      55 |             );
```
### Expected behavior
Should be able to mount react native component
#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               |  16.4.1
| react-dom           |  16.0.0
| react-test-renderer | 16.0.0
| adapter (below)     |  1.10.0

react-native: 0.56.0
jest: 23.2.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Without an actual react-native adapter, it's not going to be reliable to use RN with enzyme. Follow #1436 for that.
