### ISSUE TITLE
Accept multiple components for find, filter, children, parents, closest on ShallowWrapper & ReactWrapper

### ISSUE THREAD

**Issue by ArrayKnight** [airbnb/enzyme#2095]
## 🚀 Feature Proposal

Expand wrapper DOM traversal utilities to accept multiple components in a single call.

## Motivation

To make nested selection of components more terse and more inline with the way a selector string functions.

When using a style system that generates CSS classes (e.g. Styled Components or CSS Modules) using string selectors is difficult/impossible.

Utilizing components means a string of calls is necessary for equivalent specificity.

## Example

Currently:
```
const wrapper = shallow(<Component {...props} />)

wrapper.find(Container).find(Child).find(Element)

// more or less equivalent to

wrapper.find('.container .child element')
```

But, the classes may be unknown/generated/inaccessible to be used in a string selector.

Proposed:
```
wrapper.find(Container, Child, Element)

// or

wrapper.find([Container, Child, Element])
```

**Comment by ljharb** [comment]
This seems a bit confusing - is that finding `Container > Child > Element`, or `Container, Child, Element`?

I think the chained `find` calls are much clearer than some kind of condensed DSL that might be confusing.
