### ISSUE TITLE
Enzyme Test on generated Connected Container Fails

### ISSUE THREAD

**Issue by akshayKrSingh** [airbnb/enzyme#2097]
### Current behavior
Generated a Container using Plop, with 'yes' to all options -> **saga**, **store**, **reducers**, **selectors**, then ran the tests for the container to test if Formatted Message renders properly, the test is failing:

##### ContainerPage
```bash
export class ContainerPage extends React.PureComponent {
  render() {
    const { classes } = this.props;

    return (
      <div className={classes.root}>
        <Helmet>
          <title>ContainerPage</title>
          <meta name="description" content="Description of ContainerPage" />
        </Helmet>
        <FormattedMessage {...messages.header} />
      </div>
    );
  }
}

ContainerPage.propTypes = {
  dispatch: PropTypes.func.isRequired,
  classes: PropTypes.object.isRequired,
};

const mapStateToProps = createStructuredSelector({
  containerPage: makeSelectContainerPage(),
});

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

const withReducer = injectReducer({ key: 'containerPage', reducer });
const withSaga = injectSaga({ key: 'containerPage', saga });

export default compose(
  withReducer,
  withSaga,
  withConnect,
  withStyles(styles),
)(ContainerPage);
```

##### ContainerPage Test
```bash
import React from 'react';
import { FormattedMessage } from 'react-intl';
import { shallow } from 'enzyme';

import configureStore from '../../../configureStore';
import ContainerPage from '../index';
import messages from '../messages';

describe('<ContainerPage />', () => {
  it('should render the page message', () => {
    const renderedComponent = shallow(<ContainerPage store={configureStore({})} />).dive();
    expect(renderedComponent.contains(<FormattedMessage {...messages.header} />)).toEqual(true);
  });
});
```

##### Error
```bash
Invariant Violation: (app/utils...) injectors: Expected a valid redux store

      15 |     injectedSagas: isObject,
      16 |   };
    > 17 |   invariant(conformsTo(store, shape), '(app/utils...) injectors: Expected a valid redux store');
         |   ^
      18 | }
      19 | 

      at invariant (node_modules/invariant/invariant.js:40:15)
      at invariant (app/utils/checkStore.js:17:3)
```

### Expected behavior
The Test should pass

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               | 16.6.0
| react-dom           | 16.6.0
| react-test-renderer | 16.6.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
With shallow rendering, you need one `.dive()` per HOC. I count 4 there, so you need `.dive().dive().dive().dive()` to get to the wrapped component that contains FormattedMessage.

**Comment by akshayKrSingh** [comment]
Still the same error. tried 4 `.dive()`'s i believe it's throwing **`Invariant`** error before it's able to dive, but not sure why, since I'm passing the redux store as well.

**Comment by akshayKrSingh** [comment]
closing this issue, the enzyme part of the issue is working fine. thanks @ljharb
