### ISSUE TITLE
How to Spy on React Class Methods

### ISSUE THREAD

**Issue by kevgathuku** [airbnb/enzyme#210]
Taking the following React Component as an example, how do I spy on the `redirect`  method to ensure it's called at some point
`NavBar.jsx`
```
class NavBar extends React.Component {
  constructor(props) {
    super(props);
  }

  redirect = (path) => {
    if(path) {
      return browserHistory.push(path);
    }
  };

  render() {
    return <div> NavBar </div>
  }
}
```

`NavBar-test.js`
```
it('redirects correcty if the user is not logged in', function(done) {
  let navBar = mount(<NavBar />); // Mount the component
  const inst = navBar.instance();
  sinon.spy(inst, 'redirect');
  expect(inst).toBeA(NavBar);
  
  // navigate to a route that should be redirected
  browserHistory.push('/not-found');
  setTimeout(function() {
    expect(inst.redirect.called).toBe(true);
    expect(window.location.pathname).toBe('/auth');
    done();
  }, 200);
  // // The redirect function should be called
  inst.redirect.restore();
});
```

So far, only the instance seems to have the method so I am able to spy on it but it does not seem to be called.
Attempting to run `sinon.spy(NavBar, 'redirect');` does not work.
Any assistance on how to figure this out would be greatly appreciated

**Comment by ljharb** [comment]
@kevgathuku you're calling `restore` synchronously, which means it happens before the function inside your `setTimeout`. Move the `restore` call until just before the `done`, inside the timed out function.

**Comment by kevgathuku** [comment]
I tried your recommendation and it worked for another test, but I was not able to get this particular test to work. My logic was all wrong.
Thanks for the help and for the great library. Really appreciate it.
