### ISSUE TITLE
Different debug output between mount and shallow

### ISSUE THREAD

**Issue by pastelsky** [airbnb/enzyme#2105]
Consider the following - 

```js
function Fixture() {
  return (
    <div>
      <span className="foo" />
    </div>
  );
}

console.log(mount(<Fixture />).debug())
console.log(shallow(<Fixture />).debug())
```

### Current behavior

Currently, debug on a `mount`ed element includes tags for the component itself.

#### Mount Output - 
```
<Fixture>
   <div>
      <span className="foo" />
    </div>
</Fixture>
```

#### Shallow output -

```
<div>
  <span className="foo" />
</div>
```

### Expected behavior
Since mount renders into JSDOM, I would expect the debug output to contain only valid HTML. Moreover, the output of both shallow and mount in this case should be the same.

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | -
| react-test-renderer | -
| adapter (below)     | 1.12.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is intentional. a mount wrapper is the component being wrapped; a shallow wrapper is what that component renders.
