### ISSUE TITLE
Unable to simulate onChange event with shallow

### ISSUE THREAD

**Issue by slim-hmidi** [airbnb/enzyme#2109]
I create a test for my component and I used Shallow in order to simulate an onChange event. You could find the reproduction code on this link [Simulate onChange event with Shallow](https://bit.ly/2vl6aAR)

### Current behavior
I got this error when I run the test:
```
expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["This is just for test"]
    But it was not called.
```
### Expected behavior
The test should pass successfully.
#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.8.4
| react-dom           |  16.8.4
| react-test-renderer |  16.8.6
| adapter (below)     |  1.12.1

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Sorry for the delay, and thanks for the repro!

In your codesandbox, you pass `input.onChange` as a prop, but in your test, you pass `onChange` at the top level. I think if you correct either one of these to be the same, everything will work?

**Comment by OmriGM** [comment]
Hello @slim-hmidi ,

There are 2 problems with your test suite.
1. As @ljharb mentioned, you did not address the correct `onChange` function that comes from the props, you addressed `input.onChange` but there is no such function in the input object because you didn't pass any.

2. Your expected result is not the same object you pass to the simulate change method.
e.g
 ```javascrpit
    const mockEvent = { target: { value: "This is just for test" } };
    wrapper.find("TextField").simulate("change", mockEvent);
    expect(onChange).toHaveBeenCalledWith(mockEvent);
```
The full fixed code can be found here: https://codesandbox.io/s/amazing-burnell-b9h7b

**Comment by Ghazaleh-Graziella** [comment]
hi 
how did you solve this problem?
I have the same!
I will thankful if you share your  solution .
:)
