### ISSUE TITLE
React-native: TypeError: wrapper.find(...).childAt is not a function

### ISSUE THREAD

**Issue by vitalets** [airbnb/enzyme#211]
trying to run this code:
```js
class MyComponent extends Component {
  render () {
    return <View><Text>123</Text></View>;
  }
};
...
it('should render myComponent', () => {
    const wrapper = shallow(<MyComponent/>);

    console.log('length', wrapper.find(Text).length); / returns 1
    console.log('childAt', wrapper.find(Text).childAt(0)); // throws error!
})
```
i'm using jest as testing framework.

**Comment by ljharb** [comment]
Just to check - does `.children().at(0)` work?

**Comment by vitalets** [comment]
@ljharb thanks!
It's even works with `wrapper.find(Text).at(0)`

Please update docs to not confusing other guys.

**Comment by ljharb** [comment]
oh it still might be a bug, this just clarifies it a bit :-)

**Comment by lelandrichardson** [comment]
This method was just added.... It hasn't actually been released in a published version of enzyme yet. The docs site does not have this documentation, but github does because it is looking at master.

**Comment by AlastairTaft** [comment]
Seeing this on enzyme 2.9.1 when using `render`, should it work with `render`? After reading the docs it seems like it should.

**Comment by ljharb** [comment]
No, it should not. render returns a Cheerio wrapper, so it will only have the methods that cheerio does.

**Comment by AlastairTaft** [comment]
Okay, thanks for clarifying
