### ISSUE TITLE
defaultProps for shallow renders do not work with React.memo

### ISSUE THREAD

**Issue by KamalAman** [airbnb/enzyme#2115]
### Current behavior
Default props from the "inner component" are not applied to memo'd component. The second test fails with `<div>NaN</div>`

```jsx

import React from 'react';
import { shallow } from 'enzyme';

const Add = ({ a, b }) => <div>{a + b}</div>;

Add.defaultProps = {
  a: 2,
  b: 3,
};

const MemoAdd = React.memo(Add);

describe('Enzyme Shallow Default Props Test', () => {
  it('default props should be applied to components', () => {
    const wrapper = shallow(<Add />);
    expect(wrapper.html()).toEqual('<div>5</div>');
  });

  it('default props should be applied to memo components', () => {
    const wrapper = shallow(<MemoAdd />);
    expect(wrapper.html()).toEqual('<div>5</div>');
  });
});

```

### Expected behavior
Default props should be applied to the memo component

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.8.6
 react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] others ( )

**Comment by ljharb** [comment]
Note that using `.html()` invokes `render` - prefer `.debug()`. However, this still seems to fail with debug, so thanks, it's a bug :-)

**Comment by ljharb** [comment]
This actually seems like a bug in the shallow renderer with memoized components. I've filed https://github.com/facebook/react/issues/15556 to track it.
