### ISSUE TITLE
Typescript - How to set component type while diving?

### ISSUE THREAD

**Issue by Dalqin** [airbnb/enzyme#2118]
When diving from a shallow wrapper, the type returned is `<ShallowWrapper<S = {}, P = {}, C = Component>`.
However, it is not obvious how one sets the `C = Component` part of the type while diving, as dive only allows two type arguments.

(Crossed out lines just to provide clarity of which part of the image I'm talking about)
![image](https://user-images.githubusercontent.com/42662231/57332737-fa8c6180-70e0-11e9-96b7-9dd96ada2197.png)

What should I do in this case, where `ConnectedSupplierRevisedPoItems` is a redux-connected component wrapping a `SupplierRevisedPoItems`? 
My goal is to be able to ask for `componentWrapper.instance() as SomeType;` without having to use `as SomeType`.

Please let me know if this isn't enough information, or if a simpler example is desired.

Thank you.

**Comment by ljharb** [comment]
This seems like an issue you'd want to file on DefinitelyTyped, which is where the enzyme types are defined.

**Comment by Dalqin** [comment]
Okay thank you! I will move this issue there.
