### ISSUE TITLE
Missing dependency has for enzyme-adapter-react-16

### ISSUE THREAD

**Issue by batfink** [airbnb/enzyme#2124]
### Current behavior

When using pnpm and running tests – requiring the enzyme-adapter during jest-enzyme fails. This is because `has` is missing from dependencies. Enzyme has this as a dependency, so it works with npm and yarn because node_modules is flattened – but since pnpm doesn’t flatten node_modules dependencies has to be correct. It can be solved temporarily by hooking into the install process with a [pnpmfile](https://github.com/batfink/missing-deps-pnpm-example/blob/master/with-pnpm/pnpmfile.js), but it would be better to fix the problem in the module.

Example: https://github.com/batfink/missing-deps-pnpm-example
Pull request: #2123 

### Expected behavior

Tests should run without complaining about missing adapter

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.9.0
| react               | ^16.8.6
| react-dom           | ^16.8.6
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ("jest": "^24.8.0",
    "jest-environment-enzyme": "^7.0.2",
    "jest-enzyme": "^7.0.2",)

**Comment by jChris85** [comment]
Thank you for fixing this issue, but could you also bump the version for npm to 0.13.1, please?

Currently I just can install the old 0.13.0 version from npm not containing the fix.

**Comment by ljharb** [comment]
Closed in #2123.

I’ll try to make a release tonight.

**Comment by ljharb** [comment]
v1.13.1 released.
