### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 2

### ISSUE THREAD

**Issue by JonathanTyrrell** [airbnb/enzyme#2125]
### Current behavior

`    Enzyme Internal Error: unknown node with tag 2

      19 | ): ReactWrapper => {
      20 |   const el = (): JSX.Element => component;
    > 21 |   return mount(<Provider store={store}>{el()}</Provider>);
         |          ^
      22 | };`

from:

```jsx
import { shallow, ShallowWrapper, mount, ReactWrapper } from "enzyme";
import React, { ReactElement } from "react";
import { Provider } from "react-redux";
import { MockStoreEnhanced } from "redux-mock-store";

export const shallowWithStore = (
  component: ReactElement,
  store: MockStoreEnhanced
): ShallowWrapper => {
  const context = {
    store
  };
  return shallow(component, { context });
};

export const mountWithStore = (
  component: ReactElement,
  store: MockStoreEnhanced
): ReactWrapper => {
  const el = (): JSX.Element => component;
  return mount(<Provider store={store}>{el()}</Provider>);
};
```

I'm using `react-i18next` and suspect it could be to do with the export:
```jsx
export default withTranslation()(
  withRouter(
    connect(
      mapStateToProps,
      mapDispatchToProps
    )(HomePage)
  )
);
```

### Expected behavior
No error.
#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.5
| react-dom           | 16.8.4
| react-test-renderer | 
| adapter (below)     | 1.13.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
What does `withTranslation` do?

**Comment by ljharb** [comment]
https://unpkg.com/react-i18next@10.9.0/src/withTranslation.js looks like without the `withRef` option, it's just an SFC.

What's `withRouter` do?

This is particularly confusing because `mount` just uses normal React.

However, I *do* see that you have mismatched react-dom and react versions - what happens if you make both of them precisely identical?

**Comment by ljharb** [comment]
react-dom has `var IndeterminateComponent = 2; // Before we know whether it is function or class` [here](https://unpkg.com/react-dom@16.8.6/cjs/react-dom.development.js), which is super strange.

**Comment by JonathanTyrrell** [comment]
We use withRouter to get the prop types:
[https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md](url)

I updated both react & react-dom to 16.8.5 but still get the error.

The tests worked fine before I added the i18next framework.

**Comment by ljharb** [comment]
A reproducible test case - without `mountWithStore`, and with no other deps besides perhaps i18next - would really help here.

**Comment by JonathanTyrrell** [comment]
Working on the repro test case.
I'll upload when I have it ready.

**Comment by JonathanTyrrell** [comment]
I figured out the cause. I was using Fetch from the backend to load the string resources. For some reason, this was causing the tests to fail. Running the tests using a local resources file worked fine.

**Comment by ljharb** [comment]
I'm not sure what `Fetch` is (unless you mean `fetch`) - did this happen because you rendered a Promise?
