### ISSUE TITLE
Arrow functions in the mocha examples

### ISSUE THREAD

**Issue by rnsloan** [airbnb/enzyme#213]
I notice the mocha examples are using arrow functions. By default, arrow functions cause Mocha problems https://mochajs.org/#arrow-functions . Should they be changed to standard functions or the Mocha page http://airbnb.io/enzyme/docs/guides/mocha.html amended with a note about this/link to https://github.com/skozin/arrow-mocha ?

Happy to create the PR for this.

**Comment by ljharb** [comment]
Arrow functions only cause problems with mocha if you're using `this` inside your tests, which is a pattern we discourage.

**Comment by rnsloan** [comment]
Fair enough, thought a note might prevent people from copying & pasting and then raising an issue because they were unaware of Mocha's binding.

**Comment by ljharb** [comment]
If they copy and paste, their specs won't use the "this" keyword and there won't be any issues :-)
