### ISSUE TITLE
Question: How to test useCallback in a functional component?

### ISSUE THREAD

**Issue by edwardfhsiao** [airbnb/enzyme#2143]
Hi,

Previously using ```class``` component method, I do the following:
```js
describe('dummy text', () => {
  it('[onChange]: Should call handleOthers', () => {
    const wrapper = mount(<Component/>)
    const instance = wrapper.instance();
    instance.handleOthers = jest.fn();
    instance.onChange();
    expect(instance.handleOthers).toHaveBeenCalled();
})
```

Now I am trying the hook way(react v16.8.6), which the test above obviously breaks at ```instance```.

```js
const Component = memo(({a, b} => {
  const el = useRef(null)
  const [val, setVal] = useState('')
  const handleOnChange = useCallback((e)=>{
    setVal(el.current.value)
  }, [])
  const handleOthers = useCallback(()=>{}, [])
  const handleEffect = useCallback(()=>{}, [])
  useEffect(()=>{
    handleEffect()
  },[])
  return (
    <div><input ref={el} onChange={handleOnChange} /></div>
  )
}))
```

How to test ```handleOnChange```,```handleOthers```,```handleEffect``` respectively?

```js
"react": "^16.8.6",
"react-dom": "^16.8.6"
"enzyme": "^3.9.0",
"enzyme-adapter-react-16": "^1.13.2",
"jest": "^23.6.0",
```

**Comment by ljharb** [comment]
Hooks won't work properly until the next enzyme release, v3.10.

**Comment by edwardfhsiao** [comment]
@ljharb Thank you for your information.

**Comment by ljharb** [comment]
[v3.10.0](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.10.0) has now been released.

**Comment by edwardfhsiao** [comment]
@ljharb Thanks. But can you help me with my early question? 
How to test ```handleOnChange```,```handleOthers```,```handleEffect``` with the current version?

**Comment by ljharb** [comment]
They should all work in `mount`; but the facebook shallow renderer doesn't yet support `useEffect`, so that won't work in `shallow`.

**Comment by edwardfhsiao** [comment]
the thing is now when I do ```instance.handleOthers = jest.fn();```

It says ``` TypeError: Cannot set property 'handleOthers' of null```

**Comment by ljharb** [comment]
Sure - functional components have no instance, and `handleOthers` here is a variable inside the function. It's never been, and never will be, possible to "stub" variables inside of a closure.

**Comment by edwardfhsiao** [comment]
is there any way to test handleOthers?

**Comment by lj383997002** [comment]
have you resolve this problem?

**Comment by edwardfhsiao** [comment]
@lj383997002 I did not test callback function now.

**Comment by jdnichollsc** [comment]
You can put `useCallback` functions in another hook and later use this library to test your code: https://github.com/testing-library/react-hooks-testing-library

**Comment by KiranVH** [comment]
Hey, I am trying to test `useCallback` as mentioned above but I don't want to test it by creating a custom hook and installing the library is there any other way to test it normally @edwardfxiao ?
