### ISSUE TITLE
The Props function within a test is not called, although all the conditions to be called are correct

### ISSUE THREAD

**Issue by cadrimiranda** [airbnb/enzyme#2145]
I have a form, and when i submit her i call a function that validate the form, and if everything is alright, i call a redux-saga action with have a API inside. 

When i testing this, i spy the redux function and set the input fields with some value that pass the validation, and i expect that function is with spy have be called, but is not.

I tried to put some console log to see what i'm doing wrong, and the field values has setted and have all conditions to call function, but the spy say that was not called.

I put async and wait for function, code and test, but it did not solve my problem.

In my form, i have a function
```javascript
function loginUser(event) {
    event.preventDefault();
    let error = false;
    const { field1, field2, field3 } = values;
    console.log(values);

    // settings errors in each input field
    /* my logic is here, if has error, the var error is setted to true*/

    // if no errors, fetch login
    if (!error) {
      console.log('Error:', error);
      fetchLogin(domain, user, password);
    }
  }
```

and my test function
```javascript
test('submit ok', () => {
    const spy = jest.spyOn(Comp.props(), 'fetchLogin');
    const form = Comp.find('form');
    
    // setFieldValue is a passed in props by Formik Lib 
    Comp.props().setFieldValue('field1', 'some value');
    Comp.props().setFieldValue('field2', 'some value');
    Comp.props().setFieldValue('field3', 'some value');

    form.simulate('submit', { preventDefault() {} });
    console.log(spy);
    expect(spy).toBeCalled();
  });
```

I expect that function have been called, but this never happend and ii dont know why.

I put the console log in the first line of a function and show me the values:
```javascript
console.log src/pages/Login/LoginForm.jsx:128
{   field1: 'some value',
    field2: 'some value',
    field3: 'some value'  }
```

And put a console log before the function ```fetchLogin```:
```javascript
console.log src/pages/Login/LoginForm.jsx:158
    Error: false
```

But the test shows me:
```javascript
Expected mock function to have been called, but it was not called.
```

**Comment by ljharb** [comment]
@cadrimiranda did you figure this out?

I assume it's due to simulate not actually simulating anything, which is why I recommend never using it.
