### ISSUE TITLE
Cannot find SVG icon via Enzyme

### ISSUE THREAD

**Issue by turnerhayes** [airbnb/enzyme#2146]
I filed this bug with [Material UI](https://github.com/mui-org/material-ui/issues/15928), but they seem to think it's an Enzyme bug. One of the MUI team members there commented that

> It's likely an issue with composing memo(forwardRef()).

### Current behavior

Enzyme doesn't even seem to recognize that the icon is of the type of the icon; that is,
```
import EditIcon from '@material-ui/icons/Edit';

console.log(mount(<EditIcon />).is(EditIcon));
```

displays `false`. As a result, if I have an `IconButton` that contains `<EditIcon/>`, Enzyme doesn't find it.

See https://codesandbox.io/s/fervent-bash-5ys2g

### Expected behavior

`mount(<ComponentContainingMUIIcon />).find(MUIIcon)` should return a wrapper for the icon.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | N/A
| adapter (below)     | 1.13.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Can you please fill out the entire issue template?

From the linked issue, it looks like an interaction between memo and forwardRef.

**Comment by turnerhayes** [comment]
Done! Let me know if there's any more information that would be useful.

**Comment by oliviertassinari** [comment]
It would have been even better without Material-UI as a dependency of the codesandbox.

**Comment by ljharb** [comment]
Thanks, this is enough to reproduce.

**Comment by turnerhayes** [comment]
Great! Thanks for the quick turnaround! When will this be published on NPM?

**Comment by ljharb** [comment]
as soon as i have time; hopefully today.

**Comment by gReis89** [comment]
it stoped working again after material-ui/core 4.7.0 update(works on 4.6.1):
https://codesandbox.io/s/blissful-mendeleev-3vj5l

**Comment by ljharb** [comment]
@gReis89 sounds like they had a breaking change in a minor version; i'd file an issue.

**Comment by oliviertassinari** [comment]
Is this related to https://github.com/mui-org/material-ui/issues/15928?

**Comment by ljharb** [comment]
@oliviertassinari it may be a similar cause; but that was the cause of the OP. The latest report is something new.

**Comment by oliviertassinari** [comment]
It seems different, indeed. What could explain this new behavior?

**Comment by ljharb** [comment]
Perhaps a change in display name, or they changed the number of HOC wrappers on a component? Not really sure, I'm not familiar with material UI.
