### ISSUE TITLE
Component being rendered intermittently outside of act

### ISSUE THREAD

**Issue by nareshbhatia** [airbnb/enzyme#2151]
### Current behavior
I am writing a component that uses `useState`, `useEffect` and a custom hook. To test it, I am mounting the component using enzyme and wrapping it with `act()`. I have 5 tests for this component. They succeed when they are run individually (commenting out the others), however when I run them together, tests 4 and 5 fail. The problem is that in this scenario, the component is prematurely mounted and the final render runs outside the `act`. See console logs below:

```
      ---> test 4
      ---> render()
      ---> ticker = undefined
      ---> useEffect()
      ---> ticker received: AAPL
      ---> <HomePage>
        <div>
          Please select a ticker
        </div>
      </HomePage>
      ---> render()
      ---> ticker = AAPL
```

As an example, here's the code for test 4:

```
it('renders an error message when the company query succeeds but does not return a company', () => {
    (TickerPublisher.subscribe as jest.Mock).mockImplementation(
        (callback: TickerCallback) => {
            callback('AAPL');
        }
    );
    (useCompanyQuery as jest.Mock).mockReturnValue({
        loading: false,
        error: undefined,
        company: undefined
    });

    act(() => {
        console.log('---> test 4');
        const wrapper = mount(<HomePage />);
        console.log('--->', wrapper.debug());
        expect(
            wrapper.find(
                'div[children="Company query did not return data"]'
            )
        ).toHaveLength(1);
    });
});
```

I even tried to take out the `expect()` from the `act()` wrapper (see below), but the test still fails.

```
let wrapper: any;
act(() => {
    wrapper = mount(<HomePage />);
});
expect(
    wrapper.find(
        'div[children="Company query did not return data"]'
    )
).toHaveLength(1);
```

Here's my [full code with all 5 tests](https://github.com/nareshbhatia/enzyme-playground/blob/master/src/pages/HomePage/HomePage.test.tsx).

### Expected behavior
All tests should pass when run together.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.3
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 
| adapter (below)     | 1.13.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
enzyme already wraps with `act` if you're using the latest adapter, so I don't think you should need it there at all.

**Comment by nareshbhatia** [comment]
Wow! Didn't know that. I was basically following [react-act-examples](https://github.com/threepointone/react-act-examples) not realizing that enzyme has all that built in. All tests passing now. @ljharb, you are the best!
