### ISSUE TITLE
React Lazy tests failing. Error: Method “props” is meant to be run on 1 node. 0 found instead.

### ISSUE THREAD

**Issue by DonikaV** [airbnb/enzyme#2159]
### Your environment
Macos, Linux

#### API

- [ ] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               | 16.8.6
| react-dom           | 6.8.6
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16

**ParentComponentWIthSuspense.js**
```js

const OtherComponent = React.lazy(() => import('src/main/js/OtherComponent'));```
Render()
```jsx
return (
            <div>
                <React.Suspense fallback={<Spinner />}>
                    <OtherComponent  here some props/>
                 </React.Suspense>
            </div>
```
And this is tests 

```js
let shallowInitialComponent = async () => {
        const wrapper = shallow(<ParentComponentWIthSuspense {...props} />);
        await waitNextTick();
        wrapper.update();
        return wrapper;
    };
```

```js
it("Should render", async () => {
        const expectedProps = {
            title: "Some title",
            desc: "Some cool desc",
            .....// others
        };

        const wrapper = await shallowInitialComponent();
        Object.values(expectedProps).forEach((item) => {
            expect(wrapper.find("OtherComponent").prop(item)).toBe(expectedProps[item]);
        });
    });
```

The interesting thing. That it see Suspense. I mean if i will use standard import instead of lazy. The tests are passed... It is weird...

**Comment by ljharb** [comment]
What version of the react 16 adapter are you using?

what does `wrapper.debug()` print out?

**Comment by DonikaV** [comment]
react adapter 1.14.0
.debug will show you tomorrow. Thanks

**Comment by DonikaV** [comment]
@ljharb Hi, i dont know if it could help you. 

```js
 console.log src/test/js/unit/results/parentComponent/ParentComponent.spec.js:78
    <div>
      <Suspense fallback={{...}}>
        <lazy //HERE MY PROPS>
      </Suspense>
    </div>
```

**Comment by ljharb** [comment]
You'll note there's no `OtherComponent` in that tree, so `.find('OtherComponent')` should return an empty wrapper. Specifically, try `.find(OtherComponent)` - ie, by constructor, not by display name.

**Comment by DonikaV** [comment]
```js
let design = wrapper.find('OtherComponent');
console.log(design); // ShallowWrapper {}
expect(design.length).toBe(1);
Expected: 1
Received: 0
```

**Comment by DonikaV** [comment]
@ljharb i should import with lazy? Or just import? 
Because i changed wrapper.find('OtherComponent'); to wrapper.find(OtherComponent); and same situation.

**Comment by ljharb** [comment]
In your component file, you should change:
```jsx
const OtherComponent = React.lazy(() => import('src/main/js/OtherComponent'));
```
to:
```jsx
export const OtherComponent = React.lazy(() => import('src/main/js/OtherComponent'));
```

and then in your tests, you'd need to `import { OtherComponent } from 'wherever';`, and *then* you can do `.find(OtherComponent)`.

**Comment by DonikaV** [comment]
Works fine! Thank you so much ! :)

**Comment by rodoabad** [comment]
@DonikaV are you having any problems with your coverage?

**Comment by DonikaV** [comment]
No, everything works fine.

**Comment by YcodeMan** [comment]
I have the same problem。 if import OtherComponent can found. but lazy(() => import('src/main/js/OtherComponent')) not found。is lazy problem? How to solve ？
