### ISSUE TITLE
How to change a checkbox value using simulate api?

### ISSUE THREAD

**Issue by bboysathish** [airbnb/enzyme#216]
Hi,

I am using jsdom with enzyme. 

When the component mounts first time it is set to "checked":"checked", the input element has "onChange" event which will change the state and re-renders the check box as uncheked. 

```js

if(this.state.field_value === "True"){
<input 
     type="checkbox"
     className="form-control"
     name={this.state.field_name}
     title={this.state.help_text}
     checked="checked"
      onChange={this.handleChange} />
}else{
<input 
     type="checkbox"
     className="form-control"
     name={this.state.field_name}
     title={this.state.help_text}
      onChange={this.handleChange} />
}
```

```js
onChange function:

handleChange: function(event) {
	var checked = event.target.checked ? "True":"False";
	this.setState({field_value:checked});
  }

```

Now to test this with enzyme, I tried doing this.

```js
  it('Renders and Simulates Click Event ', () => {

    const CheckBoxProps =  {
      "field_name": "Howareyou",
      "input_type": "Checkbox"
      "field_value": "True"
    };

    const Wrapper = mount(<CheckBox
      dataObj={CheckBoxProps} />);
    
      // This one works  -- But doesn't seem like a simulation..
      expect(Wrapper.find('input[type="checkbox"][checked="checked"]')).to.have.length(1);
      Wrapper.setState({'field_value':'false'})
      expect(Wrapper.find('input[type="checkbox"][checked="checked"]')).to.have.length(0);

      // This one not works
      Wrapper.find('input[type="checkbox"][checked="checked"]').simulate('change');
      console.log(Wrapper.find('input[type="checkbox"][checked="checked"]')); // still length is 1

  });
```

Even this also not working,

```js

      Wrapper.find('input[type="checkbox"]').simulate('change');
      expect(Wrapper.state('field_value')).to.equal("False");

```

P.S : How to do simulation for all the events like input type text,radio,textarea etc.. is there any resource available.

**Comment by marlonbernardes** [comment]
I don't have the time to test it right now, but please try replacing the event name from `change` to `click`:

```js
Wrapper.find('input[type="checkbox"][checked="checked"]').simulate('click');
```

**Comment by bboysathish** [comment]
@marlonbernardes I need to make it work for change event.. Well, will give a try for 'click'.

**Comment by bboysathish** [comment]
@marlonbernardes Still not working...

**Comment by marlonbernardes** [comment]
You should bind the value of `this` when you call your `handleChange` function, because it's not pointing to your react component:  

```js
 onChange={this.handleChange.bind(this)}  
```

Try this and let me know if it works for you. I also have some tips on how to make your component's code  more concise, but lets focus on one thing at a time.

**Comment by bboysathish** [comment]
@marlonbernardes Sorry for the late reply. Still it is not working... Can you post me a sample of how to test a checkbox with jsdom and enzyme ? That would be a great help.

**Comment by ljharb** [comment]
(of course, you shouldn't create functions and pass them as props in the render path - so you'd want `this.handleChange = this.handleChange.bind(this)` in your constructor)

**Comment by bboysathish** [comment]
@ljharb @marlonbernardes  This is the full code https://gist.github.com/bboysathish/8c78d6c295c0613d08b6.

**Comment by ljharb** [comment]
@bboysathish calling `.simulate('change')` doesn't change the value though - have you tried `.simulate('change', { target: { checked: true } })` or something similar?

**Comment by bboysathish** [comment]
@ljharb  Worked like a charm, Thanks `Wrapper.find('input[type="checkbox"]').simulate('change',{ target: { checked: false } });` . But is there a documentation for this `target` argument ? or list of arguments I can pass to simulate. As per this documentation, http://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html. I don't see anything.

**Comment by ljharb** [comment]
@bboysathish See item 2 on http://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html#arguments

**Comment by bboysathish** [comment]
@ljharb R u referring this `...args (Any [optional]): A mock event object that will get passed through to the event handlers.`?  Can you please point me, how does mock event object will look like ? (Kinda what are the properties it accepts)

**Comment by ljharb** [comment]
@bboysathish it's any object you like. whatever you pass there, will be passed as arguments to the event handler. there's no magic.

**Comment by bboysathish** [comment]
@ljharb So, for `input[type="text"]` to simulate a change event with some text I can do something like this? 
`Wrapper.find('input[type="text"]').simulate('change',{ target: { value: "I need model target object :)" } })`

**Comment by ljharb** [comment]
Looks right to me - try it and see! :-)

**Comment by bboysathish** [comment]
Great!! Will try..  Thanks @ljharb ...

**Comment by besrabasant** [comment]
Now, this isn't working for me.

**Comment by Burkazoid** [comment]
I hit some problems when I was using `e.currentTarget` in the `onChange` function. If I specified `.simulate('change',{ currentTarget: { checked: true } });`, it seemed to get overwritten by the time it reached the `onChange` function, giving unexpected results. Changing `currentTarget` to `target` in both the `onChange` function and the test fixed this.

**Comment by yoni-tock** [comment]
In case someone else hits this. If you're using typescript, `React.SyntheticEvent` doesn't have `event.target.checked`. Given that I'd like my tests to work, I don't have a solution to this other than casting in the event handler :(.

**Comment by luyizhao** [comment]
As a variation on @Burkazoid's suggestion, a workaround that doesn't require changing `currentTarget` to `target` in the code would be to use `onChange` instead of `simulate` in your tests and pass in your desired event, i.e.:
```js
.prop('onChange')({currentTarget: { checked: false }})
```

**Comment by HunderlineK** [comment]
Is there a way  to simulate checking a checkbox that is within in a `select`?

**Comment by ljharb** [comment]
@HunderlineK no, you can't simulate anything. You can explicitly invoke the `onClick` or `onChange` prop; you can explicitly set the state so that it's open, but what you want to do requires a full browser integration test, and can't be done properly with enzyme.

**Comment by Duongasaur** [comment]
For those who are rendering the actual html input in another component.
You will need to mount instead of shallow in order to properly use the simulate('change ....

**Comment by ljharb** [comment]
@Duongasaur i'm going to hide that comment, because no, you don't need mount instead of shallow, and you shouldn't need simulate anyways.

**Comment by surya-art** [comment]
wrapper = mount(<customCheckboxToConfigure custom={mockLoginfn} store={store}/>);
      wrapper.setProps({checked:false});
      wrapper.find('input[type="checkbox"]').simulate('change', {target:{checked:true}})
      expect(wrapper.state(checked)).toBe(true);


This throws an error '    Method “simulate” is only meant to be run on a single node. 0 found instead.'
@ljharb

**Comment by surya-art** [comment]
wrapper = mount(<customCheckboxToConfigure store={store}/>);
      wrapper.setProps({checked:false});
      wrapper.find('input[type="checkbox"]').simulate('change', {target:{checked:true}})
      expect(wrapper.state(checked)).toBe(true);


@ljharb this shows an error like

Method “simulate” is only meant to be run on a single node. 0 found instead.

**Comment by ljharb** [comment]
@surya-art sounds like there's no checkboxes then. Remember to `wrapper.update()` after the setProps, and then what does `wrapper.debug()` print out?

(Please file a new issue with your comment and your response, if that doesn't solve it for you)

**Comment by ashrash290** [comment]
> As a variation on @Burkazoid's suggestion, a workaround that doesn't require changing `currentTarget` to `target` in the code would be to use `onChange` instead of `simulate` in your tests and pass in your desired event, i.e.:
> 
> ```js
> .prop('onChange')({currentTarget: { checked: false }})
> ```

change currentTarget to target if you're using .prop
> .prop('onChange')({target: { checked: false }})
