### ISSUE TITLE
React router's Link component is not found as expected when test runs for first time

### ISSUE THREAD

**Issue by maurocarrero** [airbnb/enzyme#2161]
### Current behavior
Testing a component with shallow and dive and searching for react-router's `Link` component fails only the first time, after that Jest uses its cache and works perfectly.

In the first run `Link` can be found as `e` instead. 

### Expected behavior
`Link` should be found seamlessly.

#### API

- [X] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-router        | 5.0.1
| react-redux         | 7.0.3
| adapter (below)     | 1.14.0

#### Adapter

- [X ] enzyme-adapter-react-16

**Comment by ljharb** [comment]
Did you figure this out?

**Comment by maurocarrero** [comment]
Will need to rewrite it.

**Comment by ljharb** [comment]
Can you provide code I can use to reproduce?

Are you using watch mode, by chance? Note that watch mode itself, like hot reloading, can cause normal JS semantics to be broken.

**Comment by maurocarrero** [comment]
The code is simple:
```
wrapper = shallow(<Example />).dive();
expect(wrapper.find('Link').prop('to')).toEqual(EXPECTED_URL);
```
I tried without watch mode as well, actually the problem was in CI, locally was passing, of course.
To make it fail locally, I used `jest --clearCache`, and run again. First time will fail, then forever pass.

**Comment by ljharb** [comment]
Try finding by constructor, instead of using the name. It's possible that react router's Link's display name isn't set properly.

**Comment by maurocarrero** [comment]
Actually after that first time it is correctly found as `Link` so the displayName seems to be ok.

**Comment by ljharb** [comment]
Right, but if it was set up correctly, it'd find it the first time :-)

The first time (when it doesn't find it), what does `wrapper.debug()` print out?

**Comment by maurocarrero** [comment]
1st: <e to="/my-url">
2nd-nth: `<Link to="/my-url">`

**Comment by ljharb** [comment]
There you go - the display name is `e` the first time around.

I don't think this is something enzyme can fix - it's either something in react-router, something in jest, or something in your build process (perhaps you're uglifying/name mangling with babel?)

**Comment by maurocarrero** [comment]
Yes, sorry, I thought this detail was clear as described in `Current Behavior` above.
This is a very usual configuration, nothing fancy.
I will search around, thanks.

**Comment by ljharb** [comment]
sorry, it was, i just missed it :-)

lmk what it ends up being. I'm going to close this for now (with a recommendation to always find by constructor and not by display name), but am happy to reopen if there's something actionable in enzyme.
