### ISSUE TITLE
mount Fragment with new style (<>...</>) return null

### ISSUE THREAD

**Issue by Eightyplus** [airbnb/enzyme#2166]
### Current behavior
rendering a component with `<> ... </>` seems troublesome and often return `null` instead of children

functional-component.js
```
import React from 'react';
export default ({ message }) => <span>{message}</span>;
```

component.js
```
import React from 'react';

import FunctionalComponent from './functional-component';

export default ({ message, show }) => {
  return (
    <>
      {message}
      {show && <FunctionalComponent message={message} />}
    </>
  );
};
```
component.test.js
```
import React from 'react';
import { mount, render } from 'enzyme';

import Comp from './component';

describe('testing render of mounted component', () => {
  it('mount ', () => {
    const wrapper = mount(<Comp message="mount " />);
    expect(wrapper).toMatchSnapshot();
  });

  it('mount then render', () => {
    const wrapper = mount(<Comp message="mount then render" />);
    expect(wrapper.render()).toMatchSnapshot();
  });

  it('render all', () => {
    const wrapper = render(<Comp message="render" show />);
    expect(wrapper).toMatchSnapshot();
  });

  it('render conditional', () => {
    const wrapper = render(<Comp message="render conditional" show={false} />);
    expect(wrapper).toMatchSnapshot();
  });
});
```

component.test.js.snap
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`testing render of mounted component mount  1`] = `
<_default
  message="mount "
>
  mount 
</_default>
`;

exports[`testing render of mounted component mount then render 1`] = `null`;

exports[`testing render of mounted component render all 1`] = `
Array [
  "render",
  <span>
    render
  </span>,
]
`;

exports[`testing render of mounted component render conditional 1`] = `null`;
```

### Expected behavior
Render children and not `null`

works if I exchange `<>` with `<Fragment>`

### Your environment
Mac OS X 10.14.5

#### API

- [ ] shallow
- [X] mount
- [X] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Enzyme does not support or encourage snapshot testing (which is very brittle) whatsoever - the closest would be `.debug()`.

This is a bug in, presumably, enzyme-to-json, and not enzyme.

**Comment by Eightyplus** [comment]
Ok than, I'll report the error to `enzyme-to-json`.
