### ISSUE TITLE
shallow.get() returns ReactElement with wrong type

### ISSUE THREAD

**Issue by Joonpark13** [airbnb/enzyme#2168]
### Current behavior
Grabbing a connected component by using `shallow().get(0)` returns a ReactElement with the wrong type (`type: function ConnectionFunction()` instead of `type: Object`).

Looks like this issue did not arise in enzyme-adapter-react-16 1.12.1 (setting the adapter version to 1.12.1 in the sandbox makes the test pass), but subsequent versions do have this issue.

### Expected behavior
Should return a ReactElement with `type: Object`.

### Your environment
https://codesandbox.io/s/happy-sammet-6o3li

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -----------------
| enzyme              | 3.10.0 (latest as of writing)
| react               | 16.8.6 (latest stable as of writing)
| react-dom           | 16.8.6 (latest stable as of writing)
| react-test-renderer | (not a direct dependency)
| adapter (below)     | 1.14.0 (latest as of writing)

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Element types should almost always be a function; unless it’s one of the newer ones like forwardRef.

**Comment by Joonpark13** [comment]
Gathering from https://twitter.com/acemarke/status/1139258985763282946 I think `connect` uses React.memo, which can have a type of Object?

**Comment by ljharb** [comment]
Indeed that's correct.

In your codesandbox, `expect(component.get(0)).toEqual(<Child />);` should never be equal since `toEqual` uses `===`, and those can't be the same element.

**Comment by Joonpark13** [comment]
Ah sorry, my fault - I should've mentioned we're using Jasmine in our codebase, and if I'm not mistaken in jasmine .toEqual does a deep compare? It also fails if I use .toEqualJSX() (https://github.com/smacker/jasmine-expect-jsx) which uses a string comparison.

**Comment by ljharb** [comment]
I also wouldn't rely on that - enzyme has `matchesElement`, what happens if you `expect(component.matchesElement(<Child />)).toBe(true)`?

**Comment by Joonpark13** [comment]
That one seems to work. It's gonna be a real hefty change in our codebase to change our usages of `.toEqual` or `.toEqualJSX` to `matchesElement`, but if we're not using shallow as intended, that just might be the way we have to go. Thanks!
