### ISSUE TITLE
enzyme "3.10.0" and react "15.0.1" Cannot find module 'react-dom/test-utils' from 'ReactFifteenAdapter.js'

### ISSUE THREAD

**Issue by sherazahmedse** [airbnb/enzyme#2183]
Hello Everyone, Its my first ever git post, please be patient and bear with me. thanks.. 

**Background :**  I have an huge react application already on production and it is written using react 15.0.1.  My task is to write test cases for already written components and in future we plan to practice TDD. 

**Limitation :** I cannot upgrade the application to react 16. because it breaks a lot of code. 

**Problem :**  I am following enzyme [docs](https://airbnb.io/enzyme/docs/installation/react-15.html) for enzyme to work with react 15 and I am getting the error while running tests which is mentioned in the title of this post  

I skip the first step that is to run `npm i --save react@15 react-dom@15` as i already have react-dom 15.0.1 in my dependencies. you can see the ` package.json` file at the very end of this post.   

I perform the second step that is to run `npm i --save-dev react-test-renderer@15` and it adds `"react-test-renderer": "^15.6.2"` in my dependencies. (I have also tried this `npm i --save-dev react-test-renderer@^15.5.0` to be specific about the version but I am still facing same issue) 

I perform the third step that is to run `npm i --save-dev enzyme enzyme-adapter-react-15`

My setupTests.js file contains the code 

```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-15';

configure({ adapter: new Adapter() });
```

When I run the test using npm test command I get the following error: 

    Test suite failed to run
    Cannot find module 'react-dom/test-utils' from 'ReactFifteenAdapter.js'

Here is the content of package.json file 

```
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "scripts": {
    "gulp": "node_modules\\.bin\\gulp.cmd",
    "test": "react-scripts test --env=jsdom"
  },
  "devDependencies": {
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babelify": "7.2.0",
    "bower": "1.8.4",
    "browserify": "13.0.0",
    "classnames": "2.2.3",
    "envify": "4.1.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-15": "^1.4.0",
    "event-stream": "3.3.2",
    "fs": "0.0.1-security",
    "glob": "7.0.3",
    "gulp": "3.9.1",
    "gulp-clean-css": "3.7.0",
    "gulp-minify": "0.0.15",
    "gulp-notify": "3.2.0",
    "gulp-rename": "1.2.2",
    "gulp-uglify": "1.5.3",
    "gulp-util": "3.0.8",
    "gulp-watch": "4.3.5",
    "react-scripts": "3.0.1",
    "react-test-renderer": "^15.6.2",
    "streamify": "0.2.5",
    "vinyl-buffer": "1.0.0",
    "vinyl-source-stream": "1.1.0",
    "vinyl-sourcemaps-apply": "0.2.1",
    "watchify": "3.11.0",
    "xmldom": "0.1.27",
    "xpath": "0.0.24"
  },
  "dependencies": {
    "bootstrap-datepicker": "1.6.0",
    "griddle-react": "0.6.1",
    "icheck": "1.0.2",
    "jquery": "2.1.4",
    "jquery-ui": "1.12.0",
    "flux": "2.1.1",
    "object-assign": "4.1.0",
    "react": "15.0.1",
    "react-checkbox-list": "0.0.2",
    "react-dom": "15.0.1",
    "react-icheck": "0.3.4",
    "react-validation": "1.7.2",
    "validator": "5.3.0",
    "react-tabs": "0.7.0",
    "react-tab-panel": "2.2.2",
    "react-select": "1.0.0-rc.2",
    "react-bootstrap-datetimepicker": "0.0.22",
    "rc-time-picker": "3.6.4",
    "moment": "2.18.1",
    "react-checkbox-tree": "0.6.4",
    "detect-browser": "1.6.2",
    "ip": "1.1.4",
    "lodash": "4.13.1",
    "es6-promise": "4.1.1",
    "json5": "0.5.1",
    "guid": "0.0.12",
    "get-ip": "2.0.0",
    "array.prototype.find": "2.0.4",
    "babel-polyfill": "6.26.0",
    "react-addons-create-fragment": "15.6.2",
    "rsvp": "4.8.2",
    "react-chartjs-2": "2.7.0",
    "chart.js": "^2.7.2"
  }
}

```

**Comment by ljharb** [comment]
Do you also have react-dom 15.0 installed? (please fill out the entire issue template, it’s there for a reason)

**Comment by sherazahmedse** [comment]
> Do you also have react-dom 15.0 installed? (please fill out the entire issue template, it’s there for a reason)

Yes I have react-dom 15.0.1 installed.

**Comment by ljharb** [comment]
ah. You need the 15.4 adapter if you have react < 15.5 - if you run `npm ls`, you’ll see that your dep graph is currently invalid.

**Comment by sherazahmedse** [comment]
> ah. You need the 15.4 adapter if you have react < 15.5 - if you run `npm ls`, you’ll see that your dep graph is currently invalid.

Thank You for your reply. 

I have followed the steps mentioned above but this time as you suggested i ran 
`npm i --save-dev enzyme enzyme-adapter-react-15.4`

instead of `npm i --save-dev enzyme enzyme-adapter-react-15`

which added `"enzyme-adapter-react-15.4": "^1.4.0",` in my devDependencies. 
Now I am running into this error : 
  **Cannot find module 'react-addons-test-utils' from 'ReactFifteenFourAdapter.js'**

I have tried deleting node modules and reinstalling all and then followed these steps but I am still having the same issue. 
I have even tried `npm i --save-dev enzyme enzyme-adapter-react-15.4` and `npm i --save-dev react-test-renderer@15.4`

**Comment by sherazahmedse** [comment]
Hello everyone, 

I wasn't able to figure out the proper solution for this issue, but I have successfully configured enzyme with react in our project for which I had limitation for react version to upgrade. 

I have downgraded enzyme to version 2.0.0 and for now the `enzyme-adapter-react` is out of the picture. 

At the every end of this comment, I am sharing my complete project's package.json file hoping it might help someone out there. 

[Here](https://github.com/vjwilson/enzyme-example-jest) is the link of a sample project I followed for enzyme to work in my very old existing project and with some hit and trail I was able to make it work in my project by upgrading some packages. 


[from this project](https://github.com/vjwilson/enzyme-example-jest) I followed the exact same directory structure and replaced the content of `.babelrc` file as follows 

```
{
  "presets": ["@babel/preset-env","@babel/preset-react"]
}
```

Use `npm test `to run the the tests 

**Bonus** : Use `jest --coverage` if you are interested to see the code coverage 
by running  `jest --coverage`  command you will notice a new directory made at the same level as your `src` directory which look for `index.html`. location of this file inside coverage directory may differ depending upon the version of your Jest you're using. copy it's full path and paste inside your browser to see the code coverage generated by Jest. 


Moreover, I would the community to guide me to either close the original issue posted or to keep it open as I am new to community. 

Major take away from my project's `package.json` file

```
{
  "scripts": {
    "test": "jest"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.5.2",
    "@babel/preset-react": "^7.0.0",
    "babel": "^6.3.26",
    "babel-jest": "^6.0.1",
    "babel-polyfill": "^6.16.0",
    "babel-preset-airbnb": "^1.0.1",
    "babelify": "7.2.0",
    "enzyme": "^2.0.0",
    "jest": "^24.8.0",
    "jest-cli": "^24.8.0",
    "react-addons-test-utils": "^0.14.7",
  },
  "dependencies": {
    "react": "15.0.1",
    "react-dom": "15.0.1"
  }
}
```


Complete Content of my project's `package.json` file
```
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "scripts": {
    "gulp": "node_modules\\.bin\\gulp.cmd",
    "test": "jest"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.5.2",
    "@babel/preset-react": "^7.0.0",
    "babel": "^6.3.26",
    "babel-jest": "^6.0.1",
    "babel-polyfill": "^6.16.0",
    "babel-preset-airbnb": "^1.0.1",
    "babelify": "7.2.0",
    "bower": "1.8.4",
    "browserify": "13.0.0",
    "classnames": "2.2.3",
    "envify": "4.1.0",
    "enzyme": "^2.0.0",
    "event-stream": "3.3.2",
    "fs": "0.0.1-security",
    "glob": "7.0.3",
    "gulp": "3.9.1",
    "gulp-clean-css": "3.7.0",
    "gulp-minify": "0.0.15",
    "gulp-notify": "3.2.0",
    "gulp-rename": "1.2.2",
    "gulp-uglify": "1.5.3",
    "gulp-util": "3.0.8",
    "gulp-watch": "4.3.5",
    "jest": "^24.8.0",
    "jest-cli": "^24.8.0",
    "react-addons-test-utils": "^0.14.7",
    "streamify": "0.2.5",
    "vinyl-buffer": "1.0.0",
    "vinyl-source-stream": "1.1.0",
    "vinyl-sourcemaps-apply": "0.2.1",
    "watchify": "3.11.0",
    "xmldom": "0.1.27",
    "xpath": "0.0.24"
  },
  "dependencies": {
    "bootstrap-datepicker": "1.6.0",
    "griddle-react": "0.6.1",
    "icheck": "1.0.2",
    "jquery": "2.1.4",
    "jquery-ui": "1.12.0",
    "flux": "2.1.1",
    "object-assign": "4.1.0",
    "react": "15.0.1",
    "react-checkbox-list": "0.0.2",
    "react-dom": "15.0.1",
    "react-icheck": "0.3.4",
    "react-validation": "1.7.2",
    "validator": "5.3.0",
    "react-tabs": "0.7.0",
    "react-tab-panel": "2.2.2",
    "react-select": "1.0.0-rc.2",
    "react-bootstrap-datetimepicker": "0.0.22",
    "rc-time-picker": "3.6.4",
    "moment": "2.18.1",
    "react-checkbox-tree": "0.6.4",
    "detect-browser": "1.6.2",
    "ip": "1.1.4",
    "lodash": "4.13.1",
    "es6-promise": "4.1.1",
    "json5": "0.5.1",
    "guid": "0.0.12",
    "get-ip": "2.0.0",
    "array.prototype.find": "2.0.4",
    "babel-polyfill": "6.26.0",
    "react-addons-create-fragment": "15.6.2",
    "rsvp": "4.8.2",
    "react-chartjs-2": "2.7.0",
    "chart.js": "^2.7.2"
  }
}
```

**Comment by ljharb** [comment]
react-addons-test-utils is a peer dep of the 15.4 adapter, which means that like react and react-dom, you have to install it manually. npm ls reports these.
