### ISSUE TITLE
shallow text() returns 'TouchableText' instead text itself. 

### ISSUE THREAD

**Issue by donghopark** [airbnb/enzyme#2188]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

### Current behavior

```
const text = 'some text';
const wrapper = shallow(<Text>text</Text>);
expect(wrapper.text()).toBe(text);

Enzyme shallow returns '<TouchableText />'
```

### Expected behavior

```
const text = 'some text';
const wrapper = shallow(<Text>{text}</Text>);
expect(wrapper.text()).toBe(text);

Enzyme shallow returns 'some text'
```

#### API

- [ v ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               | 16.8.6
| react-dom           |  16.8.6
| react-test-renderer | 16.8.3
| adapter (below)     |  1.14.0

#### Adapter

- [ v ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is expected because a shallow wrapper of X is whatever X renders, not X itself - additionally, shallow takes a react element, not a string.

What happens if you shallow wrap a component that renders your desired text?

**Comment by donghopark** [comment]
The problem here is that it returns 'TouchableText'. It looks happening only in some environment. In other environments, it returns 'some text' correctly.

**Comment by ljharb** [comment]
One issue i see is that your react-test-renderer version is 16.3 while your react is 16.8; those always need to be the same minor.

Separately though, what does `shallow(<Text />).debug()` print out? If it renders a TouchableText component that *in turn* renders text, then you'd need to do `shallow(<TouchableText />).text()` to get that text.

**Comment by donghopark** [comment]
react and react-test-renderer minor versions are all 8. 16.8.3 and 16.8.6. Do you mean that all patch ( the latest) should be same?

**Comment by ljharb** [comment]
Oh, nvm, i misread. In that case that’s not it - the other point still stands, tho.

**Comment by ParkDongJo** [comment]
I have same Issue.

**Comment by ParkDongJo** [comment]
> One issue i see is that your react-test-renderer version is 16.3 while your react is 16.8; those always need to be the same minor.
> 
> Separately though, what does `shallow(<Text />).debug()` print out? If it renders a TouchableText component that _in turn![](https://storage.googleapis.com/liner-safari-extension/tooltip/comment-icon%402x.png)_ renders text, then you'd need to do `shallow(<TouchableText />).text()` to get that text.


TouchableText is what? i can't search about TouchableText element in google or anywhere..

also impossible about that "shallow(<TouchableText />).text()", because can't import TouchabeText from anywhere

**Comment by ljharb** [comment]
Can you share the code for “Text”?

If this is the react native primitive, without an actual react native enzyme adapter, you won’t be able to reliably use enzyme with react - follow #1436 for that.

**Comment by donghopark** [comment]
shallow(<Text />).debug() results in below.

<TouchableText forwardedRef={{...}} accessible={true} allowFontScaling={true} ellipsizeMode="tail">
some text
</TouchableText>

**Comment by ljharb** [comment]
And the code for the Text component?

**Comment by donghopark** [comment]
What do you mean by 'the code for the Text component'?

```
const text = 'some text';
const wrapper = shallow(<Text>text</Text>);
expect(wrapper.text()).toBe(text);
```

is the code to test the enzyme and the Text component. 'Text' is the primitive RN component.

**Comment by ljharb** [comment]
OK, so then the answer is
> If this is the react native primitive, without an actual react native enzyme adapter, you won’t be able to reliably use enzyme with react - follow #1436 for that.

enzyme does not support React Native without a react-native adapter, which as far as I know does not yet exist.

Closing in lieu of #1436.

**Comment by RahulkumarRV** [comment]
const text = 'some text';
const wrapper = shallow(<Text>{text}</Text>);
const textNode = wrapper.find('Text')

expect(textNode.children().text()).toEqual(text);
it works for me
