### ISSUE TITLE
Shallow rendering not working properly with composed components

### ISSUE THREAD

**Issue by tarciosaraiva** [airbnb/enzyme#219]
Hi guys
the following HOC:
```
import React, { Component, PropTypes } from 'react'

const Adder = (title) => class extends Component {
  constructor (props) {
    super(props)
    this.inputField = ''
  }

  render () {
    return (
      <div className='add-item pure-form pure-g'>
        <div className='pure-u-24-24'>
          <h4>Add a new {title}</h4>
        </div>
        <div className='pure-u-19-24'>
          <input className='pure-input-1' placeholder='Enter name...' type='text' ref={(node) => { this.inputField = node }} />
        </div>
        <div className='pure-u-5-24'>
          <button className='pure-button pure-button-primary'>
            Add {title}
          </button>
        </div>
      </div>
    )
  }
}

Adder.propTypes = { createFn: PropTypes.func.isRequired }

export default Adder
```

Being used this way in another component...
```
import Adder from './enhancer/Adder'
export class Projects extends Component {
  ...
  render () {
    const AddProject = Adder('Project')
    ...
    return (
      <div className='projects'>
        <h2>Projects</h2>
        <ul>{projects}</ul>
        <AddProject createFn={this.create} />
      </div>
    )
  }
}
```

Causes the entire HTML of the HOC to be part of the HTML generated by the Projects component. This is fine, it's expected.

The test though doesn't seem to recognise it. In my assertion I'm looking for the class `.add-item` inside the HOC and although it is rendered in the HTML - invoking `wrapper.html()` I get the DOM rendered properly - when I assert `wrapper.find('.add-item')` it doesn't find the element.

You can find the HOC and the Projects component [here](https://github.com/tarciosaraiva/tasker-react/tree/master/src/app/components) and the [tests here](https://github.com/tarciosaraiva/tasker-react/tree/master/test/components).

**Comment by ljharb** [comment]
You're putting propTypes on `Adder` - but `Adder` isn't the component, the component it *returns* is - perhaps you want to attach the propType definitions inside `Adder`?

But, at any rate, shallow rendering is supposed to be shallow - meaning that the contents of `AddProject` won't be rendered - but `wrapper.find('AddProject')` should have a `length` of 1.

**Comment by tarciosaraiva** [comment]
Hi @ljharb it's a different kind of component - actually, not even a HOC. In can be classified as a pure function component, although it does take some other methods inside the function... being the way it is, the `propTypes` is in the right place.

Said that though, giving a name to the component solved my problem with shallow rendering. Now, with this `const Adder = (title) => class Adder extends Component {` I can do `wrapper.find('Adder')` which makes sense since my component is the Adder and not the returned object the component function is returning by `render`.

In any case, thanks for this.

**Comment by ljharb** [comment]
Adder isn't a component nor a function that returns JSX - so i'm pretty sure those propTypes do nothing at all, including issuing a warning if you violate them. If in fact React will enforce propTypes for you on a non-component then I'd love to read more about that?

**Comment by vlad-hgdata** [comment]
You can also try `wrapper.dive().find('.add-item')`

**Comment by vladCovaliov** [comment]
You can also try wrapper.dive().find('.add-item')
