### ISSUE TITLE
error during mount(...) causes all subsequent mount(...) calls to fail

### ISSUE THREAD

**Issue by magus** [airbnb/enzyme#2192]
### Simple repro
```js
describe('error', () => {
  test('throw error', () => {
    const ThrowAnError = () => {
      throw new Error('blah');
    };
    try {
      mount(<ThrowAnError />);
    } catch {}
  });

  test('should pass', () => {
    const wrapper = mount(<div />);
    expect(wrapper.exists()).toEqual(true);
  });
});
```

### Current behavior
subsequent `mount(...)` calls return an empty wrapper

### Expected behavior
subsequent `mount(...)` calls do not return an empty wrapper

### Your environment
enzyme@3.10.0 + jest 24 on OSX

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               |  16.5.2
| react-dom           |  16.5.2
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by lamhieu-vk** [comment]
Could you please explain more about the issue? I see current and expected behavior but I don't understand.
![image](https://user-images.githubusercontent.com/9839768/74358177-9aef7f00-4df3-11ea-8c81-d675e8554051.png)

**Comment by ljharb** [comment]
`wrapper.exists()` probably isn't the right thing to be checking; what does `wrapper.debug()` output in the second case?

**Comment by lamhieu-vk** [comment]
Output of debug is `<div />`

**Comment by ljharb** [comment]
Seems like things are working fine then? Perhaps it's been fixed in the interim.

I'll close for now, but happy to reopen if there's a repro.
