### ISSUE TITLE
ReactWrapper can only wrap valid elements jest and enzyme

### ISSUE THREAD

**Issue by santosh279** [airbnb/enzyme#2207]
I have a component that serves the data from the store to the nested HOC but when I trying to test the component I am getting an error stating "ReactWrapper can only wrap valid elements"

**Comment by OmriGM** [comment]
Hello @santosh279 ,

Are you using `mount` or `shallow`?
Can provide some of the code you used?

Consider looking at this: https://stackoverflow.com/questions/53453437/error-typeerror-reactwrapper-can-only-wrap-valid-elements-when-using-enzyme

**Comment by ljharb** [comment]
Closing pending repro info.
