### ISSUE TITLE
State not being updated after calling a prop method that should update state

### ISSUE THREAD

**Issue by dannytatom** [airbnb/enzyme#2209]
I'm sure this is a mistake on my end, but I'm not really finding any information on why this wouldn't be working so trying here. Sorry if this the wrong place for that.

### Current behavior

Full code: https://gist.github.com/dannytatom/7a10db9a702aec9c81922162bb3e3571

Excerpts:

```typescript
// Main component
const [ query, setQuery ] = useState('')
const debouncedSetQuery = debounce(value => setQuery(value || ''), 500);

if (query.length >= 2) {
  <NavbarSearchDropdownMenuView />
}

return <NavbarSearchView setQuery={ debouncedSetQuery } />

// Form NavbarSearchView
<FormControl name="search" type="text" placeholder="Search" className="mr-sm-2"
  onChange={
    (e: React.FormEvent<FormControlProps>) => props.setQuery(e.currentTarget.value || '')
  }
/>

// In test (using mount)

expect(component.exists(NavbarSearchDropdownMenuView)).toBe(false);

component.find(FormControl).props().onChange({
  currentTarget: {
    value: mock.result.data.searchScripts[0].title.substr(0, 3)
  }
});

expect(component.exists(NavbarSearchDropdownMenuView)).toBe(true); // => false
```

### Expected behavior

`expect(component.exists(NavbarSearchDropdownMenuView)).toBe(true)` should return true, since the `onChange` even of the FormControl should set the state of the main component. Using `component.debug()`, it doesn't look like it's changing the state at all.

I've also tried adding a `wrapper.update()` but didn't make a difference.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.10.0
| react               | ^16.7.0
| react-dom           | ^16.7.0
| react-test-renderer | N/A
| adapter (below)     | ^1.0.5

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by bezreyhan** [comment]
I'm running into a similar issue. I have a component that look like: 

```
const SignUpForm = () => {
  const [email, setEmail] = useState('');

  const handleEmailChange = (e) => {
    setEmail(e.target.value);
  };

  return (
    <form>
      <TextInput
          autoComplete="email"
          onChange={handleEmailChange}
          value={email}
      />
    </form>)
}
```

// Tests

```
it('passes the test', () => {
    const wrapper = mount(<SignUpForm />);
    const event = { target: { value: 'test@test.com' } };
    const emailInputComponent = wrapper
      .find(TextInput)
      .filter('[autoComplete="email"]');
    act(() => {
      emailInputComponent.prop('onChange')(event);
    });
    console.log('value: ', emailInputComponent.prop('value'));
  });
});
```

The problem is that `emailInputComponent.prop('value')` is returning `undefined`. 

Though, when I add logging to the `handleEmailChange` I see that it is being called. It looks like either the state is not updating or the `wrapper` is not reflecting the updates. I tried called `wrapper.update()` but that did not help.

Thanks for the help!

**Comment by dannytatom** [comment]
@bezreyhan Yeah, I also tried wrapping in `act` but doesn't seem to make a difference.

**Comment by Bates550** [comment]
@dannytatom, does the test pass if you remove the debouncing?

**Comment by dannytatom** [comment]
@Bates550 It's been a while since I touched this code, but I'm pretty sure it did. Moved on from this project, though (aye ADD), so gonna close this issue.
