### ISSUE TITLE
How can I infer state from the component? (TS)

### ISSUE THREAD

**Issue by viktor-ku** [airbnb/enzyme#2224]
Hi, everyone!

I have this question, it's about reducing boilerplate amount of code required to write one test. Originally posted in react issues, but felt like you might know the answer as well because it is tightly coupled with the `enzyme`.

[Original thread](https://github.com/facebook/react/issues/16553)

Thanks in advance :heart:

**Comment by ljharb** [comment]
This project isn’t authored in TS; i think the typescript repo is a better place to ask general TS questions, for react or otherwise.

**Comment by viktor-ku** [comment]
Thanks
