### ISSUE TITLE
Why instance() is not returning me correct TS types for the component?

### ISSUE THREAD

**Issue by viktor-ku** [airbnb/enzyme#2225]
Hi, everyone! I've got a small question. 

### Example

```ts
const props = {
  todos: []
}

const wrapper = shallow(<TodoList {...props} />);

wrapper.instance().submit() // Property 'submit' does not exist on type 'Component<{}, {}, any>'.ts(2339)
```

I understand that I probably have to manually pass the interface, but it doesn't feel right because I am already passing in the component, can't it infer the methods from it?

### Quick fix

```ts
const props = {
  todos: []
}

const wrapper = shallow<TodoList>(<TodoList {...props} />);

wrapper.instance().submit() // works!
```

Thanks :heart:

**Comment by ljharb** [comment]
I don’t maintain the DT types for enzyme; i believe this is a known limitation with TS and jsx, but you’d have to file an issue on DT for it.

**Comment by viktor-ku** [comment]
Thanks
