### ISSUE TITLE
Got unknown error when using "Mount" method

### ISSUE THREAD

**Issue by freezen** [airbnb/enzyme#2228]
I was trying to add test case to my project with enzyme, but got some error here, pls take a look, many thanks.
![image](https://user-images.githubusercontent.com/1651050/64012047-7f4b3180-cb4f-11e9-9ad3-c264476c7e73.png)

Code below: (if I use shallow or render, it works fine, but not for "mount")
```jsx
//mount test
const renderWrapper = mount(
    <ProjectListPopup 
        createProgram={jest.fn()}
        projectNameCheck={jest.fn()}
        history={{}}
        closeProgramPopUp={jest.fn()}
        editProgram={jest.fn()}
        projectList={[
            {
                "programName": "RoseProjectVI_1",
                "programType": "image",
                "createdBy": "sadaeer@xx.xx",
                "isPublic": true,
                "description": "This is a VI project 1",
                "createdTime": 1566900073172,
                "labelIds": {
                    "61PsHWwBXF6N6JeXs4Uv": "7FPsHWwBXF6N6JeXs4VZ,2f3CaWwBTYWgQWRNP2Pg",
                    "XjI3-msBnTe-5nxnlhmA": "YzI3-msBnTe-5nxnphmA,XzI3-msBnTe-5nxnlhml,skPgZGwBb8cw-IfErv7N,YTI3-msBnTe-5nxnmBmu,YjI3-msBnTe-5nxnnRlX,YDI3-msBnTe-5nxnlxl2"
                },
                "modelNumber": 0,
                "labelNumber": 8,
            },
        ]}
    />
)
```

**Comment by ljharb** [comment]
Are you running your tests with NODE_ENV as production? it should be "test" or "development" or unset.

**Comment by freezen** [comment]
I use "test", but got same. @ljharb 
![image](https://user-images.githubusercontent.com/1651050/64071197-02cb6680-cca7-11e9-8b0f-4baa6b302373.png)

![image](https://user-images.githubusercontent.com/1651050/64071210-35755f00-cca7-11e9-8730-69950992e498.png)

**Comment by ljharb** [comment]
(Please include text, not screenshots, of stack traces)

What does the code of ProjectListPopup look like? Have you tried mounting each of those?

**Comment by freezen** [comment]
I try to make the component easier that can locate the error position, now I got error below:

 FAIL  src/components/role_Modeler/projectList/components/ProjectListPopup.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getPublicInstance' of undefined
      
      at WrapperComponent.getWrappedComponent (node_modules/enzyme/build/ReactWrapperComponent.js:95:32)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:100:34)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/components/role_Modeler/projectList/components/ProjectListPopup.test.js:52:39)
      at process._tickCallback (internal/process/next_tick.js:68:7)


My component: (changed to make it simple, but still got error)

import React, { Component } from "react";
import * as PropTypes from "prop-types";

export default class ProjectListPopup extends Component {
  static propTypes = {
   
  };

  constructor(props) {
    super(props);
    this.state = {
     
    };
  }

  render() {
    let _this = this;
    return (
      <div className={`importFilesPopup`} style={{}}>
        <button>
            Cancel
        </button>
        <button>
            Submit
        </button>
      </div>
    );
  }
}



package.json:
"devDependencies": {
    "babel-jest": "20.0.3",
    "enzyme": "2.9.1",
    "jest": "20.0.4",
    "jest-css-modules-transform": "1.0.2",
    "react-test-renderer": "16.5.2"
  },

**Comment by ljharb** [comment]
Your react-test-renderer version must have the same exact minor version as react and react-dom; you’ve got 16.5.2, what version of react and react-dom do you have?

**Comment by freezen** [comment]
As you said, I update the react-test-renderer version to 16.8.0, but still got error: 

"dependencies": {
    "assets-webpack-plugin": "3.5.1",
    "axios": "0.18.0",
    "babel-core": "6.4.5",
    "babel-loader": "6.2.1",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-remove-strict-mode": "0.0.2",
    "babel-polyfill": "6.26.0",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-0": "6.3.13",
    "carbon-addons-cloud": "2.2.0",
    "carbon-addons-cloud-react": "1.5.1",
    "carbon-components": "9.58.0",
    "carbon-components-react": "6.112.1",
    "carbon-icons": "7.0.7",
    "css-loader": "0.23.1",
    "css-modules-require-hook": "4.2.3",
    "expose-loader": "0.7.3",
    "express": "4.17.1",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.4",
    "history": "4.7.2",
    "identity-obj-proxy": "3.0.0",
    "immutable": "3.8.1",
    "jest-cli": "20.0.4",
    "json-loader": "0.5.4",
    "mockjs": "1.0.0",
    "prop-types": "15.6.1",
    "query-string": "6.2.0",
    "react": "16.8.0",
    "react-addons-css-transition-group": "15.6.0",
    "react-addons-update": "15.6.2",
    "react-dom": "16.8.0",
    "react-intl-universal": "1.4.3",
    "react-redux": "5.1.0",
    "react-router-dom": "4.2.2",
    "redux": "4.0.0",
    "redux-immutable": "3.0.6",
    "redux-thunk": "2.3.0",
    "storm-react-diagrams": "5.2.1",
    "style-loader": "0.13.0",
    "sync-request": "^6.1.0",
    "url-loader": "0.5.6",
    "wavesurfer.js": "2.1.2",
    "webpack": "1.12.11",
    "webpack-dev-server": "1.14.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "enzyme": "2.9.1",
    "jest": "20.0.4",
    "jest-css-modules-transform": "1.0.2",
    "react-test-renderer": "16.8.0"
  },

**Comment by ljharb** [comment]
What does `npm ls` say? If that exits nonzero you can't rely on anything working.

**Comment by freezen** [comment]
it say "npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.9.1", but I think react 16 is supported?

**Comment by ljharb** [comment]
Yes, but not with enzyme 2, which is years obsolete. Do you need to upgrade to enzyme 3?

**Comment by freezen** [comment]
I tried with V3, now it works when use mount method with the simple component now, but still for the original one, I will check its child component as you mentioned, will come back if any new find out. Thx.

Current config: 
   "babel-jest": "20.0.3",
    "enzyme": "3.7",
    "enzyme-adapter-react-16": "^1.14.0",
    "jest": "20.0.4",
    "jest-css-modules-transform": "1.0.2",
    "react-test-renderer": "16.8.0"

**Comment by ljharb** [comment]
Closing for now, happy to reopen if there’s an issue with enzyme 3.

**Comment by freezen** [comment]
@ljharb ,  I finally found out the root cause in it, it is caused by a 3rd-party component lib:

                    <Tooltip clickToOpen={false} triggerText="" tabIndex={0}>
                      <p className="bx--tooltip__label">{intl.get('vi_tooltips')}</p>
                    </Tooltip>

Everything works fine if remove it now, thx.
