### ISSUE TITLE
wrapper.find(Component).state() is "null" when it is observed by "MobX"

### ISSUE THREAD

**Issue by jevonsofcode** [airbnb/enzyme#2230]
## Current

My '.test.jsx' code is 

```
describe('it's a mock', () => {
    let wrapper;
    let Mock;

    beforeEach(async () => {
        Mock = await require('Screens/mock/index.tsx').default;
        wrapper = mount(<MemoryRouter><Provider {...Stores}><Route path="/mock" render={props => <Mock {...props} />} /></Provider></MemoryRouter>);
        wrapper.instance().history.push({
            pathname: '/mock',
            state: {
                param: 'the mock'
            }
        });
        wrapper.update();
        console.log('----------------~>', wrapper.find(Mock).instance().state);
    });
})
``` 

## Result

when I component's code is

```
@inject("xxx", "xxx")
@observer
export default class theComponent extends React.Component<IStore, IState> {
    constructor(props: IStore) {
        super(props);
        this.state = {
            param: "mock"
        };
    }
    render() {
        return(...)
    }
}
```

that 'console'  in test code is null

but when I remove the @observer

console have content (param)

## Link

Similar to [this](https://github.com/airbnb/enzyme/issues/1851#issuecomment-427809625)

## Expected behaviour

`wrapper.find(Mock).instance().state` can obtain the state when that is observed by mobx

## Version

```
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-adapter-react-16.2": "^1.6.1",
    "enzyme-to-json": "^3.4.0",
    "jest": "^23.6.0",
    "jest-environment-enzyme": "^7.0.2",
    "jest-environment-jsdom": "^23.4.0",
    "jest-environment-node": "^23.4.0",
    "jest-enzyme": "^6.0.0",
    "react": "16.2.0",
    "react-native": "0.52.0"
```

thanks

**Comment by ljharb** [comment]
I’m not familiar with MobX; I’d expect that if it doesn’t match react exactly, that you’d need a MobX adapter, not a react adapter.

**Comment by ljharb** [comment]
Also, what about `wrapper.state()`? The instance is a last resort/escape hatch.

**Comment by jevonsofcode** [comment]
> Also, what about `wrapper.state()`? The instance is a last resort/escape hatch.

`wrapper.state()` not success either

**Comment by ljharb** [comment]
In that case it’s likely that MobX deviates from react, which means many things might not work without a mobx adapter.

**Comment by jevonsofcode** [comment]
> In that case it’s likely that MobX deviates from react, which means many things might not work without a mobx adapter.

Right, so I'm looking for a solution to observer reversely 

QAQ
