### ISSUE TITLE
Using invoke in act() requires manual update

### ISSUE THREAD

**Issue by Shadowlauch** [airbnb/enzyme#2231]
# Current behavior

If I use invoke in act() on a function of a mounted function component, that sets a state in that invoked method, I have to manually call update for the state to be updated in my JSX

### Expected behavior

I would expect the state  to be automatically updated

### Your environment

Here is a minimal test case:

```
it('should update state', () => {
    const component = mount(<TestA/>);

    act(() => {
        component.find(TestB).invoke('onTest')(true);
    });

    console.log('assert');
    expect(component.find(TestB).prop('state')).toEqual(true);
    component.update();
    expect(component.find(TestB).prop('state')).toEqual(true);
});

const TestA = () => {
    const [state, setState] = useState<boolean>(false);

    return (<TestB onTest={(t: boolean) => {
        setState(t);

        console.log('act')
    }} state={state} />);
};

const TestB: FC<any> = () => {
    return null;
};
```

The first expect fails in my case.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               |  16.8.6
| react-dom           | 16.8.6

#### Adapter

- [x] enzyme-adapter-react-16 | 1.14.0
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Invoke wraps in act for you; do you find the explicit act wrapping is required?

**Comment by Shadowlauch** [comment]
@ljharb they test passes without the act, but I get the following warning:

```
console.error node_modules/react-dom/cjs/react-dom.development.js:506
    Warning: An update to TestA inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in TestA (created by WrapperComponent)
        in WrapperComponent
```

**Comment by Shadowlauch** [comment]
@ljharb It seems like the invoke wrapping you are talking about is in your current master branch, but not it the latest release d2bb6554c57af7eda789f63059c76ae029e9f64e

**Comment by ljharb** [comment]
aha, well that makes sense :-)

master is currently failing due to the 16.9 release; releases are blocked on that. I'll publish one as soon as I can.

**Comment by Shadowlauch** [comment]
Thanks for the quick response! Have a good one.

**Comment by davidli16** [comment]
Are there plans for a new release of Enzyme? I noticed there have been releases to the adapters, but the core framework still needs to be updated to include https://github.com/airbnb/enzyme/commit/d2bb6554c57af7eda789f63059c76ae029e9f64e#diff-f51a48d4631e74e85755869409584c3f to enable the wrapped invoke functionality.
