### ISSUE TITLE
Enzyme detects linux .snap package file as obsolete enzyme snapshot

### ISSUE THREAD

**Issue by nahuelarjonadev** [airbnb/enzyme#2232]
If you haven't found any duplicated issues, please report it with your environment!

### Current behavior
Jest with enzyme is detecting a .snap package I built for Linux as an obsolete snapshot, and it's causing my tests to fail.

### Expected behavior
Being able to ignore the path to the release folder, so Enzyme doesn't try to parse it as an enzyme snapshot
#### API

- [x] shallow
- [x] mount
- [x] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.9.0
| react-dom           | 16.9.0
| react-test-renderer | 16.6.0
| adapter (below)     | enzyme-adapter-react-16
| jest | 24.9.0
| babel-jest | 24.9.0

**Comment by ljharb** [comment]
enzyme has no snapshot support and doesn’t recommend using snapshots; you’re probably using some other package to do snapshot testing.
