### ISSUE TITLE
Unable to access state hook inside of event handler

### ISSUE THREAD

**Issue by briantownley-wpe** [airbnb/enzyme#2236]
### Current behavior
When invoking an event handler in a component, state hooks are not accessible in the event handler code. To be clear, this only appears to happen inside of event handlers - any other functions are able to access state hooks correctly.

### Expected behavior
State hooks are accessible in all functions within a component regardless of whether they are event handlers.

### Your environment
Sample React code that illustrates the problem:
```
import React, { useState } from 'react';
import PropTypes from 'prop-types';

const OmniSearchBar = ({
  onSubmitSearch,
}) => {
  const [query, setQuery] = useState('');

  const valueChanged = (evt) => {
    setQuery(evt.target.value);
  };

  const enterPressed = (evt) => {
    const code = evt.keyCode || evt.which;
    console.log("enterPressed: " + query);
    if (code === 13 && query.length > 2) {
      onSubmitSearch(query);
    }
  };

  console.log("render: " + query);
  return (
    <div className="omni-search-bar">
      <tr>
        <input
          type="search"
          placeholder="across all accounts"
          className="search-bar"
          onChange={valueChanged}
          value={query}
          onKeyPress={enterPressed}
        />
      </tr>
    </div>
  );
};

OmniSearchBar.propTypes = {
  onSubmitSearch: PropTypes.func.isRequired,
};

export default OmniSearchBar;
```

Test code using enzyme:
```
import React from 'react';
import OmniSearchBar from 'omni_search/OmniSearchBar';
import { shallow } from 'enzyme';

describe('OmniSearch/OmniSearchPage', () => {
  let onSubmitFunc;

  beforeEach(() => {
    onSubmitFunc = jest.fn();
  });

  it('three characters are required to initiate search', () => {
    const component = shallow(<OmniSearchBar onSubmitSearch={onSubmitFunc} />);
    const input = component.find('.search-bar');

    expect(input.exists()).toEqual(true);
    expect(component).toMatchSnapshot();

    input.simulate('keypress', { keyCode: 13 });
    expect(onSubmitFunc).not.toHaveBeenCalled();

    input.prop('onChange')({ target: { value: 'te' } });
    expect(component).toMatchSnapshot();
    input.simulate('keypress', { keyCode: 13 });
    expect(onSubmitFunc).not.toHaveBeenCalled();

    input.prop('onChange')({ target: { value: 'test1234' } });
    expect(component).toMatchSnapshot();
    input.simulate('keypress', { keyCode: 13 });
    expect(onSubmitFunc).toHaveBeenCalled();
  });
});
```

#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | n/a
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by douglasnaphas** [comment]
@briantownley-wpe: I find that it works as expected with your example if I re-find the `input` element after each time state changes.

I ran your example, and indeed the test fails and prints output showing `query` being updated outside the event handlers, but not within them:
```
$ git checkout c7fe19a33f0352951155a142deb3c2ea902565fb
$ CI=true npm test

> react-app-2@0.1.0 test /Users/dougnaphas/repos/react-app-2
> react-scripts test

PASS src/App.test.js
FAIL src/OmniSearchBar.test.js
  ● Console

    console.log src/OmniSearchBar.js:19
      render:
    console.log src/OmniSearchBar.js:13
      enterPressed:
    console.log src/OmniSearchBar.js:19
      render: te
    console.log src/OmniSearchBar.js:13
      enterPressed:
    console.log src/OmniSearchBar.js:19
      render: test1234
    console.log src/OmniSearchBar.js:13
      enterPressed:

  ● OmniSearch/OmniSearchPage › three characters are required to initiate search

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      32 |     expect(component).toMatchSnapshot();
      33 |     input.simulate("keypress", { keyCode: 13 });
    > 34 |     expect(onSubmitFunc).toHaveBeenCalled();
         |                          ^
      35 |   });
      36 | });
      37 |

      at Object.toHaveBeenCalled (src/OmniSearchBar.test.js:34:26)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   3 passed, 3 total
Time:        2.205s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
The above is with [this commit](https://github.com/douglasnaphas/react-app-2/commit/c7fe19a33f0352951155a142deb3c2ea902565fb) of my project containing your sample code checked out.

When I re-find the `input` following each state change, done with [this commit](https://github.com/douglasnaphas/react-app-2/commit/9ae4be0d56bda8ddc9edb6b9d1bda0fddb88eef5), the values of `query` are as expected at every stage, and the test passes.

```
$ git checkout 9ae4be0d56bda8ddc9edb6b9d1bda0fddb88eef5
$ CI=true npm test

> react-app-2@0.1.0 test /Users/dougnaphas/repos/react-app-2
> react-scripts test

PASS src/App.test.js
PASS src/OmniSearchBar.test.js
  ● Console

    console.log src/OmniSearchBar.js:19
      render:
    console.log src/OmniSearchBar.js:13
      enterPressed:
    console.log src/OmniSearchBar.js:19
      render: te
    console.log src/OmniSearchBar.js:13
      enterPressed: te
    console.log src/OmniSearchBar.js:19
      render: test1234
    console.log src/OmniSearchBar.js:13
      enterPressed: test1234


Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   3 passed, 3 total
Time:        1.828s, estimated 2s
Ran all test suites.
```

It seems the reference stored in `input` is stale after the state changes. I don't understand why, when I ran your example code, the value of `query` was updated _outside_ of the event handlers--I just personally always re-find the elements I want to interact with right before I interact with them, to make sure they're up to date.

**Comment by ljharb** [comment]
This is an intentional change in enzyme 3 - see https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved.
