### ISSUE TITLE
No unmount function in ShallowWrapper

### ISSUE THREAD

**Issue by dobryanskyy** [airbnb/enzyme#224]
Hi,

when trying to run this code (doesn't matter which element i'm shallow-ing)
```
it.only('no unmount function with shallow', () => {
    let element = shallow(<DevicesPage />);
    element.unmount();
});
```
i get following error: 

`TypeError: element.unmount is not a function`

and debugging shows that `unmount` is undefined here. 
However all other items from ShallowWrapper are in place. 

Is `unmount` a part of ShallowWrapper as [documentation](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/unmount.md) states? And if it is then what am i doing wrong here?

**Comment by ljharb** [comment]
@dobryanskyy `unmount` will be in the next release, but isn't released just yet. the docs currently point to latest master, not to the latest release.

**Comment by dobryanskyy** [comment]
Oh, i see. 
Is there any workaround for me for now - just to test componentWillUnmount?

**Comment by ljharb** [comment]
At the moment - explicitly call it in your unit test.

**Comment by dobryanskyy** [comment]
yep, that should work. Thanks you for such quick responses.
