### ISSUE TITLE
.instance() not getting me the instance of function component

### ISSUE THREAD

**Issue by p4pramod** [airbnb/enzyme#2241]
**FunComponent:**

import React, { useState } from 'react';

export default function FunComp(){

    function test() {
        console.log("2222222");
    }

    return (
        <div>
            hello
        </div>
    );
};

**AppComp**
import React, { Component } from 'react';

export default class AppComp extends Component {

    constructor(props) {
        super(props);
    }

    test() {
        console.log("1111111111111111");
    }

    render() {
        return (
            <div to='/'>Here is a link</div>
        );
    };
}

Test:

And in my test when i am trying to following code 
    describe('basic rendering tests', function () {

     it.only('test', function () {
const selfAccounts = {  };

const store = mockStore({
            accounts: selfAccounts
        });

        wrapper2 = mount(
            <Provider store={store}>
                <AppComp />
               <FunComp></FunComp>
            </Provider>);

//This works and calls the test method
            **console.log(wrapper2.find(AppComp).instance().test());**
//This is not working and failing with message  :  TypeError: Cannot read property 'test' of null
          
  **console.log(wrapper2.find(FunComp).instance().test());**
        });
    });

Please suggest how to access the instance of the functional component.

**Comment by p4pramod** [comment]
I just read the following

```
Returns the single-node wrapper's node's underlying class instance; this in its methods.

NOTE: can only be called on a wrapper instance that is also the root instance. With React 16 and above, instance() returns null for stateless functional components.

```
I would like to understand that after the advent of hooks now functional component stateful. Then how it is handled in Enzyme??

**Comment by ljharb** [comment]
Functional components don’t have an instance in React 16+, it has nothing to do with hooks.

Separately, in your first example, the javascript language makes it impossible to ever access that closed-over function from outside the containing function, so that has nothing to do with enzyme or react.

**Comment by CristianoYL** [comment]
I had the same issue. I'm wondering if there is any way to test the methods within functional components at all? If not, what would be your recommended solution?
> Functional components don’t have an instance in React 16+, it has nothing to do with hooks.

I understand its logically irrelevant to Hooks or enzyme. However, if it's unsolvable, it would prevent people either from using Hooks or from testing them.

**Comment by ljharb** [comment]
@CristianoYL functions have no methods, only classes do - so no, you can't test things inside closures in JavaScript - that's the nature of the language.

Things inside closures are private, and private things should not be tested anyways. Test them implicitly by passing props and asserting on the render output of the component.

**Comment by vishwa3** [comment]
I too am using functional components and hooks with event handler methods but I think there's no way to test those event handling methods

**Comment by max77p** [comment]
@vishwa3 So how would I go about testing event handler methods?

**Comment by macaframa** [comment]
The pattern I have established for myself is that I create a service(es6 module) that is imported into the functional component and relies on pure the methods attached to this service being pure functions. You pass params to it and get something back. Not only is it good code hygiene but it makes your services testable. If you named things clearly enough then it wouldn't matter too much that it was in another file. However, the downside is that the business logic is now located outside of your component. That is not a great pattern. However, ideal patterns are what we sacrifice for exceptional coverage in situations like this.

**Comment by vjlicious** [comment]
i am facing the same issue .....

**Comment by seanlandsman** [comment]
Although this issue is closed, you could try wrapping your component with a `forwardRef` and expose the methods you want to use with `useImperativeHandle`.

For example:

```
const MyApp = forwardRef(function (props, ref) {
    useImperativeHandle(ref, () => {
        return {
            test() {
                return "test value";
            }
        }
    });
    
    return <div>My Component</div>
});
```

Then in your test you'd provide a `ref` to access the hook instance:

```
const ref = React.createRef()
component = mount(<App ref={ref}/>);
// ref.current will now have all exposed methods from MyApp
expect(ref.current.test()).toBe("test value")
```

You'll almost certainly have to wrap code with `act` (from @testing-library/react) to handle state/ref changes.

**Comment by shashwata27** [comment]
![image](https://user-images.githubusercontent.com/60866496/181933557-2e16792f-a1c7-46a6-be54-69109aa546ac.png)
HELP
