### ISSUE TITLE
SyntaxError: Unexpected identifier with ts-jest and typescript

### ISSUE THREAD

**Issue by DWboutin** [airbnb/enzyme#2242]
### Current behavior
In my project: https://github.com/DWboutin/gatsby-intl-redux-typescript Enzyme with Jest won't parse correctly the file provided in `jest.setup.js``

```FAIL  src/_components/Button/__tests__/Button.spec.tsx
  ● Test suite failed to run

    /Users/mikaelboutin/Desktop/self/gatsby-react-intl-starter/jest.setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Enzyme, { mount, render, shallow } from 'enzyme'
                                                                                                    ^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

### Expected behavior
Running test correctly

### Your environment
```
node -v: v10.16.3
npm -v: 6.9.0
```
#### API

- [x] shallow
- [x] mount
- [x] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.10.0
| react               | ^16.9.0
| react-dom           | ^16.9.0
| react-test-renderer | ^16.9.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is an issue with your jest setup; it's not related to enzyme. I'm not familiar with setting up a TS project.

**Comment by DWboutin** [comment]
Thank you, sorry for the trouble
