### ISSUE TITLE
spyOn anonymous function inside onClick

### ISSUE THREAD

**Issue by ajinkyaw-clarion** [airbnb/enzyme#2243]
Hi,

I have functional component in which I am doing onClick.
```
<div
 onClick={() => setIsVisible(false)}
 <Icon icon="close" />
</div>
```
While writing test cases for this I want 100% coverage. I identified that this anonymous function inside onClick is giving me problem while achieving 100% test coverage. For this I think I need to spyOn the anonymous function used inside onClick and check if it has been called. Can anyone let me about this.

Thanks!!

**Comment by ljharb** [comment]
You can't spy on things that aren't object properties - however, you can write a test that finds that div and does `.prop('onClick')()`.

**Comment by ajinkyaw-clarion** [comment]
OK...Thanks!!
