### ISSUE TITLE
react-addons-test-utils used, but not in package.json

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#225]
[react-compat#L73](https://github.com/airbnb/enzyme/blob/master/src/react-compat.js#L73) requires `react-addons-test-utils`

But it is not specified in the [package.json](https://github.com/airbnb/enzyme/blob/master/package.json)

Should it be a peerDep or something? This caused me a bit of confusion.

**Comment by ljharb** [comment]
See the comment on https://github.com/airbnb/enzyme/blob/master/src/react-compat.js#L70-L72
