### ISSUE TITLE
using wrapper.find isn't finding an html input even when using mount

### ISSUE THREAD

**Issue by dhuang612** [airbnb/enzyme#2251]
### Current behavior
trying to test an html input element when using mount it's returning an empty object.
I can see the input element using wrapper.debug()
```
test('can mount component keyboard numbers', t => {
  const wrapper = mount(<KeyboardNumberInput/>);
  const input = wrapper.find('input');
  console.log(wrapper.debug());
  console.log(input);
 
});
```

### Expected behavior
I am expecting wrapper.find to be able to get the html element
#### API

- [ ] shallow
- [ x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme           3.10.0   | 
| react            16.9.0   | 
| react-dom       16.9.0    | 
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 
<img width="545" alt="Screen Shot 2019-10-02 at 5 57 57 PM" src="https://user-images.githubusercontent.com/49162249/66085142-69f66800-e53e-11e9-8f4a-184c7244308b.png">

reactWrapper {} is what find returns

and the information with the html is what wrapper.debug() returns

Thanks

**Comment by OmriGM** [comment]
Hello @dhuang612 ,

In order to get the input element you need to use `.at(0)` to get the ShallowWrapper itself.
(https://airbnb.io/enzyme/docs/api/ShallowWrapper/at.html#atindex--shallowwrapper)
Then, in order to console log it you need to use `.debug()` on that wrapper like so:

```javascript
test('can mount component keyboard numbers', t => {
  const wrapper = mount(<KeyboardNumberInput/>);
  const input = wrapper.find('input').at(0);
  console.log(wrapper.debug());
  console.log(input.debug());
});
```

**Comment by dhuang612** [comment]
Hi,
Thanks, I was able to figure out where I went wrong with your example. 
I'll close this.
