### ISSUE TITLE
.toExist() no longer Exists but Still in Enzyme Docs for React Native

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#2252]
I think `toExists()` is no longer available in Jest, yet you still talk about it in your [docs](https://airbnb.io/enzyme/docs/guides/react-native.html).  What should we be using?  

I know in React Web, I use `expect(somecomponent.length).to.equal(1)` but just wanna be sure with native the equivalent and if we basically test things exactly the same as we do with React Web in general.

Here is an example react native test:

```
    it('shows send a hug button', () => {
        const home = shallow(<App/>);
        expect(home.findWhere(node => node.prop('testID') === 'hug')).toExist(); //bombs on me saying toExist is not a function
    });
```

Also `findWhere` with `node => node.prop('testID')` is kinda nasty.  Is that the only way with native and enzyme?

This seems to work, same idea as I do with React Web:

```
    it('shows send a hug button', () => {
        const home = shallow(<App/>);
        expect(home.findWhere(node => node.prop('testID') === 'hug').length).toBe(1);
    });
```

**Comment by ljharb** [comment]
All our docs use chai, not jest.

**Comment by dschinkel** [comment]
where is `.toExist()` coming from?  see [docs](https://airbnb.io/enzyme/docs/guides/react-native.html).  Is this a chai helper util cause chai is always .to.exist()

**Comment by ljharb** [comment]
ah, perhaps the matchers plugin stopped using that particular matcher. It'd be good to fix those examples.

**Comment by dschinkel** [comment]
I'll do a PR and help out with updating that.
