### ISSUE TITLE
mount: TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by ghasemikasra39** [airbnb/enzyme#2256]
### My code 
```javascript
describe('Some test', () => {
    test('mount', () => {
        const wrapper = mount(
            <View/>
        );
    })
});
```
### Current behavior
![image](https://user-images.githubusercontent.com/24314029/66253723-3ce1c980-e779-11e9-96b4-7cc94c506099.png)

### Your environment
```
System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 2.83 GB / 11.63 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.0 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
```

#### API
- [X] mount

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.8.3
| react-dom           | 16.10.1
| react-test-renderer | 16.8.3
| adapter (below)     | 1.14.0

#### Adapter
- [x] enzyme-adapter-react-16

**Comment by ljharb** [comment]
See https://github.com/airbnb/enzyme/issues/2004#issuecomment-538655762:
> @ghasemikasra39 your react, react-dom, and react-test-renderer must be on the same minor version - your react-dom is on 16.10.

**Comment by mmaksymovych** [comment]
@ljharb  that's different issues, I have exactly the same problem. It seems to me from logs that react dom is used instead of jsdom

**Comment by ljharb** [comment]
react-dom isn't a DOM implementation, so if you're in node, the only place `document` and friends can possibly come from is jsdom.

@mmaksymovych if you have the same problem but with different version results, please file a new issue, or post that info here, and i'll review.
