### ISSUE TITLE
State of the Union on Shallow in React Native????

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#2260]
It sounds like shallow rendering does not work well with React Native is that so?  Or at least for sure not with Redux connect.  Here's what we found:

**This worked (Straight Component not wrapped in an HOC):**
```
import { UserProfile } from "../../../src/components/UserProfile";

  it('shows a profile with name', () => {
    const store = fakeStore({ profile: { name: null }});

    const home = shallow(<UserProfile store={store} />);
    const name = home.findWhere(node => node.prop('testID') === 'user-name').dive();
    
    expect(name.text()).toBe("Dave");
  });
```

**UserProfile.js**

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Text } from 'react-native';
import { fetchUserProfile } from "../actions/UserProfileActionsCreators";

class UserProfile extends Component {
  constructor(props){
    super(props);
  }

  async componentDidUpdate(prevProps, prevState, snapshot?): void {
    const { fetchProfile } = this.props;
    await fetchProfile();
}
  render() {
    return <><Text testID="user-name">Dave</Text></>
  }
}

const mapStateToProps = state => ({
  name: state.profile.name
});

const mapDispatchToProps = {
  fetchProfile: fetchUserProfile
};
// without connect wrapper
export { UserProfile }
```

**This Did Not Work (Redux Connect HOC):**

```
import UserProfile from "../../../src/components/UserProfile";

  it('shows a profile with name', () => {
    const store = fakeStore({ profile: { name: null }});

    const home = shallow(<UserProfile store={store} />);
    const name = home.findWhere(home =>home.text() === "Thelma");
    expect(name.text()).toBe("Thelma");
    
    expect(name.text()).toBe("Dave");
  });
```

**Error: Method “text” is meant to be run on 1 node. 0 found instead.**
```
class UserProfile extends Component {
  constructor(props){
    super(props);
  }

  async componentDidUpdate(prevProps, prevState, snapshot?): void {
    const { fetchProfile } = this.props;
    await fetchProfile();
  }
  render() {
    return <><Text testID="user-name">Dave</Text></>
  }
}

const mapStateToProps = state => ({
  name: state.profile.name
});

const mapDispatchToProps = {
  fetchProfile: fetchUserProfile
};

// with connect wrapper
export default connect(mapStateToProps, mapDispatchToProps)(UserProfile)
```

**Other Observations / Questions:**

- Your docs read as though you must have jsdom enabled to shallow but shallow does not use jsdom under the hood:

[To use enzyme to test React Native, you currently need to configure an adapter, and load an emulated DOM](https://airbnb.io/enzyme/docs/guides/react-native.html)

-   It seemed like shallow rendering wasn't really rendering the react native component because I kept getting a length of 0 on the wrapper.

- Looks like in the latest version of React, we must use .at() on find()?

- Looks like you can't use `find()` on shallowed components with React Native.  I liked it when I could find things via `data-test` attributes in `React Web` but you can't do that, you are seemingly stuck with the `testID` attribute with Native, so when I tried the findAll() with node on `testID` I was not able to call .text() to get the name out of that <Text />.

- and **must** use `findAll` with `node` we can't use find()?

- **Rant**: we already know shallow won't work with React Hooks.  If the React team would stop chasing code rainbows, and insisting on trying to reinvent React 1000 times, (renderProps, to HOCs, to Hooks, to know knows wtf next) and instead simply promote good coding practices based on what was already working well in React prior to all this new shit (simple design by simply breaking shit out, keeping functions small, etc) then Redux and Enzyme wouldn't have to reinvent their codebases either every month just to try to keep stuff like shallow rendering "working" over a lib that was supposed to be kept simple (React)

**Comment by ljharb** [comment]
As is hopefully stated in #1436, enzyme has *zero* official support for React Native until a react-native adapter can be created, by whoever is willing to do the work.

Such an adapter would define "host nodes" as things like `Text` and `Image`, as opposed to `div` and other HTML elements; it would reject HTML elements as invalid, etc.

Closing in favor of #1436.
