### ISSUE TITLE
shallow render. getElement return anonymous function

### ISSUE THREAD

**Issue by DimaDaxDadeco** [airbnb/enzyme#2266]
My container return component smth like
`const App = ({ children }) => <div>{children}</div>`
And if i use shallow render and try to getElement i get

`{
      '$$typeof': Symbol(react.element),
      type: [Function],
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {}
    }
`

As we see type [Function]. But if component will be
`
function App({ children }) {
  return <div>{children}</div>;
}
`
getElement return us 

`{
      '$$typeof': Symbol(react.element),
      type: [Function: Api],
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {}
    }
`

It's a problem. Because i use snapshot tests and get `Unknown`:
`exports['<AppContainer /> render should render AppComponent if fetchStatus is SUCCESS 1'] = '<Unknown />'`

So i need to rewrite all my functional components on function. Maybe exists any other solution?

**Comment by ljharb** [comment]
This is because your arrow function doesn't have a name. SFCs should be normal, non-arrow functions anyways.

**Comment by DimaDaxDadeco** [comment]
@ljharb 
I already search a solution. I just mistake, it's not a enzyme problem. 
Here description of the problem: https://stackoverflow.com/questions/43458971/react-dev-tools-show-my-component-as-unknown

Problem:
`
export const App = ({ children }) => <div>{children}</div>
`

My solution:
`
const App = ({ children }) => <div>{children}</div>

export { App }
`

I think this question can be closed.
