### ISSUE TITLE
wrapper.toHaveBeenCalledWith() only shows the first 3 calls, please show more.

### ISSUE THREAD

**Issue by Fieel** [airbnb/enzyme#2267]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have more than 3 calls and i want to debug if a given call happened because the CLI only shows me the first 3 calls even though I have the debug the fourth or fifth call, how am I supposed to do that without even having some feedback from the CLI?

**Describe the solution you'd like**
I'd love to use a verbose command or something or to just be able to see all calls for debugging purposes. Using create-react-app we can't even customize the "react-scripts test" script without ejecting.
```

expect(jest.fn()).toHaveBeenCalledWith(...expected)
    Expected: {"payload": {"data": {}}, "type": "AGGIUNGI_CARATTERISTICA_SELEZIONABILE"}
    Received
           1
              Object {
                "payload": Object {
            -     "data": Object {},
            +     "caratteristiche": Array [],
                },
            -   "type": "AGGIUNGI_CARATTERISTICA_SELEZIONABILE",
            +   "type": "SETUP_CARATTERISTICHE",
              },
           2
              Object {
                "payload": Object {
            -     "data": Object {},
            +     "data": Array [],
                },
            -   "type": "AGGIUNGI_CARATTERISTICA_SELEZIONABILE",
            +   "type": "SETUP_IMMAGINI",
              },
           3
              Object {
                "payload": Object {
            -     "data": Object {},
            +     "data": Array [],
                },
            -   "type": "AGGIUNGI_CARATTERISTICA_SELEZIONABILE",
            +   "type": "RIMUOVI_CARATTERISTICA_SELEZIONATA",
              },

    Number of calls: 4
```

Here I'm trying to debug the fourth call, which I can't see.

A screenshot with colours might be more useful

![image](https://user-images.githubusercontent.com/11167635/67267489-b0dadc00-f4b2-11e9-8536-f967f4f752a7.png)

Excuse me if it's a stupid issue, feel free to close

**Comment by ndresx** [comment]
Hi, check out Jest's `mock` property (https://jestjs.io/docs/en/mock-functions.html#mock-property)!

It includes an array of all `calls` that were made until the point of checking.

**Comment by ljharb** [comment]
This seems like a question very specific to a custom matcher, or to your test runner (jest, mocha), or to your mocking approach (jest, sinon) - but not related to enzyme at all.

**Comment by Fieel** [comment]
@ljharb @ndresx  thank you for replying even tho it was unrelated, sorry about that!
