### ISSUE TITLE
[Help] Mount doesn't render my updated state + getting act warning

### ISSUE THREAD

**Issue by Flavien-Pensato** [airbnb/enzyme#2273]
### Current behavior

After using Promise inside `useEffect` on my component. I'm having `act` warning and a unupdated component.

### Expected behavior

I expect my component to render my items without warning.

### Your environment

Component.js
```js
const Wrapper = () => {
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.resolve().then(() => setLoading(false))
  }, [])

  if (loading) {
    return <Loader />
  }

  return <Tada />
}
```

Test.js
```js
const instance = mount(<Wrapper />)

expect(instance.find(Tada).length).toBe(1)
```

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.11.0
| react-dom           | 16.11.0
| enzyme | 3.9.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

I create this issue because the way of doing test seems full of darkness with hooks.

I thought `act` was completly integrate to mount. It seems that I'm wrong.
Maybe it actually has nothing to do with enzyme.

More than a issue, I want to understand why this simple case doesn't work. And why it seems to be working with other.

Thanks !

**Comment by ljharb** [comment]
Did you figure this out?

**Comment by Flavien-Pensato** [comment]
I figure out :) I forget the link where it was well explain :/

Just in case someone is looking for the solution.

test.js
```js
let instance

await act(async () => {
  instance = mount(<Wrapper />)
})

instance.update()

expect(instance.find(Tada).length).toBe(1)
```
Everything works like a charm now 🎉

**Comment by Flavien-Pensato** [comment]
`Use the asynchronous version of act to apply resolved promises` React docs

**Comment by azuruce** [comment]
had the same problem but wrapper should update automatically.

**Comment by Flavien-Pensato** [comment]
@azuruce I don't think so. Elsewhere how can we test before the mount of our component ?

**Comment by morgluc** [comment]
Anyone know why the `instance.update()` is needed?

**Comment by ljharb** [comment]
Because enzyme wrappers don’t auto-update when things change, so that you have control over what you’re testing.
