### ISSUE TITLE
`invoke()` is not wrapped with `act()` and requires manual `update()` calls

### ISSUE THREAD

**Issue by davidli16** [airbnb/enzyme#2279]
### Current behavior

Calling methods with `invoke` requires surrounding the method with `act()` AND calling `wrapper.update()` afterwards. If `invoke` is called directly, the following warning is thrown:

```
console.error node_modules/react-dom/cjs/react-dom.development.js:506
    Warning: An update to TestA inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in TestA (created by WrapperComponent)
        in WrapperComponent
```

### Expected behavior

According to the docs, `invoke` should wrap all method calls in `act()` and `wrapper.update()` by default.

https://github.com/airbnb/enzyme#react-hooks-support

### Your environment

Test case is the same as a previously reported issue.
https://github.com/airbnb/enzyme/issues/2231

New versions of the Enzyme adapters have been released recently that include the logic for wrapping invoke. However, the main library still needs to be updated with the following commit to actually include the `wrapInvoke` calls from the adapter: https://github.com/airbnb/enzyme/commit/d2bb6554c57af7eda789f63059c76ae029e9f64e#diff-f51a48d4631e74e85755869409584c3f

Enzyme 3.10 was cut right before this commit was introduced in master.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               | 16.10.1
| react-dom           | 16.10.1
| react-test-renderer | 16.10.1
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16 | 1.15.1
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
That's already fixed in #2158, but unreleased.

The docs on github reflect master; the docs on https://airbnb.io/enzyme/ reflect the latest published version of enzyme.

**Comment by davidli16** [comment]
Do you have any estimates of when a new version of Enzyme will be released?

**Comment by ljharb** [comment]
I don’t.

**Comment by davidli16** [comment]
That's good to know. Thank you!

We'll just keep working around it for now. :D
