### ISSUE TITLE
useRef objects cannot be changed

### ISSUE THREAD

**Issue by zkaramanlis** [airbnb/enzyme#2285]
Changing useRef objects is causing "TypeError: Cannot add property contextId, object is not extensible". I simulate a right click, and when the ref object is changed inside the context menu this error occurs.

using enzyme ^3.10.0, enzyme-adapter-react-16, and React ^16.11.0

the test:
```
test("link column snapshot test", async () => {
    let tree = toJson(component);
    expect(tree).toMatchSnapshot();

    await act(async () => {
        let links = component.find(".LinkColumnDiv");
        links.at(0).simulate("contextmenu", {clientX:20, preventDefault: jest.fn()});
    
        tree = toJson(component);
        expect(tree).toMatchSnapshot();
    });
});
```

code under test:
```
const ref = useRef({rightClickRef:React.createRef()});
...
ref.contextId = props.links[id].id;  //where it fails inside the onContextMenu function
```

**Comment by ljharb** [comment]
`useRef` returns a ref object whose `current` property is what you can modify; you can't add arbitrary properties to it according to https://reactjs.org/docs/hooks-reference.html#useref.

This is a React constraint, and is unrelated to enzyme.
