### ISSUE TITLE
shallow render "renders" wrong tag

### ISSUE THREAD

**Issue by Caraballo-truelogic** [airbnb/enzyme#2286]
### Current behavior
I have this component which renders a `Dropdown` component with the following structure:

```
<div>
 <Dropdown>
        <DropdownItem />
 </Dropdown>
</div>
```

so when shallow rendering I would expect `wrapper.find('Dropdown')` to be truthy. However the tag is wrong and it fails. When it's shallow rendered and I use `wrapper.debug()` It's actually:

```
<div>
 <t>
        <DropdownItem />
 </t>
</div>
```

Where the heck did this `t` come from?

### Expected behavior
No weird `t` html tag when shallow rendering.
### Your environment
Ubuntu 19.10 
#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10
| react               | 16.0
| react-dom           | 16.0
| react-test-renderer | N/A
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by Caraballo-truelogic** [comment]
Turns out it's minified code from a package we import

**Comment by ljharb** [comment]
@Caraballo-truelogic I'd suggest filing a bug on that package; only the top-level app should be minifying, and if they're going to, they should disable function name mangling for debug reasons.
