### ISSUE TITLE
Testing Functions Inside Function Components

### ISSUE THREAD

**Issue by andrewnottaviano** [airbnb/enzyme#2287]
**Is your feature request related to a problem? Please describe.**
React Hooks are pretty great. We are able to use function components for everything now which has been sweet 🤟🏻 But back in the class days, if we wanted to test a function internal to a class component, we could simply pass our component to shallow or mount and dig into it using instance. For all the research I've done, it doesn't seem possible to test functions inside of function components.

We are using jest as our unit testing framework with enzyme to handle DOM manipulation. I brought this up in an [issue](https://github.com/facebook/jest/issues/9152) to the jest team and they referred me here.

**Describe the solution you'd like**
I figure the best way to explain this is through an example. Fist I have an example of a class component with accompanying test
```
// Component definition
class MyComponent extends React.Component {
...
  foo(bar) {
    // Some processing on bar that depends on state and imported libraries that don't make sense importing into a helper file
    return fooBar;
  }
...
}

// Test
it('should return fooBar', () => {
  const sut = shallow(<MyComponent />);
  expect(sut.instance().foo(testValue)).toBe(fooBar);
});
```
Here is an example of something I might expect if this were implemented (which is really similar to the above, but just for clarity sake I re-wrote it):
```
// Component definition
const MyComponent = (props) => {
...
  const foo = (bar) => {
     // Some processing on bar that depends on state and imported libraries that don't make sense importing into a helper file
    return fooBar;
  }
...
}

// Test
it('should return fooBar', () => {
  const sut = shallow(<MyComponent />);
  expect(sut.instance().foo(testValue)).toBe(fooBar);
});
```

**Describe alternatives you've considered**
I couldn't really find any alternatives to this besides going back to class components 😞🤔

**Comment by ljharb** [comment]
You can't test functions that are declared inside another function - that's how the JS language itself works.

In your case, you can only test MyComponent, based on inputs (props) and outputs (what it renders). Function components have no instances, and there's no state (hooks or not, they're still forever stateless) to introspect.

**Comment by andrewnottaviano** [comment]
Thanks for getting back with me @ljharb. I understand your point, those are closures and by definition closures can't be accessed. But I don't feel like it is right that we effectively aren't able to unit test this scenario. I think I might log an issue to the React team to see if there is some sort of way to expose these functions in a test environment.

**Comment by dschinkel** [comment]
https://github.com/facebook/react/issues/17395#issuecomment-654009167
