### ISSUE TITLE
image.width always returns 0

### ISSUE THREAD

**Issue by Aror** [airbnb/enzyme#2291]
Consider the below fuctions: 

```
const toBase64 = async(file : File) => new Promise((resolve, reject) => {
  const reader = new FileReader()
  reader.readAsDataURL(file)
  reader.onload = () => resolve(reader.result)
})

const getImageWidth  = async(file: File) => {
  const src = await toBase64(file) as string
  const img = new Image()
  img.src = src
  await img.onload
  return img.width
}
```

No matter what image File is passed to getImageWidth, `return img.width` will always return 0 in tests with enzyme. This works in production code but fails in tests. 

Example: https://jsfiddle.net/hz3t74rf/

**Comment by ljharb** [comment]
This is a jsdom bug; see https://github.com/airbnb/enzyme/issues/2179#issuecomment-528973289
