### ISSUE TITLE
expect(1).toBeGreaterThan(0); PhantomJS 2.1.1 (Windows 8.0.0)     undefined is not a constructor (evaluating 'Array.from(arr)')

### ISSUE THREAD

**Issue by Link631** [airbnb/enzyme#2293]
### Current behavior
expect(0).toBeGreaterThan(-1); throws an error: Undefined is not a constructor
### Expected behavior
expect(0).toBeGreaterThan(-1); should pass.
### Your environment
TypeScript 2.4.2
React 15.4
NPM: 5.6.0
#### API

- [ ] shallow
- [ x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 15.4.2
| react-dom           | 15.4.2
| react-test-renderer | x
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [x ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
`Undefined is not a constructor` doesn't seem like it'd be coming from enzyme; you'll have to be more specific.

What happens if you run your tests in node?

**Comment by Link631** [comment]
You are right. I solved this Issue.
I also had types enzyme with es6 Issues in Phantom in mind, but it was simply a configuration issue.

Thanks.

Sorry for reporting this as a bug. I would have prefered to simply put it as a question.
