### ISSUE TITLE
react-is@16.12.0 changed the behavior of isMemo function, which cause enzyme selector fail.

### ISSUE THREAD

**Issue by changran52m** [airbnb/enzyme#2297]
### Current behavior
https://codesandbox.io/s/gracious-sun-qih2n broken
https://codesandbox.io/s/agitated-firefly-ows1l working

### Expected behavior
console.log("Icon is icon?:", mount(<EditIcon />).is(EditIcon)); // true

### Your environment
React + Enzyme

### Root cause
Please check in detail here https://github.com/facebook/react/pull/17278

#### Proposal:
1. fix the is function call to isMemo to take component.type instead of component itself.
2. pin the dependency of react-is to `16.11.0`

### API
- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.12.0
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | 15.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( ) 

Related issue https://github.com/facebook/react/issues/17457
Related issue https://github.com/facebook/react/pull/17278

**Comment by ljharb** [comment]
Yes, this is blocking #2292.

If you think you have a fix that's *not* pinning to 16.11, please link me to a branch and I'll pull in the commit :-)

**Comment by lamhieu-vk** [comment]
> If you think you have a fix that's _not_ pinning to 16.11, please link me to a branch and I'll pull in the commit :-)

I created #2298 , please review it :) .

**Comment by ljharb** [comment]
Thanks; i was hoping for a branch instead of a second PR, but I’ll take a look.

**Comment by lamhieu-vk** [comment]
I closed PR #2298  and created #2300 . Please check it again.

**Comment by ljharb** [comment]
Similarly, now there’s a 3rd PR where i wanted only 1 :-) I’ll take a look but please do not open any additional PRs for this; reuse one of the existing ones.

**Comment by lamhieu-vk** [comment]
Thanks about your reply, I just want to make clean my PR. ^^

**Comment by ljharb** [comment]
Understood - but that's what force push is for :-) now the repo is less clean ;-)

**Comment by lamhieu-vk** [comment]
Ok, I got it.  But can you help me consider the latest PR?  It has strange things, I have a comment looking forward to hearing from you.

**Comment by ljharb** [comment]
Fixed in #2300.
