### ISSUE TITLE
Snapshot contains <[object Object]>

### ISSUE THREAD

**Issue by simkessy** [airbnb/enzyme#2304]
When I test my snapshot now like this: 

```
  it('matches snapshot', () => {
    expect(tf.render()).toMatchSnapshot();
  });
```

It gives me this: 

    -       </UsageWidget>
    +       </[object Object]>

I'm not sure what has changed that caused it to render [object, object] instead of the component name.

**Comment by ljharb** [comment]
enzyme does not contain any snapshot support nor encourage snapshot testing; all we offer is `.debug()` on shallow and mount wrappers. `.render()` produces a cheerio object, which is outside of enzyme's control.
