### ISSUE TITLE
Event handlers fire when evt.stopPropagation() has been called

### ISSUE THREAD

**Issue by TrevorBurnham** [airbnb/enzyme#2306]
### Current behavior

When you `mount()` an element and `simulate` a DOM event, the React event handler fires even if `stopPropagation()` has been called on the event. Example:

```js
const Button = ({ onClick }) => (
  <button
    onClick={onClick}
    ref={ref => ref.addEventListener('click', evt => evt.stopPropagation())}
  >
    Click me
  </button>
);
const buttonWrapper = mount(<Button onClick={onClickSpy} />);
buttonWrapper.simulate('click');
expect(onClickSpy).not.toHaveBeenCalled(); // fails
```

### Expected behavior

The React event handler shouldn't be called, because this doesn't reflect real-world behavior. React can't detect DOM events that don't propagate to the `document`.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.10.1
| react-dom           | 16.10.1
| react-test-renderer | 16.10.1
| enzyme-adapter-react-16     | 1.15.1

**Comment by ljharb** [comment]
simulate is not actually simulating anything (it's a terrible API). All it's doing is invoking the `onClick` prop function in this case.

**Comment by TrevorBurnham** [comment]
I guess that's true—the element-level `click` handler doesn't fire at all, so the `evt.stopPropagation()` line doesn't run.
