### ISSUE TITLE
TypeError: Cannot read property 'Events' of undefined

### ISSUE THREAD

**Issue by yanxiaosong0902** [airbnb/enzyme#2308]
### setup.js
```javascript
var Enzyme = require('enzyme')
var Adapter = require('enzyme-adapter-react-16')
Enzyme.configure({ adapter: new Adapter() })
```
When I run jest, it got this error:
```
TypeError: Cannot read property 'Events' of undefined
```
### Version
```json
"react": "~16.8.6",
"react-dom": "~16.8.6",
"enzyme": "^3.10.0"
"jest": "^24.5.0",
"enzyme-adapter-react-16": "^1.15.1"
"react-addons-test-utils": "^15.6.2",
```

**Comment by ljharb** [comment]
Why are you using react-addons-test-utils? That shouldn't even be installed if you're using react 16.

Can you provide more info about the error? Is there a stack trace? Are you getting it running tests, or even with no tests at all?

**Comment by SarpongAbasimi** [comment]
The question is where is `Events` being used?

**Comment by ljharb** [comment]
Hopefully the stack trace would reveal that.

Closing for now, happy to reopen if it can be reproduced or if more info is provided.
