### ISSUE TITLE
Blog post about testing

### ISSUE THREAD

**Issue by sweatC** [airbnb/enzyme#2312]
I am writing a blog post about the modern way of testing React Native apps and want to include one paragraph about `enzyme` as a unit testing tool.

I need one well-described paragraph about your tool and one simple example of using.
Instead, I want you to promote my article on your site or blog.

**Comment by ljharb** [comment]
I don't have a site or a blog; does the readme and the docs not contain what you're asking for?

**Comment by sweatC** [comment]
OK. I will try to make something with the docs that you have.
Thank you for your fast feedback.
