### ISSUE TITLE
Warning: An update to SearchPage inside a test was not wrapped in act(...)

### ISSUE THREAD

**Issue by SarpongAbasimi** [airbnb/enzyme#2313]
Quick question Guys.

Please I have a test passing, but get the follow warning in the console. Is it something I should worry about. ?

<img width="896" alt="Screenshot 2020-01-03 at 12 46 51" src="https://user-images.githubusercontent.com/37377831/71724172-38d05100-2e27-11ea-82bb-6d007a77cba7.png">

**Comment by SarpongAbasimi** [comment]
@ljharb Any input into this ?
Thanks.

**Comment by ljharb** [comment]
What's your test file look like?

**Comment by SarpongAbasimi** [comment]
This is how the test looks like @ljharb 

![71717086-cfdcdf00-2e0e-11ea-8432-a4f770476e4c](https://user-images.githubusercontent.com/37377831/71745039-f592d400-2e60-11ea-855c-f73de62ef8fb.png)

**Comment by SarpongAbasimi** [comment]
I tried wrapping `form.simulate('submit)` in act, but that didn't work.

**Comment by ljharb** [comment]
I'd suggest avoiding `simulate`; it doesn't actually simulate anything. All it does is invoke the form's `onSubmit` prop, which you can and should do manually.

What needs to be wrapped in `act` is anything that rerenders the component; that probably also includes the `searchRequirements()` call?

**Comment by SarpongAbasimi** [comment]
Thanks @ljharb , it has been resolved now.
I will close this issue now.
