### ISSUE TITLE
AttachTo Required For JSDOM 15.2.0/1

### ISSUE THREAD

**Issue by shannontan-bolt** [airbnb/enzyme#2314]
### Current behavior

With JSDOM 15.1.1, `document.activeElement` could be correctly queried after focus was called on refs. After upgrades to JSDOM 15.2.0/1, `document.activeElement` was no longer being set. 

I found out that the solution to this problem is to specify `attachTo` as an option of `mount()`, but I'm curious if this was expected behavior/the correct change. I'm leaving this here instead of StackOverflow because this functionality change is odd - I would like to say that an assumption of Enzyme about JSDOM is no longer valid and therefore a change should be made.

Please let me know if I misunderstood Enzyme, and therefore, this is expected behavior and our tests that assert `document.activeElement` were wrong originally.

### Expected behavior
`document.activeElement` is valid for JSDOM 15.2.0 and JSDOM 15.1.1 without using attachTo Enzyme mount option.

### Your environment
"react": "^16.11.0",
"react-dom": "^16.11.0",
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.2",
"jsdom": "^15.2.1",

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
It sounds like you're describing a breaking change in a minor version of jsdom. A repro case would be helpful, but you may want to file an issue on jsdom instead?

**Comment by shannontan-bolt** [comment]
I think you're right - I found issues with our test cleanup that was leading to this issue. Wwe may have just been lucky with JSDOM/Enzyme thus far and it was this new combination that exposed our mistakes.
