### ISSUE TITLE
Update from 3.2 to 3.11 breaks .find() when searching for component with prop

### ISSUE THREAD

**Issue by simkessy** [airbnb/enzyme#2318]
### Current behavior
I updated from Enzyme 3.2 to 3.11 and it broke several of my tests. Wondering what's wrong with the initial selected I was using. 

I have a test which did this: 

```
        const btn = wrapper.find('[accessibilityLabel="edit note"] IconButton');
        expect(btn).not.toHaveLength(0);

    --- fail 
   expected not 0 
   received {}
```
After the update this started to failed until I changed it to: 

```
        const btn = wrapper.find('[accessibilityLabel="edit note"]');
        expect(btn).not.toHaveLength(0);

      ---pass 
```

Component: 

```
              <IconButton
                size="xs"
                accessibilityLabel="edit note"
                icon="edit"
                onClick={this.onEditButtonClick}
              />
```

#### API

- [x ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               |  16.8
| react-dom           | 16.8
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
3.2 to 3.11 is a massive jump; the first thing that would help is narrowing down exactly which version made it stop working.

How is `IconButton` defined? Finding by custom component name is brittle, depending on how the component is defined; it'd be better to do `const btn = wrapper.find('[accessibilityLabel="edit note"]').find(IconButton);` which should ideally pass in every version.

**Comment by simkessy** [comment]
I was able to fix it using this pattern instead: 

```
wrapper.find('[accessibilityLabel="edit note"]').find("IconButton"); 
```

Not entirely sure if the way the selectors worked between the versions might have changed but I'm okay with changing the tests to match this new pattern. Thank you for the response though :)

**Comment by ljharb** [comment]
It'd still be helpful, if possible, for you to do some bouncing around to try to figure out in which enzyme version it broke :-)
