### ISSUE TITLE
Query Selector fails: Attributes selectors

### ISSUE THREAD

**Issue by strawhatgami** [airbnb/enzyme#2320]
Attributes selectors work according to value passed to component

### Current behavior / Expected behavior
```javascript
import { configure, shallow } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });

import React from 'react';

// Note: the bug works also with class-based components
describe("Selector doesn't match attribute value in find()", () => {
  function MyComponent(props){
    return <div data-value={props.value}></div>
  }

  test("minimal working example", () => {
    const wrapper = shallow(<MyComponent value={1} />);
    expect(wrapper.find('div[data-value]')).toHaveLength(1); // looks right
    expect(wrapper.find('div[data-value="1"]')).toHaveLength(0); // Enzyme bug: length should be 1
    // expect(wrapper.html()).toEqual("<div data-value=\"1\"></div>");
  });

  test("However this works (value is a string)", () => {
    const wrapper = shallow(<MyComponent value={"1"} />);
    expect(wrapper.find('div[data-value="1"]')).toHaveLength(1); // good length
    // expect(wrapper.html()).toEqual("<div data-value=\"1\"></div>");
  });

  test("My current solution to bypass the bug", () => {
    const wrapper = shallow(<MyComponent value={1} />);
    const matches = wrapper
                    .find('div[data-value]')
                    .filterWhere((component) => component.prop('data-value') == 1);
    expect(matches).toHaveLength(1); // good length
  });
});
```

### Your environment
Jest 24.9.0

#### API
- [x] shallow

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.12.0
| react-dom           | 16.12.0
| react-test-renderer | 16.12.0
| adapter (below)     | 1.15.2

#### Adapter
- [x] enzyme-adapter-react-16

### Note
Maybe duplicate of #2294 ?

**Comment by ljharb** [comment]
In this case, it's because you set a number prop, and you're looking for a string prop. This is a by-design limitation of string selectors; I'd suggest using `.findWhere` with a function predicate so your selection logic can be explicitly controlled.

**Comment by strawhatgami** [comment]
OK, nevertheless it's strange that in the same time `(wrapper.html()` returns `"<div data-value=\"1\"></div>"`

Maybe it's a good idea to document it somewhere future guys in my case will find easily this answer;
in the doc, maybe [here, at the top](https://airbnb.io/enzyme/docs/api/shallow.html)? Or in a page dedicated to selectors manipulation?

**Comment by ljharb** [comment]
Like here? https://airbnb.io/enzyme/docs/api/selector.html

**Comment by strawhatgami** [comment]
Yes, sorry ><
