### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 15 when mounting React.memo component

### ISSUE THREAD

**Issue by macrozone** [airbnb/enzyme#2322]
I reopened https://github.com/airbnb/enzyme/issues/1887 because the issue still happens with latest enzyme 3.11.0, but the issue was closed

### Current behavior

Using React.memo to wrap around a functional component causes the error: Enzyme Internal Error: unknown node with tag 15

### Expected behavior

Enzyme should support React.memo components

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               | 16.10.0
| react-dom           |  16.10.0
| react-test-renderer |  - 
| adapter (below)     |  - 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by lamhieu-vk** [comment]
Can you provide a mini-repo to reproduce?

**Comment by ljharb** [comment]
Also, what version of react-test-renderer? That needs to be 16.10 as well.

**Comment by macrozone** [comment]
i currently can't reproduce it as the this test case no longer exists. i was pretty sure i checked that react-test-renderer was on the same version.

i close this, as i currently can't give more information
