### ISSUE TITLE
TypeError: moment is not a function when importing as  import * as moment from 'moment';

### ISSUE THREAD

**Issue by VishalGulati** [airbnb/enzyme#2323]
### Current behavior
I am using moment in my app as follows:

`import * as moment from 'moment';`

While shallow rendering a component that uses this moment, I am getting error:
`TypeError: moment is not a function`

Here is the line its breaking at:

`moment(inputDate, currentFormal).format(expectedFormat)`

### Expected behavior
I expected the test cases to run smoothly as the import works well in the app and should not have caused problem in testing. Since I can’t change the app code to import moment as default, is there a way to get around this? Can mocking moment help? 

### Your environment
Node v12.14.1

#### API

- [ x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               | 16.9.0
| react-dom           | 16.9.0
| react-test-renderer | 
| adapter (below)     | 1.15.2

#### Adapter

- [ x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Don't use `import * as`. Assuming you're using TypeScript, enable synthetic imports and `esModuleInterop`, and then `import moment from 'moment'`.

**Comment by ljharb** [comment]
Also, the way `import` works has zero to do with enzyme, so there's nothing actionable here.

**Comment by VishalGulati** [comment]
@ljharb Unfortunately I dont have rights to change source code. Is there no way to fix this apart from importing moment as default?

**Comment by ljharb** [comment]
I'm not sure what you mean by "rights"; how are you writing tests for code you can't author?

If `import * as moment` is working in production code, then it should be working in test code (even though it violates the JS spec). I'm not sure how to help you - you may want to ask whoever can alter the code.

**Comment by VishalGulati** [comment]
@ljharb I meant to say its not an option.

**Comment by ljharb** [comment]
Why isn't it an option? Why are you tasked to test code you can't alter?
