### ISSUE TITLE
How to test default props

### ISSUE THREAD

**Issue by jahnaviv** [airbnb/enzyme#2324]
```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    **const { checked = false, checkbox = false } = this.props;**
    this.state = { checked, checkbox };
  }
```

How to test bold line

**Comment by ljharb** [comment]
You don't need to test it; all your tests need to do is test passing `checked` as both true and false, and absent (same with `checkbox`).

Separately, setting state from props will break unless you do it in the constructor AND in componentWillReceiveProps - or, only in getDerivedStateFromProps.

**Comment by jahnaviv** [comment]
**RadioButton.js**
`import React from 'react';
import PropTypes from 'prop-types';
import RadioButton from './RadioButton.styled';

const propTypes = {
  checkbox: PropTypes.bool,
  checked: PropTypes.bool,
  onCheck: PropTypes.func,
};

const defaultProps = {
  checkbox: false,
  checked: false,
  onCheck: () => {},
};

class RadioButtonComponent extends React.Component {
  constructor(props) {
    super(props);
    const { checked = false, checkbox = false } = this.props;
    this.state = { checked, checkbox };
  }

  componentWillReceiveProps({ checked }) {
    this.setState({ checked });
  }

  onClick = () => {
    this.setState({ checked: true });
    const { onCheck } = this.props;
    onCheck && onCheck();
  };

  render() {
    const { checked, checkbox } = this.state;
    return (
      <RadioButton.Container>
        <RadioButton.Radio checked={checked} onClick={this.onClick} checkbox={checkbox} />
      </RadioButton.Container>
    );
  }
}

RadioButtonComponent.propTypes = propTypes;
RadioButtonComponent.defaultProps = defaultProps;

export default RadioButtonComponent;
`
**RadioButton.test.js** file 
```
import React from 'react';
import { shallow } from 'enzyme';
import jest from 'jest-mock';
import RadioButton from './RadioButton';
import RadioButtonStyle from './RadioButton.styled';
const mock = jest.fn();
var wrapper;
// beforeEach(() => {
//   wrapper = shallow(<RadioButton />);
// });

describe('RadioButton component', () => {
  test('renders', () => {
    wrapper = shallow(<RadioButton />);
    expect(wrapper.exists()).toBe(true);
  });

  test('props pass as false', () => {
    wrapper = shallow(<RadioButton checked={false} checkbox={false} />);
    expect(wrapper.instance().state.checked).toBe(false);
    expect(wrapper.instance().state.checkbox).toBe(false);
  });

  test('props pass as true', () => {
    wrapper = shallow(<RadioButton checked={true} checkbox={true} />);
    expect(wrapper.instance().state.checked).toBe(true);
    expect(wrapper.instance().state.checkbox).toBe(true);
  });

  test('Should default radio button `state: checked` value', () => {
    wrapper = shallow(<RadioButton />);
    expect(wrapper.state().checked).toBe(false);
  });

  test('Should click on radio button', () => {
    wrapper = shallow(<RadioButton />);
    expect(wrapper.find(RadioButtonStyle.Radio).exists()).toBe(true); //Radio button should exist
    wrapper.find(RadioButtonStyle.Radio).simulate('click'); // Simulate the click event
    expect(wrapper.state().checked).toBe(true); //Update `checked` state
  });

  test('Should componentWillReceiveProps() run', () => {
    wrapper = shallow(<RadioButton />);
    wrapper.instance().componentWillReceiveProps({ checked: true });
    expect(wrapper.state().checked).toBe(true);
  });

});

```
But still my coverage report show me
stmts: 100%
branch: 50%
Func: 100%
Lines:100%
Uncovered line :22(const { checked = false, checkbox = false } = this.props;)

**Comment by ljharb** [comment]
That's because those defaults are useless. React applies `.defaultProps`, so that `this.props.checked` and `this.props.checkbox` will NEVER be `undefined`.

Just change the line to `const { checked, checkbox } = this.props`.

**Comment by jahnaviv** [comment]
Thank You so much.:)
