### ISSUE TITLE
Contains type doesn't receive 'number'

### ISSUE THREAD

**Issue by pedroSoaresll** [airbnb/enzyme#2338]
**Is your feature request related to a problem? Please describe.**
I wrote a test that contained a number value in html. The test passed, but typescript is fighting with me because it doesn't like number, just string and element.

**Describe the solution you'd like**
A simple update in type definition to add number :smile: 

**Describe alternatives you've considered**
Hmm, some alternative for now is disable TS for this line. Is just one, and harmless.

**Additional context**
I believe that is it. Thanks for read.

Before finish, below you can see the test realized:
![image](https://user-images.githubusercontent.com/11558773/74545285-5ebd3b00-4f27-11ea-8f24-aed6d9ca4f52.png)

**Comment by ljharb** [comment]
enzyme's type definitions are not maintained in this repo; please file an issue in DefinitelyTyped.
