### ISSUE TITLE
shallow() does not seem to be updating the code of the component with mocha and --watch

### ISSUE THREAD

**Issue by tomasfejfar** [airbnb/enzyme#238]
I couldn't think about a way to describe this without the visual, so I created a gif screencap (description below) :) 
![mocha](https://cloud.githubusercontent.com/assets/642928/13558235/9058502c-e3f7-11e5-9f2a-07e3045359ce.gif)

I first added "test" to the text in button. But the test didn't fail. Then I changed the props in test. That failed the test. So it's obvious that it's called. But when I return back to previous value (and the test is rerun again) it still does not fail. After then when I close and open the test command it fails. 

So it seems as if it was caching the react component somehow. Or not clear it between the calls. The commands:

```
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js test/**/*.*",
    "test:watch": "npm run test -- --watch"
```

And test_helper:
```
import chai from 'chai';
import chaiImmutable from 'chai-immutable';
import chaiEnzyme from 'chai-enzyme'

chai.use(chaiImmutable)
    .use(chaiEnzyme);
```

I am not sure if this might be mocha issue or something else, but it didn't happen for any tests before I used *enzyme*. I'll be happy to supply more details if needed, but I don't know where to start and how to debug it further.

**Comment by tomasfejfar** [comment]
Repo with the full code: https://github.com/tomasfejfar/redux-voting/tree/bab5f4b63148cc7faaf21dbe5ff5b5508c2cf52c

**Comment by ljharb** [comment]
Is this only reproducible when using `--watch`?

**Comment by tomasfejfar** [comment]
Yes. I have slept on it and I've found the problem. It's beacuse I've never used `*.jsx` files before. I needed to update my test command to 
`"test": "mocha --compilers js:babel-core/register --compilers jsx:babel-core/register --watch-ext=jsx --require ./test/test_helper.js test/**/*.*",` and now it works. So it's completly unrelated to enzyme, sorry :(
