### ISSUE TITLE
React Native - Unexpected token export

### ISSUE THREAD

**Issue by avishayil** [airbnb/enzyme#248]
````
(function (exports, require, module, __filename, __dirname) { export { COLOR, TYPO, PRIMARY_COLORS, THEME_NAME } from './config';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:404:10)
````

**Comment by lelandrichardson** [comment]
@avishayil i'm not sure this has anything to do with enzyme. It looks like you're trying to require a file that has ES6 syntax, and you aren't using something that knows how to handle that (eg, babel-register).

**Comment by Aweary** [comment]
@avishayil as @lelandrichardson mentioned this seems to be a setup issue with your build process. If you have more information about your issue that points towards an issue with enzyme, let us know 👍
