### ISSUE TITLE
mocha test case for a jsx file with a new create class

### ISSUE THREAD

**Issue by js08** [airbnb/enzyme#254]
Hi,

- I am trying to write a mocha test case for the below file...
- I am beginner in writing unit test cases.
- I have started it but I am not sure whether I have written correctly or not.
- in the components folder I have a jsx file for that file only I am writing my test case..
- I am trying to print values using console.logs in my code but I am not able to find out...
- i am using npm enzyme package..
- using a sample code as example and I have written test case for my code.
- not sure whether this line is correct const wrapper = shallow(<MyComponent />);
- and I am not sure how to test the inside element return (<p key={element.id} dangerouslySetInnerHTML={{__html: element.text}}></p>);
- it would be great help if you update my code

https://www.npmjs.com/package/enzyme

test-cases
import React from 'react';
import { shallow } from 'enzyme';
import sinon from 'sinon';
 
describe('<MyComponent />', () => {
 
  it('renders one <SportsList /> components', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find(SportsList)).to.have.length(1);
  });
 
  it('renders an `.pageFooter-sports`', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find('.pageFooter-sports')).to.have.length(1);
  });
 
  it('renders children when passed in', () => {
    const wrapper = shallow(
      <MyComponent>
        <div className="pageFooter-sports">
      </MyComponent>
    );
    expect(wrapper.contains(<div className="pageFooter-sports">" />)).to.equal(true);
  });
 
});

   actual code
    
    import React from 'react';
    let SportsList = React.createClass({
        propTypes: {
            sports: React.PropTypes.array
        },
    
        render() {
            return (
                <div className="pageFooter-sports">
                    {this.props.sports.map((element) => {
                        return (<p key={element.id} dangerouslySetInnerHTML={{__html: element.text}}></p>);
                    })}
                </div>
            );
        }
    });
    console.log("SportsList" + SportsList);
    export default SportsList;

**Comment by ljharb** [comment]
Please stop spamming - you've asked this same question in a number of slack and gitter channels.

We're happy to help if you have a specific enzyme question!

**Comment by js08** [comment]
@ljharb ok sorry about it...what component name should I need to put in place of MyComponent  in my code
const wrapper = shallow(<MyComponent />);

https://www.npmjs.com/package/enzyme

can you tell me that alone since I didn't find any explanation in the documentation for MyComponent

**Comment by ljharb** [comment]
You'd want `<MyComponent />` - ie, jsx to create an element

**Comment by js08** [comment]
@ljharb thanks for your reply...so I should replace MyComponent  by SportsList

**Comment by js08** [comment]
@ljharb hey atleast for this alone can you reply
