### ISSUE TITLE
Lets change the API for spyLifecycle and spyMethods

### ISSUE THREAD

**Issue by goatslacker** [airbnb/enzyme#26]
The goal of this is to

* Make whats happening a bit more explicit. Currently there's a bit of magic.
* Let you use your own sinon rather than rely on reagent using its own.

```js
let spy; 

describe('MyComponent', () => {
  beforeEach() {
    spy = reagent.spyLifecycle(sinon, MyComponent);
  },

  it('should do things', () => {
    const my = mount(<MyComponent />);
    my.setProps({ hello: 'world' });

    assert.isTrue(spy.get('componentWillReceiveProps').calledOnce, 'receive props was called');

    // or if we don't want to be stringly typed...
    assert.isTrue(my.componentWillReceiveProps.calledOnce);
  });

  afterEach() {
    spy.destroy();
  }
});
```

Pros: It's more explicit what's happening.
Cons: You now have to do the beforeEach/afterEach setup yourself.

Ideally we'd merge spyLifecycle and spyMethods so it just spies every method.

**Comment by lelandrichardson** [comment]
Closing as these APIs no longer exist.
