### ISSUE TITLE
enzyme downloading problem

### ISSUE THREAD

**Issue by texirv0203** [airbnb/enzyme#260]
hi,

- my network doesnt allow me to install  enzyme 
- so can I donwload the zip file and put it in node modules 
- if I run it will it work then

**Comment by ljharb** [comment]
@texirv0203 i'm not sure what you mean by "your network doesn't allow it" - if `npm install enzyme` or `git clone git@github.com:airbnb/enzyme.git` doesn't work, you may need to contact your network administrator.

**Comment by texirv0203** [comment]
@ljharb instead of doing it is there any other alternate method

**Comment by ljharb** [comment]
Just `npm install`, and `git clone`. I'm not sure why anyone would prevent `npm install` from working on their network, though.

**Comment by texirv0203** [comment]
till the end your not giving solution for secured network

**Comment by ljharb** [comment]
@texirv0203 there is no solution for a "secured" network except to recognize that blocking incoming traffic isn't security :-) again, you need to talk to your network administrator. github and npm traffic should be whitelisted.

**Comment by texirv0203** [comment]
But downloading that zip file and importing in node modules won't it work

**Comment by ljharb** [comment]
you are correct. again, your best option is to reconfigure your network so that `npm install` works. If that doesn't work, you're going to have a tough time doing any useful web dev in 2016.
