### ISSUE TITLE
wrapper.find() cannot retrieve stateless components

### ISSUE THREAD

**Issue by mdotasia** [airbnb/enzyme#262]
I'm trying to find rendered stateless components in a wrapper using `name`/`displayName` as selector (when using `mount`). For normal components `find` always returns selected components as expected, but for stateless components it returns nothing, even though they are there.

In [`findAllInRenderedTreeInternal`](https://github.com/airbnb/enzyme/blob/7efeda383c3c914f038ec0005ca493ed591b9d47/src/MountedTraversal.js#L236-L289) at [line 249](https://github.com/airbnb/enzyme/blob/7efeda383c3c914f038ec0005ca493ed591b9d47/src/MountedTraversal.js#L249) there is this a call

```
var publicInst = inst.getPublicInstance();
```

which calls `getPublicInstance` of `ReactCompositeComponent.js`:

```
  getPublicInstance: function () {
    var inst = this._instance;
    if (inst instanceof StatelessComponent) {
      return null;
    }
    return inst;
  },
```

Obviously, `find` will fail for stateless components since `getPublicInstance` always returns `null`. I'm wondering why in line 249 further up it is necessary to call `getPublicInstance` since there should be other ways to retrieve the element for testing.

I'm fairly new to `React` and `enzyme` so I am not sure if I am missing something.

**Comment by AugustinLF** [comment]
I've read that arrow functions for stateless components [don't have a name property](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless). Could this be the cause of your problem?
