### ISSUE TITLE
Possible React compatibility issues

### ISSUE THREAD

**Issue by ajgreenb** [airbnb/enzyme#268]
I just added Enzyme to my project (I use Karma for testing) and I'm trying to build my bundle of dependencies (using webpack), but I'm getting 4 errors. Three of them are webpack errors, and one is a Karma run-time error. I followed the instructions in the installation guide and in [Using Enzyme with Karma][enzyme-karma] (added the `externals` property to my webpack config.)

**Here are the errors:**
```
WARNING in ./~/enzyme/build/react-compat.js
Module not found: Error: Cannot resolve module 'react-dom' in C:\path\to\node_modules\enzyme\build
 @ ./~/enzyme/build/react-compat.js 103:17-37

WARNING in ./~/enzyme/build/react-compat.js
Module not found: Error: Cannot resolve module 'react-addons-test-utils' in C:\path\to\node_modules\enzyme\build
 @ ./~/enzyme/build/react-compat.js 117:18-52

ERROR in ./~/enzyme/build/react-compat.js
Module not found: Error: Cannot resolve module 'react-dom/server' in C:\path\to\node_modules\enzyme\build
 @ ./~/enzyme/build/react-compat.js 109:58-85
Chrome 49.0.2623 (Windows 7 0.0.0) ERROR
  Uncaught ReferenceError: react is not defined
  at C:/path/to/bundle.spec.js:55610 <- webpack:/external "react/lib/ReactContext":1:0
```

**Here are some relevant software versions:**
* Operating System: `Windows 7`
* Browser: `Chrome 49.0.2623`
* React: `^0.13.3`
* Enzyme: `^2.1.0`
* Karma: `^0.13.21`
* karma-webpack: `^1.7.0`
* webpack: `^1.12.13`

I'm not sure why the first 3 errors are appearing&mdash;according to [Working with React 0.13][react-13], I shouldn't have to install `react-dom` or `react-addons-test-utils`. My best guess here is that webpack is doing its static dependency analysis, finds the `require` expressions in `enzyme/build/react-compat.js`, and then tries to import those two unnecessary dependencies. Is there a best-practice workaround for this? I could use a webpack `IgnorePlugin`, but that seems a bit janky.

But I'm not sure why Karma's throwing that last run-time error. Any ideas on that? I looked through `react/lib/ReactContext`, and it doesn't even reference `react`&hellip;This may be a React error and not an Enzyme error, but it didn't show up before I added the three `externals` to my webpack config as specified in the documentation.

Thanks!
Aaron

[enzyme-karma]: https://github.com/airbnb/enzyme/blob/master/docs/guides/karma.md
[react-13]: https://github.com/airbnb/enzyme/blob/master/docs/installation/react-013.md

**Comment by lelandrichardson** [comment]
> My best guess here is that webpack is doing its static dependency analysis, finds the require expressions in enzyme/build/react-compat.js, and then tries to import those two unnecessary dependencies. Is there a best-practice workaround for this? I could use a webpack IgnorePlugin, but that seems a bit janky.

This is essentially what we are recommending in the webpack guide. It's equivalent to marking them as externals...

These issues will go away once we drop 0.13 support. In the meantime, this is an issue because of the fact that commonjs-aware asset bundlers use static analysis.

**Comment by ajgreenb** [comment]
So I *should* be getting those warnings? I did mark them as externals in my Karma webpack configuration property, but I can't get the tests to even run.

Probably the real workaround for this issue is to focus on upgrading to `react@latest` and then using Enzyme, rather than spinning my wheels mucking with webpack and Karma to get it to work with 0.13&hellip;

**Comment by lelandrichardson** [comment]
@ajgreenb feel free to let me know if you need any more help. It *should* work with 0.13 and webpack, albeit with some slightly ugly webpack config required.

**Comment by ajgreenb** [comment]
Thanks!
