### ISSUE TITLE
Trying to findWhere by the node's text

### ISSUE THREAD

**Issue by mordrax** [airbnb/enzyme#270]
So I've got some html that looks like this:
```javascript
//Gender component
      <div className={classNames("ui labeled icon button", {active:gender === 'male'})}
           onClick={() => {onChangeGender('male');}}>
        <i className="large male icon"/>
        Male
      </div>
      <div className="or"></div>
      <div className={classNames("ui labeled icon button", {active:gender === 'female'})}
           onClick={() => {onChangeGender('female')}}>
        <i className="large female icon"/>
        Female
      </div>
```

I want to reference the first div based on the text that is contained in the div (Male).

When I do:
```javascript
let component = shallow(<Gender />)
component.find('div.button').findWhere(x=>x.text() === 'Male') // gives me two nodes, the div and the string 'Male'
component.find('div.button').findWhere(x=>x.type()==='div' && x.text() === 'Male') // gives me just the div
```

I would have thought the first command should just give me the div, but it seems that enzyme also regards the child component, just the string 'Male' as it's own node where the text is just 'Male' and returns it as well.

Is this a bug or expected? 

Alternatively, is there a better way to find a div by text? I don't even know if the first `find('div.button')` does anything.

**Comment by blainekasten** [comment]
> Alternatively, is there a better way to find a div by text? I don't even know if the first find('div.button') does anything.

The `div.button` selector should work to return both div's in your scenario. There are a couple different ways you could get what you need.

1. You could try using the component prop selector. This is untested but I think it should work:

```js
component.find('div[children="Male"]')
```

1. use the `.at(n)` method.

```js
const maleDiv = component.find('div.button').at(0);
const femaleDiv = component.find('div.button').at(1);
```

> Is this a bug or expected?

I think it is not a bug. Since react wraps free-standing text in spans. Technically there are multiple nodes there. Additionally, the docs are very clear that this is intended behavior (https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/text.md)

**Comment by mordrax** [comment]
@blainekasten thanks for clearing that up and giving me some alternatives. Both of them are too tightly coupled to the implementation imo. I ended up creating a `.test-gender-male`uurrrgghh! but it gets the job done and i can restyle on demand without breaking the test.

**Comment by nareshbhatia** [comment]
@blainekasten, nice solution with component prop selector (`component.find('div[children="Male"]')`). Is this documented anywhere? I read the [selectors docs](https://airbnb.io/enzyme/docs/api/selector.html) several times, but it never mentions the ability to select by component props!

**Comment by inside** [comment]
@nareshbhatia I think this quote from the selectors docs explains it:
> While in most cases, any React prop can be used, there are exceptions. The key and ref props will never work; React uses these props internally.

**Comment by nareshbhatia** [comment]
Thanks for digging that up, @inside. It's very subtle and indirect. I think it deserves its own section "A React Component Property", complete with examples and then the exceptions.

**Comment by inside** [comment]
You're welcome, agreed!

**Comment by KitsonBroadhurst** [comment]
I know this thread is old, but still was the first place I came for this issue.

I had a very similar situation, trying to find a specific button by the button text.
Example component, mapped to create multiple tabs:
```
<TabButton
  key       = { index }
  current   = { currentTab.key === tab.key }
  onClick   = { () => setCurrentTab(tab) }
>
  { checkedOptions[tab.key] ? (
    <TabCount>{ checkedOptions[tab.key].length }</TabCount>
  ) : null }
  { tab.label }
</TabButton>
```

When I did:
```
const wrapper = mount(<MainComponent />)

const button = wrapper
  .find('[data-test="searchByAttributeTabs"]')
  .find('button')
  .filterWhere(button => button.text() === AF_SEARCH_TABS.department.label)
```

my assumption was that I would get the button wrapper with matching text...

However, I received only the button text, I assume that filterWhere was returning the span
> Since react wraps free-standing text in spans. 

The solution I found checked that both the wrapper was a button AND that the text matched:
```
wrapper
  .find('[data-test="searchByAttributeTabs"]')
  .findWhere(node => {
     return node.type() === 'button' && node.text() === AF_SEARCH_TABS.designers.label
  })
```
