### ISSUE TITLE
Option to have a prop ignored on contains

### ISSUE THREAD

**Issue by DanielMSchmidt** [airbnb/enzyme#273]
Hi there,

First of all thanks for this great library! I am currently testing a React Native application and I found it hard to do so, as `contains` can't be differed to be more allowing.

My use case is that I have a component render a `<Text`> element which is set via prop, much like in your [example test](https://github.com/lelandrichardson/enzyme-example-react-native/blob/master/test/MyComponent.js). Unfortunately my <Text> element needs a style prop, which I don't intend to share between my tests and application. Would it be possible to add a whitelist to the compare functions as additional argument? I would be glad to help and do a PR if this feature is chosen to be useful for anyone else.

Have a nice day!

**Comment by gm758** [comment]
I also found this a bit counter intuitive my first time using enzyme. I currently use the approach below when I want to test the contents of an element.

```
  it('should render text inside the Text component', () => {
    const text = 'Test Text';
    const wrapper = shallow(
      <Button text={text} />
    );

    expect(wrapper.find(Text).prop('children')).to.equal(text);
  });
```

**Comment by smacker** [comment]
same idea: https://github.com/airbnb/enzyme/issues/204#issuecomment-185607556 :)

**Comment by Aweary** [comment]
The new API introduced in https://github.com/airbnb/enzyme/pull/362 should cover this use case, so I'm going to close this as it seems resolved. Let me know if you have any questions!
