### ISSUE TITLE
Lint errors in test/**

### ISSUE THREAD

**Issue by ncuillery** [airbnb/enzyme#276]
I just spotted an unused var in https://github.com/airbnb/enzyme/blob/348bab741016efcd94249ad5d507dd9c53f30625/test/ShallowWrapper-spec.js#L69 so I ask myself why the linter didn't see it and I found that the lint script don't scan the `test` dir : https://github.com/airbnb/enzyme/blob/348bab741016efcd94249ad5d507dd9c53f30625/package.json#L12

If it does, it reveals ~100 errors.

**Comment by ljharb** [comment]
Whoops! Thanks, will fix.
