### ISSUE TITLE
Equals without childrens content?

### ISSUE THREAD

**Issue by ngerritsen** [airbnb/enzyme#282]
With the React test utils (with chai-jsx to do the assertion) I could do:

```
const renderer = TestUtils.createRenderer()
renderer.render(<Foo/>)
expect(renderer.getRenderOutput()).to.deep.equal(
  <div>
    <Bar/>
  </div>
) // succeeds
```

However with enzyme shallow equals:

```
expect(shallow(<Foo/>).equals(
  <div>
    <Bar/>
  </div>
)) // fails
```

This fails because you need to specify also the contents of Bar. I don't think this should be the behaviour for shallow rendering? You should not care about the contents of Bar.

Is there a way to get the same behaviour in enzyme? Because I like all the other features that enzyme has that the test utils from React do not provide (at least not when shallow rendering).,

**Comment by Markionium** [comment]
Is there a reason why you want to check the whole structure at once and can't just check if a `<Bar />` component was rendered as a part of `<Foo />`?

```js
expect(shallow(<Foo />).find(Bar)).to.have.length(1);
```

or to be more specific
```js
expect(shallow(<Foo />).find('div').find(Bar)).to.have.length(1);
```

**Comment by lelandrichardson** [comment]
> This fails because you need to specify also the contents of Bar.
@ngerritsen I can't be sure from the example, but this should not be the case...

This would fail if you don't specify the *children* of `<Bar>`. ie, you would essentially need to replicate the render method of `Foo` (not that I recommend that).

Can you provide working code for your example? Either there is a legitimate bug going on here, or one of us is misunderstanding.

Thanks  for taking the time to file an issue.

**Comment by ngerritsen** [comment]
It is not a bug, it's a different way of doing the equal.

@Markionium sometimes with small components it's just convenient do do an equal with the whole component sometimes, but just querying the component for specific elements is also fine.

Let's close this for now.
