### ISSUE TITLE
find with href attribute of full URL is rejected for being complex

### ISSUE THREAD

**Issue by vegetabill** [airbnb/enzyme#283]
I may have missed an explanation in #70 but I expected this selector to work:

`.find('a[href='http://example.com/xyz']')`

But instead it complains:
`TypeError: Enzyme received a complex CSS selector ('a[href='http://example.com/xyz']') that it does not currently support`

If I remove the domain name from URL and make it relative, it works:

`.find('a[href='/xyz']')`

It gives no error and works as expected.

**Comment by lelandrichardson** [comment]
Hmm. This is an unfortunate side effect of the shitty CSS parsing we are doing.

An alternative for you right now is to do: `.find({ href: url })` instead of the stringified CSS selector.

**Comment by andrewmclagan** [comment]
also experiencing this with a selector as follows:

`find('img[src="http://image.com/image.jpg"]')

**Comment by Aweary** [comment]
@lelandrichardson is there a long-term plan for how you guys want to approach CSS selector parsing?

**Comment by stevenmusumeche** [comment]
An update on this?

**Comment by aweary** [comment]
@stevenmusumeche our CSS parsing is still shitty, we're [tracking it](https://github.com/airbnb/enzyme/projects/1) and hope to implement an actual CSS parser soon. Until then I'd recommend the workaround that @lelandrichardson mentioned:

>An alternative for you right now is to do: .find({ href: url }) instead of the stringified CSS selector.

**Comment by FinnFrotscher** [comment]
+1

**Comment by aweary** [comment]
This will be resolved by https://github.com/airbnb/enzyme/pull/1086

**Comment by ljharb** [comment]
Closed in #1086
