### ISSUE TITLE
Invariant Violation error thrown when testing on Stateful Component

### ISSUE THREAD

**Issue by qingweibinary** [airbnb/enzyme#284]
I am using React 15.

I have a component which call setTimeout in componentWillMount, the function is similar to 

``` javascript
class Test extends Component {
    componentWillMount() {
        this.timer = setTimeout(() => this.setState(....), 4000);
    }
    // .....
}
```

When the timer is triggered, an error is thrown as follow

`Invariant Violation: React DOM tree root should always have a node reference.`

Here's a related issue on React
https://github.com/facebook/react/issues/6232

Is there anyway I could prevent throwing error when testing, without using JSDOM?

Edit1: 
`this.setState(...)` to `() => this.setState(...)`

**Comment by ljharb** [comment]
Perhaps do you mean `setTimeout(() => this.setState(…), 4000)`? As is, you'll be passing the return value of `setState` into `setTimeout`, but setting the state immediately.

**Comment by qingweibinary** [comment]
@ljharb yes, sorry for the typo

**Comment by imontiel** [comment]
Do you have a `componentWillUnmount` that clears the timer?

You will have to run `wrapper.unmount()` after your tests to make sure that the `componentWillUnmount` gets called.

**Comment by ljharb** [comment]
You generally don't want to call setState inside componentWillMount.
