### ISSUE TITLE
Conditionally require React version specific modules

### ISSUE THREAD

**Issue by levithomason** [airbnb/enzyme#285]
Currently, `react-compat.js` blindly requires modules that are only existent in React v0.13 (`react/lib/ReactContext`, `react/lib/ExecutionEnvironment`).  React 0.15 does not include these modules, so the `require()`s. break.  This is the root issue with #47.

The fix shouldn't be to have the bundlers shim these requires, but to not require missing modules in the first place.

One solution might be to check the version of the currently installed React, then enzyme can have conditional logic to handle React version specific cases:

**react-compat.js**

```js
import React from 'react' // load the consumer's PeerDep version
import semver from 'node-semver'

const isReactVersion = (ver) => semver.satisfies(React.version, ver)

// @ ln 23
const ReactContext = isReactVersion('0.13') ? require('react/lib/ReactContext') : {}

// @ ln 41
if (isReactVersion('0.13')) {
  require('react/lib/ExecutionEnvironment').canUseDOM = true
}
```

Some kind of mechanism to properly deal with multiple versions of react is probably needed for this project.  Hope this helps spur some good ideas.

**EDIT**
The code snippet is untested and for illustrative purposes only ;)

**Comment by lelandrichardson** [comment]
@levithomason I'm afraid this won't change anything. This is actually *exactly* how it already works. Bundlers such as webpack and browserify use static analysis to find any and all `require` calls to build a dependency graph, even if that require call is unreachable.

We will likely be dropping 0.13 in a version 3 bump, but for now - this is something we have decided that we are going to live with.

**Comment by levithomason** [comment]
With a small refactor of the conditional, I believe it could be auto removed with dead code removal.  Since webpack will remove any code inside an unreachable conditional.  In either case, dropping 0.13 is even more welcomed.

**Comment by lelandrichardson** [comment]
@levithomason I'd be happy to make a change that would allow for a branch to fall under dead code elimination....  AFAIK this only works for compile-time constant expressions (which can also be comparisons to `process.env` variables through envify).

How do you suggest changing the conditional?

**Comment by levithomason** [comment]
Right you are, I had thought uglify/webpack would resolve that conditional but it didn't.  Shame on me.

I was able to get this working on `v2.2.0` with a conditional require though:

**react-compat.js**
```js
// up top
const reactContextPath = REACT013 ? 'react/lib/ReactContext' : 'empty'
const executionEnvironmentPath = REACT013 ? 'react/lib/ExecutionEnvironment' : 'empty'

// @ ln 23
const ReactContext = require(reactContextPath);

// @ ln 41
require(executionEnvironmentPath).canUseDOM = true;
```

**Test repo**

I also made an example repo that rebuilds enzyme with this ^ file.  It has a minimal webpack build with it as well: https://github.com/levithomason/enzyme-conditional-require.

There are pseudo diffs in `react-compat.js` file where I modified it:

```js
  /* ------------------------------------------------------------------------
  /* CHANGE
  /* -    const ReactContext = require('react/lib/ReactContext');
  /* + */ const ReactContext = require(reactContextPath);
  // ------------------------------------------------------------------------
```

See the `README.md`.

**Comment by levithomason** [comment]
...also, I just booked a 5 day trip to Hawaii on airbnb in between writing tests with enzyme, thanks for everything :stuck_out_tongue:!

**Comment by lelandrichardson** [comment]
@levithomason this is cool work. I think this may only work for webpack though...

btw, have fun on your trip!
