### ISSUE TITLE
Error: Cannot find module './package' from 'index.js'     

### ISSUE THREAD

**Issue by goivemaster** [airbnb/enzyme#286]
getting this error when trying to import shallow from enzyme in test component for the first time.

**Comment by ljharb** [comment]
What version of enzyme? Can you include a sample of how you're importing `shallow`?

**Comment by goivemaster** [comment]
my enzyme version is 2.2.0 

import { shallow } from "enzyme";

```
Error: Cannot find module './package' from 'index.js'
    at Loader._resolveNodeModule (/home/silver/projects/pipernew/client/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:431:11)
    at Object.<anonymous> (/home/silver/projects/pipernew/client/node_modules/cheerio/index.js:11:19)
    at Object.<anonymous> (/home/silver/projects/pipernew/client/node_modules/enzyme/build/ReactWrapper.js:13:16)

```
I have now added json to the moduleFileExtensions config for jest in my project which resolves the issue. I have submitted a pr to change the docs accordingly.

**Comment by ljharb** [comment]
ah ok, so it's specific to jest mocking. thanks for clarifying

**Comment by ItsCosmo** [comment]
This is not specific to Jest. It is related to cheerio. In my case it was happening with karma configured using webpack. I provided a workaround here: https://github.com/cheeriojs/cheerio/issues/836

**Comment by ljharb** [comment]
Hmm - that seems like an issue with webpack then. implicit `.json` is part of node's require(), so if a tool doesn't support it, then it's broken ¯\\\_(ツ)_/¯

**Comment by ItsCosmo** [comment]
It might be a little more complicated than that. I left out some details in my response. I had webpack configured to resolve to a source folder as follows:
```
resolve: {
    root: path.resolve("./src"),
    extensions: ['', 'js', 'jsx']
}
```
It looked to me like because cheering was doing `require("./package")`, the lack of extension was causing webpack to look under the `.src/` folder for the file. The workaround I provided forced the .json extension, thus bypassing the resolve.

Yes, the `require("./package")` statement in cheerio's index.js is legit, but then again so is the webpack configuration. Webpack does provide a plugin for dealing with weird things like this, so maybe this is just one of those things ¯\_(ツ)_/¯

**Comment by ttrmw** [comment]
With @goivemaster's fix I'm seeing this issue intermittently unless I run jest with the `--runInBand` flag. 

The error I see is:

``
● AppControls › it should render link text
  - TypeError: _cheerio2.default.load is not a function
        at render (../node_modules/enzyme/build/render.js:30:31)
        at Object.eval (__tests__/AppControls-test.js:14:66)
        at handle (../node_modules/worker-farm/lib/child/index.js:41:8)
        at process.<anonymous> (../node_modules/worker-farm/lib/child/index.js:47:3)
        at emitTwo (../events.js:87:13)
        at process.emit (../events.js:172:7)
        at handleMessage (../internal/child_process.js:689:10)
        at Pipe.channel.onread (../internal/child_process.js:440:11)
``

Failure moves around tests intermittently as mentioned unless tests are run in a single thread (`--runInBand`).

**Comment by ttrmw** [comment]
FYI I think it must have been a fluke that this worked with `--runInBand` on my colleague's machine - he too is now seeing intermittent failures.

I see that we are not the only ones having this issue, #309 looks to be related

**Comment by calclavia** [comment]
I can replicate this issue with Jest and React Native.

**Comment by blainekasten** [comment]
What version of jest?

**Comment by calclavia** [comment]
@blainekasten Version 13 (the newest one). "enzyme": "^2.3.0"

```
"jest": {
    "verbose": true,
    "scriptPreprocessor": "<rootDir>/jest.js",
    "testPathDirs": ["src"],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ],
    "testFileExtensions": [
      "ts",
      "tsx"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "unmockedModulePathPatterns": [
      "react",
      "react-native",
      "enzyme",
      "chai",
      "react-addons-test-utils",
      "rxjs"
    ],
    "collectCoverage": true,
    "coverageDirectory": "out/coverage",
    "haste": {
      "defaultPlatform": "ios",
      "platforms": [
        "ios",
        "android"
      ],
      "providesModuleNodeModules": [
        "react",
        "react-native"
      ]
    }
  }
```

**Comment by blainekasten** [comment]
Are you also using the `import` syntax? Try using commonjs `require()`

**Comment by calclavia** [comment]
@blainekasten I tried both using `const { shallow } = require('enzyme');` and es6 imports. Same error.

**Comment by aj0strow** [comment]
If you add `json` to module file extensions, it works.

```json
"jest": {
    "moduleFileExtensions": [
      "js",
      "json"
    ]
}
```

**Comment by calclavia** [comment]
@aj0strow Thanks, that worked perfectly!

**Comment by Aweary** [comment]
Thanks @aj0strow! I'm closing this as it seems resolved, and it's not actually an enzyme issue, so nothing actionable for us.

**Comment by arfordweb** [comment]
I know this is closed, but it seems that if setting the "moduleFileExtensions" property without adding "json" causes an issue, then this is an issue with Jest, if it causes an issue in the execution of one of its dependencies.

Enzyme is using Cheerio `0.20.0`.  In Cheerio `0.22.0`, they added an explicit .json extension to their import statement in their `index.js`.  So, revving your dependency should fix the issue.

Here's their changlog: https://github.com/cheeriojs/cheerio/blob/master/History.md
One item in the latest release is: `add extension for JSON require call`

**Comment by ljharb** [comment]
This is definitely a webpack and/or jest bug. `json` files are automatically requireable sans extension in node, so anything that doesn't do that by default is broken.

**Comment by nickkhall** [comment]
I know this post is closed, but I'd like to share the silly solution that solved my issue.

The problem in my case was someone was importing the component from the HOC (`index.js`) that exports the component with `withStyles()` instead of the importing the component itself in the test. (`import component from './component';`)

Therefore the solution was to import the component from the exported component and not the HOC or connected component.

**Comment by ljharb** [comment]
@nickkhall that's not actually the right solution :-) you want `.dive()`, and never to export anything unwrapped just for tests (or make any changes to production code, just for tests)
