### ISSUE TITLE
karma - Error: no such file or directory

### ISSUE THREAD

**Issue by alawatthe** [airbnb/enzyme#289]
I'm currently trying to get enzyme working with an karma, webpack, mocha setup.
Unfortunately karma does not find a configuration file, when I am using enzyme.

I am reporting the bug in the enzyme repo since everything works fine until I import ```enzyme```.
Note, that I don't need to call any functions of ```enzyme```, importing like
```js
import {shallow} from 'enzyme';
```
is enough to trigger the error.

Needless to say, the file exists and has the following content
```js
const integrationTests = require.context(
  '../../src',
  true,
  /([\w-]+\/)*\/test\/[\w-]+\.spec\.js$/
);

integrationTests.keys().forEach(integrationTests);
```

This is the error message I get:

```sh
> env BABEL_ENV='test' node node_modules/karma/bin/karma start build/karma/karma.conf.js

01 04 2016 10:44:33.499:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/build/webpack/tests-integration.config.js' }
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/name/Project/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.readFile (/Users/name/Project/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/name/Project/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (/Users/name/Project/node_modules/karma-webpack/index.js:160:3)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
Hash: 3c5b4b6d5b26acf0d742
Version: webpack 1.12.9
Time: 8562ms
```

I am using
```
react: 0.14.8
enzyme: 2.2.0
karma 0.13.22
```
Does anyone know how to fix this issue? Or how I can debug this?
Any help would be greatly appreciated. :-)

**Comment by Terminux** [comment]
Hi. 

I had the same issue and I solved it  by adding this config in my karma.conf.js file as mentioned in the enzyme documentation (http://airbnb.io/enzyme/docs/guides/karma.html)

```js
config.set({
  ...
  webpack: {
    ...
    exernals: {
      'react/lib/ExecutionEnvironment': true,
      'react/lib/ReactContext': true
    }
  }
});
```
hope that helps

**Comment by alawatthe** [comment]
@Terminux Thank you for the link, this was one of the problems I had.  An other one was https://github.com/cheeriojs/cheerio/pull/832.

Note to myself: debugging webpack is easier when the webpack NoErrorsPlugin is commented out.

**Comment by pd4d10** [comment]
@Terminux 's solution is correct. Just notice that `exernals` should be `externals` :)
