### ISSUE TITLE
Add ReactWrapper.getDomNode() method

### ISSUE THREAD

**Issue by tarjei** [airbnb/enzyme#290]
Hi, sometimes it is usefull to work on the dom node of the rendered component - either to trigger native events or (in my case) to be able to use a complex dom selector. Therefore it would be great if the ReactWrapper had a method to get the DOM node directly.

**Comment by christian-schulze** [comment]
@tarjei - this should be addressed when #679 is merged.

**Comment by tarjei** [comment]
Thanks!

**Comment by ljharb** [comment]
Issues should remain open until PRs are merged.

**Comment by ljharb** [comment]
Merged in #679.

**Comment by FezVrasta** [comment]
It looks like it's missing in the flow annotations?

![image](https://user-images.githubusercontent.com/5382443/27648686-99130282-5c2f-11e7-81d5-3ce75de1a9cb.png)

**Comment by ljharb** [comment]
Whoever maintains those would need to update them then.

**Comment by FezVrasta** [comment]
I submitted a PR to flow-typed
