### ISSUE TITLE
Documentation for simulate is minimal and dblclick event is named doubleclick

### ISSUE THREAD

**Issue by mordrax** [airbnb/enzyme#310]
I tried to simulate a double click like this:
```javascript
component.find('[id="purse"]').parent().simulate('dblclick');
```
Because the documentation for [simulate](http://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html) seems to suggest dom events are used.
I'm pretty sure (although could be wrong) that the dom event for double click is [dblclick](https://developer.mozilla.org/en-US/docs/Web/Events/dblclick).

Then I looked through the repo and found mentions of `doubleclick`, and doing this:
```javascript
component.find('[id="purse"]').parent().simulate('doubleclick');
```
works.

So it would be good to have a list of simulated events other than click because that's in every tut and example but there's no documentation about the list of events that can be simulated.
Does [this](https://github.com/airbnb/enzyme/blob/699ec7e39560a68c198ecf80b59d177d003fc869/src/Utils.js#L230) have something to do with it?

**Comment by ljharb** [comment]
You're simulating React events, not DOM events, which is why `doubleClick` is expected - but yes, I think perhaps the native name there needs to change from `doubleclick` to `dblclick`.

**Comment by ljharb** [comment]
Since it's "native" to "react event" map, the "native" should match native - so I think that the key in https://github.com/airbnb/enzyme/blob/699ec7e39560a68c198ecf80b59d177d003fc869/src/Utils.js#L230 should indeed be changed to "dblclick" to match user expectations.

**Comment by mordrax** [comment]
Yeah ok, gotcha.
