### ISSUE TITLE
.hasClass with several class names

### ISSUE THREAD

**Issue by SaidTayebi** [airbnb/enzyme#312]
How to check if an element has a list of classes ?
Example: 
`expect(ShowMoreLessButton.hasClass('btn', 'btn-sm')).to.equal(true);`

**Comment by ljharb** [comment]
`expect(['btn', 'btn-sm'].every(c => ShowMoreLessButton.hasClass(c))).to.equal(true)`?

**Comment by AnthonyDS** [comment]
const wrapper = mount(
        <Post
            content={content}
        />
);
const post = wrapper.find('article');
expect(['top', 'active'].every(c => post.hasClass(c))).to.equal(true);

**Comment by lucasdeassis** [comment]
I've just tested here and you can do `expect(ShowMoreLessButton.hasClass('btn btn-sm')).to.equal(true);`

**Comment by aweary** [comment]
It should support querying for multiple classes now, so I'll close this.
