### ISSUE TITLE
Add `.render()` method to ReactWrapper

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/enzyme#32]

**Comment by geowarin** [comment]
Would this make `mount()` work with stateless functional components?

**Comment by lelandrichardson** [comment]
@geowarin no this is unrelated. This would be a method to turn a sub-tree of a `mount()` wrapper into a cheerio wrapper (ie, what is returned by `render()`)

**Comment by dustinsanders** [comment]
Can you provide more insight on this? I understand why this is needed for Shallow rendering, but it seems like you could do everything with `find()` if you are using `mount()` since the entire tree is rendered.

**Comment by lelandrichardson** [comment]
Merged.
