### ISSUE TITLE
.find("textArea[name='description']") is broken

### ISSUE THREAD

**Issue by cliren** [airbnb/enzyme#321]
The following find fails to find the component in the latest version of enzyme (2.2.0), looks likes its broken in 2.1.0. We are using React 0.14.x, does that mean we can't upgrade enzyme?

`var component = enzyme.mount(Component, props);`
`var textArea = component.find("textArea[name='description']");`
`textArea.simulate('change');`

The following error occurs:
// Error: This method is only meant to be run on single node. 0 found instead.

Test runs fine with 1.5.0 version.

//Component
`<div><textarea name="description" rows="5" cols="55" /><div>`

**Comment by ljharb** [comment]
@cliren why would `textArea` find a `textarea`?

**Comment by cliren** [comment]
@ljharb Sorry I should have given a complete example, textarea is child of another component.

**Comment by ljharb** [comment]
Can you update the code for `Component`? it doesn't contain `textArea`.

**Comment by cliren** [comment]
ah..., that's right it should be textarea instead of textArea. That fixed it. But still wondering why this passed in 1.5.0, guessing its a bug that got fixed. Here is an example test that would pass 1.5.0 and not in the latest just for reference.

describe("TextArea Test", ()=> {
  const TestComponent = React.createClass({
    render(){
      return (
        <div>
          <textarea/>
          <input/>
        </div>
      );
    }
  });

  it("should render text area", () => {
    let testComponent = mount(<TestComponent/>);

    testComponent.find("input").length.should.eql(1);
    testComponent.find("textArea").simulate("change");
  });
});

**Comment by lelandrichardson** [comment]
I'm not sure why `.find("textArea")` would have passed in *any* version of enzyme. The casing definitely matters here.

**Comment by coderefractor** [comment]
Agree with you.

**Comment by ljharb** [comment]
@coderefractor that would have passed precisely because calling "simulate(change)" is not an assertion - ie, the line was always a noop. At some point, enzyme started throwing when calling simulate on a wrapper that doesn't contain one node, turning your noop into a failure.

**Comment by cliren** [comment]
got it, thanks!
