### ISSUE TITLE
.contains not matching partially

### ISSUE THREAD

**Issue by Rob-pw** [airbnb/enzyme#322]
```
var element = shallow(
  <div>
    <p>Foo. 
      <span>Bar!</span>
    </p>
  </div>
);

expect(element.contains('Foo.')).to.be.true;
```

This test will fail since the node property of `<p>` is `Foo.` (with a trailing space after it).

.contains(string) should match partially on the node's contents.

**Comment by ljharb** [comment]
`expect(html()).to.contain('Foo.')` will work. `contains` is for precise checking if something contains a subtree.

**Comment by alangolm** [comment]
How can I check that a string does NOT exist in the html subtree? Basically what is the negation of expect(wrapper.html()).toContain(‘hello world’)?

**Comment by ljharb** [comment]
`.not.toContain`?

**Comment by alangolm** [comment]
Yep, that worked. Thank you!
