### ISSUE TITLE
Enzyme break after React upgrade from 15.0.0-rc2 to 15.0.1

### ISSUE THREAD

**Issue by nehaleem** [airbnb/enzyme#325]
We are using enzyme to test our React components together with browserify.
But after upgrade React from rc2 to stable 15.0.1:

If i'll run tests, i'll get this error:
`Error: Cannot find module 'react/addons' from '/myproject/node_modules/enzyme/build`

But installed version is 15.0.1 (React.version) which is using module `react-addons-test-utils`
If i'll remove this line:
`TestUtils = require('react/addons').addons.TestUtils;`
from `build\react-compat.js` its works properly.

Package.json:
```
"dependencies": {
    "react": "15.0.1",
    "react-addons-perf": "15.0.1",
    "react-addons-test-utils": "15.0.1",
    "react-addons-update": "15.0.1",
    "react-dom": "15.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.7.0",
    "babel-plugin-external-helpers-2": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babelify": "^7.2.0",
    "browserify": "^13.0.0",
    "enzyme": "^2.2.0",
    "watchify": "^3.7.0"
  }
```

**Comment by JakubBarta** [comment]
same problem here

**Comment by jodal** [comment]
I believe this was fixed by commit 77e6bdc17ad52aefd9ccdc82d4197bd0709c95aa. I have the same issue with v2.2.0, but it works when running master. Would be nice with an Enzyme release which works with React 15.

**Comment by ljharb** [comment]
That commit shouldn't have been able to impact anything, unless you're relying on npm 2 implicitly installing peer deps?

**Comment by jodal** [comment]
Ok, that might not be the fix then. A release that works with React 15 out of the box is still wanted though :-)

**Comment by ljharb** [comment]
The latest release is already that. The only difference is potentially a peer dep warning.

We'll try to cut a release soon.

**Comment by nehaleem** [comment]
Guys, can you please release new version ?, this commit would be great :)

**Comment by ljharb** [comment]
@nehaleem enzyme already works fine with React 15. The commit you're referencing is just documentation.
