### ISSUE TITLE
first newline missing from text() output

### ISSUE THREAD

**Issue by kagia** [airbnb/enzyme#326]
when writing tests that compare the output of `.text()`, I am surprised to find that the first new line character is missing.

I have [reproduced](https://github.com/andela-bkagia/enzyme-example-mocha/tree/text-issue) this issue on a fork of the demo.

So let's say I have a component:

``` jsx
class Foo extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const content = '{\n hallo}';
    return (
      <div className="foo">{ content }</div>
    );
  }
}
```

and a test

``` jsx
describe("A suite", function() {
  it("new lines are preserved", function() {
    expect(shallow(<Foo />).text()).to.equal('{\n hallo}');
  });
});
```

I receive the following error

``` text
AssertionError: expected '{ hallo}' to equal '{\n hallo}'
```

**Comment by ljharb** [comment]
All browsers reduce all whitespace down to a single space - I'd expect the same behavior here.

**Comment by andela-bkagia** [comment]
@ljharb it seems not all whitespace is not being reduced, only the _first_ newline.

so a string like `{\n hallo \n world\n again}` comes back as `{ hallo \n world\n again}`. 

Also notice that the newline is being removed entirely rather than being collapsed to a space.

**Comment by ljharb** [comment]
@andela-bkagia if you try `\nhallo`, is it still being removed? I said "collapsed" because `\n ` is turning into ` `

**Comment by Aweary** [comment]
@ljharb using @andela-bkagia's example repo, `\nhallo` is returned from `text()` as `_hallo`. With the DOM API we get:

```js
var div = document.createElement('div')
div.innerText = '\nhallo'
div.textContent
// 'hallo'
```

I'm not sure if `text()` is expected to return the same value as `textContent`, but if it is it seems to be handling whitespace incorrectly.

**Comment by ljharb** [comment]
This seems to be a jsdom issue? Happy to reopen if someone can provide a failing test case.

**Comment by ZChenzy** [comment]
This is my minimally reproducible test:
`describe("test", ()=>{

    let text = "Hello\nworld\nI\nam\nme"
    class Test extends React.Component<any,any>{

        render(){
            return <span>{text}</span>
        }
       
    }

    let wrapper = shallow(<Test/>)
    
    it("should return the correct text", ()=>{
        expect(wrapper.text()).toEqual(text)
    })
})`

` test › should return the correct text

    expect(received).toEqual(expected)

    Expected value to equal:
      "Hello
    world
    I
    am
    me"
    Received:
      "Hello world
    I
    am
    me"

    Difference:

    - Expected
    + Received

    -Hello
    -world
    +Hello world
     I
     am
     me`
