### ISSUE TITLE
Support for find('button')

### ISSUE THREAD

**Issue by danielbachhuber** [airbnb/enzyme#330]
Searching for a button `<button>` doesn't seem to be supported.

**Comment by ljharb** [comment]
It should be - can you provide sample implementation and test code?

**Comment by danielbachhuber** [comment]
> can you provide sample implementation and test code?

Sure — I'll do so when I have a moment to produce a decoupled example.

**Comment by danielbachhuber** [comment]
I can't reproduce this outside of my project :( I'll follow up if I reproduce this again in a different context.
