### ISSUE TITLE
can't import enzyme without module manager

### ISSUE THREAD

**Issue by micaelmbagira** [airbnb/enzyme#333]
I don't use neither Webpack or Browserify. So I use `require` to get enzyme, but when I run the test I have the following error `Can't find variable require`.

````
'use strict';

var shallow = require('enzyme').shallow;

describe('Footer', function () {
  it('should be a footer', function () {
    expect(shallow(<Footer/>).is('footer')).toBe(true);
  });
});
````

**Comment by ljharb** [comment]
A module system is basically a requirement to do frontend dev in 2016. I'd highly recommend getting one in place.

**Comment by Aweary** [comment]
`require` is part of the Node.js module system. It doesn't sound like you're using node to run your testS at all which would give you this error. Webpack and Browserify are build tools, not module systems. `npm` would be the module system you should be using here.

**Comment by Aweary** [comment]
@micaelmbagira I'm going to close this for now as there doesn't seem to be anything actionable here on our part.
