### ISSUE TITLE
How to test for disabled attribute?

### ISSUE THREAD

**Issue by ttrmw** [airbnb/enzyme#336]
I have a component that, given some props, sets `disabled` on a select. 

What would be the right way to test for this? I've set up the test like so: 

``` js
it("disables company select", () => {                                             
    const wrapper = render(<OpportunityEditor opportunity={mockOpportunity}    
                                              companies={mockCompanies}             
                                              departments={mockDepartments} />);

    const companySelect = wrapper.find("select[name='company[remote_id]']");   
});
```

and, upon examining companySelect I can see that `attribs`, where I would probably expect to see the attribute, does not contain `disabled`.

**Comment by ttrmw** [comment]
Okay - I was being silly, disabled is actually set on the select's fieldset in my component - d'oh!

I have ended up with the following assertion, which still feels clunky:

```js
 expect(companySelect.closest("fieldset")[0].attribs["disabled"]).toBe("");
```

Is there a cleaner approach?

**Comment by ljharb** [comment]
does `expect(companySelect.closest('fieldset').props('disabled')).toBe('');` work?

**Comment by ttrmw** [comment]
Nah:

```
  - TypeError: companySelect.closest(...).props is not a function
        at Object.eval (__tests__/OpportunityEditor-test.js:79:46)
        at attemptSync (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1791:24)
        at QueueRunner.run (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1779:9)
        at QueueRunner.execute (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1764:
...
```

**Comment by Aweary** [comment]
@ttrmw what does `companySelect.closest()` return?

**Comment by mvattuone** [comment]
I was having a problem with `props()` but I think if you use `prop('disabled')`, you'll find success.

**Comment by christiansakai** [comment]
I'm having similar issue. I was trying to check whether my form contains a disabled button or not.

The test always fails, until I remove disabled property from the button, then it works.

So this fails
```
// Form.js
// --- other components
<button type="submit" disabled={pending}>
   {(() => {
       if (pending) {
           return <i className="fa fa-spinner fa-spin"></i>;
       }
   })()}Sign up
</button>
// -- other components
```
```
// Form.test.js
expect(wrapper.contains(
   <button type="submit" disabled="true">
      Sign up
     </button>
)).to.equal(true);
```

but this works, by removing the disabled property
```
// Form.js
// --- other components
<button type="submit">
   {(() => {
       if (pending) {
           return <i className="fa fa-spinner fa-spin"></i>;
       }
   })()}Sign up
</button>
// -- other components
```
```
// Form.test.js
expect(wrapper.contains(
   <button type="submit">
      Sign up
     </button>
)).to.equal(true);
```

**Comment by ljharb** [comment]
@christiansakai that's to be expected - `"true"` is the string "true", which is an invalid valid for the "disabled" HTML attribute. In pure HTML it'd be `disabled="disabled"`, and `disabled={true}` or just `disabled` is a shortcut for that.

**Comment by christiansakai** [comment]
@ljharb right, thank you

**Comment by kwnccc** [comment]
@ttrmw @christiansakai Another way you could probably check the html attribute above could be 
`expect(companySelect.closest('fieldset').is('[disabled]')).toBe(true)`;

**Comment by SavePointSam** [comment]
@kwnccc Unfortunately, that won't work either as `.is('[disabled]')` is always going to return true if a valid node is found.

For right now the cleanest and more reliable way I've found to determine if an element has the disabled attribute is the following:

```
wrapper.find('input').html().includes('disabled=""');
```

This, however, can be replaced with a more accurate CSS disabled pseudo selector:

```
wrapper.find('input:disabled');
```

Or with a dedicated attribute lookup. For example:

```
wrapper.find('input').hasAttr('disabled');
wrapper.find('input').hasAttribute('disabled');
```

**Comment by arnarleifs** [comment]
I believe you can use wrapper.getNode().props.disabled.

**Comment by dnp1** [comment]
Currently you can use `wrapper.prop('disabled')`.

The bug on selector `[disabled]` persists, still.

**Comment by tomisu** [comment]
I think the best current way to do this is:

`wrapper.getDOMNode().disabled`

This will be `true`/`false`. It's short and clear.

**Comment by karak** [comment]
@dnp1 How can we reproduce "the bug on selector `[disabled]`?" All the test-cases I tried in the code:<https://github.com/karak/enzyme-issue-336/blob/master/test.jsx> did work fine.

**Comment by Fil923** [comment]
Try with a disabled button, the bug persists

**Comment by walliby** [comment]
```expect(companySelect.closest("fieldset").hasAttribute('disabled','disabled')).toBeFalsy()```
or
```expect(companySelect.closest("fieldset").hasAttribute('disabled','disabled')).toBeTruthy()```

**Comment by ljharb** [comment]
This seems addressed; if you're still having trouble and using `render`, you'll need to file an issue on cheerio - if you're using `shallow`/`mount`, please file a new issue.

**Comment by dinukadesilva** [comment]
For me, it worked as below

`expect(companySelect.find('input').props()["disabled"]).toBe(true)`

`props()` returns an object having all the attributes of the selector and then it can be browsed as an object. 

Hope this helps too....

**Comment by avudai-16thyard** [comment]
Hi All,

I am getting like 

TypeError: compiled.find is not a function

any solution??

**Comment by ljharb** [comment]
@avudai-16thyard please file a new issue, and include your test code.

**Comment by JESii** [comment]
For those who get here in the present, `getNode()` is no longer supported (as in `wrapper.getNode().props.disabled`).

**Comment by chris542** [comment]
> For me, it worked as below
> 
> `expect(companySelect.find('input').props()["disabled"]).toBe(true)`
> 
> `props()` returns an object having all the attributes of the selector and then it can be browsed as an object.
> 
> Hope this helps too....

I also found `companySelect.find('input[type="submit"]').props().disabled).toBeTruthy()` working.
 :D!

**Comment by JESii** [comment]
Thanks, Chris!.  <https://github.com/notifications/beacon/AAAADZVFECKSVHYXZMIASUTQHAZOXA5CNFSM4CBN3S52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5PZEYA.gif>

**Comment by alex24-olex** [comment]
> Nah:
> 
> ```
>   - TypeError: companySelect.closest(...).props is not a function
>         at Object.eval (__tests__/OpportunityEditor-test.js:79:46)
>         at attemptSync (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1791:24)
>         at QueueRunner.run (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1779:9)
>         at QueueRunner.execute (../node_modules/jest-jasmine2/vendor/jasmine-2.3.4.js:1764:
> ...
> ```
> 
> I also tried `...closest(..)[0]` but this had the same result.

pagal ho kya sale

**Comment by jinocj** [comment]
expect(app.find('.btn').props().disabled).toBe(true)

this seems ok !!

**Comment by superelement** [comment]
This worked for me (`plusBtn` is of type `ReactWrapper`)
```
expect(plusBtn.getDOMNode().hasAttribute("disabled")).toBe(true);
```
