### ISSUE TITLE
Improve .html() print

### ISSUE THREAD

**Issue by montogeek** [airbnb/enzyme#345]
Hi!

At this moment when you log `component.html()` it displays one line:
`<span><a role="button" class="nav-button--zeba8r" aria-expanded="false" data-toggle="dropdown"><span>USD</span><span class="nav-button-caret--2D3OWP"></span></a><ul role="menu" class="currency-dropdown--3UHnJ9 dropdown-menu--23TTls"></ul></span>`

Would be great if it could print a prettify version:
```html
<span>
  <a role="button" class="nav-button--zeba8r" aria-expanded="false" data-toggle="dropdown">
    <span>USD</span>
    <span class="nav-button-caret--2D3OWP"></span>
  </a>
  <ul role="menu" class="currency-dropdown--3UHnJ9 dropdown-menu--23TTls">
  </ul>
</span>
```

**Comment by ljharb** [comment]
That could interfere with string comparisons. I'd recommend piping the output through https://www.npmjs.com/package/js-beautify (which handles HTML).

**Comment by montogeek** [comment]
Thank you :)
