### ISSUE TITLE
Newline immediately following class causes '.classname' selector to fail

### ISSUE THREAD

**Issue by GabeIsman** [airbnb/enzyme#347]
This should be approximately the minimal test case. Apologies for not writing an actual failing test.
Component:
```js
<TestComponent className={`some-class
`} />
```
Test:
```js
expect(shallow(<TestComponent />).is('.some-class')).to.be.true(); // Actually false
```
Tested with version 2.2.0.

**Comment by ljharb** [comment]
Does the same happen if you have a trailing space on the class name?

**Comment by GabeIsman** [comment]
@ljharb Nope. Just a new line from what I've seen.

**Comment by ljharb** [comment]
@GabeIsman thanks! does it also occur on `mount`?

**Comment by GabeIsman** [comment]
@ljharb Yep!

**Comment by Aweary** [comment]
@ljharb would it work if we just stripped any trailing newline characters (or maybe all non-signiciant whitespace?) in [`instHasClassName`](https://github.com/airbnb/enzyme/blob/master/src/MountedTraversal.js#L54)?

**Comment by GabeIsman** [comment]
👍
