### ISSUE TITLE
Enzyme and Jest

### ISSUE THREAD

**Issue by ssoliwal** [airbnb/enzyme#350]
I am trying to run enzyme and Jest for unit test with react-native and running into this issue at the import line:
import { shallow, mount, render } from 'enzyme';

**tests**/assets/enzymeTest.js 
● Runtime Error
TypeError: Cannot convert undefined or null to object

**package.json:**

> "scripts": {
>     "start": "node_modules/react-native/packager/packager.sh",
>     "lint": "eslint js",
>     "test": "jest"
>   },
>   "devDependencies": {
>     "babel-jest": "*",
>     "babel-core": "~6.7.7",
>     "babel-preset-react-native": "~1.6.0",
>     "chai": "~3.5.0",
>     "enzyme": "~2.0.0",
>     "eslint": "^2.2.0",
>     "eslint-plugin-react": "^4.1.0",
>     "jest": "^0.1.40",
>     "jest-cli": "^0.8.2",
>     "mocha": "~2.4.5",
>     "pre-push": "^0.1.1",
>     "react": "~0.14.8",
>     "react-addons-test-utils": "~15.0.1",
>     "react-dom": "~15.0.1",
>     "react-native-mock": "0.0.7"
>   },
>   "jest": {
>     "preprocessorIgnorePatterns": [
>       "node_modules/enzyme"
>     ],
>     "scriptPreprocessor":  "node_modules/babel-jest",
>     "setupTestFrameworkScriptFile": "jestSupport/setupTestFramework.js",
>     "setupEnvScriptFile": "node_modules/react-native/jestSupport/env.js",
>     "unmockedModulePathPatterns": [
>       "promise",
>       "source-map",
>       "react",
>       "enzyme",
>       "node_modules/react",
>       "node_modules/fbjs",
>       "node_modules/react-dom",
>       "node_modules/react-addons-test-utils",
>       "react-dom",
>       "react-addons-test-utils",
>       "fbjs",
>       "cheerio",
>       "htmlparser2",
>       "underscore",
>       "lodash",
>       "domhandler",
>       "object.assign",
>       "define-properties",
>       "function-bind",
>       "object-keys"
>     ],
>     "testPathIgnorePatterns": [
>       "/node_modules/",
>       "packager/react-packager/src/Activity/"
>     ],
>     "testFileExtensions": [
>       "js"
>     ]
>   },

**Comment by gbhasha** [comment]
can you the content of enzymeTest.js?

**Comment by ssoliwal** [comment]
`import React from 'react';
import { shallow, mount, render } from 'enzyme';

describe("A suite", function() {

});`

**Comment by ssoliwal** [comment]
I cloned the project on github ([enzymeWithJest](https://github.com/lelandrichardson/enzyme-example-jest)) and copied over my reactNative source code into that workspace and now i am seeing a different error:

```
> jest "enzymeTest"

Using Jest CLI v0.8.2, jasmine1
Running 1 test suite...[SyntaxError: Unexpected token ...]
```

adding '--verbose' to jest doesn't seem to help either.

**Comment by Aweary** [comment]
Hey @ssoliwal have you had any progress on this error in the last week? Or are you still having the same problem?

**Comment by blainekasten** [comment]
The runtime error seems like you are just missing `unmockedModulePathPatterns` ?
The syntax error sounds more like your preprocessing is not quite correct.

**Comment by ssoliwal** [comment]
@Aweary @blainekasten i still have the same issue.

not sure what i am missing in "unmockedModulePathPatterns", and my preprocessing is described in the package.json:

"scriptPreprocessor":  "<rootDir>/node_modules/babel-jest"

I am seeing this issue once i have some react-native code added to the test.

Is there way to fix it or have a verbose error thrown, its almost impossible to debug with one line error.

**Comment by blainekasten** [comment]
You don't need to specifiy babel-jest like that. Jest is [smart enough](https://github.com/babel/babel-jest) to know if babel-jest is installed in node_modules and then use it.

as for the unmocked stuff. Jest mocks all `require`s by default. So anything that shouldn't ever be mocked should be in that config.

Typically that means react and enzyme should both be in there. (probably react-native also in a react native project).

https://facebook.github.io/jest/docs/api.html#unmockedmodulepathpatterns-array-string

**Comment by ssoliwal** [comment]
@blainekasten  i agree, but this is from the sample enzyme-jest project on github

I have had all of the added to the path, it doesnt help.

Any suggestions on how can we get verbose error logs

**Comment by Aweary** [comment]
@ssoliwal if you could put together a repo reproducing the issue that would be helpful, but it's from what I can see it seems like it's most likely a configuration issue with Jest.

**Comment by ljharb** [comment]
Airbnb now uses jest with enzyme 2 and 3. Happy to reopen this if there's something actionable.
