### ISSUE TITLE
finding by component does not work with switch case & shallow rendering

### ISSUE THREAD

**Issue by villesau** [airbnb/enzyme#353]
Below is the snippet of non-working test case. So if i have a par wrapped in anonymous function, i'm not able to find by component. If i give a component a className and try to find using it, the test works. I wouldn't want to give some custom class name for it just for tests. Also,  `expect(this.element.find('input').length).toEqual(1);` works like expected when testing the existence of input element.

``` javascript
import React from 'react';
import SomeComponent from 'SomeComponent';

const MyComponent = ({rule, onChange}) => (
  <div>
    <div>
      {(() => {
        switch (rule.rule) {
          case 'rule1':
            return <input type="text"
                          onChange={event => onChange(event)}/>;
          case 'rule2':
            return <SomeComponent className="forTests"/>;
        }
      })()}
    </div>
  </div>
);

MyComponent.displayName = 'MyComponent';
export default MyComponent;

```

the test case:

``` javascript
  import SomeComponent from 'SomeComponent';
  describe('when "rule2" is selected', function() {
    beforeEach(function() {
      const propsWithRule = {...props, rule: {rule: 'rule2'}};
      this.element = shallow(<MyComponent {...propsWithRule}/>);
    });

    it('shows SomeComponent', function() {
      expect(this.element.find(SomeComponent).length).toEqual(1); // length is 0, it should be 1
      expect(this.element.find('.forTests').length).toEqual(1); // works like expected, except prints a warning like below
    });
  });

  describe('when "rule1" is selected', function() {
    beforeEach(function() {
      const propsWithRule = {...props, rule: {rule: 'rule1'}};
      this.element = shallow(<MyComponent {...propsWithRule}/>);
    });

    it('shows input', function() {
      expect(this.element.find('input').length).toEqual(1); // works like expected
    });
  });
```

e: also getting following warning when testing non-working element:

'Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MyComponent`.'

The setup:
enzyme 2.2.0
react: 15.0.1
react-dom: 15.0.1
react-addons-test-utils: 15.0.1

**Comment by Aweary** [comment]
Can you add a default case to your `switch` statement that returns an empty `<div/>` or something and see if it's still failing?

**Comment by villesau** [comment]
No success with default and empty div as a default. It's never going to default state anyways. When i remove the switch case and return SomeComponent straight from the function, things work smoothly again, the warning is not shown and i can .find(SomeComponent) without a problems. Is there maybe some scoping problems with switch case?

It's also weird since this behaviour is only with this component, not when returning inputs around it. If it matters, SomeComponent is also stateless/functional component just like the MyComponent, except it's passed trough redux-connect higher order component.

**Comment by Aweary** [comment]
Looking at it again, I think the issue is that you're you're essentially returning a function when you're doing {() => {}}, which doesn't appear to work: https://jsfiddle.net/w04wxhyp/

Try doing something like:

```js

const MyComponent = ({rule, onChange}) => {
  let value = null;
  switch (rule.rule) {
  case 'rule1':
     value = <input type="text" onChange={event => onChange(event)}/>;
   case 'rule2':
      value =  <SomeComponent className="forTests"/>;
    }

  return (<div>
    <div>
      {value}
    </div>
  </div>);
};
```

**Comment by villesau** [comment]
@Aweary there is a small error in your jsfiddle: It should be wrapped into a immediately invoked function expression like this and it starts to work, like this: {(() => <h2>World</h2>)()}

**Comment by Aweary** [comment]
Ah I didn't see you were using an IIFE. Can you move the switch statement outside the return statement like above^ and see if it's still erroring? And if so, what's the value of `value` when it does fail?

**Comment by villesau** [comment]
the problem seems to persist :/

**Comment by villesau** [comment]
again removing the switch case and/or replacing it with if/elseif things start to work:

```javascript
const MyComponent = ({rule, onChange}) => {
  let value;
  if(rule.rule === 'rule1') {
    value = <input type="text" onChange={event => onChange(event)}/>;
  } else if (rule.rule === 'rule2') {
    value = <SomeComponent className="forTests"/>;
  }
  return (<div>
    <div>
      {value}
    </div>
  </div>);
};

```

**Comment by Aweary** [comment]
I wasn't able to reproduce the issue with a `switch` statement specifically:

```js
    it('should work with a switch statement', () => {
      const MyComponent = ({ name }) => {
        let foo = null;
        switch (name) {
          case 'test':
            foo = 'bar';
            break;
          case 'another-test':
            foo = 'baz';
            break;
          default:
            /* */
        }
        return (
          <div>
            <div>
              foo: {foo}
            </div>
          </div>
        );
      };

      shallow(<MyComponent name="test" />);
    });
```

This passed fine without any errors using the current master branch of `enzyme`. So I'm not sure what something similar would be it'd be failng for you. There shouldn't be any difference between a `switch` or an `if`/`else` statement determining the value, they're both just conditional logic.

There must be something else going on there.

**Comment by villesau** [comment]
Yeah, like i said it works fine with inputs (and apparently with strings too). What if you create a stateless component and try with it? The problem is only with SomeComponent in this case. Everything else works without errors. and with Somecomponent, things start to work if i change to if/else or assign it straight to value, or use it straight away. You can try with this (create SomeComponent.js):

```javascript
import React from 'react';
const SomeComponent = () => <div></div>;
SomeComponent.displayName = 'SomeComponent';
export default SomeComponent;
```

**Comment by Aweary** [comment]
I updated the test to use a stateless component and it still passes just fine for me:

```js
    it('should work with a switch statement', () => {
      const SomeComponent = ({ value }) => <div>{value}</div>;
      const MyComponent = ({ name }) => {
        let foo;
        switch (name) {
          case 'test':
            foo = <SomeComponent value={name} />;
            break;
          case 'another-test':
            foo = <SomeComponent value={name} />;
            break;
          default:
            /* */
        }
        return (
          <div>
            <div>
              foo: {foo}
            </div>
          </div>
        );
      };

      shallow(<MyComponent name="test" />);
      shallow(<MyComponent name="another-test" />);
    });
```

**Comment by villesau** [comment]
i'm starting to think this might be some issue with babel and how it transpiles my code. If babel does some magic on it's side with swtich cases (like wraps into function or something else more or less funky), could it mean that shallow renderer some how stops rendering some childs? I probably have to dig into the transpiled code and see how it looks (once i have figured out how).

**Comment by villesau** [comment]
@Aweary It's a bug in our transpiler, and the bug seems to appear only when running tests, the actual transpiling works fine.

here is a code snippet of the transpiled code:

```javascript
case _get__('RULES').rule1:
return _react2.default.createElement('input', {
    type: 'text', placeholder: 'myPlaceHolder',
    onChange: function (event) {
        return onChange(_extends({}, rule, { value: event.target.value }));
    } });

var _SomeComponent_Component = _get__('SomeComponent');

case _get__('RULES').rule2:
return _react2.default.createElement(_SomeComponent_Component, {
    selectedProductselectedSet: rule.value,
    select: function (id) {
        return onChange(_extends({}, rule, { value: id }));
    } });
```

var _SomeComponent_Component is defined before the case -_- I just have to figure out why this occurs only when testing and not in the actual build. So it's not a bug in Enzyme after all.

**Comment by ljharb** [comment]
@Aweary thanks for confirming!

**Comment by villesau** [comment]
if anyone is interested what was wrong, it was a bug with older version of babel-plugin-rewire: https://github.com/speedskater/babel-plugin-rewire/issues/92
