### ISSUE TITLE
Invariant Violation when trying to simulate an event on a pure, stateless component

### ISSUE THREAD

**Issue by pahund** [airbnb/enzyme#355]
When I try to simulate a click event on a React component that is pure and stateless, I get the following error:

```
Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID, ``.
    at invariant (/Users/pahund/node_modules/fbjs/lib/invariant.js:39:15)
    at traverseParentPath (/Users/pahund/node_modules/react/lib/ReactInstanceHandles.js:157:63)
    at Object.ReactInstanceHandles.traverseAncestors (/Users/pahund/node_modules/react/lib/ReactInstanceHandles.js:285:5)
    at findDeepestCachedAncestor (/Users/pahund/node_modules/react/lib/ReactMount.js:234:24)
    at Object.ReactMount.findComponentRoot (/Users/pahund/node_modules/react/lib/ReactMount.js:708:27)
    at Object.ReactMount.findReactNodeByID (/Users/pahund/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNodeFromInstance (/Users/pahund/node_modules/react/lib/ReactMount.js:180:32)
    at findDOMNode (/Users/pahund/node_modules/react/lib/findDOMNode.js:43:23)
    at ReactWrapper.<anonymous> (/Users/pahund/git/private-messages/node_modules/enzyme/build/ReactWrapper.js:538:66)
    at ReactWrapper.single (/Users/pahund/git/private-messages/node_modules/enzyme/build/ReactWrapper.js:1101:19)
```

See code example, which is a slight variation of the example for simulate from the Enzyme docs: https://gist.github.com/pahund/014c1c82b05ca3bc563e5ba25cfdb5ac

**Comment by pahund** [comment]
React 15.0.1
Enzyme 2.2.0
Mocha 2.4.5
Node 5.10.1

**Comment by Aweary** [comment]
I ran your test against the current master branch and it did not throw that error. It did fail, but that's because the `onClick` handler was not passed down to the `<button/>` in `<IncrementButton/>`. If I change it to:

```js
    function IncrementButton(props) {
      return <button onClick={props.onClick}>Increment</button>;
    }
```

This would be expected ([reproduced here](https://jsfiddle.net/xhtz3pdd/)).

**Comment by Aweary** [comment]
I ran your test against the current master branch and it did not throw that error. It did fail, but that's because the `onClick` handler was not passed down to the `<button/>` in `<IncrementButton/>`. If I change it to:

```js
    function IncrementButton(props) {
      return <button onClick={props.onClick}>Increment</button>;
    }
```

This would be expected ([reproduced here](https://jsfiddle.net/xhtz3pdd/)).

**Comment by pahund** [comment]
You're right, there was an mistake in the Ghist, missing onClick handler in <Button>. I updated it according to your last comment. I still get the same error when running that test, though, so the mistake was not causing the error.

**Comment by pahund** [comment]
I've created a repo on GitHub that should allow you to reproduce the issue: https://github.com/pahund/enzyme-bug-example

When I run npm test on it, I get the exact same "Invariant Violation" error.

**Comment by pahund** [comment]
Btw. thank you for helping me out! Enzyme is a really cool library, keep up the good work!

**Comment by Aweary** [comment]
Thanks for the repo @pahund, I cloned it and tried to reproduce the error but didn't have any luck.

After running `npm install` and `npm test` I get the error:

```
react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
```

Which is just because `react-dom` is missing from the `package.json` file. After adding it with `npm install --save-dev react-dom` and running `npm test` everything passed just fine:

<img width="336" alt="screen shot 2016-05-02 at 9 16 17 am" src="https://cloud.githubusercontent.com/assets/6886061/14956676/8f73ead8-1046-11e6-84e6-a02795c7f475.png">

I got the same results on both my machines.

**Comment by pahund** [comment]
That's it! I hadn't included react and react-dom in the dependencies for my project because I'm loading them from a CDN. The "invariant violation" error message misled me to think it had something to do with enzyme. Thank you very much for your help!

**Comment by Aweary** [comment]
@pahund glad to hear, no problem! 👍 🎉
