### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [airbnb/enzyme#358]
Hi, I'm going to host this lib on the [cdnjs](https://cdnjs.com).
I need to add npm auto-update config.
But I don't know which file is the main file.
Can you help me?

Thanks!

https://github.com/cdnjs/cdnjs/issues/7651

**Comment by Aweary** [comment]
You can see in the `package.json` folder that the `main` entry point path is `"build"` (implicitly `"build/index.js"`.

**Comment by x09326** [comment]
@Aweary 
I sent a pull request to cdnjs.
Thank you for your help.

https://github.com/cdnjs/cdnjs/pull/7772

**Comment by Aweary** [comment]
@x09326 happy to help, feel free to close this issue if you're good from here 😄
