### ISSUE TITLE
Document `index` in `forEach` callback

### ISSUE THREAD

**Issue by joshma** [airbnb/enzyme#366]
This seems obvious in hindsight, but I think it'd be nice for the docs on `forEach` to mention that the callback can take a second parameter `index`. Otherwise, even though I tested it and saw that `index` was being passed I'm not sure that it's a formally supported argument.

I'll send a PR if I get some time this weekend, but thought I'd just mention it in case this was a super quick fix for someone familiar with the documentation.

**Comment by Aweary** [comment]
@ljharb is there an actual bug here (see the bug label) or just a docs issue?

**Comment by ljharb** [comment]
It's a bug in the docs :-)

**Comment by nfcampos** [comment]
was fixed in #407
