### ISSUE TITLE
Proposal: wrapper.findClass() shorthand

### ISSUE THREAD

**Issue by joshhunt** [airbnb/enzyme#383]
We're using CSS Modules, and so we have an object of our classNames. When using these to seach for components with enzume, we have to add a dot at the beginning of these, and repeat this a lot.

```
output.find(`.${styles.fakeCheckbox}`)
output.find('.' + styles.fakeCheckbox)
slide.find(`.${styles.subHeading}`)
slide.find(`.${styles.subHeading}`)
slide.find(`.${styles.description}`)
slide.find(`.${styles.description}`)
wrapper.find(`.${styles.itemLink}`)
wrapper.find(`.${styles.item}`)
dropdownComponent.find(`.${styles.label}`)
dropdownComponent.find(`.${styles.label}`)
dropdownComponent.find(`.${styles.menu}`)
dropdownComponent.find(`.${styles.label}`)
dropdownComponent.find(`.${styles.label}`)
output.find(`.${stylesStub.main}`)
output.find(`.${stylesStub.sidebar}`)
output.find(`.${stylesStub.header}`)
output.find(`.${stylesStub.header}`)
navComponent.find(`.${stylesStub.prevLinkWrapper}`)
navComponent.find(`.${stylesStub.prevLinkWrapper}`)
navComponent.find(`.${stylesStub.nextLinkWrapper}`)
navComponent.find(`.${stylesStub.nextLinkWrapper}`)
output.find(`.${messageStyles.title}`)
output.find(`.${messageStyles.subtitle}`)
component.find(`.${styles.checkbox}`)
component.find(`.${styles.sidebar}`)
component.find(`.${styles.scrollContent}`)
extrasContent.find(`.${stylesStub.innerWrapper}`)
wrapper.find(`.${mockStyles.subtitle}`)
```

What we would like to do is add a method to both ShallowWrapper and ReactWrapper called `.findClass()` where we can pass in just the class name, without the dot at the beginning. So like `wrapper.findClass(styles.header)`.

Thoughts? I'm willing to work on a PR, but wanted to get feedback on the idea first.

**Comment by Aweary** [comment]
You should be able to do `wrapper.find({className: styles.header})`.

**Comment by Aweary** [comment]
@joshhunt also note that you can always extend `ReactWrapper` or `ShallowWrapper` for `mount` and `shallow` respectively

```js
import { ShallowWrapper } from 'enzyme';
ShallowWrapper.prototype.findClass = function (className) { 
  return ShallowWrapper.find(`.${className}`)
};
```

**Comment by Aweary** [comment]
@joshhunt I'm going to close this since there are existing options that cover this use case, and I think those options are easy enough that they don't warrant a new API method. Feel free to continue discussing the topic here and we can always revisit the idea if we see it as a viable option 👍

**Comment by joshhunt** [comment]
Completely happy with this :)
