### ISSUE TITLE
ReactWrapper.unmount() throws Cannot render markup in a worker thread.

### ISSUE THREAD

**Issue by tleunen** [airbnb/enzyme#395]
For some reasons, when I call `unmount` on a react wrapper node, React throws an error saying I don't have a DOM.

jsdom is initialized, before importing React and enzyme, but I still get this error on unmount.

I even checked if the dom was really initialized properly, with the same check React does, and it's evaluated as `true` so everything looks ok.
```
!!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
)
```

Any idea what could be the problem?

**Comment by Aweary** [comment]
Can you share the code for the test that is throwing this error? Thanks!

**Comment by tleunen** [comment]
I tried to find the root cause of this and I think I found it.
ES6 imports were used in the setup file for jsdom, and inside it React was imported as well and it seems that it was causing the issue.
Not sure why es6 imports were used in this file instead of commonjs :) I'm surprised it even worked before with es6 imports. The file is probably also run with the babel compilers, but then it seems there's an issue with React.

Anyway, problem solved when modifying in simple commonjs require.

**Comment by Aweary** [comment]
Thanks for the update @tleunen!

**Comment by tomkis1** [comment]
@tleunen Can you elaborate on this? I don't understand what was the fix.

Anyway, having the same issue basically, calling `unount` on componet throws this invariant.


```javascript
it('doesnt work', () => {
  const dispatchSpy = spy();
  const globalDispatchSpy = spy(mockStore, 'dispatch');
  const WrappedView = dfView(syncMockFetch, MOCK_SCHEMA, MockView);

  const cmp = mount(
    <WrappedView
      model={{}}
      store={mockStore}
      dispatch={dispatchSpy}
    />
  );

  cmp.unmount();
});
```

Of course neither `document` nor `window` is empty (using jsdom).

**Comment by tleunen** [comment]
I had `import X from 'Y'` in the jsdom setup file and after replacing it with `const X = require('Y')`,  everything worked

**Comment by tomkis1** [comment]
that's weird
1) I don't see how these two are different
2) Doesn't work for me anyway...

**Comment by Aweary** [comment]
@tomkis1 can you share a small example reproducing your issue (including the content of the mounted component)? I'm in Paris for ReactEurope this week but I can look at this when I get back if no one else does.

**Comment by tomkis1** [comment]
```javascript
import React from 'react';
import jsdom from 'jsdom';
import { mount } from 'enzyme';

const doc = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.document = doc;
global.window = doc.defaultView;

describe('foo', () => {
  it('works', () => {
    mount(<div>Foo Bar</div>);
  });

  it('doesnt work', () => {
    const mounted = mount(<div>Foo Bar</div>);
    mounted.unmount();
  });
});
```

**Comment by matheusrocha89** [comment]
Somebody found a solution for this problem?

**Comment by tomkis1** [comment]
Yes, @matthewgertner found a workaround. Can you please elaborate?

**Comment by matheusrocha89** [comment]
I am having the same problem you had @tomkis1 , when I try to unmount the component I receive the same error message about the `Invariant Violation`

**Comment by nfcampos** [comment]
Sorry about the delay in posting a solution, here goes:
- `react-dom` needs `navigator` to be a global (`enzyme` imports `react-dom`)
- both `react` and `enzyme` imports need to happen after the globals are attached (so they need to be `require` calls, because `import`s happen before anything else irrespective of where they appear in the file
```js
import jsdom from 'jsdom';

const doc = jsdom.jsdom('');
global.document = doc;
global.window = doc.defaultView;
global.navigator = {
  userAgent: 'node.js',
}

const React = require('react')
const mount = require('enzyme').mount

describe('foo', () => {
  it('works', () => {
    mount(<div>Foo Bar</div>);
  });

  it('doesnt work', () => {
    const mounted = mount(<div>Foo Bar</div>);
    mounted.unmount();
  });
});
```

**Comment by matheusrocha89** [comment]
@nfcampos The `import` happens even before the configs I put on `setup.js` when I run the tests?

**Comment by nfcampos** [comment]
it's something like this:
```js
import React from 'react'
console.log('hey')
import jsdom from 'jsdom'
console.log('boo')
```
1. `react` is imported
2. `jsdom` is imported
3. `hey` is logged
4. `boo` is logged
So all imports run in the order you wrote them, but they all run before anything else in this file.

as for `setup.js`, are you talking about running `mocha --require setup.js test.js`? if yes, then anything in `setup.js` will run before anything in `test.js` (which is why we recommend `jsdom` setup happens in a separate file, to avoid these situations

**Comment by matheusrocha89** [comment]
That's my scenario, I put the jsdom config on `setup.js` and just import the `mount` and `React` on the test files. So I don't know why still happens.

**Comment by tp** [comment]
Running into the same issue with TypeScript transpiled files, that make it hard to require/order the imports. Is there any other known workaround? Really surprised this only happens when unmounting, since everything else works fine.

**Comment by kentcdodds** [comment]
I figured out what my issue was:

Here's my `setup-test-env.js` file now:

```javascript
/**
 * This is used to set up the environment that's needed for most

 * of the unit tests for the project which includes polyfilling,
 * chai setup, and initializing the DOM with jsdom
 */
import 'babel-polyfill'
import chai from 'chai'
import sinonChai from 'sinon-chai'
import {jsdom} from 'jsdom'

chai.use(sinonChai)

global.document = jsdom('<body></body>')
global.window = document.defaultView
global.navigator = window.navigator
global.expect = chai.expect

// this has to happen after the globals are set up because `chai-enzyme`
// will require `enzyme`, which requires `react`, which ultimately
// requires `fbjs/lib/ExecutionEnvironment` which (at require time) will
// attempt to determine the current environment (this is where it checks
// for whether the globals are present). Hence, the globals need to be
// initialized before requiring `chai-enzyme`.
chai.use(require('chai-enzyme')())
```

**Comment by j-funk** [comment]
I don't think this issue should be closed.

**Comment by butlermd** [comment]
I agree with @j-funk, something appears to be wrong here. If nothing else, this seems like it ought to be addressed within the documentation?

**Comment by jackbrown** [comment]
In addition to @kentcdodds fixes, I managed to fix this issue by changing the order of my `test-setup.js` to the following:

```
/**
 * This is used to set up the environment that's needed for most
 * of the unit tests for the project which includes polyfilling,
 * chai setup, and initializing the DOM with jsdom
 */
import 'babel-polyfill'
import chai from 'chai'
import sinonChai from 'sinon-chai'
import {jsdom} from 'jsdom'

chai.use(sinonChai)

global.document = jsdom('<body></body>')
global.window = document.defaultView
global.navigator = window.navigator
global.expect = chai.expect

// this has to go after the window, document and navigator are set up
global.React = require('React');
global.TestUtils = require('react-addons-test-utils');

// this has to happen after the globals are set up because `chai-enzyme`
// will require `enzyme`, which requires `react`, which ultimately
// requires `fbjs/lib/ExecutionEnvironment` which (at require time) will
// attempt to determine the current environment (this is where it checks
// for whether the globals are present). Hence, the globals need to be
// initialized before requiring `chai-enzyme`.
chai.use(require('chai-enzyme')())
```

**Comment by peter-mouland** [comment]
thanks @jackbrown . the last point was essential for it to work for me

**Comment by nabati** [comment]
To possibly help future debuggers. 

The equivalent of the line below should also be placed after jsdom.
`const Adapter = require('enzyme-adapter-react-15');`
