### ISSUE TITLE
Documentation ambiguous about what .props are.

### ISSUE THREAD

**Issue by bcowgill** [airbnb/enzyme#397]
wrapper.state() returns the this.state from your component so logically one assumes that wrapper.props() returns the this.props from your component, but no it returns the HTML element properties from the root element.
You obtain the this.props from wrapper.instance().props

Confusing and should be pointed out in the documentation.

**Comment by blainekasten** [comment]
Would gladly accept a PR!

**Comment by Moezalez** [comment]
this also suggests it would be the passed props:
http://airbnb.io/enzyme/docs/api/ShallowWrapper/props.html

**Comment by christiansakai** [comment]
Got mislead today also by http://airbnb.io/enzyme/docs/api/ShallowWrapper/props.html until I saw this issue.
