### ISSUE TITLE
text(), html() not working on mounted SFC

### ISSUE THREAD

**Issue by Andarist** [airbnb/enzyme#401]
Such methods as `text`, `html`, `render` are not working on mounted SFC (or at least that is my conclusion for now). 

It gives me an error of:
```
Element appears to be neither ReactComponent nor DOMNode (keys: _currentElement,_rootNodeID,_instance,_nativeParent,_nativeContainerInfo,_pendingElement,_pendingStateQueue,_pendingReplaceState,_pendingForceUpdate,_renderedNodeType,_renderedComponent,_context,_mountOrder,_topLevelWrapper,_pendingCallbacks,_calledComponentWillUnmount,_mountIndex,_mountImage,_isOwnerNecessary,_warnedAboutRefsInRender)
```

Scenario I'm using:

`const SFC = ({ text }) => <HOC>{ text }</HOC>`

```
const component = mount(<SFC text='test' />)
component.text().includes('test')
```

**Comment by Aweary** [comment]
Hey @Andarist what version of enzyme are you using? I'm betting you're on 2.2.0 or lower, as 2.3.0 fixed an issue where stateless components returned no instances (https://github.com/airbnb/enzyme/pull/359). See here for a passing test case:  [Aweary/enzyme-test-repo/blob/issue-#401/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-%23401/test.js)

If you're using the latest version of enzyme it might be the HOC you're returning.

**Comment by Andarist** [comment]
Hey,
It seems you were right about me having older version of enzyme, however I've updated it before and somehow (maybe cause of not updated shrinkwrap) landed back on the older one. Sorry for troubling.
