### ISSUE TITLE
Get node by className when svg inluded in a mounted component

### ISSUE THREAD

**Issue by OttlikG** [airbnb/enzyme#409]
This code snippet throw the following error:
undefined is not a function (evaluating 'classes.replace(/\s/g, ' ')')
instHasClassName@enzyme/build/MountedTraversal.js:73:0

```javascript
function TestSVG () {
  let useTag = '<use xlink:href="/path/to/svg/symbol.svg" />';

  return (
    <div className='svg'>
      <svg aria-hidden='true' className='test-svg' dangerouslySetInnerHTML={{__html: useTag }}/>
    </div>
  )
}

let _wrapper = mount(<TestSVG />)
expect(_wrapper.find('.svg').length).to.equal(1)
```

I can get over of it when I extended the instHasClassName function with the following:
```javascript
var classes = (0, _reactCompat.findDOMNode)(inst).className || '';
console.log('classes', classes)

if(Object.prototype.toString.call( classes ) === '[object SVGAnimatedString]' && classes.hasOwnProperty('baseVal')) {
  classes = classes.baseVal
}
```

The console log printed out these:
LOG: 'classes', 'svg'
LOG: 'classes', Object{baseVal: 'test-svg', animVal: 'test-svg'}

**Comment by Aweary** [comment]
Hey @OttlikG thanks for the issue. This is a known issue. Our tests run in jsdom which doesn't support SVGs so SVG support was never addressed. You can follow https://github.com/airbnb/enzyme/issues/375 for any updates.
