### ISSUE TITLE
TypeError: Cannot read property 'reverse' of null

### ISSUE THREAD

**Issue by vlkosinov** [airbnb/enzyme#410]
Thank you very much for this library! ❤️ 

I'm trying to test a library which provides some Higher-order Component, but I get a weird bug.
#### Example:

**Enhancer:**

``` js
function enhance(ComposedComponent) {
    class Enhancer extends Component {
        render() {
            const newProps = Object.assign({}, this.props, {
                someAdditionalProp: true    
            });
            return createElement(WrappedComponent, newProps);
        }
    }

    return Enhancer;
}
```

**Component to enchace:**

``` js
class Foo extends Component {
    render() {
        return (<div>Bla bla</div>);
    }
}
const FooEnhanced = enhance(Foo);
```

**Main component:**

``` js
class App extends React.Component {
    render() {
        return (
            <div>
                <FooEnhanced />
            </div>
        );
    }
}
```

I want to ensure that the Enhancer adds additional prop 'someAdditionalProp' to composed components, so I'm doing the following:

``` js
const wrapper = mount(<App />);
const enhancedComponents = wrapper
    .find(App)
    .children()
    .findWhere(n => typeof n.type() !== 'string')
    .findWhere(n => n.parent().is(FooEnhanced));

enhancedComponents.forEach(node => {
    expect(node.prop('someAdditionalProp')).to.be.a('boolean');
});
```

And get error message:

``` bash
/Users/vladkosinov/projects/test/node_modules/enzyme/build/MountedTraversal.js:199
  return pathToNode(inst, root).reverse();
                               ^

TypeError: Cannot read property 'reverse' of null
    at parentsOfInst (/Users/vladkosinov/projects/test/node_modules/enzyme/build/MountedTraversal.js:199:32)
    at ReactWrapper.<anonymous> (/Users/vladkosinov/projects/test/node_modules/enzyme/build/ReactWrapper.js:841:54)
    at ReactWrapper.single (/Users/vladkosinov/projects/test/node_modules/enzyme/build/ReactWrapper.js:1297:19)
    at ReactWrapper.parents (/Users/vladkosinov/projects/test/node_modules/enzyme/build/ReactWrapper.js:840:41)
    at ReactWrapper.<anonymous> (/Users/vladkosinov/projects/test/node_modules/enzyme/build/ReactWrapper.js:860:21)
    at /Users/vladkosinov/projects/test/node_modules/enzyme/build/ReactWrapper.js:1166:21
    at Array.map (native)
    at ReactWrap%
```

Essentially, the error occurs when we attempt to call the `parent` method on ReactWrapper around `Foo`:

``` js
const wrapper = mount(<App />);
const foo = wrapper.find(Foo).parent()
```

Any ideas on how to solve this problem? 😊

**Comment by Aweary** [comment]
Hey @vlkosinov thanks so much for the issue report. This does indeed seem to be a bug in enzyme. I was able to create a simple repro case you can see here: 

https://github.com/Aweary/enzyme-test-repo/blob/issue-410/test.js

```js

class App extends React.Component {
  render() {
    return (
      <div>Hello, world</div>
    );
  }
}

/**
 * Change the `describe` and `it` block so it acurately describes
 * the test that you are trying to reproduce.
 */

describe('Repro case for issue #401', () => {
  it('shouldnt throw when calling parent() in findWhere()', () => {
    const wrapper = mount(<App/>);
    wrapper.findWhere(n => n.parent())
  });
```

The issue appears to be calling `parent` on a node returned from `findWhere`. I'll take a look at this today.

**Comment by Aweary** [comment]
I think either `pathToNode` is returning null when it shouldn't or `parent` should have a null check. @lelandrichardson what do you think?

**Comment by jguillen1984** [comment]
Just a heads up this issue still persists, I just ran into this issue myself on "enzyme": "2.4.1"

**Comment by just-boris** [comment]
Currently, I could reproduce the problem with simplest code example: see #769.

Also, I tried to fix it but didn't succeed, because there is something wrong with `MountedTraversal.childrenOfInst` function, but is seemed to me very hard to fix it, without breaking a lot of user calls for this function.

**Comment by nbkhope** [comment]
I just ran into this problem. Does anybody know a good solution?

**Comment by nbkhope** [comment]
So I figured it out. The issue was that I used **mount** to render the component and it had a nested component whose props were required but I did not provide them. So in the end, that component was never properly set up there. So make sure all nested components are passed the right props in order to be properly rendered.

**Comment by yashnerella** [comment]
Did anyone get a solution for this? Is there a temporary workaround for this?

**Comment by ljharb** [comment]
The tests are in #769; I'm not aware of a fix yet.

**Comment by yashnerella** [comment]
okay, I will check it out

**Comment by fisx** [comment]
Is this related to #534?  (Not sure, but even if it's clearly not, it may be worth pointing that out.)

**Comment by AlisonWoodman** [comment]
👍

**Comment by ljharb** [comment]
@vlkosinov is this still an issue in enzyme 3?

**Comment by timrsmith** [comment]
It appears to be. I'm seeing it in 3.2.0

**Comment by nbkhope** [comment]
Is this somehow related to gettting the parent() of a parent()?

Previously my enzyme v2 tests succeeded, but now doing:
```
wrapper.find('SomeComponent').parent().parent()
```
gives out the error:

```
TypeError: Cannot read property 'reverse' of null

      at parentsOfNode (node_modules/enzyme/build/RSTTraversal.js:134:32)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:1087:50)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1620:25)
      at ShallowWrapper.parents (node_modules/enzyme/build/ShallowWrapper.js:1086:41)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:1106:21)
      at node_modules/enzyme/build/ShallowWrapper.js:1468:21
      at Array.map (native)
      at ShallowWrapper.flatMap (node_modules/enzyme/build/ShallowWrapper.js:1467:45)
      at ShallowWrapper.parent (node_modules/enzyme/build/ShallowWrapper.js:1105:21)
      at Object.<anonymous> (someTestFile.test.js:462:60)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by jamespfarrell** [comment]
For me the easiest work around is to select the parent, and find() within that, rather than going to the node and looking for the parent.
