### ISSUE TITLE
.find selector fails when searched attribute contains space

### ISSUE THREAD

**Issue by rifeljm** [airbnb/enzyme#416]
If my React component contains &lt;div someAttribute="One two"&gt;

This works: 
- document.querySelector('[someAttribute="One two"]')
- cheerio.find('[someAttribute="One two"]')

This doesn't work: enzyme.mount(myComponent).find('[someAttribute="One two"]')

**Comment by Aweary** [comment]
Hey @rifeljm, thanks for the issue. I was able to reproduce this, you can see the failing test case here: [Aweary/enzyme-test-repo/blob/issue-416/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-416/test.js).


We'll look into this when we get a chance, or feel free to submit a PR if you'd like 😄

**Comment by Aweary** [comment]
We can close this now thanks to https://github.com/airbnb/enzyme/pull/427, thanks again @rifeljm! 😄
