### ISSUE TITLE
Can't use `mount` with Chimp

### ISSUE THREAD

**Issue by Moezalez** [airbnb/enzyme#417]
Trying to run the full dom rendering example gives me:

`Uncaught Error: It looks like you called `mount()` without a global document being loaded.`.

I run tests with [Chimp](https://github.com/xolvio/chimp), which runs the test in Chrome. So the document should be loaded, right?

```
import React from 'react';
import { mount } from 'enzyme';
import sinon from 'sinon';

const Foo = (props) => (
  <button onClick={props.onButtonClick}>Foo</button>
)

const MyComponent = (props) => (
  <div>
    <Foo className="icon-star" />
    <Foo />
    <Foo />
    {props.children}
  </div>
)

describe.only('<Foo />', () => {

  it('allows us to set props', () => {
    const wrapper = mount(<Foo bar="baz" />);
    expect(wrapper.props().bar).to.equal("bad");
    wrapper.setProps({ bar: "foo" });
    expect(wrapper.props().bar).to.equal("foo");
  });

  it('simulates click events', () => {
    const onButtonClick = sinon.spy();
    const wrapper = mount(
      <Foo onButtonClick={onButtonClick} />
    );
    wrapper.find('button').simulate('click');
    expect(onButtonClick.calledOnce).to.equal(true);
  });

  it('calls componentDidMount', () => {
    sinon.spy(Foo.prototype, 'componentDidMount');
    const wrapper = mount(<Foo />);
    expect(Foo.prototype.componentDidMount.calledOnce).to.be.true;
    Foo.prototype.componentDidMount.restore();
  });

});
```

**Comment by Aweary** [comment]
Thanks for the issue @Moezalez! If you `console.log` out `global.window` and `global.document` what do you get? Also, can you log out `window` and `document` as well?

**Comment by ljharb** [comment]
@Moezalez You should be using browserify to run things in a browser environment, which converts `global` to `window` for you.

**Comment by Moezalez** [comment]
@Aweary 
`global.window`: `undefined`
`global.document`: `undefined`
`window`: `ReferenceError`
`document`: `ReferenceError`

So this might actually be an (config) issue with chimp.

**Comment by Aweary** [comment]
Interesting, I'm not at all familiar with chimp so I can't comment on what might be going on there, but it does seem like enzyme is working as expected so far.

@ljharb on the topic, should we have some documentation on using enzyme in a browser environment? I don't think we explicitly say anywhere that we have a hard dependency on the `global` object in node? Might be worth documenting or reconsidering if people are using alternatives other than browserify for browser testing.

**Comment by ljharb** [comment]
It's an npm package - the default is that all of them require `browserify` (or webpack, etc - ie, a module system) to be used in a browser.

We can certainly document it in the readme, but this shouldn't be surprising to anybody.

**Comment by samhatoum** [comment]
Hello, I'll chime in on this as the author of Chimp :)

Chimp is an acceptance/integration/e2e testing framework. It runs in a node context (so no browsers) and gives you a client object which you can use to control a Selenium browser with (using [webdriver.io](http://webdriver.io))

Enzyme is not really applicable in this context hence the issues you're facing above. 

There may be an opportunity for integration around creating PageObjects from React components using Enzyme, but that's another issue for another day :)

If you need any Chimp help or want to brainstorm some integration ideas, please feel free to join our [xolv.io/community](http://xolv.io/community) slack channel.

**Comment by Aweary** [comment]
Thanks @samhatoum for chiming it, much appreciated. I'm going to close this issue @Moezalez as there's nothing actionable here for enzyme, but if anything changes that indiciates an enzyme problem let us know 👍
