### ISSUE TITLE
find broken in 2.3.0?

### ISSUE THREAD

**Issue by RobinClowers** [airbnb/enzyme#418]
In version 2.2.0, this code works find:

```javascript
    component = mount(
      <MyComponent.WrappedComponent {..props} />
    )

    component.find('.some-css-class')
```

With 2.3.0, I get `undefined is not a constructor (evaluating 'classes.replace(/\s/g, ' ')')`.

**Comment by Aweary** [comment]
Hey @RobinClowers thanks for the issue. Can you share a little more about what your testing setup is? It seems strange to me that it's trying to evaluate that `replace` call as a constructor.

**Comment by RobinClowers** [comment]
Thanks for the quick response. I don't have time to build a repro right now, but here are some more details. We are building with webpack and running tests through karma, and we are using `react-addons-test-utils` directly for some tests as well as `react-shallow-testutils` for other tests. This particular case is just using enzyme's `mount` and `find`. Here is the stack trace:

```
MyComponent test FAILED
  undefined is not a constructor (evaluating 'classes.replace(/\s/g, ' ')')
  instHasClassName@/Users/robin/src/my-project/client/specs/index.js:15547:29 <- webpack:///~/enzyme/build/MountedTraversal.js:69:0
  /Users/robin/src/my-project/client/specs/index.js:15702:37 <- webpack:///~/enzyme/build/MountedTraversal.js:224:0
  findAllInRenderedTreeInternal@/Users/robin/src/my-project/client/specs/index.js:15760:18 <- webpack:///~/enzyme/build/MountedTraversal.js:282:0
  findAllInRenderedTreeInternal@/Users/robin/src/my-project/client/specs/index.js:15775:52 <- webpack:///~/enzyme/build/MountedTraversal.js:297:0
  findAllInRenderedTreeInternal@/Users/robin/src/my-project/client/specs/index.js:15772:54 <- webpack:///~/enzyme/build/MountedTraversal.js:294:0
  findAllInRenderedTreeInternal@/Users/robin/src/my-project/client/specs/index.js:15772:54 <- webpack:///~/enzyme/build/MountedTraversal.js:294:0
  findAllInRenderedTreeInternal@/Users/robin/src/my-project/client/specs/index.js:15775:52 <- webpack:///~/enzyme/build/MountedTraversal.js:297:0
  treeFilter@/Users/robin/src/my-project/client/specs/index.js:15785:40 <- webpack:///~/enzyme/build/MountedTraversal.js:307:0
  /Users/robin/src/my-project/client/specs/index.js:7580:19 <- webpack:///~/enzyme/build/ReactWrapper.js:62:0
  /Users/robin/src/my-project/client/specs/index.js:8684:26 <- webpack:///~/enzyme/build/ReactWrapper.js:1166:0
  map@[native code]
  flatMap@/Users/robin/src/my-project/client/specs/index.js:8683:36 <- webpack:///~/enzyme/build/ReactWrapper.js:1165:0
  findWhereUnwrapped@/Users/robin/src/my-project/client/specs/index.js:7579:26 <- webpack:///~/enzyme/build/ReactWrapper.js:61:0
  recurseSelector@/Users/robin/src/my-project/client/specs/index.js:12458:56 <- webpack:///~/enzyme/build/ComplexSelector.js:55:0
  handleSelectors@/Users/robin/src/my-project/client/specs/index.js:12520:38 <- webpack:///~/enzyme/build/ComplexSelector.js:117:0
  find@/Users/robin/src/my-project/client/specs/index.js:12536:39 <- webpack:///~/enzyme/build/ComplexSelector.js:133:0
  find@/Users/robin/src/my-project/client/specs/index.js:8037:42 <- webpack:///~/enzyme/build/ReactWrapper.js:519:0
  /Users/robin/src/my-project/client/specs/index.js:134333:47 <- webpack:///specs/components/Summary.spec.js:126:0
```

**Comment by RobinClowers** [comment]
If none of that helps, I can try to find time this weekend to build a repro.

**Comment by Aweary** [comment]
Does your component have any SVGs by chance? If not this seems likely to be an issue with using enzyme with webpack.

**Comment by RobinClowers** [comment]
We do, in fact, have an svg icon in this test! Is there some secret to making that work?

**Comment by Aweary** [comment]
This makes sense then! This is a known issue.

Check out https://github.com/airbnb/enzyme/issues/375, enzyme doesn't currently support SVG class name queries. The SVG `classname` prop returns an object unlike regular elements, and in <2.2.0 this failed silently.

We don't currently have any tests setup on enzyme to test in actual browser environments, and jsdom doesn't support SVGs, so it slipped through the cracks for a while. We'll need to start testing in browsers before we can confidently introduce support, but I'll update https://github.com/airbnb/enzyme/issues/375 whenever progress is made on that front.

**Comment by RobinClowers** [comment]
Cool, again, thanks for the quick response! Just for my own edification, is there any way to work around the issue in 2.3?

**Comment by Aweary** [comment]
Unfortunately I can't think of anyway to avoid this in 2.3.0. It uses `findDOMNode(...).className` so you'd have to somehow overwrite that to return a string instead of an object for SVGs. You might want to stick with 2.2.0 for now.

**Comment by RobinClowers** [comment]
Yeah, that's my plan, I was just curious. 👍

**Comment by interactivellama** [comment]
Having same problem with components that use SVGs (and that's most of them in our UI library). Downgrading to 2.2.0 is a temporary fix.

**Comment by osmola** [comment]
Thanks for pointing to SVGs inside the component! I have the same issue.
Wonder if it has been fixed?
