### ISSUE TITLE
Projectname

### ISSUE THREAD

**Issue by hkjels** [airbnb/enzyme#43]
This can be confused with the ClojureScript view-layer over React called Reagent. It should be mentioned in the Readme.

**Comment by ljharb** [comment]
The tagline is "JavaScript Testing utilities for React" - is that not sufficient?

Is there a corresponding issue filed on the ClojureScript project to mention this project in the readme?

**Comment by hkjels** [comment]
It might, I am not the author, but if I was I would have liked a mention. Note that [Reagent](http://reagent-project.github.io) was developed before this project.

**Comment by Kauko** [comment]
I think it would be worthwhile coming up with a different name. Reagent is very established in the Clojure(Script) community, and there's a lot of overlap between the JS and CLJS communities.

Not sure exactly how old the clojurescript Reagent project is, but there's commits from at least 2013.

**Comment by mike-thompson-day8** [comment]
For many people, Javascript and Clojurescript are in the same space.

Look, we know it is a pain to rename, but really you should.  There's just too much overlap here. And this project is about two years too late to the name.

**Comment by alexkalderimis** [comment]
This is particularly important since both projects are in the React ecosystem (hence the name choices obviously). Confusion is inevitable. https://github.com/reagent-project/reagent clearly has priority.

**Comment by gadfly361** [comment]
+1 on renaming

**Comment by emil0r** [comment]
Agreed. Should be renamed.

**Comment by borkdude** [comment]
+1 on renaming

**Comment by danielcompton** [comment]
Think about this if the shoe was on the other foot. Imagine this library was open source for two years and then Google released an open source project focused on React also called Reagent. You'd probably feel pretty ticked off (I know I would).

**Comment by sanatgersappa** [comment]
+1 on renaming

**Comment by daslu** [comment]
+1 on renaming

**Comment by pepe** [comment]
+1 rename

**Comment by thenonameguy** [comment]
+1 rename

**Comment by Gregg8** [comment]
+1 for renaming. This is definitely going to cause confusion, being in such a similar space. 

This Reagent's first commit was Aug 2015. The original Reagent has been going since December 2013 and is very well established.

**Comment by nidu** [comment]
+1 rename

**Comment by mateusz-fiolka** [comment]
+1 on rename

**Comment by brendonrapp** [comment]
Both of these libraries relate to the React ecosystem. There's no reason this library should use a name that's already taken by something else within the same general sphere. It's not a good thing for anybody.

**Comment by wvdlaan** [comment]
+1 on rename

**Comment by skovsgaard** [comment]
Renaming would avoid the awkward PR situation Groupon ended in when they stole a GNOME project name and refused to acknowledge the conflict; it'd just be so much easier to change the name.

**Comment by hipitihop** [comment]
+1 for rename. You gain nothing from re-using the name in a related space 2 years after the fact, while both the existing and future communities for both projects will lose with confusion while looking up references

**Comment by vibel** [comment]
If you keep this name:
- You would harm the very community you're intending to contribute to: React. (That it's in JS or a compiled-to-JS language is irrelevant here, they're totally interoperable.)
- You would harm your project in two ways: 1) It would be harder to Google, which is critical for a new project 2) You would not show that you're ready to play nice with the community, which is also critical for a new project in a FOSS community.
- Ironically, you would end up with a name that is not that good: the word "reagent" will in itself always be difficult to Google because it is a very common word in chemistry, especially when associated with "react".

In FOSS communities, we don't privatize words by putting a trademark on them and suing anybody that uses it for something else in the same space (like you would for 'Airbnb'). We count on people's good judgement to respect the name of other projects and sub-communities within the community.

**Comment by martinklepsch** [comment]
:+1: on renaming

**Comment by sharnik** [comment]
Rename, please. Not cool, bro.

**Comment by darwin** [comment]
:name_badge: rename, please

**Comment by julianjelfs** [comment]
You should absolutely rename and you should not have made such a dumb mistake in the first place.

**Comment by martinklepsch** [comment]
@julianjelfs please watch your tone. While this is unfortunate there is no need to attack people. Thank you :+1:

**Comment by px0** [comment]
+1 rename please

**Comment by mccraigmccraig** [comment]
+1 rename plz

**Comment by abnaod** [comment]
rename please

**Comment by olecve** [comment]
+1 rename

**Comment by bsteuber** [comment]
Rename plz

**Comment by csummers** [comment]
+1 rename

**Comment by rwaguy** [comment]
It would be a good idea to rename this project.  Using the same name will confuse Clojure, Airbnb, and React users.  While Airbnb may not feel this is a significant issue, you may want to consider that the programmers and companies who depend upon Clojure/Reagent may be among your clientele and investors, as well.

A partial list of those is here:  http://clojure.org/Companies

**Comment by domgetter** [comment]
@martinklepsch Claiming that someone made a mistake is not an "attack".  There is no need for you to claim false things here. Thank you.

**Comment by munk** [comment]
Please rename

**Comment by sickill** [comment]
Yes, please rename this project.

**Comment by zamaterian** [comment]
Please Rename!

**Comment by Kauko** [comment]
@domgetter the message he's replying to had a different tone before it was edited. Nothing terrible, but definitely more constructive now.

**Comment by dialelo** [comment]
:+1: rename it, please.

**Comment by DavidYKay** [comment]
Big user of the other Reagent, so I am a bit biased, but I think it'd be best for both the Clojurescript and Javascript programmers to keep the names separate. Please consider renaming. Thanks!

**Comment by fromheten** [comment]
:+1: for renaming. Great stuff otherwise :)

**Comment by jstewart** [comment]
There's already one very popular react library named "reagent". What the host language is should have no bearing as both use React, and this WILL cause confusion if you don't.

**Comment by cjohansen** [comment]
Seriously, can't you even be bothered to google a name before choosing it? It would've taken all of 10 seconds to figure out this name is already being used for something very similar (a React-related OSS project).

**Comment by escherize** [comment]
:+1: On the renaming.  I was excited, thinking this was for testing reagent views...

**Comment by mcramm** [comment]
+1 on renaming.

**Comment by kangsy** [comment]
+1 rename

**Comment by pietu** [comment]
+1 rename

**Comment by yogthos** [comment]
+1 rename

**Comment by niquola** [comment]
:+1:  rename

**Comment by glorphindale** [comment]
+1 rename

**Comment by obarbeau** [comment]
+1 rename

**Comment by badenkov** [comment]
+1 rename

**Comment by donmullen** [comment]
+ 1 rename - Not doing so hurts your project as mentioned above.

**Comment by jelz** [comment]
+1 rename

**Comment by statonjr** [comment]
+1 rename

**Comment by cybem** [comment]
+1 rename

**Comment by ikitommi** [comment]
+1 on rename.

**Comment by skrat** [comment]
You, you copycats! Much lame, MUST rename

**Comment by jcoyne** [comment]
Please pick a unique name that makes it easy to google your docs without getting hits for different products that are very similar.

**Comment by john2x** [comment]
I agree, too much overlap. +1 for renaming

**Comment by vibl** [comment]
I think a lot of people would be willing to help you with the renaming: if you announce another name and you ask for help, PRs with the new name replaced everywhere in the code and documentation would probably save you most of the grunt work.

Granted, the main hassles of a renaming generally is in the legacy code and docs, in changing internal habits and in public relations. But it can be done! (and the alternative would create even more hassles in the medium and long terms).

**Comment by niwinz** [comment]
+1 for renaming...

**Comment by comprehendreality** [comment]
+1 rename

**Comment by maacl** [comment]
+ 1 rename. Don't hurt a otherwise great initiative by being inconsiderate.

**Comment by arbroween** [comment]
+1 rename

**Comment by lozlow** [comment]
+1 rename

**Comment by alxers** [comment]
+1 rename

**Comment by chopmo** [comment]
+1 for renaming

**Comment by ljharb** [comment]
While we appreciate everyone offering input, and will consider it, please do not offer simple "+1s", as these add no value. I will be deleting all +1s that offer nothing to the conversation, and if more continue to be added, I will be forced to lock the conversation.

**Comment by rocky-jaiswal** [comment]
Please rename. There is a popular ClojureScript library with the same name. This will do nothing except confuse people.

**Comment by gadfly361** [comment]
@ljharb I greatly appreciate that the rename will be considered! :)

I would submit, however, that the volume of +1s is *significant* and does affect the conversation - namely that this is important to an overwhelming number of people. Deleting the +1s is unnecessary, given that they are easy to skip past when skimming the thread.

**Comment by csummers** [comment]
Please rename.  It creates confusion when googling.

Also, the value of a +1 is an indicator of the magnitude of the issue.

**Comment by jiyinyiyong** [comment]
Maybe like "polyglot.js", just call it "reagent.js", will that help?

**Comment by ljharb** [comment]
@jiyinyiyong a ".js" suffix is a bit dated, so i wouldn't be in favor of using that convention for projects moving forward.
@gadfly361 i don't find them easy to skip past when I'm trying to read the whole thread to understand people's thoughts. +@csummers: Issues (of any kind) are not decided based on "popularity" or "number of people affected" - 1 person is just as important as 1 million. The only impact "+1" has is irritating contributors; it doesn't increase the perceived importance of the issue.

**Comment by julianjelfs** [comment]
@ljharb  Of course the +1s add value. They show clearly the level of feeling. If you delete them it just looks like you are in denial.

**Comment by burhanloey** [comment]
Please consider renaming this project. Both are used in JavaScript AND for React, which is not cool.

**Comment by vibl** [comment]
The +1s are the most important information in this thread.

This is a community problem, the community should, if not decide, at least be heard.

There isn't any representatives here, so the only voices are members voices.

The number of people that are affected by the name collision and agree about the best way to solve the problem is the one thing that should be considered in priority.

I hope as much people as possible will express their interest, by +1s, -1s or a comment.

**Comment by ioRekz** [comment]
I could actually use both library in my project so I would like to see a way to differentiate them when googling reagent.

**Comment by chepprey** [comment]
I agree that the Clojurescript Reagent project rightfully has dibs on the name, and the fact that both of these projects are related to react.js would cause undue confusion.

How about we come up with some cool react-ish alternative names for this Airbnb project?  How about "Reaction"? "Reactant"? "Reactest"?

**Comment by ljharb** [comment]
@vibl as I've said, the number of people is irrelevant, because one person carries as much weight to us as one million. No voices are needed because the issue has been raised, and we are considering it. Additional points - that have not already been raised - are indeed valuable, and I hope people will continue to add those.

So far, what's been raised is:
 - hard to google (this is already a problem for the ClojureScript library because "reagent" is a chemistry word)
 - confusion for existing users of the ClojureScript library
 - confusion for future users of both the ClojureScript library and this project
 - and the most compelling imo, from [here](https://github.com/airbnb/reagent/issues/43#issuecomment-161942840), is "play nice with the OSS community"

Please rest assured that even if no further comments were added to this thread, we will be considering it with the same amount of speed and attention than we would if thousands of people cluttered our email inboxes with "+1" notifications :-) (perhaps faster without the clutter!)

Alternate name suggestions are indeed welcome as well, but it might also help to put those in a separate issue.

**Comment by mtrimpe** [comment]
Definitely agree that the project should be renamed.

Reagent is a very popular key component for the (rather big) ClojureScript React community. This will definitely cause a lot of confusion and do a lot of damage to their project (and this one too.)

By itself that's hopefully plenty motivation to find an even better name; but also keep in mind that trying to keep the name would be very bad PR for AirBnB in the open source community.

Hope you choose to do the right thing! The project looks pretty cool...

**Comment by KingMob** [comment]
Two projects in the React space named Reagent? Ugh, no. Please do us and search engines a favor and rename it.

**Comment by milt** [comment]
:+1: Please rename. Trust me, you don't want that name due to the chemistry connection, my search history looks like I've been trying to stock up a meth lab.

**Comment by postspectacular** [comment]
+1 for renaming! Reagent is established for 2+ years and one of the most prominent CLJS projects. I'd hate to see you just steamrolling it into invisibility due to your project's larger mass appeal to the pure-JS crowd. There're enough other names to choose from!

**Comment by lelandrichardson** [comment]
Thank you to everyone in this thread for your thoughts. A project rename is being considered.

I would like to add to Jordan's comments the following:

1. Please no more "+1" comments in this thread. We see that there are people who feel this needs to happen, and additional "+1" comments will no longer affect our decision. If you have more to say than please say it, however.
2. To add a bit of context, the project was just renamed from `catalyst` internally. To be fair, this could have been done with a bit more research, but the main measure of "name is available" we were looking for was the package name being available on npm. Lesson learned.
3. If this project is to be renamed, I would like for it to happen FAST.

Airbnb (and myself) of course want to be good stewards to this project and to the open source community at large, and have no desire to do it damage.

If you have any name recommendations, please put them in https://github.com/airbnb/reagent/issues/46

**Comment by dviramontes** [comment]
+1 
I second @postspectacular 
I use **ClojureScript/Reagent** every single day and its a formidable library.

**Comment by jbeja** [comment]
Thank you for reconsider.

**Comment by maacl** [comment]
@lelandrichardson @ljharb Ref your comments on +1 comments you guys have a lot to learn about running an open source project, if you consider the minor inconvenience it may cause you more important that letting the community voice its opinion.

**Comment by meatcompute** [comment]
Maintainers: thank you for your consideration. As a user of cljs Reagent on a daily basis, I'm concerned that the name clash will be unhealthy for both projects in the long run.

I imagine the worst side effect would be on cljs devs when attempting to use this project in a ClojureScript environment.

I would urge the maintainers to take us into consideration and use this time to pick a new name for http://github.com/airbnb/reagent.

**Comment by hzhu** [comment]
I ask that Airbnb rename this open source project.

Big fan of Airbnb and Airbnb engineering. I attend Airbnb Nerds meetup at your HQ as often as I can. We use Reagent in production at the company I work at. Though I use Reagent at work (and sometimes side projects), I consider myself first and foremost a JavaScript developer. The Reagent (CLJS) community really considers themselves not a separate community (isolated from React/JavaScript) both part of both, a joined community.

It would really suck to see Airbnb, not rename, and steamroll the existing open source project. Ya'll got 500 stars in a few days.

Also the +1 comments though minimal in value, showed how many people we're affected or care about this issue. So far **44** of those +1 comments have been silenced and removed.

**Comment by ljharb** [comment]
@hzhu I don't think playing the game of "more people means it matters more" is going to be productive, especially if people start comparing the sizes of the JS and ClojureScript communities, or the number of stars a project has, etc. It's sufficient to say that *any nonzero number of people* are impacted, and that absolutely is enough to warrant consideration, with any issue, at any time, in any context.

@maacl thanks for your input. I'm following the lead of many other popular open source projects, including npm itself, in not conflating "the community voicing its opinion" with "let's all dogpile on a thread without adding any value". I appreciate that everyone wants to be heard, but that doesn't automatically guarantee that what they have to say is useful to anybody.

Thanks again to everybody for their input. Please follow along on #46 for naming suggestions, and please try to refrain from commenting unless you have a **new** thing for us to consider that adds to [this list](https://github.com/airbnb/reagent/issues/43#issuecomment-162013860).

**Comment by ericqweinstein** [comment]
+1 for rename.

**Comment by ericqweinstein** [comment]
^ Apologies, I missed @lelandrichardson's comment above. My thought process:

  * The ClojureScript and JavaScript communities are closely-knit enough, IMHO, that this would be confusing regardless;
  * The ClojureScript project is specifically an interface for React, meaning:
  * Any attempt to search for "javascript reagent," "javascript testing reagent," &c, is more likely to confuse the issue than to provide meaningful feedback.

**Comment by bhugueney** [comment]
Thanks for considering renaming the project. Names should be "locally" unique to avoid confusion. Javascript React is a specific enough space so that names uniqueness is a realistic goal. It will be a one time pain for you to switch, but taking the high road will be repaid by the goodwill you will reap from it.

**Comment by sundbry** [comment]
Please don't lift the reagent name from the clojurescript project. It is a great library.
A couple name suggestions:
  "Retest"
  "Replay"

**Comment by rygine** [comment]
Not sure how this slipped past the author(s). I'm also in favor of a name change.

**Comment by spikebrehm** [comment]
> Not sure how this slipped past the author(s).

It's unrealistic for a few people to be familiar with the full breadth of the React ecosystem.  The NPM package name was free so we figured so was the name.

**Comment by spikebrehm** [comment]
__Locking this issue for now because everyone agrees we need a rename.__ Thanks again to everybody for your input. 

Please follow along on #46 for naming suggestions.

**Comment by ljharb** [comment]
Closed with 38ae4b2

**Comment by ljharb** [comment]
Thanks everyone for your feedback and civil discussion, and thanks to those who agreed with the rename but refrained from burying us in +1s! We've renamed the project to `enzyme` and it's freshly available on [`npm`](https://www.npmjs.com/package/enzyme). Thanks as well to those who suggested names in #46.

Mistakes happen, but we definitely don't want to steal someone's thunder, nor steamroll another project, nor add confusion to the plates of those attempting to build cool stuff. Our sincere apologies to the folks at https://github.com/reagent-project/reagent (and its users).

We've published a "v1.0.1" under the "reagent" name on [npm](https://www.npmjs.com/package/reagent) that does nothing except direct users to install `enzyme` - we'll leave that package up for at least a month or two, after which, @reagent-project is free to take it over if they wish; otherwise we'll keep it as-is so as to not leave it open for someone else to accidentally take.

**Comment by gadfly361** [comment]
Very excited and grateful to see this name change, thank you!!

@ljharb Definitely makes sense to leave the "reagent" name up on npm for a couple of months as a pointer to enzyme to ease the transition.  After that, I am happy to take it over on behalf of reagent-project.  We can coordinate that when the time comes and outside of this thread (my email is on my github page).

**Comment by Morantron** [comment]
:clap:
