### ISSUE TITLE
Can't pass on Context when using with react-redux's connect

### ISSUE THREAD

**Issue by 5punk** [airbnb/enzyme#436]
Hi Guys,
I've a bit of a situation, when using enzyme for rendering React Components for my unit tests, I cannot pass over the context when I am exporting the component using react-redux's `connect`.

Let me show you what I mean:

Component: 
```
class TestPage extends Component {
  contextType = {
     a: required
  }
  render() {
    return (<div>1</div>);
  }
}
export default TestPage;
```

Test:
```
import { shallow } from 'enzyme';

wrapper = shallow(<TestPage>, {
  context: {
    a: 10
  }
});
```

This WORKS!

BUT:

Component:
```
class TestPage extends Component {
  contextType = {
     a: required
  }
  render() {
    return (<div>1</div>);
  }
}
export default connect( state => ({ a: state.runtime.a }))(TestPage);
```

Test:
```
import { shallow } from 'enzyme';

wrapper = shallow(<TestPage>, {
  context: {
    a: 10
  }
});
```

Spits out: ``Warning: Failed Context Types: Required context `a` was not specified in `TestPage```

Help... How do I pass on my context through Redux's connect function?

**Comment by MQuy** [comment]
@5punk it's the same as my issue https://github.com/airbnb/enzyme/issues/435

**Comment by MQuy** [comment]
Not sure it's correct or not, but I think it's related to our problem https://github.com/airbnb/enzyme/issues/435
The context is passed to that function but, it doesn't work

**Comment by Aweary** [comment]
@MQuy can you try defining a `childContextTypes` as well? It should work then. I use `redux-mock-store` and enzyme at work and this works fine.

```js
wrapper = shallow(<TestPage>, {
  context: {
   store: mockStore
  },
  childContextTypes: {
    store: React.PropTypes.Object
  }
```

**Comment by MQuy** [comment]
@Aweary I tried, it's still the same, just tested in this repo https://github.com/MQuy/redux-store-enzyme

**Comment by Aweary** [comment]
@MQuy this is exactly what we do internally where I work, so I'll have to try and reproduce when I'm back home to see what's going on 👍

**Comment by MQuy** [comment]
thank @Aweary  👍

**Comment by 5punk** [comment]
Does rewiring `react-redux's` connect function make sense?
I was trying to do something like..

```
// Rewire React-redux, connect API
  TestPageRewired.__Rewire__('connect', (props) => {
    console.log('Rewired Connect');
    return {
      contextTypes: [{ requiredContext: () => {} }],
      ...props
    };
  });
```
But this isn't working for me. Am I missing something?

**Comment by blainekasten** [comment]
#472

**Comment by jamrizzi** [comment]
There's an npm module that makes it really easy to add redux to the react context

https://github.com/jamrizzi/redux-context-provider
https://www.npmjs.com/package/redux-context-provider

```js
import React, { Component } from 'react';
import ReduxContextProvider from 'redux-context-provider';
import createStore from './createStore';
import actions from './actions';
import Routes from './routes';

export default class App extends Component {
  render() {
    return (
      <ReduxContextProvider store={store} actions={actions}>
        <Routes />
      </ReduxContextProvider>
    );
  }
}
```
