### ISSUE TITLE
Proper test failure message?

### ISSUE THREAD

**Issue by Anahkiasen** [airbnb/enzyme#447]
The recommended way to use enzyme seems to be doing this:

```js
const wrapper = shallow(<Foo />);

expect(wrapper.equals(<div>)).toBe(true);
```

However on failure all that yields is `Expected false to be true` which is extremely unhelpful. Am I missing something here? Is there a way to display a JSX diff like [expect-jsx](https://github.com/algolia/expect-jsx) does?

**Comment by jackpopp** [comment]
It's usually the responsibility of your assertion library for example with chai its a optional second parameter - http://chaijs.com/api/bdd/#method_equal

**Comment by Anahkiasen** [comment]
Ah yes I understand, but if I understand correctly those would just display a diff of the React objects, not a JSX diff no?

**Comment by Anahkiasen** [comment]
That being said I just tested which Chai as `chai-enzyme` and the error message isn't much better:

```
    AssertionError: expected <ContactAvatar /> to contain { Object ($$typeof, type, ...) }

      + expected - actual



     HTML:

     <div class="foo">
       <div style="background-image:url(&quot;http://foo.jpg&quot;);" class="c-avatar c-avatar-large"></div>
     </div>
    at Context.<anonymous> (/Users/anahkiasen/Sites/madewithlove/sweepbright-webapp/tests/index.js:33933:302 <- webpack:///tests/Components/Elements/Contacts/ContactAvatarTest.js:9:1408)
```

I guess my question is what is the *recommended* way to use enzyme?

**Comment by Aweary** [comment]
I'm not sure we have one "recommended" way to do this, enzyme doesn't make any assumptions about what assertion library or test runner you're using.

```js
expect(wrapper.equals(<div>)).toBe(true);
```

Enzyme doesn't have any control over what the output of this statement would be, as @jackpopp mentioned. All it knows is to return a boolean value from `equals`. If you think `chai-enzyme` could be more helpful feel free to discuss that with them!

I'm going to close this as its out of the scope for enzyme and there's nothing actionable for us, but feel free to continue your conversation 👍
