### ISSUE TITLE
Test component with style via props

### ISSUE THREAD

**Issue by ivanbtrujillo** [airbnb/enzyme#451]
Hi all,

I'm trying to test a component that has an object with an style via props.

The component:
`render(){
    return(
      <View >
        <Text style={this.style.title}>{this.props.rowData.title}</Text>
      </View>
    )
  }`

Inside my test, i have an object with the style and other for the data:
`const styles = StyleSheet.create({
  post: {
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    padding: 10,
  },
  title: {
    fontSize: 18
  },
  content: {
    fontSize: 14
  }
});`

`var data={
  title:'This is the title',
  content:'This is the content'
}`

Here, i render the component:
`const wrapper = shallow(<Post rowData={data} style={styles}/>);`

So when i try to check if the component it's ok :
`it("Should have a title", () => {
    //Title
    expect(wrapper.contains(<Text style={fontSize: 18} >This is the title</Text>)).to.equal(true);
  });`

i've obtain an unexpected token error :
<img width="1045" alt="captura de pantalla 2016-06-13 a las 10 21 52" src="https://cloud.githubusercontent.com/assets/6088653/16002640/ad4f530a-3150-11e6-9016-bb920fb42818.png">

If i remove the style (from test and component) it works, so it seem that doesn't understand my styles object but the data object works perfectly.

Some ideas to make it work or anybody know what i'm doing wrong?

Thanks in advance!

**Comment by AugustinLF** [comment]
And if you do `it("Should have a title", () => { //Title expect(wrapper.contains(<Text style={{fontSize: 18}} >This is the title</Text>)).to.equal(true); });`, does it work? You need to write an object literal inside the `style={}` :) This has nothing to do with your tests, it's just not JSX valid!

**Comment by Aweary** [comment]
@AugustinLF is exactly right, your test contains a syntax error 👍  Closing as this isn't an actual issue with enzyme.

**Comment by ivanbtrujillo** [comment]
Yep was that, thanks for answer with a literal object inside it works.
