### ISSUE TITLE
is ":not" selector not supported?

### ISSUE THREAD

**Issue by arch-mage** [airbnb/enzyme#456]
What I understand is that ":not" is a css selector to find an element without specified attribute.
So, with this component:

``` javascript
const Table = () => (
  <table>
    <thead>
      <tr>
        <th></th>
        <th></th>
      <tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td></td>
      <tr>
    </tbody>
  </table>
);
```

But why this is happening?

``` javascript
wrapper.find('th[scope="row"]').length // == 1
wrapper.find('th:not([scope="row"])').length // == 0 ?
```

**Comment by koba04** [comment]
You can see enzyme is supporting CSS selectors in the following.

https://github.com/airbnb/enzyme/blob/master/docs/api/selector.md#1-a-valid-css-selector

**Comment by blainekasten** [comment]
We'd gladly accept a PR if you were wanting to add support for the `:not` selector!

**Comment by AugustinLF** [comment]
I'm giving it a try, I'll ley you know soon of my progress!

**Comment by ljharb** [comment]
This was added in #460.

**Comment by akegan** [comment]
Looks like the PR referenced above ended up getting closed rather than merged. Does anyone know whether or not it got implemented, and if it did, which version it was released in?

**Comment by ljharb** [comment]
@akegan it ended up moving to #1086, and should be in all versions of enzyme 3.
