### ISSUE TITLE
Attribute Selector with data-attributes

### ISSUE THREAD

**Issue by jacobp100** [airbnb/enzyme#457]
Failing test file (with ava),

```js
test('data test', t => {
  t.plan(5);

  const component = mount(<div><span data-test="test" /></div>);

  t.true(component.contains('[data-test="test"]'));
});
```

**Comment by Aweary** [comment]
@jacobp100 `contains` doesn't use a selector

http://airbnb.io/enzyme/docs/api/ReactWrapper/contains.html

> .contains() expects a ReactElement, not a selector (like many other methods). Make sure that when you are calling it you are calling it with a ReactElement or a JSX expression.

So instead you should use:

```js
t.true(component.contains(<span data-test="test" />));
```
