### ISSUE TITLE
hasClass don't work as expected

### ISSUE THREAD

**Issue by OttlikG** [airbnb/enzyme#466]
Can I do anything for this test to pass?

```javascript
it('Test hasClass', () => {
  let li = mount(
    <li class="slds-tabs--scoped__item slds-text-heading--label slds-active" title="Tab2" role="presentation">
      <a class="slds-tabs--scoped__link visible-tab" data-tab-index="1" href="#tab_2" role="tab">
        Tab2
      </a>
    </li>
  )
  expect(li.hasClass('slds-active')).to.equal(true)
})
```

**Comment by Aweary** [comment]
You need to use `className` instead of `class`, since this is expected to be a React element.

**Comment by OttlikG** [comment]
Thanks your response. Now I can see what caused the problem.
The following code fails, even so I get this from the console.log:
LOG: '_secondTab', `<li class="slds-tabs--scoped__item slds-text-heading--label slds-active" title="Tab2" role="presentation"><a class="slds-tabs--scoped__link visible-tab" data-tab-index="1" href="#tab_2" role="tab">Tab2</a></li>`

```javascript
_secondTab = _wrapper.find('.slds-tabs--scoped__nav').childAt(1)
console.log('_secondTab', _secondTab.html())
expect(_secondTab.hasClass('slds-active')).to.equal(true)
```

When I extend my query with find, it'll pass:
```javascript
expect(_secondTab.find('li').hasClass('slds-active')).to.equal(true)
```
I have seen, that both childAt() and find() return with the same ReactWrapper.
Did I misunderstand something about the API?
