### ISSUE TITLE
Button click simulation is returning true with shallow rendering.

### ISSUE THREAD

**Issue by muneermuhammed** [airbnb/enzyme#468]
I'm running the test for a login operation. Shallow rendering is used here and on triggering the button click it is returning false. On debugging the jsx I'm getting the following as the response,
```
<div id="login" className="card">
<div>
<h1>
Welcome
</h1>
<p>
Login to manage your business.
</p>
<div className="tabs">
<i onClick={[Function]} data-tab="0" className="fa fa-phone active" aria-hidden="true" />
<i onClick={[Function]} data-tab="1" className="fa fa-at" aria-hidden="true" />
</div>
<div className="inputs">
<PhoneNumber countryData={{...}} suggestions={{...}} onChange={[Fu   nction]} onSubmit={[Function]} autofocus={true} value="123456789"  selectedCountry="India" validationHandler={[Function]} />
</div>
<button className="button" type="button" onClick={[Function]}>
Continue
</button>
</div>
</div>
```

And my test script is given below, 

```
it('find the tab state', () => {

//     const wrapper2 = mount(<PhoneNumber value="1234567890"  suggestions={item}/>);
 const onsubmit = sinon.spy();
   const wrapper = shallow(<Login onClick={onsubmit} countryData={Countries} suggestions={item}/>);
     wrapper.setState({ tab: 0 });
     wrapper.setState({ clientNumber: '1234567890' });
     wrapper.setState({clientCountry: "India"});
     wrapper.setState({dial_code: '+91'});
     console.log(wrapper.state('loading'));
     wrapper.find('button').simulate('click');
     wrapper.simulate('submit');
 //   expect(spy.called).to.equal(true);
 //  console.log(wrapper.find('button').simulate('click'));
  expect(onsubmit.calledOnce).to.equal(true);
});
```

I'm new to reactjs and enzyme as well. So don't know I'm doing it in the right manner. All kinda helps are appreciated.

**Comment by blainekasten** [comment]
Can you share the code for `Login` component? 

###### side note. 
Calling `setState` multiple times is slower than calling it once with all the object changes you want. You could just do

```js
wrapper.setState({ 
  tab: 0, 
  clientNumber: '1234567890',
  clientCountry: "India",
  dial_code: '+91',
});

**Comment by muneermuhammed** [comment]
Thanks @blainekasten . I will make the changes accordingly. And the following is the login implementation, [Login ](https://gist.github.com/muneermuhammed/c2367799cf01c471a88a0a91c0aaac56)

**Comment by blainekasten** [comment]
So, a couple things I'm noticing:

* Login does not do anything with any props. So the fact that you are expecting to pass a prop in (`onSubmit`) and it to be called won't ever be true unless you call that prop as a result of a `button.onClick`

So to explain in a reduced case, this is basically what your component is doing:

```js
class Comp extends React.Component {
  handleClick() {
    // does logic
  },
  render() {
    return (
      <button onClick={this.handleClick} />
    );
  }
}
```

in that example above, it doesnt do anything with any prop. So if you are wanting your assertion to pass you would have to do something more like this:

```js
class Comp extends React.Component {
  handleClick() {
    // does logic
    this.props.onSubmit(); // THIS IS THE IMPORTANT PART
  },
  render() {
    return (
      <button onClick={this.handleClick} />
    );
  }
}
```

This one means that when the button is clicked, it will ultimately calls `props.onSubmit`. Does that make sense?

**Comment by muneermuhammed** [comment]
I admit that. But here, in this case, I'm not allowed to make changes to the Reactjs code.  I'm only dealing with the test part.

**Comment by blainekasten** [comment]
Okay. I'm not sure how to help then. That test will never pass unless the underlying component is changed. Are you sure that's what the component should be doing?

As this is showing to not be a problem with enzyme, and there isn't any action item for us, i'm going to close out this issue. Feel free to keep the conversation going however.

**Comment by muneermuhammed** [comment]
Is there any way to simply check whether button click is happening ?

**Comment by blainekasten** [comment]
It looks like the `button` click calls `this.login`. So you could mock that function and assert it gets called, or go lower level and assert that `LoginActions.loginX` gets called by mocking it.

Example:

```js
Login.prototype.login = mockFunction();
const wrapper = mount(<Login />);

wrapper.simulate('click');
expect(wrapper.instance().login).toBeCalled();
```

I think that's the right thing. might need a `instance().prototype.login` there instead.

**Comment by muneermuhammed** [comment]
Thanks. But that did not work for me. But when I tried with shallow, it seems like the values are assigning just like the below one,

`<div id="login" class="card"><div><h1>Welcome</h1><p>Login to manage your business.</p><div class="tabs"><i data-tab="0" class="fa fa-phone active" aria-hidden="true"></i><i data-tab="1" class="fa fa-at" aria-hidden="true"></i></div><div class="inputs"><div class="phoneInput focused"><div><span><div style="position:relative;"><span><button>+57 <i class="fa fa-caret-down" aria-hidden="true"></i></button></span><input style="position:absolute;z-index:-1;width:20%;height:20%;top:5%;left:5%;opacity:0;"/></div></span><span><input type="text" placeholder="Phone" value="123456789"/></span></div></div></div><button class="button" type="button">Continue</button></div></div>`

 I could find nothing to expect apart from the values assigning to the inputs to assert statement here.

**Comment by muneermuhammed** [comment]
And when I try the assertion statement 
`expect(wrapper.equals(<input type="text" placeholder="Phone" value="1234567489"/>)).to.equal(true);
`
it is returning false. Do you have any idea why it is so ?

**Comment by ljharb** [comment]
The wrapper may contain that element, but it doesn't equal it. Try .contains instead?

**Comment by muneermuhammed** [comment]
I have tried contains but there are no changes in the response.
