### ISSUE TITLE
.equals()/.matchesElement()/.is() with two shallow renders of the same element returns false.

### ISSUE THREAD

**Issue by aubford** [airbnb/enzyme#477]
Very confused as to why all of these return false.

```
  const one = shallow(<LoadingScreen logo= { logo } loadingIcon= { loadingIcon } />)
  const two = shallow(<LoadingScreen logo= { logo } loadingIcon= { loadingIcon } />)

  console.log(one.equals(two))
  // false
  console.log(one.matchesElement(two))
  // false
  console.log(one.is('LoadingScreen'))
  // false
  console.log(one.first().equals(two.first()))
  // false
  console.log(one.first().matchesElement(two.first()))
  // false
```

**Comment by ljharb** [comment]
Because all of those methods take ReactElements, and you're passing them enzyme wrappers?

**Comment by ljharb** [comment]
You may want `one.equals(<LoadingScreen logo= { logo } loadingIcon= { loadingIcon } />)`?

As for `one.is('LoadingScreen')` - that's false because it's comparing to what `LoadingScreen` *renders* - not LoadingScreen itself. Try `console.log(one.debug())` to see what it's rendering.

**Comment by aubford** [comment]
Thanks.  I find it strange that you have no access to a wrapper for a container element at the highest level in case you want to check props ect.  I guess I can always wrap it in a div, though.  Also your equals example returns false as well.

**Comment by ljharb** [comment]
Ah right that's true :-) `one` isn't actually a LoadingScreen, it's a wrapper around what it *renders* - so all those methods' behavior depends on the implementation of `LoadingScreen`.
