### ISSUE TITLE
Selector fails if data attribute value is using quotes

### ISSUE THREAD

**Issue by janodvarko** [airbnb/enzyme#478]
Example:
<div className='myDiv' data-index='5' />

This query currently fails:
expect(wrapper.find('.myDiv[data-index="5"]')).to.have.length(1);

Only this works (no quotes around 5):
expect(wrapper.find('.myDiv[data-index=5]')).to.have.length(1);

Could the first case be fixed?
Note that this syntax works for Element.querySelector() API.

Honza

**Comment by Aweary** [comment]
Hey @janodvarko thanks for the report! I wasn't able to reproduce your issue. You can see a passing test case here: [enzyme-test-repo/blob/issue-478/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-478/test.js)

```js
class TestComponent extends React.Component {
  render() {
    return (
      <div className="foo" data-index="5">
          <h1>Hello, {this.props.name}</h1>
      </div>
    );
  }
}

/**
 * Change the `describe` and `it` block so it acurately describes
 * the test that you are trying to reproduce.
 */

describe('Issue #478', () => {
  it('should find elements with quoted data attribut values', () => {
    const wrapper = mount(<TestComponent/>);
    expect(wrapper.find('.foo[data-index="5"]')).to.have.length(1);
  });
})
```

What version of Enzyme are you using?  I see you're using a compound selector, are you sure you have an element with the `myDiv` class and the `data-index` attribute set to `"5"`?

**Comment by blainekasten** [comment]
The reason one test is passing and the other is not is that we decided to have quotes literally mean string value. So effectively you are asking `5 === '5'` which is obviously false.

We should probably document that clearly...

**Comment by Aweary** [comment]
Yeah it's likely the difference between using `data-index={5}`  or `data-index="5"`

**Comment by janodvarko** [comment]
I see, that explains the behavior, thanks!

Honza
