### ISSUE TITLE
Invalid Doc for JSDom 9.3.0

### ISSUE THREAD

**Issue by KrysKruk** [airbnb/enzyme#483]
In JSDom 9.3.0 `Image` constructor is no longer enumerable in the `defaultView` (see https://github.com/tmpvar/jsdom/commit/bc9b6b40fd4e9e8bbedd440fdc491f6ace561324 ).

[Using Enzyme with JSDOM](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md) doc file should use `Object.getOwnPropertyNames` instead of `Object.keys` in the provided example to make sure that `Image` constructor is available in the `global` namespace.

**Comment by KrysKruk** [comment]
BTW I'm not sure why, but `Object.getOwnPropertyNames` on Node v6.2.2 doesn't return the `Image` constructor.

```
> process.version
'v6.2.2'
> Object.getOwnPropertyNames(require('jsdom').jsdom('').defaultView).indexOf('Image')
-1
> Object.getOwnPropertyDescriptor(require('jsdom').jsdom('').defaultView, 'Image')
{ value: [Function: Image],
  writable: true,
  enumerable: false,
  configurable: true }
```

**Comment by ljharb** [comment]
I've noticed this Object.getOwnPropertyNames issue as well. It might be a v8 bug but I think jsdom should be providing an array of window properties for us, so we can work around it :-/

**Comment by jbinto** [comment]
This is due to a change in jsdom.

https://github.com/tmpvar/jsdom/blob/master/Changelog.md

> Fixed all constructors that appears as globals on the jsdom window object to be non-enumerable.

This is based on the spec according to this discussion: https://github.com/tmpvar/jsdom/issues/1546#issuecomment-230126658

**Comment by jbinto** [comment]
I created another issue about Enzyme's docs contradicting jsdom's docs here: https://github.com/airbnb/enzyme/issues/507

**Comment by KrysKruk** [comment]
Thanks @jbinto for creating the issue. IMO we should continue the discussion on your issue. It's well described and more abstracted.

@ljharb Feel free to reopen this issue.
