### ISSUE TITLE
Docs need to be deployed?

### ISSUE THREAD

**Issue by acco** [airbnb/enzyme#484]
Hey guys,

I'm not sure how the `http://airbnb.io/enzyme/` site is updated (releases?), but it appears it's tracking behind `master`.

For example, [this commit](https://github.com/airbnb/enzyme/commit/b5a3954a34144d9f47d202cd6f0d0be9715e471b) fixes a broken example config for enzyme+jest, yet [the site](http://airbnb.io/enzyme/docs/guides/jest.html) still reflects the outdated doc. (Checked in multiple browsers)

Thanks!
A

**Comment by blainekasten** [comment]
cc @lelandrichardson / @ljharb

**Comment by ljharb** [comment]
It should be updated with releases, but not keep apace with master.

I'll make sure it's updated with the next release.

**Comment by blainekasten** [comment]
Did it get updated with 2.4.1 ? Can we close?
