### ISSUE TITLE
Attribute selector values containing # broke in 2.4.0

### ISSUE THREAD

**Issue by rixth** [airbnb/enzyme#495]
https://github.com/airbnb/enzyme/issues/314 caused a regression. It broke attribute selectors with values containing `#`, ex  `a[href='/page#anchor']`.

Failing test case:

```
it('should query attributes with hashes in their values', () => {
  const wrapper = mount(
    <div>
      <a href="/page">Hello</a>
      <a href="/page#anchor">World</a>
    </div>
  );
  expect(wrapper.find("a[href='/page#anchor']")).to.have.length(1);
});
```

**Comment by rixth** [comment]
In the function `splitSelector` in `Utils.js`, the regular expression `/(?=\.|\[.*\])|(?=#|\[#.*\])/` is a little over-zealous, causing `a[href='/page#anchor']` to be split in to `[ 'a', '[href=\'/page', '#anchor\']' ]`. Prior to this change, it was split to `[ 'a', '[href=\'/page#anchor\']' ]`

**Comment by Aweary** [comment]
Well, it's not necessary over-zealous, it's just not smart enough to handle compound selectors and attribute values containing `#`. https://github.com/airbnb/enzyme/pull/458 would likely fix this, but feel free to work on a PR to fix the RexEp for now, since https://github.com/airbnb/enzyme/pull/458 still has issues that haven't been worked out.

**Comment by ljharb** [comment]
fwiw, before releasing or merging anything new, we urgently need to either fix this behavior regression or revert #314.

**Comment by Aweary** [comment]
Reverting #314 would be easiest if we need an urgent fix, I'm not 100% sure how difficult it's going to be to get this behavior working correctly. That regex is getting unwieldy

**Comment by Aweary** [comment]
@ljharb should we just revert #387? It seems that fixing this behavior is going to be non-trivial, and we've already let this sit for quite a while.

**Comment by ljharb** [comment]
Yes, I think we should.

**Comment by ljharb** [comment]
Let's keep the test cases tho, skipped.

**Comment by mik01aj** [comment]
Maybe #547 is related to this too?

**Comment by rixth** [comment]
@mik01aj I don't think so -- the code that caused this bug was not present in 2.3.0 (as mentioned in the linked ticket).

**Comment by rixth** [comment]
Why was 2.5.0+ released given that it was a regression, and there was earlier talk of reverting the PR that introduced it?

**Comment by ljharb** [comment]
I think this has slipped through the cracks. When we get a fix in, I'll backport it to both the 2.4.x and 2.5.x lines.

**Comment by ljharb** [comment]
I've put up #670 which fixes this issue without reverting #387.

**Comment by ljharb** [comment]
v2.4.2, v2.5.2, and v2.6.0 are all now published and all contain this fix.

Sorry for the delay!

**Comment by rixth** [comment]
Wahoo, thanks @ljharb!
