### ISSUE TITLE
Unaware of ReactDOM.render()

### ISSUE THREAD

**Issue by georeith** [airbnb/enzyme#496]
I am attempting to test a function that calls `ReactDOM.render()` on a stateless root component. In doing so I realised the following:

```js
class ComponentA extends React.Component {
    render() {
        return <div />;
    }
}
const rootComponent = mount(<div />);
const rootNode = ReactDOM.findDOMNode(rootComponent.instance());
ReactDOM.render(<ComponentA />, rootNode);
console.log(rootComponent.children().length) // 0;
console.log(rootComponent.children.length) // 1;
```

Although React states that multiple calls to `ReactDOM.render()` given the same parent node and component will cause it to only apply the difference which must mean it is able to see that the component is in there.

I couldn't see it stated anywhere what enzyme will and will not find in regards to how a component has been inserted, does it only work with composition?

If so does anyone know how if at all I would search/wrap a stateless component inserted by `ReactDOM.render()` wrapped in a function with the only access being the container node to insert into?

**Comment by ljharb** [comment]
That sounds more like a test of the function doing the insertion - which isn't a React component.

`enzyme` would be used to test `ComponentA` in isolation - and once you've got plenty of tests that cover the behavior of that component, you'd write separate non-enzyme tests for the non-component function that's mutating the DOM.

**Comment by georeith** [comment]
@ljharb Thanks the issue was I couldn't test that function as its output solely depended on what happened in React. I was testing the entry to a library but realised the reason what I was doing was so hard to test was because it is probably an anti-pattern and refactored to remove the non-react layer and just let the library return the top component and put these functions on it.
