### ISSUE TITLE
Get doesn't always return a react element

### ISSUE THREAD

**Issue by bdwain** [airbnb/enzyme#497]
the [get](http://airbnb.io/enzyme/docs/api/ReactWrapper/get.html) method for mounted components doesn't always return a react element even though it says it does. if i create something with nested components, like this,

``` js
   let el = (
     <Parent><Child /></Parent>
   );
   let wrapper = mount(el);
   console.log(wrapper.get(0)); //Parent Component instance, not element
   console.log(typeof wrapper.get(0)); //object, not reactelement

  console.log(wrapper.find(Child).get(0)); //Child component instance, not element
  console.log(typeof wrapper.find(Child).get(0)); //object, not reactelement
```

is there a way to get the element?

**Comment by bdwain** [comment]
i would like to use it with https://github.com/algolia/react-element-to-jsx-string

**Comment by bdwain** [comment]
i guess i can actually do this with shallow rendering and the context option. but is there a way to do it with mount?

**Comment by ljharb** [comment]
`typeof` will always return "object" because "reactelement" is not a type.

That said, can you console.log the results of `React.isValidElement(wrapper.get(0))` and `React.isValidElement(wrapper.find(Child).get(0))`? If those return `true`, then everything's working; if not, there's a bug.

**Comment by ljharb** [comment]
Also, can you confirm if this happens on `shallow` as well, or only on `mount`?

**Comment by bdwain** [comment]
ah sorry. you're right about about the typeof.

isValidElement returns false in both scenarios above. it only happens on mount though. not shallow.

here's the parent class for reference.

```js
  class Parent extends React.Component {
    constructor(props){
      super(props);
    }

    getChildContext(){
      return {
        foo: true,
        bar: this.props.bar
      };
    }

    render(){
      return this.props.children;
    }
  }

  Parent.childContextTypes = {
    bar: React.PropTypes.func.isRequired,
    foo: React.PropTypes.bool.isRequired
  };
```

and here's what i passed to mount

```js
<Parent bar={someMock}>
  <Child {...someProps} />
</FormParent>
```

**Comment by bdwain** [comment]
and the child class is pretty straightforward. it just uses the context to do some things. nothing out of the ordinary.

**Comment by ljharb** [comment]
What does `wrapper.at(0).debug()` and `wrapper.find(Child).at(0).debug()` print out?

**Comment by Aweary** [comment]
`get` does not return a `ReactElement`, it returns an instance of the component that exists at the passed index. You can see a failing test case here: [enzyme-test-repo/blob/issue-497/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-497/test.js)

`get` relies on `getWrappedComponent` from `ReactWrapperComponent`

```js
    getWrappedComponent() {
      const component = this._reactInternalInstance._renderedComponent;
      const inst = component.getPublicInstance();
      if (inst === null) {
        return component._instance;
      }
      return inst;
    },
```

`component._instance` (which is returned in either case) is not a `ReactElement`, it's an instance of the component that is being rendered. If you want the actual `ReactElement` then you need to use the internal instance which is available on `_reactInternalInstance` (See [`ReactInstanceMap`](https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/ReactInstanceMap.js)) which holds a reference to the element at `_currentElement`.

IMO `get()` not be returning the `ReactElement`. If you need access to the actual `ReactElement` then you can access it via

```js
wrapper.get(0)._reactInternalInstance._currentElement
```

We should just update the docs so it doesn't claim to return a `ReactElement`, which it's never done AFAIK.

**Comment by ljharb** [comment]
@Aweary If we find ourselves recommending underscored properties, perhaps we should add a method like `elementAt(n)` that gets the actual ReactElement?

**Comment by bdwain** [comment]
@ljharb agreed. i think needing the element could be a not uncommon use case.

**Comment by Aweary** [comment]
What are the use cases for accessing the actual `ReactElement` instance? I'm not necessarily recommending it, just pointing out where it can be found. I'm hesitant about providing a new API that just wraps another internal property access for React.

**Comment by ljharb** [comment]
The one thought I have immediately is, passing into `.contains`

**Comment by bdwain** [comment]
@Aweary when testing react components it's nice to just say something like this

```js
   expect(componentWrapper.get(0)).toEqualJSX(<div><span>whatever</span></div>);
```

there's a few libraries that expose that assertion, all relying on [a library that converts a react element to a jsx string](https://github.com/algolia/react-element-to-jsx-string)

**Comment by Aweary** [comment]
> The one thought I have immediately is, passing into .contains

Isn't that tautological though? If you get the `ReactElement` from a wrapper than it by definitions contains the element. And you can't use a `ReactElement` from one wrapper in a `contains` call from another wrapper, even if they render identical components.

**Comment by Aweary** [comment]
> there's a few libraries that expose that assertion, all relying on a library that converts a react element to a jsx string

Can `containsMatchingElement` provide the same/equivalent functionality?

**Comment by Aweary** [comment]
cc @spicyj @gaeron what do you guys think about providing an API that will reach into `_reactInternalInstance` to get the `ReactElement` for a component? Will we be setting ourselves up for trouble?

**Comment by ljharb** [comment]
@Aweary 
> you can't use a ReactElement from one wrapper in a contains call from another wrapper, even if they render identical components.

I'm pretty sure you can, since you can create an element inline and pass it into `.contains` and it works?

**Comment by Aweary** [comment]
I just tried and `contains` returned false, let me try to get a better test case together and see

**Comment by bdwain** [comment]
containsMatchingElement didn't work for me @Aweary

**Comment by Aweary** [comment]
@ljharb so yeah, it does work, but so does passing the component instance

```js
const component = wrapper.find(Foo).get(0)
const element = component._reactInternalInstance._currentElement
// wrapper2 identical to wrapper
wrapper2.contains(component) // true
wrapper.contains(element) // true
```

**Comment by Aweary** [comment]
@bdwain can you share your specific use case?

**Comment by bdwain** [comment]
i think it was related to trying to match against a component with a method for a prop. i got it to work by passing in the actual method on the component that i was matching against.

```js
  class Parent extends React.Component {
    constructor(props){
      super(props);
      this.foo = this.foo.bind(this);
    }

    foo(){
    }

    render(){
      return <Child foo={this.foo}/>;
    }
  }

  function Child(props){
    return <div className="abc" onClick={props.foo}>123</div>;
  }

  it('renders properly', function(){
    componentWrapper = mount(<FormParent />);
    expect(componentWrapper.contains(<div className="abc" onClick={componentWrapper.get(0).foo}>123</div>)).toBe(true);
  });
```

**Comment by Aweary** [comment]
@bdwain you should also be able to just exclude the `onClick` property. `containsMatchingElement` does a sort of loose equality check, something like this should work:

```js
    expect(componentWrapper.contains(<div className="abc">123</div>)).toBe(true);
```

**Comment by bdwain** [comment]
ah got it. that's good to know. i guess this isn't a big deal then. the documentation should just change to reflect that it's not necessarily a reactelement being returned

**Comment by Aweary** [comment]
@bdwain if you want to submit a PR with the doc change I think we can get it updated. If not, we can always do it, just want to offer 😄

**Comment by bdwain** [comment]
Sure. So we're just changing it to say it returns a ReactComponent? or something else

**Comment by bdwain** [comment]
@aweary just realized this pr was still around and still seems relevant. I'd be happy to change the docs. just not sure if ReactComponent is the right return value.

**Comment by bdwain** [comment]
i think this is resolved with v3
