### ISSUE TITLE
onClick event from cloneElement is not available in shallow rendering

### ISSUE THREAD

**Issue by tleunen** [airbnb/enzyme#499]
I have a component (lets say a list) which maps the children and attach an onclick even on each one of them. When testing using the `shallow` renderer, the onClick event doesn't work and is not in the `item.props()` list for the item. When testing with the full dom (`mount`), it works fine.

``` js
{React.Children.map(children, child =>
    React.cloneElement(child, {
        onClick: () => {
            onItemClick(child.props.name);
        }
    })
)}
```

**Comment by blainekasten** [comment]
Do you know if this works with React's TestUtils.shallowRenderer?

**Comment by anthonator** [comment]
@tleunen were you able to find a workaround for this? I can't seem to get children with dynamic props (similar to your example) with `shallow` or `mount`.

**Comment by ljharb** [comment]
@anthonator do you have a test case? The code in the OP seems to work.

**Comment by ljharb** [comment]
ah, looks like this might fail in React 0.13, but works in 0.14+?
