### ISSUE TITLE
incompatibility with karma and react15.2.1

### ISSUE THREAD

**Issue by Joegrundman** [airbnb/enzyme#502]
shallow rendering fails with React15.2.1 and karma 1.1.1

with the following error

```
   ✗ renders as a div
    null is not an object (evaluating 'ReactInstrumentation.debugTool.onSetDisplayName')
    ShallowComponentWrapper@tests.webpack.js:75869:34
    _render@tests.webpack.js:75919:48
    _batchedRender@tests.webpack.js:75901:20
    batchedUpdates@tests.webpack.js:15977:16
    batchedUpdates@tests.webpack.js:1068:35
    render@tests.webpack.js:75894:31
    render@tests.webpack.js:39176:40
    tests.webpack.js:51532:33
    perform@tests.webpack.js:2952:25
    batchedUpdates@tests.webpack.js:15979:27
    batchedUpdates@tests.webpack.js:1068:35
    tests.webpack.js:51531:42
    withSetStateAllowed@tests.webpack.js:40282:6
    ShallowWrapper@tests.webpack.js:51530:39
    shallow@tests.webpack.js:70431:39
    tests.webpack.js:56497:40
```

If react, react-dom and react-addons-test-utils are rolled back to 15.2.0, tests pass

**Comment by Aweary** [comment]
Hey @Joegrundman thanks for the report, can you share the code for the test that is failing?cc @nfcampos, I know you were working on some Karma tests.

**Comment by Joegrundman** [comment]
For sure, although, I think the issue might be with webpack+react+enzyme, and not karma. When i tried running tests through mocha alone (ie, without karma) it worked fine until i started using mocha-webpack to process postcss files into the tests.

anyway the setup can be perfectly demonstrated with this demo repo here: 

[react-yelp-clone](https://github.com/fullstackreact/react-yelp-clone)

if you just npm install, you will have the current react setup,  for react, react-dom, react-addons-test-utils 15.2.1 as of 18th July 2016.  The tests will fail, with errors as shown above, that **null is not an object**  

But if you run npm install having specified in the package.json that you want no later than react 15.2.0 all the tests will pass.

I think you will find seeing it from this repo more use than looking at my stuff, but if you really want it i will show you!

Note that the webpack is made with hjs-webpack library, and also postcss to create css modules. I suspect this is the key area, as the tests use webpack to compile postcss and compare the modularized css class name with the class name on the shallow wrapper

when i tried working without karma, just using mocha, i used the ignore-styles library, and then tests would pass, but of course i could not compare dynamically generated css classnames from css modules. When i tried to use mocha webpack to compile the postcss classes, the test framework would fail again.

As before, rolling back to react, react-dom, react-addons-test-utils 15.2.0 will see all tests pass.

hope this helps!

**Comment by nfcampos** [comment]
Hi @Joegrundman!
It looks like you're running into a react "bug" (it's not really a bug, it's just changed behaviour, see https://github.com/facebook/react/issues/7231).
Basically you're running the tests with a production version of react (see this line in `hjs-webpack` https://github.com/HenrikJoreteg/hjs-webpack/blob/master/index.js#L160).
You can fix it by changing this line in https://github.com/fullstackreact/react-yelp-clone/blob/master/webpack.config.js#L21  to `isDev: isDev || isTest,`.

does this help?
Nuno

**Comment by Joegrundman** [comment]
Hi @nfcampos,

that's awesome, yes that fixed the problem! thanks so much, and sorry for wasting your time. I thought maybe the react update had broken an enzyme usecase and you'd want to fix it, but that was not the situation!

Still, I see it tripped up gaeron among others, so, for a mortal like me perhaps not too shameful :-)

best wishes

Joe

**Comment by nfcampos** [comment]
No problem! You're welcome
