### ISSUE TITLE
Problems with binding context of `this` multiple times in one test suite

### ISSUE THREAD

**Issue by Mrparkers** [airbnb/enzyme#504]
Hi everyone,

I made a StackOverflow question about my issue last week, but it hasn't gotten any attention, and my team is currently being blocked by this issue, so I figured my best chance at getting some help would be here.

You can find the question I asked here: http://stackoverflow.com/questions/38379229/react-unit-tests-with-enzyme-dont-re-bind-context-of-helper-functions

In short, it appears that when using the `shallow` API, helper functions that have their context bound to an instance of a React component are never re-bound, even after calling `shallow()` again.  Multiple tests which rely on the functionality of these helper functions appear to be using the context that was bound during the execution of the first test.

Here is the example code that I used in the StackOverflow question:

```js
import React from 'react';

function renderInnerSpan() {
    const {foo} = this.props;

    if (foo) {
        return <span>Foo is truthy!</span>;
    }

    return <span>Foo is falsy!</span>;
}

export default class extends React.Component {
    render() {
        return (
            <div>
                {renderInnerSpan.call(this)}
            </div>
        );
    }    
}
```

This component renders a different message depending on the `foo` prop that was passed to it from its parent.  If `foo` is truthy, it should display "Foo is truthy!".  If `foo` is falsy, it should display "Foo is falsy!".

Here is a test suite that tests both scenarios, and results in two passing tests:

```js
import React from 'react';
import {shallow} from 'enzyme';
import {expect} from 'chai';

describe('Test Suite', () => {
    let renderedElement,
        expectedProps;

    function renderComponent() {
        const componentElement = React.createElement(Test, expectedProps);

        renderedElement = shallow(componentElement);
    }

    beforeEach(() => {
        expectedProps = {
            foo: true
        };

        renderComponent();
    });

    it('should display the correct message for truthy values', () => {
        const span = renderedElement.props().children;

        expect(span.props.children).to.equal('Foo is truthy!');
    });

    it('should display the correct message for falsy values', () => {
        expectedProps.foo = false;
        renderComponent();

        const span = renderedElement.props().children;

        expect(span.props.children).to.equal('Foo is falsy!');
    });
});
```

In this test suite, the function `renderComponent()` will use my `expectedProps` to create a new shallow-rendered component that I can perform my assertions on.  By default, I set my `expectedProps` to contain a prop `foo` that is equal to `true`.  In my second test, I set this value to `false` before calling `renderComponent()` so I can assert that the rendered message has changed.

I didn't start having problems until I made a small change to my Test component.  Since I'm using `.call()` inside of the `render()` function of my Test component, a new function is being created every time `render()` fires.  I wanted to optimize this by binding the correct context for my helper function in the constructor of my React component.  After doing this, my component now looks like this:

```js
import React from 'react';

function renderInnerSpan() {
    const {foo} = this.props;

    if (foo) {
        return <span>Foo is truthy!</span>;
    }

    return <span>Foo is falsy!</span>;
}

export default class extends React.Component {
    constructor(props) {
        super(props);

        renderInnerSpan = renderInnerSpan.bind(this);
    }

    render() {
        return (
            <div>
                {renderInnerSpan()}
            </div>
        );
    }
}
```

This component still behaves exactly the same as before.  However, my once-passing test suite is now failing at the second test:

```
AssertionError: expected 'Foo is truthy!' to equal 'Foo is falsy!'
Expected :Foo is falsy!
Actual   :Foo is truthy!
```

In an attempt to debug this, I added a `console.log(props.foo)` in the constructor of my React component.  During the execution of my failing test, this fired twice, once with the value `true`, and once with the value `false`.  This is expected, since I'm calling `renderComponent()` once in `beforeEach()`, and another time in my failing test, after changing the `foo` prop to false.

Since this log statement didn't tell me anything useful, I added a `console.log(foo)` inside of `renderInnerSpan()`, which printed `true` twice.  This was **not** expected, because the second call of `renderComponent()` used the value `false` for the `foo` prop, which was confirmed by my first `console.log()` statement.

This leads me to believe that the bound helper function `renderInnerSpan()` is created once during the execution of my entire test suite, and re-used for every subsequent test, even after multiple calls to `React.createElement()` and `shallow()`.  I've been stuck on this for a few days trying to figure out what I'm doing wrong, but at this point it seems like a bug, which is why I'm making this post now.

Please let me know if I'm doing something incorrectly or if there's a workaround that I haven't thought of.

Thanks!

**Comment by ljharb** [comment]
If you want to bind for performance, you need to attach the bound function to `this` - your approach means that two elements at the same time will call a function that's bound to the wrong receiver.

**Comment by Mrparkers** [comment]
Is there no way to accomplish this without attaching the helper function to `this`?  I'd rather not expose these helper functions to my tests if I can avoid it, and attaching them to `this` means I can do `shallow(<Test />).instance().renderInnerSpan()` (effectively making them public). Again, the second implementation described in my original post does work as intended - it's just the test suite that starts failing.

**Comment by ljharb** [comment]
There is no way in JavaScript at the moment to have per-instance privacy, so no, there's no other way.

I think your best bet would be to skip both approaches, and just make your private function an SFC itself, and use `<InnerSpan {...innerSpanProps} />`.

**Comment by Mrparkers** [comment]
Unfortunately, a SFC won't work for us, since we have a lot of React components that follow this kind of pattern (dynamically generating specific context depending on the value of certain props).  We'd need a lot of new SFC's for this.

I suppose the part I'm confused about is that my second implementation of the example component works perfectly fine - it's just my tests that start failing.  If I really needed to attach these helper functions to the component's instance for it to work correctly, why am I able to observe the correct behavior without doing so?  Would you be able to clear this up for me?

**Comment by ljharb** [comment]
It's a race condition. Your second approach ends up polluting the namespace that all `Test` components share - so you have some percentage chance that it will work perfectly, versus that it will break horribly.

If you can't use SFCs everywhere (which I highly recommend, especially over dynamism), then you should stick with the `.call` approach.

**Comment by Mrparkers** [comment]
Ah okay, that explanation cleared it up for me.  We'll look into SFCs as opposed to helper functions, that is probably a better approach.  A lot of our helper functions don't return JSX (and still rely on the correct context of `this`) so SFCs won't work in every case.

Thanks for the advice!
