### ISSUE TITLE
.simulate 'changes' still changes Checkbox input value when disabled

### ISSUE THREAD

**Issue by paulsoh** [airbnb/enzyme#505]
I am trying to test a checkbox input and noticed that even if it is disabled, if you apply `.simulate('change');` the value still changes.

Here is a summary of my test code:
```javascript

const defaultProps = {
  prompt: 'CheckboxInput prompt',
  disabled: true,
};

describe.only('<CheckboxInput>', function tests() {
  beforeEach(() => {
    this.props = _cloneDeep(defaultProps); // disabled is set as true
    this.subject = (method = shallow) =>
      method(<CheckboxInput {...this.props} />);
  });

  // Test fails
  it('does not change value state', () => {
    const wrapper = this.subject(mount);
    wrapper.setState({ value: false });
    wrapper.find('input').simulate('change');
    expect(wrapper).to.have.state('value').equal(false);
  });

  // Test fails
  it('does not call onCheckboxClick', () => {
    const spy = sinon.spy();
    const wrapper = this.subject(mount);
    wrapper.instance().onCheckboxClick = spy;
    wrapper.setState({ value: true });
    wrapper.find('input').simulate('change');
    expect(spy).to.not.have.been.called;
  });
});
```

Am I doing it wrong? Can anyone help me out with this issue? 
Thanks in advance

**Comment by ljharb** [comment]
`disabled` inputs may not be changeable and thus not fire "change" events, but if you explicitly simulate a "change" I'm not sure why the fact that it's disabled would matter - i think you can manually trigger a change event on disabled inputs with native APIs too.

**Comment by paulsoh** [comment]
@ljharb Oh, I see.. Thanks. In case of disabled buttons, I found that even if you simulate a 'click' event, it wouldn't trigger the onClick handler, so I assumed the same for Checkbox inputs.

Any idea on how I can test a disabled checkbox then? Is there any kind of `event` that would fire a 'change' event for a enabled checkbox and not for a disabled checkbox? (I noticed that 'click' didn't work on both enabled and disabled checkboxes)

**Comment by ljharb** [comment]
I'm not sure what you're trying to test - if it's got a `disabled` prop, then unless you're testing React itself, the checkbox will show up in the DOM disabled. I'd think just ensuring that the prop "disabled" is `true` would be sufficient?

**Comment by paulsoh** [comment]
Good point. I guess my test schemes weren't exactly on point. Thanks for your comment.

**Comment by qjlee** [comment]
You should not be able to do so via native API based on the [HTML spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls%3A-the-disabled-attribute)

> A form control that is disabled must prevent any click events that are queued on the user interaction task source from being dispatched on the element.
