### ISSUE TITLE
"Find" and "some" methods have not corresponding results

### ISSUE THREAD

**Issue by Jamakase** [airbnb/enzyme#510]
Have faced an issue when `find` method will find the node with some specific selector, however `some` method will respond with false for the same selector. Is it the expected behavior?
```
const wrapper = shallow(<CloudTemplateNode {...props} />);
expect(wrapper.find(TooltipCoveredArea).length).toEqual(1);//pass
expect(wrapper.some(TooltipCoveredArea)).toBeTruthy();//fail
```

**Comment by blainekasten** [comment]
I don't _think_ that is expected behavior.. Would be happy to accept a PR for a fix if you can figure it out.

**Comment by Aweary** [comment]
Thanks for the report @Jamakase , I was able to reproduce this issue. You can see the failing test case here: [Aweary/enzyme-test-repo/tree/issue-510](https://github.com/Aweary/enzyme-test-repo/tree/issue-510).

**Comment by Aweary** [comment]
@blainekasten if you look at our tests for `.some()` we only check that it works chained after a `find()` call:

```js
      const wrapper = mount(
        <div>
          <div className="foo qoo" />
          <div className="foo boo" />
          <div className="foo hoo" />
          <div id="baz" />
          <div data-qux="qux" />
        </div>
      );
      expect(wrapper.find('.foo').some('.qoo')).to.equal(true);
      expect(wrapper.find('.foo').some('.foo')).to.equal(true);
      expect(wrapper.find('.foo').some('.bar')).to.equal(false);
```

At a cursory glance, it seems like we need to be sure to clarify that `some` should be run an a wrapper containing more than one node.

**Comment by ljharb** [comment]
@Aweary I'd expect `some` on a root level wrapper to either throw, or work just as it would on found elements. I think we should add tests that ensure one of these two behaviors.

**Comment by Aweary** [comment]
>I'd expect some on a root level wrapper to either throw, or work just as it would on found elements. I think we should add tests that ensure one of these two behaviors.

I don't think it would make sense for it work on root level wrappers, as it's meant to iterate over a collection of nodes. It seems like if we just iterated over every child node or something we'd just be re-implementing  `find`.

Throwing on root level wrappers seems like the best idea to me.
