### ISSUE TITLE
Jest + Enzyme: Using expect from enzyme not from Jasmine

### ISSUE THREAD

**Issue by Frrede** [airbnb/enzyme#514]
It looks like when you use Jest and Enzyme that it takes the 'expect' function from jasmine instead of the one from Enzyme. In the example project it's also 'toBe' instead of 'to.equal' or something:
https://github.com/lelandrichardson/enzyme-example-jest/blob/master/src/__tests__/Foo-test.js

How can I get Jest to use Enzyme and not Jasmine or am I getting something wrong?

**Comment by ljharb** [comment]
@Frrede you may have to import `expect` from somewhere - jasmine creates it as a global, enzyme doesn't have it at all, and I'm not sure about jest but I'd assume you need to import it from there as well.

**Comment by blainekasten** [comment]
Jest uses enzyme under the hood. So it is supposed to use jasmine's `expect`. which is set as a global. Like @ljharb said, enzyme doesn't have an `expect` function anywhere. Are your tests not passing?

**Comment by Frrede** [comment]
I was just trying to use the shallow example from that page:
http://airbnb.io/enzyme/

There is no import of an `expect ` so I was assuming there is one on board?!
Or does that example should be run with some runner that also creates it globally?

I guess I just got a little confused by the example so thanks for your answers I will just import `expect ` (maybe from chai) or stick with jasmines.

**Comment by blainekasten** [comment]
Understandable. Maybe the docs assume too much. Every testing framework provides the `expect` as a global. So it's just assuming you use some proper testing framework, or learn the nuances enough to translate documentation code -> real code.
