### ISSUE TITLE
Problems with simulation input change

### ISSUE THREAD

**Issue by optimatex** [airbnb/enzyme#515]
I have read issues with similar problem but solutions discribed there doesn't help me. Nor 
`const event = {target: {value: 'cats'}};
 wrap.ref('email').simulate('change', event);` 
nor
`wrap.ref('email').simulate('keyDown', {keyCode: 40});`
Shall i provide full test code? it is huge

**Comment by ljharb** [comment]
A reduced test case would be ideal. A gist and/or repo may be helpful.

**Comment by demoritik** [comment]
I have removed all redundant code like validation, placeholders, classes for style
here are my component

`'use strict';
import React, { Component } from 'react';
import { observer } from 'mobx-react';

@observer
class Signup extends Component {
   render() {
      const {profile} = this.context;
      return (
         <form onSubmit={this.handleSubmit.bind(this)} className="signForm" noValidate>
            <div className="form__group">
               <input type="email" name="email" ref="email" />
            </div>
            <div className="form__group">
               <input type="password" name="password" ref="password" />
            </div>
            <div className="form__group">
               <input type="password" name="passwordConfirm" ref="passwordConfirm" />
            </div>
            <div className="form__group">
               <div className={"form__hint " +(profile.errorMessage.length > 0 ? "visible" : "hidden") }>
                  <span>{ profile.errorMessage }</span>
                  <span onClick={ () => {profile.clearErrorMessage()} } className="form__closeHint">x</span>
               </div>
               <button type="submit">Create an account</button>
            </div>
         </form>
      );
   }
   componentWillMount() {
      this.context.profile.errorMessage = '';
   }
   constructor(props) {
      super(props);
   }
   handleSubmit(event) {
      event.preventDefault();
      // Grasp Values
      const email = this.refs.email.value;
      const password = this.refs.password.value;
      const passwordConfirm = this.refs.passwordConfirm.value;
      if (email && password && passwordConfirm) {
         this.context.profile.signup(email, password);
      }
   }
}
Signup.contextTypes = {
   profile: React.PropTypes.object
};
export default Signup;`

here are my test

`'use strict';
import React from 'react';
import { shallow, mount } from 'enzyme';
import sinon from 'sinon';
import chai, { expect } from 'chai';
import Profile_Store from '../profile.store';
import Signup from '../components/signup.component';

describe('__Signup__', ()=> {
   let signup_stub, spySubmit, spyCloseHint, wrap, context, email, pssword, passwordConfirm, submit, form_hint, input__hint;

   beforeEach(() => {
      spySubmit = sinon.spy(Signup.prototype, 'handleSubmit');
      signup_stub = sinon.stub(Profile_Store.prototype, 'signup');
      spyCloseHint = sinon.spy(Profile_Store.prototype, 'clearErrorMessage');
      context = {
         profile: new Profile_Store()
      };
      wrap = mount(<Signup  />, {context});
      email = wrap.find('input[type="email"]');
      pssword = wrap.find('input[type="password"]');
      submit = wrap.find('button[type="submit"]');
      input__hint = wrap.find('.input__hint');
      form_hint = wrap.find('.form__hint');
   });
   afterEach(() => {
      spySubmit.restore();
      spyCloseHint.restore();
      signup_stub.restore();
   });

   it("contains all inputs, button and validation hints", function() {
      expect(email).to.have.length(1);
      expect(pssword).to.have.length(2);
      expect(submit).to.have.length(1);
      expect(form_hint).to.have.length(1);
      expect(input__hint).to.have.length(3);
   });

   it('form work correctly', () => {
      const event = {target: {value: 'cats'}};
      wrap.ref('email').simulate('change', event);
      console.log("input value", wrap.ref('email').prop('value'));
      wrap.simulate('submit',  { preventDefault() {} });
      chai.assert.equal(spySubmit.callCount, 1);
      sinon.assert.calledOnce(signup_stub);
   });
});`

**Comment by demoritik** [comment]
I found solution  - i don't use 
```
<input type="email" value={this.state.email} onChange={this.handleChange.bind(this)} />
```
instead i grab value from `this.refs.email.value` - so when i did click simulation it doesn't change value

**Comment by ljharb** [comment]
simulate does not faithfully simulate anything, and doesn't cause any changes to occur - it's just sugar for invoking a prop function.

I suggest avoiding it, and directly invoking props instead.
