### ISSUE TITLE
Docs: shallow#isEmpty page seems to have a bug

### ISSUE THREAD

**Issue by jmeas** [airbnb/enzyme#522]
Page affected: [shallow API](http://airbnb.io/enzyme/docs/api/shallow.html)

Click the isEmpty link and you'll be taken to [this page](http://airbnb.io/enzyme/docs/api/ShallowWrapper/isEmpty.md). There doesn't seem to be [a corresponding html page](http://airbnb.io/enzyme/docs/api/ShallowWrapper/isEmpty.html) for it, like there are for [other methods](http://airbnb.io/enzyme/docs/api/ShallowWrapper/is.html).

Didn't really look too much into what the issue is, but I noticed it while writing tests.

**Comment by ljharb** [comment]
Turns out this was missing from the table of contents in the readme (including the `mount` one).

Pages have been updated to the latest tagged version.

**Comment by jmeas** [comment]
Thanks @ljharb !
