### ISSUE TITLE
Enzyme with Fluxible - connectToStores

### ISSUE THREAD

**Issue by ccjruemenapf** [airbnb/enzyme#526]
Hi folks,
for our Project we want to use enzyme as test util. But we have problems to run tests on components with Fluxible Stores.

Simple testing component:

```
import React from 'react';
import { connectToStores } from 'fluxible-addons-react';
import LoginStore from '../../stores/LoginStore.jsx';

@connectToStores([LoginStore], (context, props) => ({
    labels: context.getStore(LoginStore).getLabels()
}))
class Test extends React.Component {

    render() {
        return (
            <div >hello</div>
        );
    }
}
export default Test;

```

Enzyme test:

```
import React from 'react';
import { expect } from 'chai';
import { shallow, mount, render } from 'enzyme';
import Test from '../../../src/components/Login/Test.jsx';

describe('test-test', () => {
    it('should render a text with hello', () => {
        const wrapper = shallow(<Test />);
        expect(wrapper.containsMatchingElement(<div>hello</div>)).to.equal(true);
    });
});
```

> > project@0.0.0 test C:\develop\project\frontend
> > mocha --require ignore-styles test/.setup.jsx test/**/*-test.jsx
> 
>   test-test
> Warning: Failed Context Types: Required context `getStore` was not specified in `storeConnector(Test)`.
>     1) should render a text with hello
> 
>   0 passing (37ms)
>   1 failing
> 
>   1) test-test should render a text with hello:
>      TypeError: context.getStore is not a function
>       at Test.jsx:6:21
>       at StoreConnector.Object.assign.getStateFromStores (C:\develop\project\frontend\node_modules\fluxible-addons-react\connectToStores.js:48:20)
>       at new StoreConnector (C:\develop\project\frontend\node_modules\fluxible-addons-react\connectToStores.js:19:27)
>       at [object Object].ReactCompositeComponentMixin.mountComponent (C:\develop\project\frontend\node_modules\react\lib\ReactCompositeComponent.js:148:18)
>       at [object Object].wrapper [as mountComponent] (C:\develop\project\frontend\node_modules\react\lib\ReactPerf.js:66:21)
>       at [object Object].ReactShallowRenderer._render (C:\develop\project\frontend\node_modules\react\lib\ReactTestUtils.js:366:14)
>       at _batchedRender (C:\develop\project\frontend\node_modules\react\lib\ReactTestUtils.js:348:12)
>       at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\develop\project\frontend\node_modules\react\lib\ReactDefaultBatchingStrategy.js:60:7)
>       at Object.batchedUpdates (C:\develop\project\frontend\node_modules\react\lib\ReactUpdates.js:94:20)
>       at [object Object].ReactShallowRenderer.render (C:\develop\project\frontend\node_modules\react\lib\ReactTestUtils.js:343:16)
>       at [object Object].render (C:\develop\project\frontend\node_modules\enzyme\build\react-compat.js:153:39)
>       at C:\develop\project\frontend\node_modules\enzyme\build\ShallowWrapper.js:90:26
>       at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\develop\project\frontend\node_modules\react\lib\Transaction.js:136:20)
>       at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\develop\project\frontend\node_modules\react\lib\ReactDefaultBatchingStrategy.js:62:19)
>       at batchedUpdates (C:\develop\project\frontend\node_modules\react\lib\ReactUpdates.js:94:20)
>       at C:\develop\project\frontend\node_modules\enzyme\build\ShallowWrapper.js:89:41
>       at withSetStateAllowed (C:\develop\project\frontend\node_modules\enzyme\build\Utils.js:196:3)
>       at new ShallowWrapper (C:\develop\project\frontend\node_modules\enzyme\build\ShallowWrapper.js:88:38)
>       at shallow (C:\develop\project\frontend\node_modules\enzyme\build\shallow.js:19:10)
>       at Context.<anonymous> (Test-test.jsx:8:25)
>       at callFn (C:\develop\project\frontend\node_modules\mocha\lib\runnable.js:326:21)
>       at Test.Runnable.run (C:\develop\project\frontend\node_modules\mocha\lib\runnable.js:319:7)
>       at Runner.runTest (C:\develop\project\frontend\node_modules\mocha\lib\runner.js:422:10)
>       at C:\develop\project\frontend\node_modules\mocha\lib\runner.js:528:12
>       at next (C:\develop\project\frontend\node_modules\mocha\lib\runner.js:342:14)
>       at C:\develop\project\frontend\node_modules\mocha\lib\runner.js:352:7
>       at next (C:\develop\project\frontend\node_modules\mocha\lib\runner.js:284:14)
>       at Immediate._onImmediate (C:\develop\project\frontend\node_modules\mocha\lib\runner.js:320:5)
> 
> 
> 
> npm ERR! Test failed.  See above for more details.
> 

I read something about problems with decorators, but with the other Fluxible - connectToStores syntax we have still the same error.

```

import React from 'react';
import { connectToStores } from 'fluxible-addons-react';
import LoginStore from '../../stores/LoginStore.jsx';

class Test extends React.Component {

    render() {
        return (
            <div >hello</div>
        );
    }
}

Test = connectToStores(Test, [LoginStore], (context, props) => ({
    labels: context.getStore(LoginStore).getLabels()
}));

export default Test;

```

**Comment by blainekasten** [comment]
I don't know much about `fluxible`, but I assume these components get rendered into some sort of `Provider` React component which likely handles setting up `context` for these components. When testing, we don't know what context should look like, so it's up to you to configure that.

Your test is going to be modified to something like this:

```js
const propContextConfig = { ... };

const wrapper = shallow(<Test />, { context: propContextConfig });
```

**Comment by jsmey** [comment]
I put together an example at https://github.com/jsmey/fluxible-unittest.  If you find it helpful, I'll write up a doc and put in a PR

**Comment by ccjruemenapf** [comment]
Hi blainekasten,
thanks for the hint to set the context by our self. Jsmey solution also contain the solution to mock the fluxible context yourself.

Hey jsmey,
your example was really really helpful for us! Thanks a lot for your solution! 
I think many other people will also find helpfully to use enzyme with fluxible.
