### ISSUE TITLE
[Feature Request Spike] wrapper#findFirst()

### ISSUE THREAD

**Issue by ianks** [airbnb/enzyme#528]
I have noticed a pattern in my code that I often tend to do something like:

```js
const img = wrapper.find('.ProfileForm__profile-img').first();
```

This works just fine; however, it is an inefficient way of finding the first item which matches a certain class. When mounting a component, it must run the predicate against the whole tree; which is unnecessary when the user only wants to find a single component. Also, it is somewhat prone to error since the semantics of `#find()` typically refer top finding the first element which matches some predicate (https://lodash.com/docs#find). I have on multiple occasions forgotten to call `#.first()` on the results of `#find()` and spent to time debugging what I did wrong.

Since it would not be possible to change the implementation of find in a backwards compatible way; I propose a new function (`ReactWrapper#findFirst()`) which finds the first item which matches some predicate. Would the community be supportive of this? I am happy to implement this method if so! Just wanted to get some feedback/spark some discussion before I got started on an implementation.

**Comment by Aweary** [comment]
My first reaction is that the current API seems fine, and increasing our API surface area to handle this wouldn't bring enough benefits. Enzyme is pretty consistent about this, as `at`, `first`, and `last` all need to be called on a *collection* of nodes.

But I haven't personally struggled with the current API so I might not be the target audience; I'd be interested in hearing more from other users or other maintainers.

**Comment by blainekasten** [comment]
I'm also on that same page. I always defer to minimizing API surface area. Helper methods usually just complicate a library: More API to ensure unit-tests, More API to potentially regress, More API for new-comers to learn and possibly be overwhelmed by.

**Comment by ianks** [comment]
@blainekasten  I do tend to agree. However, in this case, I do not know of a way to implement an efficient `findFirst()` with the current API. I would say adding `findFirst` is filling a gap in the API more more than just adding a helper function.

> More API for new-comers to learn and possibly be overwhelmed by.

`find` departs from the typical semantics of a `find` function by returning a collection of objects rather than a single object.  To me, this was the most overwhelming part of the library. Everytime I use it I have to remember: 'oh this is not a traditional find function, I have to call `.first()` on it'. And unfortunately, my brain is bad at remembering things like this, so I end up in the debugger :sad:. Providing a `findFirst` would ease the pains of `find` not being traditional because I know it will do the correct thing efficiently.

IMO, `find` is a misnomer and should be deprecated; but I understand that it is not feasible to change to implementation at this point until the next major release, if ever.

I think the entire enzyme API is very intuitive. Most of the methods are familiar functional concepts (map, filter, etc.). It was incredibly simple to pick up this library and be productive incredibly fast. Excellent work :+1:. I hope you will take my pains and experiences into consideration to make the enzyme library ever-so-slightly more awesome to work with!

**Comment by ljharb** [comment]
In this case it maps to jQuery's `find` function, not to `Array.prototype`'s, which does in fact return multiple items.

**Comment by blainekasten** [comment]
Based on the discussion so far, i'm going to close this issue as it doesn't seem like something we'll add to the API. If you feel the API would really help you, don't forget that you can always extend the prototype and add your own methods. Here's the code for you if you want to go this route :)

_untested, take with a grain of salt_

```js
import {
  ReactWrapper,
  ShallowWrapper,
} from 'enzyme';

[ReactWrapper, ShallowWrapper].forEach(Wrapper => {
  Wrapper.prototype.findFirst = function findFirst(selector) {
    return this.find(selector).first();
  }
});
```
