### ISSUE TITLE
Error: Cannot find module "react-dom"

### ISSUE THREAD

**Issue by owencorpening** [airbnb/enzyme#529]
I followed all the threads on this, but can't get it working, react-dom is certainly in my package,json, here is what I am typing:

slmbp1510:testBed owencorpening$ mocha-webpack --require setup.js --webpack-config webpack.config-testing.js src/tests/components/Comment-test.js

react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:54681
          throw e;

**Comment by Aweary** [comment]
Can you share our `package.json`?

**Comment by owencorpening** [comment]
BTW just discovered: if I comment out the guts of all the tests, still  happens, but if I also comment out the import of enzyme it stops! Here is my package.json:

`{
  "name": "react-webpack-babel",
  "version": "0.0.2",
  "description": "React Webpack Babel Starter Kit",
  "main": "''",
  "scripts": {
    "build": "webpack -p --config webpack.production.config.js --progress --profile --colors",
    "dev": "webpack-dev-server --progress --profile --colors --hot",
    "test": "mocha-webpack --growl"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/alicoding/react-webpack-babel"
  },
  "keywords": [
    "React",
    "Webpack",
    "Babel",
    "Starter",
    "template"
  ],
  "author": "Ali Al Dallal",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/alicoding/react-webpack-babel/issues"
  },
  "homepage": "https://github.com/alicoding/react-webpack-babel#readme",
  "dependencies": {
    "babel-core": "6.10.4",
    "babel-loader": "6.2.4",
    "babel-preset-es2015": "6.9.0",
    "babel-preset-react": "6.11.1",
    "bootstrap": "3.3.5",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "0.23.1",
    "file-loader": "0.9.0",
    "json-loader": "^0.5.4",
    "json5-loader": "^0.6.0",
    "jsx-loader": "^0.13.2",
    "moment": "^2.14.1",
    "node-libs-browser": "1.0.0",
    "postcss": "^5.1.1",
    "react": "^15.3",
    "react-hot-loader": "^1.3.0",
    "react-tinymce": "^0.5.1",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.13.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.7",
    "babel-eslint": "^6.1.2",
    "babel-preset-stage-0": "^6.5.0",
    "chai": "^3.5.0",
    "enzyme": "^2.4.1",
    "eslint": "^3.1.1",
    "eslint-plugin-react": "^5.2.2",
    "jsdom": "^9.4.1",
    "mocha": "^2.5.3",
    "mocha-webpack": "^0.5.0",
    "postcss-import": "^8.1.2",
    "postcss-loader": "^0.9.1",
    "precss": "^1.4.0",
    "raw-loader": "^0.5.1",
    "react-addons-test-utils": "^15",
    "react-dom": "^15.3.0",
    "source-map-support": "^0.4.2",
    "webpack-dev-server": "1.14.1"
  }
}
`

**Comment by Aweary** [comment]
Can you clear your `node_modules` and run `npm install` again to see if that helps?

**Comment by owencorpening** [comment]
I certainly did that, no help.

**Comment by Aweary** [comment]
For some reason `ReactDOM = require('react-dom')` is throwing an error for you. It should throw that error in addition to the `console.error` call, do you see what that error is?

**Comment by owencorpening** [comment]
here is the full stack trace:

slmbp1510:testBed owencorpening$ mocha-webpack --require setup.js --webpack-config webpack.config-testing.js src/tests/components/Comment-test.js

react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:40133
	      throw e;
	      ^

Error: Cannot find module "react-dom"
    at webpackMissingModule (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:40129:83)
    at /Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:40129:169
    at Object.defineProperty.value (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:40193:6)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at Object.<anonymous> (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:38931:21)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at Object.<anonymous> (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:37970:15)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at Object.<anonymous> (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:4065:26)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at Object.defineProperty.value (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:3997:22)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at Object.<anonymous> (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:53:16)
    at __webpack_require__ (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:20:30)
    at /Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:40:18
    at Object.<anonymous> (/Users/owencorpening/experiments/testBed/.tmp/mocha-webpack/Comment-test.js:43:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:469:10)
    at /usr/local/lib/node_modules/mocha-webpack/lib/cli/runner.js:55:11
    at Compiler.<anonymous> (/usr/local/lib/node_modules/mocha-webpack/lib/webpack/createCompiler.js:73:7)
    at Compiler.applyPlugins (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compiler.js:193:12)
    at Compiler.emitRecords (/usr/local/lib/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compiler.js:187:11)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/usr/local/lib/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compiler.js:267:14)
    at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/owencorpening/experiments/testBed/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/mocha-webpack/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by blainekasten** [comment]
Is this project public on github that we can look at?

**Comment by Aweary** [comment]
Also, if you look in your `node_modules` folder do you see `react-dom`?

**Comment by Duan112358** [comment]
```
vision-ui git:(master) ✗ npm test

> vision-ui@1.2.21 test /Users/duanhong/Source/Wepiao/vision-ui
> NODE_PATH=components ava

react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
/Users/duanhong/Source/Wepiao/vision-ui/node_modules/enzyme/build/react-compat.js:111
      throw e;
      ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/react/lib/ReactDOM.js:72:11)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/babel-register/lib/node.js:156:7)
    at extensions.(anonymous function) (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/react-dom/index.js:3:18)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/babel-register/lib/node.js:156:7)
    at extensions.(anonymous function) (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/duanhong/Source/Wepiao/vision-ui/node_modules/ava/lib/test-worker.js:92:3)

   1 exception


   ✖ test/Text.spec.js exited with a non-zero exit code: 1
npm ERR! Test failed.  See above for more details.
```
and my `package.json`

```
{
  "name": "vision-ui",
  "version": "1.2.21",
  "title": "Vision Design",
  "description": "UI design guideline of Wepiao",
  "keywords": [
    "design",
    "react",
    "react-component",
    "component",
    "components",
    "ui",
    "framework",
    "frontend"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/wepiaoFEI/vision-design"
  },
  "bugs": {
    "url": "https://github.com/wepiaoFEI/vision-design/issues"
  },
  "main": "lib/vision.js",
  "files": [
    "components",
    "lib"
  ],
  "license": "MIT",
  "dependencies": {
    "classnames": "~2.2.0",
    "css-animation": "1.1.x",
    "in-viewport": "^3.4.1",
    "object-assign": "~4.0.1"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "ava": "^0.16.0",
    "babel-cli": "^6.2.0",
    "babel-core": "^6.2.1",
    "babel-jest": "^6.0.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-add-module-exports": "^0.1.1",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-0": "^6.1.18",
    "babel-register": "^6.11.6",
    "busboy": "^0.2.9",
    "chalk": "^1.1.0",
    "css-loader": "^0.23.0",
    "enzyme": "^2.4.1",
    "es3ify-loader": "^0.1.0",
    "eslint": "^3.3.1",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-import-resolver-node": "^0.2.3",
    "eslint-plugin-ava": "^3.0.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.1.0",
    "eslint-plugin-react": "^6.1.2",
    "extract-text-webpack-plugin": "^0.9.1",
    "file-loader": "^0.8.5",
    "gh-pages": "^0.5.0",
    "history": "^1.17.0",
    "ignore-styles": "^4.0.0",
    "jsdom": "^9.4.2",
    "json-loader": "^0.5.1",
    "less": "~2.5.3",
    "less-loader": "^2.2.0",
    "lodash": "^3.10.0",
    "nico-jsx": "~0.7.0",
    "node-sass": "^3.4.2",
    "react": "^15.3.1",
    "react-addons-test-utils": "^15.3.1",
    "react-dom": "^15.3.1",
    "react-router": "~1.0.3",
    "react-stateless-wrapper": "~1.0.2",
    "reqwest": "~2.0.5",
    "sass-loader": "^3.1.2",
    "semver": "~5.0.3",
    "sinon": "^1.17.5",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "util-deprecate": "~1.0.1",
    "warning": "~2.1.0",
    "webpack": "^1.10.1",
    "webpack-dev-middleware": "^1.2.0"
  },
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0",
    "react-addons-shallow-compare": "^0.14.0 || ^15.0.0",
    "react-dom": "^0.14.0 || ^15.0.0"
  },
  "scripts": {
    "start": "npm run clean && nico server --watch",
    "clean": "rm -rf _site dist lib",
    "site": "npm run clean && webpack --config webpack.deploy.config.js && NODE_ENV=PRODUCTION nico build",
    "deploy": "rm -rf node_modules && npm run just-deploy",
    "just-deploy": "npm run site && node scripts/deploy.js",
    "test": "NODE_PATH=components ava",
    "pub": "sh ./scripts/publish.sh",
    "webpack": "webpack --config webpack.prod.config.js",
    "beta": "sh ./scripts/publish.sh --tag beta"
  },
  "babel": {
    "presets": [
      "es2015",
      "react",
      "stage-0"
    ],
    "plugins": [
      "add-module-exports"
    ]
  },
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register",
      "ignore-styles",
      "./test/helpers/setup"
    ],
    "files": [
      "test/**/*.js",
      "!_site/**/*",
      "!site/**/*"
    ]
  }
}
```
**error still even after `rm -rf node_modules & npm i`**

my test code
```
import { shallow, mount, render } from 'enzyme'
import React from 'react'
import { spy } from 'sinon'
import test from 'ava'
import Text from 'text'

test('output Text', t => {
    const wrapper = shallow(<Text value="something..."/>)

    t.is(wrapper.find('.Text').length, 1, 'Should has Text className at default')
})

test('output Text', t => {
    const wrapper = shallow(<Text type='tel'/>)

    t.is(wrapper.find('.Text--tel').length, 1, 'Should has Text--tel className')
    t.is(wrapper.find('input[type="tel"]').length, 1, 'Should has input type=tel')
})

test('out Text with clearable feature', t => {
    const onChange = spy()
    const wrapper = mount(<Text value="something" clearable={true} onChange={onChange}/>)    

    Text.prototype.componentDidMount.restore()
    t.is(wrapper.find('input').props().value, 'something', 'set value after componentDidMount')

})

```

**Comment by Duan112358** [comment]
sorry about that,  I got it at [enzyme-example-ava](https://github.com/mikenikles/enzyme-example-ava/blob/master/test/helpers/setup-test-env.js)

**Comment by blainekasten** [comment]
I just cloned that repo, installed modules, and ran `npm test` :\ 

![image](https://cloud.githubusercontent.com/assets/2916023/17935778/1ea79bb0-69e2-11e6-882f-5e318bca8fa7.png)

@Duan112358 maybe try to run `npm i` again?

**Comment by veeracs** [comment]
I'm getting same error...

```
/node_modules/enzyme/build/react-compat.js:111
      throw e;
      ^
Error: Cannot find module 'react-dom'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/csekharveera/Sites/app-f-components/node_modules/enzyme/build/react-compat.js:107:18
    at Object.<anonymous> (/Users/csekharveera/Sites/app-f-components/node_modules/enzyme/build/react-compat.js:187:5)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/csekharveera/Sites/app-f-components/node_modules/babel-tape-runner/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
```

**Comment by veeracs** [comment]
Here are my dependencies...

```
  "devDependencies": {
    "babel-core": "6.4.5",
    "babel-eslint": "6.1.2",
    "babel-preset-es2015": "6.9.0",
    "babel-preset-react": "6.11.1",
    "babel-preset-stage-0": "6.5.0",
    "babel-tape-runner": "2.0.1",
    "enzyme": "2.4.1",
    "eslint": "3.1.1",
    "eslint-plugin-immutable": "1.0.0",
    "eslint-plugin-import": "1.12.0",
    "eslint-plugin-react": "5.2.2",
    "faucet": "0.0.1",
    "jsdom": "9.4.1",
    "ncp": "2.0.0",
    "react": "0.14.7",
    "react-addons-test-utils": "0.14.7",
    "react-redux": "4.4.5",
    "react-responsive": "1.1.4",
    "react-router": "2.6.1",
    "redux": "3.5.2",
    "sinon": "1.17.5",
    "tape": "4.6.0",
    "webpack": "1.13.1"
  },
  "license": "SEE LICENSE IN LICENSE.md",
  "dependencies": {
    "classnames": "2.2.5",
    "js-md5": "0.4.1",
    "moment": "2.14.1",
    "react-dom": "0.14.6"
  }
```

**Comment by Aweary** [comment]
Can you see if `react-dom` exists in `node_modules`? What version of Node are you using?

**Comment by veeracs** [comment]
⚡ npm --version && node --version
2.15.3
v4.2.6

> Can you see if react-dom exists in node_modules ?
It doesn't exist.

**Comment by lazurey** [comment]
I met the same problem and fixed it by `npm uninstall react-dom` and `npm install react-dom --save-dev`.

**Comment by abdennour** [comment]
It seems that you didn't read the [README.md](https://github.com/airbnb/enzyme/blob/master/README.md) of this package where it mentions to install 2 packages : 

```
npm i --save-dev react-addons-test-utils;
npm i --save-dev react-dom;
```

**Comment by sliker** [comment]
Any update on this? Same problem here, react-dom reinstalled without success. Thanks.

```
"dependencies": {
    "appdynamics": "^4.2.2",
    "babel": "^5.8.29",
    "body-parser": "^1.13.2",
    "bootstrap-sass": "^3.3.5",
    "bundle-loader": "~0.5.4",
    "classnames": "^2.1.5",
    "cluster": "~0.7.7",
    "compression": "^1.5.0",
    "cookie-parser": "~1.4.0",
    "es6-promise": "^3.0.2",
    "express": "^4.13.0",
    "express-session": "^1.11.3",
    "formsy-react": "^0.18.1",
    "history": "^1.14.0",
    "imagesloaded": ">=3.2.0",
    "imports-loader": "~0.6.5",
    "ipaddr.js": "^1.0.4",
    "jsonfile": "^2.2.3",
    "lodash": "^3.10.1",
    "masonry-layout": ">=3.3.2",
    "moment": "^2.15.2",
    "node-cache": "^3.0.0",
    "object-assign": "^4.0.1",
    "proxy-middleware": "~0.15.0",
    "qs": "^6.1.0",
    "rc-align": "2.x",
    "rc-animate": "2.x",
    "rc-slider": "^4.0.1",
    "rc-tooltip": "~3.3.0",
    "rc-util": "~3.1.3",
    "react": "~0.14.8",
    "react-addons-css-transition-group": "^0.14.0",
    "react-day-picker": "^2.4.1",
    "react-document-title": "~2.0.1",
    "react-lazy": "~0.1.0",
    "react-mixin": "^2.0.2",
    "react-redux": "^4.4.5",
    "react-router": "~1.0.1",
    "react-slick": "^0.9.3",
    "react-visibility-sensor": "^3.1.1",
    "redux": "^3.0.2",
    "sanitizer": "^0.1.3",
    "serialize-javascript": "^1.0.0",
    "serve-favicon": "^2.3.0",
    "serve-static": "^1.10.0",
    "stats-webpack-plugin": "^0.4.2",
    "url": "~0.11.0",
    "uuid": "^3.0.1",
    "winser": "^1.0.0",
    "winston": "^2.1.1",
    "winston-daily-rotate-file": "^1.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "babel-core": "~5.8.33",
    "babel-eslint": "^6.1.2",
    "babel-loader": "~5.4.2",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-typecheck": "^2.0.1",
    "babel-runtime": "~5.8.29",
    "basscss": "^8.0.2",
    "better-npm-run": "~0.0.1",
    "bless-webpack-plugin": "^1.0.0",
    "bootstrap-loader": "^1.1.1",
    "chai": "^3.5.0",
    "chalk": "~1.1.1",
    "clean-webpack-plugin": "~0.1.5",
    "concurrently": "^2.2.0",
    "css-loader": "^0.24.0",
    "enzyme": "^2.7.0",
    "eslint": "^3.4.0",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-filenames": "^1.1.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.0",
    "eslint-plugin-react": "^6.2.0",
    "extract-text-webpack-plugin": "~1.0.1",
    "jscs": "^2.11.0",
    "jscs-loader": "~0.2.0",
    "json-loader": "~0.5.2",
    "karma": "^1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.1",
    "mocha": "^3.2.0",
    "node-sass": "^3.4.2",
    "null-loader": "^0.1.1",
    "piping": "^0.3.1",
    "postcss-cssnext": "~2.7.0",
    "postcss-loader": "^0.11.0",
    "pretty-error": "^2.0.0",
    "react-a11y": "^0.3.3",
    "react-addons-test-utils": "^0.14.8",
    "react-dom": "^0.14.8",
    "react-hot-loader": "^1.2.7",
    "react-range-slider": "^0.2.0",
    "react-tools": "^0.10.0",
    "react-transform": "~0.0.3",
    "redux-devtools": "^3.3.1",
    "rimraf": "^2.4.4",
    "sass-lint": "^1.10.0",
    "sass-loader": "^4.0.0",
    "sasslint-webpack-plugin": "^1.0.4",
    "strip-loader": "~0.1.2",
    "style-loader": "^0.13.1",
    "text-table": "~0.2.0",
    "walk": "~2.3.9",
    "webpack": "~1.13.0",
    "webpack-dev-server": "~1.15.0"
  }
```

**Comment by jackson-sandland** [comment]
I'm also experiencing this. Why would enzyme not be able to find a dependency that exists in the project?

**Comment by ljharb** [comment]
It's not enyzme finding anything - enzyme uses `require`, which unless your tooling breaks it, works in node like every other require. If webpack, for example, is breaking that, then you need to fix your config.

@sliker `react-addons-css-transition-group` needs to be the identical version as react itself; you have it allowing as low as 0.14.0, but everything else is 0.14.8. Try bumping that?

**Comment by sliker** [comment]
@ljharb that doesn't work :(
Using ReactTestUtils without enzyme works fine, problem is something with Enzyme and I could not figure out what is it.

Here is my externals, missing something?:

```
externals: {
                'cheerio': 'window',
                'react-dom': true,
                'react-dom/server': true,
                'react-addons-test-utils': true,
                'react/addons': true,
                'react/lib/ExecutionEnvironment': true,
                'react/lib/ReactContext': true
            }
```

**Comment by blainekasten** [comment]
> `ReferenceError: Can't find variable: react`

typically react is imported as `React`. Is your code looking for a lowercase version when it should be looking for an capitalized version?

**Comment by sliker** [comment]
> typically react is imported as React. Is your code looking for a lowercase version when it should be looking for an capitalized version?

import React from 'react';

**Comment by ljharb** [comment]
@sliker what's your eslintrc look like?

**Comment by sebas5384** [comment]
this error continues to happen till today

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.

**Comment by tomcrusader** [comment]
I would say it's still relevant @ljharb 
Did you not write regression tests for this issue?

package.json
```
...
"devDependencies": {
    "axios-mock-adapter": "^1.10.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.0.6",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.0",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "jest-enzyme": "^4.0.2",
    "jest-expo": "^22.0.0",
    "jest-serializer-enzyme": "^1.0.0",
    "react-native-scripts": "1.8.1",
    "react-test-renderer": "16.2.0",
    "redux-mock-store": "^1.4.0",
    "remotedev-rn-debugger": "^0.8.3"
  },
```

Error

> Exception has occurred: Error
> Error: Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'
>     at Resolver.resolveModule (/Users/user/Source/MyApp.React/node_modules/jest-resolve/build/index.js:194:17)
>     at Resolver._getVirtualMockPath (/Users/user/Source/MyApp.React/node_modules/jest-resolve/build/index.js:311:23)
>     at Resolver._getAbsolutPath (/Users/user/Source/MyApp.React/node_modules/jest-resolve/build/index.js:294:10)
>     at Resolver.getModuleID (/Users/user/Source/MyApp.React/node_modules/jest-resolve/build/index.js:267:31)
>     at Runtime._shouldMock (/Users/user/Source/MyApp.React/node_modules/jest-runtime/build/index.js:615:37)
>     at Runtime.requireModuleOrMock (/Users/user/Source/MyApp.React/node_modules/jest-runtime/build/index.js:407:14)
>     at Object.<anonymous> (/Users/user/Source/MyApp.React/node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:13:17)
>     at Runtime._execModule (/Users/user/Source/MyApp.React/node_modules/jest-runtime/build/index.js:541:13)
>     at Runtime.requireModule (/Users/user/Source/MyApp.React/node_modules/jest-runtime/build/index.js:330:14)
>     at Runtime.requireModuleOrMock (/Users/user/Source/MyApp.React/node_modules/jest-runtime/build/index.js:410:19)

**Comment by tomcrusader** [comment]
Well after reading and re-reading the relevant [documentation](http://airbnb.io/enzyme/docs/guides/jest.html) as well as googling issues with specific versions I sorted this out.

There's a lot of "moving parts" in that all NPM packages have to play nice together. I.E testing, mocking, redux and and your flavour of React. Took me a couple of days (!) to get this right.

Environment:
- OS X High Sierra
- Visual Studio Code

Project platform
- Create React Native App (CRNA)
- Expo 23.0.4
- React 16.0.0-alpha.12
- React-Native 0.50.3 

Testing framework:
- Jest ^22.0.6
- Jest-CLI ^22.0.6
- Jest-Enzyme ^4.0.2
- Jest-Expo ^22.0.0
- React-addons-test-utils ^15.6.2
- React-DOM 16.0.0-beta.5

Full package.json
Working tests for Redux actions, reducers and components (not connected).
>  "devDependencies": {
>     "axios-mock-adapter": "^1.10.0",
>     "babel": "^6.3.26",
>     "babel-eslint": "^8.2.1",
>     "babel-jest": "^22.0.6",
>     "babel-polyfill": "^6.16.0",
>     "babel-preset-airbnb": "^1.0.1",
>     "babel-preset-es2015": "^6.18.0",
>     "babel-preset-react": "^6.16.0",
>     "babel-preset-react-native": "1.9.0",
>     "eslint": "^4.15.0",
>     "eslint-config-airbnb": "^16.1.0",
>     "eslint-plugin-import": "^2.8.0",
>     "eslint-plugin-jsx-a11y": "^6.0.3",
>     "eslint-plugin-react": "^7.5.1",
>     "jest": "^22.0.6",
>     "jest-cli": "^22.0.6",
>     "jest-enzyme": "^4.0.2",
>     "jest-expo": "^22.0.0",
>     "react-addons-test-utils": "^15.6.2",
>     "react-dom": "^16.0.0-beta.5",
>     "react-native-mock": "^0.3.1",
>     "react-native-scripts": "1.8.1",
>     "react-test-renderer": "^16.0.0-alpha.12",
>     "remotedev-rn-debugger": "^0.8.3"
>   },
>   "babel": {
>     "presets": [
>       "es2015",
>       "react"
>     ]
>   },
>   "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
>   "scripts": {
>     "start": "react-native-scripts start",
>     "eject": "react-native-scripts eject",
>     "android": "react-native-scripts android",
>     "ios": "react-native-scripts ios",
>     "test": "node node_modules/jest/bin/jest.js --watch",
>     "postinstall": "remotedev-debugger --hostname localhost --port 5678 --injectserver",
>     "eslint": "./node_modules/.bin/eslint"
>   },
>   "remotedev": {
>     "hostname": "localhost",
>     "port": 5678
>   },
>   "jest": {
>     "preset": "jest-expo",
>     "transformIgnorePatterns": [
>       "node_modules/(?!(react-native|jest-resolve|expo|lodash|enzyme|prop-types|react|jest-enzyme|enzyme|jest-expo|jest-serializer-enzyme|react-native-elements|react-native-google-places-autocomplete)/)"
>     ],
>     "setupFiles": [
>       "./config/jest/globalFetch.js",
>       "./config/enzyme/index.js"
>     ]
>   },
>   "dependencies": {
>     "@expo/vector-icons": "^6.2.2",
>     "axios": "^0.17.1",
>     "expo": "^23.0.4",
>     "enzyme": "^3.3.0",
>     "enzyme-adapter-react-16": "^1.1.1",
>     "lodash": "^4.17.4",
>     "prop-types": "^15.6.0",
>     "react": "16.0.0-alpha.12",
>     "react-native": "0.50.3",
>     "react-native-elements": "^0.18.5",
>     "react-native-google-places-autocomplete": "^1.3.6",
>     "react-native-maps": "^0.18.0",
>     "react-navigation": "^1.0.0-beta.23",
>     "react-navigation-redux": "^0.1.0",
>     "react-redux": "^5.0.6",
>     "redux": "^3.7.2",
>     "redux-logger": "^3.0.6",
>     "redux-promise": "^0.5.3",
>     "redux-thunk": "^2.2.0",
>     "redux-mock-store": "^1.4.0",
>     "remote-redux-devtools": "^0.5.12",
>     "socketcluster-server": "^9.1.2"
>   }

**Comment by ljharb** [comment]
You shouldn't need to use `react-addons-test-utils` v15 with react 16; and now that react 16 is out, you should upgrade past the alpha.

**Comment by felipealfonsog** [comment]
still experiencing this on my case ...

**Comment by Navdeep-bains** [comment]
> It seems that you didn't read the [README.md](https://github.com/airbnb/enzyme/blob/master/README.md) of this package where it mentions to install 2 packages :

> ```
> npm i --save-dev react-addons-test-utils;
> npm i --save-dev react-dom;
> ```

these above commands are not in working

**Comment by amitntrivedi** [comment]
Worked for me after uninstalling and reinstalling. Followed this command` npm uninstall react-dom and npm install react-dom --save-dev.`

**Comment by luixlive** [comment]
If it helps someone, in my case I'm using [react-hot-loader](https://github.com/gaearon/react-hot-loader) with [their implementation](https://github.com/gaearon/react-hot-loader#hot-loaderreact-dom) of the React DOM module `@hot-loader/react-dom`. I fixed the issue just by adding `react-dom` to my dev dependencies :)

**Comment by akshaykumar0291** [comment]
> I met the same problem and fixed it by `npm uninstall react-dom` and `npm install react-dom --save-dev`.

Thank you, it worked for me.

**Comment by sissixiyang** [comment]
I run npm install and then the bug gone
