### ISSUE TITLE
enzyme does not appear to be a valid ES6 module

### ISSUE THREAD

**Issue by Wilfred** [airbnb/enzyme#540]
The following does not work:

```js
import enzyme from 'enzyme';
console.log(enzyme.shallow) // TypeError: Cannot read property 'shallow' of undefined
```

Whereas this does work:

```js
var enzyme = require('enzyme');
console.log(enzyme.shallow); // [Function: shallow]
```

The `import` version is compiled by babel into:

```js
var _enzyme = require('enzyme');
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var _enzyme2 = _interopRequireDefault(_enzyme);
console.log(_enzyme2.default.shallow)
```

The enzyme module does have the attribute `.__esModule`, but does not have `.default`.

**Comment by Aweary** [comment]
I think we recommend using `import { shallow } from 'enzyme'` if you're using ES6 in your tests. If you look at [our main file](https://github.com/airbnb/enzyme/blob/master/src/index.js) you can see that we don't `export default` anything at all.

**Comment by Wilfred** [comment]
I've been migrating a codebase from ES5 to ES6. Why does `var enzyme = require('enzyme');` work?

**Comment by blainekasten** [comment]
> Why does var enzyme = require('enzyme'); work?

Because it is commonjs vs es6 modules. They are not the same. when you use the import syntax, it has to differentiate between default exports and named exports, something which was not part of commonjs.

**Comment by blainekasten** [comment]
I'm going to close this as there is nothing to act upon here. Feel free to continue the discussion though!

**Comment by Wilfred** [comment]
Thanks :)

**Comment by Aweary** [comment]
@Wilfred  If you really wanted an `enzyme` object to reference for whatever reason, you could do:

```js
import * as enzyme from 'enzyme'
```

**Comment by Wilfred** [comment]
Makes sense. I'd been using [lebab](https://github.com/mohebifar/lebab) which assumes it's always safe to rewrite `var foo = require('foo');` as `import foo from 'foo'`. Mea culpa.
