### ISSUE TITLE
jsdom: Support for localStorage

### ISSUE THREAD

**Issue by umairwanclouds** [airbnb/enzyme#544]
I am assuming currently jsdom currently doesn't support localStorage as of now. Is this mentioned in the docs? I was kind of stuck at it but I have managed with a workaround that might be useful. 
So, I had this piece of code:

```
render() {
    let name = (_.get(currentUser, 'name') || _.get(localStorage, 'username'));
return();
}
```
That was causing all the other tests in that file because of the `localStorage` being undefined. I managed to fix this by adding this in my jsdom config.
```
if (!global.window.localStorage) {
  global.window.localStorage = {
    getItem() { return '{}'; },
    setItem() {}
  };
}
```
**Test**
```
it('should fetch from local storage', () => {
      const props = {
        currentUser: 'UMAIR',
        user: {
          is_key: false
        }
      };

      const spy = sinon.spy(global.window.localStorage, "setItem");
      spy(props);
      expect(spy.calledWith( {
        currentUser: 'UMAIR',
        user: {
          is_key: false
        }
      }));
      spy.restore();

      const stub = sinon.stub(global.window.localStorage, 'getItem');
      stub(props);
      expect(stub.calledWith(Object.keys(props)));
// stub.restore();
    });
```
Is this worth adding as an example? I think it might be helpful.

**Comment by Aweary** [comment]
>I am assuming currently jsdom currently doesn't support localStorage as of now. Is this mentioned in the docs?

They have an issue open for it https://github.com/tmpvar/jsdom/issues/1137

>Is this worth adding as an example? I think it might be helpful.

Thanks for the info @umairwanclouds. Since this isn't really specific to Enzyme I think it would be best to keep this out of our docs, as you'd have this issue with any code using `localStorage`, whether Enzyme is there or not 👍 

We appreciate the heads up though!

**Comment by umairwanclouds** [comment]
@Aweary All right. Thanks

**Comment by yurkagon** [comment]
I use Enzyme with jest, so I solved this problem with this package:
