### ISSUE TITLE
What is the benefit of enzyme in comparison to chai-jquery

### ISSUE THREAD

**Issue by mehrdaad** [airbnb/enzyme#546]
Till now, I've been using chai-jquery with jsdom for testing my react components.   
I'm using redux with react in my app, so if I try to test a component which has access to redux store with ``shallow`` function, I get an error ``   Invariant Violation: Could not find "store" in either the context or props
of "Connect(CommentBox)". Either wrap the root component in a <Provider>, or exp
licitly pass "store" as a prop to "Connect(CommentBox)".``
I've solved it by making a function like:  

     function enzyme(ComponentClass, props, state) {
		const componentInstance = mount(
				<Provider store={createStore(reducers, state)}>
						<ComponentClass {...props} />
				</Provider>
		);
		return componentInstance;
		// return $(ReactDOM.findDOMNode(componentInstance)); // produces HTML
    }
    
this way I can test all containers with calling ``enzyme`` instead of calling ``mount`` directly.  
Is this approach acceptable from your point of view?(I already use jsdom)  

the second problem I have is that enzyme adds some complexity to my tests without adding any value to it for example I have tested to components one with chai-jquery and the other with enzyme.  
What is the benefit of using enzyme over chai-jquery?  

    describe('CommentBox', () => {
		let component;
		let wrapper;
		beforeEach(() => {
				component = renderComponent(CommentBox);
				wrapper = enzyme(CommentBox);
                                component.find('textarea').simulate('change', 'new comment');
				wrapper.find('textarea').simulate('change', {target: {value: 'new 
		});
                 it('shows that text in the textarea', () =>
						expect(wrapper.find('textarea').props().value).to.be.equal('new comment');
						expect(component.find('textarea')).to.have.value('new comment');
				});
    }
    function renderComponent(ComponentClass, props, state) {
		const componentInstance = TestUtils.renderIntoDocument(
				<Provider store={createStore(reducers, state)}>
						<ComponentClass {...props} />
				</Provider>
		);

		return $(ReactDOM.findDOMNode(componentInstance)); // produces HTML
              }// build 'renderComponent' helper that should render a given react class
              // build 'renderComponent' helper that should render a given react class
              function enzyme(ComponentClass, props, state) {
		const componentInstance = mount(
				<Provider store={createStore(reducers, state)}>
						<ComponentClass {...props} />
				</Provider>
		);
		return componentInstance;
		// return $(ReactDOM.findDOMNode(componentInstance)); // produces HTML
    }
As you can see both do almost the same thing, except enzyme is a little bit more complex, So what is the value enzyme adds to my code?

**Comment by travisperson** [comment]
That is because you are using a plugin for chai.

If you want something similar use the [chai-enzyme](https://github.com/producthunt/chai-enzyme) plugin.

#### `value(str)`
| render | mount | shallow |
| -------|-------|-------- |
| yes    | yes   | yes     |


Assert that the given wrapper has given value:

```js
import React from 'react'
import {mount, render, shallow} from 'enzyme'

class Fixture extends React.Component {
  render () {
    return (
      <div>
        <input defaultValue='test' />
      </div>
    )
  }
}

const wrapper = mount(<Fixture />) // mount/render/shallow when applicable

expect(wrapper.find('input')).to.have.value('test')
expect(wrapper.find('input')).to.not.have.value('other')
```
https://github.com/producthunt/chai-enzyme#valuestr

**Comment by mehrdaad** [comment]
@travisperson did you read my discussion? I didn't asked for getting value of a component

**Comment by mehrdaad** [comment]
@travisperson did you read my discussion? I didn't asked for getting value of a component

**Comment by travisperson** [comment]
> Is this approach acceptable from your point of view?

No comment really here. Do whatever helps you reduce code complexity. I will say that generally you will not want to test connected components (unless you are trying to do full integration testing of your application, in which case there are plenty of strange edge cases you may have to deal with). It's better to export both the connected and non connected component in some way. You can unit test the non connect component to make sure things are working correctly.

I can go into more detail here if you want.

> What is the benefit of using enzyme over chai-jquery?

These aren't what you want to compare. I think the question you are really asking is what is the benefit of using enzyme over jQuery + React Test Utils. To answer that I think you just need to go look at what enzyme exposes to you.

http://airbnb.io/enzyme/docs/api/mount.html#reactwrapper-api

I haven't used jQuery + React Test Utils so I can't really answer this question completely, but I'd say a large part of why enzyme might be a better choice is that you have more hooks into React.

> As you can see both do almost the same thing, except enzyme is a little bit more complex, So what is the value enzyme adds to my code?

See previous comment.

**Comment by Aweary** [comment]
@travisperson is on point, it doesn't really seem that chai-jquery provides the same feature set that enzyme does. All it provides is a better assertion interface, which chai-enzyme also provides.

Enzyme actually manages the mounting/unmounting/updating for your components while providing a jQuery like API for traversal. 

>this way I can test all containers with calling enzyme instead of calling mount directly.

You can also just [pass in a context option](http://airbnb.io/enzyme/docs/api/mount.html#-mount-node-options-reactwrapper) when calling `mount`.

Since this isn't really an actionable issue with Enzyme, I'm going to close it out, but feel free to continue the discussion!
