### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by MatthewKosloski** [airbnb/enzyme#560]
There is a typo on [this page](http://airbnb.io/enzyme/docs/api/ReactWrapper/matchesElement.html).  `onst` should be `const` in the example.  I know this is not important or urgent, but I though I'd point it out.

**Comment by ljharb** [comment]
Thanks, that should be fixed :-)

**Comment by montogeek** [comment]
This is fixed in the source code https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/matchesElement.md

**Comment by ljharb** [comment]
Great, then it will be updated in the docs with the next release.
