### ISSUE TITLE
React component maxLength rendered as maxlength

### ISSUE THREAD

**Issue by terryx** [airbnb/enzyme#565]
```
const wrapper = mount(
    <InputText
      type="text"
      label="email"
      maxLength={10}
    />
  );
```

the actual result render is
 `<input type="text"  maxlength="10">`

isn't the result is `max-length` ?

**Comment by blainekasten** [comment]
Based on this fiddle, it seems that react itself renders to `maxlength`.

http://jsbin.com/tutamofeyo/edit?js,console,output

and according to mozilla docs, it is correct. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-maxlength
