### ISSUE TITLE
Simulate click on component with no-string-refs callback

### ISSUE THREAD

**Issue by gregegan** [airbnb/enzyme#566]
I am working on converting all my ref strings to ref callbacks, and trying to figure out how to handle my ref as a react component.

Since the callback returns a HTMLElement, I think I need to figure out how to render this as a react component? Can someone advise?

Previously, I could just do `wrapper.ref('hello').simulate('click');`

Code:

```
var Hello = React.createClass({
  componentDidMount: function() {
    var component = this.hello;
  },
  render() {
    return <div ref={(c) => { this.hello = c; }}>Hello, world.</div>;
  }
});
```

Test:

```
const wrapper = mount(<Hello />);
wrapper.node.hello.simulate('click');
```

Error:

```
TypeError: wrapper.node.hello.simulate is not a function
```

**Comment by ljharb** [comment]
`wrapper.instance().hello.simulate`?

**Comment by gregegan** [comment]
That is just a HTMLElement `<div>Hello, world.</div>`

**Comment by ljharb** [comment]
`simulate('click')` on that would simply fire its `onClick` handler - what are you hoping will happen?

**Comment by gregegan** [comment]
yeah that is what I am trying to accomplish, triggering the onClick handler using enzyme simulate.

You can not trigger enzyme `simulate` on the callback ref which is a HTMLElement. I assume this needs to get rendered into a ReactElement? Not sure how to go about this

**Comment by ljharb** [comment]
In this case, `wrapper` is the div itself - does `wrapper.simulate('click')` not work?

**Comment by gregegan** [comment]
I apologize, I guess i should have been more specific that I am trying to access it for a child node of the wrapper by accessing its ref.

`<div><div ref={(c) => { this.hello = c; }}>Hello, world.</div></div>`

**Comment by maxkostow** [comment]
So is there any recommendation on how to use enzyme with ref callbacks?

**Comment by syabro** [comment]
Any news here?

**Comment by billyvg** [comment]
Not a great solution, but you can do:

```javascript
wrapper.findWhere(n => n.node === wrapper.instance().hello).simulate();
```

**Comment by kangax** [comment]
I ended up adding this to a custom wrapper of enzyme wrapper (which fixes some other issues with `find` and `findWhere`) 🤦‍♂️ 

```js
wrapper.findByRef = ref => {
  const refNode = wrapper.ref(ref);
  return wrapper.findWhere(node => {
    return node.getDOMNode() === refNode;
  });
};
```

now what used to be this:
```js
wrapper.ref(nextButton).simulate('click');
```

can be written as:
```js
wrapper.findByRef(nextButton).sumulate('click');
```

...which seems pretty clean and readable.

**Comment by ughitsaaron** [comment]
this was driving me bonkers. @kangax's solution was the best I could find. thanks for the suggestion!

**Comment by Talkwondo** [comment]
It is better to put some id on it and do like this:
const wrapper = shallow(<Input redFrame={false}/>)
wrapper.find('[id="inputfocus"]').simulate('click')

**Comment by ljharb** [comment]
I definitely disagree - it's a very bad idea to put things in your code solely for the purpose of testing, ie, "test IDs" like you're suggesting.
