### ISSUE TITLE
Cannot fetch prop value on shallow render

### ISSUE THREAD

**Issue by vrinek** [airbnb/enzyme#570]
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/prop.md contains the following example: 

```jsx
const wrapper = shallow(<MyComponent foo={10} />);
expect(wrapper.prop('foo')).to.equal(10);
```

When running it though, it does not work.

## Full example used

```jsx
import React from "react";

class MyComponent extends React.Component {
    render() {
        return (
            <div>
                {this.props.foo}
            </div>
        );
    }
}

MyComponent.propTypes = {
    foo: React.PropTypes.number
};

import {mount, shallow} from 'enzyme';
import {expect} from 'chai';

describe.only('enzyme test', () => {
    let wrapper;

    context('mount', () => {
        beforeEach(() => {
            wrapper = mount(<MyComponent foo={10} />);
        });

        it('debug works fine', () => { // this works
            expect(wrapper.debug()).to.contain('10');
        });

        it('prop works fine', () => { // this works
            expect(wrapper.prop('foo')).to.equal(10);
        });
    });

    context('shallow', () => {
        beforeEach(() => {
            wrapper = shallow(<MyComponent foo={10} />);
        });

        it('debug works fine', () => { // this works
            expect(wrapper.debug()).to.contain('10');
        });

        it('prop works fine', () => { // this does not work
            expect(wrapper.prop('foo')).to.equal(10);
        });
    });
});
```

(Potentially relevant discussion: https://github.com/airbnb/enzyme/issues/331)

**Comment by ljharb** [comment]
The wrapper represents what MyComponent renders, not MyComponent itself. The div it renders doesn't have any props.

There's no value anyway in rendering something with a prop, and then immediately testing that it has that prop - you aren't validating anything except the immediately preceding line of code in your test.

**Comment by Aweary** [comment]
Yeah this is expected behavior, see https://github.com/airbnb/enzyme/issues/331#issuecomment-230578503. We should update that example though since it's incorrect. @vrinek want to open a PR with a better example?

**Comment by vrinek** [comment]
@ljharb the fact that `shallow` & `mount` behave differently is alarming to me. I would expect them to represent something on the same level. Instead it seems like one represents the actual MyComponent and the other what's inside MyComponent. For reference, my understanding on the distinction of shallow vs mount is that mount will render every child component while shallow will not.

@Aweary Yes, the documentation is indeed incorrect and that was the source of my confusion. I'll try to find the time to open a PR on it.

Updated example I have in mind...

```jsx
wrapper = shallow(<div><MyComponent foo={10} /></div>);
expect(wrapper.find('MyComponent').prop('foo')).to.equal(10);
```

...along with an explanation on why the more intuitive `shallow(<MyComponent foo={10} />)` does not provide the expected results.

**Comment by vrinek** [comment]
Seems to be fixed by https://github.com/airbnb/enzyme/pull/580. Closing...
