### ISSUE TITLE
Trigger callbacks without `on` prefix

### ISSUE THREAD

**Issue by ghost** [airbnb/enzyme#572]
Hey, how to I trigger components callbacks which have not the `on` prefix?
`onChange` I trigger with `comp.simulate(change, data)`. 
But what if the property's name is for instance `doSomething`?

**Comment by ljharb** [comment]
`simulate` is meant to be for React event handlers - `doSomething` isn't one, so it wouldn't be invoked by `simulate`.

**Comment by MoeSattler** [comment]
My custom `onSomething` do work though with enzyme. 

Now I have to use a component that has an event handler with, I suppose plain wrong, naming convention. There is nothing I can do about it. 
I still would like to test the containing component with events being triggered from the nested one.

Is there any way to do this?

**Comment by Andarist** [comment]
If you have nested components and you want to test nested event handler from the parent you need to render the parent with `mount` instead of `shallow`. Although shallow rendering is preferable way to go, test this handler in the child containing it, not in the parent.
