### ISSUE TITLE
Testing SFCs

### ISSUE THREAD

**Issue by Mrparkers** [airbnb/enzyme#574]
Hi all,

A while ago I opened #504 to get some help relating to dynamically rendering markup depending on a component's props.  I finally have some time to revisit this problem, and I am trying to take the advice given to me to use SFCs.

For a simple example, let's say I have a component that looks like this:

```jsx
function renderHelloMessage() {
    const {name} = this.props;

    if (name) {
        return <span>Hello, {name}</span>;
    }

    return <span>Hello, anonymous</span>;
}

export default class Hello extends React.Component {
    render() {
        return (
            <div className="hello">
                {renderHelloMessage.call(this)}
            </div>
        );
    }
}
```

And a test suite like this (assertions via [chai-enzyme](https://github.com/producthunt/chai-enzyme)):

```jsx
describe('Hello Component', () => {
    it('should say hello to me', () => {
        const wrapper = shallow(<Hello name="Michael" />),
            renderedSpan = wrapper.childAt(0);

        expect(renderedSpan).to.have.tagName('span');
        expect(renderedSpan).to.have.text('Hello, Michael');
    });

    it('should say hello to anonymous', () => {
        const wrapper = shallow(<Hello />),
            renderedSpan = wrapper.childAt(0);

        expect(renderedSpan).to.have.tagName('span');
        expect(renderedSpan).to.have.text('Hello, anonymous');
    });
});
```

These tests pass just fine.

What I'd like to do is turn `renderHelloMessage` in my component to a SFC like so:

```jsx
const HelloMessage = ({name}) => {
    if (name) {
        return <span>Hello, {name}</span>;
    }

    return <span>Hello, anonymous</span>;
};

export default class Hello extends React.Component {
    render() {
        return (
            <div className="hello">
                <HelloMessage {...this.props} />
            </div>
        );
    }
}
```

While this still gives me the behavior I want, the tests I wrote now start failing.  However, the strange thing is that they aren't failing on the first assertion, but the second one.  In other words, enzyme seems to understand that `renderedSpan` is a `<span>`, but fails when checking its text content.  Another strange thing is that the output from `chai-enzyme` seems to imply that my span is being rendered the way I expect it to:

> AssertionError: expected the node in <Hello /> to have text 'Hello, Michael', but it has '< />'      
>     
>      HTML:
>     
>      <span>Hello, Michael</span>

> AssertionError: expected the node in <Hello /> to have text 'Hello, anonymous', but it has '< />'      
>      
>      HTML:
>      
>      <span>Hello, anonymous</span>

Am I approaching this incorrectly?  Also, I apologize if this is a problem with `chai-enzyme` and not a problem with `enzyme` itself.

**Comment by Andarist** [comment]
Well, test if name is rendered correctly in your `HelloMessage` component and in `Hello` just that it contains `HelloMessage` component and not what `HelloMessage` would render.

First of all you need to understand the difference between `shallow` and `mount` methods. `shallow` will render only the component passed to it and not its children. So its only natural it wont contain its children text, right?

And about first 'working' example - JSX is just a sugar syntac around `React.createElement(...` and there is fundamental difference between those 2 - `renderHelloMessage.call(this)` and `React.createElement(HelloMessage, {...this.props})`. Thats why first is 'working' cause you are just calling the function right away and its included in the rendered component and with shallow rendered children with `createElement` it wont be. Thats the purpose of it.

**Comment by Mrparkers** [comment]
Yeah, I figured it had something to do with `shallow` not rendering the SFC by design, but I read a few blog posts that seemed to imply otherwise.  I probably just misinterpreted them.

Thanks for your response!
