### ISSUE TITLE
When available, wrappers should be iterable

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#577]
When `typeof Symbol === 'function' && typeof Symbol.iterator === 'symbol'` is true, perhaps ShallowWrapper and ReactWrapper instances should be iterable, so they can be destructured?

**Comment by Aweary** [comment]
I haven't used iterators a lot, what's the use case here for making our wrappers iterable? What does destructed mean in the context of iterables?

**Comment by ljharb** [comment]
`const [linkOne, linkTwo] = wrapper.find('a')`

**Comment by ljharb** [comment]
basically, providing a shortcut so that you can destructure via `.get()`

**Comment by Aweary** [comment]
I like it 👍  I'd like to give this a try to get some exposure to iterables
