### ISSUE TITLE
Incorrect shallow rendering incase of children with the same key

### ISSUE THREAD

**Issue by faalsh** [airbnb/enzyme#579]
Let's say we have a component that recieve an array and renders them in a list
```
var List = React.createClass({
  render: function() {
    return (
    <div>
    	{
      	this.props.items.map(function(item){
        	return <div className="item" key={item.id}>{item.name}</div>;
        })
      }
     </div>
    )
  }
});
```

and let's say we passed the following array:
```
var items = [{id:'1', name: 'one'},{id:'1', name: 'two'}];
```
since the id is a duplicate, React will render only one item and throws the following warning 
```
Encountered two children with the same key, `1`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by List)
    in List
```
Here is a demo for the above https://jsfiddle.net/69z2wepo/55187/

However, when using shallow to render the item and test it, the shallow function will return two items instead of 1. 

```
describe('<List>', () =>

  // this should fail because it is rendering only one item in the browser due to duplicate keys
  it('should render the correct number of items', () => {
    expect(shallow(<List  items={items} />).find('div.item').length).toBe(2)
  }),

);
```

Currently the above test case passes which is not correct. 

BTW, this is not the case for mount !!

Any advise or thought?

**Comment by faalsh** [comment]
Update on this issue, I tried to replicate the same case with ReactTestUtils and I got the same result. 

I'm not sure, but is it related ?

Here is my testcase with ReactTestUtils

```
import React from 'react'
import ReactTestUtils from 'react-addons-test-utils'

var List = React.createClass({
  render: function() {
    return (
    <div>
        {
        this.props.items.map(function(item){
            return <div className="item" key={item.id}>{item.name}</div>;
        })
      }
     </div>
    )
  }
});




describe('<List>', () => 


it('should render the correct number of items', () => {

	let items = [{id:'1', name: 'one'},{id:'1', name: 'two'}];
	let renderer = ReactTestUtils.createRenderer();
	let result= renderer.render(<List items={items} />);

	// the following testcase should fail

	expect(result.props.children.length).toBe(2)

}))
```

**Comment by Aweary** [comment]
@faalsh our `shallow` wraps `ReactTestUtils` so it's likely related, yes. Do you get the same results with `mount`?

**Comment by faalsh** [comment]
@Aweary actually mount has the correct behavior and it returns one item in the list. 

If you think this is related to ReactTestUtils not enzyme, then I should report this to React repo??

**Comment by ljharb** [comment]
That seems like the right place to report it - ReactTestUtils itself should be doing key checking.

**Comment by Aweary** [comment]
@faalsh feel free to open an issue on React and ping me on it please 😀

**Comment by faalsh** [comment]
@ljharb @Aweary Thanks for your reply. The issue was reported to React repo. https://github.com/facebook/react/issues/7664
