### ISSUE TITLE
is(':checked') not working to inspect checked state

### ISSUE THREAD

**Issue by lukebarton** [airbnb/enzyme#585]
I can't seem to check the `checked` state of a component or a child element (with one notable exception, when the element is a child and through `render`).

What is the expected behaviour?

I accept I may be doing something wrong or stupid, I'd just like to find out what it is 👍 

Note: I'm almost certain the selector is not the issue because I've also tried every other permutation of `checked`, `[checked]`, `[checked=""]` etc and none offer any more than `:checked` does - you can dig back through the commit history of [this repo](https://github.com/lukebarton/enzyme-issue).

```
let shallow = require('enzyme').shallow;
let mount = require('enzyme').mount;
let render = require('enzyme').render;
let React = require('react');

let jsdom = require('jsdom').jsdom;
global.document = jsdom('');
global.window = document.defaultView;

/** Component **/
console.log('-- Component');
el = React.createElement('input', { id: 'checked', defaultChecked: true });
console.log(shallow(el).is(':checked')); // false
console.log(mount(el).is(':checked')); // false
console.log(render(el).is(':checked')); // false

class Fixture extends React.Component {
  render() {
    return React.createElement(
      'div',
      null,
      React.createElement('input', { id: 'checked', defaultChecked: true }),
      React.createElement('input', { id: 'not', defaultChecked: false })
    );
  }
}

/** Child **/
console.log('-- Child El');
el = React.createElement(Fixture, null);
console.log(shallow(el).find('#checked').is(':checked')); // false
console.log(mount(el).find('#checked').is(':checked')); // false
console.log(render(el).find('#checked').is(':checked')); // true
```

**Comment by Aweary** [comment]
@lukebarton thanks for the report. We don't actually support these psuedo-class selectors yet. We [used to warn about this](https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L168-L177) but it looks like that warning got removed when we started support other complex selectors.

**Comment by Aweary** [comment]
`.is([checked])` doesn't work because React doesn't initially set the `checked` attribute when you use `defaultChecked` and is generally weird about setting it in general https://jsfiddle.net/9ntjopsn/

**Comment by Aweary** [comment]
@ljharb should we bring back this warning for psuedo-class selectors? Supporting them is going to be difficult as far as I can tell, and likely not worth doing until https://github.com/airbnb/enzyme/pull/458 lands.

**Comment by lukebarton** [comment]
Even with the warning about pseudo-selectors, shouldn't you carry a warning re: react in general?

**Comment by Aweary** [comment]
What do you mean by a warning regarding React in general?

**Comment by ljharb** [comment]
@Aweary yes, we should still be warning on whatever we don't support.

**Comment by lukebarton** [comment]
Well, `enzyme` provides `is('[checked]')` which doesn't work on a `react` component which has html containing `checked=""`

That's unexpected behaviour to me.

```
el.html() -> <input id="checked" checked=""/>
el.is('input[checked]') -> false
el.is('input[checked="checked"]') -> false
el.is('checked') -> false
el.is('[checked]') -> false
el.is(':checked') -> false
el.is('input[checked=""]') -> false
mount()
el.html() -> <input id="checked">
el.is('input[checked]') -> false
el.is('input[checked="checked"]') -> false
el.is('checked') -> false
el.is('[checked]') -> false
el.is(':checked') -> false
el.is('input[checked=""]') -> false
render()
el.html() ->
el.is('input[checked]') -> true
el.is('input[checked="checked"]') -> false
el.is('checked') -> false
el.is('[checked]') -> true
el.is(':checked') -> true
el.is('input[checked=""]') -> true
```

**Comment by ljharb** [comment]
That's because [in HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox), `checked=""` means "not checked". The only value value of "checked" (when there is a value present at all) is "checked", else it is ignored.

In other words, `checked` and `checked="checked"` mean checked, everything else means unchecked.

React may treat this differently (they do with many other things in jsx) but `checked=""` imo should never be used regardless.

**Comment by lukebarton** [comment]
Forgive my error.

It's clear to me now that the confusion is due to `react`'s inability to initialise the html element in the correct state when using `defaultChecked`. Thanks!
