### ISSUE TITLE
Testing propType validators

### ISSUE THREAD

**Issue by umairwanclouds** [airbnb/enzyme#588]
Normally, I do my propType validation testing as :
`it('should require a disabled bool as props', () => {
      expect(Dropdown.propTypes.disabled).to.equal(PropTypes.bool);
    });`

But it doesn't work as expected with `PropTypes.shape` or `oneOfType`
So: 
`expect(Dropdown.propTypes.value).to.eql(PropTypes.oneOfType([
        PropTypes.string,
        PropTypes.number,
        PropTypes.object
      ]).isRequired);` fails. 

` AssertionError: expected [Function: bound checkType] to equal [Function: bound checkType]`. 
Am I missing something here?

**Comment by ljharb** [comment]
I'm not sure what the benefit is of testing those - we make console warnings fail our tests, and thus any test that triggers PropType warnings fails.

`shape`, `oneOfType`, `arrayOf`, `objectOf`, and many others return new functions every time, and custom validators might as well, so this style of propType testing simply isn't feasible.

**Comment by umairwanclouds** [comment]
Yeah I agree. But if I  were to test these in any case, is there a way or would you suggest one to test these? @ljharb Thanks a lot anyways

**Comment by ljharb** [comment]
@umairwanclouds `expect(() => (<Component prop={invalidValue} />)).to.throw()`?

**Comment by umairwanclouds** [comment]
@ljharb Nice. Thanks.
