### ISSUE TITLE
simulate mouse event second button

### ISSUE THREAD

**Issue by potapovDim** [airbnb/enzyme#596]
how to simulate mouse event second button?

**Comment by blainekasten** [comment]
Or you can pass the button value using simulates second argument:

```
wrapper.simulate('click', { button: 1 })
```

I'm going to close this issue as it reports nothing wrong with enzyme itself. Feel free to keep the conversation going however!

**Comment by sanusart** [comment]
Just for reference, right mouse button triggers '[contextmenu](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu)' event, so this is also can be simulated as:

`wrapper.simulate('contextmenu');`
