### ISSUE TITLE
childAt doesn't seem to work

### ISSUE THREAD

**Issue by janejanejane** [airbnb/enzyme#599]
I might be doing something wrong in my tests but I can't seem to make the `childAt` method work. In the docs, it returns a wrapper like the `first` and `last`.

I have the following test:

![image](https://cloud.githubusercontent.com/assets/1129555/18570865/bee93e9a-7c01-11e6-803c-9571e2942651.png)

This results to the following error:

![image](https://cloud.githubusercontent.com/assets/1129555/18570881/dcd1cb02-7c01-11e6-85fd-5fa3a470b3f6.png)

**Comment by samueljseay** [comment]
@janejanejane what you actually want to call in your case is not `childAt(1)` but `at(1)`

**Comment by ljharb** [comment]
In this case, you're using `.render()` so it's using cheerio, not our ShallowWrapper/ReactWrapper. I don't believe cheerio supports `childAt` - that'd be `.children().eq(1)`
