### ISSUE TITLE
Add support for Emmet syntax by merging Eminent

### ISSUE THREAD

**Issue by nathancahill** [airbnb/enzyme#601]
I maintain an assertions library called [Eminent](https://github.com/nathancahill/eminent) that allows [Emmet](http://docs.emmet.io/) abbreviations to be used when expecting DOM to have a certain structure. For example (this currently works):

```js
import React from 'react'
import { domIs } from 'eminent'
import { shallow } from 'enzyme'

class Header extends React.Component {
    render() {
        return (
            <div id='header'>
                <div class='logo'>Company</div>
            </div>
        )
    }
}

const wrapper = shallow(<Header />)

domIs(wrapper.html(), 'div#header>div.logo{Company}')
```

This seems very much inline with Enzyme's API. What are your thoughts about merging Eminent into Enzyme? I imagine an API like:

```js
.isEmmet(abbreviation) => Boolean
.isLikeEmmet(abbreviation) => Boolean
.attrsIsEmmet(abbreviation) => Boolean
.attrsIsLikeEmmet(abbreviation) => Boolean
.contentIsEmmet(abbreviation) => Boolean
```

So the assertion line would become:

```js
expect(wrapper.isEmmet('div#header>div.logo{Company}')).toBe(true)
```

Eminent has 100% test coverage and also runs on jsdom.

**Comment by Aweary** [comment]
I think expanding the API at this point isn't what we want to do. It's a nice API, but maybe it would be better if you wrote a wrapper that extends `ShallowWrapper`/`ReactWrapper` with this functionality?

```js

function addEmmet(wrapper) {
  wrapper.prototype.isEmmet = function(selector) {
    // your code here
  }
}

**Comment by ljharb** [comment]
We definitely don't want to tightly couple to something that's not overwhelmingly a community standard.

**Comment by nathancahill** [comment]
Cool, thanks guys.
