### ISSUE TITLE
Can't access externally generated elements when using ReactWrapper

### ISSUE THREAD

**Issue by cipacda** [airbnb/enzyme#605]
I am trying to test a case where in my render() function of a component I only render a `<div/>` which is then initialized via Handsontable and assigns a class to it - exampleHotTable.

In my tests when using `ReactWrapper` if I print the output of `wrapper.debug()` it prints the exact empty `<div/>` but when I print the output of `wrapper.find('.exampleHotTable').first().html()` I get the whole generated html of the table as it should be on the page.

The most curious thing is that if I try `wrapper.find('.exampleHotTable table').first().html()` that returns null, although the above output was containing several tables.

Any suggestions on how to manage to get access to the child elements?

P.S. I have tried calling `wrapper.update()` before with no luck.

**Comment by ljharb** [comment]
I'm not sure what `handsontable` is, but it's pretty unidiomatic in React to mutate the DOM, and I'm not sure exactly how enzyme could help you here.

If you can provide a minimal failing test case, I'll be happy to reopen this.
