### ISSUE TITLE
TypeError: Attempted to wrap componentDidMount which is already wrapped

### ISSUE THREAD

**Issue by laumair** [airbnb/enzyme#609]
```
 const initialProps = setup();
      const groups = {
        fetchGroups: sinon.stub(),
        groupsStore: {
          profilesList: []
        }
      };
      const props = _.merge({}, initialProps, { groups });
      const spy = sinon.spy(Groups.prototype, 'componentDidMount');
      shallow(<Groups {...props} />);
      expect(spy.calledOnce).to.equal(true);
```

It says : `Attempted to wrap componentDidMount which is already wrapped`

I am not sure what I am missing.

**Comment by laumair** [comment]
Basically, I have a bunch of methods that I fire on `componentDidMount`: 

```
 componentDidMount() {
    this.props.fetchGroups();
    this.props.fetchProfilesForGroup();
    this.props.resetGroupsStatuses(Types.FORM, Types.BLOCK);
    this.props.fetchStats();
  }
```
I just want to check if they are called on `componentDidMount`. I was going through a recent PR and I believe shallow render supports to check react life cycle methods. Not sure what I am missing here. Thanks in advance.

**Comment by ljharb** [comment]
Are you doing that in multiple tests? I don't see you cleaning up the spy after that test.

**Comment by laumair** [comment]
Yeah my bad I figured it out. Now, I have this:
```
 const props = _.merge({}, initialProps, { groups });
      const spy = sinon.spy(Groups.prototype, 'componentDidMount');
      shallow(<Groups {...props} />);
      expect(spy.calledOnce).to.equal(true);
      spy.reset();
```
It expects `false`. Doesn't shallow render supports lifecycle methods?

**Comment by laumair** [comment]
Seems like I needed ` { lifecycleExperimental: true }` to make shallow work with `componentDidMount`. Since this is experimental, is it safe to go with this? If not what's the alternative you recommend best at this moment? @ljharb

**Comment by Aweary** [comment]
@laumair I'd recommend using `{ lifecycleExperimental: true }` if you want to test lifecycle methods with shallow wrappers! We hid it behind a flag for now to be sure it worked as expected, so we'd really appreciate it if you used it and let us know if you have issues 👍

**Comment by laumair** [comment]
@Aweary thanks for the quick response. I am already using it :) 

+1 for allowing shallow wrappers to test lifecycle methods.

**Comment by laumair** [comment]
@Aweary Is it possible to test methods other than render inside class using `shallow`? If yes, I'd really appreciate if you could point me to the docs maybe?

**Comment by laumair** [comment]
```
export default class Foo extends Component {
someFunction(){}
render() {}
}
```

What I meant to ask is if I wanted to test `someFunction()` with shallow? Is this possible?

**Comment by laumair** [comment]
`Instance` is what I needed.
