### ISSUE TITLE
jsdom mount

### ISSUE THREAD

**Issue by n7best** [airbnb/enzyme#61]
I already make travis use nvm use 4 and the test involved mount method still fail, any solution?

link to [build](https://travis-ci.org/n7best/react-weui/builds/95718088)

link to [file line](https://github.com/n7best/react-weui/blob/master/src/style/components/button/__test__/index.spec.jsx#L54)

**Comment by ljharb** [comment]
On [this line](https://github.com/n7best/react-weui/blob/master/src/style/components/button/__test__/index.spec.jsx#L60), wrapper *is* the button - perhaps you just want `wrapper.simulate('click')`?

**Comment by n7best** [comment]
Yea, everything works fine local. Trying to get t work with Travis. I want to make sure it works before adding more test.

**Comment by lelandrichardson** [comment]
@n7best is there any way you can figure out what that stacktrace is pointing to?  `undefined is not a function`...  it would be nice to know what it is thinking is undefined.

i see you're using webpack to bundle it. When you run it locally, is it also running it bundled with webpack?

**Comment by n7best** [comment]
Yea. Everything is same except for Travis I add
'''
 if (process.env.TRAVIS) {
    configs.browsers = ['Chrome_travis_ci'];
  }
'''
To karma config to make chrome work.  And all those error are from the one using mount. So I figure it's some where with Travis config where I manually insert nvm use 4 command where something still undefined

**Comment by ljharb** [comment]
@n7best you don't want a manual `nvm use` command anywhere for travis tho - https://github.com/n7best/react-weui/blob/master/.travis.yml#L12 is unnecessary due to https://github.com/n7best/react-weui/blob/master/.travis.yml#L4. (also, https://github.com/n7best/react-weui/blob/master/.travis.yml#L13 is unnecessary since travis always prints that out)

**Comment by n7best** [comment]
Ha I was just hoping that might be the problem since it doesn't work without those. So, yea those didn't help any thing. You can see (this build)[https://travis-ci.org/n7best/react-weui/builds/95716852] are without those and have same problem before I added those.

**Comment by lelandrichardson** [comment]
It would help to know what line it is throwing on and what it is trying to invoke that is undefined. I suspect it is something that webpack is doing but I'm not sure what that would be

**Comment by n7best** [comment]
@lelandrichardson I am running out of idea how to debug this thing since it's only happening with travis. I add debug info and sourcemap to this [build]https://travis-ci.org/n7best/react-weui/builds/95830951) where you can see which function is trigger the problem.

**Comment by lelandrichardson** [comment]
@n7best

**Comment by lelandrichardson** [comment]
@n7best one thing i can see is that part of the stack trace is `ReactPerf.js`. Are you running the performance utils with react?  I'm not sure if we've ever tested that. It could be causing some problems.

It seems like `component.getPublicInstance()` is what is failing, thus `getPublicInstance` does not exist.  I'm not sure why that would happen :/
