### ISSUE TITLE
Weird behavior with jest

### ISSUE THREAD

**Issue by gilbarbara** [airbnb/enzyme#611]
hey!
While testing a component with `shallow` its children stateless components sometimes display their names sometimes don't.

If I run jest in watch mode the `wrapper.text()` shows:
`<Header /><Connect(Notifications) /><Footer />`

But if I run jest normally the content is:
`< /><Connect(Component) />< />`

If I add a `displayName` to the stateless components it works in both modes but it's weird, right?

**Comment by ljharb** [comment]
@gilbarbara I'm going to close this, but if you can provide a minimal repro case, I'll be happy to reopen it and fix the issue.
