### ISSUE TITLE
Lodash dependency overwrites Window._

### ISSUE THREAD

**Issue by kushalk25** [airbnb/enzyme#612]
Enzyme uses Lodash version 4.13.1 as a dependency.
This version of Lodash overwrites Window._ which I use for underscore.
As a result, any webapp that expects Window._ to be something else will break if Enzyme is imported.

Lodash versions 4.14.0 and onward have solved this issue, but Enzyme uses the older version:
https://github.com/lodash/lodash/issues/1798

Can you please upgrade to a newer version of Lodash to resolve this issue?

**Comment by Aweary** [comment]
> Enzyme uses Lodash version 4.13.1 as a dependency.

Enzyme depends on version [`^4.15.0`](https://github.com/airbnb/enzyme/blob/master/package.json#L57). Are you using an older version of enzyme?

**Comment by kushalk25** [comment]
Yeah, it turns out that the version of Enzyme I got when I npm installed it yesterday was an old version. I installed it using the github:airbnb/enzyme and it seems up to date.

**Comment by Aweary** [comment]
Thanks for verifying! The latest version is available on npm too, so it should install from there just fine. But since this doesn't seem to be an issue with enzyme, I'm going to close this out 👍

**Comment by kushalk25** [comment]
I just reinstalled with npm and these are dependencies i got from the package.json file:
`"dependencies": {
    "cheerio": "^0.20.0",
    "is-subset": "^0.1.1",
    "lodash": "^4.13.1",
    "object-is": "^1.0.1",
    "object.assign": "^4.0.3",
    "object.values": "^1.0.3"
  },`
some of these are older versions compared to the package.json on github.

Although, the version number still says `"version": "2.4.1"` maybe the version of enzyme on npm isn't exactly up to date.

**Comment by Aweary** [comment]
@kushalk25 I just tested myself and you are totally right, looks like that dep update was made after we published `2.4.1`. I'll keep this closed since it's resolved on master, but this should be fixed in the next release then.

**Comment by kushalk25** [comment]
Great! thanks for clearing that up.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
