### ISSUE TITLE
Accessing state after calling unmount

### ISSUE THREAD

**Issue by SomniumDigital** [airbnb/enzyme#615]
I have been trying to test the state of a component before and after it has been unmounted. Whilst the state is accessible before unmounting, once I've called `component.unmount()` the `component.state()` is inaccessible.

If I log out the component object, I can see within `component.nodes[0].state` that the updated state is in there.

Here's an example of the code that I'd like to test inside my component -
```
  componentWillUnmount() {
    let myObject = this.state.myObject;

    myObject.message = [];

    this.setState({
      myObject: myObject
    });
  }
```
In my test I'd expect to be able to test the state as below
```
expect( component.state().myObject.message ).toBe( [] );
```

**Comment by ljharb** [comment]
`toBe` is `===`. You want `.toEqual`

**Comment by SomniumDigital** [comment]
I actually @ljharb agree with you there, my mistake.

However, it does not solve this issue of being able to access `state` after calling `unmount()`. You'll find you get the following error -
```
TypeError: component.getPublicInstance is not a function
```

**Comment by Aweary** [comment]
Why would you be calling `setState` in `componentWillUnmount`? When the component is unmounted the instance is destroyed along with the state. Updating it would essentially be a no-op.

**Comment by SomniumDigital** [comment]
@Aweary I had suspicions myself that this was an anti-pattern. It turns out I had a referencing issue linked to an object being used in `state`.

This is indeed an anti-pattern, and as you mention a components `state` should be destroyed up unmounting.
