### ISSUE TITLE
Find() returns no results when searching for a redux React Native component

### ISSUE THREAD

**Issue by joemckie** [airbnb/enzyme#616]
I'm currently trying to integration test a React Native component that's connected to a Redux store.

Mounting the component to works fine, but the `find` method returns no results when I try to find a component's child.

I've added a very simple test case [here](https://github.com/joemckie/enzyme-find-test-case) which attempts to search for an element in such a component.

**Comment by heurefugitive** [comment]
Ditto. I think the intent was recursive, but the `filterTree` or something is not unwrapping properly.

**Comment by joemckie** [comment]
In case anyone happens upon this, I have since found out that I was not testing correctly.

Instead of testing the redux-connected component, import the React class instead.

E.g.:

**Bad**

```js
/* MyComponent.js */
class MyComponent {
  render () {
    return <div />;
  }
}

export default connect()(MyComponent);
```
This will import the _redux connected_ component, which fails!
```js
/* MyComponent.spec.js */
import MyComponent from '../';

/* Write some tests based on the component... */
```

**Good**

```js
/* MyComponent.js */
export class MyComponent {
  render () {
    return <div />;
  }
}

export default connect()(MyComponent);
```
This will import the _React component_, which will not be connected to redux!
```js
/* MyComponent.spec.js */
import { MyComponent } from '../';

/* Write some tests based on the component... */
```

**Comment by ljharb** [comment]
You can also import the connected component and use `.dive()`.
