### ISSUE TITLE
Accessing root DOMComponent on composite component

### ISSUE THREAD

**Issue by Andarist** [airbnb/enzyme#623]
```
const Component = () => <div className="foo" />;
const wrapper = mount(Component);
```

I'm pretty sure there is a away of doing that, but I just cant figure it out. I would like to check some className, props or other things on the root dom element, but it is not a child (only nested components are) or anything else on the `wrapper`. I can use `find` to access it, but then I will couple my test to a `selector`.

Is there a way of accessint it in a more friendly way?

**Comment by ljharb** [comment]
This seems like a duplicate of #134?

**Comment by Andarist** [comment]
Ye, it probably is. Have tried to fix this, but encountered the issue mentioned in the other thread - geting duplicates by using `find`

**Comment by ljharb** [comment]
For mount, use `.childAt(0)` in v3.
