### ISSUE TITLE
Submit button not submitting: no error message

### ISSUE THREAD

**Issue by mywebmagic** [airbnb/enzyme#624]
I.m working in  a rails application in cloud9. I enter info in the fields in the Contact Us page for a test as follows: Name: test1, Email: test1@example.com, Comments: test1, clicked Submit, nothing happens and there is no error message. Need expert advice, I am stuck at this juncture: Here is my code:

contacts_controller.rb (file)

class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = "Error occured, message has not been sent."
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
        params.require(:contact).permit(:name, :email, :comments)
        end
end

new.html.erb (file)

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well"
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                    
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
                    
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class: 'form-control' %>
                </div>
                    <%= f.submit "Submit", class: "btn btn-default" %>
              <% end %>
        </div>
    </div>
</div>

routes.rb (file)

Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

application.html.erb (file)

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<% key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden= "true"></span>&times;></span></button>
      <%= value %>
    </div>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

contact.rb (file)

class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

**Comment by ljharb** [comment]
@mywebmagic nothing about your post seems related to react, or enzyme, or JS - this isn't the right venue for generic questions, let alone generic questions about Ruby or Rails.
