### ISSUE TITLE
Warning: You are manually calling a React.PropTypes in shallow or mount rendering without react-addons-test-utils installed

### ISSUE THREAD

**Issue by dbertella** [airbnb/enzyme#637]
I'm using create-react-app so I have Jest configured and I added enzyme.

I had a warning for every PropTypes in my component but I found out that installing react-addons-test-utils clear those warnings. 
I didn't have any clue from npm asking for installing it. And googoling it there wasn't anybody talking about it. [#587](https://github.com/airbnb/enzyme/issues/587) issue is realted but it isn't really clear the solution and it was about react native.

Hope this can help someone else in this situation.

**Comment by vjwilson** [comment]
@dbertella , 

Yeah, the docs aren't explicit about test-utils being a dependency, but it is mentioned in this article about Enzyme:
https://semaphoreci.com/community/tutorials/testing-react-components-with-enzyme-and-mocha

Not sure what comes with create-react-app (I think jsdom comes with Jest), but I would always install Enzyme and test-utils in tandem:

        npm install --save-dev react-addons-test-utils enzyme

**Comment by vjwilson** [comment]
@dbertella ,

Actually, I found it in the docs, but it is buried in the setup doc each specific version of React, such as [enzyme/docs/installation/react-15.md](https://github.com/airbnb/enzyme/blob/4d1517ab01c01011d7e7d1b4e9ae4201cd23268d/docs/installation/react-15.md)

**Comment by blainekasten** [comment]
Hopefully #638 will simplify this when we can get to it.

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.
