### ISSUE TITLE
Deprecate use with React 0.13

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#638]
Curious on the other maintainers thoughts on deprecating use of this library with React 0.13 moving forward. Of course the previous versions are still usable. But it seems that the [conditional requirement of `test-utils`](https://github.com/airbnb/enzyme/blob/master/src/react-compat.js#L92-L99) causes plenty of confusion.

Deprecating 0.13 would allow us to clean up some code, and reduce confusion.

Thoughts?

cc @Aweary, @nfcampos, @ljharb, @lelandrichardson

**Comment by ljharb** [comment]
I prefer to support the latest major, plus the previous 2. When v16 comes out, I'd be happy to immediately ship a breaking change that drops support for 0.13.

That said, "deprecation" is not breaking, and I think it's reasonably to support N, N-1, and N-2, but to have N - 2 be officially deprecated.

**Comment by nfcampos** [comment]
@blainekasten yep removing support for 0.13 would remove most (all?) of the conditional requires, which would be great to reduce confusion. would it actually remove all of them?

**Comment by ljharb** [comment]
Now that enzyme v3 is out, and the 0.13 stuff is in its own adapter, there's not really a reason to ever drop support for it.
