### ISSUE TITLE
.slice(begin, [end]) => Wrapper

### ISSUE THREAD

**Issue by nhardy** [airbnb/enzyme#647]
# `.slice(begin[, end]) => Wrapper`
Returns a new wrapper with a subset of the nodes of the original wrapper, according to the rules of `Array.prototype.slice`.

## Use Case

Currently:

```javascript
wrapper.find(Component).forEach((item, index) => {
  if (index < 2) return;
  // Assertions
});
```

This would be a nice addition:

```javascript
wrapper.find(Component).slice(2).forEach((item, index) => {
  // Assertions
});
```

**Comment by ljharb** [comment]
I like it. This seems straightforward, as long as it conforms to `Array#slice`.

**Comment by nhardy** [comment]
I'd be happy to submit a PR for this when I get some time this weekend.
