### ISSUE TITLE
Error if `hasClass` is called on the wrapper element

### ISSUE THREAD

**Issue by jackfranklin** [airbnb/enzyme#648]
I just lost a few minutes because I had:

```js
wrapper = mount(...)
expect(wrapper.hasClass('foo')).toEqual(true)
```

Where it of course should have been `wrapper.find('button').hasClass(...)`. Would it be possible to catch when someone is calling `hasClass` on the wrong thing and throw an error? I'm happy to do the PR if you think this is worthwhile. No worries if not!

Potentially even just adding this as a gotcha to the hasClass docs might be enough (which again, I'm happy to do).

**Comment by simonvizzini** [comment]
I've run into the same problem today and noticed that `shallow` vs `mount` behaves differently:

````javascript
wrapper = shallow(<div className="foo">bar</div>)
expect(wrapper.hasClass('foo')).toEqual(true) // ok

wrapper = mount(<div className="foo">bar</div>)
expect(wrapper.hasClass('foo')).toEqual(true) // not ok
expect(wrapper.find('div').hasClass('foo')).toEqual(true) // ok
````

**Comment by tleunen** [comment]
I'm having the same issue as @simonvizzini 

`hasClass` on a mounted wrapper doesn't work.

**Comment by tleunen** [comment]
Looks like [this commit](https://github.com/airbnb/enzyme/commit/e9ede3e2eac83bc8af7e51058616ff11acc1da3f#diff-077191fec7d029ff150ed4dfafc6a732) might fix my issue, since I was trying to check a class on a non DOM element, which was impossible with the current code in 2.6.0.

**Comment by tleunen** [comment]
Any way we can get a new release soon @lelandrichardson @ljharb ?

**Comment by ljharb** [comment]
v2.7.0 just published.

@jackfranklin please reopen if that doesn't solve your issue.

**Comment by jackfranklin** [comment]
Looks perfect, thank you so much 👍
