### ISSUE TITLE
package.json has "main" set to "build" which breaks with the latest Typescript

### ISSUE THREAD

**Issue by guncha** [airbnb/enzyme#651]
The problem is that `build` is a directory and doesn't have an extension that Typescript understands. Not sure who's right here, but using `build/index.js` fixes the issue. Please consider using that.

**Comment by ljharb** [comment]
That's a bug in TypeScript then, since an implicit "/index.js" is an essential part of node's require algorithm. Please file that on their repo, as it's a strong best practice to always omit the explicit index file (to enable easier refactoring).
