### ISSUE TITLE
What's the difference between contains and containsMatchingElement?

### ISSUE THREAD

**Issue by ZhihaoJia** [airbnb/enzyme#652]
I'm confused by the documentation for `contains` and `containsMatchingElement`. Is there a difference between the two apart from the arguments?

The doc for `containsMatchingElement` goes into some detail on what it means by "looks like". The doc for `contains` uses the same "looks like" wording, but it's not clear whether that means the same thing given that the return value, examples, and gotchas between the two are very similar.

**Comment by ljharb** [comment]
Hi Zhihao!

The difference is that `contains` checks all the props - ie, the element needs to be a 1:1 match. `foo.containsMatching(bar)` only checks that the props of `bar` exist on `foo` and are the same.

**Comment by ZhihaoJia** [comment]
Thanks for the clarification!

Any chance these details could be added to the docs? I don't know what type of language you like to use, but I could try adding it if you don't mind.

**Comment by ljharb** [comment]
A PR to improve the docs is always welcome.

**Comment by ljharb** [comment]
Closed in #663. Thanks!
