### ISSUE TITLE
Matching in container components

### ISSUE THREAD

**Issue by gravitycode** [airbnb/enzyme#653]
Hi everyone,
I have a question about how match with containers elements that have children. The children of the container doesnt matter for the test. I only need to check if the Container have a specific props.    
    
```
  const wrapper = shallow(
        <div>
          <Container className="foo" step="LOADING" visible={false}>
               <span>Hello</span>
          </Container>
      </div>

  );
 expect(wrapper.containsMatchingElement(<Container step="LOADING"></Container>)).toBe(true);
```

Its possible to test it?
Thank you :)

**Comment by ljharb** [comment]
@gravitycode `shallow` renders the *output of the render method* of `Container` - so unless Container renders a Container somewhere, wrapper wouldn't be, nor contain, a Container.

If you want to check the props of the div container that Container renders, `expect(wrapper.props()).to.eql({ … })` should do it

**Comment by ljharb** [comment]
based on your edit, you want `expect(wrapper.find(Container).props()).to.contain.keys({ step: 'LOADING' })` etc

**Comment by gravitycode** [comment]
sorry @ljharb i forget the root div container. And with the change I made now, its possible? Thank you!

**Comment by ljharb** [comment]
yes, with https://github.com/airbnb/enzyme/issues/653#issuecomment-258368414

**Comment by gravitycode** [comment]
Excellent @ljharb :)!

**Comment by gravitycode** [comment]
I found the plugin for chai 'chai-subset' to compare with props objects (key-value is compared)
https://github.com/debitoor/chai-subset

**Comment by ljharb** [comment]
chai has that built in already, with `.to.contain.all.keys(obj)`
