### ISSUE TITLE
`equals` should skip null and undefined props

### ISSUE THREAD

**Issue by vadimdemedes** [airbnb/enzyme#656]
This is a continuation of #151, which fixed the skipping of *nodes*, but the same issue exists for *props*.

Here's an example to demonstrate the problem:

```jsx
import React from 'react';
import {shallow} from 'enzyme';

const Box = ({className}) => (
  <div className={className}/>
);

shallow(<Box/>).equals(<div/>); //=> false
shallow(<Box/>).equals(<div className={undefined}/>); //=> true
shallow(<Box className="awesome"/>).equals(<div className="awesome"/>); //=> true
```

`nodeEqual()` fails, because it expects `className={undefined}` property in the other component (`<div/>`). This is happening here https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L94. Tested using the latest enzyme available on npm (`2.5.1`).

I think this case should be covered in enzyme by ignoring `null` and `undefined` props, which is what React does too. If everyone agrees, I can submit a PR to fix it ;)

**Comment by ljharb** [comment]
That does seem reasonable, but let's get thoughts from more collabs before making the PR.

**Comment by Aweary** [comment]
👍 sounds good to me. If React ignores it, we should too.
