### ISSUE TITLE
Jest support documentation

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#66]
In order for this to work with jest, jest needs to know about some libraries specifically not to be mocked. It'd be nice if you could document this somewhere. This is specifically what I had to do to get tests running:

`/package.json`
```json
{
  "jest": {
    "unmockedModulePathPatterns": [
      "enzyme",
      "cheerio",
      "htmlparser2",
      "sinon",
      "..."
    ]
  }
}
```

This is an exhaustive list of needed items
- [ ] enzyme
- [ ] cheerio
- [ ] htmlparser2
- [ ] sinon
- [ ] underscore
- [ ] lodash  `dep of cheerio, needed for render method`
- [ ] domhandler `dep of htmlparser2, from cheerio`
- [ ] object.assign
- [ ] define-properties
- [ ] function-bind
- [ ] object-keys

**Comment by lelandrichardson** [comment]
@blainekasten this is great. I have a PR out that i'm going to be adding some documentation stuff to. There will end up being a "guides" section, where there is a guide for working with various different environments (of which, jest will be one). This will be very helpful to add to that!

**Comment by blainekasten** [comment]
For reference: recently, I needed to add `"underscore"` to the unmocked paths also.

**Comment by lelandrichardson** [comment]
This is good. I'll get something like this added into a guide for using enzyme with jest

**Comment by blainekasten** [comment]
Also for reference, this list is primarily for npm3 due to https://github.com/facebook/jest/issues/554.

When using with npm2 and when that is fixed, it should be fine to just use 
```json
{
  "jest": {
    "unmockedModulePathPatterns": [
      "enzyme"
    ]
  }
}
