### ISSUE TITLE
shallow-rendering component with `getChildContext` should work

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#664]
```jsx
class Foo extends React.Component {
  getChildContext() {
    return { a: 1 };
  }
  render() {
    return <Bar b={this.context.b} />;
  }
}
Foo.contextTypes = {
  b: React.PropTypes.number,
};

class Bar extends React.Component {
  render() {
    return <div />;
  }
}
Bar.contextTypes = {
  a: React.PropTypes.number,
  b: React.PropTypes.number,
};
```

```jsx
const wrapper = shallow(<Foo />, { context: { b: 2 });

expect(wrapper).props()).to.eql({ b: 2 }); // works
// .props() provides me with the first argument that will be passed to `Bar`'s constructor

expect(wrapper).context()).to.eql({ a: 1, b: 2 }); // does not work
// I expect .context() to provide me with the second argument that will be passed to `Bar`'s constructor
```

**Comment by jordann-nulogy** [comment]
I'll take a try at this one

**Comment by jordann-nulogy** [comment]
I took a stab at this but I'm not sure it's a real bug. @ljharb why would you expect context to have both `a` and `b` populated?

https://jsfiddle.net/reactjs/69z2wepo/

This fiddle (I believe) represents what you are trying to render in an actual react environment and the behaviour exhibited by enzyme appears to be correct.

**Comment by ljharb** [comment]
@jordann-nulogy React only provides context keys for which there are `contextTypes`, and yes, what React is doing is correct. However, enzyme will not in fact replicate this when shallow-rendering `ContextComponent` with a context of `{ b: 2 }` and then attempting to determine the context of the `ChildContextComponent` element (or, to shallow-render it, and have it inherit the context of `{ a: 1, b: 2 }`)

**Comment by ljharb** [comment]
@lelandrichardson can we make sure this works with your rewrite?

**Comment by borela** [comment]
Any updates on this one?
