### ISSUE TITLE
Difference in traversing ReactWrappers and ShallowWrappers

### ISSUE THREAD

**Issue by pvienneau** [airbnb/enzyme#674]
Provided the following tests, where I'm traversing to the Table component from both _mount()_ and _shallow()_ functions:

```
    let tableStructure = (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHeaderColumn>ID</TableHeaderColumn>
              <TableHeaderColumn>Name</TableHeaderColumn>
              <TableHeaderColumn>Status</TableHeaderColumn>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableRowColumn>1</TableRowColumn>
              <TableRowColumn>John Smith</TableRowColumn>
              <TableRowColumn>Employed</TableRowColumn>
            </TableRow>
          </TableBody>
      </Table>
    );

    it('should be able to navigate to all components on MOUNT', () => {
        const wrapper = mount(tableStructure);
        const table = wrapper.find(Table);
        const tableSub = table.find(Table);

        expect(table.length).toBe(1);
        expect(tableSub.length).toBe(1);
    });

    it('should be able to navigate to all components on SHALLOW', () => {
        const wrapper = shallow(tableStructure);
        const table = wrapper.find(Table);

        expect(wrapper.length).toBe(1);
        expect(table.length).toBe(0);
    });
```

In the first test, with the `ReactWrapper`, I'm able to continuously traverse to the `Table` component through itself, whereas from the `ShallowWrapper` I'm not able to traverse to the `Table`, which to me is understandable since I'm already pointing to that component.

Can anyone shed a little light for me as to why the `ReactWrapper` traversal includes oneself in its search?

**Comment by Aweary** [comment]
@pvienneau the shallow renderer will start rendering with the render output of the top level component, so it doesn't actually contain a `Table` element.

For example, if your `Table` component renders:

```jsx
<table className="table">
  {this.props.children}
</table>
```

Your wrapper will actually contain:

```jsx
<table className="table">
  <TableHeader>
    // ...
  </TableHeader>
  <TableBody>
    // ...
  </TableBody> 
</table>
```

You can verify this by logging the output of `wrapper.debug()` which should return something similar. `mount` does what you'd expect, which is actually mount every component.
