### ISSUE TITLE
Simulate keydown

### ISSUE THREAD

**Issue by Simproduction** [airbnb/enzyme#675]
Hi I try simulate keydown on draft-js Editor I want 

```
it('Should be called editNote and selectNote', () => {
    _component.find('.DraftEditor-root').simulate('keyDown', {
      which: 83,
      ctrlKey: true
    })
    expect(editNote.calledOnce).to.be.equal(true)
    expect(selectNote.calledOnce).to.be.equal(true)
  })
```

I try diferent level select in editor and different keyDown but not working same in other part of kode I try with keyDown simulate enter Key but same without effect could you help me? 

Component: 

```
   <Editor ref="editor" 
    editorState={editorState} 
    onChange={this.onChange}
    onTab={this.onTab} 
    keyBindingFn= {this.keyBindingFn}
    handleKeyCommand={this.handleKeyCommand}/> 
```

HANDLING FOR KEYPRESS
```
  keyBindingFn (e) {
      const { editorState } = this.state
      const { hasCommandModifier }= KeyBindingUtil
      let command
      if (e.keyCode === 83 /* `S` key */ && hasCommandModifier(e)) {
        return 'myeditor-save'
      } 

      if (CodeUtils.hasSelectionInBlock(editorState)) {
          command = CodeUtils.getKeyBinding(e)
      }
      if (command) {
          return command
      }

      return getDefaultKeyBinding(e)
  }

 handleKeyCommand (command) {
      let newState
      const { editorState } = this.state

      if (command === 'myeditor-save') {
        const note = Object.assign({}, this.props.note, {
          desc: JSON.stringify(convertToRaw(editorState.getCurrentContent()))
        })
        this.props.editNote(note).then((data) => {
          this.props.selectNote(note)
        })
      } 

      if (CodeUtils.hasSelectionInBlock(editorState)) {
          newState = CodeUtils.handleKeyCommand(editorState, command)
      }

      if (!newState) {
          newState = RichUtils.handleKeyCommand(editorState, command)
      }

      if (newState) {
          this.onChange(newState);
          return true
      }
      return false
  }
```

Thank you

**Comment by jordann-nulogy** [comment]
The way that simulate is written appears to expect that `onKeyDown` is mapped to the component you are trying to simulate an event on.

E.g. `simulate('change')` will call `Component.onChange` if it's defined. Or, `simulate('keyDown')` will call `Component.onKeyDown`

Unfortunately, I don't think `simulate` will work for your use case

**Comment by kenju** [comment]
@jordann-nulogy 
@Simproduction 

FYI
I have faced with the same problem with you, and found a better solution to test Keyboard Event simulation for draft.js. Have a look at ->
https://github.com/facebook/draft-js/issues/325#issuecomment-300372428

**Comment by baldwmic** [comment]
@kenju your suggestion was helpful, thank you for leaving the note!

**Comment by kenju** [comment]
@Simproduction Does [my comment](https://github.com/airbnb/enzyme/issues/675#issuecomment-300372582) helps your case?

FYI @ljharb I think you can close this issue 😉
