### ISSUE TITLE
Testing scrollIntoView

### ISSUE THREAD

**Issue by laumair** [airbnb/enzyme#676]
```
 scrollToAnchor(props) {
    const anchorName = props.location.hash;
    if (anchorName) {
      browserHistory.replace(`/url/${props.params.id}`);
      setTimeout(() => {
        const anchorElement = document.getElementById(anchorName);
        if (anchorElement) {
          anchorElement.scrollIntoView();
        }
      }, 0);
    }
  }
```
I am spying on `scrollIntoView` but haven't been lucky at all. 

```
it('should call scrollIntoView native method on element', () => {
          const props = getDefaultProps(); // Defined globally
          const wrapper = mount(<Abstractions {...props} />);
          const element = wrapper.findWhere(n => n.props().id === 'pods');
          sinon.spy(element, 'scrollIntoView');

          const instance = wrapper.instance();
          instance.scrollToAnchor({
            location: {
              hash: '#map'
            },
            params: {
              id: '1'
            }
          });

          expect(element.scrollIntoView).to.have.been.called;
        });
```
Am I missing something here or there's some other mechanism that we need to adapt for testing the native methods?

**Comment by ljharb** [comment]
`findWhere` doesn't find a dom node, it finds a ReactWrapper-wrapped element.

Specifically. you're using `document.getElementById` instead of ref callbacks to locate a DOM node in your implementation; I think that's going to make it harder to test.

**Comment by Aweary** [comment]
You could spy on `getElementById` here and return a mock element that you can then add another spy for `scrollIntoView` on. Using ref callbacks would definitely be a better option if this component is rendering the element you're scrolling to.

**Comment by ljharb** [comment]
@laumair a ref callback provides that.

**Comment by jangeroo** [comment]
> You could spy on `getElementById` here and return a mock element that you can then add another spy for `scrollIntoView` on. Using ref callbacks would definitely be a better option if this component is rendering the element you're scrolling to.


This solution helped me get this working for testing that a function `scrollTo` calls `scrollIntoView`:
```javascript
...
const scrollIntoViewSpy = jest.fn();
jest.spyOn(global.document, 'getElementsByClassName')
  .mockImplementation(() => [{ scrollIntoView: scrollIntoViewSpy }]);

instance.scrollTo(selected);
expect(scrollIntoViewSpy).toHaveBeenCalledTimes(1);
```
