### ISSUE TITLE
enable `lifecycleExperimental` by default?

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#678]
https://github.com/airbnb/enzyme/issues/34#issuecomment-260141576 reminded me that perhaps for v3, we should enable this by default.

Any objections? @Aweary @blainekasten @nfcampos @lelandrichardson

**Comment by Aweary** [comment]
Haha, I was just about to open this same issue. We haven't heard any reports of issues with it, though it's hard to say if that's due to the implementation's correctness or lack of awareness.

Either way, I think it's a good idea to enable it by default with the next major release.

**Comment by nfcampos** [comment]
I agree we should enable it by default in the next major. (do we keep the flag?)
(I've added a couple more test cases for this that I felt were missing in https://github.com/airbnb/enzyme/pull/681)

**Comment by laumair** [comment]
:+1: I've been using it extensively for over a month now I presume and it works great. I can maybe provide some examples as well as I've used it in many places. 
However, even if used with `mount` it just work. I think it should only work with `shallow` and should atleast display some sort of a warning when used with `mount` @ljharb @Aweary

**Comment by nfcampos** [comment]
@laumair thanks for telling us your experience with it. glad to see it's been useful! 
I agree that we should validate the options object and throw or warn when unknown keys are passed in.

**Comment by laumair** [comment]
@nfcampos Thank YOU for this awesome library. Yeah validation would be much helpful if added.

**Comment by ljharb** [comment]
@nfcampos i'd say we maybe rename the flag to `deprecatedDisableLifecycleMethods` or something, and keep it, but remove that in the next major.

**Comment by jwbay** [comment]
I've also used this for months and seen no problems. I can work on a PR to make this the default.

@ljharb From your last comment, it sounds like you want to add a flag to *suppress* the lifecycle methods? A rename with the same functionality seems like it would be `deprecatedEnableLifecycleMethods`?

**Comment by ljharb** [comment]
Yes, I think that would be the safe approach.

In fact, I'd prefer one semver-minor PR that adds "deprecatedDisableLifecycleMethods" (that right now is a no-op) and to publish that, and then later, a semver-major PR that changes the default behavior to enable the lifecycle methods and removes `lifecycleExperimental`, but respects the explicit disable flag as well.

**Comment by jwbay** [comment]
Opened #7912 with some questions.

**Comment by ljharb** [comment]
Done in #1140.
