### ISSUE TITLE
Error: Cannot find module 'react-dom/lib/ReactTestUtils'

### ISSUE THREAD

**Issue by tomoueda** [airbnb/enzyme#684]
I'm getting this error during a test run:

Error: Cannot find module 'react-dom/lib/ReactTestUtils',

I'm also getting this message:

react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation

I installed the required dependencies, I'm still getting the same error.

This only started happening today randomly.

**Comment by ljharb** [comment]
React 15.4 broke some things.

If you downgrade to 15.3, things should continue to work.

I'll look into fixing the underlying issue.

**Comment by tomoueda** [comment]
Were on version 14.8, the new react version shouldn't have affected our project.

**Comment by ljharb** [comment]
If you run `npm ls`, are there no copies of React 15 in your dep tree?

**Comment by ljharb** [comment]
Hmm - I can't reproduce this locally with our tests.

Can you provide your `package.json` (the deps and dev deps) as well as `npm ls` output?

**Comment by tomoueda** [comment]
I'm not at a liberty to provide, but does node version matter? We're running node0.10, and npm3

**Comment by Aweary** [comment]
@tomoueda can you share the stack trace for the `react-dom/lib/ReactTestUtils` error?

**Comment by Aweary** [comment]
It seems most likely that you are somehow depending on the latest version of React, or at least of `react-addons-test-utils`. Your issue coincides with the release timing, and we've seen similar reports with the same error message (https://github.com/facebook/react/issues/8314) reported on the React repo.

**Comment by tomoueda** [comment]
Hmm yeah thats probably it, I'll try to find out where I refer to the latest version. Thanks.

**Comment by ljharb** [comment]
@tomoueda also node 0.10 is officially EOL'd, you really need to get on 4 or 6 ASAP.

**Comment by tomoueda** [comment]
Thanks,

I figured out my issue:

I had this dependency in my package:

"react-addons-test-utils": "^15.2.0"

this auto upgraded to 15.4, reducing the version of react-addons-test-utils, fixed my problem.

Thanks, everyone.

**Comment by DDKnoll** [comment]
Also had this issue when I had "react-addons-test-utils": "0.14.0" installed.  There was a dependency conflict with the jsx-chai package. Updating to "react-addons-test-utils": "0.14.8" resolved the dependency conflict.

**Comment by danielehrlich** [comment]
I was on "react-addons-test-utils": "^15.3.2" and I moved to "0.14.8" per a couple of people's suggestion here and it fixed the issue immediately with Travis-CI.

**Comment by ezmiller** [comment]
I was having this problem and downgraded to 15.3.0, which solved the problem for now.

**Comment by rajan-ls** [comment]
Simple removing `   "react-addons-test-utils": "^15.4.0",` from my package.json fixed this issue for me. Hopefully this helps someone elsen

**Comment by gastikirs** [comment]
Downgraded `react-addons-test-utils` to ^0.14.8 and fixed the problem!

**Comment by Vanuan** [comment]
So what's the solution if I'm on `15.4`?

**Comment by ljharb** [comment]
It's not about any particular version, it's that all of the core react-* packages in `npm ls` must be the same version.

**Comment by jackson-sandland** [comment]
One of my core-react dependencies was set to a different version in the package.json. When I ran npm test - the shell complained that react was not installed. After making sure the core react-* packages were in sync - problem solved. Thanks!

**Comment by eldyvoon** [comment]
@ljharb what does that means? How to solve this problem? I tried to downgrade react-addons-test-utils still couldn't get my problem solved.

**Comment by ljharb** [comment]
@eldyvoon what's your package.json look like?

**Comment by balinskia** [comment]
I think it is fixed in: react-addons-test-utils@15.5.1

**Comment by robin22d** [comment]
Im getting this error. Here is my package.json: 


{
  "name": "list",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "tape -r babel-register ./__test__/*.js | tap-spec",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "extend-tape": "^1.2.0",
    "react-addons-test-utils": "^15.6.2",
    "tap-spec": "^4.1.1",
    "tape": "^4.8.0",
    "tape-jsx-equals": "^1.0.0"
  },
  "babel": {
    "presets": ["react", "es2015"]
  }
}

**Comment by ljharb** [comment]
@robin22d you have react 16, but react-addons-test-utils 15. Remove the react-addons-test-utils line entirely.

**Comment by robin22d** [comment]
Thank you it works now. Is it build into react 16 now?

**Comment by ljharb** [comment]
@robin22d It's built into the react 16 enzyme adapter (altho neither your package.json nor react-scripts includes enzyme, so i'm not sure how this repo is relevant to you)

**Comment by kerrermanisNL** [comment]
For anyone who ran into this thread but is not actually using enzyme. If you find you can't access `react-addons-test-utils` and you've upgraded from below react (I'm thinking) 15.4 make sure you're importing the `TestUtils` class from `react-dom/test-utils`. 

`react-addons-test-utils` no longer exists and has been moved to `react-dom`. Took me a while to figure out.

**Comment by ljharb** [comment]
The goal with enzyme, however, is not to need the test utils directly at all :-)

**Comment by kerrermanisNL** [comment]
@ljharb definitely good to know! For me however I rolled into a (big) project that already uses it and needed to be upgraded to react 16. Searching for a solution to the missing testutils, this came up as the first answer on Google. So I though I'd provide some more information for people following that same route. In any case, thanks for the heads-up!

**Comment by gazatem** [comment]
You need to install react-dom/test-utils instead of react-addons-test-utils

**Comment by zhoulujun** [comment]
https://www.zhoulujun.cn/html/tools/webpack/2016_0217_6459.html
  "react": "^16.7.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.7.0",
react-dom 16 根本就没有lib/ReactTestUtils 这玩意儿。
于是修改，react-addons-test-utils index 文件,坑还是未填好
//module.exports = require('react-dom/lib/ReactTestUtils');
module.exports = require('react-dom/test-utils');
最好还是降级到15.x ，期待官方修复！
