### ISSUE TITLE
 how newly added tags  to use the enzyme API?

### ISSUE THREAD

**Issue by SansaZhang** [airbnb/enzyme#687]
in my project , simulate('click')  will add tags to the html. 
but the newly added tags are not in my wrapper, How these newly tags to use the enzyme API?

**Comment by blainekasten** [comment]
Hey @SansaZhang, you'll have to provide a bit more information than that. Component, test, etc. There is nothing within enzyme that would be adding new tags into your rendered output. There would have to be something within your code that would be injecting it unexpectedly.

**Comment by SansaZhang** [comment]
Thanks for your reply! 
for example, click a <button>, will add a div , $(body).append('<div></div>') ,this div is not in my wrapper , how to simulate click to this div!

**Comment by SansaZhang** [comment]
sorry~
for example, click a , will add a `div` `, $(body).append('<div></div>')` ,this `div` is not in my wrapper , how to simulate click to this `div!`

**Comment by SansaZhang** [comment]
Thanks for your reply!
for example, click a `div `, will add a `div ,` `$(body).append('<div></div>')` ,this `div `is not in my wrapper , how to simulate click to this `div`!

**Comment by ljharb** [comment]
@SansaZhang idiomatic React doesn't modify the DOM outside the component container, and uses props and state *only* to change what renders. If your code appends things to the body, you have to have a DOM available, and do all the mocking yourself.
