### ISSUE TITLE
Cannot run tests with React 15.4.0

### ISSUE THREAD

**Issue by AdamYahid** [airbnb/enzyme#688]
First off, thanks for this great library.

After upgrading to react 15.4.0, I cannot run tests due to import from react/lib/ReactTestUtils in enzyme/build/react-compat.js:132

as mentioned in their [documentation](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html)
this is no longer supported.

Reverting to 15.3.2 solved the issue for now.

Thanks again,
Adam

**Comment by ljharb** [comment]
@AdamYahid what version of enzyme are you using? We import from the separate package `react-addons-test-utils` for 0.14 and v15 [here](https://github.com/airbnb/enzyme/blob/master/src/react-compat.js#L93-L108).

**Comment by ljharb** [comment]
Actually this seems to have been in every version of enzyme, so I'm not sure why this error is occurring.

**Comment by AdamYahid** [comment]
@ljharb I missed updating react-addons-test-utils as well, updating to 15.4.0 solved the problem

I am now running all tests as expected with
enzyme 2.6.0
react, react-dom, react-addons-test-utils 15.4.0

Thank you very much for your help
