### ISSUE TITLE
Attribute selector doesn't work on attributes that have numbers in them

### ISSUE THREAD

**Issue by raduanastases** [airbnb/enzyme#693]
In [ShallowTraversal.js](https://github.com/airbnb/enzyme/blob/master/src/ShallowTraversal.js#L113) the selector for the attribute doesn't work on attributes that have numbers in them.
`const propKey = selector.split(/\[([a-zA-Z-]*?)(=|])/)[1];`

Instead, it should be:
`const propKey = selector.split(/\[([a-zA-Z-0-9-]*?)(=|])/)[1];`

**Comment by ljharb** [comment]
@raduanastases it'd be great if you could file a PR with a test case!

**Comment by ljharb** [comment]
(also, please note that attributes that start with numbers are invalid)

**Comment by raduanastases** [comment]
sure, I'll get to it as soon as possible.

**Comment by jsmey** [comment]
I made this change and added a test https://github.com/airbnb/enzyme/pull/700

**Comment by ljharb** [comment]
Closed in #1086
