### ISSUE TITLE
.children() are empty when a component doesn't wrap its children

### ISSUE THREAD

**Issue by hon2a** [airbnb/enzyme#696]
I have a `Localize` component that is used with the app as its single child and provides `context` to it. The relevant part is:

```javascript
class Localize extends React.Component {
  render() {
    return React.Children.only(this.props.children);
  }
}
```

When I `mount` this component and try to get `.children()`, I get nothing.

```javascript
const children = mount(React.createElement(Localize, {}, childElement)).children();
// children.length === 0
```

I can get the wrapper for the child component if I do this:

```javascript
const child = mount(React.createElement(Localize, {}, childElement))
  .find(childElement.type)
  .at(0);
```

**Comment by ljharb** [comment]
When you say `someComponent` - `children` need to be Elements, not Components - can you share the code that initializes `someComponent`?

**Comment by hon2a** [comment]
@ljharb Sorry, I see how that is misleading. I updated the description to clearly describe it as `Element`. It can be any `Element`, e.g. `<div/>` or `<MyComponent ... />` where `MyComponent` extends `React.Component`.

**Comment by ljharb** [comment]
Does this same thing happen with `shallow`, or only with `mount`?

**Comment by hon2a** [comment]
I've just tested it with

```javascript
    class Wrapper extends React.Component {
      render() {
        return React.Children.only(this.props.children);
      }
    }

    const wrapper = shallow(
      React.createElement(Wrapper, {}, React.createElement('div'))
    );

    expect(wrapper.children().length).toBe(1);
```

and it fails too (expects 1, gets 0). Just like when I use `mount` in place of `shallow`.

**Comment by jantorestolsvik** [comment]
Does anyone have an update on this or any idea how we can fix it?

**Comment by ljharb** [comment]
Related to #977?

**Comment by hon2a** [comment]
@ljharb Yeah, looks #977 is a duplicate of this, though with a tad more extensive description.

**Comment by c-emil** [comment]
I have very similar issue, also related to if component doesn't have a wrapping element.
```jsx
const StepsComponent = function StepsComponent({ steps }) {
  return steps.map(function stepsMap(step) {
    if (step.src) {
      return <img src={step.src} alt={step.alt} />;
    }

    return step;
  });
};


const steps = [
  '123',
  'another simple string',
  { src: './src/to/img', alt: 'img alt' },
];
const wrapper = mount(<StepsComponent steps={steps} />);

// The following only returns the img elements, it doesn't return simple nodes, such as strings.
const elements = wrapper.children().getElements();


// Now if I try this for shallow rendering, it won't even proceed
const wrapper2 = shallow(<StepsComponent steps={steps} />);
// This throws the following error:
// ShallowWrapper::getNode() can only be called when wrapping one node
const elements2 = wrapper.children().getElements();
```

If I wrap my component into a div, such as:
```jsx
const StepsComponent = function StepsComponent({ steps }) {
  return (
    <div>
      { steps.map(function stepsMap(step) {
           if (step.src) {
             return <img src={step.src} alt={step.alt} />;
           }

           return step;
      }); }
    </div>
  );
};
```
Using shallow rendering on such component and then calling `wrapper.children().getElements()` will output all children, however simple nodes are presented as `null` (but at least it indicates there are such nodes).

**Comment by ljharb** [comment]
@c-emil you're using react 16? I think your issue is different, since StepsComponent renders an array. I believe you want #1213.

**Comment by c-emil** [comment]
@ljharb Thanks for quick reply. Yes, I'm using react 16, I updated my comment to reflect that information. That's exactly the issue I'm referring to :) I missed that one, thanks! Even though I think it's related to both the issue you mentioned and this one since this one is also about not wrapped fragments, but author doesn't mention it explicitly. Should I rather add this comment to the issue you mentioned? It seems like it's not resolved either.

**Comment by ljharb** [comment]
This issue long predates React 16, so I don't think it's related.

**Comment by c-emil** [comment]
@ljharb Alright, it may not be after all. So do you think I should repost this comment to the issue you mentioned?

**Comment by ljharb** [comment]
Yes, that'd be great, thanks. If you want to delete your comments here too that'd also be good :-)

**Comment by ljharb** [comment]
I don't think this is still an issue in v3; please file a new issue if that's not the case.
