### ISSUE TITLE
Mount component, then render it

### ISSUE THREAD

**Issue by web2style** [airbnb/enzyme#698]
Is it possible to `mount` a component, mutate it (in my case simulate input change) and then `render` it to check resulting DOM elements.

This is what I want to achieve:

```
import React from 'react'
import expect from 'expect'
import {mount, render} from 'enzyme'
import SetPassword from './'

describe('<SetPassword />', () => {
  it('should render 3 validation error messages', () => {
    const mountedComponent = mount(<SetPassword />)
    mountedComponent.find('#password').simulate('change', {target: {value: '123'}})
    const renderedComponent = render(mountedComponent)
    expect(renderedComponent.find('.validation-error').length).toEqual(3)
  })
})
```

I get the following error in this case:
> Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.

Is there a way to do this?

**Comment by ljharb** [comment]
you don't need to "render" it at all. just call `.html()` on it after it's been updated.

**Comment by web2style** [comment]
@ljharb Thank you very much!
