### ISSUE TITLE
Usage with ZombieJS

### ISSUE THREAD

**Issue by deyceg** [airbnb/enzyme#699]
Hey,

Couldnt find any discussion on this so I figured I'd ask the question...

Im creating a little component test harness for my react/redux app. Normally I'd write these tests as unit test with tape/enzyme; however I have a requirement to make it more BDD style so I'd like to actually write (read: auto generate) some gherkin feature files, which are then run with cucumber js against an emulated browser environment to produce a report.

Normally, my app would be running somewhere and you would just visit the url with something like ZombieJS; however I dont want the compute overhead of having to constantly rebuild/transpile the app, and restart/hot load the web server.

My idea was the use enzyme to mount the component under test into the dom (and configure/initialize the redux store) then put the wrapper on the world object to interact with the app enabling me to implement my Given/When/Then using enzyme combined with <insert assertion library here>

The main issue is I dont think cucumber will run against jsdom directly without some wrapper (hence using ZombieJS as someones built one), but Im also struggling to figure out how to export the correct window object from ZombieJS before I require React such that the app is mounted into the correct jsdom instance!

Any suggestions welcome, including cease and desist :P

**Comment by blainekasten** [comment]
Hey @deyceg this sounds like a really cool idea. But I don't think any of us on the core team have played around with ZombieJS so we don't have much advice to offer. It's also outside the scope of the library a bit. Good luck to you! If you create something cool let us know. I'm going to close the issue for now as there isn't anything actionable, but feel free to keep the conversation going.
