### ISSUE TITLE
findWhere - unexpected results

### ISSUE THREAD

**Issue by danielpetrov** [airbnb/enzyme#701]
We have 3 buttons on the page. We select them and then we want to find the button with Download Text. This code returns 4 results for Download, as there should be only 1. 

    const buttons = wrapper.find('button')
    const downloadUploadDetailsButton = buttons.findWhere(button => {
        console.info(chalk.green.bold(button.text(), button.text() === 'Download'))
        return button.text() === 'Download'
    })

Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Persist false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Persist false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Persist false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Persist false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Upload false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Upload false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Upload false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Upload false'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Download true'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Download true'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Download true'
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Download true'

Instead with forEach this is what we get on the console:

    const buttons = wrapper.find('button')
    const downloadUploadDetailsButton = buttons.forEach(button => {
        console.info(chalk.green.bold(button.text(), button.text() === 'Download'))
        return button.text() === 'Download'
    })

Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Persist', false
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Upload', false
Chrome 54.0.2840 (Linux 0.0.0) INFO: 'Download', true

**Comment by ljharb** [comment]
I don't think this is still an issue in v3; please file a new issue if that's not the case.
