### ISSUE TITLE
Support for pseudo-classes

### ISSUE THREAD

**Issue by cameronroe** [airbnb/enzyme#703]
It would be great to have support for pseudo-class selectors.

Current Error
```
Error: Enzyme received a pseudo-class CSS selector (':first-child') that it does not currently support
```

**Comment by vkraucunas** [comment]
Along the same vein, `input:required` would also be great.

**Comment by Yimiprod** [comment]
In the same idead `button:not(.is-disabled)` would be awesome.

**Comment by nickkhall** [comment]
Any pseudo class support would be nice!

**Comment by Lieblein** [comment]
This also does not work: `const inputsWithError = formWrap.find('[class$=--state-error]');`

**Comment by nickhallph** [comment]
I'm `nickkhall`'s clone, and I agree with my clone. I need them pseudo's!!

**Comment by ljharb** [comment]
@aweary is this covered by v3?

**Comment by aweary** [comment]
@ljharb the infrastructure is there, but the implementation is not. I will investigate this today to see what set of pseudo-classes we can reasonably support.

**Comment by trigun539** [comment]
Is there anyway to get a focused element?

**Comment by lgandecki** [comment]
@aweary Hello there, any update? If you can give me some tips/clues/observations I'm happy to jump in and implement this, but I wouldn't want to duplicate any effort if you already put some thoughts into this. Please let me know :)

Having things like first-child / nth-child would be fantastic. To give some context - I'm currently writing a "page-object wrapper" which allows me to run the same tests with any driver (cypress, chimp, wdio, enzyme)..

So basically you can do something like:
```javascript

class LoginPage {
  constructor (driver) {
    this.driver = driver;

    const root = '.login__form';
    this.selectors = {
      root,
      loginButton: `${root} .button--primary`,
      loginInput: `${root} #username`,
      passwordInput: `${root} #password`,
      swalContainer: `.swal2-shown`
    };
    Object.entries(this.selectors).forEach(([name, selector]) => {
      Object.defineProperty(this, name, {get: function () { return this.driver.getElement(selector); }});
    });
  }

  async setPassword (password) {
    await this.passwordInput.setValue(password);
  }
  async setUsername (username) {
    await this.loginInput.setValue(username);
  }
  async login () {
    await this.loginButton.click();
  }
  assertIsActive () {
    this.root.assertIsVisible();
  }
  assertNotActive() {
    this.root.assertNotVisible()
  }
}

```

and then run your tests:
```javascript
test('login correct ', async () => {
  const resolvers = {...};
  const wrapper = await startApp(resolvers);
  const loginPage = new LoginPage(wrapper);

  await loginPage.setPassword('correctPassword');
  await loginPage.setUsername('correctUsername');
  await loginPage.login();

  loginPage.assertNotActive() 
});
```

and internally in startApp depending on the context you run the tests with enzyme, or e2e with a browser. It works like a dream with react and graphql, with instant feedback with wallabyjs, and I'm very excited to share this with a world in the next couple weeks.

Being able to use more sophisticated selectors would be fantastic to have here :)

**Comment by yahilmadakiya** [comment]
I have an issue with `':focus'`.
**Error:** *Enzyme::Selector does not support pseudo-element or pseudo-class selectors.*

```
const wrapper = mount( <UrlInputButton autofocus={ false } /> );
wrapper.setState( { expanded: true } );
const elem = wrapper.find( 'input[type="text"]' );
expect( elem.is( ':focus' ) ).toBe( true );
```

Thanks.

**Comment by ljharb** [comment]
#1537 added support for some of these, and will be in the next release.

I'm going to close this one; please file a new issue for each/any pseudoselector you'd like to see supported, or that isn't supported properly. Thanks!

**Comment by franciscop-invast** [comment]
That looks great, has it been published to npm? I updated Enzyme to search for `:first-child` but I'm still seeing the same error.

**Comment by ljharb** [comment]
enzyme has not yet been updated, no. it will be updated as soon as possible.

**Comment by Emidomenge** [comment]
Please guys, this feature would be great, unless I'm mistaken, there is still nothing released ! :'(

In my case, I'm unable to detect the value of pseudo class `::place-holder`

Did someone find a workaround meanwhile ?

Thanks

**Comment by ljharb** [comment]
@Emidomenge It's definitely been released. Are you sure your transitive dependencies are fully updated?

**Comment by Emidomenge** [comment]
@ljharb You're right, I don't have the latest version, my bad ! ^^ 
But still, I didn't see on documentation something which explain how to deal with pseudo class, it would be cool. :) 
Have a nice day

**Comment by ljharb** [comment]
Sure, a PR to improve docs would be appreciated.

**Comment by nimishbongale** [comment]
@ljharb Is the `:root` pseudo selector supported?

**Comment by ljharb** [comment]
@nimishbongale i doubt it, since there's no tests for it. Happy to review a PR that adds it.
