### ISSUE TITLE
Not found class with pure function + shallow

### ISSUE THREAD

**Issue by ninahaack** [airbnb/enzyme#709]
Hello, I'm having a problem trying to create a test with pure function and shallow. I'm new with react so, could be my mistake.

I have this pure function:

```
const PanelHeader = () => (
  <Header>
    Pagamento de publishers
  </Header>
)

export default PanelHeader
```

My test consists in:
```
import { shallow } from 'enzyme'
import React from 'react'
import PanelHeader from '../PanelHeader'

describe('PanelHeader', () => {
  const wrapper = shallow(<PanelHeader />)

  it('shows header title', () => {
    const expectedTitle = 'Pagamento de publishers'
    const currentTitle = wrapper.find('.sn-layout-title')
    console.log('-->>', wrapper.html());
    console.log('-->>', currentTitle.length);
    expect(currentTitle.text()).toEqual(expectedTitle)
  })
})

```

the result of the test is:

console.log src/app/layout/components/tests/PanelHeader.test.js:13
      -->> ```<header class="sn-layout__header sn-presentation-header"><div aria-expanded="false" role="button" tabindex="0" class="sn-layout__drawer-button"><i class="material-icons"></i></div><div class="sn-layout__header-row"><span class="sn-layout-title">Pagamento de publishers</span></div></header>```
    console.log src/app/layout/components/tests/PanelHeader.test.js:14
      -->> 1

   PanelHeader › shows header title
    Method “text” is only meant to be run on a single node. 0 found instead.

I really doesn't understand why it doesn't find the text and if I change shallow for mount, works.  Thanks for the help

react: 15.3.2 and enzyme: 2.5.1

**Comment by ljharb** [comment]
You're doing a shallow-render of `PanelHeader` - as such, it doesn't actually render the `Header` itself. In other words, a shallow test of `PanelHeader` should only assert that it renders a `Header` with the `children` you expect.

The tests for `Header` should be checking for the `sn-layout-title` className, etc.

**Comment by ninahaack** [comment]
I understand, thank you very much
