### ISSUE TITLE
ReferenceError not defined with multiple expects

### ISSUE THREAD

**Issue by ttbarnes** [airbnb/enzyme#710]
Not sure if i'm missing something here or if i've discovered a bug :)

Given this test:

```
it('should render a default option', () => {
  const wrapper = shallow(
    <SelectBox disabled={true} default="Select something">
      <option value="1">option 1</option>
    </SelectBox>
  );
  expect(wrapper.find('select').childAt(0).type()).toEqual('option'));
  expect(wrapper.find('select').childAt(0).text()).toEqual('Select something'));
});
```

With both of these expect's, it fails with `ReferenceError: wrapper is not defined`. 

If I disable either one of the expect's, it passes. EG:

```
expect(wrapper.find('select').childAt(0).type()).toEqual('option'));
// expect(wrapper.find('select').childAt(0).text()).toEqual('Select me'));
```
or
```
// expect(wrapper.find('select').childAt(0).type()).toEqual('option'));
expect(wrapper.find('select').childAt(0).text()).toEqual('Select me'));
```

I tried creating a new wrapper between each expect, but get a different error which kind of makes sense: 

`'expect' was used when there was no current spec, this could be because an asynchronous test timed out`

Separating the 2 expects into individual tests/specs works just fine.

Sorry to raise this issue if it's not a bug. Can someone confirm?

**Comment by ljharb** [comment]
Where does your `expect` come from?

**Comment by ttbarnes** [comment]
@ljharb  I'm getting a different error message now - unable to replicate my original case above that returns `'expect' was used when there was no current spec...`

With the 2 assertions in the same it function: 

```
it('should render a default option', () => {
    const wrapper = shallow(
      <Selectbox disabled={true} defaultOption="Select something">
        <option value="1">option 1</option>
        <option value="2">option 2</option>
      </Selectbox>
    );
    expect(wrapper.find('select').childAt(0).type()).toEqual('option'));
    expect(wrapper.find('select').childAt(0).text()).toEqual('Select something'));
  });
```

I am now getting this error:

```
<Selectbox/> › encountered a declaration exception

    ReferenceError: wrapper is not defined
      
      at Suite.<anonymous> (src/controls/Selectbox/Selectbox.test.tsx:26:12)
      at Object.<anonymous> (src/controls/Selectbox/Selectbox.test.tsx:10:1)
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

If I disable one of the assertions, or separate them, they work just fine.

**Comment by ljharb** [comment]
That definitely doesn't make any sense :-/ based on how JS works, that should work the same.

What about:
```js
const option = wrapper.find('select').childAt(0);
expect(option.type()).toEqual('option'));
expect(option.text()).toEqual('Select something'));
```

**Comment by Aweary** [comment]
Your stack trace indicates you're using TypeScript (`tsx` extension), I wonder if it's an issue with how TypeScript is compiling your code?

**Comment by ttbarnes** [comment]
Thanks guys,

I can confirm this approach works:
```
const option = wrapper.find('select').childAt(0);
expect(option.type()).toEqual('option'));
expect(option.text()).toEqual('Select something'));
```

It does seems like this is a typescript specific issue. I'm on a relatively new project so our typescript config will probably adapt shortly. If we get any similar issues i'll report back - could try some different typescript configurations.

 @ljharb @Aweary
