### ISSUE TITLE
ReactWrapperComponent#getInstance and getWrappedComponent are the same?

### ISSUE THREAD

**Issue by nfcampos** [airbnb/enzyme#726]
see https://github.com/airbnb/enzyme/blob/master/src/ReactWrapperComponent.jsx#L55
and https://github.com/airbnb/enzyme/blob/master/src/ReactWrapperComponent.jsx#L46

They return the same thing, is this intentional? If so, we can deprecate one of `getNode` and `instance` on `mount` because they return the same thing

@ljharb @Aweary @blainekasten

**Comment by ljharb** [comment]
@lelandrichardson ?

**Comment by blainekasten** [comment]
@lelandrichardson added both APIs in 9acb9d1. It seems that `getWrappedComponent` is ONLY used in 1 [place](https://github.com/airbnb/enzyme/blob/master/src/ReactWrapper.jsx#L86)

**Comment by ljharb** [comment]
In that case lets deprecate `getWrappedComponent`, rewrite it to call into `.instance`, and remove it at the next major?

**Comment by blainekasten** [comment]
Is it even a public API? looks like it's private to just ReactWrapper

**Comment by ljharb** [comment]
If it's reachable anywhere, it's public.

**Comment by ljharb** [comment]
This seems like it's addressed by v3.
