### ISSUE TITLE
TypeError: Cannot read property 'contextTypes' of undefined

### ISSUE THREAD

**Issue by emptyOne322** [airbnb/enzyme#729]
Hi, I added enzyme into my test and tried to do some simple test 
describe('Component: SliderField', () =>{
    
    const minProps = {
        input: {
            name:"name",
            value:0,
            onChange: ()=>{},
            meta: {

            },
            min: 0,
            max: 100
        },
    };

    it('renders', () => {
        const wrapper = shallow(<SliderField {...minProps}/>)
        expect(wrapper.length).toEqual(1);
    });
}) 
but it returned TypeError: Cannot read property "contextTypes" of undefined. I'm using mocha, webpack to build tests and webpack-dev-server to runing them in browser . So can someone help me or give some advices what can be wrong here?

**Comment by blainekasten** [comment]
I'm guessing your SliderField is expecting some context to be defined on it. You can pass context into a renderer via the second argument. See the documentation here: https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md#shallownode-options--shallowwrapper

`shallow(<SliderField {...minProps} />, { context: {...} });`

**Comment by blainekasten** [comment]
I'm going to close this out as it is not an issue with Enzyme itself. Feel free to keep discussing though if you need more support.

**Comment by emptyOne322** [comment]
So can u give me qiuck explanation what context should be like?

**Comment by jskeate** [comment]
Going to leave a note here in case others come across this issue in a search. This error seems to happen if you
`import {Component} from '<path>';`  
when you should have  
`import Component from '<path>';`

**Comment by ljharb** [comment]
If you use `eslint-plugin-import` (which the airbnb eslint config uses) then you'd get a linting error if you imported the wrong thing ;-)

**Comment by jskeate** [comment]
`import/named` and `import/default` are off in the airbnb eslint config, it seems.

**Comment by ljharb** [comment]
Touché :-) they'll be turned on eventually.

**Comment by rmpardee** [comment]
Thank you so much @jskeate that saved me so much time

**Comment by docunext** [comment]
Ja! Thank you @jskeate - much appreciated.

**Comment by AKNiazi** [comment]
@jskeate Thanks.

**Comment by lucasdeassis** [comment]
@jskeate some heroes don't use cape!

**Comment by luciomartinez** [comment]
In my case was similar but I fixed by importing the component instead of "wrapped component". For most components they are wrapped with `connect()` so in test:

```
import _MyComponent from './MyComponent';
const MyComponent = _MyComponent.WrappedComponent;
// then used such as <MyComponent ...props />
```

This time the test was over a PureFunction component instead of a Class. I changed the usage to be:

```
import MyComponent from './MyComponent';
// then used such as <MyComponent ...props />
```

**Comment by errawn** [comment]
@jskeate  danke! <3

**Comment by gecersiznick** [comment]
> Going to leave a note here in case others come across this issue in a search. This error seems to happen if you
> `import {Component} from '<path>';`
> when you should have
> `import Component from '<path>';`

If this doesn't solve the issue, make sure that you actually **export** the component that you are trying to **import**.
