### ISSUE TITLE
jsdom dependency?

### ISSUE THREAD

**Issue by jakemmarsh** [airbnb/enzyme#73]
I'm just curious as to why `jsdom` is required for the full rendering. I understand the need for a DOM, but what about in environments in which a DOM already exists? In our current architecture, we're running our tests directly in the browser via Karma.

I do see that `jsdom` is an optional dependency, and that its require statement is wrapped in a try/catch. Does this mean that it would still work if you're using some alternative DOM? If so, then just the docs are misleading.

**Comment by MattKunze** [comment]
Yeah, we definitely want to be able to use the native DOM when running tests in the browser

**Comment by lelandrichardson** [comment]
Agreed 100%. I hope this will be accomplished with this PR: https://github.com/airbnb/enzyme/pull/60
