### ISSUE TITLE
How to test CSS event changes ?

### ISSUE THREAD

**Issue by csbhut** [airbnb/enzyme#734]
Hello , 

I have started using enzyme , chai , mocha to test react component . This set up is working fine for me except few scenarios like input textbox is Focus or not ? also can i check whether particular css property applied or not ? 

Thanks .

**Comment by ljharb** [comment]
Can you provide some more specific code examples that illustrate your question?

**Comment by csbhut** [comment]
@ljharb  like i have class defined in my css like 
.custombutton:hover{
    background-color: some color code ;
}
which i applied on button . Also Property called "focus " for textbox when textbox get selected .  So i want to test this in my unit test . 
Doubt 1 : whether this is right to test in unit test ? 
Doubt 2 : If yes then how it is possible with enzyme and not then how can I test behavior like this ? 

Thanks .

**Comment by ljharb** [comment]
Generally I wouldn't test CSS in a unit test, no - but since it's a `style` prop on a `button` element, you can simply `.find('button').props()` and write assertions on that.

**Comment by csbhut** [comment]
@ljharb  thnaks  for your response .

**Comment by csbhut** [comment]
@ljharb Sorry to ask "Different issue here", In my react component I amsetting one div html in jQuery way on button click , which I am trying to test by simulating form submit and then check value of that div is updated or not but it is not updating . I tried to put console.log also but it is returning empty . 

const wrapper = mount(<page />);
        const instance = wrapper.instance();
        const handleClickStub = sinon.spy(instance,'handleSubmit');
       const errordiv = wrapper.find('#errorhandler');
        instance.forceUpdate()
        wrapper.find('form').simulate('submit');
        sinon.assert.calledOnce(handleClickStub);
        //way to print state in the test
       console.log(errordov.text());``

Thanks.

**Comment by ljharb** [comment]
The original question seems answered.

I wouldn't recommend using `simulate` since it doesn't actually simulate anything. Instead, directly invoke the prop function you want.
