### ISSUE TITLE
Testing when returning components inside class methods

### ISSUE THREAD

**Issue by laumair** [airbnb/enzyme#735]
I have this `Block` component where I am using `GroupsContainers` component but instead of directly consuming it inside the `render` method I am getting it from a class method: 

 ```
 mapToContainerBoxes(data) {
    return map(data, (containers, key) => (
      <GroupsContainers
        key={key}
        name={get(head(containers), 'name')}
      />
    ));
  }
```

```
const instance = shallow(<GroupsBlock {...props} />).instance();
          const data= {
            some_id: [{
              entity_type: 'entity',
              group_id: '1',
              name: 'modesty'
            }]
          };

expect(instance.mapToContainerBoxes(data)[0] instanceof GroupsContainers); // Gives false
```

From my understanding this should return true, no? Or am I missing something here?

**Comment by ljharb** [comment]
Those are elements, which aren't instanceof the component. Use `.is(GroupsContainers)` instead.

**Comment by laumair** [comment]
@ljharb Nice. Is this in the official docs?

**Comment by ljharb** [comment]
The method is - that you can't use instanceof is just the nature of react.

**Comment by blainekasten** [comment]
Sounds like this is resolved. I'm going to close the issue since there isn't anything actionable. Feel free to keep the conversation going if needed.
