### ISSUE TITLE
TypeError: wrapper.find(...).exists is not a function

### ISSUE THREAD

**Issue by FakhruddinAbdi** [airbnb/enzyme#736]
When i'm running same example given in [exist api page](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/exists.md)

I got following the error in console 

     TypeError: wrapper.find(...).exists is not a function

**Comment by Aweary** [comment]
Hey @FakhruddinAbdi, thanks for the issue. That feature was [recently merged](https://github.com/airbnb/enzyme/pull/722) and hasn't been released yet.

Refer to the [published API docs](http://airbnb.io/enzyme/docs/api/) instead of the docs in the repo, as we'll make sure to publish any doc changes alongside the minor release that will accompany `exists()`

**Comment by dpikt** [comment]
Getting this error in `2.7.1`, `exists()` is in the [published API docs](http://airbnb.io/enzyme/docs/api/ReactWrapper/exists.html) too...?

**Comment by blainekasten** [comment]
Quick side note - What are you using the Cheerio wrapper for that the other wrappers can't do?

**Comment by dpikt** [comment]
@blainekasten I was using it to deep-render my components, it seemed less costly than running `mount()` since I don't care about lifecycle methods or DOM APIs. Is that the right call or would you suggest doing something else?

**Comment by ljharb** [comment]
I'd suggest using `shallow` at every level :-p

**Comment by blainekasten** [comment]
@dpikt it's not necessarily wrong. I just am curious if anyone actually uses the Render api. I personally would be pretty happy getting rid of it all together.

**Comment by bay007** [comment]
I use `shallow` : my code,
```
it('Render if Editable component if have Editable photo', () => {
  const photos = new Map();
  photos.set(1, { isEditable: false });
  photos.set(2, { isEditable: true });
  photos.set(3, { isEditable: false });

  const wrapper = shallow(<Editable photos={photos} />);
});
```

where Editable component starts with:

```
export const Editable = class _Editable extends Component {
  render() {
    const editablePhoto = this.props.photos.values().find(photo => {
      return photo.isEditable;
    });
.
.
.
```

The error:
![image](https://cloud.githubusercontent.com/assets/8164038/25295235/6495560c-26a8-11e7-920b-03004d9febe3.png)

**Comment by ljharb** [comment]
@bay007 a Map's `values` function returns an *iterator*, not an array - you'd need `[...this.props.photos.values()].find` instead.

**Comment by palaniichukdmytro** [comment]
I got the same error:
 <Routes/> should login on entering /login-callback or redirect to / :
     TypeError: result.find is not a function

```
describe('<Routes/>', () => {
    let routes
    let redirectToLoginPage
    let login

    beforeEach(() => routes = shallow(<Routes redirectToLoginPage={redirectToLoginPage = sinon.spy()} login={login = sinon.spy()}/>))


    it.only('should login on entering /login-callback or redirect to / ', () => {

        let result = routes.find(Route).findWhere(x => x.props().path === '/login-callback').props().render()
        console.log(result.type)


        login.calledOnce.should.be.true
        result.find(Redirect).length.should.be.equal(1)
        result.props.to.should.be.equal('/')
    })
```

**Comment by palaniichukdmytro** [comment]
I solve the main problem, but why I recive the 
expected <Redirect /> to be of type [Function: Redirect], but it is of type null
`expect(result).to.have.type(Redirect)`

**Comment by ljharb** [comment]
I'm not sure why you'd expect `result` - which is a cheerio wrapper - to have a type of `Redirect`

**Comment by palaniichukdmytro** [comment]
@ljharb I'm testing the react router v4, so the result expect return the Redirect component
```
 <Route path='/login-callback' render={() => {

                if (!isLoggedIn)
                    login()
                return <Redirect to="/"/>

            }}
            />
```

**Comment by ljharb** [comment]
Ah, I misunderstood - you're manually calling the render prop. In that case, the result will be a React element - it won't have a `.find` method at all.

**Comment by palaniichukdmytro** [comment]
yes, I've already notice  that, the code looks now like this:
```
it.only('should login on entering /login-callback or redirect to / ', () => {
        
        let result = shallow(routes.find(Route).findWhere(x => x.props().path === '/login-callback').props().render())
        console.log(result.unrendered)


        login.calledOnce.should.be.true
        expect(result).to.have.type(Redirect)
        result.props.to.should.be.equal('/')
    })
```

 AssertionError: expected <Redirect /> to be of type [Function: Redirect], but it is of type null
I'm only starting with enzyme

**Comment by ljharb** [comment]
because now `result` is an enzyme shallow wrapper. You want:
```js
const result = shallow(<div>{routes.find(Route).findWhere(x => x.props().path === '/login-callback').props().render()}>/div>)
expect(result.is(Redirect)).to.equal(true);
```

**Comment by palaniichukdmytro** [comment]
Yes, but in this  case, I catch an error:
 AssertionError: expected false to equal true

 + expected - actual
      -false
      +true

**Comment by palaniichukdmytro** [comment]
this one help me
`result.props().render().type.should.be.equal(Redirect)`

**Comment by palaniichukdmytro** [comment]
How to check the if else statement logic here. Cuase when I cover my app, catch the warning that **else path not taken**
```
<Route path='/login-callback' render={() => {
                if (!isLoggedIn)
                    login()
                else
                    return false
                return <Redirect to="/"/>
            }}
            />
```

my unit test:
```
describe('<Routes/>', () => {
    let routes
    let redirectToLoginPage
    let login
    let isLoggedin
    beforeEach(() => routes = shallow(<Routes redirectToLoginPage={redirectToLoginPage = sinon.spy()} login={login = sinon.spy()}/>))

    it('should login on entering /login-callback or redirect to / ', () => {
        let redirect = routes.find(Route).findWhere(x => x.props().path === '/login-callback').props().render()

        login.calledOnce.should.be.true

        redirect.type.should.be.equal(Redirect)
        redirect.props.to.should.be.equal('/')
    })

```

**Comment by ljharb** [comment]
that means you're not testing when "isLoggedIn" is true (only when it's false).

@palaniichukdmytro none of these questions are an issue, nor related to *this* issue - can you please ask them in our gitter channel instead?

**Comment by palaniichukdmytro** [comment]
@ljharb done, thanks
