### ISSUE TITLE
webpack externals are not complete

### ISSUE THREAD

**Issue by gilamran** [airbnb/enzyme#740]
Hi,
In our situation we use webpack to bundle the application code into a bundle, and the external packages (Like `react`)  we load them using a `script` tag (CDN). We would like to mimic that also in our tests.
But when importing `enzyme` in our tests, it will bundle **react** and **react-dom** into the application bundle, even after we specifically mentioned them in our `externals` section.

To solve this, you have to add this to the externals:

```
    "react": 'React',
    "react-dom": 'ReactDOM',
    "react-dom/server": true,
    "react-dom/lib/ReactTestUtils": true
```

**Comment by blainekasten** [comment]
Could you throw up a PR for updating the docs?

**Comment by gilamran** [comment]
Done, #744

**Comment by gilamran** [comment]
I've updated the issue description to explain the situation. (PR was not updated)
[Here](https://github.com/gilamran/enzyme_webpack_bug_example)'s a repo. to test the issue.
Tests are on the latest react `15.4.1`

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.
