### ISSUE TITLE
Does it intend to work .simulate('click') with disabled button?

### ISSUE THREAD

**Issue by blackpost38** [airbnb/enzyme#749]
I was testing click event of disabled button. But click event works.

I want to know if it is intended or not.

```js
const props = {
  onClick: jest.fn()
}
const enzymeWrapper = shallow(
  <button
    onClick={props.onClick}
    disabled
  >
    test
  </button>
)
enzymeWrapper.simulate('click')
expect(props.onClick.mock.calls.length).toBe(1) // not 0
```

**Comment by aweary** [comment]
Thanks for the issue @blackpost38, we are aware of this, track it at: https://github.com/airbnb/enzyme/issues/386

**Comment by blackpost38** [comment]
@aweary thanks for a comment! I didn't know it. 👍
