### ISSUE TITLE
query with an keyword in selector string

### ISSUE THREAD

**Issue by woaiso** [airbnb/enzyme#754]
There is one such keyword in my selector string
```
const wrapper = mount(<Input/>);
wrapper.find('#link#url')
```
`link#url` is an  id 

when selector string has keyword what should I do ？

Jquery solution is add Escape characters `\\` before keyword like `link\\#url`

**Comment by ljharb** [comment]
I'm pretty sure "#" is not a valid character in IDs.

**Comment by woaiso** [comment]
“#” for [HTML 4](https://www.w3.org/TR/html4/types.html#type-id) is not  a valid character in IDs. 

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

but in [HTML 5 ](https://www.w3.org/TR/html5/dom.html#the-id-attribute) it's was valid.
> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.

**Comment by ljharb** [comment]
It seems very ill-advised to select an ID format that fails hard in older browsers - not very a11y compliant.

That said, I'll leave this open to tackle when we rewrite our selector engine.

In the meantime (and always) you'll be better off using `.findWhere` and providing a function predicate, instead of relying on strings.

**Comment by woaiso** [comment]
Okay i will try `.findWhere`

**Comment by ljharb** [comment]
@aweary is this still an issue in v3?

**Comment by aweary** [comment]
@ljharb it is, `#a#b` is grammatically ambiguous since the selector spec allows multiple ID selectors. This query will fail even with browser selector parsers, like `querySelector` ([example](https://jsfiddle.net/5gLbm7kv/)) so I think it's safe to say this is an unsupported query format.
