### ISSUE TITLE
is there 'simulate' callback?

### ISSUE THREAD

**Issue by shallwefootball** [airbnb/enzyme#758]
I want to test, after [simulate](http://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html).

because after event emit, setState is async.
so if test should be success, async was resolved. 
than we should expect test spec.

so we need some callback. whatever.

```
it('will success', (done) => {
  wrapper.simulate('click', () => {
     // expect code..
     done();
  });
})
```

but there is no callback arguments..

why nothing?

**Comment by ljharb** [comment]
`simulate` calls user code, and enzyme has no idea if that code calls setState or not. So, there's no way to know if a callback is even needed, let alone to know when to fire it.

**Comment by shallwefootball** [comment]
thanks🙏
