### ISSUE TITLE
refs are blank using mount and ref on react-native child component

### ISSUE THREAD

**Issue by chrismcleod** [airbnb/enzyme#760]
When mounting a component (using jsdom) with a child component that has a ref="nav", I expect this.refs.nav to be the child Navigator in componentDidMount.  I get blank this.refs object when I console.log(this.refs) in componentDidMount.

The component below renders and works fine in the ios simulator, however refs are blank using enzyme's mount.  I have also noticed that if I have a ref on the root element, that particular ref *is* defined in componentDidMount.

I am using:
```json
"react": "^15.4.1",
"react-native": "^0.39.2",
"chai": "^3.5.0",
"enzyme": "^2.7.0",
"jsdom": "^9.9.1",
"mocha": "^3.2.0",
"react-native-mock": "^0.2.9"
```

**setup.js**
runs before all tests
```node
var jsdom = require('jsdom').jsdom;
global.__DEV__ = true;
global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});
global.navigator = {
  userAgent: 'node.js'
};
require("react-native-mock/mock");
```

**TEST**
```node
describe("MyComponent", function() {
  it("does a thing", function() {
    const view = mount(<MyComponent/>);
    expect(...);
  });
});
```

**COMPONENT**

```node
class MyComponent extends React.Component {
  componentDidMount() {
    console.log(this.refs); // {}
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Navigator
          ref="nav"
          renderScene={this.renderScene}
          initialRouteStack={routes}
          sceneStyle={{ flex: 1 }}
          configureScene={() => Object.assign(Navigator.SceneConfigs.HorizontalSwipeJump, { gestures: {} })}
        />
        <TouchableHighlight ref="prev" key="prev" onPress={this.handlePressPrev}>
          <Text>Prev</Text>
        </TouchableHighlight>
        <TouchableHighlight ref ="next" key="next" onPress={this.handlePressNext}>
          <Text>Next</Text>
        </TouchableHighlight>
      </View>
    );
  }

}
```

**Comment by julien-rodrigues** [comment]
I also have the problem. 
I usually use ref functions but never had to use them to test my code.

But when I tried to, it didn't work. I tested string ref and `this.refs` is always empty.

Example of code I have:
```javascript 
// Component.js
class Input extends Component {
  textInput = null;

  onSubmitEditing = event => {
    this.props.onSubmitEditing(event);
    this.textInput.blur();
  };

  referenceMapping = component => {
    this.textInput = component;
  }

  render() {
    return (
      <View>
        <TextInput ref={this.referenceMapping} onSubmitEditing={this.onSubmitEditing} />
      </View>
    );
}
```

```javascript 
// test.js
test('onSubmitEditing() - Should be bound to the TextInput component.', t => {
  const onSubmitEditingSpy = spy();
  const render = mount(<Input onSubmitEditingSpy={onSubmitEditingSpy} />);

  console.log(render.instance().textInput); // Prints `null`.
  render.instance().textInput.simulate('submitEditing'); // TextInput being `null`, this breaks.
});
```

I also tried to change the type of the `referenceMapping` function from `class property` to `method` (and binding `this` inside the constructor of the class) but it changed nothing.

**Comment by zacharyfox** [comment]
Also having this problem. For more information, if I look at refs in the node in my test code `wrapper.find(Foo).node.refs` it is there - but `this.refs` is an empty object in Foo.

**Comment by SureshCS-50** [comment]
@julien-rodrigues @zacharyfox  I found my object. 
` beforeAll(() => { wrapper = shallow(<LoginComponent />); }); `
` let textInput = wrapper.find(TextInput).at(0).props();`

but, I don't know how to simulate `onSubmitEditing`
tried this code.. but, It fails..

     describe("checks email TextInput behaviour", () => {
        let onSubmit, props, wrapper;
        beforeAll(() => {
            onSubmit = jest.fn();
            props = { onSubmitEditing: onSubmit };
            wrapper = shallow(<TextInput {...props} />);
        });

        describe("on submitting", () => {
            beforeEach(() => {
                wrapper.simulate("keydown", {
                    key: "Enter",
                    keyCode: 13,
                    which: 13
                });
            });
            it("onSubmitEditing", () => {
                expect(props.onSubmitEditing).toHaveBeenCalledTimes(1);
            });
        });
    });

**Comment by ljharb** [comment]
You'd need a react native adapter to use enzyme with React Native.

Closing this in favor of #1436.
