### ISSUE TITLE
Improve `shallow` docs for options

### ISSUE THREAD

**Issue by ryanmcnamara** [airbnb/enzyme#762]
The docs for `shallow`: https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md don't list supported fields of the `options` object. They do show that you can provide a `context` option, but *all* supported options aren't clearly illuminated. They are missing at least one: `lifecycleExperimental`

**Comment by thurt** [comment]
Was curious about this as well. 

Having a look at the source here https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js

it appears that this.options is only referenced for `context` and `lifecycleExperimental`, suggesting these are in fact the only options currently available.

**Comment by kumar303** [comment]
The HTML (official?) docs have even less information about what `options` can be: http://airbnb.io/enzyme/docs/api/ShallowWrapper/shallow.html

**Comment by ljharb** [comment]
PRs are welcome to improve it.

**Comment by NiveditN** [comment]
Hey @ljharb, I have updated the HTML docs with the required details. Hope this helps. :slightly_smiling_face:
