### ISSUE TITLE
Enzyme webpack alias not working

### ISSUE THREAD

**Issue by svidhani** [airbnb/enzyme#764]
I am trying to use enzyme with react 15.4 and webpack. 
I get errors "Cannot find module 'mymodule'". 

The reason for that is that i have alias set up in my webpack.config.
How can I resolve this where Enzyme can use the alias to resolve the path?

**Comment by ljharb** [comment]
enzyme doesn't resolve any paths, webpack does. If you're getting that error, then it's an issue with your webpack config.

**Comment by ljharb** [comment]
How do you run your tests? Are they run through webpack?

**Comment by svidhani** [comment]
using mocha

test mocha --timeout 30000 --compilers jsx:test/helpers/compiler.js js:test/helpers/compiler.js,js:babel/register test/**/** --recursive

**Comment by ljharb** [comment]
I'm going to close this since this is entirely unrelated to enzyme.

I believe you need to run webpack as part of your tests if you want nonstandard requires to work, but the webpack or mocha repos are a better place to ask about that.

**Comment by haledeng** [comment]
@svidhani  Do you solve the problem?  I have the same issue. Any ideas?
