### ISSUE TITLE
Shallow does not return 0 when doing `[].length && '1'`

### ISSUE THREAD

**Issue by rodoabad** [airbnb/enzyme#766]
```javascript
                {[].length > 0 && '1'}
                {[].length && '1'}
```

The latter should return `0` and it should display it. However for enzyme, they both return `null`.

**Comment by blainekasten** [comment]
This took a minute for me to grok. haha. Correct me if I'm wrong. You're saying:

```js
function Comp() {
  return <div>{[].length && '1'}</div>
}

mount(<Comp />).html();
// prints <div></div>
// but should be <div>0</div>
```

So then the issue is that the number `0`, is being translated to `null` in enzyme?

**Comment by rodoabad** [comment]
Yep!

**Comment by ljharb** [comment]
Does this also occur with `shallow`, or only with `mount`?

**Comment by aweary** [comment]
@rodoabad what version of Enzyme are you using? I tried to reproduce with the latest and was unable to. You can see the test case here: [aweary/enzyme-test-repo/blob/issue-766/test.js](https://github.com/aweary/enzyme-test-repo/blob/issue-766/test.js)

```js
class RendersAZero extends React.Component {
  render() {
    return (
      <div>{[].length && '1'}</div>
    );
  }
}

describe('Issue #766', () => {
  it('renders 0 when doing [].length && 1', () => {
    const wrapper = shallow(<RendersAZero/>);
    expect(wrapper.html()).to.equal('<div>0</div>');
  });
})
```

I tested with `mount` as well and it passed.

**Comment by ljharb** [comment]
This seems like a non-issue, pending a repro case.
