### ISSUE TITLE
Calling the constructor 3 times

### ISSUE THREAD

**Issue by vladblindu** [airbnb/enzyme#774]
I don't know if this is an enzyme issue, a react issue or it is the way it's supposed to work.
When I **mount** a component the constructor of the tested component is called 3 times. 
I am mounting a material-ui based component which expects a _muiTheme_. The this is context :
`{
            context: {
                muiTheme: muiTheme
            },
            childContextTypes: {
                muiTheme: React.PropTypes.object
            }
`
The mount call is:
    `
let wrapper = mount(<ThrowMockComponent {...props}/>, context);
`
I just added a console.log that prints a counter and the context received by the component.
The result is:
 
       0, undefined
       1, undefined
       2, (the correct muiTheme content)

For the first two the component issues a warning about the undefined muiTheme context.

The test is working, but I am a bit annoyed by this warnings. 
Is this the intended behaviour?
Thank you for your time.

**Comment by aweary** [comment]
@vladblindu thanks for the issue. Can you share a small test case that reproduces your issue? I would not expect the `constructor` to be called three times if it is only mounted once.

**Comment by ljharb** [comment]
Happy to reopen this with a repro case.
