### ISSUE TITLE
missing shallow propTypes warning for a subcomponent

### ISSUE THREAD

**Issue by thurt** [airbnb/enzyme#779]
if I shallow render a component called `MyComponent`, whose render function looks like:
```javascript
render() {
  return(
    <MySubComponent /> // purposely omitting required prop value
  )
}
```
and MySubComponent.propTypes look like:
```javascript
{
  value: React.propTypes.string.isRequired
}
```
i only get a propType warning the first time I run `shallow(<MyComponent />)` in a jest test. The second time i run `shallow(<MyComponent />)` I do not get a propType warning.

It should give me a propType warning every time I run `shallow(<MyComponent />)` if MySubComponent does not have valid propTypes.

**Comment by ljharb** [comment]
Indeed, it should. Can you verify if that's related to jest by trying a different framework? Can you share your test file?

**Comment by aweary** [comment]
This is expected behavior, [React dedupes](https://github.com/facebook/react/blob/e36b38c1cad22f7dff557736cf4b0280106e937e/src/shared/types/checkReactTypeSpec.js#L93-L95) these messages so they are only logged once, no matter how many times the component is rendered.

**Comment by thurt** [comment]
ahh that explains it. i appreciate the point out in source code. thanks guys! @ljharb @aweary
