### ISSUE TITLE
Update to babel 6

### ISSUE THREAD

**Issue by tmcw** [airbnb/enzyme#78]
Ideally enzyme would update to babel 6 so that it can be compatible with applications built in babel 6 land and their configuration files.

**Comment by ljharb** [comment]
Why would the babel version used matter, since the transpiled version is what's published, and `node_modules` shouldn't ever be transpiled?

**Comment by goatslacker** [comment]
We should probably upgrade regardless but not for that reason.

**Comment by lelandrichardson** [comment]
PR Merged
