### ISSUE TITLE
Duplicated Code ?

### ISSUE THREAD

**Issue by windyGex** [airbnb/enzyme#782]
https://github.com/airbnb/enzyme/blob/2b219bf9052a8d75dc002093cd51f6341fa9e0b6/src/ReactWrapperComponent.jsx#L46-L62

And I want to know when the returned value of `getPublicInstance` is `null` ?

**Comment by ljharb** [comment]
Here's [one place](https://github.com/facebook/react/blob/6eebed0535a5e28effb7200783cede7a4bdab7ec/src/test/ReactShallowRenderer.js#L44-L46) where it can return `null`.

You're right about the duplicate code tho - we should pick one as the preferred one, redefine the other in terms of it, and deprecate the other.

**Comment by windyGex** [comment]
Ok. I got it. Thx.
