### ISSUE TITLE
[Question]Undefined is not a constructor when shallow rendering

### ISSUE THREAD

**Issue by albertovilva** [airbnb/enzyme#784]
Hello. Im running enzyme, with mocha, and karma. So far I had no problems, but when trying to test a simple redux-form component Im getting this:

```javascript
undefined is not a constructor (evaluating 'handleSubmit(function (values) {
    	            _this2.handleFormSubmit(values);
    	          })')
```

This is the component code. Its a simple presentational component with redux-form elements. Im guessing its failing in the redux-form own functions? maybe I have to test the connected one? 

```javascript
import React, {PropTypes, Component} from 'react';
import {Field, propTypes as formPropTypes} from 'redux-form';
import {Button, Form, Divider} from 'semantic-ui-react';
import inputText from '../../../components/Forms/Input';

export default class LoginForm extends Component {

  handleFormSubmit(formProps) {
    this.props.login(formProps);
  }

  render() {
    const {handleSubmit, error, submitting} = this.props;
    return (
      <Form onSubmit={handleSubmit((values) => { this.handleFormSubmit(values); })}>
        <Field name='username' type='text' component={inputText} label='Username' />
        <Field name='password' type='text' component={inputText} label='Password' />
        <Divider />
        <strong>{error && error}</strong>
        <Button fluid primary size='big' type='submit' disabled={submitting}>Login</Button>
      </Form>
    );
  }
}

LoginForm.propTypes = {
  ...formPropTypes,
  login: PropTypes.func.isRequired,
  handleSubmit: PropTypes.func.isRequired,
};

```

Thank you very much.

**Comment by ljharb** [comment]
(btw, `{error && error}` is redundant; just `{error}` will work)

The implication is that `handleSubmit` is attempting to `new` the thing passed into it (which in this case, is your arrow function - which can't be `new`ed).

Can you share the code that's rendering `LoginForm`?

**Comment by aweary** [comment]
@ljharb I don't think its related to `new`'ing the arrow function, since this is being compiled with Babel and Babel [doesn't track if an arrow function is `new`'d](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&code=const%20a%20%3D%20()%20%3D%3E%20%7B%7D%3B%0Avar%20b%20%3D%20new%20a()%3B&experimental=false&loose=false&spec=false&playground=true). You can see in the error that its evaluating a regular function.

The error `undefined is not a constructor` indicates that somewhere a variable with the value `undefined` is being `new`'d

**Comment by ljharb** [comment]
I'd still be interested to see the implementation of `handleSubmit`, given that the error's occurring there.

**Comment by aweary** [comment]
Yeah definitely. I expect its [the one provided by `redux-form`](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js).

**Comment by albertovilva** [comment]
@ljharb @aweary Thanks for the help guys! That is the code that renders LoginForm. And yeah the handleSubmit() is the one provided by redux-form.

**Comment by Means88** [comment]
@albertovilva Maybe you should call `wrapper.instance().handleSubmit()` instead of `wrapper.handleSubmit()`.

**Comment by jsj14** [comment]
When using react-select too, I get the same error that hints to a line of code that uses `Object.values()` 

`undefined is not a constructor (evaluating 'Object.values(this.props.options)')`  where this.props.options is an object of objects.

However, Object.keys() doesn't cause a problem. 

Any reason why?

**Comment by ljharb** [comment]
@jsj14 probably because `Object.keys` is in ES5, and thus is in browsers since 2009, and `Object.values` is in ES2017, and is in very few browsers - are you shimming/polyfilling it? I recommend https://npmjs.com/airbnb-browser-shims.

**Comment by glosee** [comment]
In case anyone gets here from Googling... I got this error because I was trying to test a function that I didn't export... I especially hit this when I have files that just export a bunch of stuff inline, and I add a new function. Eg.

```
// myActions.js
export const banana = () => 'banana';
export const orange = () => 'orange';
const tryingToTest = () => 'wrong';

// myActions.spec.js
import * as actions from 'myActions';

describe('tryingToTest', () => {
  const {tryingToTest} = actions;
  expect(tryingToTest()).toEqual(something);
});

// Output
TypeError: undefined is not a constructor (evaluating '') in webpack/test/test_index.js (line 55806)

// My reaction...
:doublefacepalm:
```

**Comment by ljharb** [comment]
If you use airbnb's eslint config, it will catch that for you. `</plug>`

**Comment by glosee** [comment]
Ah I see - currently using `xo` on a project. Will have to see if a similar rule exists there. Thanks @ljharb!

**Comment by ljharb** [comment]
This seems resolved; happy to reopen if not.
