### ISSUE TITLE
state is undefined on child component callback

### ISSUE THREAD

**Issue by Gungrave223** [airbnb/enzyme#787]
So lets say I have a component that is structured as such...

```
class Example extends component {

    handleCallBack(param) {
       this.setState({
           exampleState: state.oldState + param
       })
    }

    render() {
        <Child ref='child' onCallback={this.handleCallBack} />
    }
}
```

then in my test I do something like this...

```
const callback = sinon.spy(Example.prototype, 'handleCallBack');
const wrapper = mount(<Example />)

const childBtn = wrapper.ref('child').find('button');
childBtn.simulate('click');
sinon.assert.calledOnce(callback);
````

The issue that I'm running into is that in handleCallBack this.setState is not a function because the state is undefined..

but i can access the state using wrapper.state() ... so not sure why its undefined when the function is being called from a child component...any ideas?

**Comment by ljharb** [comment]
You need to manually bind instance methods of class-based components in the constructor. (Also, Component not component)

**Comment by Gungrave223** [comment]
Wow that was super fast response...thank @ljharb 

Ignore the case on Component...

also binding the methods in the constructor 

`this.handleCallBack = this.handleCallBack.bind(this);`

resolved my issues...

thanks again
