### ISSUE TITLE
Feature request: way to walk the children in wrapper.find, wrapper.findWhere

### ISSUE THREAD

**Issue by raptoria** [airbnb/enzyme#788]
I saw that it's possible to do this:
expect(wrapper.find(Bar).dive().find('.in-bar')).to.have.length(1);

but I want to be able to return the outer div that has a div inside it that has the text 'File'
eg.
```
<div role="listbox">
<div class="text">File</div>
</div>

```
something like:
`const outerDiv = wrapper.find('div[role=listbox]').dive().findWhere(n => n.text() === 'File'); `

If that makes sense...

**Comment by ljharb** [comment]
```js
const outerDiv = wrapper
  .find('div[role="listbox"]')
  .filterWhere(n => shallow(n).findWhere(n => n.text() === 'File').length > 0);
```
?

**Comment by raptoria** [comment]
cool, I didn't know you could do that. thanks!!!
