### ISSUE TITLE
document.querySelectorAll('.div1') or $('.div1') => undefined

### ISSUE THREAD

**Issue by SansaZhang** [airbnb/enzyme#799]
`const wrapper = mount(<div><div className="div1"></div></div>)`
`wrapper.find('.div1').length`  // 1
`$('.div1').length`   // 0
or 
`document.querySelectorAll('.div1').length` // 0

**Comment by ljharb** [comment]
I'm not sure why you'd expect that `mount` would actually leave behind elements in the DOM for jQuery to select?

**Comment by SansaZhang** [comment]
my test case for a React Component whitch has DOM Manipulation reports  error,
finally I find the reason as above  and   remove the DOM Manipulation,
 I can't understand why   `mount `  elements in the DOM cannot  select via native js or jquery , unlike browser..

**Comment by ljharb** [comment]
It's a testing framework, not a browser simulator. React components should be using ref callbacks to find DOM nodes, not document-based selection - what does your component look like?

**Comment by SansaZhang** [comment]
Thanks for your patience!
the component: [https://github.com/SansaZhang/FiveSixUI-1/blob/master/components/basic/Select/index.js#L376](url)
I use jsdom for browser simulator.
I think I shuold commit issue to jsdom.

**Comment by ljharb** [comment]
It's not a jsdom issue. Your code isn't doing the right thing. Instead of doing `$('.computeFontWidth')`, you should be using React's ref callback API to get a handle to the DOM node. You don't need jQuery for selection at all.

**Comment by SansaZhang** [comment]
you are right!  but jquery  is not in conflict with React~ 
and jsdom'behavior should be consistent with browser..

**Comment by ljharb** [comment]
Yes, it is. Idiomatic React doesn't use jQuery at all if possible, but certainly not for selection.

**Comment by ljharb** [comment]
Also, this isn't a jsdom issue because `mount` doesn't put anything in the DOM for you to select.

**Comment by SansaZhang** [comment]
I see~thanks!
