### ISSUE TITLE
Cannot find module 'react-dom' from 'react-compat.js'

### ISSUE THREAD

**Issue by gyzerok** [airbnb/enzyme#802]
Hello everyone!

While trying to execute tests in my project I get the following error:

```
Cannot find module 'react-dom' from 'react-compat.js'
```

My environment is as follows:
1. `"react": "^15.4.2",`
2. `"react-addons-test-utils": "^15.4.2",`
3. `"jest": "18.1.0",`
4. `"react-native": "0.40.0",`
5. `"enzyme": "^2.7.1",`

In my test file I have imports in the following order:

```js
import * as React from 'react';
import 'react-native';
import { shallow } from 'enzyme';
```

I've read common problems and tried to search through issues, but haven't found anything. Sorry if I missed something.

**Comment by ljharb** [comment]
You also need `react-dom` installed, even if you're not using it.

**Comment by gyzerok** [comment]
@ljharb thank you for blazingly fast answer!

That solved an issue. It seems like it's worth mentioning in the [React Native setup guide](http://airbnb.io/enzyme/docs/guides/react-native.html).
