### ISSUE TITLE
ReactWrapper.simulate() with multiple arguments?

### ISSUE THREAD

**Issue by jurassix** [airbnb/enzyme#808]
Is there an example of supplying multiple args when simulating events on a mounted component?

I'm seeing an inconsistency in the `simulate` API between _shallow_ and _mount_ renderers.

Example _onChange_ handler has customized signature:

```js
  onChange={(event, index, nextValue) => this.setState({ value: nextValue })}
```

_Simulate_ with shallow rendering works fine because api is **simulate(event, ...args)**:

ref: https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L569

```js
const tree = shallow(/* ... */);
// ...setup omitted
el.simulate('change', null, null, 'my value')
```

_Simulate_ with mount is tricky because it seems like I only have access to the first argument? Api is **simulate(event, mock = {})**:

ref: https://github.com/airbnb/enzyme/blob/master/src/ReactWrapper.jsx#L528

```js
const tree = mount(/* ... */);
// ...setup omitted
const mock = { target: { value: 'nextValue' }};
el.simulate('change', mock)
```

Any suggestions on how to supply multiple args is appreciated.

**Comment by jurassix** [comment]
I guess this could be a misunderstanding of _shallow_ vs _mount_. My assumption is that during simulation of a mounted Component the Component is going to extract the Event and then delegate to the onChange provided.

So this seems like it's behaving normally, there must be something wrong inside my the component when it's being rendered with _mount_.

I'll close for now and reopen if needed.

**Comment by good2hear** [comment]
@jurassix were you able to figure out how to do it with mount? 
I was only able to do it with shallow.
Thanks!
