### ISSUE TITLE
Testing input of type *range*

### ISSUE THREAD

**Issue by ekaradon** [airbnb/enzyme#809]
Hello,

I am looking for a way to test an input of type [*range*](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_range_get).

However, even if it is an input, it does not interact the same way than an input of type *text* or *number*. And so I am facing some difficulties to change its value. 
I would like to be able to simulate a click on it, but how to specify then the wanted value/direction? 

So, resigned, I though that I would instead use `simulate('change')`, however, it looks like it does not take in account the `disabled` property (may be related to #386 or something). 

Example:

```
  "dependencies": {
    "enzyme": "^2.7.1",
    "must": "^0.13.4",
    "react": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2",
    "sinon": "^1.17.7"
  }
```

```
import React from 'react';
import sinon from 'sinon';
import expect from 'must';
import {shallow, mount} from 'enzyme';

it('should take in account the disabled property with shallow', () => {
    const spy = sinon.spy();
    const RangeInput = (on_change) => <input disabled={true} onChange={on_change} type='range'/>;

    const tested_range_input = shallow(RangeInput(spy));
    tested_range_input.simulate('change');
    expect(spy.callCount).to.eql(0);
});

it('should take in account the disabled property with mount', () => {
    const spy = sinon.spy();
    const RangeInput = (on_change) => <input disabled={true} onChange={on_change} type='range'/>;

    const tested_range_input = mount(RangeInput(spy));
    tested_range_input.simulate('change');
    expect(spy.callCount).to.eql(0);
});

```

Output:

```
 FAIL  src/App.test.js
  ● should take in account the disabled property with shallow

    AssertionError: 1 must be equivalent to 0
      
      at Object.<anonymous>.it (src/App.test.js:12:69)

  ● should take in account the disabled property with mount

    AssertionError: 1 must be equivalent to 0
      
      at Object.<anonymous>.it (src/App.test.js:21:69)

  ✕ should take in account the disabled property with shallow (9ms)
  ✕ should take in account the disabled property with mount (19ms)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total

```
Is there something I am doing wrong? Have you any idea for simulating use of input of type *range*?

Thanks!

**Comment by ljharb** [comment]
"range" is just for the browser UI - you interact with it programmatically exactly the same as you would a "text" input.

**Comment by ekaradon** [comment]
Well, it was my thought, but then I still have the problem with the `disabled` property.

**Comment by ljharb** [comment]
The browser simply won't fire `change` on a disabled input, so it's an invalid simulation - there's no need to test the browser here (nor test that React properly renders the "disabled" attribute), so I'd just remove that test entirely.

**Comment by ekaradon** [comment]
Ok, thank you @ljharb ! :)
