### ISSUE TITLE
Error: ShallowWrapper::state() can only be called on the root

### ISSUE THREAD

**Issue by joetidee** [airbnb/enzyme#814]
I am getting this error:

`Error: ShallowWrapper::state() can only be called on the root`

Here is my test:

```
it('default "errors" state is an empty object', () => {
    const router = {'react-router': {}};
    const wrapper = shallow(<IntlProvider><SignUpForm router={router} /></IntlProvider>);
    expect(wrapper.find(SignUpForm).state('errors')).to.equal({});
});
```

Would anyone be able to tell me how I can access/test the state of the `SignUpForm` component?

**Comment by ljharb** [comment]
I think #431 might be relevant here.

**Comment by ljharb** [comment]
You want `wrapper.dive()` so that it re-shallow-renders the SignUpForm.

**Comment by dabit1** [comment]
I finally found a very good solution to get a wrapper from a decorated component. For shallowed components you can use `dive()` but there is no similar method for mounted components. This is the solution I did:

```javascript
const wrapper = mount(shallow(<MyComponent />).get(0))
```

Works like a charm :)

**Comment by jeremy-brooks** [comment]
this would work like a charm if my component didn't contain a "Link" component, it requires that it is wrapped in a router to render. So it is currently impossible for me to render the component and then access its state in a test as it will always be a child node.

**Comment by jumpinjan** [comment]
@dabit1   Thank you very much your tip worked like a charm for me too

**Comment by paddotk** [comment]
@dabit1 When I do that I just get a bunch of errors:
`Warning: Failed prop type: Invalid prop 'Component' supplied to `WrapperComponent`.`
`Error: Uncaught [TypeError: Cannot read property 'hasOwnProperty' of null]`[..]

**Comment by rnagy90** [comment]
Hi!
I can verify that it still works in 2019 (in contrast of the react intl team's enzyme + jest tutorial which doesn't :( )
```
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-intl": "^2.9.0",
"jest": "^24.8.0",
"enzyme": "^3.10.0",
"enzyme-adapter-react-16": "^1.14.0"
```
