### ISSUE TITLE
How to get a named prop from an instance of a component?

### ISSUE THREAD

**Issue by joetidee** [airbnb/enzyme#816]
For example:
```jsx
    describe('<Bar>', function() {
        it('receives the correct props', function () {
            let wrapper = mount(<Foo someProp="someVal"><Bar /></ Foo>);
            // how to test if Bar has received the correct props
        });
    });
```

**Comment by ljharb** [comment]
there's no guarantee that `Foo` renders the `children` you give it. What's the implementation of `Foo` here?

**Comment by aweary** [comment]
If `Foo` is rendering and passing new props to `children` (assuming you're using `React.cloneElement` or something?) you should be able to just do:

```js
expect(wrapper.find(Bar).prop("bar")).to.equal("bar");
```

**Comment by joetidee** [comment]
I'm not looking to test the value of a prop, just that the prop exists.

**Comment by ljharb** [comment]
You can use `expect(wrapper.find(Bar).props()).to.contain.key('bar')` if you want, but it's far better to test the value.

**Comment by aweary** [comment]
Either way, the API for finding the component and accessing the prop is the same. I verified this works locally, so I'm going to close this out but feel free to ask any clarifying questions.
