### ISSUE TITLE
Shallow rendering doesn’t work with non-default exports

### ISSUE THREAD

**Issue by kirkstrobeck** [airbnb/enzyme#817]
To get around a `Connect` issue, I’m exporting both the component as `component` and the Connect-wrapped component as `default`.

When importing as `import { component } from '../index.js';`, `component` in `shallow` acts as if it has no relation to the imported component and simply shows the JSX I wrote in the `shallow` function call.

**Comment by aweary** [comment]
React components have to be capitalized (`Component` works, `component` doesn't), can you try exporting it with the correct naming convention and see if that works?

**Comment by ljharb** [comment]
This seems answered; happy to reopen if not.
