### ISSUE TITLE
Prop equality hook

### ISSUE THREAD

**Issue by suchipi** [airbnb/enzyme#818]
Some test frameworks allow asymmetric matching, via special functions or values, for example Jest:
```js
const actual = "foo";
expect(actual).toEqual(expect.stringMatching(/f/)) // passes
```

It'd be nice if we could use these with enzyme:
```jsx
const Something = () => (
  <div>
    <span id="foo">Hello!</span>
  </div>
);

const wrapper = mount(<Something />);
expect(wrapper.containsMatchingElement(
  <span id={expect.stringMatching(/f/)} />
)).toBe(true); // doesn't work right now
```

But it's obviously not enzyme's responsibility to implement these on behalf of the frameworks.

I'm thinking it'd be nice if enzyme had an API for hooking into its equality checking so that frameworks could feature asymmetric matching integration with enzyme.

It looks like the relevant change needs to occur here: https://github.com/airbnb/enzyme/blob/c64474073e71277a940b9c93b14c1c01bde94b66/src/Utils.js#L123

One way it could be implemented would be with a shared Symbol. This is similar to what util.inspect does:
```jsx
import { mount, isEqualSymbol } from "enzyme";

const myAsymmetricMatcher = {
  [isEqualSymbol]: (otherValue) => { // receives "foo" in this case
    return /f/.test(otherValue); // returns true to indicate values are equal
  },
};

const wrapper = mount(<Something />);
expect(wrapper.containsMatchingElement(
  <span id={myAsymmetricMatcher} />
)).toBe(true); // passes
```

cc @cpojer @vjeux

**Comment by ljharb** [comment]
`enzyme` needs to be able to run in older nodes and browsers, so `Symbol` isn't an option.

**Comment by suchipi** [comment]
Guess it'd be a string key with a low chance of collision, then:
```js
Object.defineProperty({}, "__enzymeIsEqual", {
  value: (otherValue) => /f/.test(otherValue);
});
```

**Comment by ljharb** [comment]
It might be simpler, **if** we decide to go this route, for enzyme to export a `match` function that when invoked with a callback function, returns an object that enzyme is capable of detecting reliably - ie, you'd do something like:
```jsx
import { match, mount } from 'enzyme';
import { expect } from 'chai';

function Something() {
  return (
    <div>
      <span id="foo">Hello!</span>
    </div>
  );
}

const wrapper = mount(<Something />)
expect(wrapper.containsMatchingElement(
  <span id={match(propValue => /f/.test(propValue))} />
)).toBe(true); // passes
```

**Comment by suchipi** [comment]
That would work cross-framework without the need for changes in the framework, so that would be good. It might be nice to still have an option for frameworks to be able to make their own values "match-compatible", though. But I can see the argument that you wouldn't want to support both APIs.

**Comment by suchipi** [comment]
Apparently I didn't need this in the last 8 months, so I'll close this 😉
