### ISSUE TITLE
You are manually calling a React.PropTypes validation function...

### ISSUE THREAD

**Issue by sylvain-hamel** [airbnb/enzyme#819]
I get warnings like this when running my tests:

```
You are manually calling a React.PropTypes validation function...
```

Here is the stack trace:

![image](https://cloud.githubusercontent.com/assets/1754010/23244039/b58df738-f950-11e6-93cf-a3c4b5a00173.png)

Am I missing something?

**Comment by ljharb** [comment]
This is a warning from React itself, not enzyme. Do you perhaps have a custom propType function in your code?

**Comment by sylvain-hamel** [comment]
I know it's from React, but I only get it when I test the component with `shallow`. I'm converting my tests from `ReactTestUtils.createRenderer()` to enzyme. I did not get this warning before the conversion. That is why I assumed this is related to enzyme. There is no custom propType function involved.

**Comment by ljharb** [comment]
Can you share your test code?

**Comment by sylvain-hamel** [comment]
the test (I took out the expectations)

```
    fit('should work...', ()=> {
      const wrapper = shallow(<Field showLabel={true} entity={entity} schema={schema} label="theLabel" field="a" setValue={()=>null} errors={[]}/>);
    });
```

I trimmed down the component to this, and I still get the error

```
export const Field = ({schema, entity, field, setValue, showLabel = true, label, required, readonly, maxlength, errors, input, readMode = false}) =>
 <div></div>;

Field.propTypes = {
  schema: PropTypes.object.isRequired,
  entity: PropTypes.object.isRequired,
  field: PropTypes.string.isRequired,
  showLabel: PropTypes.bool,
  label: PropTypes.string,
  required: PropTypes.bool,
  readonly: PropTypes.bool,
  readMode: PropTypes.bool,
  maxlength: PropTypes.number,
  setValue: PropTypes.func.isRequired,
  errors: PropTypes.array.isRequired,
  input: PropTypes.element
};

```

It's the second (#820) strange issue I get. Could this be related the fact that I'm using a defective browserify build (see my last comment in #806)?

**Comment by aweary** [comment]
Can you make sure that you all React packages you have installed are on the same version? (`react`, `react-dom`, `react-addons-test-utils`)

**Comment by sylvain-hamel** [comment]
@aweary, what I have is:

- https://npmcdn.com/react@15.4.0/dist/react-with-addons.js
- https://npmcdn.com/react-dom@15.4.0/dist/react-dom.js

**Comment by sylvain-hamel** [comment]
Issues resolved : My project does use react 15. But my tests ran under react 14. My browserify build of enzyme uses react 14 because by default the enzyme project is set to react 14 so when I browserifyed it, it embedded react 14 in the bundle.
