### ISSUE TITLE
[dive]: Store dived component as a variable?

### ISSUE THREAD

**Issue by joncursi** [airbnb/enzyme#822]
I have a HOC that wraps a pure component. This test works:

```jsx
it('an integration test', function () {
    const wrapper = shallow(
      <DropDownHOC
        {...minProps}
      />,
    );

    expect(
      wrapper.dive().dive({ context }).prop('opened')
    ).toEqual(false);

    wrapper.dive().dive({ context }).prop('onBackdropPress')();

    expect(
      wrapper.dive().dive({ context }).prop('opened')
    ).toEqual(true);
  });
```

This test fails:

```jsx
it('an integration test', function () {
    const wrapper = shallow(
      <DropDownHOC
        {...minProps}
      />,
    );
    const pure = wrapper.dive().dive({ context });

    expect(
     pure.prop('opened')
    ).toEqual(false);

    pure.prop('onBackdropPress')();

    expect(
      pure.prop('opened') // fails here, pure doesn't know about the update
    ).toEqual(true);
  });
```

Even if I call `pure.update()` before asserting the second time on `opened`, the pure component is not updated. Seems like this approach only works if operations are taken on the initial `wrapper`.

Is it possible to store a reference to the pure component as a variable, and run the interactions and assertions on that variable, rather than having to dive into it multiple times from `wrapper` during each test?

**Comment by ljharb** [comment]
What does the `onBackdropPress` prop do?

What you're describing (with `pure.update()`) should be working, but if it requires interacting with the original `wrapper`, then I wouldn't really expect it to.

**Comment by joncursi** [comment]
The pure component is wrapped using recompose like so:

```
export const DropDown = ({
  ...
  handleToggleOpenState,
  onMenuToggle,
  open,
  ...
}) => (
    <Menu
      onBackdropPress={onMenuToggle}
      opened={open}
    >

      {...}

    </Menu>
  );
};

const enhance: Function = compose(
  withState('open', 'handleToggleOpenState', false),
  withHandlers({
    onMenuToggle: (props): Function => () => {
      props.handleToggleOpenState(!props.open);
    },
  }),
);

export default enhance(DropDown);
```

So, calling `onBackdropPress` on the pure Menu invokes `onMenuToggle` upstream in the HOC, and then calls `handleToggleOpenState` which updates the `open` state. Then everything re-renders top-down and the pure component should have a new `open` state.

**Comment by ljharb** [comment]
ok - so given that, you need work with the HOC, and can't work with the wrapped component. What I'd recommend is asserting that your HOC shallow-renders your pure component with the expected props, and then, separately, manually shallow-render the pure component directly and test its behavior.

**Comment by joncursi** [comment]
Will do, thank you!

While I have your attention on this topic, out of curiosity, do you employ HOCs in this pattern? Or stick mostly to the `class` syntax? I started down the path of converting my classes -> stateless functional components, and wrapping them with recompose. Hitting some snags along the way, so I'm very curious to know what the bright minds out there are doing. Thanks again!

**Comment by ljharb** [comment]
I think we tend to use all of the patterns :-) it really depends on the use case. The important thing is to encapsulate things properly in testable, conceptually separate components.
