### ISSUE TITLE
Allow contains() to take a selector

### ISSUE THREAD

**Issue by probablyup** [airbnb/enzyme#824]
Apologies if this has been brought up before, but would be nice to be able to rewrite:

```js
expect(shallow(<div><Foo /></div>).find('Foo')).toHaveLength(1);
```

as 

```js
expect(shallow(<div><Foo /></div>).contains('Foo')).toBe(true);
```

**Comment by ljharb** [comment]
`expect(shallow(<div><Foo /></div>).containsMatchingElement(<Foo />)).to.equal(true)`

**Comment by yaycmyk** [comment]
Does that work if my element has props?

**Comment by ljharb** [comment]
It should :-) try it and see!
