### ISSUE TITLE
Print selector when an element is not found

### ISSUE THREAD

**Issue by nhunzaker** [airbnb/enzyme#825]
We frequently encounter this error:

> Method “simulate” is only meant to be run on a single node

Which is fantastic, that it fails when it can't find anything. However it would be wonderful if the error message included a string name for _what_ element was missing. Something like:

> Unable to call “simulate” on "MyForm > button". Selector found no match.

or

> Unable to call “simulate” on "MyForm > button". Found more than one match

I'd be happy to dig into this, but I was curious if I missed any prior discussion or if there's some active dev in this area.

**Comment by ljharb** [comment]
That would require the last-used selector to be persisted statefully. There's also `.findWhere`, `.filterWhere`, `.find(Foo)`, etc, where there's no string selector at all.

I could imagine an option to the find methods that throws whenever no match is found, but I can't conceive of any other way to do it. Typically you'd assert on the `.length` of your wrapper before attempting to call any methods on it, so that your tests are robust.

**Comment by nhunzaker** [comment]
> Typically you'd assert on the .length of your wrapper before attempting to call any methods on it, so that your tests are robust.

I don't want to fall too much into the territory of asking for advice, but I want my tests to be robust. I'll admit that I rely on the error raised when a selector isn't found to halt a test for me. It's very convenient.

Do you run an assertion on the length before continuing forward, like:

```javascript
// Assuming I am using Jest, happy to translate to another assertion method for clarity
let button = wrapper.find('button')

expect(child.length).toBeGreaterThan(0)

button.simulate('click')

// continue test...
```

Or do you throw a specific exception, like:

```javascript
// Assuming I am using Jest, happy to translate to another assertion method for clarity
let button = wrapper.find('button')

if (button.length <=0) {
  throw new Error('Unable to find submit button for Login form')
}

button.simulate('click')

// continue test...
```

In all cases, it would be valuable to me for Enzyme take care of this (or at least try). Particularly when selecting components by their display name. It allows affordances to the test author for giving better feedback when a test fails that doesn't require them to as pedantic.

> I could imagine an option to the find methods that throws whenever no match is found

What about passing `true` as a second argument to be more strict, like:

`wrapper.find('button', true)`

**Comment by ljharb** [comment]
I write the former.

The reason why it wouldn't make sense for enzyme to throw in those cases is that sometimes, finding zero items is a *desired* use case - and your assertion might be `expect(wrapper).to.have.lengthOf(0)`.

Passing an additional argument might work, but a boolean arg is an antipattern, and an options arg is a lot of complexity to add just so you don't have to write a more explicit assertion (thereby making your tests more clear and straightforward).

**Comment by nhunzaker** [comment]
Writing an assertion that way makes sense to me. Thank you for taking the time to explain it.

As for the original issue. It sounds like there isn't much of a desire to add this to Enzyme. If I were to explore making the improvement to the error message, would there be interest in accepting a PR for it? 

You mentioned "That would require the last-used selector to be persisted statefully". Would a change like this work against your desired direction for the way Enzyme works?

**Comment by ljharb** [comment]
I've looked into this in the ancient past for persisting a selector more reliably on jQuery objects.

If you can write a PR that handles all the edge cases of ways to refine the list of wrapped nodes, such that string selectors (which are inferior and unofficially discouraged) aren't given special standing, then I'm always happy to see error messages improved!

**Comment by nhunzaker** [comment]
Cool. It's good to know that string selection is discouraged. I'll go ahead and close this out, but make a reminder to dig in and see what I'm able to do.

Thanks for your time and thoughts!
