### ISSUE TITLE
Container with addEventListener in componentWillMount, simulate click is not helping 

### ISSUE THREAD

**Issue by AnilGayakwad** [airbnb/enzyme#828]
Trying to test a container with addEventListener in componentWillMount,  

<pre>
export const clickToChatClick = (data) => {
   window._chatCount = window._chatCount || [];
  window.chatCount.push(data);
}  /* This is dummy method */

export const handleClick = (e) => {
  if (e.target && e.target.className == "clickToChat") {
    const dataChatAttr = e.target.attributes && e.target.attributes['data-chat'] ? e.target.attributes['data-chat'].value : '';
    clickToChatClick(dataChatAttr);
  }
}

export class HomePage extends React.Component {
  componentDidMount() { 
    document.getElementById('appt') &&
    document.getElementById('appt').addEventListener('click', (e) => {
     handleClick(e);
    });
  }
  render() {
    &#60; div id="appt"&#62;
    ...
    &#60; button className="clickToChat" data-chat="clickToChatTest" &#62;Testing chat click event &#60; /button&#62;
   ...
   &#60; /div&#62;
  }
</pre>

The test is the simulate the click event

<pre>
it(' componentDidMount addEventListener', () => {
  const wrapper = mountWithIntl(
        &#60; HomePage intl={intl} / &#62;
    ); 
    expect(HomePage.prototype.componentDidMount.isSinonProxy).toBe(true);
    wrapper.find('button').simulate('click');
    console.log(window._tfsq.length);
});
</pre>

Simulate is not helping .

**Comment by ljharb** [comment]
what is `.Simulate`? do you mean `.simulate('click')`?

At any rate, I highly recommend not using addEventListener, and just using `<div onClick={handleClick}>`, which is a noop on the server (before didMount).

**Comment by AnilGayakwad** [comment]
@ljharb  Yes it is .simulate('click'), I updated it.

**Comment by ljharb** [comment]
If you fix the code so that you're using React's event handlers instead of native ones, I think you'll have a much easier time of it.

**Comment by AnilGayakwad** [comment]
https://github.com/airbnb/enzyme/issues/832

**Comment by ljharb** [comment]
@AnilGayakwad i'm not sure why you filed a separate issue. What happens if you use `onClick` rather than `addEventListener`?

**Comment by AnilGayakwad** [comment]
Achieved this with add a helper component, calling this viva action on click .
