### ISSUE TITLE
Cannot read property 'be' of undefined

### ISSUE THREAD

**Issue by eldyvoon** [airbnb/enzyme#829]
My not working test code

```
import React from 'react';
import {shallow, mount} from 'enzyme';
import TopNav from '../components/topNav';

it('Navbar should existed', () => {
    const nav = shallow(<TopNav />);
    expect(nav.find('#topNav').exists()).to.be(true);
});
```

My topNav Component.

```
import { Component } from 'react';
export default class topNav extends Component {
    render(){
        return(
            <div id="topNav"><strong class="testtest">Nav bar</strong></div>
        )
    }
}
```
I have no clue what is wrong here. I took the [exact example from the API doc of enzyme](http://airbnb.io/enzyme/docs/api/ShallowWrapper/exists.html). But when I do this, it worked.

```
it('Navbar should existed', () => {
    expect(shallow(<TopNav />).is('#topNav')).toBe(true);
});
```

**Comment by ljharb** [comment]
Are you using mocha, and chai's expect? Your matcher syntax looks like the expect package, or jest/jasmine

**Comment by eldyvoon** [comment]
@ljharb  I used airbnb's enzyme http://airbnb.io/enzyme/docs/api/ShallowWrapper/exists.html

**Comment by ljharb** [comment]
That's fine, but the code in the example works with mocha and chai, so copying it verbatim won't work with jest. Indeed, `.toBe` is what you want to use with jest.
