### ISSUE TITLE
How to unmount mounted components?

### ISSUE THREAD

**Issue by pierlo-upitup** [airbnb/enzyme#83]
It would be really nice if the `ReactWrapper` would expose a `.unmount()` function that would behind the scenes perform something similar to doing `mountedComponent.getInstance().componentWillUnmount();` for those components rendered with  `mount()`. 
It would be also OK if the docs would mention what is the recommended way of doing this, too.

A use case for this is to prevent leaking listeners bound during `componentWillMount` calls.

**Comment by lelandrichardson** [comment]
I agree this would be a good addition. It should be easy enough to do if you want to PR it yourself, or else I will try and get to it soon!  Should be just adding a way for the ReactWrapperComponent to conditionally unrender the mounted component through some state flag.

**Comment by pierlo-upitup** [comment]
Sounds cool! I will try to give it a whirl in the next days, but can't promise anything!

**Comment by pierlo-upitup** [comment]
I wonder if it would make sense to additionally perform an `React.unmountComponentAtNode(this.component.instance().getDOMNode());`...

**Comment by lelandrichardson** [comment]
in `mount`, the component you are rendering is actually wrapped by a parent component to allow for the setting of props, passing of context, etc.  As a result, just conditionally rendering the child component should make the child component go through a full "unmount" lifecycle, so I don't think this would be necessary...

**Comment by lelandrichardson** [comment]
Update: i'd like to add these methods, but we will need to wait until 2.0 to do so. These methods will not work without a DOM being present before requiring react since react's internals cache a reference to `document`.

**Comment by pierlo-upitup** [comment]
@lelandrichardson thanks for the update!

**Comment by lelandrichardson** [comment]
This feature is now merged in. It will be in the next release.

**Comment by crisu83** [comment]
@lelandrichardson mind adding a link to the change to this issue? Thanks!
