### ISSUE TITLE
Jest.mock cannot find request module error

### ISSUE THREAD

**Issue by eldyvoon** [airbnb/enzyme#830]
I got error of Cannot find module '../request' from 'CrudList.spec.js'

I followed the async example, I've no clue what's the problem. My file structure look like this

https://i.stack.imgur.com/dMvjt.png

**Comment by ljharb** [comment]
This seems like a jest-specific question, and has nothing to do with enzyme.

**Comment by eldyvoon** [comment]
sorry posted in the wrong place.
