### ISSUE TITLE
container with componentWillMount which has addEventListener, How to test this.

### ISSUE THREAD

**Issue by AnilGayakwad** [airbnb/enzyme#832]
The App index.js is 
<pre> 
 import React from 'react';

 import Header from 'containers/Header'; 
 import Footer from 'components/Footer';
 import { connect } from 'react-redux';
 import { createStructuredSelector } from 'reselect'; 

export const clickToChatClick = (data) => {
   window.chatCount = window.chatCount || [];
  window.chatCount.push(data);
}  /* This is dummy method */

 export const clickToChatEvent = (e) => {
   if (e.target && e.target.className == "clickToChat") {
     const dataChatAttr = e.target.attributes && e.target.attributes['data-chat'] ? e.target.attributes['data-chat'].value : '';
     clickToChatClick(dataChatAttr);
   }
 }

 export class App extends React.Component{
   componentDidMount() { 
     console.log(document.getElementById('appt'));
     document.getElementById('appt') &&
     document.getElementById('appt').addEventListener('click', (e) => {
      clickToChatEvent(e);
     });
   }

     render() {
       return (
         &#60;div&#62;
           &#60;Header /&#62;
           {React.Children.toArray(this.props.children)}
           &#60;Footer /&#62;
         &#60;/div&#62;
       );
     }
 }

 App.propTypes = {
   children: React.PropTypes.node,
 };

 //export default App;
 const mapStateToProps = createStructuredSelector({});

export function mapDispatchToProps(dispatch) {
  return {
    dispatch
  };
}
export default connect(mapStateToProps, mapDispatchToProps)(App);
</pre>

Tried to mock the child component for mount 
<pre>
describe('<App Click event which checks for the clickToChat class/>', () => {
it('calls componentDidMount', () => {
window.chatCount = [];
     const store = {
         getState: function() {
             return {};
         },
         subscribe: function() {
             return {};
         },
         dispatch: function() {
             return {};
         },
         get: function() {
             return {};
         }
     };

jest.mock('containers/Header', () => 'Header');
 jest.mock('components/Footer', () => 'Footer'); 

sinon.spy(App.prototype, 'componentDidMount');
     console.log(App.prototype);
     const children = (&#60;div &#62; &#60;button className="clickToChat" data-chat="clickToChatTestCaseTest"&#62; Test Case Click &#60;/button&#62; &#60;/div&#62;);
     const wrapper = mount(
       &#60;Provider store={store}&#62;
         &#60;App&#62;
           {children}
         &#60;/App&#62;
       &#60;/Provider&#62;
     );

    expect(App.prototype.componentDidMount.isSinonProxy).toBe(true);
     expect(App.prototype.componentDidMount.calledOnce).toBe(true);
     const buttonOnPage = wrapper.find('button').first();
     buttonOnPage.simulate('click');

     const modal = wrapper.find('.clickToChat').first() 
     modal.simulate('click');
     console.log("===================");
     console.log(window.chatCount);
     console.log("===================");
 });
});
</pre>

Getting error "TypeError: state.get is not a function", 
mock is not helping.
<pre>
   jest.mock('containers/Header', () => 'Header');
   jest.mock('components/Footer', () => 'Footer'); 
</pre>

If we remove  "&#60; Header /&#62;" from "index.js" render() it works, But the "window.chatCount" is still empty [] it has to contain one item with "clickToChatTestCaseTest" as value.
<pre>
 console.log(document.getElementById('app'));  // is displayed null  
</pre>

**Comment by ljharb** [comment]
I have the same question here as I did in #828 - why are you using addEventListener instead of the `onClick` prop?

**Comment by AnilGayakwad** [comment]
@ljharb This has to generic for all the page's, in my application whoever want's to get there click event notified to chat, they have to add the className="clickToChat"  and the prop data-chat="mail button" which to be sent for chat.

**Comment by ljharb** [comment]
Right, but you're rendering the div with the ID and in the same component, adding the listener. Just add the listener directly in the jsx.

**Comment by AnilGayakwad** [comment]
{React.Children.toArray(this.props.children)} , Is one which render components base on router.
To make it understand i have added that id. 
Its actually document.getElementById('app')

**Comment by ljharb** [comment]
This doesn't sound like the way you want to be working with the DOM in React - whatever's passing the children should be passing a prop callback; you shouldn't need to crawl the DOM.

At any rate, to your original question - `simulate('click')` can only call `onClick` prop methods. If you've used `addEventListener`, to trigger that click, you have to extract the DOM node, and use native DOM APIs to trigger it.

**Comment by AnilGayakwad** [comment]
whatever's passing the children should be passing a prop callback;  
Do help me with, some example / link. which i can refer to.
