### ISSUE TITLE
Stubbing inconsistencies with mounted components

### ISSUE THREAD

**Issue by alexadusei** [airbnb/enzyme#837]
Hi there. Say I have a container and a presentational component. Let's say the presentational component is just a form and a submit button via Semantic UI React.

Here's the container:

```javascript
import React, {Component} from 'react'
import {MessageTextArea} from 'components'

export default class MessageTextContainer extends Component {
  constructor (props) {
    super(props)

    this.state = {
      text: '',
    }

    this.handleChange = this.handleChange.bind(this)
    this.handleSubmit = this.handleSubmit.bind(this)
  }

  handleChange (e) {
    const text = e.target.value

    console.log('handleChange() has been called:', text)
    this.setState({text})
  }

  handleSubmit () {
    console.log('handleSubmit() has been called')
  }

  render () {
    return <MessageTextArea
             text={this.state.text}
             onChangeText={this.handleChange}
             onSubmitText={this.handleSubmit}/>
  }
}
```

The two functions are `handleSubmit` and `handleChange` when the user types in the text area. Here's the presentational component:

```javascript
import React, {PropTypes} from 'react'
import {Form, TextArea, Button} from 'semantic-ui-react'

export default function MessageTextArea ({text, onChangeText, onSubmitText}) {
  return (
    <div>
      <Form>
        <TextArea value={text} onChange={onChangeText} />
        <Button type='button' content='Submit' onClick={onSubmitText} />
      </Form>
    </div>
  )
}
```

Now, all I want to do is test the container component right now. I want to verify that the functions are being binded and passed down as props to the presentational component. I'm testing that the presentational component is receiving these props by using it to call these functions, and expect the container to respond to them. 

I'm using Sinon to stub the container functions. I have a test for `handleSubmit` and one for `handleChange`. This works for `handleSubmit`, but not for `handleChange`, which are both written in the exact same way.. Here are the tests of interest (for the sake of this example, I'm using Sinon's `spy` function to see the outputs).

```javascript
import React from 'react'
import {mount} from 'enzyme'
import {expect} from 'chai'
import {spy} from 'sinon'

import {MessageTextContainer} from 'containers'
import {MessageTextArea} from 'components'

describe('<MessageTextContainer/>', () => {
  it('should bind handleSubmit() function to <MessageTextArea/>', () => {
    const wrapper = mount(<MessageTextContainer/>)

    const handleSubmitSpy = spy(wrapper.instance(), 'handleSubmit')
    const MessageTextAreaComponent = wrapper.find(MessageTextArea)
    const event = {target: {value: 'This works, and is called by a Sinon spy'}}

    MessageTextAreaComponent.prop('onChangeText')(event)

    expect(handleSubmitSpy.calledOnce).to.equal(false)
    MessageTextAreaComponent.prop('onSubmitText')()
    expect(handleSubmitSpy.calledOnce).to.equal(true)
  })

  it('should bind handleChange() function to <MessageTextArea/>', () => {
    const wrapper = mount(<MessageTextContainer/>)

    const handleChangeSpy = spy(wrapper.instance(), 'handleChange')
    const MessageTextAreaComponent = wrapper.find(MessageTextArea)
    const event = {target: {value: 'This works, but is not called by a Sinon spy'}}

    expect(handleChangeSpy.calledOnce).to.equal(false)
    MessageTextAreaComponent.prop('onChangeText')(event)
    expect(handleChangeSpy.calledOnce).to.equal(true)
  })
})
```

Here's the output of the test from Mocha:
![screen shot 2017-03-04 at 10 16 33 pm](https://cloud.githubusercontent.com/assets/9813064/23584210/5c3a9b52-0128-11e7-8331-7f2a3746591b.png)

As you can see by the output, the methods _are_ being passed and are being called, except only `handleSubmit` is successfully being called by a spy. Is there any reason for this behaviour? Seems a bit inconsistent, and I can't find anything in docs about this particular case.

I have a sample [repo](https://github.com/alexadusei/react-enzyme-sinon) available along with the [test cases ](https://github.com/alexadusei/react-enzyme-sinon/blob/master/app/containers/MessageText/tests/MessageTextContainer.test.js)

**Comment by ljharb** [comment]
I wouldn't expect either of those to work. Spy on the prototype methods *before* creating the jsx elements, and make sure you're cleaning up your spies after every test.

**Comment by alexadusei** [comment]
Is there a reason in particular you wouldn't expect them to work? I'm wondering why the `handleSubmit` test case worked given the setup.

You're right though, using the prototypes seemed to have corrected the issue. For closure:

```javascript
  it('should bind handleChange() function to <MessageTextArea/>', () => {
    const handleChangeSpy = spy(MessageTextContainer.prototype, 'handleChange')
    const wrapper = mount(<MessageTextContainer/>)
    const MessageTextAreaComponent = wrapper.find(MessageTextArea)
    const event = {target: {value: 'This works with prototypes'}}

    expect(handleChangeSpy.calledOnce).to.equal(false)
    MessageTextAreaComponent.prop('onChangeText')(event)
    expect(handleChangeSpy.calledOnce).to.equal(true)
    handleChangeSpy.restore()
  })
```

Thanks @ljharb!

**Comment by ljharb** [comment]
Because they're bound in the constructor, and passed by reference as props, such that your stub shouldn't have any effect.
