### ISSUE TITLE
Testing cursor position for controlled inputs in enzyme

### ISSUE THREAD

**Issue by smoholkar** [airbnb/enzyme#839]
I am working on a controlled input and am explicitly setting the cursor position in componentWillUpdate() & onKeydown, onChange. The behavior seems right but I'm trying to write some tests for this. The selectionStart always seems to be 0 even if I set it explicitly. How do I go about testing it ?

This is what my test looks like: 

```
const component = mount(<FileOne {...properties} />);
    const input = component.find('input');
    console.log('current cursor position:', input.node.selectionStart); // this will be 0
    // set cursor position to 2
    input.node.selectionStart = 2;
    console.log('current cursor position 1:', input.node.selectionStart); // this is 2
    // call onFocusHandler
// even if I use simulate('focus') here it doesn't help
    component.instance().onFocusHandler();
    // cursor position now should still be 3
    console.log('current cursor position 2:', component); // this is always zero. It should be 2 How do I test this?
```

```
**FileOne.jsx**
<Wrapper1>
 <Wrapper2 handleKeyDown={this.handleKeyDown} onFocusHandler={this.onFocusHandler}/>
</Wrapper1>

**two.jsx**
<Wrapper3 handleKeyDown={props.handleKeyDown} onFocusHandler={props.onFocusHandler}/>

**wrapper3.jsx**
<input class='abc' onKeyDown={props.handleKeyDown} onFocus={props.onFocusHandler}/>

**Comment by khawkinson** [comment]
@smoholkar were you ever able to find a solution to this?

**Comment by AlexGoodwin** [comment]
Also curious to see if this is a bug, or if there's a way to test this?

**Comment by ljharb** [comment]
I'd suggest avoiding use of `simulate`; it doesn't actually simulate anything. Instead, explicitly invoke the prop you're interested in.

Being able to test text selection requires that you get the DOM node in question, and use the native text selection APIs. I'd be happy to accept a PR to the docs to illustrate how this can be done, if someone's interested, but I think it's outside the scope of enzyme.
