### ISSUE TITLE
How to deal with prop warnings with shallow rendering?

### ISSUE THREAD

**Issue by rtymchyk** [airbnb/enzyme#843]
I have the following setup:
```javascript
const RootComponent = (props) => {
  return <ChildComponent>Hello</ChildComponent>
} 
```

```javascript
const ChildComponent = ({children, connectedProp}) => {
   return <span>{children} ~ {connectedProp}</span>
}
ChildComponent.propTypes = {
  children: React.PropTypes.node.isRequired,
  connectedProp: React.PropTypes.string.isRequired
}
export default connect({ connectedProp: ... }, ChildComponent);
```

`connect` here comes from Redux, which injects props from a global state, but it could be connected by anything else.

If I test `RootComponent` with `shallow(<RootComponent/>)`, I get a 
```
Warning: Failed prop type: The prop `connectedProp` is marked as required in `ChildComponent`, but its value is `undefined`.
```

The shallow render is validating the propTypes of the child components. Essentially I don't expect this, because those props are not provided by the root, but by a connector, and I'm not testing the behaviour of the connector. Is there a proper way of removing this warning? Should I just not mark them as required?

**Comment by ljharb** [comment]
You need to manually provide the `connectedProp` then.

What's typically done is that you shallow-render the connector, and use `.dive()` so your test doesn't have to repeat the implementation details of the connector.

**Comment by rtymchyk** [comment]
I didn't really understand the above, because that doesn't seem to allow you to provide props for children components that have connectors. I ended up stubbing out connector-provided prop validators.

**Comment by ljharb** [comment]
There's two ways to do it: manually pass the child all the props the connector would, *or*, shallow-render the connector, and `.dive()` down to the child.

**Comment by jDeppen** [comment]
(posterity) This was the problem for me in `mapStateToProps`:
``Warning: Failed prop type: The prop `someProp` is marked as required in `SomeComponent`, but its value is `undefined`.``
```
// when var1 is undefined
const var2 = true // could be anything since it isn't evaluated
return {
  someProp: var1 && var2 // returns undefined instead of a boolean
}
```

`!!(var1 && var2)` was what I needed (TIL)
