### ISSUE TITLE
Shallowly Get Props from Child Component

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#848]
I want to check the props of the child, not sure if this is possible with shallow:

```
export class InterviewWrapper extends Component {
    render(){
        const {company} = this.props;

        return (
            <div id="interview-content" className="margin-top-30">
                <div className="column-group">
                    <div className="all-20">
                         <TableOfContents company={company} />
                    </div>
                    <div className="all-80 margin-top-20">
                        <InterviewContent company={company} />
                    </div>
                </div>
            </div>
        )
    }
}
```

**Test**
```
it('renders expected components', () => {
        const company = {
            name: "Stride"
        },
interviewWrapper = shallow(<InterviewWrapper company={company} />),
            tableOfContents = interviewWrapper.find(TableOfContents),
            interviewContent = interviewWrapper.find(InterviewContent);

        // test that InterviewWrapper indeed pass company to TableOfContents.  But trying this is not possible, you can't do instance() on a child component
        expect(tableOfContents.instance().props().company).to.deep.equal(company);
}
```

`Error: ShallowWrapper::instance() can only be called on the root`

I tried using instance() on a child component instead of the parent here.  Is this possible some other way than how I'm trying to obtain props of a child shallowly?  Or do I have no choice but to use mount here?

The goal here isn't to test the behavior of TableOfContents.  If I tried doing that, which you probably can't anyway with shallow, would make this an integration test and make my test brittle.  Instead, all I care is that the parent component (InterviewWrapper) successfully passed props to TableOfContents and that's the extend of my test here.  I want to stop at that.  If I am forced to mount this, it essentially becomes an integration test...I don't want that.  

But then again, if you're using Shallow() on the parent, is it actually exercising logic in the parent if say the parent had some constants being assigned and passed that constant to a child's props???  If no, then what I'm trying to do makes no sense...

There's still a bit of grey area for me on shallow() in terms of yes I get that it doesn't run behavior, but I guess that means any _statements, functions_, etc. in the parent and child components are *not* run when you use shallow correct?

**Comment by dschinkel** [comment]
Here is another example, lets say you have this:

```
export class InterviewWrapper extends Component {
    render(){
        const {company} = this.props,
                   anotherCompany = "SoundCloud";

        return (
            <div id="interview-content" className="margin-top-30">
                <div className="column-group">
                    <div className="all-20">
                         <TableOfContents company={anotherCompany} />
                    </div>
                    <div className="all-80 margin-top-20">
                        <InterviewContent company={company} />
                    </div>
                </div>
            </div>
        )
    }
}
```

So the above, there's some behavior there.  The behavior is that for whatever reason, there's some logic there.  Logic is simple here, a new constant with another value.  We're passing that instead to TableOfContents's company prop.

So when you have behavior like this, I'd wanna test that the outcome (the props passed to the child) is indeed what I expected after sending in initial props to the Parent.

**Comment by ljharb** [comment]
You don't need `.instance()` to get `.props()`, only to get `.props` - they're different. Just do `.props()` after `.find`.

**Comment by dschinkel** [comment]
well that's what I tried before trying to add instance() because I was getting undefined for the props, that didn't work on the child with just .props

**Comment by ljharb** [comment]
Try just asserting directly on `props()` - you might have an actual bug.

**Comment by dschinkel** [comment]
tried that I get:

```AssertionError: expected {} to deeply equal { Object (name, images, ...) }```

**Comment by ljharb** [comment]
Sounds like you're not passing any props at all.

**Comment by dschinkel** [comment]
Yes I'm the idiot.  Thank you for pinpointing the obvious :).

**Comment by dschinkel** [comment]
this works fine now after adding the missing company props on my TableOfContents.  And yes props() which I know I've used before many times in other tests is now working fine.  

I hope though this helps someone else in the future.

**Comment by dschinkel** [comment]
I love you enzyme, you rock!
