### ISSUE TITLE
[Question] How to remove a prop

### ISSUE THREAD

**Issue by julien-f** [airbnb/enzyme#851]
With [ReactWrapper#setProps()](http://airbnb.io/enzyme/docs/api/ReactWrapper/setProps.html), I can merge new props with the existing ones but I cannot remove (really remove, not set to `undefined`) a property.

How can I achieve this? Is there a work-around?

**Comment by blainekasten** [comment]
What is the use case where you need to delete a property of props?

**Comment by julien-f** [comment]
I test presence of the `value` property to detect whether my input should behave in controlled mode.
I found that testing the presence of the property and accepting `undefined` as a valid inputs helped a lot with async data.

So I want to test that my component correctly errors when the property disappears (meaning the input went from controlled to uncontrolled mode which is not normal).

**Comment by julien-f** [comment]
FYI, here is the [component repo](https://github.com/JsCommunity/uncontrollable-input/) (and [the test](https://github.com/JsCommunity/uncontrollable-input/blob/master/src/index.spec.js#L57-L66)).

**Comment by ljharb** [comment]
Code should never differentiate absent and undefined, or you'll run into lots of problems.

`setProps` comes from React, and merges prop values - they haven't provided a way to replace them. Since it's a bad practice to differentiate anyways, I doubt they'd expose that as an API.

**Comment by ljharb** [comment]
For your use case I'd just render it in separate tests, and not test the transition between controlled and uncontrolled - since that's testing React itself, and you don't need to do that.

**Comment by julien-f** [comment]
I was pretty sure that's the kind of answers I was going to get 😛 
Usually I don't differentiate them (not even null), but in this case it provides more benefits than problems.

Thanks for your answer, I'll give it a try.
