### ISSUE TITLE
Missing Closing Tags form Input fields

### ISSUE THREAD

**Issue by digitalkaoz** [airbnb/enzyme#852]
Hey,

there seems to be some bug regarding rendering closing tags (with and without /):
my Component

```jsx
//TimeField
<div>
     <input type='time' placeholder='HH:mm' />
</div>
```

```jsx
//Form
<Fieldset>
     <div>
          <TimeField select='start' label='Start Time' />
     </div>
</Fieldset>
```

my spec file

```js
  it('renders every field', () => {
      const component = mount(<Form />)
      expect(component).toContainReact(<TimeField select='start' label='Start Time' />);
  });
```

i get the following error:

```diff
Expected <Form> to contain <div><input type="time" placeholder="HH:mm"/></div> but it was not found.

HTML Output of <Form>:
<div><input type="time" placeholder="HH:mm"><div></div>
```

notice the closing `/` in expected and the missing one in `present` dom.

i guess it has something todo how react renders server side markup? also the current compare also doenst take `<!-- react-empty: xx -->` into account. the should be stripped away i guess?

**Comment by ljharb** [comment]
Where does `toContainReact` come from? That's not part of enzyme.

What does `component.containsMatchingElement(<TimeField select='start' label='Start Time' />)` return?

**Comment by digitalkaoz** [comment]
i use https://github.com/blainekasten/enzyme-matchers for syntactic sugar.

```js
      expect(component.containsMatchingElement(<TimeField select='start' label='Start Time' />)).toBeTruthy(); === false
```

thats even weirder for me

**Comment by ljharb** [comment]
The latter should certainly be returning `true`. Can you perhaps create a repro, ideally a small, simple repo I can clone myself?

**Comment by digitalkaoz** [comment]
sure, here is the code: https://github.com/digitalkaoz/time-calc/blob/specs/src/components/Form/Form.test.js#L25 i guess finding fails because of `formValue` ?

but neverless https://github.com/blainekasten/enzyme-matchers  simply does a shallow render of the expected Component, and checks for existence in the mounted Component.

it seems shallow renders `<input />` while mount renders `<input>`

**Comment by blainekasten** [comment]
There's a decent chance It's a bug in my library. I'm wondering if it's because you are using the `mount` API and internally I'm comparing it to a `shallow` instance.. https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/toContainReact.js#L17-L18

It does infer a bug in enzyme as the output of mount and shallow should be the same though.

**Comment by blainekasten** [comment]
Errr, ignore. i shallow wrap just so I can output `.html` in the event of a failure. So I'm strictly using the `.contains` API. Seems like potentially 2 bugs here in Enzyme.

**Comment by digitalkaoz** [comment]
rendering is done with jsdom right? maybe its the same problem as https://github.com/tmpvar/jsdom/issues/798 

so fiddeling around with `config.parsingMode` in jsdom might reveal the underlying problem?

**Comment by digitalkaoz** [comment]
@blainekasten if i change your wrapper to use `mount` the closing tags are identical. so the rendering between `shallow` and `mount` produces different markup

**Comment by ljharb** [comment]
Using .html() to compare is problematic because cheerio does not return the same HTML that mount does.

**Comment by ljharb** [comment]
Since your matches is using .contains, however, it shouldn't matter what the HTML output is.

**Comment by digitalkaoz** [comment]
@ljharb but

```js
expect(component.contains(<TimeField select='start' label='Start Time' />)).toBeTruthy()
``` 
is also false, i guess it has something todo with additional props that are set on the `TimeField` ? is enzyme able to omit props (while searching) that are missing in the expected react component?

**Comment by ljharb** [comment]
@digitalkaoz try `containsMatchingElement` - `contains` requires every single prop to be `===`.

**Comment by digitalkaoz** [comment]
@ljharb thanks that works like a charm! so i guess the bug is in the matcher wrapper @blainekasten ?! ill close this. @blainekasten should i open one in your repo?

**Comment by Ashoka222** [comment]
import React, { Component } from 'react';


import DashboardCardSection from './common/DashboardCardSection';
import Button from './common/Button';
import DashboardCard from './common/DashboardCard';
import Input from './common/Input';

class LoginForm extends Component {


    state = { Email: '', Password: '' };
    render() {
        return (
            <DashboardCard>

                <DashboardCardSection>
                    <Input
                        placeHolder="Eneter A Email"
                        label="Email"
                        value={this.state.Email}
                        onChangeText={Email => this.setState({ Email })} />
                </DashboardCardSection>


                <DashboardCardSection>
                    <Input
                        secureTextEntry
                        placeHolder="Eneter A Password"
                        label="Password"
                        value={this.state.Password}
                        onChangeText={Password => this.setState({ Password })} />
                </DashboardCardSection>



                <DashboardCardSection>
                    <Button>
                        log in
                    </Button>
                </DashboardCardSection>



            </DashboardCard>




        );
    }
}
export default LoginForm;

error expected the closing tag <DashboardCardSection> i am stuck not found the issue

**Comment by ljharb** [comment]
@Ashoka222 please file a new issue, and fill out the issue template - this seems unrelated.
