### ISSUE TITLE
set caret(cursor) position in contenteditable element (div)

### ISSUE THREAD

**Issue by liorsharabi** [airbnb/enzyme#856]
Hi

i wanna test appending element in the middle of my div(the user put the caret in the middle of the contenteditable(with the mouse) and drag elements there)
so i'm trying to use browser methods to mock the user behavior.
i'm trying to put the caret in the middle of the div using this code:
(el is the contenteditable element)
` let range = document.createRange();

        let sel = window.getSelection();

        range.setStart(el, caretPosition);

        range.collapse(true);

        sel.removeAllRanges();

        sel.addRange(range);`

when it's getting to "addRange" it throwing an exception **"The given range isn't in document"**.
i guess that the contenteditable document that i'm creating using mount isn't the same as the global document...

am i right?
how can i get the right document so the range and the selection would be in the same document?

**Comment by ljharb** [comment]
This is completely outside the scope of enzyme to test; I think you want ReactDOM.render for this part instead.

**Comment by ljharb** [comment]
(related to #839)
