### ISSUE TITLE
test componentWillReceiveProps failed

### ISSUE THREAD

**Issue by OscarBengtsson** [airbnb/enzyme#857]
I'm going to test lifecycle functions including componentWillReceiveProps using enzyme.

Before anything else, my component should be wrapped materialUi styles and be connected with redux. Otherwise, there will be bugs in render function because I use material-ui components including FlatButton.
```
const wrapper = mount(
 <MuiThemeProvider muiTheme={muiTheme}>
      <Provider store={store}>
           <MemoryRouter>
              <MyComponent />
           </MemoryRouter>
      </Provider>
  </MuiThemeProvider>)

// absolutely fail
wrapper.find(MyComponent).setProps({ something })
expect(MyComponent.prototype.componentWillReceiveProps.calledOnce).toBe(true)
```
So the problem is that I can't use setProps() to MyComponent because enzyme doesn't allow applying non-root component. I'm not able to test componentWillReceiveProps or other necessary parts by changing props.

Is there any good way to set/change props of MyComponent?

**Comment by ljharb** [comment]
`wrapper.instance().componentWillReceiveProps()` - iow, call it manually.

**Comment by OscarBengtsson** [comment]
Sorry but I get this error.
TypeError: wrapper.instance(...).componentWillReceiveProps is not a function

**Comment by ljharb** [comment]
Ah - you can only use it on the root.

What you want to do is `shallow` your `MyComponent`, and do all the individual tests there.

**Comment by OscarBengtsson** [comment]
I've tried with shallow but componentWillReceiveProps isn't triggered.
```
    const spyWillReceiveProps = sinon.spy(MyComponent.prototype, 'componentWillReceiveProps')
    const wrapper = shallow(
      <MyComponent
      />)

    wrapper.setProps({ test: 'test' })
   // props is changing.
    expect(wrapper.props().test).toBe('test')
    // failed here
    expect(spyWillReceiveProps.calledOnce).toBe(true)```

**Comment by OscarBengtsson** [comment]
Never mind. I solved setting prop 'test' by default.

**Comment by OscarBengtsson** [comment]
Yeah, shallow works well.
Finally how can I call reducer of MyComponent?

**Comment by ljharb** [comment]
If you mean the reducer of a flux store, you'd shallow-render the wrapper, and assert on the child's props.

**Comment by OscarBengtsson** [comment]
Thank you
