### ISSUE TITLE
Assign one text box to second text box with key press event on both text box using jquery?

### ISSUE THREAD

**Issue by Coderwill** [airbnb/enzyme#864]
i have a 2 text box box.now i want to one text on key press event value enter this value automatically write in the second text box with key press event.so now i want to key press event also got second text box.so how can do that i don't know.

here is my text box :
`<input type="search" id="search" class="form-control" placeholder="Search...">`

this is my script code :

` <script type="text/javascript">
    $(function () {
        $("#search").keypress(function () {
            debugger;
            //$("#anotherName").val($(this).val());           
                $(".fixed-table-container").find(".dataTables_filter input.input-sm[type='search']").val($(this).val());    // this is my 2nd text box       
        });
    })
    </script>`
so here write now first text box key press event is working so now i want to same time 2nd text box key press want.

for example i am write abc on 1st textbox that same time keypress using abc write automatically in 2nd textbox but that time i want keypress event also for 2nd textbox.

**Comment by ljharb** [comment]
This is React - use `setState` and rerender the second text box; you wouldn't want to use any jquery code for that.
