### ISSUE TITLE
`this.node` is undefined in componentWillUnmount() for shallow renderer

### ISSUE THREAD

**Issue by jwalton** [airbnb/enzyme#865]
I have a test that basically does:

```
    it('should update when props change', () => {
        const wrapper = shallow(
            <MyComponent>woo</MyComponent>
        );

        return Promise.resolve()
        .then(() => wrapper.setProps({children: 'woo2'}))
        .then(() => promiseTools.delay(10))
        .then(() => {
            expect(wrapper.containsMatchingElement('woo2'), 'woo2').to.be.true;
            wrapper.unmount();
        });

    });
```

This fails because in my component, in `componentWillUnmount()`, `this.node` is undefined.  If I change this to use `mount` instead of `shallow`:

```
    it('should update when props change', () => {
        const wrapper = mount(
            <MyComponent>woo</MyComponent>
        );

        return Promise.resolve()
        .then(() => wrapper.setProps({children: 'woo2'}))
        .then(() => promiseTools.delay(10))
        .then(() => {
            expect(wrapper.getNode().innerHTML).to.include('woo2');
            wrapper.unmount();
        });

    });
```

Then it passes.

**Comment by ljharb** [comment]
With shallow, after `setProps`, you have to explicitly `wrapper.update()`.

**Comment by jwalton** [comment]
Explicit call to `update()` didn't fix it.  I put a debugger on this; I notice that despite the documentation [here](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md#shallownode-options--shallowwrapper), `componentDidMount()` is never being called for my component, even if I explicitly set `disableLifecycleMethods` to false.  I mean, this kind of makes sense to be honest, because I wouldn't expect `componentDidMount()` to run for a shallow render, and now that I think about it, maybe I shouldn't expect there to even be a `this.node` when I shallow render, since there's no DOM for the node to be a part of.  But, if `componentDidMount()` doesn't get called, why does `componentWillUnmount()`?

**Comment by koba04** [comment]
@jwalton 
Currently, `disableLifecycleMethods` is a no-op, which will be enabled when all lifecycle methods are supported by default in v3. #789 #678

In v2, you can use `lifecycleExperimental` option instead of `disableLifecycleMethods` to false.

**Comment by ljharb** [comment]
@jwalton are you still experiencing this issue with v3?

**Comment by jwalton** [comment]
I haven't tried it.  Feel free to close this.

**Comment by ljharb** [comment]
Happy to reopen if it's still an issue.
