### ISSUE TITLE
Shallow renderer has been moved to react-test-renderer/shallow

### ISSUE THREAD

**Issue by cyanic-webdesign** [airbnb/enzyme#879]
With the upgrade of React to version 15.5 our unit tests are breaking with the following comment:

`Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning`

```
import React from 'react';
import { shallow } from 'enzyme';
import { shallowToJson } from 'enzyme-to-json';

import Component from './Component';

describe('Component', () => {
  it('should render correctly', () => {
    const wrapper = shallow(<Component />);
    expect(shallowToJson(wrapper)).toMatchSnapshot();
  });
});
```

**Comment by ljharb** [comment]
See #875 / #876. The deprecation warnings affect a lot of tools, so temporarily, you'd need to whitelist that console warning to not fail your tests (or stay on 15.4)

**Comment by tehnomaag** [comment]
> temporarily, you'd need to whitelist that console warning

How does one do that?

**Comment by ljharb** [comment]
Since console warnings failing tests isn't something standard, you'd find whatever code you wrote to make that happen, and then modify it to ignore this particular error.
