### ISSUE TITLE
Listen for warning from proptypes

### ISSUE THREAD

**Issue by Jameskmonger** [airbnb/enzyme#882]
I have a component which has some `propTypes` rules on it. I would like to test that there are warnings given.

I have this test:

    console.log("begin");
    try {
      shallow(<NavigationBar><span></span></NavigationBar>);
    } catch (err) {
      console.log("error:");
      console.log(err);
    }
    console.log("done");

React gives a warning, because it is logged to my console, however the `catch` is not triggered. How can I listen for a warning on the component, so that I can test it?

**Comment by Jameskmonger** [comment]
I can "solve" this by hooking into `console.error`, but it doesn't feel right. Is there a better way to do this using enzyme?

    const spyConsoleError = SpyOn(console, "error");
    spyConsoleError.andCall((message: string) => {
      if(message.lastIndexOf("Warning: Failed prop type:") === 0) {
        throw new Error(message);
      }
    });

    console.log("begin");
    try {
      shallow(<NavigationBar><span></span></NavigationBar>);
    } catch (err) {
      console.log("error:");
      console.log(err);
    }
    console.log("done");

    spyConsoleError.restore();

**Comment by Jameskmonger** [comment]
Contrary to my last post, this does not work when there are multiple tests around the component due to react deduping the messages.

**Comment by eduardomoroni** [comment]
I think this is related to https://github.com/airbnb/enzyme/issues/885

**Comment by ljharb** [comment]
Generally one does not test propTypes in this fashion. You want to:
1. Unit test all custom prop type validators
1. Make propType warnings fail your tests by hooking into console.error - which is the only way.

**Comment by Jameskmonger** [comment]
Thanks @ljharb I appreciate the pointers :)
