### ISSUE TITLE
Element height with percentage?

### ISSUE THREAD

**Issue by acidron** [airbnb/enzyme#887]
My component content depends on it's container size, I've tried to test it with enzyme and discovered Enzyme reads "x%" as "x".

Here is my spec for this case:

> import React from 'react';
> import {render} from 'react-dom';
> import { mount } from 'enzyme';
> import $ from 'jquery';
> function getJSX() {
> 	return <div style={{height: "1000px"}} id="outer">
> 		<div style={{height: "90%"}} id="inner">
> 			content
> 		</div>
> 	</div>
> }
> 
> describe('Enzyme_PhantomJS heights test', () => {
> 
> 	it('works in PhantomJS', () => {
> 		let rootEl = document.createElement('div');
> 		document.body.appendChild(rootEl);
> 		render(getJSX(), rootEl);
> 		expect($('#inner').height()).toEqual(900); //SUCCESS
> 	});
> 
> 	it('works in enzyme', () => {
> 		const wrapper = mount(getJSX());
> 		let el = wrapper.find('#outer').getDOMNode();
> 		expect($(el).height()).toEqual(1000); //SUCCESS
> 		expect($(el).find('#inner').height()).toEqual(900); //FAILED with Expected 90 to equal 900.
> 	});
> });

Is it a bug ?

**Comment by ljharb** [comment]
That looks like jQuery providing the height. Can you reproduce a similar failure without using jQuery?

**Comment by acidron** [comment]
Hm, I've tried to get element's height with plain js by reading .clientHeight, .offsetHeight properties, they give zero values for enzyme getDOMNode()

**Comment by ljharb** [comment]
If you're testing the style prop, I'd suggest asserting on that. The actual height is a result of React and the browser; you don't need to test those.
