### ISSUE TITLE
Jsdom configuration conflict with Chai's type-detect

### ISSUE THREAD

**Issue by LeonardoGentile** [airbnb/enzyme#888]
In the [docs](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md) is recommended to do this before running the tests when using mount:

```
var jsdom = require('jsdom').jsdom;

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```
The problem is that this is tricking [Chai's type-detect](https://github.com/chaijs/type-detect/issues/98) into believing we are running into a browser and it will throws Exceptions.
  
Probably this is happening also for other libraries checking in which environments we are, but type-detect is used by chai and sinon. So this is really strictly related to the test environment setup.

I'm not sure this should be fixed by enzyme, jsdom or type-detect

I've reported this also to type-detect: https://github.com/chaijs/type-detect/issues/98

**Comment by LeonardoGentile** [comment]
After reading [Don't stuff jsdom globals onto the Node global]( https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global) form jsdom wiki I wonder if this is happening because your doc suggests something that jsdom considers an anti pattern?

**Comment by ljharb** [comment]
Whether jsdom considers it an antipattern or not, it's required to make react itself work.

The real problem is https://github.com/chaijs/type-detect/issues/98 - if it's detecting a browser, and then breaking, clearly it's not detecting the right things - ie, if it can be fooled (unless it works 100%), it's broken.

**Comment by zazapeta** [comment]
Hellow,

As quick fix to passing test until it's fix add this line to your setup :
```javascript
global.HTMLElement = () => {};

**Comment by palaniichukdmytro** [comment]
After migration to enzyme I catch the error when start testing, also I use chai 4.1.2 and chay-enzyme "^1.0.0-beta.0" with React 16,

```
it.only('should render icon with correct style', () => {
            props.icon.props.style.should.be.deep.equal(iconPropsStyle)
        })
```
all my casse failed on should.be.deep.equal

```
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills


  !

  0 passing (206ms)
  1 failing

  1) <Button/>
       with icon
         should render icon with correct style:
     ReferenceError: HTMLElement is not defined
      at typeDetect (node_modules\type-detect\index.js:163:24)
      at extensiveDeepEqual (node_modules\deep-eql\index.js:183:22)
      at Object.deepEqual [as eql] (node_modules\deep-eql\index.js:106:10)
      at Proxy.assertEql (node_modules\chai\lib\chai\core\assertions.js:1081:11)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at Proxy.assertEqual (node_modules\chai\lib\chai\core\assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at Context.<anonymous> (C:/Users/d.palaniichuk/Documents/react-components/test/Button/Button-test.js:80:51)
```

**Comment by ljharb** [comment]
This seems resolved.
