### ISSUE TITLE
`html()` has no button, while `find('button').length` is 1

### ISSUE THREAD

**Issue by ewendel** [airbnb/enzyme#89]
I'm writing a test that checks that a component does not include a `<button>` when a certain prop isnt passed.

I'm using the shallow renderer as two of the examples on this section seems to do exactly what I intend to do.

```
const wrapper = shallow(<MyComponent />);
```

When I log the output html of the component through `wrapper.html()` I see there's no `<button>` in there. In fact I can see the `<noscript/>`'s created by my conditional rendering component.

However, `wrapper.find('button')` or `wrapper.find('.btn')` (as it has this class) both return an object with length equals 1.

`wrapper.contanis('button')` is also true.

What could I be doing wrong, have I misunderstood something?
What is the best way to assert the presence of a node in the rendered output?

I could of course assert on the contents of `html()` but that feels a bit brittle.

**Comment by blainekasten** [comment]
Can you share what your `MyComponent` implementation looks like?

**Comment by ewendel** [comment]
Sorry I haven't gotten around to this yet. Currently at ReactConf, but I'll share my implementation when I get home. 

The issue referenced seems to be exactly the same thing.

**Comment by Aweary** [comment]
@ewendel any chance you have an update on this?
