### ISSUE TITLE
Building enzyme with browserify fails after enzyme@2.8.1 - "Cannot find module 'react-test-renderer/shallow'"

### ISSUE THREAD

**Issue by tiriana** [airbnb/enzyme#899]
After enzyme 2.8.1 I cannot build enzyme with browserify. Enzyme 2.8.2 does not fix this issue either. 
With 2.8.0 and ^2.7.1 everything works ok.

I put all my setup and errors in gist: https://gist.github.com/tiriana/26a0394d8f9e26e28a1726bc33b13317

Let me know if you rather have this info in the very ticket instead.

**Comment by ugurozgen** [comment]
There is same problem in webpack too

**Comment by finnigantime** [comment]
The fix here is to mark "react-test-renderer/shallow" as an external dependency.

See https://github.com/airbnb/enzyme/blob/master/docs/guides/browserify.md. Follow these instructions, except for you'll need this line:

```
b.external("react-test-renderer/shallow");
```

The documentation should be updated.

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.
