### ISSUE TITLE
Warning Errors about PropTypes and React.createClass

### ISSUE THREAD

**Issue by travisdmathis** [airbnb/enzyme#901]
React 15.5 when running tests i get the following errors.. i'm assuming its coming from enzyme..

I don't use createClass and have already upgraded to use PropTypes package in my component.

 console.error node_modules/fbjs/lib/warning.js:36
    Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

  console.error node_modules/fbjs/lib/warning.js:36
    Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by ljharb** [comment]
These warnings could be coming from anything in your entire dependency graph. You'll have to ensure everything in node_modules has updated, as well.

If you've updated to prop-types, then you won't get a warning for it from enzyme.

You have to have create-react-class as a dev dep with enzyme whether you use it or not, however, to avoid a warning from enzyme.

**Comment by travisdmathis** [comment]
thanks @ljharb that did it.. can close.
