### ISSUE TITLE
[Query Selector Fail]  simulat('toggle') doesn't work with mount(<Component/>) but works with shallow(<Component/>)

### ISSUE THREAD

**Issue by farhaanbukhsh** [airbnb/enzyme#902]
I was trying to test a component which is using `material-ui Toggle`, these are few behaviours which I observe, when I use `mount` of the component and try to `simulate` `toggle` action on it. I get an error saying `toggle` is not an `action` for simulate while when I try to do the same thing with `shallow` it works .

This doesn't solve my problem because I am interested in the child component too.

**Comment by ljharb** [comment]
Simulate does not faithfully simulate anything; it's just sugar for invoking a prop function. I'd suggest doing that instead.
