### ISSUE TITLE
flatMap removes duplicate text nodes

### ISSUE THREAD

**Issue by jerrysu** [airbnb/enzyme#906]
I ran into a problem while using `children()` and `childAt(idx)`. I am writing specs for a component that adds spaces between child elements. I wanted to test this behavior, but am finding that https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L942 removes all of the subsequent spaces. I see in the comment above `flatMap` that this line is for de-duplicating nodes, but am not sure what duplicate nodes are. Otherwise, I'd just submit a PR to fix this.

My particular use case is as follows:

```
function JustificationRow({ children, styles }) {
  const wrappedChildren = React.Children.map(
    children,
    child => child && <span {...css(styles.child)}>{child}</span>,
  );

  const justifiedChildren = [];
  React.Children.forEach(wrappedChildren, (child) => {
    if (child) {
      justifiedChildren.push(child, ' ');
    }
  });
  justifiedChildren.pop();

  return <div {...css(styles.row)}>{justifiedChildren}</div>;
}
```

I wanted to write the following test:

```
it('renders children separated by spaces', () => {
  const wrapper = shallow(
    <JustificationRow>
      <div>foo</div>
      <div>bar</div>
      <div>baz</div>
    </JustificationRow>
  ).dive();

  expect(wrapper.children()).have.lengthOf(5);
  expect(wrapper.childAt(0).type()).to.equal('span');
  expect(wrapper.childAt(1).text()).to.equal(' ');
  expect(wrapper.childAt(2).type()).to.equal('span');
  expect(wrapper.childAt(3).text()).to.equal(' ');
  expect(wrapper.childAt(4).type(4)).to.equal('span');
});
```

However, `wrapper.children()` has a length of `4` and looks like:

```
[<span />, ' ', <span />, <span />]
```

Writing the test with only two children allows me to workaround this for now...

**Comment by ljharb** [comment]
Does this work in your actual component, rendered in a browser? Generally this is achieved by adding `<span>{' '}</span>` to the array with a "key" prop - I suspect React itself is deduping all your space characters (since they all have no key).

**Comment by jerrysu** [comment]
The component does render as expected without any warnings. You gave me another idea for a workaround (by pushing something like `<span key={`space-${index}`}>{' '}</span>` instead.

I'm more curious what the code that I pointed out does. When will there be duplicate nodes?

**Comment by ljharb** [comment]
If your original code works normally but not in enzyme, then that's definitely a bug.

Can you compare with `mount` and `shallow`, and help figure out if it's a bug in just one, or both?

**Comment by jerrysu** [comment]
With `mount`, `children()` and `childAt(idx)` appear to only have nodes. `html()` shows ```<!-- react-text: 4 --> <!-- /react-text -->``` between the nodes.

**Comment by ljharb** [comment]
This seems mostly fixed; I'm seeing a difference in that with shallow, there's 5 children, and with mount, there's just 3.
