### ISSUE TITLE
Issues mount'ing component

### ISSUE THREAD

**Issue by tarciosaraiva** [airbnb/enzyme#91]
Hey guys, great work with the library, makes testing quite a breeze! But I'm having some issues with it though that I would like to clarify if it's a problem with enzyme or potentially jsdom.

Here's my React component:

```
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { reference: { orgs: [] } };
  }

  fetchReferenceData() {
    fetch(`${API_HOST}/endpoint`)
      .then(res => res.json())
      .then(json => {
        let currentState = this.state;
        currentState.reference = { orgs: json };
        this.setState(currentState);
      });
  }

  componentDidMount() {
    this.fetchReferenceData();
  }

  render() {
    return (
      <Input name="field" type="select" label="Field *">
        {
          this.state.reference.orgs.map(bo => {
            return <option key={bo.id} value={bo.id}>{bo.name}</option>;
          })
        }
      </Input>
    );
}
```

And on my test, whenever I try to query an element on the form like below...

```
describeWithDOM('<CreateBroker />', () => {
  var wrapper;

  before((done) => {
    wrapper = mount(<CreateBroker />);
    done();
  });

  it('should submit the form', (done) => {
    wrapper.find('form');
    done();
  });

});
```

I get the following error:

```
  1) (uses jsdom) <CreateBroker /> should submit the form:
     Error: Invariant Violation: findComponentRoot(..., .cdzgo5m3gg.0.2.0.0.1:$input.$1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

If I remove the `[].map` part out, it works but I lose the functionality. Any ideas?

**Comment by tarciosaraiva** [comment]
OK looks like there's a little bit of an issue with jsdom + mocha-jsdom integration.

I've changed two things:

1. Followed the recommendation [on this issue](https://github.com/airbnb/enzyme/issues/58#issuecomment-162514956) to init JSDOM manually
2. Since that caused initialisation problems as JSDOM was already init'ed with `describeWithDOM` I was forced to use a normal `describe`

That did the trick for me and is working like a charm.

**Comment by tarciosaraiva** [comment]
Digging into the problem a bit seems like whenever there's a DOM change caused by `setState` forcing the `render` on the component, the initialisation on `mocha-jsdom` occurs after React has already done its thing.

I could prove it works with the same configuration `mocha-jsdom` used by simply creating a specHelper to be loaded upon mocha's initialisation:

```
import jsdom from 'jsdom';

const html = "<!doctype html><html><head><meta charset='utf-8'></head><body></body></html>";

global.document = jsdom.jsdom(html, {
  globalize: true,
  console: true,
  useEach: false,
  skipWindowCheck: false,
});

global.window = document.defaultView;
global.navigator = window.navigator;
```

This way I can write a test like below without any problems:

```
    it('allows setState inside of componentDidMount with dynamic data', () => {
      class MySharona extends React.Component {
        constructor(props) {
          super(props);
          this.state = {mounted: false, data: []};
        }
        componentDidMount() {
          this.setState({mounted: true, data: [{ a: 'b' }, { a: 'c' }]});
        }
        render() {
          if (this.state.data.length) {
            const fragment = this.state.data.map(d => {
              return <p key={d.a}>{d.a}</p>;
            });

            return (
              <div>
              {this.state.mounted ? 'a' : 'b'}
              <br/>
              {fragment}
              </div>
            );
          }
          return (
            <div>{this.state.mounted ? 'a' : 'b'}</div>
          );
        }
      }
      const wrapper = mount(<MySharona />);
      expect(wrapper.find('div').text()).to.equal('abc');
    });
```

**Comment by lelandrichardson** [comment]
@tarciosaraiva There seems to be some issues with `describeWithDOM()` and components with conditionally rendered DOM nodes of different node types...  This is because React's internals rely on a cached `document` at require time and it screws some things up.

`describeWithDOM` is going to be gutted soon for the `2.0` release, and we will no longer be recommending its use. The use of this function in the first place was a vestige of some airbnb-specific environment issues.

In 2.0 I will be giving environment-specific guides to using enzyme, one of which will be using enzyme with jsdom. In this case I will be recommending loading up one jsdom `document` initially and using that throughout your entire test suite... mostly because React's internals  (and many other libraries) are buggy if you do it any other way.

**Comment by tarciosaraiva** [comment]
Excellent, thanks for all the info @lelandrichardson.
