### ISSUE TITLE
Enzyme not unmounting by itslef

### ISSUE THREAD

**Issue by hakunin** [airbnb/enzyme#911]
Hi, I noticed that Enzyme doesn't unmount the components I mounted after each test.
In my case, they will listen and react to stuff, thus the test gets slower and slower.

Are we supposed to do it manually? 
I'd expect a high level library like Enzyme to unmount everything at the end of each test.

**Without unmounting:**
![screenshot 2017-04-21 14 47 56](https://cloud.githubusercontent.com/assets/65846/25278090/a02cc2c4-26a1-11e7-9c00-07efb294df9b.png)

**With unmounting its plenty fast but I get errors from the unmount code**
![screenshot 2017-04-21 14 53 36](https://cloud.githubusercontent.com/assets/65846/25278233/5bc4561e-26a2-11e7-83de-de77dcc46fe2.png)

I tried clearing the timers in the `afterEach()` function where I try to unmount but it didn't help. Any ideas?

**Comment by ljharb** [comment]
Yes, you're supposed to do it manually.

It would be impossible for enzyme to know when your test is over, or even that you're writing a test at all.

Your component probably needs to clean up after itself in `componentWillUnmount`.

**Comment by hakunin** [comment]
> It would be impossible for enzyme to know when your test is over
How about `afterEach`? Does that not mean the test is over?

**Comment by ljharb** [comment]
It is impossible for enzyme to know that any of its code is running in an `afterEach`, for example. Obviously your test is over inside the afterEach, but only *you* know that - not enzyme.

**Comment by hakunin** [comment]
I don't follow. Are you saying Enzyme can't add `afterEach` callback that would cleanup the mounted components?

**Comment by ljharb** [comment]
Yes, because enzyme doesn't know you're using mocha, or any other test framework. `afterEach` doesn't exist in every test framework, it exists in the one you chose to use.

**Comment by hakunin** [comment]
then a simple `enzyme.cleanup()` in a global `afterAll` hook would still work, or even something like `enzyme.init(jest)`, but I will simply create a wrapper myself :) thanks for explaining it

**Comment by ljharb** [comment]
Indeed, something that would be useful for you here would be a wrapper that kept in memory every enzyme wrapper that was ever created, and provided an unmount/cleanup method to clean them all up, so you could call that in `afterEach`.

That belongs in a separate enzyme wrapper package, but would be very useful.

**Comment by silvenon** [comment]
Material UI solved it [like this](https://material-ui-1dab0.firebaseapp.com/guides/testing) ([source](https://github.com/callemall/material-ui/blob/v1-beta/src/test-utils/createMount.js)).

**Comment by jackgeek** [comment]
I think this really belongs in the enzyme library.  Its not immediately clear that you have to clean up.  If there was a documented enzyme.cleanup() that would be very useful.

**Comment by AndyObtiva** [comment]
It violates the principle of lease surprise. I don't care if Enzyme knows or not when to clean. From a software engineering and design point of view, it doesn't satisfy my requirements with its current design compared to many other similar pieces of software that clean after themselves in their problem space, like rspec rails and database cleanup. You start with the requirements in mind, not technical designs that were done to satisfy some requirements to begin with, which are clearly not satisfying fully as reported by professional developers.

Also, as a piece of feedback from an experienced software engineer and open-source project owner myself, a good attitude in response to issues is to say something like "enzyme doesn't know when to clean.... help me understand your need, and we'll look into coming up with a solution to add to Enzyme". That's how good customer service, open-source or not, operates in America! That's the only standard I expect with any respectable piece of software, unless you live in a 3rd world country or something.

**Comment by cgood92** [comment]
I came across this unfortunate news today, and I have implemented a solution that seems to be working for me.  I will post it here, and I would love feedback.

`jest-setup.js`
```js
import { configure } from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'
import reactDOM from 'react-dom'

const attachTo = global.document.createElement('div')

class ReactAdapterWithMountTracking extends Adapter {
	constructor(...args) {
		super(...args)
	}
	createRenderer(options){
		// Provide a default option on each render for attachTo, being a global div that we can unmount later
		Object.assign(options, { attachTo: options.attachTo || attachTo })
		return Adapter.prototype.createRenderer.call(this, options)
	}
}

afterEach(() => {
	// Unmount react component after each test
	reactDOM.unmountComponentAtNode(attachTo)
})

configure({ adapter: new ReactAdapterWithMountTracking() })
```

**Comment by cgood92** [comment]
I made this into an NPM package for easy consumption.  Now you can do the following:

```
npm i -d eynzme-cleanup 
```

And add this to your jest setup script (where you set up your enzyme adapter)

```js
import { configure } from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'
import { cleanup, makeAdapter } from 'enzyme-cleanup'

// afterEach is a global jest method
afterEach(cleanup)

configure({ adapter: makeAdapter(Adapter) })
```

**Comment by jackgeek** [comment]
I've stopped using enzyme in favor of testing-library. I'd recommend the maintainers have a read of the testing-library docs. Have a look at how Kent achieved this.

You are in an eco system, not a vacuum. There are ways you can make this "just work" for the most common environments and users. Leave an escape hatch for the edge cases and advanced users.
