### ISSUE TITLE
Docs link in PR placeholder doesn't go anywhere

### ISSUE THREAD

**Issue by hakunin** [airbnb/enzyme#912]
https://github.com/airbnb/enzyme/commit/c2545d9d8637d2b6a4d1f2d117b45a70f578baf5#commitcomment-21854609

**Comment by blainekasten** [comment]
Mind putting together a quick PR to fix it?

**Comment by hakunin** [comment]
I can try :) where did you intend the docs link to go?
I don't see a common issues page here http://airbnb.io/enzyme/docs/guides.html

**Comment by blainekasten** [comment]
https://github.com/airbnb/enzyme/blob/master/docs/common-issues.md

**Comment by blainekasten** [comment]
Has there not been a deploy to the docs since that was added? @ljharb

**Comment by ljharb** [comment]
@blainekasten there's a deploy every release; that file was last updated prior to v2.8.0, so it should be deployed. We may not add every file into gitbook tho

**Comment by hanumanthan** [comment]
Fix in PR [912](https://github.com/airbnb/enzyme/pull/913).

Sorry @hakunin If i jumped in and opened PR. If have already worked on it, happy to close my PR.

**Comment by hakunin** [comment]
No worries :) thanks for jumping in @hanumanthan

**Comment by ljharb** [comment]
Merged in #913.
