### ISSUE TITLE
Enzyme doesn't report invalid React components

### ISSUE THREAD

**Issue by akalman** [airbnb/enzyme#922]
### The Problem

We're trying to have unit test level validation that our React components are legal react components, and we've chosen enzyme to help us test the component itself.  Largely it has been very helpful.  However, one thing that has slipped through recently was a component that was using `class` instead of `className`.  When loaded into a browser this produces an error in the console.  Ideally we'd like to use enzyme to catch this error, but when I went back to modify the tests to catch this, I found it was very difficult to do so.

this is logged via the `console.error()` function.  I did find a workaround that included changing the global console.error function but managing that in a test suite that is designed to function through multiple exit points from test functions seems risky at best.  Also, having to modify global state at all is less than ideal.  I believe that enzyme already hooks into `console.error()` at some level because when the error is logged in the test it gets converted to html output used by the `html()` function.  Also I currently believe that the error is only detectable at all when the component is `rendered()` (a.k.a. you can't detect it using `shallow()`) but I honestly can't remember why I thought that so it very well could be wrong.

### Potential Solutions

1. Some configuration option to throw exceptions when `console.error()` is written to
1. A new function on `ShallowWrapper`, `CheerioWrapper`, or both that would either return these errors or throw if any errors had been logged.
1. A validate function that lives alongside `shallow()` and `render()` for the express purpose of detecting these errors.

None of these solutions are perfect (3 in particular seems really clunky) and I'm certainly open to other options.

**Comment by ljharb** [comment]
I'd use eslint-plugin-react for this tbh.

However, you should already be doing option 1 in your test suite - that's not an enzyme thing; you want propType warnings to fail tests too.
