### ISSUE TITLE
Documentation site is broken with fastly error

### ISSUE THREAD

**Issue by juliepagano** [airbnb/enzyme#923]
Seeing "Fastly error: unknown domain: airbnb.io. Please check that this domain has been added to a service." when I go to http://airbnb.io/enzyme/. Guessing this isn't just an enzyme docs issue, but wasn't sure where to file a general bug with airbnb folks, so hoping this is a good starting place.

**Comment by ljharb** [comment]
Thanks; we're having issues with fastly right now. It's being looked into.

**Comment by ljharb** [comment]
Should be all fixed!
