### ISSUE TITLE
indentation is broken for debug() on shallow wrapper

### ISSUE THREAD

**Issue by finnigantime** [airbnb/enzyme#925]
### Repro
1. render a shallow wrapper of an element that has children
2. call .debug() on the wrapper

expected: each level of children is on a new line and intended 2 spaces
actual: no levels of children are indented

**Comment by fatfisz** [comment]
Hi, when is a next version with this fixed expected to be released?

**Comment by ljharb** [comment]
It's now released.

**Comment by fatfisz** [comment]
Yup, I've used that already. Thanks, great work!
