### ISSUE TITLE
Trigger event keyDown on Contenteditable element

### ISSUE THREAD

**Issue by dzhytomyrsky** [airbnb/enzyme#927]
Hello, is it possible to trigger onKeyDown event on contetnteditable span element? 

`<span id = 'name' contenteditable = 'true'> Editable text </span>`

I tried: 

`result.find('#name').simulate('keyDown', { key: 'm', keyCode: 77, which: 77 });`,

but it did not work.

**Comment by aweary** [comment]
Make sure you're using the correct prop name, `contentEditable`

**Comment by ljharb** [comment]
Separately, `simulate` does not faithfully simulate anything nor trigger events - all it is is sugar for invoking a prop function.
