### ISSUE TITLE
when the root component has more than one component in the render code; error in the emulator/device

### ISSUE THREAD

**Issue by dcu-sharepoint** [airbnb/enzyme#932]
I have noticed lately that when I render more than two components in the render function of the main component, I get an expected component class error even though all my components are defined as component classes. If I remove one of the components, then the emulator works to perfection.

I'm sure the issue is my lack of knowledge but please see images:

**this error DOES NOT tell me anything of value or at least I  do not understand it**

![2017-05-08](https://cloud.githubusercontent.com/assets/22737071/25823403/02f9fdde-340a-11e7-9a96-1ac40c27af65.png)
**this one either!**
![2017-05-08 1](https://cloud.githubusercontent.com/assets/22737071/25823422/0df21410-340a-11e7-9c69-8594324dce07.png)

**this is the debugger console window**
![2017-05-08 2](https://cloud.githubusercontent.com/assets/22737071/25823456/272086a6-340a-11e7-8c28-b7b918e951a5.png)

**this one gives the error shown on first & second images**
![2017-05-08 3](https://cloud.githubusercontent.com/assets/22737071/25823524/573abd70-340a-11e7-845f-58a9150950b1.png)

**this one works; no issues**
![2017-05-08 4](https://cloud.githubusercontent.com/assets/22737071/25823538/5f560b2c-340a-11e7-83f1-5d3b5b62b907.png)

**Comment by ljharb** [comment]
What does `Main.js` look like?

**Comment by ljharb** [comment]
Closing; happy to reopen if more info appears.
