### ISSUE TITLE
Request: Enzyme clean up function

### ISSUE THREAD

**Issue by georeith** [airbnb/enzyme#935]
Proposing the addition of an `unmountAll()` function which unmounts all mounted components.

I often have the following issue:

- I want to mount a separate component in each test with different parameters.
- To safely `unmount()` an enzyme component I need to wrap each test in its own `describe()` block (this is for mocha but I'm sure this is the case for other test runners with different semantics). Mount and store the component in a closure and unmount it in an `after()` block.
- If I call `unmount()` at the end of the test and my test fails early then `unmount()` is never called. This allows the test to leak side effects into other tests.

Instead of having to:

```js
describe('forced to create this', () => {
    let wrapper; 
    before(() => {
        wrapper = mount(<Component />, { attachTo: container });
    });
    it('assert', () => {});
    after(() => {
        wrapper.unmount();
    });
});
```

I should be able to:

```js
// In some higher common file
afterEach(() => {
    unmountAll();
});

// In my test file
it('assert', () => {
    wrapper = mount(<Component />, { attachTo: container });
});
```

**Comment by ljharb** [comment]
That would only be possible if enzyme kept track of all mount/shallow wrapped components, which if it did that by default would be a memory leak.

This needs to be solved by a separate enzyme wrapper, not in enzyme itself.

**Comment by jack-sf** [comment]
Have you considered adding a helper function then like this one https://github.com/mui-org/material-ui/blob/71234113e3d14bcbfe0d3acec3023d219615d74e/packages/material-ui/src/test-utils/createMount.js ?

Then we could use enzyme like that

```js
let mount;

beforeEach(() => {
  mount = createMount();
});

afterEach(() => {
  mount.cleanUp();
});

it('test sth', () => {
  const output = mount(...);
});
```

Currently cleaning up components that are mounted inside of a testcase source code is very troublesome. (Especially when your testcase can fail in the middle of its' code.)

**Comment by jtomaszewski** [comment]
Have you considered adding a helper function then like this one https://github.com/mui-org/material-ui/blob/71234113e3d14bcbfe0d3acec3023d219615d74e/packages/material-ui/src/test-utils/createMount.js ?

Then we could use enzyme like that

```js
let mount;

beforeEach(() => {
  mount = createMount();
});

afterEach(() => {
  mount.cleanUp();
});

it('test sth', () => {
  const output = mount(...);
});
```

Currently cleaning up components that are mounted inside of a testcase source code is very troublesome. (Especially when your testcase can fail in the middle of its' code.)

**Comment by ljharb** [comment]
Duplicate of #1689. Duplicate of #437
