### ISSUE TITLE
Async mock support

### ISSUE THREAD

**Issue by damianobarbati** [airbnb/enzyme#936]
We have no way to wait for the (mocked) method of the component instance to be called.

Example:
```
it('renders', async () => {
    const store = mockStore({});
    const component = shallow(<Component />).dive();

    const spy = jest.fn(component.instance().compute);

    component.find('button').simulate('click');
    component.update();

    await expect(spy).resolves.toHaveBeenCalled(); //???
    spy.mockReset();
    spy.mockRestore();
});
```

**Comment by ljharb** [comment]
That's because enzyme has no way it can know when your `onClick` is completed. You have to use mocks to get a promise or callback tied to your handler as part of the test - enzyme can't do that for you.

**Comment by damianobarbati** [comment]
Got it: closing this.

**Comment by ljharb** [comment]
Related reading: #823, #867, #898
