### ISSUE TITLE
CSS descendant selector not working as expected

### ISSUE THREAD

**Issue by cgood92** [airbnb/enzyme#938]
I am having the following issue with Enzyme `2.8.2`.

The problem is independent of Jest completely (obviously), but putting my issue in the context of my Jest test may also clarify the problem.

```
test('test', () => {
	const Component = () => (
		<div>
			<div>TEST</div>
		</div>
	)
	const wrapper = shallow(<Component/>)
	expect(wrapper.find('div div')).toHaveLength(1)
	// => FAIL: has length of 2
	wrapper.find('div div').forEach(n => console.log(n.text()))
	// => TEST
	// => TEST
        console.log(wrapper.find('div div').html())
        // => ERROR: expected to be called on only 1 element, but 2 found instead
})
```

There is something not accurate about this.  Following the proper CSS rules, `div div` should only target the inner `div`, and to do so once.  For some strange reason, Enzyme returns the inner `div` twice, which doesn't make sense on many levels.  First of all, it didn't apply the selector correctly, because only 1 element fits that selector.  Second, how come it has 2 of the same element?

Here is the expected behavior:

```
test('test', () => {
	const Component = () => (
		<div>
			<div>TEST</div>
		</div>
	)
	const wrapper = shallow(<Component/>)
	expect(wrapper.find('div div')).toHaveLength(1)
	// => Success
	wrapper.find('div div').forEach(n => console.log(n.text()))
	// => TEST
        console.log(wrapper.find('div div').html())
        // => <div>TEST</div>
})
```

According to this PR (https://github.com/airbnb/enzyme/issues/23), this should have already been taken care of.  But, I'm not seeing it work as expected on my machine.

**Comment by cgood92** [comment]
Note that if I use the selector `div > div`, everything works just as expected.  But, that's only cool if my structure has the second `div` as a direct descendant of the parent `div`.  For my real example that I'm working on, that is not the case...

**Comment by ljharb** [comment]
I don't think this is still an issue in v3; happy to reopen if so.
