### ISSUE TITLE
Allow support for Node.JS <= v0.12.9 

### ISSUE THREAD

**Issue by chriscartlidge** [airbnb/enzyme#94]
A lot of companies still use older versions of Node.JS for a variety of reasons.

That being said the optional dependancy on jsdom (^6.1.0) requires us to be using Node.JS v4 or greater. 

My recommendation is to use jsdom (~3.1.2) which is allow support for a greater number of previous versions of Node.JS. 

I have ran through the source code and also check the tests whilst using this version of the jsdom dependency and everything looks OK.

I'll submit a PR and link to this ticket for your consideration. (https://github.com/airbnb/enzyme/pull/95)

**Comment by blainekasten** [comment]
Looks like this can be closed as the PR is merged.

**Comment by ljharb** [comment]
Closed via #95.
