### ISSUE TITLE
predicate in `filterWhere` and `findWhere` should take index as second parameter

### ISSUE THREAD

**Issue by hesher** [airbnb/enzyme#943]
Using `component.findWhere(predicateFn)` would be really useful if the second parameter of `predicateFn` would be the index.

It is customary in all iterator functions in ES6.
For example:

```
['hello','mr'].find( (_, ind) => ind === 1 ) // return the second element
```

So in Enzyme, taking all elements starting with the 3rd element from a list could work like this:

```
domElement.find('.list-item').filterWhere( (_, ind) => ind >= 2 )
```

**Comment by ljharb** [comment]
Yes, but in ES6, they're iterating over a list. In enzyme, `.findWhere` is iterating over a tree - there *isn't* a useful index.

For the use case you mentioned, you can use `.slice(2)`.

**Comment by hesher** [comment]
That's a good point I haven't considered.
I guess I'll close the issue

**Comment by hesher** [comment]
Interesting to notice though - `forEach()` function does take index as second parameter

**Comment by ljharb** [comment]
True, that's a fair point. I kind of feel though like it'd be best to remove all index arguments, rather than add in the "missing" ones.

What's the use case (besides slice) where you need the index?

**Comment by hesher** [comment]
Specifically, I'm writing a component driver and allowing the user of the driver to pass in a predicate to determine which instance of the element matching the driver he would like to wrap. 

In certain cases, specifically a list, I would like the user of the driver to choose the instance by the index. 

Right now I'm planning on using forEach and increment a counter, but it will be a hack and will force me to run over all the results instead of stopping when the first match is found.

Example:

'''
ListItem.createrDriver(listElement, (_, ind) => ind === 3)
'''
This will wrap the third list item under listElement and return the driver.

**Comment by ljharb** [comment]
Why is the index the best information the user has to select an item?

**Comment by hesher** [comment]
It's usually not the best but when you talk about things that have order (lists, arrays, iterables) it's sometimes easier to refer to an item by the index (get me the second item in the list) and not to force the user to add specific values to the item so it is recognizable (get me the item that has a contrived value I added to it so I can explain to you which list item I'm referring to)

**Comment by hesher** [comment]
Bottom line, it's nice to have. That's probably why JavaScript added it. But maybe not.

**Comment by ljharb** [comment]
You'll note that the index is provided in the language when iterating over arrays, but that the iterable protocol introduced in ES6 lacks any concept of "index" or "count".
