### ISSUE TITLE
setState for connected components.

### ISSUE THREAD

**Issue by supritashankar** [airbnb/enzyme#946]
Browser.tsx

```jsx
export class UBrowserLoader extends React.Component<IProps, IState> {
  public state = {
    loading: true;
  }
  public render() {
    const {errorState} = this.props;
    if (errorState) {
      // some code
      return <div className="error"></div>
    }
    if (this.state.loading) {
      // some code
      return <div className="loading"></div>.
    }
    return <div className="browser-body">Hello</div>
}
export const BrowserLoader = connect(mapStateToProps, mapDispatchToProps)(UBrowserLoader)
```

My tests look like this
```jsx
describe("Browser tests", function() {
  test("test the browser loader for error case", () => {
        const mockStore = configureMockStore([thunk]);
        const store = mockStore({
            errorState: {
                error: "internal error"
            }
        });

        const wrapper = mount(<Provider store={store}><BrowserLoader/></Provider>);
        expect(wrapper.find('.error')).toHaveLength(1);
        expect(wrapper.find('.browser-body')).toHaveLength(0);
    });
  test("tests the loader on the browser", () => {
    const mockStore = configureMockStore([thunk]);
        const store = mockStore({errorState: {}});
        const wrapper = mount(<Provider store={store}><BrowserLoader/></Provider>);
        expect(wrapper.find('.loading')).toHaveLength(1); // this works
        expect(wrapper.find('.error')).toHaveLength(1); // this works
        wrapper.setState({loading: false})
        expect(wrapper.find('.loading')).toHaveLength(0); // does not work!!!!! it does not setState on the child component
```

How do I get this to work? Any ideas?
Any help will be appreciated!

cc @lelandrichardson  - I saw your comments regarding this on another github issue - where you said to test the flux cycle one can use mount. But I don't understand how to do it in this case.

**Comment by ljharb** [comment]
Can you explain `if (errorState) {..<div class="error"></div>}`, which looks like very invalid code? Is that some kind of TypeScript thing?

**Comment by supritashankar** [comment]
@ljharb I corrected it. it was my bad.

**Comment by ljharb** [comment]
@supritashankar again tho, you've just got an element hanging out there, it's not `return`ed or used.

**Comment by supritashankar** [comment]
@ljharb I have corrected it. This is to just give the idea. How do I setState on the child pure component?

**Comment by ljharb** [comment]
Shallow-render the wrapper, and use `.dive()` - then you have an enzyme wrapper around the wrapped component.

**Comment by dabit1** [comment]
I finally found a very good solution to avoid decoration on mounted components. For shallowed components you can use `dive()` but there is no similar method for mounted components. This is the solution I did:

```javascript
const wrapper = mount(shallow(<MyComponent />).get(0))
```

Works like a charm :)

**Comment by debo07** [comment]
> Shallow-render the wrapper, and use `.dive()` - then you have an enzyme wrapper around the wrapped component.

And what do I do if I have `refs` in the same component and that's also needs to be tested.

**Comment by ljharb** [comment]
@debo07 use ref callbacks (since string refs are deprecated), and unit test those.
