### ISSUE TITLE
Simulate event throws error 

### ISSUE THREAD

**Issue by tonitagd** [airbnb/enzyme#948]
I am trying to fire an event on a child component of my ShallowWrapper. Everything looks fine as I am able to render it and find the exact node on which I want to fire the event but it seems like most of the functionalities that Shallow/React/Cheerio Wrappers have, do not work. 

```
ComposerApp = shallow(<App {...props}/>);
instance = ComposerApp.instance();

const wrapper = ComposerApp.find(EmbeddedApp).render();
const inputNode = wrapper.find('.content');

console.log(inputNode.html()); // Prints the inputNote html properly

// I get an error here:
inputNode.simulate('keydown', {
    key: 'Enter',
    keyCode: 13,
    which: 13
});
```

When I print the founded node I get the proper HTML String, but I cannot console.log the node itself:

`TypeError: undefined is not a constructor (evaluating 'target.dispatchEvent(e)') in http://localhost:9876/context.js (line 397)
serialize@http://localhost:9876/context.js:397:42
stringify@http://localhost:9876/context.js:46:25
stringify@http://localhost:9876/context.js:64:45
log@http://localhost:9876/context.js:127:33
http://localhost:9876/context.js:218:19
tests/unit/index.js:473918:19
loaded@http://localhost:9876/context.js:151:17`

or I cannot simulate any event:

`TypeError: undefined is not a constructor (evaluating 'inputNode.simulate('keydown', {
			key: 'Enter',
			keyCode: 13,
			which: 13
		  })') in tests/unit/index.js (line 473919)
tests/unit/index.js:473919:26
loaded@http://localhost:9876/context.js:151:17`

**Note** I cannot mount the parent as one of its children uses conect and I cannot pass the store to it.

I am new to react testing and I am not sure if this is expected behaviour, so I apologise in advance

**Comment by ljharb** [comment]
`render` provides a cheerio wrapper, which doesn't have `simulate` - only `shallow` has that.

**Comment by tonitagd** [comment]
Ah, I see... So I got to a workaround of this issue. I created one shallow and one mounted wrapper of the application. The mounted wrapper is wrapped in <Provider> so it can pass the store to its children and I use the mounted wrapper to find the '.content' node and simulate event on it. 
Thanks for the response.
