### ISSUE TITLE
Snapshot different on CI

### ISSUE THREAD

**Issue by DCKT** [airbnb/enzyme#950]
Hello,

I'm using Enzyme with Jest snapshot with CircleCI and I expect a strange behavior on Circle.
The tests with Enzyme generates a snapshot diff with a different `_debugID`.

My test : 
```javascript
test('Test with enzyme', () => {
  const props = {
    ...defaultProps,
    delivery: {
      ...delivery,
      delivery_state: 'delivery_failed'
    }
  }
  const wrapper = shallow(<StatusPlayer {...props} />)
  wrapper.setState({
    missingName: true,
    missingSignature: true,
    nameField: ''
  })

  expect(wrapper).toMatchSnapshot()
})
```
The output 
```
 -        "_debugID": 160,
 +        "_debugID": 2,
```

On my local, I don't have this behavior.

Have you got an idea about this ?
Thanks

**Comment by ljharb** [comment]
Snapshots aren't part of enzyme; enzyme's debug output comes from React. I'm not sure how we can help here.

**Comment by jwbay** [comment]
Unless you've installed a snapshot serializer for Enzyme specifically, that code is serializing the entire enzyme wrapper instance, which includes the React component instance (which is where the debug id comes from). This is way too much information. You probably want something like this, which generates a much, much smaller snapshot of the 'shape' of the component's output: https://github.com/adriantoine/enzyme-to-json

**Comment by DCKT** [comment]
Thanks for your answers.

Indeed @jwbay I used `enzyme-to-json` and it works perfectly. Thanks for your explanation !
