### ISSUE TITLE
this.refs is deprecated, so enzyme can't handle Callback attributes

### ISSUE THREAD

**Issue by sandrina-p** [airbnb/enzyme#954]
Before I had components like this:

```jsx
class Foo extends React.Component {
  render() {
    return (
      <div>
        <span ref="firstRef" amount={2}>First</span>
      </div>
    );
  }
}
```

And on enzyme with Jest it works like charm:

```js
const wrapper = mount(<Foo />);
expect(wrapper.ref('firstRef').prop('amount')).toEqual(2);
```

Now, that [refs-strings are near to be deprecated](https://zhenyong.github.io/react/docs/more-about-refs.html#the-ref-string-attribute) I started to write them as a Callback attribute.

```jsx
<span ref={ (ref) => { this.firstRef = ref; } } amount={2}>First</span>
```

Now it comes the problem because the tests are failing:

> Method “prop” is only meant to be run on a single node. 0 found instead.

How can I work it around?

Thanks!

**Comment by ljharb** [comment]
It wouldn't make sense for .ref to work with callback refs, since there's no way for enzyme to know what you're doing with the ref node. If you assign it to `this.firstRef`, then you should be able to do `wrapper.instance().firstRef`.

**Comment by sandrina-p** [comment]
Hum... I'm not sure about it. I have a ref called `tab-2`

```js
wrapper.instance()['tab-2'].simulate('click');
```

>TypeError: wrapper.instance(...).tab-2.simulate is not a function

What I am missing here? 🤔

**Comment by ljharb** [comment]
What does the ref callback look like for that?

Separately, a ref is a node - it wouldn't have an enzyme wrapper on it.

**Comment by sandrina-p** [comment]
```js
<span ref={ (ref) => { this[`tab-${index}`] = ref; } } amount={index}>{value}</span>
```

This ref is created in a map, so its name is not straightforward. The solution I am seeing here is to reduce the name without special characters

**Comment by ljharb** [comment]
Or put it in a dictionary instead of directly on the `this`

**Comment by sandrina-p** [comment]
Like what?

**Comment by ljharb** [comment]
`this.tabs[index] = ref;`

**Comment by sandrina-p** [comment]
Ah! ill try it out and then post results, thank you 👌

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Wed, May 24, 2017 at 18:31, Jordan Harband <notifications@github.com> wrote:
this.tabs[index] = ref;

**Comment by sandrina-p** [comment]
`this.tabs[index] = ref;` doesn't work, even on development.
>  TypeError: Cannot set property '0' of undefined
It makes sense because at the time this.tabs doesn't exist at all. I even created a if to set `this.tab = {}` but then on tests, said: 

> TypeError: wrapper.instance(...).tab[mockIndex].simulate is not a function

So, I tried `this[`tab${index}`] = ref;`. It didn't work neither.

> wrapper.instance(...).tab2.simulate is not a function

Any other solution?

**Comment by ljharb** [comment]
Sorry I'm not being clear - you can't ever call .simulate on a ref directly, because that's not an enzyme wrapper, it's a DOM node.

**Comment by sandrina-p** [comment]
Hum... But if I do this, it works perfectly:

```jsx
<div>
   <button ref="clickMe">Click me</button>
   <button ref="hoverMe">Hover me</button>
</div>
```

```js
wrapper.ref('clickMe').simulate('click');
```

**Comment by ljharb** [comment]
In that case enzyme wraps it for you, but that approach is deprecated.

**Comment by sandrina-p** [comment]
So whats the best way to target an emement without refs?

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Fri, May 26, 2017 at 16:54, Jordan Harband <notifications@github.com> wrote:
In that case enzyme wraps it for you, but that approach is deprecated.

**Comment by ljharb** [comment]
tbh, it's not to. Shallow rendering and asserting on props covers like 99% of what you need; and you don't need to test React itself or the DOM.

**Comment by sandrina-p** [comment]
Hum... Let me show you a real test:
```js
    test('<Accordion /> click on its tab', () => {
        const mockIndex = 2;
        const wrapper = mount(
            <Accordion { ...mockedProps } />
        );

        wrapper.instance()._selectTab = jest.fn();
        wrapper.ref(`tab-${mockIndex}`).simulate('click');

        expect(wrapper.instance()._selectTab).toBeCalledWith(mockIndex);
        expect(toJson(wrapper)).toMatchSnapshot();
    });

In this test I add test coverage to the click method on the tab (the button shown on the client before) and make sure it calls `_selectTab()` with the correct argument. Are you telling me this test is redundant?

**Comment by ljharb** [comment]
I'm suggesting that you shallow-render, and .find the element with the onClick, and then just *call it directly* to see what it does. You don't have to test that react wires up onClicks correctly.
