### ISSUE TITLE
Unnecessarily complex output when expect(elements).toHaveLength() fails in Jest

### ISSUE THREAD

**Issue by apaatsio** [airbnb/enzyme#955]
With such a simple looking test like
```jsx
import React from 'react';
import { shallow } from 'enzyme';

it('has 3 items', () => {
  const wrapper = shallow(
    <ul>
      <li>item 1</li>
      <li>item 2</li>
    </ul>
  );
  expect(wrapper.find('li')).toHaveLength(3);
});
```
The error output looks like there's a bit too much information
```
 FAIL  src/ui/__tests__/MyTest.test.js
  ● has 3 items

    expect(received).toHaveLength(length)
    
    Expected value to have length:
      3
    Received:
      {"complexSelector": {"buildPredicate": [Function buildPredicate], "childrenOfNode": [Function childrenOfNode], "findWhereUnwrapped": [Function findWhereUnwrapped]}, "length": 2, "node": <li>item 1</li>, "nodes": [<li>item 1</li>, <li>item 2</li>], "options": {}, "renderer": null, "root": {"complexSelector": {"buildPredicate": [Function buildPredicate], "childrenOfNode": [Function childrenOfNode], "findWhereUnwrapped": [Function findWhereUnwrapped]}, "length": 1, "node": <ul><li>item 1</li><li>item 2</li></ul>, "nodes": [<ul><li>item 1</li><li>item 2</li></ul>], "options": {}, "renderer": {"_instance": null, "getRenderOutput": [Function getRenderOutput], "render": [Function render]}, "root": [Circular], "unrendered": <ul><li>item 1</li><li>item 2</li></ul>}, "unrendered": null}
    received.length:
      2
      
      at Object.<anonymous>.it (src/ui/__tests__/MyTest.test.js:11:30)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```

The JSON looking like monster contains quite a lot useless information and is hard to read. And this is just for an extremely simple component. It gets worse with more complex ones. 

A more useful output would be, for example:

```
 FAIL  src/ui/__tests__/MyTest.test.js
  ● has 3 items

    expect(received).toHaveLength(length)
    
    Expected value to have length:
      3
    Received:
      [
        <li>item 1</li>,
        <li>item 2</li>
      ]
    received.length:
      2
```

I'm not sure if this is a problem in Enzyme or Jest or both, but I'm sure we'll figure it out.

Used versions:
enzyme: 2.8.2
jest: 20.0.3
react: 15.5.4
react-scripts: 1.0.5
enzyme-to-json: 1.5.1 (I don't think this affects this particular test, but I had it installed anyway)

**Comment by ljharb** [comment]
This seems unique to jasmine/jest's output; I'm not sure what would be a clean way of providing simpler output automatically.

**Comment by apaatsio** [comment]
I see. I looked at the Jest code, and yeah, this is a Jest feature. It just spits out the object that it is given. 

One solution would be to write a custom Jest matcher and not use the default one.

I'll close this as it looks like there's nothing to do within the Enzyme project.

**Comment by ekulabuhov** [comment]
Facing exactly same problem with this setup. Is there an issue raised with Jest I could follow or have you found a solution?

**Comment by eddyerburgh** [comment]
I've opened a feature request in enzyme to remove received for custom objects—https://github.com/facebook/jest/issues/6519
