### ISSUE TITLE
contains() with multiple nodes/jsx elements

### ISSUE THREAD

**Issue by artemstepanenko** [airbnb/enzyme#957]
I have a Component which debugs renders as such:

```javascript
  console.log src/components/WidgetList/WidgetList.test.js:12
      <div className="row WidgetList">
      <div className="col-xs-6 col-sm-4 col-lg-3">
      <Connect(WeekNumber) />
      </div>
      <div className="col-xs-6 col-sm-4 col-lg-3">
      <Connect(BugsDiff) />
      </div>
      <div className="col-xs-12 col-sm-12 col-lg-6">
      <Connect(BugsHistory) />
      </div>
      </div>
```

And I'm trying to see if WeekNumber, BugsDiff and BugsHistory are present.
The following works:

```javascript
expect(widget.contains(<WeekNumber />)).toEqual(true);
expect(widget.contains(<BugsDiff />)).toEqual(true);
expect(widget.contains(<BugsHistory />)).toEqual(true);
```

but when I use an array like `contains([<BugsDiff />, <BugsHistory />, <WeekNumber />]).toEqual(true)` it doesn't.. 

What am I doing wrong?

**Comment by ljharb** [comment]
`contains` takes an element, not an array - if you want the array, you need something like `expect(elements.every(el => widget.contains(el))).toEqual(true);`.

In other words, the expectation that you can use "contains" to check more than one thing at once is the part that seems wrong.

**Comment by artemstepanenko** [comment]
@ljharb I appreciate your reply. Maybe, I'm missing something. I've found a few examples with arrays [here](https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/contains.md).

**Comment by ljharb** [comment]
Whoops, you're right, my mistake.

You can see [in the source](https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L385) that if it's an array, it sees if it contains [that exact sequence](https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L162). In other words, it's not for checking "do all of these elements appear somewhere", it's for checking "does this sequence of elements appear somewhere".

In your case, you still want to check that three independent elements appear, so you'll still need three separate checks.

**Comment by artemstepanenko** [comment]
@ljharb thank you very much.

**Comment by gkatsanos** [comment]
@ljharb do you think it would be possible to add this clarification to the examples/documentation? It's quite confusing if you read it as-is.

**Comment by ljharb** [comment]
Absolutely; PRs to improve documentation are always appreciated.
