### ISSUE TITLE
Finding component Through Enzyme mounted <MemoryRouter />

### ISSUE THREAD

**Issue by dschinkel** [airbnb/enzyme#958]
Ok, stuck.  I know this isn't necessarily a bug but really wanted to get some help on this one.

I'm not able to `find()` my component.  What I get back is a mounted <MemoryRouter /> so not sure how to work with this.
 
And...pretty sure (not entirely though) I have jsdom setup using the newer jsdom sytax but not 100% sure yet but it certainly isn't causing me any errors so far.

**jsdom.js**
```
const jsdom = require('jsdom')
const { JSDOM } = jsdom

global.window = new JSDOM(`<!doctype html><html><body id='root'></body></html>`).window
global.document = window.document
```

Test
```
require('../jsdom')

describe('Protected Route', () => {
  let store, app, index, responseBody

  beforeEach(() => {
    store = initStore()

    const App = ({store}) => (
      <Provider store={store}>
        <Layout>
          <Switch>
            <ProtectedRoute component={DashboardContainer} path='/dashboard'/>
          </Switch>
        </Layout>
      </Provider>)

    app = mount(<MemoryRouter><App store={store} /></MemoryRouter>)
  })

  it.only('renders requested route if authenticated', () => {
    const dashboard = app.find(DashboardContainer)
    expect(dashboard).to.exist
  })
})
```

Here is what I see in WebStorm, looks like I have an instance of `<MemoryRouter />` coming back after mounting:

<img width="1117" alt="screen shot 2017-05-29 at 5 48 20 pm" src="https://cloud.githubusercontent.com/assets/338798/26563589/fe4bb214-4499-11e7-9c45-1dd96a87d04a.png">

**Comment by dschinkel** [comment]
eh nevermind I resolved it.  Gonna do a blog post on it.

**Comment by arjunmehta** [comment]
@dschinkel Did you ever write that blog post? 😄 
Any insight on how you resolved this after all? I know it was a while ago...
