### ISSUE TITLE
Form onChange not triggered by Form Element Change

### ISSUE THREAD

**Issue by KeKs0r** [airbnb/enzyme#959]
I am tying to get a test passing, where I want to click on a button that under the hood triggers a checkbox, which then should bubble to a form onChange event. This works in real browsers, but somehow not woking in my test case. This is the minimal test case that is failing for me:

```javascript
test.only('onChange form', () => {
  let myRef
  const onClick = () => {
    myRef.focus()
    myRef.click()
  }
  const spy = Sinon.spy()

  const wrapper = mount(
    <form onChange={spy}>
      <button onClick={onClick}>Button</button>
      <input
      type="checkbox"
      ref={ref => { myRef = ref } }
      />
    </form>
  )
  wrapper.find('button').simulate('click')
  expect(spy.called).toBeTruthy()
})
```

I would expect the button click triggering the checkbox to change and in turn the spy to be called. Which seems not to be the case.

**Comment by ljharb** [comment]
`simulate` isn't to allow you to test React event wiring, or the browser. simulating "click" calls `onClick`, that's it.

You don't need to test that a change event fired inside your `<form>` will bubble up - that's how browsers work. All you need to assert in your test is that there's an `onChange` handler on the form.

**Comment by KeKs0r** [comment]
Thanks for the clarification.
