### ISSUE TITLE
Request: add option to debug() to ignore props

### ISSUE THREAD

**Issue by finnigantime** [airbnb/enzyme#960]
It would be nice to have an option in debug() that skips printing props in the debug string.

For large components with many props spread across the different elements in the render tree, if you want to focus on the structure of the tree when debugging, this option can hide all props so you can focus just on the hierarchy of elements.

This is particularly useful if matchesElement() is used in a test that fails. matchesElement() just returns a boolean that doesn't show the diff of what didn't match when it fails. Using debug() is the best way to debug this. However, matchesElement() ignores props in its comparison, so it would be nice to have a variant of debug() that also ignores props so that it can be used while debugging to figure out exactly what is the diff between actual and expected values that caused matchesElement()  to fail.

**Comment by ljharb** [comment]
Seems reasonable; but it might be tricky in that I think in `debug` we just pass through what React gives us.

**Comment by finnigantime** [comment]
Took a stab at it (wrote the code before I filed this issue), let me know what you think.

Also, this might be useful inhttps://github.com/blainekasten/enzyme-matchers/pull/95
