### ISSUE TITLE
Enzyme does not render DOM tree of higher order components with mount

### ISSUE THREAD

**Issue by AkshatM** [airbnb/enzyme#966]
Version 2.7.1.

I have defined a higher-order component called `persistChanges`, and am using `mount` to test lifecycle calls around a mock object called `WrappedComponent` in a Node environment (i.e. [without `jsdom`](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md)).

This is the code that's generating the issue, in a nutshell:
 ```jsx
 const simpleComponent = mount(<WrappedComponent />);
 console.log(simpleComponent.debug())
    
 // correctly yields the expected DOM output:
 //  <WrappedComponent currentText="">
 //    <div className="test">
 //      Default text to display when no data is available.
 //    </div>
 //  </WrappedComponent>
    
 const enhancedComponent = persistChanges(WrappedComponent);
 // enhancedComponent merely renders WrappedComponent
 const renderedComponent = mount(<enhancedComponent />);
 console.log(enhancedComponent.debug());
 // yields just <enhancedComponent />
```
**Subsequent tests for children on enhancedComponent, including `.find()`, `.children()`, `.text()`, etc. all return empty.** The tests in question (using Jest as the assertion library):
```jsx
// fails with count 0 for enhancedComponent, but passes with count 1 for WrappedComponent
test('check length of children', () => {
  expect(renderedComponent.children().length)
  .toBe(1);
});
    
// fails with received response "" for enhancedComponent, but passes with WrappedComponent
test('fires a request and receives no data from cache', () => {
  expect(renderedComponent.text())
  .toBe('Default text to display when no data is available.');
});
```
The same tests pass for the `WrappedComponent`, even though `enhancedComponent` merely renders `WrappedComponent`. I can't find the `div className='test' />` component in `enhancedComponent`, and, worse, `.children()` seems to think nothing is there.

This is the code for the HOC (with lifecycle methods removed - removing them did not alter this behaviour): 
```jsx
function persistChanges(WrappedComponent) {
  return class extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        data: {},
      };
   }
    
    render() {
      return <WrappedComponent {...this.state.data} />;
    }
  };
}
```
This is the `WrappedComponent` (also with lifecycle methods removed): 

```jsx
class WrappedComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      textToSave: 'This is the data we want to save',
      currentText: 'Default text to display when no data is available.',
    };
  }
    
  getDataToPersist() {
    return { currentText: this.state.textToSave };
  }
    
  render() {
    return (<div className="test">{this.state.currentText}</div>);
  }
}
```

I am fairly certain there must be something I am doing wrong, as support for HOCs with `mount` should be straightforward. I have scoured the documentation, and cannot find any similar resolved issue (everything with HOCs appears to be about usage with `shallow`, which I am not using).

**Comment by ljharb** [comment]
(updated your OP to include triple backticks, so there's proper syntax highlighting)

When you say "correctly yields the expected DOM output:" but then it contains "<WrappedComponent currentText="">", it seems like your expectations are off. `debug` doesn't contain DOM output, or else it wouldn't contain "WrappedComponent", which isn't a DOM element.

What does `.html()` look like?

**Comment by AkshatM** [comment]
Thanks!

With `.html()`, they look as so: 

```
<enhancedcomponent></enhancedcomponent>
```

and for `WrappedComponent`

```
<div class="test">Default text to display when no data is available.</div>
```

respectively.

**Comment by ljharb** [comment]
Gotcha, that makes sense.

Any chance if you add a `displayName` to the persistChanges HOC that it changes things? Currently you're returning an anonymous class with no `displayName`.

**Comment by AkshatM** [comment]
It makes no difference.

```jsx
function persistChanges(WrappedComponent) {
  const generatedComponent = class extends Component {
    constructor(props) {
      super(props);
      this.handleChange = this.handleChange.bind(this);
      this.state = {
        data: {currentText: 'I am a Baarbie girl'},
      };
    }

    render() {
      return <WrappedComponent {...this.state.data} />;
    }
  };
  generatedComponent.displayName = `foo`;
  return generatedComponent;
}
```

**Comment by ljharb** [comment]
Thanks for confirming.

One more guess: components with a lowercased name are DOM elements; custom elements *must* start with an uppercase letter - ie, if you name it "EnhancedComponent", not "enhancedComponent", what happens?

**Comment by AkshatM** [comment]
That fixes it. I can't believe I overlooked that. Thank you!

**Comment by dabit1** [comment]
I finally found a very good solution to get a wrapper from a decorated component. For shallowed components you can use `dive()` but there is no similar method for mounted components. This is the solution I did:

```javascript
const wrapper = mount(shallow(<MyComponent />).get(0))
```

Works like a charm :)
