### ISSUE TITLE
Convert all usages of noop mocha expressions to function matchers

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#97]
There are a few instances in our [doc examples](https://github.com/airbnb/enzyme/blob/38ae4b22a78ae3570b2c35c4071602037e2b0c9c/docs/api/ReactWrapper/every.md#examples), and our [tests](https://github.com/airbnb/enzyme/blob/36b38ed9e41fe4744ab883f8de2430e494ce04fc/src/__tests__/ReactWrapper-spec.js#L64-L65) which currently violate our [styleguide](https://github.com/airbnb/javascript). This also forces the relevant [eslint rule](https://github.com/airbnb/enzyme/blob/9ced15fe03a3b45ab176f5f97e9b224480bfeb6c/src/__tests__/.eslintrc#L4) to be disabled.

A great first task would be removing this rule override, and fixing our tests and docs to use, for example, `.to.equal(true)` instead of `.to.be.true`. (One reason this form is superior, is that `expect(false).to.be.truthy`, which many might think is a valid matcher, will silently pass tests as a no-op, because `truthy` isn't a thing).

(Per https://github.com/airbnb/enzyme/commit/d00c1422ba8559e6f41f9e3ff9cbd38cf9925c4a#commitcomment-15192634 and #96)

**Comment by zeke** [comment]
@ljharb this is good to know. I have some projects using `chai` that are using these brittle expressions.

Where in the styleguide is The Right Way™ covered? I poked around but couldn't find it.

**Comment by ljharb** [comment]
@zeke it may not be explicitly laid out (just covered by the eslint rule), but if not, please file an issue so we can add a section :-)
