### ISSUE TITLE
CharCode issue when using shallowWrapper.text()

### ISSUE THREAD

**Issue by thekemkid** [airbnb/enzyme#972]
Hello :)

I'm encountering a _really_ weird piece of behaviour at the moment, relating to the charCode in a string being returned in a .text() call. Below is a simple example that fails unexpectedly:

```
import React from 'react'
import test from 'tape'
import { shallow } from 'enzyme'

test('that it works as expected', (t) => {
  const aNumber = 123
  const localised = aNumber.toLocaleString('de', {style: 'currency', currency: 'EUR'})
  const rendered = shallow(<div id='someCoolId'>{localised}</div>).find('#someCoolId').text()

  t.equal(localised, rendered)
  t.equal(localised.charCodeAt(1), rendered.charCodeAt(1))

  t.end()
})
```

(If needed, I can put this into a repo with a `package.json` configured for running)

output on my machine:
```
that it works as expected

    ✖ should be equal
    ------------------
      operator: equal
      expected: '€ 123.00'
      actual:   '€ 123.00'
      at: Test.<anonymous> (/Users/glen/work/min.test.js:10:5)


    ✖ should be equal
    ------------------
      operator: equal
      expected: 32
      actual:   160
      at: Test.<anonymous> (/Users/glen/work/min.test.js:11:5)
```

 I have investigated the codebase and found this line to be the source: https://github.com/airbnb/enzyme/blob/master/src/ShallowTraversal.js#L152

The whitespace here is charCode 32, but the charCode of the whitespace in the toLocaleString call is 160... 🤔

Because its a charcode whitespace issue, I'm not sure what can be done 🤔

**Comment by ljharb** [comment]
There are many whitespace characters. Perhaps it'd be more accurate to check that the character matches `/\s/`?
