### ISSUE TITLE
Null state when mounting a React Component in Karma

### ISSUE THREAD

**Issue by yingw787** [airbnb/enzyme#974]
Hi,

I'm using MobX, Immutable.js, Karma, and [mocha, enzyme-expect, sinon] when I'm trying to test the state of my React component, and I'm getting `null` when logging out `el.state()`. This is despite the fact that I have set some amount of state in the constructor.

Constructor in React Component:
```
        this.state = Immutable({
            keyOne : [ // array of objects
            ],
            keyTwo: null,
            keyThree: 0,
        });
```

Test:
```
        let el = mount(<ReactComponent someProp={ somePropValue } />);
        expect(el.state().keyOne).toExist();
```

When I run this, I get back from the Karma runner this error message: `TypeError: Cannot read property 'keyOne' of null`.

Does anybody know what's going on? I can provide more detailed information (version numbers, etc.) upon request.

**Comment by ljharb** [comment]
I wouldn't expect to be able to set `this.state` to anything but a plain object in React (that perhaps contained immutables); is that something MobX allows?

**Comment by yingw787** [comment]
@ljharb I think we've been following off of this: https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state

We don't use setState to set state in our React component, we do something like this.state = this.state.set(<Immutable thing>). @jpiv

**Comment by ljharb** [comment]
Note that in that example, `state` is just a plain object, but its values are Immutable.

**Comment by yingw787** [comment]
@ljharb sorry, this is probably a better example, as we are using seamless-immutable: https://medium.com/@ckoster22/seamless-immutable-an-alternative-to-immutablejs-12795d6bf577

so we do something like this.state = this.state.set('key', newValue); this.forceUpdate(); when we update our state

**Comment by ljharb** [comment]
That article doesn't mention `this.state` or `this.setState` anywhere?

**Comment by yingw787** [comment]
mm I think this section provides a good example of what we do:

```
/* Or equivalently
const nextState = DEFAULT_STATE
                     .set('users', payload.users)
                     .set('items', massageItemsData(payload.items));
*/
```

We don't use the `this.setState` method provided by React, instead we replace the state with a new immutable object.

**Comment by ljharb** [comment]
Gotcha.

I'm not sure how well that will work with enzyme; but if you can provide a PR with some good test cases, we may be able to provide a fix.

**Comment by ljharb** [comment]
I'm going to close this, but will be happy to reopen with some test cases.
