### ISSUE TITLE
Only children of DOMComponents available through children() and childAt()

### ISSUE THREAD

**Issue by jantorestolsvik** [airbnb/enzyme#977]
I use react-redux and connect many places in my code and i noticed that some of the components does not have parents when i find them using find() and they are not in the component tree when i check childAt().childAt() etc. 

The problem seem to be that components wrapped in Children.only(children) does not appear in the component tree. Is that intentional?

```javascript
const Comp = ({ children }) => Children.only(children);

const wrapper = mount(
      <Comp>
        <div>test</div>
      </Comp>
)

wrapper.children.length // 0
```

EDIT:

It seems intentional. When I fixed the issue the following tests broke 

```javascript
it('should handle mixed children with and without arrays', () => {
        const Foo = props => (
          <div>
            <span className="foo" />
            {props.items.map(x => x)}
          </div>
        );

        const wrapper = mount(
          <Foo
            items={[
              <i key={1} className="bar">abc</i>,
              <i key={2} className="baz">def</i>,
            ]}
          />,
        );
        expect(wrapper.children().length).to.equal(3);
        expect(wrapper.children().at(0).hasClass('foo')).to.equal(true);
        expect(wrapper.children().at(1).hasClass('bar')).to.equal(true);
        expect(wrapper.children().at(2).hasClass('baz')).to.equal(true);
      });
```

From what I could see in the code also, .children() only returns children of DOMComponents. So unless a component is the child of a DOMComponent parent() will also fail, which is unfortunate (and the reason I found this strage behavoiur.)

I would like to change the behavoiur of children() so that it always returns the next component, regardless of which component .children() is used on. What do you think?

**Comment by ljharb** [comment]
In shallow rendering, I would expect `.children()` to be similar to `.props().children` - however, with `mount`, I'd expect either the same behavior, or i'd expect Comp's children to be a div.

I'm not exactly sure what to do here. A PR with test cases would help explain the impact - ideally, only with new test cases, and not altering any existing ones :-)

**Comment by jantorestolsvik** [comment]
I wrote another test for a case which is bothering me. 

```javascript
const Comp = ({ children }) => <div className="test">{children}</div>;
const wrapper = mount(<Comp />);
expect(wrapper.find('.test').parents()).to.have.length(1);
```

This will crash with the error  TypeError: Cannot read property 'reverse' of null because of the code
```
return pathToNode(inst, root).reverse();
```

where pathToNode uses childrenOfInst() to find the path, and since the component is not a child of anyone reverse() will be called on null.

I am not sure how it was intended for mount to work, but it seems inconsistent what you can access in the "DOM" through at() and childAt(), and that can cause some weird situations.

**Comment by ljharb** [comment]
@jantorestolsvik that bug is captured by #410

**Comment by ljharb** [comment]
I don't think this is still an issue in v3; please file a new issue if that's not the case.
