### ISSUE TITLE
Question: testing component directly inside an component

### ISSUE THREAD

**Issue by chrisregner** [airbnb/enzyme#978]
I'm trying to assert that all of my component's content is wrapped in another component. I've scanned the API but none of the methods I tried achieved the desired result. Here's an example:
```jsx
	// AnotherCmpt.js
	function AnotherCmpt({ children }) {
			return (<div className='layout styles'>
			 {children}
			</div>)
	}

	// MyCmpt.js
	function MyCmpt() {
			return (<AnotherCmpt>
					<div className={'foo'}>
							...all else
					</div>
			</AnotherCmpt>)
	}

	// MyCmpt.test.js
	const myCmpt = mount(<MyCmpt />)

	describe('<MyCmpt />', () => {
		it('it wraps all its content in <AnotherCmpt />', () => {	
			const myCmpt = shallow(<MyCmpt />
			// throws error
			expect(myCmpt.is('AnotherCmpt')).to.be.true
			// not working either, .childAt(0) returns <div class='foo'>
			expect(myCmpt.childAt(0).is('AnotherCmpt).to.be.true
			// this one works, but it doesn't ensure that everything's
			// wrapped in <AnotherCmpt />
			expect(myCmpt.find('AnotherCmpt')).to.have.lengthOf(1)
		})
	}
```

**Comment by ljharb** [comment]
This is an existing bug with mount and `is`.

Separately, I'd recommend always creating your wrapper inside every `it`, so that errors from it will fail the appropriate test - and, I'd suggest using `shallow` here, not `mount`.

**Comment by chrisregner** [comment]
Thanks for letting me know. I'd close this issue now but, do you mind if I ask you for resources where I can learn more about this?

> ...creating your wrapper inside every `it`,...

From beginner's perspective (as I am), I can't see how it would not fail the appropriate test if I'll use the same wrapper throughout the file. I've been creating my wrappers in `describe` block to prevent repetitiveness.

**Comment by ljharb** [comment]
@chrisregner It's a flaw with all BDD-style test runners (mocha, jasmine, jest, etc) - exceptions thrown outside an `it` aren't properly associated with the test. `describe` blocks run synchronously, and since a "describe" isn't a test, throwing an exception inside one won't give you a nice test failure message.

Repetition in tests is a *good* thing. DRY is for production code.

**Comment by chrisregner** [comment]
Thanks. Closing it now.

**Comment by ljharb** [comment]
(For reference, the existing bug: #768)

**Comment by chrisregner** [comment]
For those who are new to the idea that repetition is good in unit testing, this [stackoverflow answer](https://stackoverflow.com/questions/6453235/what-does-damp-not-dry-mean-when-talking-about-unit-tests/11837973#11837973) is a good, concise explanation.
