### ISSUE TITLE
Equivalence of components

### ISSUE THREAD

**Issue by perevezencev** [airbnb/enzyme#980]
I have a simple application on React and React-router:

    import React from "react";
    import { Switch, Route } from "react-router-dom";

    export const Home = () => (
      <div className="Home">Home</div>
    );

    export const Profile = () => (
      <div className="Profile">Profile</div>
    );
    
    const App = () => (
      <Switch>
        <Route exact path="/" component={Home}/>
        <Route path="/anotherRouteToProfile" component={Profile}/>
      </Switch>
    );
    
    export default App;

I want to write routing tests like this

    describe('<App />', () => {
      it('on "/profile" render `Profile` container', () => {
        const wrapper = render(
          <MemoryRouter initialEntries={['/profile']}>
            <App/>
          </MemoryRouter>
        );
    
        expect(
          wrapper.is(Profile)
        ).toBe(true);
      });
    });

Why this test is pass? In the browser on route `/profile` rendred blank page and on route `/anotherRouteToProfile` rendered Profile-component.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ExLBr.png

**Comment by ljharb** [comment]
I assume because `MemoryRouter` is rendering the Profile, since that matches the route.

I'm not sure how to help here :-/ happy to reopen if needed.
