### ISSUE TITLE
Basic example not working: Cannot read property 'be' of undefined

### ISSUE THREAD

**Issue by DrainMorten** [airbnb/enzyme#981]
Hi!
I am rather new to react and testing, and have hit a wall with what should be a very simple case. I have tried to look at similar issues but to no avail, so last resort is to post here. Following this basic example: http://airbnb.io/enzyme/docs/api/ShallowWrapper/instance.html
I have first imported the following:

```
import React from 'react';
import { shallow} from 'enzyme';
import renderer from 'react-test-renderer';
import { IntlProvider } from 'react-intl';
import Price from '../Price';
```
and then written the following test:

```
const wrapper = shallow(<IntlProvider locale="en"><Price className="Priceclass" >{2500}</Price></IntlProvider>);
  const inst = wrapper.instance();
  expect(inst).to.be.instanceOf(IntlProvider);
```

---

I have console logged the inst: 

```
IntlProvider {
      props:
       { locale: 'en',
         children:
          { '$$typeof': Symbol(react.element),
            type: [Object],
            key: null,
            ref: null,
            props: [Object],
            _owner: null,
            _store: {} } },
```
.............

The error i get is "Cannot read property 'be' of undefined", and I cant understand why? As seen by the console.log, it should match the IntlProvider?

Thanks, eager to learn!
Kind regards,
Morten

**Comment by ljharb** [comment]
This looks like an error in your test framework - it looks like you're using expect, but not chai's expect.

**Comment by ljharb** [comment]
(happy to keep discussing and debugging here, of course, but I closed the issue because it has nothing to do with enzyme)

**Comment by DrainMorten** [comment]
Hi, thanks for the input, understand that you close the topic. I am using jest, yes. I read now that the Enzyme examples are using chai and mocha. Is there some sort of overview of what the equivalent of the different commands(?) like .to.have and to.be etc is when using jest?

**Comment by ljharb** [comment]
jest has jasmine's syntax; either jest's docs or jasmine's should tell you.
