### ISSUE TITLE
Can't simulate press event in react-native

### ISSUE THREAD

**Issue by cigdemgullu** [airbnb/enzyme#991]
We have implemented NativeBase's CheckBox where you can find [here](https://github.com/GeovisionGroup/tvb.a/blob/master/src/components/check/CheckInput.tsx).
It simply iterates over a list and return a set of ListItems which contains CheckBox.
We are trying to write unit test of this component and stuck at simulation of press event. 
The press event is bind to ListItems. You can find the test code below. Having trouble testing `press`event.

```
import * as React from 'react'
import { mount } from 'enzyme'
import * as chai from 'chai'
import { ListItem } from 'native-base'

it('onPress()', () => {
        const wrapper = mount(getComponent(commonProps))
        wrapper.find(ListItem).first().simulate('press')
})
```
And the console output is

```
TypeError: ReactWrapper::simulate() event 'press' does not exist
```

We appreciate any feedback about event simulation.

**Comment by rndmerle** [comment]
Just to be sure, because you're using press you're under React-Native?
Do `wrapper.find(ListItem).first().props().onPress()` works?

**Comment by ljharb** [comment]
In general, I've found it's best to invoke the prop directly and avoid `.simulate`.

**Comment by cigdemgullu** [comment]
Thanks a lot
