### ISSUE TITLE
TypeError: _react2.default.createElement is not a function

### ISSUE THREAD

**Issue by wjdimba** [airbnb/enzyme#992]
"devDependencies": {
    "babel-core": "^6.9.1",
    "babel-eslint": "^6.0.4",
    "babel-jest": "20.0.3",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-object-assign": "^6.8.0",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2016": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-native": "1.9.2",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.23.1",
    "enzyme": "^2.8.2",
    "html-webpack-plugin": "^2.28.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "20.0.4",
    "jest-css-modules": "^1.1.0",
    "react-addons-test-utils": "^15.6.0",
    "react-test-renderer": "^15.6.1",
    "style-loader": "^0.13.1",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  }

**Comment by aweary** [comment]
@wjdimba there's no information here that would help us understand your issue, nor is there any indication that this problem is related to Enzyme at all. If you can provide steps to reproduce the issue that indicates Enzyme is causing the problem I'll be happy to re-open this.

**Comment by wjdimba** [comment]
I have a simple test code


import React from 'react'
import Todo from '../src/component/Text'
import { shallow } from 'enzyme'

const setup = () => {
    const props = {
    }
    const wrapper = shallow(<Todo />)
    return {
        props,
        wrapper
    }
}

describe('Todo', () => {
    const { props, wrapper } = setup()

    it('Todo item should  render', () => {
        expect(wrapper.find('Container').exists())
    })
    
})


![image](https://user-images.githubusercontent.com/7369822/27332432-6d218f0e-55f4-11e7-86b0-9a6f660a8ba2.png)

**Comment by wjdimba** [comment]
@aweary

**Comment by aweary** [comment]
It looks like a problem with your build setup or Babel configuration. Can you inspect what the `react` import is resolving to? It's hard to say what the issue is here without an actual reproduction (e.g., a small repo we could clone and reproduce the issue in), but it still doesn't sound like it's related to Enzyme.
