### ISSUE TITLE
Getting `Unexpected token import` error for dynamice import

### ISSUE THREAD

**Issue by dineshvgp** [airbnb/enzyme#993]
I'm using react-loadable(https://github.com/thejameskyle/react-loadable).

```
const thread = Loadable({
  loader: () => import('containers/Thread'),  //unexpected token import error
  LoadingComponent: threadLoader
})
```

**Comment by aweary** [comment]
Hey @dineshvgp! The token error is unrelated to Enzyme, as it has no part in parsing your code. You're likely using dynamic `import` without the proper Babel configuration. See https://webpack.js.org/guides/code-splitting-async/#usage-with-babel

Hope that helps!

**Comment by dineshvgp** [comment]
Thanks @aweary! I'll take a look.

**Comment by dineshvgp** [comment]
Fixed it by using this [dynamic import node plugin](https://github.com/airbnb/babel-plugin-dynamic-import-node)
