### ISSUE TITLE
Ambiguous failure message for text element

### ISSUE THREAD

**Issue by sgottfried** [airbnb/enzyme#994]
I have a test that was checking for an `h1` with some text content.  At some point, we changed the `h1` to an `h4` and this test failed.  
The problem is that the test failure message didn't give us much information and some significant time was spent tracking down the cause of the failure.

Here is the test:
```js
    it('renders', () => {
      const subject = shallow(<MyComponent />);
      expect(subject.find('h1').text()).toBe('Some text');
    });
```

The failure looked like this:
```
FAILED TESTS:
  <MyComponent />
    initial mount
      ✖ renders
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      single
      text
```

I think it was saying that it couldn't find a "single" piece of "text", but this wasn't a very helpful message.  

Perhaps something like "Expected to find \<h1> with text 'Some text'" would make this more clear?

**Comment by ljharb** [comment]
There's no way for the matcher here to know that's what you were trying to do; all you're doing is comparing strings.

You'd need a custom matcher that took "h1", 'text", and "some text" before that custom message would be possible.

You may want to look into chai and chai-enzyme; it's also possible someone has made custom matchers for jasmine/jest.
