### ISSUE TITLE
can I add an event listener to a node after rendering?

### ISSUE THREAD

**Issue by Michael-Gannon** [airbnb/enzyme#999]
I wanted to know if there was a way for me to add an event listener to a node after rendering. Sounds weird heres the rub using a contrived example

    class MyComponent extends Component {
        constructor(props) {
            super(props);
            this.handleClick = this.handleClick.bind(this);
        }

        handleClick(e) {
            if(true) { //replace this is some business-y test
                this.form.submit(); //want this to be a proper submit, taking the user away from this page
            } else {
                e.preventDefault();
                return false;
            }
        };

        render() {
            return (
                <form ref={ (form) => { this.form = form; } } >
                    <button name="click-me" onClick={ this.handleClick }>click me</button>
                </form>
            );
        };
    };

In my test I'd like to do something like this

    it('when the business-y rule is true, I click on the submit button it submits the form', (done) => {
        const component = mount(<MyComponent />);
        component.find('form').onSubmit(() => {
            done();
        })
        component.find('button').simulate('submit');
    });

The return from component.find('form') has no onSubmit function so this fails here. 

    TypeError: component.find(...).onSubmit is not a function

At this point I feel I need to implement an onSubmit prop that I pass in to support this test, but it didn't seem like too far a stretch to be able to hook into the component ad-hoc. 

Thoughts?

**Comment by ljharb** [comment]
```js
const spy = sinon.stub(component.instance().form, 'submit');
component.find('button').simulate('submit');
expect(spy).to.have.property('callCount', 0);
```
?
